<TextStyle Leading='14' Name='ChatFont' UseCachedFont='true'>
<FontCharacter Advance='3' Code='32' SourceFile='arial8_0' SourceRect='0,0,4,14'/>
<FontCharacter Advance='2' Code='33' SourceFile='arial8_0' SourceRect='4,0,7,14'/>
<FontCharacter Advance='4' Code='34' SourceFile='arial8_0' SourceRect='7,0,12,14'/>
<FontCharacter Advance='6' Code='35' SourceFile='arial8_0' SourceRect='12,0,19,14'/>
<FontCharacter Advance='6' Code='36' SourceFile='arial8_0' SourceRect='19,0,26,14'/>
<FontCharacter Advance='10' Code='37' SourceFile='arial8_0' SourceRect='26,0,37,14'/>
<FontCharacter Advance='7' Code='38' SourceFile='arial8_0' SourceRect='37,0,45,14'/>
<FontCharacter Advance='2' Code='39' SourceFile='arial8_0' SourceRect='45,0,48,14'/>
<FontCharacter Advance='4' Code='40' SourceFile='arial8_0' SourceRect='48,0,53,14'/>
<FontCharacter Advance='4' Code='41' SourceFile='arial8_0' SourceRect='53,0,58,14'/>
<FontCharacter Advance='4' Code='42' SourceFile='arial8_0' SourceRect='58,0,63,14'/>
<FontCharacter Advance='6' Code='43' SourceFile='arial8_0' SourceRect='63,0,70,14'/>
<FontCharacter Advance='3' Code='44' SourceFile='arial8_0' SourceRect='70,0,74,14'/>
<FontCharacter Advance='4' Code='45' SourceFile='arial8_0' SourceRect='74,0,79,14'/>
<FontCharacter Advance='3' Code='46' SourceFile='arial8_0' SourceRect='79,0,83,14'/>
<FontCharacter Advance='3' Code='47' SourceFile='arial8_0' SourceRect='83,0,87,14'/>
<FontCharacter Advance='6' Code='48' SourceFile='arial8_0' SourceRect='87,0,94,14'/>
<FontCharacter Advance='6' Code='49' SourceFile='arial8_0' SourceRect='94,0,101,14'/>
<FontCharacter Advance='6' Code='50' SourceFile='arial8_0' SourceRect='101,0,108,14'/>
<FontCharacter Advance='6' Code='51' SourceFile='arial8_0' SourceRect='108,0,115,14'/>
<FontCharacter Advance='6' Code='52' SourceFile='arial8_0' SourceRect='115,0,122,14'/>
<FontCharacter Advance='6' Code='53' SourceFile='arial8_0' SourceRect='0,14,7,28'/>
<FontCharacter Advance='6' Code='54' SourceFile='arial8_0' SourceRect='7,14,14,28'/>
<FontCharacter Advance='6' Code='55' SourceFile='arial8_0' SourceRect='14,14,21,28'/>
<FontCharacter Advance='6' Code='56' SourceFile='arial8_0' SourceRect='21,14,28,28'/>
<FontCharacter Advance='6' Code='57' SourceFile='arial8_0' SourceRect='28,14,35,28'/>
<FontCharacter Advance='3' Code='58' SourceFile='arial8_0' SourceRect='35,14,39,28'/>
<FontCharacter Advance='3' Code='59' SourceFile='arial8_0' SourceRect='39,14,43,28'/>
<FontCharacter Advance='6' Code='60' SourceFile='arial8_0' SourceRect='43,14,50,28'/>
<FontCharacter Advance='6' Code='61' SourceFile='arial8_0' SourceRect='50,14,57,28'/>
<FontCharacter Advance='6' Code='62' SourceFile='arial8_0' SourceRect='57,14,64,28'/>
<FontCharacter Advance='6' Code='63' SourceFile='arial8_0' SourceRect='64,14,71,28'/>
<FontCharacter Advance='11' Code='64' SourceFile='arial8_0' SourceRect='71,14,83,28'/>
<FontCharacter Advance='8' Code='65' SourceFile='arial8_0' SourceRect='83,14,92,28'/>
<FontCharacter Advance='7' Code='66' SourceFile='arial8_0' SourceRect='92,14,100,28'/>
<FontCharacter Advance='7' Code='67' SourceFile='arial8_0' SourceRect='100,14,108,28'/>
<FontCharacter Advance='7' Code='68' SourceFile='arial8_0' SourceRect='108,14,116,28'/>
<FontCharacter Advance='6' Code='69' SourceFile='arial8_0' SourceRect='116,14,123,28'/>
<FontCharacter Advance='6' Code='70' SourceFile='arial8_0' SourceRect='0,28,7,42'/>
<FontCharacter Advance='8' Code='71' SourceFile='arial8_0' SourceRect='7,28,16,42'/>
<FontCharacter Advance='7' Code='72' SourceFile='arial8_0' SourceRect='16,28,24,42'/>
<FontCharacter Advance='2' Code='73' SourceFile='arial8_0' SourceRect='24,28,27,42'/>
<FontCharacter Advance='5' Code='74' SourceFile='arial8_0' SourceRect='27,28,33,42'/>
<FontCharacter Advance='7' Code='75' SourceFile='arial8_0' SourceRect='33,28,41,42'/>
<FontCharacter Advance='6' Code='76' SourceFile='arial8_0' SourceRect='41,28,48,42'/>
<FontCharacter Advance='8' Code='77' SourceFile='arial8_0' SourceRect='48,28,57,42'/>
<FontCharacter Advance='7' Code='78' SourceFile='arial8_0' SourceRect='57,28,65,42'/>
<FontCharacter Advance='8' Code='79' SourceFile='arial8_0' SourceRect='65,28,74,42'/>
<FontCharacter Advance='6' Code='80' SourceFile='arial8_0' SourceRect='74,28,81,42'/>
<FontCharacter Advance='8' Code='81' SourceFile='arial8_0' SourceRect='81,28,90,42'/>
<FontCharacter Advance='7' Code='82' SourceFile='arial8_0' SourceRect='90,28,98,42'/>
<FontCharacter Advance='7' Code='83' SourceFile='arial8_0' SourceRect='98,28,106,42'/>
<FontCharacter Advance='6' Code='84' SourceFile='arial8_0' SourceRect='106,28,113,42'/>
<FontCharacter Advance='7' Code='85' SourceFile='arial8_0' SourceRect='113,28,121,42'/>
<FontCharacter Advance='8' Code='86' SourceFile='arial8_0' SourceRect='0,42,8,56'/>
<FontCharacter Advance='11' Code='87' SourceFile='arial8_0' SourceRect='8,42,21,56'/>
<FontCharacter Advance='7' Code='88' SourceFile='arial8_0' SourceRect='21,42,29,56'/>
<FontCharacter Advance='8' Code='89' SourceFile='arial8_0' SourceRect='29,42,38,56'/>
<FontCharacter Advance='7' Code='90' SourceFile='arial8_0' SourceRect='38,42,46,56'/>
<FontCharacter Advance='3' Code='91' SourceFile='arial8_0' SourceRect='46,42,50,56'/>
<FontCharacter Advance='3' Code='92' SourceFile='arial8_0' SourceRect='50,42,54,56'/>
<FontCharacter Advance='3' Code='93' SourceFile='arial8_0' SourceRect='54,42,58,56'/>
<FontCharacter Advance='5' Code='94' SourceFile='arial8_0' SourceRect='58,42,64,56'/>
<FontCharacter Advance='6' Code='95' SourceFile='arial8_0' SourceRect='64,42,71,56'/>
<FontCharacter Advance='4' Code='96' SourceFile='arial8_0' SourceRect='71,42,76,56'/>
<FontCharacter Advance='6' Code='97' SourceFile='arial8_0' SourceRect='76,42,83,56'/>
<FontCharacter Advance='6' Code='98' SourceFile='arial8_0' SourceRect='83,42,90,56'/>
<FontCharacter Advance='6' Code='99' SourceFile='arial8_0' SourceRect='90,42,97,56'/>
<FontCharacter Advance='6' Code='100' SourceFile='arial8_0' SourceRect='97,42,104,56'/>
<FontCharacter Advance='6' Code='101' SourceFile='arial8_0' SourceRect='104,42,111,56'/>
<FontCharacter Advance='4' Code='102' SourceFile='arial8_0' SourceRect='111,42,116,56'/>
<FontCharacter Advance='6' Code='103' SourceFile='arial8_0' SourceRect='116,42,123,56'/>
<FontCharacter Advance='6' Code='104' SourceFile='arial8_0' SourceRect='0,56,7,70'/>
<FontCharacter Advance='2' Code='105' SourceFile='arial8_0' SourceRect='7,56,9,70'/>
<FontCharacter Advance='2' Code='106' SourceFile='arial8_0' SourceRect='10,56,14,70'/>
<FontCharacter Advance='5' Code='107' SourceFile='arial8_0' SourceRect='14,56,20,70'/>
<FontCharacter Advance='2' Code='108' SourceFile='arial8_0' SourceRect='20,56,23,70'/>
<FontCharacter Advance='8' Code='109' SourceFile='arial8_0' SourceRect='23,56,32,70'/>
<FontCharacter Advance='6' Code='110' SourceFile='arial8_0' SourceRect='32,56,39,70'/>
<FontCharacter Advance='6' Code='111' SourceFile='arial8_0' SourceRect='39,56,46,70'/>
<FontCharacter Advance='6' Code='112' SourceFile='arial8_0' SourceRect='46,56,53,70'/>
<FontCharacter Advance='6' Code='113' SourceFile='arial8_0' SourceRect='53,56,60,70'/>
<FontCharacter Advance='4' Code='114' SourceFile='arial8_0' SourceRect='60,56,65,70'/>
<FontCharacter Advance='6' Code='115' SourceFile='arial8_0' SourceRect='65,56,71,70'/>
<FontCharacter Advance='3' Code='116' SourceFile='arial8_0' SourceRect='72,56,77,70'/>
<FontCharacter Advance='6' Code='117' SourceFile='arial8_0' SourceRect='77,56,84,70'/>
<FontCharacter Advance='6' Code='118' SourceFile='arial8_0' SourceRect='84,56,91,70'/>
<FontCharacter Advance='10' Code='119' SourceFile='arial8_0' SourceRect='91,56,102,70'/>
<FontCharacter Advance='6' Code='120' SourceFile='arial8_0' SourceRect='102,56,109,70'/>
<FontCharacter Advance='6' Code='121' SourceFile='arial8_0' SourceRect='109,56,116,70'/>
<FontCharacter Advance='6' Code='122' SourceFile='arial8_0' SourceRect='116,56,123,70'/>
<FontCharacter Advance='4' Code='123' SourceFile='arial8_0' SourceRect='123,56,128,70'/>
<FontCharacter Advance='2' Code='124' SourceFile='arial8_0' SourceRect='0,70,3,84'/>
<FontCharacter Advance='4' Code='125' SourceFile='arial8_0' SourceRect='3,70,8,84'/>
<FontCharacter Advance='6' Code='126' SourceFile='arial8_0' SourceRect='8,70,15,84'/>
<FontCharacter Advance='6' Code='128' SourceFile='arial8_0' SourceRect='15,70,22,84'/>
<FontCharacter Advance='8' Code='129' SourceFile='arial8_0' SourceRect='22,70,31,84'/>
<FontCharacter Advance='2' Code='130' SourceFile='arial8_0' SourceRect='31,70,34,84'/>
<FontCharacter Advance='6' Code='131' SourceFile='arial8_0' SourceRect='34,70,41,84'/>
<FontCharacter Advance='4' Code='132' SourceFile='arial8_0' SourceRect='41,70,46,84'/>
<FontCharacter Advance='11' Code='133' SourceFile='arial8_0' SourceRect='46,70,58,84'/>
<FontCharacter Advance='6' Code='134' SourceFile='arial8_0' SourceRect='58,70,65,84'/>
<FontCharacter Advance='6' Code='135' SourceFile='arial8_0' SourceRect='65,70,72,84'/>
<FontCharacter Advance='4' Code='136' SourceFile='arial8_0' SourceRect='72,70,78,84'/>
<FontCharacter Advance='11' Code='137' SourceFile='arial8_0' SourceRect='78,70,90,84'/>
<FontCharacter Advance='7' Code='138' SourceFile='arial8_0' SourceRect='90,70,98,84'/>
<FontCharacter Advance='4' Code='139' SourceFile='arial8_0' SourceRect='98,70,103,84'/>
<FontCharacter Advance='11' Code='140' SourceFile='arial8_0' SourceRect='103,70,115,84'/>
<FontCharacter Advance='8' Code='141' SourceFile='arial8_0' SourceRect='115,70,124,84'/>
<FontCharacter Advance='7' Code='142' SourceFile='arial8_0' SourceRect='0,84,8,98'/>
<FontCharacter Advance='2' Code='145' SourceFile='arial8_0' SourceRect='8,84,11,98'/>
<FontCharacter Advance='2' Code='146' SourceFile='arial8_0' SourceRect='11,84,14,98'/>
<FontCharacter Advance='4' Code='147' SourceFile='arial8_0' SourceRect='14,84,19,98'/>
<FontCharacter Advance='4' Code='148' SourceFile='arial8_0' SourceRect='19,84,24,98'/>
<FontCharacter Advance='4' Code='149' SourceFile='arial8_0' SourceRect='24,84,29,98'/>
<FontCharacter Advance='6' Code='150' SourceFile='arial8_0' SourceRect='29,84,37,98'/>
<FontCharacter Advance='11' Code='151' SourceFile='arial8_0' SourceRect='37,84,50,98'/>
<FontCharacter Advance='4' Code='152' SourceFile='arial8_0' SourceRect='50,84,55,98'/>
<FontCharacter Advance='11' Code='153' SourceFile='arial8_0' SourceRect='55,84,67,98'/>
<FontCharacter Advance='6' Code='154' SourceFile='arial8_0' SourceRect='67,84,74,98'/>
<FontCharacter Advance='4' Code='155' SourceFile='arial8_0' SourceRect='74,84,79,98'/>
<FontCharacter Advance='10' Code='156' SourceFile='arial8_0' SourceRect='79,84,90,98'/>
<FontCharacter Advance='8' Code='157' SourceFile='arial8_0' SourceRect='90,84,99,98'/>
<FontCharacter Advance='6' Code='158' SourceFile='arial8_0' SourceRect='99,84,106,98'/>
<FontCharacter Advance='8' Code='159' SourceFile='arial8_0' SourceRect='106,84,115,98'/>
<FontCharacter Advance='3' Code='160' SourceFile='arial8_0' SourceRect='115,84,119,98'/>
<FontCharacter Advance='2' Code='161' SourceFile='arial8_0' SourceRect='119,84,122,98'/>
<FontCharacter Advance='6' Code='162' SourceFile='arial8_0' SourceRect='0,98,7,112'/>
<FontCharacter Advance='6' Code='163' SourceFile='arial8_0' SourceRect='7,98,14,112'/>
<FontCharacter Advance='7' Code='164' SourceFile='arial8_0' SourceRect='14,98,22,112'/>
<FontCharacter Advance='6' Code='165' SourceFile='arial8_0' SourceRect='22,98,29,112'/>
<FontCharacter Advance='2' Code='166' SourceFile='arial8_0' SourceRect='29,98,32,112'/>
<FontCharacter Advance='6' Code='167' SourceFile='arial8_0' SourceRect='32,98,39,112'/>
<FontCharacter Advance='4' Code='168' SourceFile='arial8_0' SourceRect='39,98,44,112'/>
<FontCharacter Advance='8' Code='169' SourceFile='arial8_0' SourceRect='44,98,53,112'/>
<FontCharacter Advance='4' Code='170' SourceFile='arial8_0' SourceRect='53,98,58,112'/>
<FontCharacter Advance='6' Code='171' SourceFile='arial8_0' SourceRect='58,98,65,112'/>
<FontCharacter Advance='6' Code='172' SourceFile='arial8_0' SourceRect='65,98,72,112'/>
<FontCharacter Advance='4' Code='173' SourceFile='arial8_0' SourceRect='72,98,77,112'/>
<FontCharacter Advance='8' Code='174' SourceFile='arial8_0' SourceRect='77,98,86,112'/>
<FontCharacter Advance='6' Code='175' SourceFile='arial8_0' SourceRect='86,98,93,112'/>
<FontCharacter Advance='4' Code='176' SourceFile='arial8_0' SourceRect='93,98,98,112'/>
<FontCharacter Advance='6' Code='177' SourceFile='arial8_0' SourceRect='98,98,105,112'/>
<FontCharacter Advance='4' Code='178' SourceFile='arial8_0' SourceRect='105,98,110,112'/>
<FontCharacter Advance='4' Code='179' SourceFile='arial8_0' SourceRect='110,98,115,112'/>
<FontCharacter Advance='4' Code='180' SourceFile='arial8_0' SourceRect='115,98,120,112'/>
<FontCharacter Advance='6' Code='181' SourceFile='arial8_0' SourceRect='120,98,127,112'/>
<FontCharacter Advance='6' Code='182' SourceFile='arial8_0' SourceRect='0,112,7,126'/>
<FontCharacter Advance='3' Code='183' SourceFile='arial8_0' SourceRect='7,112,11,126'/>
<FontCharacter Advance='4' Code='184' SourceFile='arial8_0' SourceRect='11,112,16,126'/>
<FontCharacter Advance='4' Code='185' SourceFile='arial8_0' SourceRect='16,112,21,126'/>
<FontCharacter Advance='5' Code='186' SourceFile='arial8_0' SourceRect='21,112,27,126'/>
<FontCharacter Advance='6' Code='187' SourceFile='arial8_0' SourceRect='27,112,34,126'/>
<FontCharacter Advance='9' Code='188' SourceFile='arial8_0' SourceRect='34,112,44,126'/>
<FontCharacter Advance='10' Code='189' SourceFile='arial8_0' SourceRect='44,112,55,126'/>
<FontCharacter Advance='10' Code='190' SourceFile='arial8_0' SourceRect='55,112,66,126'/>
<FontCharacter Advance='6' Code='191' SourceFile='arial8_0' SourceRect='66,112,73,126'/>
<FontCharacter Advance='8' Code='192' SourceFile='arial8_0' SourceRect='73,112,82,126'/>
<FontCharacter Advance='8' Code='193' SourceFile='arial8_0' SourceRect='82,112,91,126'/>
<FontCharacter Advance='8' Code='194' SourceFile='arial8_0' SourceRect='91,112,100,126'/>
<FontCharacter Advance='8' Code='195' SourceFile='arial8_0' SourceRect='100,112,109,126'/>
<FontCharacter Advance='8' Code='196' SourceFile='arial8_0' SourceRect='109,112,118,126'/>
<FontCharacter Advance='8' Code='197' SourceFile='arial8_0' SourceRect='118,112,127,126'/>
<FontCharacter Advance='11' Code='198' SourceFile='arial8_1' SourceRect='0,0,13,14'/>
<FontCharacter Advance='7' Code='199' SourceFile='arial8_1' SourceRect='13,0,21,14'/>
<FontCharacter Advance='6' Code='200' SourceFile='arial8_1' SourceRect='21,0,28,14'/>
<FontCharacter Advance='6' Code='201' SourceFile='arial8_1' SourceRect='28,0,35,14'/>
<FontCharacter Advance='6' Code='202' SourceFile='arial8_1' SourceRect='35,0,42,14'/>
<FontCharacter Advance='6' Code='203' SourceFile='arial8_1' SourceRect='42,0,49,14'/>
<FontCharacter Advance='2' Code='204' SourceFile='arial8_1' SourceRect='49,0,53,14'/>
<FontCharacter Advance='2' Code='205' SourceFile='arial8_1' SourceRect='53,0,56,14'/>
<FontCharacter Advance='2' Code='206' SourceFile='arial8_1' SourceRect='56,0,62,14'/>
<FontCharacter Advance='2' Code='207' SourceFile='arial8_1' SourceRect='62,0,66,14'/>
<FontCharacter Advance='8' Code='208' SourceFile='arial8_1' SourceRect='66,0,75,14'/>
<FontCharacter Advance='7' Code='209' SourceFile='arial8_1' SourceRect='75,0,83,14'/>
<FontCharacter Advance='8' Code='210' SourceFile='arial8_1' SourceRect='83,0,92,14'/>
<FontCharacter Advance='8' Code='211' SourceFile='arial8_1' SourceRect='92,0,101,14'/>
<FontCharacter Advance='8' Code='212' SourceFile='arial8_1' SourceRect='101,0,110,14'/>
<FontCharacter Advance='8' Code='213' SourceFile='arial8_1' SourceRect='110,0,119,14'/>
<FontCharacter Advance='8' Code='214' SourceFile='arial8_1' SourceRect='119,0,128,14'/>
<FontCharacter Advance='6' Code='215' SourceFile='arial8_1' SourceRect='0,14,7,28'/>
<FontCharacter Advance='8' Code='216' SourceFile='arial8_1' SourceRect='7,14,16,28'/>
<FontCharacter Advance='7' Code='217' SourceFile='arial8_1' SourceRect='16,14,24,28'/>
<FontCharacter Advance='7' Code='218' SourceFile='arial8_1' SourceRect='24,14,32,28'/>
<FontCharacter Advance='7' Code='219' SourceFile='arial8_1' SourceRect='32,14,40,28'/>
<FontCharacter Advance='7' Code='220' SourceFile='arial8_1' SourceRect='40,14,48,28'/>
<FontCharacter Advance='8' Code='221' SourceFile='arial8_1' SourceRect='48,14,57,28'/>
<FontCharacter Advance='7' Code='222' SourceFile='arial8_1' SourceRect='57,14,65,28'/>
<FontCharacter Advance='7' Code='223' SourceFile='arial8_1' SourceRect='65,14,73,28'/>
<FontCharacter Advance='6' Code='224' SourceFile='arial8_1' SourceRect='73,14,80,28'/>
<FontCharacter Advance='6' Code='225' SourceFile='arial8_1' SourceRect='80,14,87,28'/>
<FontCharacter Advance='6' Code='226' SourceFile='arial8_1' SourceRect='87,14,94,28'/>
<FontCharacter Advance='6' Code='227' SourceFile='arial8_1' SourceRect='94,14,101,28'/>
<FontCharacter Advance='6' Code='228' SourceFile='arial8_1' SourceRect='101,14,108,28'/>
<FontCharacter Advance='6' Code='229' SourceFile='arial8_1' SourceRect='108,14,115,28'/>
<FontCharacter Advance='10' Code='230' SourceFile='arial8_1' SourceRect='115,14,126,28'/>
<FontCharacter Advance='6' Code='231' SourceFile='arial8_1' SourceRect='0,28,7,42'/>
<FontCharacter Advance='6' Code='232' SourceFile='arial8_1' SourceRect='7,28,14,42'/>
<FontCharacter Advance='6' Code='233' SourceFile='arial8_1' SourceRect='14,28,21,42'/>
<FontCharacter Advance='6' Code='234' SourceFile='arial8_1' SourceRect='21,28,28,42'/>
<FontCharacter Advance='6' Code='235' SourceFile='arial8_1' SourceRect='28,28,35,42'/>
<FontCharacter Advance='2' Code='236' SourceFile='arial8_1' SourceRect='35,28,39,42'/>
<FontCharacter Advance='2' Code='237' SourceFile='arial8_1' SourceRect='39,28,42,42'/>
<FontCharacter Advance='2' Code='238' SourceFile='arial8_1' SourceRect='42,28,48,42'/>
<FontCharacter Advance='2' Code='239' SourceFile='arial8_1' SourceRect='48,28,52,42'/>
<FontCharacter Advance='6' Code='240' SourceFile='arial8_1' SourceRect='52,28,59,42'/>
<FontCharacter Advance='6' Code='241' SourceFile='arial8_1' SourceRect='59,28,66,42'/>
<FontCharacter Advance='6' Code='242' SourceFile='arial8_1' SourceRect='66,28,73,42'/>
<FontCharacter Advance='6' Code='243' SourceFile='arial8_1' SourceRect='73,28,80,42'/>
<FontCharacter Advance='6' Code='244' SourceFile='arial8_1' SourceRect='80,28,87,42'/>
<FontCharacter Advance='6' Code='245' SourceFile='arial8_1' SourceRect='87,28,94,42'/>
<FontCharacter Advance='6' Code='246' SourceFile='arial8_1' SourceRect='94,28,101,42'/>
<FontCharacter Advance='6' Code='247' SourceFile='arial8_1' SourceRect='101,28,108,42'/>
<FontCharacter Advance='6' Code='248' SourceFile='arial8_1' SourceRect='108,28,115,42'/>
<FontCharacter Advance='6' Code='249' SourceFile='arial8_1' SourceRect='115,28,122,42'/>
<FontCharacter Advance='6' Code='250' SourceFile='arial8_1' SourceRect='0,42,7,56'/>
<FontCharacter Advance='6' Code='251' SourceFile='arial8_1' SourceRect='7,42,14,56'/>
<FontCharacter Advance='6' Code='252' SourceFile='arial8_1' SourceRect='14,42,21,56'/>
<FontCharacter Advance='6' Code='253' SourceFile='arial8_1' SourceRect='21,42,28,56'/>
<FontCharacter Advance='6' Code='254' SourceFile='arial8_1' SourceRect='28,42,35,56'/>
<FontCharacter Advance='6' Code='255' SourceFile='arial8_1' SourceRect='35,42,42,56'/>
<FontCharacter Advance='24' Code='57345' Name='ilc9' SourceFile='ui_kill_echo_amp_magscatter' SourceRect='0,0,24,16'/>
<FontCharacter Advance='22' Code='57346' Name='isp' SourceFile='ui_kill_echo_amp_magscatter' SourceRect='0,16,22,32'/>
<FontCharacter Advance='31' Code='57347' Name='ams' SourceFile='ui_kill_echo_ams_sunder_stealthquad_basilisk' SourceRect='0,0,31,16'/>
<FontCharacter Advance='34' Code='57348' Name='apc' SourceFile='ui_kill_echo_ams_sunder_stealthquad_basilisk' SourceRect='0,16,34,32'/>
<FontCharacter Advance='33' Code='57349' Name='quadstealth' SourceFile='ui_kill_echo_ams_sunder_stealthquad_basilisk' SourceRect='0,32,33,48'/>
<FontCharacter Advance='36' Code='57350' Name='quadassault' SourceFile='ui_kill_echo_ams_sunder_stealthquad_basilisk' SourceRect='0,48,36,64'/>
<FontCharacter Advance='29' Code='57351' Name='beamer' SourceFile='ui_kill_echo_beamer_magcutter_forceblade_chainblade' SourceRect='0,0,29,16'/>
<FontCharacter Advance='46' Code='57352' Name='magcutter' SourceFile='ui_kill_echo_beamer_magcutter_forceblade_chainblade' SourceRect='0,16,46,32'/>
<FontCharacter Advance='44' Code='57353' Name='forceblade' SourceFile='ui_kill_echo_beamer_magcutter_forceblade_chainblade' SourceRect='0,32,44,48'/>
<FontCharacter Advance='59' Code='57354' Name='chainblade' SourceFile='ui_kill_echo_beamer_magcutter_forceblade_chainblade' SourceRect='0,48,59,64'/>
<FontCharacter Advance='56' Code='57355' Name='bolt_driver' SourceFile='ui_kill_echo_bolt_hunter_striker_lancer' SourceRect='0,0,56,16'/>
<FontCharacter Advance='59' Code='57356' Name='hunterseeker' SourceFile='ui_kill_echo_bolt_hunter_striker_lancer' SourceRect='0,16,59,32'/>
<FontCharacter Advance='43' Code='57357' Name='striker' SourceFile='ui_kill_echo_bolt_hunter_striker_lancer' SourceRect='0,32,43,48'/>
<FontCharacter Advance='53' Code='57358' Name='lancer' SourceFile='ui_kill_echo_bolt_hunter_striker_lancer' SourceRect='0,48,53,64'/>
<FontCharacter Advance='16' Code='57359' Name='boomer' SourceFile='ui_kill_echo_boomerhe_fragrenade' SourceRect='0,0,16,16'/>
<FontCharacter Advance='13' Code='57360' Name='frag_grenade' SourceFile='ui_kill_echo_boomerhe_fragrenade' SourceRect='0,16,13,32'/>
<FontCharacter Advance='49' Code='57362' Name='r_shotgun' SourceFile='ui_kill_echo_dragon_jackhammer_cycler_minichaingun' SourceRect='0,16,49,32'/>
<FontCharacter Advance='52' Code='57363' Name='cycler' SourceFile='ui_kill_echo_dragon_jackhammer_cycler_minichaingun' SourceRect='0,32,52,48'/>
<FontCharacter Advance='48' Code='57364' Name='mini_chaingun' SourceFile='ui_kill_echo_dragon_jackhammer_cycler_minichaingun' SourceRect='0,48,48,64'/>
<FontCharacter Advance='17' Code='57365' Name='he_mine' SourceFile='ui_kill_echo_hemine_magno' SourceRect='0,0,17,16'/>
<FontCharacter Advance='16' Code='57366' Name='magno_mine' SourceFile='ui_kill_echo_hemine_magno' SourceRect='0,16,16,32'/>
<FontCharacter Advance='57' Code='57367' Name='lasher' SourceFile='ui_kill_echo_lasher_pulsar_thumper_guass' SourceRect='0,0,57,16'/>
<FontCharacter Advance='44' Code='57368' Name='pulsar' SourceFile='ui_kill_echo_lasher_pulsar_thumper_guass' SourceRect='0,16,44,32'/>
<FontCharacter Advance='37' Code='57369' Name='thumper' SourceFile='ui_kill_echo_lasher_pulsar_thumper_guass' SourceRect='0,32,37,48'/>
<FontCharacter Advance='44' Code='57370' Name='gauss' SourceFile='ui_kill_echo_lasher_pulsar_thumper_guass' SourceRect='0,48,44,64'/>
<FontCharacter Advance='44' Code='57371' Name='lightning' SourceFile='ui_kill_echo_lightning_galaxy_prowler_vanguard' SourceRect='0,0,44,16'/>
<FontCharacter Advance='47' Code='57451' Name='galaxy_gunship' SourceFile='ui_kill_echo_lightning_galaxy_prowler_vanguard' SourceRect='0,16,47,32'/>
<FontCharacter Advance='36' Code='57373' Name='prowler' SourceFile='ui_kill_echo_lightning_galaxy_prowler_vanguard' SourceRect='0,32,36,48'/>
<FontCharacter Advance='48' Code='57374' Name='vanguard' SourceFile='ui_kill_echo_lightning_galaxy_prowler_vanguard' SourceRect='0,48,48,64'/>
<FontCharacter Advance='28' Code='57375' Name='threemanheavybuggy' SourceFile='ui_kill_echo_marauder_deliverer_enforcer_harraser' SourceRect='0,0,28,16'/>
<FontCharacter Advance='34' Code='57376' Name='mediumtransport' SourceFile='ui_kill_echo_marauder_deliverer_enforcer_harraser' SourceRect='0,16,34,32'/>
<FontCharacter Advance='43' Code='57377' Name='twomanheavybuggy' SourceFile='ui_kill_echo_marauder_deliverer_enforcer_harraser' SourceRect='0,32,43,48'/>
<FontCharacter Advance='46' Code='57378' Name='two_man_assault_buggy' SourceFile='ui_kill_echo_marauder_deliverer_enforcer_harraser' SourceRect='0,48,46,64'/>
<FontCharacter Advance='10' Code='57379' Name='minesweeper' SourceFile='ui_kill_echo_minesweeper_plasma' SourceRect='0,0,10,16'/>
<FontCharacter Advance='9' Code='57380' Name='plasma_grenade' SourceFile='ui_kill_echo_minesweeper_plasma' SourceRect='0,16,9,32'/>
<FontCharacter Advance='33' Code='57381' Name='repeater' SourceFile='ui_kill_echo_repeater_punisher_rocklet_suppressor' SourceRect='0,0,33,16'/>
<FontCharacter Advance='39' Code='57382' Name='punisher' SourceFile='ui_kill_echo_repeater_punisher_rocklet_suppressor' SourceRect='0,16,39,32'/>
<FontCharacter Advance='31' Code='57383' Name='rocklet' SourceFile='ui_kill_echo_repeater_punisher_rocklet_suppressor' SourceRect='0,32,31,48'/>
<FontCharacter Advance='37' Code='57384' Name='suppressor' SourceFile='ui_kill_echo_repeater_punisher_rocklet_suppressor' SourceRect='0,48,37,64'/>
<FontCharacter Advance='54' Code='57385' Name='twomanhoverbuggy' SourceFile='ui_kill_echo_thresher_magrider_reaver_mosquito' SourceRect='0,0,54,16'/>
<FontCharacter Advance='53' Code='57386' Name='magrider' SourceFile='ui_kill_echo_thresher_magrider_reaver_mosquito' SourceRect='0,16,53,32'/>
<FontCharacter Advance='53' Code='57387' Name='lightgunship' SourceFile='ui_kill_echo_thresher_magrider_reaver_mosquito' SourceRect='0,32,53,48'/>
<FontCharacter Advance='46' Code='57388' Name='mosquito' SourceFile='ui_kill_echo_thresher_magrider_reaver_mosquito' SourceRect='0,48,46,64'/>
<FontCharacter Advance='19' Code='57389' Name='trhev_burster' SourceFile='ui_kill_echo_trhev_nchev' SourceRect='0,0,19,16'/>
<FontCharacter Advance='19' Code='57390' Name='trhev_dualcycler' SourceFile='ui_kill_echo_trhev_nchev' SourceRect='0,0,19,16'/>
<FontCharacter Advance='19' Code='57391' Name='trhev_pounder' SourceFile='ui_kill_echo_trhev_nchev' SourceRect='0,0,19,16'/>
<FontCharacter Advance='17' Code='57392' Name='nchev_falcon' SourceFile='ui_kill_echo_trhev_nchev' SourceRect='0,16,17,32'/>
<FontCharacter Advance='17' Code='57393' Name='nchev_scattercannon' SourceFile='ui_kill_echo_trhev_nchev' SourceRect='0,16,17,32'/>
<FontCharacter Advance='17' Code='57394' Name='nchev_sparrow' SourceFile='ui_kill_echo_trhev_nchev' SourceRect='0,16,17,32'/>
<FontCharacter Advance='18' Code='57395' Name='vshev_comet' SourceFile='ui_kill_echo_vshev_suicide' SourceRect='0,0,18,16'/>
<FontCharacter Advance='18' Code='57396' Name='vshev_starfire' SourceFile='ui_kill_echo_vshev_suicide' SourceRect='0,0,18,16'/>
<FontCharacter Advance='18' Code='57397' Name='vshev_quasar' SourceFile='ui_kill_echo_vshev_suicide' SourceRect='0,0,18,16'/>
<FontCharacter Advance='27' Code='57398' Name='suicide' SourceFile='ui_kill_echo_vshev_suicide' SourceRect='0,16,27,32'/>
<FontCharacter Advance='64' Code='57399' Name='flechette' SourceFile='ui_kill_echo_flechette_phoenix_spitfire' SourceRect='0,0,64,14'/>
<FontCharacter Advance='49' Code='57400' Name='phoenix' SourceFile='ui_kill_echo_flechette_phoenix_spitfire' SourceRect='0,16,49,32'/>
<FontCharacter Advance='14' Code='57401' Name='spitfire_turret' SourceFile='ui_kill_echo_flechette_phoenix_spitfire' SourceRect='0,33,14,49'/>
<FontCharacter Advance='30' Code='57402' Name='ace' SourceFile='ui_smlinv_ace_00' SourceRect='0,0,30,16'/>
<FontCharacter Advance='24' Code='57403' Name='bank' SourceFile='ui_smlinv_bank_00' SourceRect='0,0,24,16'/>
<FontCharacter Advance='37' Code='57404' Name='boomer' SourceFile='ui_smlinv_boomer_trigger_00' SourceRect='0,0,37,16'/>
<FontCharacter Advance='56' Code='57405' Name='jammer_grenade' SourceFile='ui_smlinv_jammer_grenade_00' SourceRect='0,0,56,16'/>
<FontCharacter Advance='21' Code='57406' Name='medicalapplicator' SourceFile='ui_smlinv_medical_applicator_00' SourceRect='0,0,21,16'/>
<FontCharacter Advance='9' Code='57407' Name='mine_sweeper' SourceFile='ui_smlinv_mine_sweeper_00' SourceRect='0,0,9,16'/>
<FontCharacter Advance='33' Code='57408' Name='nano_dispenser' SourceFile='ui_smlinv_nano_dispenser_00' SourceRect='0,0,33,16'/>
<FontCharacter Advance='19' Code='57409' Name='remote_electronics_kit' SourceFile='ui_smlinv_remote_electronics_kit_00' SourceRect='0,0,19,16'/>
<FontCharacter Advance='36' Code='57410' Name='ant' SourceFile='ui_kill_echo_ant_uplink_turret_00' SourceRect='0,0,36,16'/>
<FontCharacter Advance='9' Code='57411' Name='command_detonater' SourceFile='ui_kill_echo_ant_uplink_turret_00' SourceRect='0,17,9,33'/>
<FontCharacter Advance='45' Code='57412' Name='liberator' SourceFile='ui_kill_echo_liberator_skyguard_00' SourceRect='0,0,45,16'/>
<FontCharacter Advance='40' Code='57413' Name='skyguard' SourceFile='ui_kill_echo_liberator_skyguard_00' SourceRect='0,17,40,33'/>
<FontCharacter Advance='48' Code='57414' Name='flail' SourceFile='ui_kill_echo_expansion_00' SourceRect='0,0,48,16'/>
<FontCharacter Advance='64' Code='57415' Name='router' SourceFile='ui_kill_echo_expansion_00' SourceRect='0,34,64,50'/>
<FontCharacter Advance='26' Code='57416' Name='switchblade' SourceFile='ui_kill_echo_expansion_00' SourceRect='49,0,75,16'/>
<FontCharacter Advance='14' Code='57417' Name='vanu_sentry_turret' SourceFile='ui_kill_echo_expansion_00' SourceRect='60,17,74,33'/>
<FontCharacter Advance='53' Code='57418' Name='maelstrom' SourceFile='ui_kill_echo_expansion_00' SourceRect='30,51,83,67'/>
<FontCharacter Advance='29' Code='57419' Name='spiker' SourceFile='ui_kill_echo_expansion_00' SourceRect='0,51,29,67'/>
<FontCharacter Advance='59' Code='57420' Name='radiator' SourceFile='ui_kill_echo_expansion_00' SourceRect='0,17,59,33'/>
<FontCharacter Advance='22' Code='57421' Name='manned_turret' SourceFile='ui_kill_echo_ant_uplink_turret_00' SourceRect='0,34,22,50'/>
<FontCharacter Advance='23' Code='57422' Name='router_telepad_deployable' SourceFile='ui_kill_echo_expansion_00' SourceRect='0,68,23,84'/>
<FontCharacter Advance='23' Code='57423' Name='lodestar' SourceFile='ui_kill_echo_expansion_00' SourceRect='67,33,90,50'/>
<FontCharacter Advance='36' Code='57424' Name='fury' SourceFile='ui_kill_echo_ams_sunder_stealthquad_basilisk' SourceRect='0,48,36,64'/>
<FontCharacter Advance='34' Code='57425' Name='aurora' SourceFile='ui_kill_echo_marauder_deliverer_enforcer_harraser' SourceRect='0,16,34,32'/>
<FontCharacter Advance='34' Code='57426' Name='battlewagon' SourceFile='ui_kill_echo_marauder_deliverer_enforcer_harraser' SourceRect='0,16,34,32'/>
<FontCharacter Advance='34' Code='57427' Name='thunderer' SourceFile='ui_kill_echo_marauder_deliverer_enforcer_harraser' SourceRect='0,16,34,32'/>
<FontCharacter Advance='52' Code='57428' Name='fluxpod' SourceFile='ui_kill_echo_expansion_00' SourceRect='0,84,52,96'/>
<FontCharacter Advance='55' Code='57429' Name='gauss_cannon' SourceFile='ui_kill_echo_expansion_00' SourceRect='41,97,96,112'/>
<FontCharacter Advance='36' Code='57430' Name='20mm_cannon_deliverer' SourceFile='ui_kill_echo_expansion_00' SourceRect='0,101,36,112'/>
<FontCharacter Advance='39' Code='57431' Name='hellfire' SourceFile='ui_kill_echo_expansion_00' SourceRect='56,76,95,94'/>
<FontCharacter Advance='2' Code='8217' SourceFile='arial8_0' SourceRect='45,0,48,14'/>
<FontCharacter Advance='16' Code='57432' Name='peregrine' SourceFile='ui_kill_echo_ant_uplink_turret_00' SourceRect='46,0,64,19'/>
<FontCharacter Advance='16' Code='57433' Name='peregrine_flight' SourceFile='ui_kill_echo_ant_uplink_turret_00' SourceRect='46,0,64,19'/>
<FontCharacter Advance='16' Code='57434' Name='peregrine_gunner' SourceFile='ui_kill_echo_ant_uplink_turret_00' SourceRect='46,0,64,19'/>
<FontCharacter Advance='18' Code='57435' Name='colossus' SourceFile='ui_kill_echo_ant_uplink_turret_00' SourceRect='22,18,42,34'/>
<FontCharacter Advance='18' Code='57436' Name='colossus_flight' SourceFile='ui_kill_echo_ant_uplink_turret_00' SourceRect='22,18,42,34'/>
<FontCharacter Advance='18' Code='57437' Name='colossus_gunner' SourceFile='ui_kill_echo_ant_uplink_turret_00' SourceRect='22,18,42,34'/>
<FontCharacter Advance='11' Code='57438' Name='aphelion' SourceFile='ui_kill_echo_ant_uplink_turret_00' SourceRect='19,47,28,63'/>
<FontCharacter Advance='11' Code='57439' Name='aphelion_flight' SourceFile='ui_kill_echo_ant_uplink_turret_00' SourceRect='19,47,28,63'/>
<FontCharacter Advance='11' Code='57440' Name='aphelion_gunner' SourceFile='ui_kill_echo_ant_uplink_turret_00' SourceRect='19,47,28,63'/>
<FontCharacter Advance='38' Code='57441' Name='heavy_sniper' SourceFile='ui_kill_echo_ant_uplink' SourceRect='26,55,64,64'/>
<FontCharacter Advance='2' Code='700' SourceFile='arial8_0' SourceRect='45,0,48,14'/>
<FontCharacter Advance='45' Code='57442' Name='vulture' SourceFile='ui_kill_echo_liberator_skyguard_00' SourceRect='0,0,45,16'/>
<FontCharacter Advance='46' Code='57443' Name='wasp' SourceFile='ui_kill_echo_thresher_magrider_reaver_mosquito' SourceRect='0,48,46,64'/>
<FontCharacter Advance='16' Code='57444' Name='anniversary_gun' SourceFile='ui_kill_echo_flamer_oicw_anniv_pistols' SourceRect='0,32,16,48'/>
<FontCharacter Advance='16' Code='57445' Name='anniversary_guna' SourceFile='ui_kill_echo_flamer_oicw_anniv_pistols' SourceRect='0,48,16,64'/>
<FontCharacter Advance='16' Code='57446' Name='anniversary_gunb' SourceFile='ui_kill_echo_flamer_oicw_anniv_pistols' SourceRect='16,48,32,64'/>
<FontCharacter Advance='60' Code='57447' Name='oicw' SourceFile='ui_kill_echo_flamer_oicw_anniv_pistols' SourceRect='0,16,60,32'/>
<FontCharacter Advance='59' Code='57448' Name='flamethrower' SourceFile='ui_kill_echo_flamer_oicw_anniv_pistols' SourceRect='0,0,59,16'/>
<FontCharacter Advance='41' Code='57449' Name='phantasm' SourceFile='ui_kill_echo_flamer_oicw_anniv_pistols' SourceRect='23,32,64,47'/>
<FontCharacter Advance='28' Code='57450' Name='katana' SourceFile='ui_kill_echo_flamer_oicw_anniv_pistols' SourceRect='34,49,62,62'/>
<FontCharacter Advance='2' Code='65425' SourceFile='arial8_0' SourceRect='45,0,48,14'/>
<FontCharacter Advance='2' Code='65426' SourceFile='arial8_0' SourceRect='45,0,48,14'/>
</TextStyle>
