<TextStyle Leading='14' Name='ChatFont'>
<FontCharacter Advance='3' Code='32' SourceFile='arial14_0' SourceRect='1,1,5,15'/>
<FontCharacter Advance='2' Code='33' SourceFile='arial14_0' SourceRect='7,1,10,15'/>
<FontCharacter Advance='4' Code='34' SourceFile='arial14_0' SourceRect='12,1,17,15'/>
<FontCharacter Advance='6' Code='35' SourceFile='arial14_0' SourceRect='19,1,26,15'/>
<FontCharacter Advance='6' Code='36' SourceFile='arial14_0' SourceRect='28,1,35,15'/>
<FontCharacter Advance='10' Code='37' SourceFile='arial14_0' SourceRect='37,1,48,15'/>
<FontCharacter Advance='7' Code='38' SourceFile='arial14_0' SourceRect='50,1,58,15'/>
<FontCharacter Advance='2' Code='39' SourceFile='arial14_0' SourceRect='60,1,63,15'/>
<FontCharacter Advance='4' Code='40' SourceFile='arial14_0' SourceRect='65,1,70,15'/>
<FontCharacter Advance='4' Code='41' SourceFile='arial14_0' SourceRect='72,1,77,15'/>
<FontCharacter Advance='4' Code='42' SourceFile='arial14_0' SourceRect='79,1,84,15'/>
<FontCharacter Advance='6' Code='43' SourceFile='arial14_0' SourceRect='86,1,93,15'/>
<FontCharacter Advance='3' Code='44' SourceFile='arial14_0' SourceRect='95,1,99,15'/>
<FontCharacter Advance='4' Code='45' SourceFile='arial14_0' SourceRect='101,1,106,15'/>
<FontCharacter Advance='3' Code='46' SourceFile='arial14_0' SourceRect='108,1,112,15'/>
<FontCharacter Advance='3' Code='47' SourceFile='arial14_0' SourceRect='114,1,118,15'/>
<FontCharacter Advance='6' Code='48' SourceFile='arial14_0' SourceRect='120,1,127,15'/>
<FontCharacter Advance='6' Code='49' SourceFile='arial14_0' SourceRect='1,17,8,31'/>
<FontCharacter Advance='6' Code='50' SourceFile='arial14_0' SourceRect='10,17,17,31'/>
<FontCharacter Advance='6' Code='51' SourceFile='arial14_0' SourceRect='19,17,26,31'/>
<FontCharacter Advance='6' Code='52' SourceFile='arial14_0' SourceRect='28,17,35,31'/>
<FontCharacter Advance='6' Code='53' SourceFile='arial14_0' SourceRect='37,17,44,31'/>
<FontCharacter Advance='6' Code='54' SourceFile='arial14_0' SourceRect='46,17,53,31'/>
<FontCharacter Advance='6' Code='55' SourceFile='arial14_0' SourceRect='55,17,62,31'/>
<FontCharacter Advance='6' Code='56' SourceFile='arial14_0' SourceRect='64,17,71,31'/>
<FontCharacter Advance='6' Code='57' SourceFile='arial14_0' SourceRect='73,17,80,31'/>
<FontCharacter Advance='3' Code='58' SourceFile='arial14_0' SourceRect='82,17,86,31'/>
<FontCharacter Advance='3' Code='59' SourceFile='arial14_0' SourceRect='88,17,92,31'/>
<FontCharacter Advance='6' Code='60' SourceFile='arial14_0' SourceRect='94,17,101,31'/>
<FontCharacter Advance='6' Code='61' SourceFile='arial14_0' SourceRect='103,17,110,31'/>
<FontCharacter Advance='6' Code='62' SourceFile='arial14_0' SourceRect='112,17,119,31'/>
<FontCharacter Advance='6' Code='63' SourceFile='arial14_0' SourceRect='1,33,8,47'/>
<FontCharacter Advance='11' Code='64' SourceFile='arial14_0' SourceRect='10,33,22,47'/>
<FontCharacter Advance='8' Code='65' SourceFile='arial14_0' SourceRect='24,33,33,47'/>
<FontCharacter Advance='7' Code='66' SourceFile='arial14_0' SourceRect='35,33,43,47'/>
<FontCharacter Advance='7' Code='67' SourceFile='arial14_0' SourceRect='45,33,53,47'/>
<FontCharacter Advance='7' Code='68' SourceFile='arial14_0' SourceRect='55,33,63,47'/>
<FontCharacter Advance='6' Code='69' SourceFile='arial14_0' SourceRect='65,33,72,47'/>
<FontCharacter Advance='6' Code='70' SourceFile='arial14_0' SourceRect='74,33,81,47'/>
<FontCharacter Advance='8' Code='71' SourceFile='arial14_0' SourceRect='83,33,92,47'/>
<FontCharacter Advance='7' Code='72' SourceFile='arial14_0' SourceRect='94,33,102,47'/>
<FontCharacter Advance='2' Code='73' SourceFile='arial14_0' SourceRect='104,33,107,47'/>
<FontCharacter Advance='5' Code='74' SourceFile='arial14_0' SourceRect='109,33,115,47'/>
<FontCharacter Advance='7' Code='75' SourceFile='arial14_0' SourceRect='117,33,125,47'/>
<FontCharacter Advance='6' Code='76' SourceFile='arial14_0' SourceRect='1,49,8,63'/>
<FontCharacter Advance='8' Code='77' SourceFile='arial14_0' SourceRect='10,49,19,63'/>
<FontCharacter Advance='7' Code='78' SourceFile='arial14_0' SourceRect='21,49,29,63'/>
<FontCharacter Advance='8' Code='79' SourceFile='arial14_0' SourceRect='31,49,40,63'/>
<FontCharacter Advance='6' Code='80' SourceFile='arial14_0' SourceRect='42,49,49,63'/>
<FontCharacter Advance='8' Code='81' SourceFile='arial14_0' SourceRect='51,49,60,63'/>
<FontCharacter Advance='7' Code='82' SourceFile='arial14_0' SourceRect='62,49,70,63'/>
<FontCharacter Advance='7' Code='83' SourceFile='arial14_0' SourceRect='72,49,80,63'/>
<FontCharacter Advance='6' Code='84' SourceFile='arial14_0' SourceRect='82,49,89,63'/>
<FontCharacter Advance='7' Code='85' SourceFile='arial14_0' SourceRect='91,49,99,63'/>
<FontCharacter Advance='8' Code='86' SourceFile='arial14_0' SourceRect='101,49,110,63'/>
<FontCharacter Advance='10' Code='87' SourceFile='arial14_0' SourceRect='112,49,124,63'/>
<FontCharacter Advance='7' Code='88' SourceFile='arial14_0' SourceRect='1,65,9,79'/>
<FontCharacter Advance='8' Code='89' SourceFile='arial14_0' SourceRect='11,65,20,79'/>
<FontCharacter Advance='7' Code='90' SourceFile='arial14_0' SourceRect='22,65,30,79'/>
<FontCharacter Advance='3' Code='91' SourceFile='arial14_0' SourceRect='32,65,36,79'/>
<FontCharacter Advance='3' Code='92' SourceFile='arial14_0' SourceRect='38,65,42,79'/>
<FontCharacter Advance='3' Code='93' SourceFile='arial14_0' SourceRect='44,65,48,79'/>
<FontCharacter Advance='5' Code='94' SourceFile='arial14_0' SourceRect='50,65,56,79'/>
<FontCharacter Advance='6' Code='95' SourceFile='arial14_0' SourceRect='58,65,65,79'/>
<FontCharacter Advance='4' Code='96' SourceFile='arial14_0' SourceRect='67,65,72,79'/>
<FontCharacter Advance='6' Code='97' SourceFile='arial14_0' SourceRect='74,65,81,79'/>
<FontCharacter Advance='6' Code='98' SourceFile='arial14_0' SourceRect='83,65,90,79'/>
<FontCharacter Advance='6' Code='99' SourceFile='arial14_0' SourceRect='92,65,99,79'/>
<FontCharacter Advance='6' Code='100' SourceFile='arial14_0' SourceRect='101,65,108,79'/>
<FontCharacter Advance='6' Code='101' SourceFile='arial14_0' SourceRect='110,65,117,79'/>
<FontCharacter Advance='4' Code='102' SourceFile='arial14_0' SourceRect='119,65,124,79'/>
<FontCharacter Advance='6' Code='103' SourceFile='arial14_0' SourceRect='1,81,8,95'/>
<FontCharacter Advance='6' Code='104' SourceFile='arial14_0' SourceRect='10,81,17,95'/>
<FontCharacter Advance='2' Code='105' SourceFile='arial14_0' SourceRect='19,81,22,95'/>
<FontCharacter Advance='2' Code='106' SourceFile='arial14_0' SourceRect='24,81,28,95'/>
<FontCharacter Advance='5' Code='107' SourceFile='arial14_0' SourceRect='30,81,36,95'/>
<FontCharacter Advance='2' Code='108' SourceFile='arial14_0' SourceRect='38,81,41,95'/>
<FontCharacter Advance='8' Code='109' SourceFile='arial14_0' SourceRect='43,81,52,95'/>
<FontCharacter Advance='6' Code='110' SourceFile='arial14_0' SourceRect='54,81,61,95'/>
<FontCharacter Advance='6' Code='111' SourceFile='arial14_0' SourceRect='63,81,70,95'/>
<FontCharacter Advance='6' Code='112' SourceFile='arial14_0' SourceRect='72,81,79,95'/>
<FontCharacter Advance='6' Code='113' SourceFile='arial14_0' SourceRect='81,81,88,95'/>
<FontCharacter Advance='4' Code='114' SourceFile='arial14_0' SourceRect='90,81,95,95'/>
<FontCharacter Advance='6' Code='115' SourceFile='arial14_0' SourceRect='97,81,104,95'/>
<FontCharacter Advance='3' Code='116' SourceFile='arial14_0' SourceRect='106,81,111,95'/>
<FontCharacter Advance='6' Code='117' SourceFile='arial14_0' SourceRect='113,81,120,95'/>
<FontCharacter Advance='6' Code='118' SourceFile='arial14_0' SourceRect='1,97,8,111'/>
<FontCharacter Advance='10' Code='119' SourceFile='arial14_0' SourceRect='10,97,21,111'/>
<FontCharacter Advance='6' Code='120' SourceFile='arial14_0' SourceRect='23,97,30,111'/>
<FontCharacter Advance='6' Code='121' SourceFile='arial14_0' SourceRect='32,97,39,111'/>
<FontCharacter Advance='6' Code='122' SourceFile='arial14_0' SourceRect='41,97,48,111'/>
<FontCharacter Advance='4' Code='123' SourceFile='arial14_0' SourceRect='50,97,55,111'/>
<FontCharacter Advance='2' Code='124' SourceFile='arial14_0' SourceRect='57,97,60,111'/>
<FontCharacter Advance='4' Code='125' SourceFile='arial14_0' SourceRect='62,97,67,111'/>
<FontCharacter Advance='6' Code='126' SourceFile='arial14_0' SourceRect='69,97,76,111'/>
<FontCharacter Advance='24' Code='57345' Name='ilc9' SourceFile='ui_kill_echo_amp_magscatter' SourceRect='0,0,24,16'/>
<FontCharacter Advance='22' Code='57346' Name='isp' SourceFile='ui_kill_echo_amp_magscatter' SourceRect='0,16,22,32'/>
<FontCharacter Advance='31' Code='57347' Name='ams' SourceFile='ui_kill_echo_ams_sunder_stealthquad_basilisk' SourceRect='0,0,31,16'/>
<FontCharacter Advance='34' Code='57348' Name='apc' SourceFile='ui_kill_echo_ams_sunder_stealthquad_basilisk' SourceRect='0,16,34,32'/>
<FontCharacter Advance='33' Code='57349' Name='quadstealth' SourceFile='ui_kill_echo_ams_sunder_stealthquad_basilisk' SourceRect='0,32,33,48'/>
<FontCharacter Advance='36' Code='57350' Name='quadassault' SourceFile='ui_kill_echo_ams_sunder_stealthquad_basilisk' SourceRect='0,48,36,64'/>
<FontCharacter Advance='29' Code='57351' Name='beamer' SourceFile='ui_kill_echo_beamer_magcutter_forceblade_chainblade' SourceRect='0,0,29,16'/>
<FontCharacter Advance='46' Code='57352' Name='magcutter' SourceFile='ui_kill_echo_beamer_magcutter_forceblade_chainblade' SourceRect='0,16,46,32'/>
<FontCharacter Advance='44' Code='57353' Name='forceblade' SourceFile='ui_kill_echo_beamer_magcutter_forceblade_chainblade' SourceRect='0,32,44,48'/>
<FontCharacter Advance='59' Code='57354' Name='chainblade' SourceFile='ui_kill_echo_beamer_magcutter_forceblade_chainblade' SourceRect='0,48,59,64'/>
<FontCharacter Advance='56' Code='57355' Name='bolt_driver' SourceFile='ui_kill_echo_bolt_hunter_striker_lancer' SourceRect='0,0,56,16'/>
<FontCharacter Advance='59' Code='57356' Name='hunterseeker' SourceFile='ui_kill_echo_bolt_hunter_striker_lancer' SourceRect='0,16,59,32'/>
<FontCharacter Advance='43' Code='57357' Name='striker' SourceFile='ui_kill_echo_bolt_hunter_striker_lancer' SourceRect='0,32,43,48'/>
<FontCharacter Advance='53' Code='57358' Name='lancer' SourceFile='ui_kill_echo_bolt_hunter_striker_lancer' SourceRect='0,48,53,64'/>
<FontCharacter Advance='16' Code='57359' Name='boomer' SourceFile='ui_kill_echo_boomerhe_fragrenade' SourceRect='0,0,16,16'/>
<FontCharacter Advance='13' Code='57360' Name='frag_grenade' SourceFile='ui_kill_echo_boomerhe_fragrenade' SourceRect='0,16,13,32'/>
<FontCharacter Advance='54' Code='57361' Name='dragon' SourceFile='ui_kill_echo_dragon_jackhammer_cycler_minichaingun' SourceRect='0,0,54,16'/>
<FontCharacter Advance='49' Code='57362' Name='r_shotgun' SourceFile='ui_kill_echo_dragon_jackhammer_cycler_minichaingun' SourceRect='0,16,49,32'/>
<FontCharacter Advance='52' Code='57363' Name='cycler' SourceFile='ui_kill_echo_dragon_jackhammer_cycler_minichaingun' SourceRect='0,32,52,48'/>
<FontCharacter Advance='48' Code='57364' Name='mini_chaingun' SourceFile='ui_kill_echo_dragon_jackhammer_cycler_minichaingun' SourceRect='0,48,48,64'/>
<FontCharacter Advance='17' Code='57365' Name='he_mine' SourceFile='ui_kill_echo_hemine_magno' SourceRect='0,0,17,16'/>
<FontCharacter Advance='16' Code='57366' Name='magno_mine' SourceFile='ui_kill_echo_hemine_magno' SourceRect='0,16,16,32'/>
<FontCharacter Advance='57' Code='57367' Name='lasher' SourceFile='ui_kill_echo_lasher_pulsar_thumper_guass' SourceRect='0,0,57,16'/>
<FontCharacter Advance='44' Code='57368' Name='pulsar' SourceFile='ui_kill_echo_lasher_pulsar_thumper_guass' SourceRect='0,16,44,32'/>
<FontCharacter Advance='37' Code='57369' Name='thumper' SourceFile='ui_kill_echo_lasher_pulsar_thumper_guass' SourceRect='0,32,37,48'/>
<FontCharacter Advance='44' Code='57370' Name='gauss' SourceFile='ui_kill_echo_lasher_pulsar_thumper_guass' SourceRect='0,48,44,64'/>
<FontCharacter Advance='44' Code='57371' Name='lightning' SourceFile='ui_kill_echo_lightning_galaxy_prowler_vanguard' SourceRect='0,0,44,16'/>
<FontCharacter Advance='47' Code='57372' Name='dropship' SourceFile='ui_kill_echo_lightning_galaxy_prowler_vanguard' SourceRect='0,16,47,32'/>
<FontCharacter Advance='36' Code='57373' Name='prowler' SourceFile='ui_kill_echo_lightning_galaxy_prowler_vanguard' SourceRect='0,32,36,48'/>
<FontCharacter Advance='48' Code='57374' Name='vanguard' SourceFile='ui_kill_echo_lightning_galaxy_prowler_vanguard' SourceRect='0,48,48,64'/>
<FontCharacter Advance='28' Code='57375' Name='threemanheavybuggy' SourceFile='ui_kill_echo_marauder_deliverer_enforcer_harraser' SourceRect='0,0,28,16'/>
<FontCharacter Advance='34' Code='57376' Name='mediumtransport' SourceFile='ui_kill_echo_marauder_deliverer_enforcer_harraser' SourceRect='0,16,34,32'/>
<FontCharacter Advance='43' Code='57377' Name='twomanheavybuggy' SourceFile='ui_kill_echo_marauder_deliverer_enforcer_harraser' SourceRect='0,32,43,48'/>
<FontCharacter Advance='46' Code='57378' Name='two_man_assault_buggy' SourceFile='ui_kill_echo_marauder_deliverer_enforcer_harraser' SourceRect='0,48,46,64'/>
<FontCharacter Advance='10' Code='57379' Name='minesweeper' SourceFile='ui_kill_echo_minesweeper_plasma' SourceRect='0,0,10,16'/>
<FontCharacter Advance='9' Code='57380' Name='plasma_grenade' SourceFile='ui_kill_echo_minesweeper_plasma' SourceRect='0,16,9,32'/>
<FontCharacter Advance='33' Code='57381' Name='repeater' SourceFile='ui_kill_echo_repeater_punisher_rocklet_suppressor' SourceRect='0,0,33,16'/>
<FontCharacter Advance='39' Code='57382' Name='punisher' SourceFile='ui_kill_echo_repeater_punisher_rocklet_suppressor' SourceRect='0,16,39,32'/>
<FontCharacter Advance='31' Code='57383' Name='rocklet' SourceFile='ui_kill_echo_repeater_punisher_rocklet_suppressor' SourceRect='0,32,31,48'/>
<FontCharacter Advance='37' Code='57384' Name='suppressor' SourceFile='ui_kill_echo_repeater_punisher_rocklet_suppressor' SourceRect='0,48,37,64'/>
<FontCharacter Advance='54' Code='57385' Name='twomanhoverbuggy' SourceFile='ui_kill_echo_thresher_magrider_reaver_mosquito' SourceRect='0,0,54,16'/>
<FontCharacter Advance='53' Code='57386' Name='magrider' SourceFile='ui_kill_echo_thresher_magrider_reaver_mosquito' SourceRect='0,16,53,32'/>
<FontCharacter Advance='53' Code='57387' Name='lightgunship' SourceFile='ui_kill_echo_thresher_magrider_reaver_mosquito' SourceRect='0,32,53,48'/>
<FontCharacter Advance='46' Code='57388' Name='mosquito' SourceFile='ui_kill_echo_thresher_magrider_reaver_mosquito' SourceRect='0,48,46,64'/>
<FontCharacter Advance='19' Code='57389' Name='trhev_burster' SourceFile='ui_kill_echo_trhev_nchev' SourceRect='0,0,19,16'/>
<FontCharacter Advance='19' Code='57390' Name='trhev_dualcycler' SourceFile='ui_kill_echo_trhev_nchev' SourceRect='0,0,19,16'/>
<FontCharacter Advance='19' Code='57391' Name='trhev_pounder' SourceFile='ui_kill_echo_trhev_nchev' SourceRect='0,0,19,16'/>
<FontCharacter Advance='17' Code='57392' Name='nchev_falcon' SourceFile='ui_kill_echo_trhev_nchev' SourceRect='0,16,17,32'/>
<FontCharacter Advance='17' Code='57393' Name='nchev_scattercannon' SourceFile='ui_kill_echo_trhev_nchev' SourceRect='0,16,17,32'/>
<FontCharacter Advance='17' Code='57394' Name='nchev_sparrow' SourceFile='ui_kill_echo_trhev_nchev' SourceRect='0,16,17,32'/>
<FontCharacter Advance='18' Code='57395' Name='vshev_comet' SourceFile='ui_kill_echo_vshev_suicide' SourceRect='0,0,18,16'/>
<FontCharacter Advance='18' Code='57396' Name='vshev_starfire' SourceFile='ui_kill_echo_vshev_suicide' SourceRect='0,0,18,16'/>
<FontCharacter Advance='18' Code='57397' Name='vshev_quasar' SourceFile='ui_kill_echo_vshev_suicide' SourceRect='0,0,18,16'/>
<FontCharacter Advance='27' Code='57398' Name='suicide' SourceFile='ui_kill_echo_vshev_suicide' SourceRect='0,16,27,32'/>
<FontCharacter Advance='45' Code='57399' Name='flechette' SourceFile='ui_kill_echo_flechette_phoenix_spitfire' SourceRect='0,0,64,14'/>
<FontCharacter Advance='49' Code='57400' Name='phoenix' SourceFile='ui_kill_echo_flechette_phoenix_spitfire' SourceRect='0,16,49,32'/>
<FontCharacter Advance='14' Code='57401' Name='spitfire_turret' SourceFile='ui_kill_echo_flechette_phoenix_spitfire' SourceRect='0,33,14,49'/>
<FontCharacter Advance='30' Code='57402' Name='ace' SourceFile='ui_smlinv_ace_00' SourceRect='0,0,30,16'/>
<FontCharacter Advance='24' Code='57403' Name='bank' SourceFile='ui_smlinv_bank_00' SourceRect='0,0,24,16'/>
<FontCharacter Advance='37' Code='57404' Name='boomer' SourceFile='ui_smlinv_boomer_trigger_00' SourceRect='0,0,37,16'/>
<FontCharacter Advance='56' Code='57405' Name='jammer_grenade' SourceFile='ui_smlinv_jammer_grenade_00' SourceRect='0,0,56,16'/>
<FontCharacter Advance='21' Code='57406' Name='medicalapplicator' SourceFile='ui_smlinv_medical_applicator_00' SourceRect='0,0,21,16'/>
<FontCharacter Advance='9' Code='57407' Name='mine_sweeper' SourceFile='ui_smlinv_mine_sweeper_00' SourceRect='0,0,9,16'/>
<FontCharacter Advance='33' Code='57408' Name='nano_dispenser' SourceFile='ui_smlinv_nano_dispenser_00' SourceRect='0,0,33,16'/>
<FontCharacter Advance='19' Code='57409' Name='remote_electronics_kit' SourceFile='ui_smlinv_remote_electronics_kit_00' SourceRect='0,0,19,16'/>
<FontCharacter Advance='36' Code='57410' Name='ant' SourceFile='ui_kill_echo_ant_uplink' SourceRect='0,0,36,16'/>
<FontCharacter Advance='9' Code='57411' Name='command_detonater' SourceFile='ui_kill_echo_ant_uplink' SourceRect='0,17,9,33'/>
</TextStyle>
