<Namespace Name='Backdrops'>
<ImageStyle Name='BluePlanet'>
<ImageFrame>
<ImageFragment Source='ps_interface_background_00' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,0' Source='ps_interface_background_01' SourceRect='0,0,256,256'/>
<ImageFragment Offset='512,0' Source='ps_interface_background_02' SourceRect='0,0,256,256'/>
<ImageFragment Offset='768,0' Source='ps_interface_background_03' SourceRect='0,0,32,256'/>
<ImageFragment Offset='0,256' Source='ps_interface_background_04' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,256' Source='ps_interface_background_05' SourceRect='0,0,256,256'/>
<ImageFragment Offset='512,256' Source='ps_interface_background_06' SourceRect='0,0,256,256'/>
<ImageFragment Offset='768,256' Source='ps_interface_background_07' SourceRect='0,0,32,256'/>
<ImageFragment Offset='0,512' Source='ps_interface_background_08' SourceRect='0,0,256,88'/>
<ImageFragment Offset='256,512' Source='ps_interface_background_09' SourceRect='0,0,256,88'/>
<ImageFragment Offset='512,512' Source='ps_interface_background_10' SourceRect='0,0,256,88'/>
<ImageFragment Offset='768,512' Source='ps_interface_background_11' SourceRect='0,0,32,88'/>
</ImageFrame>
</ImageStyle>
<ImageStyle Name='RedPlanet'>
<ImageFrame>
<ImageFragment SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,0' SourceRect='0,0,256,256'/>
<ImageFragment Offset='512,0' SourceRect='0,0,256,256'/>
<ImageFragment Offset='0,256' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,256' SourceRect='0,0,256,256'/>
<ImageFragment Offset='512,256' SourceRect='0,0,256,256'/>
<ImageFragment Offset='768,0' SourceRect='0,0,32,128'/>
<ImageFragment Offset='768,128' SourceRect='0,0,32,128'/>
<ImageFragment Offset='768,256' SourceRect='0,0,32,128'/>
<ImageFragment Offset='768,384' SourceRect='0,0,32,128'/>
<ImageFragment Offset='0,512' SourceRect='0,0,128,88'/>
<ImageFragment Offset='128,512' SourceRect='0,0,128,88'/>
<ImageFragment Offset='256,512' SourceRect='0,0,128,88'/>
<ImageFragment Offset='384,512' SourceRect='0,0,128,88'/>
<ImageFragment Offset='512,512' SourceRect='0,0,128,88'/>
<ImageFragment Offset='640,512' SourceRect='0,0,128,88'/>
<ImageFragment Offset='768,512' SourceRect='0,0,32,88'/>
</ImageFrame>
</ImageStyle>
<ImageStyle Name='Login'>
<ImageFrame>
<ImageFragment SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,0' SourceRect='0,0,256,256'/>
<ImageFragment Offset='512,0' SourceRect='0,0,256,256'/>
<ImageFragment Offset='768,0' SourceRect='0,0,32,256'/>
<ImageFragment Offset='0,256' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,256' SourceRect='0,0,256,256'/>
<ImageFragment Offset='512,256' SourceRect='0,0,256,256'/>
<ImageFragment Offset='768,256' SourceRect='0,0,32,256'/>
<ImageFragment Offset='0,512' SourceRect='0,0,256,88'/>
<ImageFragment Offset='256,512' SourceRect='0,0,256,88'/>
<ImageFragment Offset='512,512' SourceRect='0,0,256,88'/>
<ImageFragment Offset='768,512' SourceRect='0,0,32,88'/>
</ImageFrame>
</ImageStyle>
</Namespace>
