<Page Name='console' PackSize='1.0, Fixed' PackSizeProp='0002/0003,xxxx/xxxx' scroll.visible='true' ScrollExtent='1024,400' Size='1024,400' Visible='false' visualeditlock='true' wantsinput='true'>
<Text Font='/SmallFont' Name='output' PackSize='Absolute, Absolute' PackSizeProp='0026/0001,xxxx/xxxx' ScrollExtent='998,368' Size='998,368'></Text>
<Textbox BackgroundColor='#111111' BackgroundOpacity='1.000' Location='0,368' Name='input' Opacity='0.900' PackSize='Absolute, Fixed' PackSizeProp='0002/0001,xxxx/xxxx' ScrollExtent='1022,32' Size='1022,32' Style='/ConsoleTextbox.Style'></Textbox>
<Scrollbar Control='output' Location='1001,-1' Name='Scroll' PackLocation='Right, Top' PackLocationProp='-023/0001,xxxx/xxxx' ScrollExtent='20,368' Size='20,368' Style='/VScrollbar.style'/>
<Page BackgroundOpacity='1.000' Name='Tint' PackSize='1,1' PackSizeProp='0002/0003,0002/0003' ScrollExtent='1024,400' Size='1024,400'/>
</Page>
