<Namespace Name='DefaultCheckbox'>
<ImageStyle Name='Unchecked'>
<ImageFrame Source='ui_checkbox' SourceRect='0,0,13,13'/>
</ImageStyle>
<ImageStyle Name='Checked'>
<ImageFrame Source='ui_checkbox' SourceRect='13,0,26,13'/>
</ImageStyle>
<ImageStyle Name='Selected.Unchecked'>
<ImageFrame Source='ui_checkbox' SourceRect='0,14,13,27'/>
</ImageStyle>
<ImageStyle Name='Selected.Checked'>
<ImageFrame Source='ui_checkbox' SourceRect='13,14,26,27'/>
</ImageStyle>
<ImageStyle Name='Disabled.Unchecked'>
<ImageFrame Source='ui_checkbox' SourceRect='26,28,39,41'/>
</ImageStyle>
<ImageStyle Name='Disabled.Checked'>
<ImageFrame Source='ui_checkbox' SourceRect='39,28,52,41'/>
</ImageStyle>
<CheckboxStyle disabledcheckedimage='Disabled.Checked' disableduncheckedimage='Disabled.Unchecked' Name='Style' normalcheckedimage='Checked' NormalTextStyle='/Fonts.DefaultFont' normaluncheckedimage='Unchecked' selectedcheckedimage='Selected.Checked' selecteduncheckedimage='Selected.Unchecked' TextOffset='20,0'/>
</Namespace>
