<Page Name='Play' OnHide='Parent.NavBar.Visible = false





























Parent.CharacterOverlay.Visible = false' OnShow='Parent.NavBar.Visible = true' PackLocation='0.5, 0.5' ScrollExtent='800,600' Size='800,600' Visible='false' visualeditlock='true'>
<Image Location='18,40' Name='Plate' Opacity='0.15' ScrollExtent='764,541' Size='764,541' Stretch='false' Style='/Plates.Large'/>
<Image Name='Border' ScrollExtent='800,600' Size='800,600' Stretch='false' Style='/Plates.Border'/>
<3DPlanet Color='#000000' Name='Planet' PackSize='1,1' ScrollExtent='800,600' Size='800,600'/>
</Page>
