<Page Name='ContinentalMap' PackLocation='0.5, 0.5' ScrollExtent='800,600' Size='800,600' Visible='false'>
<Button Location='760,60' Name='Exit' OnPress='ui_popstate' ScrollExtent='16,16' Size='16,16' Style='/Buttons.Exit.style'></Button>
<Text Font='/Fonts.DefaultFont' Location='10,10' ScrollExtent='191,20' Size='220,20'>Continental Map Goes Here</Text>
<Image Location='9,47' Name='Plate1' Opacity='0.30' ScrollExtent='782,505' Size='782,505' Stretch='false' Style='/Plates.Large'/>
<Image Name='Backdrop' ScrollExtent='800,600' Size='800,600' Style='/Backdrops.BluePlanet'/>
</Page>
