<Page Name='CreateCharacter' PackLocation='Center,Center' PackLocationProp='-512/0001,-384/0001' ScrollExtent='1024,768' Size='1024,768' Visible='false'>
<DataSource Name='MaleHeads'>
<Data e='1,1' l='0,0' Name='Male01a' t='/CreateCharacter.GridElement'/>
<Data e='1,1' l='1,0' Name='Male01b' t='/CreateCharacter.GridElement'/>
<Data e='1,1' l='2,0' Name='Male01c' t='/CreateCharacter.GridElement'/>
<Data e='1,1' l='3,0' Name='Male01d' t='/CreateCharacter.GridElement'/>
<Data e='1,1' l='4,0' Name='Male01e' t='/CreateCharacter.GridElement'/>
<Data e='1,1' l='0,1' Name='Male02a' t='/CreateCharacter.GridElement'/>
<Data e='1,1' l='1,1' Name='Male02b' t='/CreateCharacter.GridElement'/>
<Data e='1,1' l='2,1' Name='Male02c' t='/CreateCharacter.GridElement'/>
<Data e='1,1' l='3,1' Name='Male02d' t='/CreateCharacter.GridElement'/>
<Data e='1,1' l='4,1' Name='Male02e' t='/CreateCharacter.GridElement'/>
<Data e='1,1' l='0,2' Name='Male03a' t='/CreateCharacter.GridElement'/>
<Data e='1,1' l='1,2' Name='Male03b' t='/CreateCharacter.GridElement'/>
<Data e='1,1' l='2,2' Name='Male03c' t='/CreateCharacter.GridElement'/>
<Data e='1,1' l='3,2' Name='Male03d' t='/CreateCharacter.GridElement'/>
<Data e='1,1' l='4,2' Name='Male03e' t='/CreateCharacter.GridElement'/>
<Data e='1,1' l='0,3' Name='Male04a' t='/CreateCharacter.GridElement'/>
<Data e='1,1' l='1,3' Name='Male04b' t='/CreateCharacter.GridElement'/>
<Data e='1,1' l='2,3' Name='Male04c' t='/CreateCharacter.GridElement'/>
<Data e='1,1' l='3,3' Name='Male04d' t='/CreateCharacter.GridElement'/>
<Data e='1,1' l='4,3' Name='Male04e' t='/CreateCharacter.GridElement'/>
<Data e='1,1' l='0,4' Name='Male05a' t='/CreateCharacter.GridElement'/>
<Data e='1,1' l='1,4' Name='Male05b' t='/CreateCharacter.GridElement'/>
<Data e='1,1' l='2,4' Name='Male05c' t='/CreateCharacter.GridElement'/>
<Data e='1,1' l='3,4' Name='Male05d' t='/CreateCharacter.GridElement'/>
<Data e='1,1' l='4,4' Name='Male05e' t='/CreateCharacter.GridElement'/>
<Data e='1,1' l='0,5' Name='Male06a' t='/CreateCharacter.GridElement'/>
<Data e='1,1' l='1,5' Name='Male06b' t='/CreateCharacter.GridElement'/>
<Data e='1,1' l='2,5' Name='Male06c' t='/CreateCharacter.GridElement'/>
<Data e='1,1' l='3,5' Name='Male06d' t='/CreateCharacter.GridElement'/>
<Data e='1,1' l='4,5' Name='Male06e' t='/CreateCharacter.GridElement'/>
<Data e='1,1' l='0,6' Name='Male07a' t='/CreateCharacter.GridElement'/>
<Data e='1,1' l='1,6' Name='Male07b' t='/CreateCharacter.GridElement'/>
<Data e='1,1' l='2,6' Name='Male07c' t='/CreateCharacter.GridElement'/>
<Data e='1,1' l='3,6' Name='Male07d' t='/CreateCharacter.GridElement'/>
<Data e='1,1' l='4,6' Name='Male07e' t='/CreateCharacter.GridElement'/>
<Data e='1,1' l='0,7' Name='Male08a' t='/CreateCharacter.GridElement'/>
<Data e='1,1' l='1,7' Name='Male08b' t='/CreateCharacter.GridElement'/>
<Data e='1,1' l='2,7' Name='Male08c' t='/CreateCharacter.GridElement'/>
<Data e='1,1' l='3,7' Name='Male08d' t='/CreateCharacter.GridElement'/>
<Data e='1,1' l='4,7' Name='Male08e' t='/CreateCharacter.GridElement'/>
<Data e='1,1' l='0,8' Name='Male09a' t='/CreateCharacter.GridElement'/>
<Data e='1,1' l='1,8' Name='Male09b' t='/CreateCharacter.GridElement'/>
<Data e='1,1' l='2,8' Name='Male09c' t='/CreateCharacter.GridElement'/>
<Data e='1,1' l='3,8' Name='Male09d' t='/CreateCharacter.GridElement'/>
<Data e='1,1' l='4,8' Name='Male09e' t='/CreateCharacter.GridElement'/>
<Data e='1,1' l='0,9' Name='Male10a' t='/CreateCharacter.GridElement'/>
<Data e='1,1' l='1,9' Name='Male10b' t='/CreateCharacter.GridElement'/>
<Data e='1,1' l='2,9' Name='Male10c' t='/CreateCharacter.GridElement'/>
<Data e='1,1' l='3,9' Name='Male10d' t='/CreateCharacter.GridElement'/>
<Data e='1,1' l='4,9' Name='Male10e' t='/CreateCharacter.GridElement'/>
<Data e='1,1' l='0,10' Name='Male11a' t='/CreateCharacter.GridElement'/>
<Data e='1,1' l='1,10' Name='Male11b' t='/CreateCharacter.GridElement'/>
<Data e='1,1' l='2,10' Name='Male11c' t='/CreateCharacter.GridElement'/>
<Data e='1,1' l='3,10' Name='Male11d' t='/CreateCharacter.GridElement'/>
<Data e='1,1' l='4,10' Name='Male11e' t='/CreateCharacter.GridElement'/>
</DataSource>
<DataSource Name='FemaleHeads'>
<Data e='1,1' l='0,0' Name='Female01a' t='/CreateCharacter.GridElement'/>
<Data e='1,1' l='1,0' Name='Female01b' t='/CreateCharacter.GridElement'/>
<Data e='1,1' l='2,0' Name='Female01c' t='/CreateCharacter.GridElement'/>
<Data e='1,1' l='3,0' Name='Female01d' t='/CreateCharacter.GridElement'/>
<Data e='1,1' l='4,0' Name='Female01e' t='/CreateCharacter.GridElement'/>
<Data e='1,1' l='0,1' Name='Female02a' t='/CreateCharacter.GridElement'/>
<Data e='1,1' l='1,1' Name='Female02b' t='/CreateCharacter.GridElement'/>
<Data e='1,1' l='2,1' Name='Female02c' t='/CreateCharacter.GridElement'/>
<Data e='1,1' l='3,1' Name='Female02d' t='/CreateCharacter.GridElement'/>
<Data e='1,1' l='4,1' Name='Female02e' t='/CreateCharacter.GridElement'/>
<Data e='1,1' l='0,2' Name='Female03a' t='/CreateCharacter.GridElement'/>
<Data e='1,1' l='1,2' Name='Female03b' t='/CreateCharacter.GridElement'/>
<Data e='1,1' l='2,2' Name='Female03c' t='/CreateCharacter.GridElement'/>
<Data e='1,1' l='3,2' Name='Female03d' t='/CreateCharacter.GridElement'/>
<Data e='1,1' l='4,2' Name='Female03e' t='/CreateCharacter.GridElement'/>
<Data e='1,1' l='0,3' Name='Female04a' t='/CreateCharacter.GridElement'/>
<Data e='1,1' l='1,3' Name='Female04b' t='/CreateCharacter.GridElement'/>
<Data e='1,1' l='2,3' Name='Female04c' t='/CreateCharacter.GridElement'/>
<Data e='1,1' l='3,3' Name='Female04d' t='/CreateCharacter.GridElement'/>
<Data e='1,1' l='4,3' Name='Female04e' t='/CreateCharacter.GridElement'/>
<Data e='1,1' l='0,4' Name='Female05a' t='/CreateCharacter.GridElement'/>
<Data e='1,1' l='1,4' Name='Female05b' t='/CreateCharacter.GridElement'/>
<Data e='1,1' l='2,4' Name='Female05c' t='/CreateCharacter.GridElement'/>
<Data e='1,1' l='3,4' Name='Female05d' t='/CreateCharacter.GridElement'/>
<Data e='1,1' l='4,4' Name='Female05e' t='/CreateCharacter.GridElement'/>
<Data e='1,1' l='0,5' Name='Female06a' t='/CreateCharacter.GridElement'/>
<Data e='1,1' l='1,5' Name='Female06b' t='/CreateCharacter.GridElement'/>
<Data e='1,1' l='2,5' Name='Female06c' t='/CreateCharacter.GridElement'/>
<Data e='1,1' l='3,5' Name='Female06d' t='/CreateCharacter.GridElement'/>
<Data e='1,1' l='4,5' Name='Female06e' t='/CreateCharacter.GridElement'/>
<Data e='1,1' l='0,6' Name='Female07a' t='/CreateCharacter.GridElement'/>
<Data e='1,1' l='1,6' Name='Female07b' t='/CreateCharacter.GridElement'/>
<Data e='1,1' l='2,6' Name='Female07c' t='/CreateCharacter.GridElement'/>
<Data e='1,1' l='3,6' Name='Female07d' t='/CreateCharacter.GridElement'/>
<Data e='1,1' l='4,6' Name='Female07e' t='/CreateCharacter.GridElement'/>
<Data e='1,1' l='0,7' Name='Female08a' t='/CreateCharacter.GridElement'/>
<Data e='1,1' l='1,7' Name='Female08b' t='/CreateCharacter.GridElement'/>
<Data e='1,1' l='2,7' Name='Female08c' t='/CreateCharacter.GridElement'/>
<Data e='1,1' l='3,7' Name='Female08d' t='/CreateCharacter.GridElement'/>
<Data e='1,1' l='4,7' Name='Female08e' t='/CreateCharacter.GridElement'/>
<Data e='1,1' l='0,8' Name='Female09a' t='/CreateCharacter.GridElement'/>
<Data e='1,1' l='1,8' Name='Female09b' t='/CreateCharacter.GridElement'/>
<Data e='1,1' l='2,8' Name='Female09c' t='/CreateCharacter.GridElement'/>
<Data e='1,1' l='3,8' Name='Female09d' t='/CreateCharacter.GridElement'/>
<Data e='1,1' l='4,8' Name='Female09e' t='/CreateCharacter.GridElement'/>
<Data e='1,1' l='0,9' Name='Female10a' t='/CreateCharacter.GridElement'/>
<Data e='1,1' l='1,9' Name='Female10b' t='/CreateCharacter.GridElement'/>
<Data e='1,1' l='2,9' Name='Female10c' t='/CreateCharacter.GridElement'/>
<Data e='1,1' l='3,9' Name='Female10d' t='/CreateCharacter.GridElement'/>
<Data e='1,1' l='4,9' Name='Female10e' t='/CreateCharacter.GridElement'/>
<Data e='1,1' l='0,10' Name='Female11a' t='/CreateCharacter.GridElement'/>
<Data e='1,1' l='1,10' Name='Female11b' t='/CreateCharacter.GridElement'/>
<Data e='1,1' l='2,10' Name='Female11c' t='/CreateCharacter.GridElement'/>
<Data e='1,1' l='3,10' Name='Female11d' t='/CreateCharacter.GridElement'/>
<Data e='1,1' l='4,10' Name='Female11e' t='/CreateCharacter.GridElement'/>
</DataSource>
<Checkbox BackgroundOpacity='1.000' Location='505,59' Name='Male' PackLocation='right,top' PackLocationProp='-519/0001,0059/0001' PackSize='proportional,fixed' PackSizeProp='0220/1024,0002/0003' Radio='true' ScrollExtent='220,40' Size='220,40' Style='/Buttons.FrontendButton.checkstyle' textcolor='#72C9D1' TooltipStyle='/Tooltips.Default'>@CreateCharacterMale</Checkbox>
<Checkbox BackgroundOpacity='1.000' Location='747,59' Name='Female' PackLocation='right,top' PackLocationProp='-277/0001,0059/0001' PackSize='proportional,fixed' PackSizeProp='0220/1024,0002/0003' Radio='true' ScrollExtent='220,40' Size='220,40' Style='/Buttons.FrontendButton.checkstyle' textcolor='#72C9D1' TooltipStyle='/Tooltips.Default'>@CreateCharacterFemale</Checkbox>
<Page Location='60,59' Name='CharacterView' PackLocation='left,cfc' PackLocationProp='0060/0001,0000/0001' PackSize='proportional,proportional' PackSizeProp='0425/1024,0650/0768' ScrollExtent='425,650' Size='425,650'>
<Textbox Activated='true' IME='true' Location='20,13' Name='Name' PackSize='absolute,fixed' PackSizeProp='0040/0001,0002/0003' ScrollExtent='385,29' Size='385,29' Style='/Textboxes.Frontend' TooltipStyle='/Tooltips.Default'>sample</Textbox>
<Button Enabled='false' Location='10,10' Name='NameHeading' PackSize='absolute,fixed' PackSizeProp='0020/0001,0002/0003' ScrollExtent='405,30' Size='405,30' Style='/Buttons.FrontendTitleButton.style' TooltipStyle='/Tooltips.Default'></Button>
<Button LocalText='New Button' Location='114,602' Name='RotateLeft' PackLocation='center,bottom' PackLocationProp='-098/0001,-048/0001' PackSize='fixed,fixed' PackSizeProp='0002/0003,0002/0003' ScrollExtent='17,12' Size='17,12' Style='/Buttons.CharacterCreateRotateLeft.style' TooltipStyle='/Tooltips.Default'>New Button</Button>
<Button LocalText='New Button' Location='289,602' Name='RotateRight' PackLocation='center,bottom' PackLocationProp='0077/0001,-048/0001' ScrollExtent='17,12' Size='17,12' Style='/Buttons.CharacterCreateRotateRight.style' TooltipStyle='/Tooltips.Default'>New Button</Button>
<Button LocalText='New Button' Location='190,601' Name='ZoomIn' PackLocation='center,bottom' PackLocationProp='-022/0001,-049/0001' ScrollExtent='15,15' Size='15,15' Style='/Buttons.CharacterCreateZoomIn.style' TooltipStyle='/Tooltips.Default'>New Button</Button>
<Button LocalText='New Button' Location='219,605' Name='ZoomOut' PackLocation='center,bottom' PackLocationProp='0007/0001,-045/0001' ScrollExtent='16,6' Size='16,6' Style='/Buttons.CharacterCreateZoomOut.style' TooltipStyle='/Tooltips.Default'>New Button</Button>
<GameObjectView Location='10,10' Name='3DCharacterView' PackSize='absolute,absolute' PackSizeProp='0020/0001,0020/0001' ScrollExtent='405,630' Size='405,630'/>
<Image Location='-11,34' Name='VSBackground' Opacity='0.300' PackSize='absolute,absolute' PackSizeProp='-026/0001,0049/0001' ScrollExtent='451,601' Size='451,601' Style='/Plates.ShellVSBackground' Visible='false'/>
<Image Location='-8,10' Name='TRBackground' Opacity='0.300' PackSize='absolute,absolute' PackSizeProp='-026/0001,-026/0001' ScrollExtent='451,676' Size='451,676' Style='/Plates.ShellTRBackground'/>
<Image Location='-11,60' Name='NCBackground' Opacity='0.300' PackSize='absolute,absolute' PackSizeProp='-026/0001,0111/0001' ScrollExtent='451,539' Size='451,539' Style='/Plates.ShellNCBackground' Visible='false'/>
<Image BackgroundOpacity='1.000' Name='Box' PackSize='1,1' PackSizeProp='0002/0003,0002/0003' RStyleDefault='/Frontend.Box.style' ScrollExtent='425,650' Size='425,650' Stretch='false' Style=' '/>
</Page>
<Page Location='505,119' MaximumSize='460,10000' Name='Heads' PackLocation='fff,top' PackLocationProp='-059/0001,0119/0001' PackSize='proportional,absolute' PackSizeProp='0460/1024,0352/0001' ScrollExtent='460,416' Size='460,416'>
<Grid CellCount='5,11' CellSize='85,130' DataSource='MaleHeads' Location='10,10' Name='HeadGrid' PackSize='absolute,absolute' PackSizeProp='0030/0001,0020/0001' ScrollExtent='425,1430' Size='430,396' Style='/Grids.FrontendGrid.style'/>
<Scrollbar Control='HeadGrid' Location='441,10' Name='HeadScrollbar' PackLocation='right,top' PackLocationProp='-019/0001,0010/0001' ScrollExtent='10,396' Size='10,396' Style='/ScrollBars.frontend_vertical.style'/>
<ImageStyle Name='HeadSelectionStyle'>
<ImageFrame SourceRect='0,0,66,98'>
<ImageFragment Source='ui_shell_charcreate_headpick_rollover_00' SourceRect='0,0,64,64'/>
<ImageFragment Offset='0,64' Source='ui_shell_charcreate_headpick_rollover_01' SourceRect='0,0,64,64'/>
<ImageFragment Offset='64,0' Source='ui_shell_charcreate_headpick_rollover_02' SourceRect='0,0,32,32'/>
<ImageFragment Offset='64,32' Source='ui_shell_charcreate_headpick_rollover_03' SourceRect='0,0,32,32'/>
<ImageFragment Offset='64,64' Source='ui_shell_charcreate_headpick_rollover_04' SourceRect='0,0,32,32'/>
<ImageFragment Offset='64,96' Source='ui_shell_charcreate_headpick_rollover_05' SourceRect='0,0,32,32'/>
</ImageFrame>
</ImageStyle>
<Image BackgroundOpacity='1.000' Name='HeadBox' PackLocation='left,top' PackLocationProp='0000/0001,0000/0001' PackSize='1,1' PackSizeProp='0002/0003,0002/0003' RStyleDefault='/Frontend.Box.style' ScrollExtent='460,416' Size='460,416' Stretch='false' Style=' '/>
</Page>
<Page Location='505,555' MaximumSize='460,154' Name='SoundPage' PackLocation='fff,bottom' PackLocationProp='-059/0001,-213/0001' PackSize='proportional,fixed' PackSizeProp='0460/1024,0002/0003' ScrollExtent='460,154' Size='460,154'>
<Button LocalText='ROUGHNECK' Location='176,15' Name='Voice0Text' PackLocation='cfc,top' PackLocationProp='0021/0001,0015/0001' PackSize='fixed,fixed' PackSizeProp='0002/0003,0002/0003' ScrollExtent='150,30' Size='150,30' Style='/Buttons.FrontendButton.selected'>ROUGHNECK</Button>
<Button LocalText='ROUGHNECK' Location='52,60' Name='Voice1Text' PackLocation='left,top' PackLocationProp='0052/0001,0060/0001' PackSize='fixed,fixed' PackSizeProp='0002/0003,0002/0003' ScrollExtent='150,30' Size='150,30' Style='/Buttons.FrontendButton.style'>ROUGHNECK</Button>
<Button LocalText='[@MaleVoice3]' Location='52,110' Name='Voice2Text' PackLocation='left,top' PackLocationProp='0052/0001,0110/0001' PackSize='fixed,fixed' PackSizeProp='0002/0003,0002/0003' ScrollExtent='150,30' Size='150,30' Style='/Buttons.FrontendButton.style'>@MaleVoice3</Button>
<Button LocalText='[@MaleVoice4]' Location='298,60' Name='Voice3Text' PackLocation='right,top' PackLocationProp='-162/0001,0060/0001' PackSize='fixed,fixed' PackSizeProp='0002/0003,0002/0003' ScrollExtent='150,30' Size='150,30' Style='/Buttons.FrontendButton.style'>@MaleVoice4</Button>
<Button LocalText='[@MaleVoice5]' Location='298,110' Name='Voice4Text' PackLocation='right,top' PackLocationProp='-162/0001,0110/0001' PackSize='fixed,fixed' PackSizeProp='0002/0003,0002/0003' ScrollExtent='150,30' Size='150,30' Style='/Buttons.FrontendButton.style'>@MaleVoice5</Button>
<Checkbox Activated='true' BackgroundOpacity='1.000' Checked='true' Location='134,10' Name='Voice0' PackLocation='cfc,top' PackLocationProp='-075/0001,0010/0001' ScrollExtent='42,42' Size='42,42' Style='/Buttons.CharacaterCreateVoice.style' TooltipStyle='/Tooltips.Default'>@MaleVoice0</Checkbox>
<Checkbox Activated='true' BackgroundOpacity='1.000' Checked='true' Location='10,55' Name='Voice1' PackLocation='left,top' PackLocationProp='0010/0001,0055/0001' ScrollExtent='42,42' Size='42,42' Style='/Buttons.CharacaterCreateVoice.style' TooltipStyle='/Tooltips.Default'>@MaleVoice1</Checkbox>
<Checkbox BackgroundOpacity='1.000' Location='10,105' Name='Voice2' PackLocation='left,top' PackLocationProp='0010/0001,0105/0001' ScrollExtent='42,42' Size='42,42' Style='/Buttons.CharacaterCreateVoice.style' TooltipStyle='/Tooltips.Default'>@MaleVoice2</Checkbox>
<Checkbox Activated='true' BackgroundOpacity='1.000' Checked='true' Location='256,55' Name='Voice3' PackLocation='right,top' PackLocationProp='-204/0001,0055/0001' ScrollExtent='42,42' Size='42,42' Style='/Buttons.CharacaterCreateVoice.style' TooltipStyle='/Tooltips.Default'>@MaleVoice3</Checkbox>
<Checkbox BackgroundOpacity='1.000' Location='256,105' Name='Voice4' PackLocation='right,top' PackLocationProp='-204/0001,0105/0001' ScrollExtent='42,42' Size='42,42' Style='/Buttons.CharacaterCreateVoice.style' TooltipStyle='/Tooltips.Default'>@MaleVoice4</Checkbox>
<Image BackgroundOpacity='1.000' Name='SoundBox' PackLocation='left,top' PackLocationProp='0000/0001,0000/0001' PackSize='1,1' PackSizeProp='0002/0003,0002/0003' RStyleDefault='/Frontend.Box.style' ScrollExtent='460,154' Size='460,154' Stretch='false' Style=' '/>
</Page>
<Page Name='FrontendBasic' PackSize='1,1' PackSizeProp='0002/0003,0002/0003' ScrollExtent='1024,768' Size='1024,768'>
<Button LocalText='[@FrontendBackButton]' Location='5,723' Name='BackButton' PackLocation='left,bottom' PackLocationProp='0005/0001,-045/0001' PackSize='fixed,fixed' PackSizeProp='0002/0003,0002/0003' ScrollExtent='120,40' Size='120,40' Style='/Buttons.FrontendButton.style'>@FrontendBackButton</Button>
<Button IsDefaultButton='true' LocalText='[@FrontendFinishButton]' Location='899,723' Name='NextButton' PackLocation='right,bottom' PackLocationProp='-125/0001,-045/0001' PackSize='fixed,fixed' PackSizeProp='0002/0003,0002/0003' ScrollExtent='120,40' Size='120,40' Style='/Buttons.FrontendButton.style'>@FrontendFinishButton</Button>
<Button LocalText='?' Location='487,728' Name='HelpButton' PackLocation='left,top' PackLocationProp='0487/0001,0728/0001' PackSize='fixed,fixed' PackSizeProp='0002/0003,0002/0003' ScrollExtent='50,35' Size='50,35' Style='/Buttons.FrontendButton.iconstyle' Visible='false'>?</Button>
<Button LocalText='[@FrontendOptionButton]' Location='562,728' Name='OptionsButton' PackLocation='cfc,bottom' PackLocationProp='0100/0001,-040/0001' PackSize='fixed,fixed' PackSizeProp='0002/0003,0002/0003' ScrollExtent='100,35' Size='100,35' Style='/Buttons.FrontendButton.style' Visible='false'>@FrontendOptionButton</Button>
<Button LocalText='EXIT' Location='5,723' Name='CloseButton' PackLocation='left,bottom' PackLocationProp='0005/0001,-045/0001' PackSize='fixed,fixed' PackSizeProp='0002/0003,0002/0003' ScrollExtent='120,40' Size='120,40' Style='/Buttons.FrontendButton.style' Visible='false'>EXIT</Button>
<Image BackgroundOpacity='1.000' Location='15,10' Name='ThickTop' PackLocation='left,top' PackLocationProp='0015/0001,0010/0001' PackSize='absolute,fixed' PackSizeProp='0029/0001,0002/0003' RStyleDefault='/Frontend.Thick.style' ScrollExtent='995,4' Size='995,4' Stretch='false' Style=' '/>
<Image BackgroundOpacity='1.000' Location='125,754' Name='ThickBottom' PackLocation='left,bottom' PackLocationProp='0125/0001,-014/0001' PackSize='absolute,fixed' PackSizeProp='0612/0001,0002/0003' RStyleDefault='/Frontend.Thick.style' ScrollExtent='412,4' Size='412,4' Stretch='false' Style=' '/>
<Image BackgroundOpacity='1.000' Location='537,754' Name='ThickBottom2' PackLocation='left,bottom' PackLocationProp='0537/0001,-014/0001' PackSize='absolute,fixed' PackSizeProp='0662/0001,0002/0003' RStyleDefault='/Frontend.Thick.style' ScrollExtent='362,4' Size='362,4' Stretch='false' Style=' '/>
<Image BackgroundOpacity='1.000' Location='11,10' Name='ThickLeft' PackLocation='left,top' PackLocationProp='0011/0001,0010/0001' PackSize='fixed,absolute' PackSizeProp='0002/0003,0056/0001' RStyleDefault='/Frontend.Thick.style' ScrollExtent='4,712' Size='4,712' Stretch='false' Style=' '/>
<Image BackgroundOpacity='1.000' Location='1010,10' Name='ThickRight' PackLocation='right,top' PackLocationProp='-014/0001,0010/0001' PackSize='fixed,absolute' PackSizeProp='0002/0003,0056/0001' RStyleDefault='/Frontend.Thick.style' ScrollExtent='4,712' Size='4,712' Stretch='false' Style=' '/>
<Image BackgroundOpacity='1.000' Location='979,37' Name='EastBorder' PackLocation='right,top' PackLocationProp='-045/0001,0037/0001' PackSize='fixed,absolute' PackSizeProp='0002/0003,0083/0001' RStyleDefault='/Frontend.EastBorder.style' ScrollExtent='21,685' Size='21,685' Stretch='false' Style=' '/>
<Image BackgroundOpacity='1.000' Location='24,28' Name='WestBorder' PackLocation='left,top' PackLocationProp='0024/0001,0028/0001' PackSize='fixed,absolute' PackSizeProp='0002/0003,0073/0001' RStyleDefault='/Frontend.WestBorder.style' ScrollExtent='21,695' Size='21,695' Stretch='false' Style=' '/>
<Image BackgroundOpacity='1.000' Location='125,722' Name='SouthBorder' PackLocation='left,bottom' PackLocationProp='0125/0001,-046/0001' PackSize='absolute,fixed' PackSizeProp='0250/0001,0002/0003' RStyleDefault='/Frontend.SouthBorder.style' ScrollExtent='774,22' Size='774,22' Stretch='false' Style=' '/>
<Image BackgroundOpacity='1.000' Location='24,24' Name='NorthBorder' PackLocation='left,top' PackLocationProp='0024/0001,0024/0001' PackSize='absolute,fixed' PackSizeProp='0057/0001,0002/0003' RStyleDefault='/Frontend.NorthBorder.style' ScrollExtent='967,22' Size='967,22' Stretch='false' Style=' '/>
<Image Color='#E9DAC0' Name='Planet' ScrollExtent='1024,768' Size='1024,768' Stretch='false' Style='/Plates.PlanetBackground'/>
</Page>
<Namespace Name='Faces'>
<ImageStyle Name='Male01a'>
<ImageFrame SourceRect='0,0,81,130'>
<ImageFragment Source='ui_male_faces_1_00' SourceRect='0,0,256,256'/>
<ImageFragment Offset='0,256' Source='ui_male_faces_1_01' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,0' Source='ui_male_faces_1_02' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,0' Source='ui_male_faces_1_03' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,128' Source='ui_male_faces_1_04' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,128' Source='ui_male_faces_1_05' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,256' Source='ui_male_faces_1_06' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,256' Source='ui_male_faces_1_07' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,384' Source='ui_male_faces_1_08' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,384' Source='ui_male_faces_1_09' SourceRect='0,0,32,128'/>
</ImageFrame>
</ImageStyle>
<ImageStyle Name='Male01b'>
<ImageFrame SourceRect='81,0,162,130'>
<ImageFragment Source='ui_male_faces_1_00' SourceRect='0,0,256,256'/>
<ImageFragment Offset='0,256' Source='ui_male_faces_1_01' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,0' Source='ui_male_faces_1_02' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,0' Source='ui_male_faces_1_03' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,128' Source='ui_male_faces_1_04' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,128' Source='ui_male_faces_1_05' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,256' Source='ui_male_faces_1_06' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,256' Source='ui_male_faces_1_07' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,384' Source='ui_male_faces_1_08' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,384' Source='ui_male_faces_1_09' SourceRect='0,0,32,128'/>
</ImageFrame>
</ImageStyle>
<ImageStyle Name='Male01c'>
<ImageFrame SourceRect='162,0,243,130'>
<ImageFragment Source='ui_male_faces_1_00' SourceRect='0,0,256,256'/>
<ImageFragment Offset='0,256' Source='ui_male_faces_1_01' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,0' Source='ui_male_faces_1_02' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,0' Source='ui_male_faces_1_03' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,128' Source='ui_male_faces_1_04' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,128' Source='ui_male_faces_1_05' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,256' Source='ui_male_faces_1_06' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,256' Source='ui_male_faces_1_07' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,384' Source='ui_male_faces_1_08' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,384' Source='ui_male_faces_1_09' SourceRect='0,0,32,128'/>
</ImageFrame>
</ImageStyle>
<ImageStyle Name='Male01d'>
<ImageFrame SourceRect='243,0,324,130'>
<ImageFragment Source='ui_male_faces_1_00' SourceRect='0,0,256,256'/>
<ImageFragment Offset='0,256' Source='ui_male_faces_1_01' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,0' Source='ui_male_faces_1_02' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,0' Source='ui_male_faces_1_03' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,128' Source='ui_male_faces_1_04' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,128' Source='ui_male_faces_1_05' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,256' Source='ui_male_faces_1_06' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,256' Source='ui_male_faces_1_07' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,384' Source='ui_male_faces_1_08' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,384' Source='ui_male_faces_1_09' SourceRect='0,0,32,128'/>
</ImageFrame>
</ImageStyle>
<ImageStyle Name='Male01e'>
<ImageFrame SourceRect='324,0,405,130'>
<ImageFragment Source='ui_male_faces_1_00' SourceRect='0,0,256,256'/>
<ImageFragment Offset='0,256' Source='ui_male_faces_1_01' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,0' Source='ui_male_faces_1_02' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,0' Source='ui_male_faces_1_03' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,128' Source='ui_male_faces_1_04' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,128' Source='ui_male_faces_1_05' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,256' Source='ui_male_faces_1_06' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,256' Source='ui_male_faces_1_07' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,384' Source='ui_male_faces_1_08' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,384' Source='ui_male_faces_1_09' SourceRect='0,0,32,128'/>
</ImageFrame>
</ImageStyle>
<ImageStyle Name='Male02a'>
<ImageFrame SourceRect='0,130,81,260'>
<ImageFragment Source='ui_male_faces_1_00' SourceRect='0,0,256,256'/>
<ImageFragment Offset='0,256' Source='ui_male_faces_1_01' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,0' Source='ui_male_faces_1_02' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,0' Source='ui_male_faces_1_03' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,128' Source='ui_male_faces_1_04' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,128' Source='ui_male_faces_1_05' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,256' Source='ui_male_faces_1_06' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,256' Source='ui_male_faces_1_07' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,384' Source='ui_male_faces_1_08' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,384' Source='ui_male_faces_1_09' SourceRect='0,0,32,128'/>
</ImageFrame>
</ImageStyle>
<ImageStyle Name='Male02b'>
<ImageFrame SourceRect='81,130,162,260'>
<ImageFragment Source='ui_male_faces_1_00' SourceRect='0,0,256,256'/>
<ImageFragment Offset='0,256' Source='ui_male_faces_1_01' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,0' Source='ui_male_faces_1_02' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,0' Source='ui_male_faces_1_03' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,128' Source='ui_male_faces_1_04' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,128' Source='ui_male_faces_1_05' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,256' Source='ui_male_faces_1_06' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,256' Source='ui_male_faces_1_07' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,384' Source='ui_male_faces_1_08' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,384' Source='ui_male_faces_1_09' SourceRect='0,0,32,128'/>
</ImageFrame>
</ImageStyle>
<ImageStyle Name='Male02c'>
<ImageFrame SourceRect='162,130,243,260'>
<ImageFragment Source='ui_male_faces_1_00' SourceRect='0,0,256,256'/>
<ImageFragment Offset='0,256' Source='ui_male_faces_1_01' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,0' Source='ui_male_faces_1_02' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,0' Source='ui_male_faces_1_03' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,128' Source='ui_male_faces_1_04' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,128' Source='ui_male_faces_1_05' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,256' Source='ui_male_faces_1_06' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,256' Source='ui_male_faces_1_07' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,384' Source='ui_male_faces_1_08' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,384' Source='ui_male_faces_1_09' SourceRect='0,0,32,128'/>
</ImageFrame>
</ImageStyle>
<ImageStyle Name='Male02d'>
<ImageFrame SourceRect='243,130,324,260'>
<ImageFragment Source='ui_male_faces_1_00' SourceRect='0,0,256,256'/>
<ImageFragment Offset='0,256' Source='ui_male_faces_1_01' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,0' Source='ui_male_faces_1_02' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,0' Source='ui_male_faces_1_03' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,128' Source='ui_male_faces_1_04' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,128' Source='ui_male_faces_1_05' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,256' Source='ui_male_faces_1_06' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,256' Source='ui_male_faces_1_07' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,384' Source='ui_male_faces_1_08' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,384' Source='ui_male_faces_1_09' SourceRect='0,0,32,128'/>
</ImageFrame>
</ImageStyle>
<ImageStyle Name='Male02e'>
<ImageFrame SourceRect='324,130,405,260'>
<ImageFragment Source='ui_male_faces_1_00' SourceRect='0,0,256,256'/>
<ImageFragment Offset='0,256' Source='ui_male_faces_1_01' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,0' Source='ui_male_faces_1_02' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,0' Source='ui_male_faces_1_03' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,128' Source='ui_male_faces_1_04' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,128' Source='ui_male_faces_1_05' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,256' Source='ui_male_faces_1_06' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,256' Source='ui_male_faces_1_07' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,384' Source='ui_male_faces_1_08' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,384' Source='ui_male_faces_1_09' SourceRect='0,0,32,128'/>
</ImageFrame>
</ImageStyle>
<ImageStyle Name='Male03a'>
<ImageFrame SourceRect='0,260,81,390'>
<ImageFragment Source='ui_male_faces_1_00' SourceRect='0,0,256,256'/>
<ImageFragment Offset='0,256' Source='ui_male_faces_1_01' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,0' Source='ui_male_faces_1_02' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,0' Source='ui_male_faces_1_03' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,128' Source='ui_male_faces_1_04' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,128' Source='ui_male_faces_1_05' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,256' Source='ui_male_faces_1_06' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,256' Source='ui_male_faces_1_07' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,384' Source='ui_male_faces_1_08' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,384' Source='ui_male_faces_1_09' SourceRect='0,0,32,128'/>
</ImageFrame>
</ImageStyle>
<ImageStyle Name='Male03b'>
<ImageFrame SourceRect='81,260,162,390'>
<ImageFragment Source='ui_male_faces_1_00' SourceRect='0,0,256,256'/>
<ImageFragment Offset='0,256' Source='ui_male_faces_1_01' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,0' Source='ui_male_faces_1_02' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,0' Source='ui_male_faces_1_03' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,128' Source='ui_male_faces_1_04' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,128' Source='ui_male_faces_1_05' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,256' Source='ui_male_faces_1_06' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,256' Source='ui_male_faces_1_07' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,384' Source='ui_male_faces_1_08' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,384' Source='ui_male_faces_1_09' SourceRect='0,0,32,128'/>
</ImageFrame>
</ImageStyle>
<ImageStyle Name='Male03c'>
<ImageFrame SourceRect='162,260,243,390'>
<ImageFragment Source='ui_male_faces_1_00' SourceRect='0,0,256,256'/>
<ImageFragment Offset='0,256' Source='ui_male_faces_1_01' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,0' Source='ui_male_faces_1_02' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,0' Source='ui_male_faces_1_03' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,128' Source='ui_male_faces_1_04' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,128' Source='ui_male_faces_1_05' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,256' Source='ui_male_faces_1_06' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,256' Source='ui_male_faces_1_07' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,384' Source='ui_male_faces_1_08' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,384' Source='ui_male_faces_1_09' SourceRect='0,0,32,128'/>
</ImageFrame>
</ImageStyle>
<ImageStyle Name='Male03d'>
<ImageFrame SourceRect='243,260,324,390'>
<ImageFragment Source='ui_male_faces_1_00' SourceRect='0,0,256,256'/>
<ImageFragment Offset='0,256' Source='ui_male_faces_1_01' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,0' Source='ui_male_faces_1_02' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,0' Source='ui_male_faces_1_03' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,128' Source='ui_male_faces_1_04' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,128' Source='ui_male_faces_1_05' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,256' Source='ui_male_faces_1_06' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,256' Source='ui_male_faces_1_07' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,384' Source='ui_male_faces_1_08' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,384' Source='ui_male_faces_1_09' SourceRect='0,0,32,128'/>
</ImageFrame>
</ImageStyle>
<ImageStyle Name='Male03e'>
<ImageFrame SourceRect='324,260,405,390'>
<ImageFragment Source='ui_male_faces_1_00' SourceRect='0,0,256,256'/>
<ImageFragment Offset='0,256' Source='ui_male_faces_1_01' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,0' Source='ui_male_faces_1_02' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,0' Source='ui_male_faces_1_03' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,128' Source='ui_male_faces_1_04' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,128' Source='ui_male_faces_1_05' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,256' Source='ui_male_faces_1_06' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,256' Source='ui_male_faces_1_07' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,384' Source='ui_male_faces_1_08' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,384' Source='ui_male_faces_1_09' SourceRect='0,0,32,128'/>
</ImageFrame>
</ImageStyle>
<ImageStyle Name='Male04a'>
<ImageFrame SourceRect='0,390,81,520'>
<ImageFragment Source='ui_male_faces_1_00' SourceRect='0,0,256,256'/>
<ImageFragment Offset='0,256' Source='ui_male_faces_1_01' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,0' Source='ui_male_faces_1_02' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,0' Source='ui_male_faces_1_03' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,128' Source='ui_male_faces_1_04' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,128' Source='ui_male_faces_1_05' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,256' Source='ui_male_faces_1_06' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,256' Source='ui_male_faces_1_07' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,384' Source='ui_male_faces_1_08' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,384' Source='ui_male_faces_1_09' SourceRect='0,0,32,128'/>
</ImageFrame>
</ImageStyle>
<ImageStyle Name='Male04b'>
<ImageFrame SourceRect='81,390,162,520'>
<ImageFragment Source='ui_male_faces_1_00' SourceRect='0,0,256,256'/>
<ImageFragment Offset='0,256' Source='ui_male_faces_1_01' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,0' Source='ui_male_faces_1_02' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,0' Source='ui_male_faces_1_03' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,128' Source='ui_male_faces_1_04' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,128' Source='ui_male_faces_1_05' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,256' Source='ui_male_faces_1_06' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,256' Source='ui_male_faces_1_07' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,384' Source='ui_male_faces_1_08' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,384' Source='ui_male_faces_1_09' SourceRect='0,0,32,128'/>
</ImageFrame>
</ImageStyle>
<ImageStyle Name='Male04c'>
<ImageFrame SourceRect='162,390,243,520'>
<ImageFragment Source='ui_male_faces_1_00' SourceRect='0,0,256,256'/>
<ImageFragment Offset='0,256' Source='ui_male_faces_1_01' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,0' Source='ui_male_faces_1_02' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,0' Source='ui_male_faces_1_03' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,128' Source='ui_male_faces_1_04' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,128' Source='ui_male_faces_1_05' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,256' Source='ui_male_faces_1_06' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,256' Source='ui_male_faces_1_07' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,384' Source='ui_male_faces_1_08' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,384' Source='ui_male_faces_1_09' SourceRect='0,0,32,128'/>
</ImageFrame>
</ImageStyle>
<ImageStyle Name='Male04d'>
<ImageFrame SourceRect='243,390,324,520'>
<ImageFragment Source='ui_male_faces_1_00' SourceRect='0,0,256,256'/>
<ImageFragment Offset='0,256' Source='ui_male_faces_1_01' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,0' Source='ui_male_faces_1_02' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,0' Source='ui_male_faces_1_03' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,128' Source='ui_male_faces_1_04' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,128' Source='ui_male_faces_1_05' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,256' Source='ui_male_faces_1_06' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,256' Source='ui_male_faces_1_07' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,384' Source='ui_male_faces_1_08' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,384' Source='ui_male_faces_1_09' SourceRect='0,0,32,128'/>
</ImageFrame>
</ImageStyle>
<ImageStyle Name='Male04e'>
<ImageFrame SourceRect='324,390,405,520'>
<ImageFragment Source='ui_male_faces_1_00' SourceRect='0,0,256,256'/>
<ImageFragment Offset='0,256' Source='ui_male_faces_1_01' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,0' Source='ui_male_faces_1_02' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,0' Source='ui_male_faces_1_03' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,128' Source='ui_male_faces_1_04' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,128' Source='ui_male_faces_1_05' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,256' Source='ui_male_faces_1_06' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,256' Source='ui_male_faces_1_07' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,384' Source='ui_male_faces_1_08' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,384' Source='ui_male_faces_1_09' SourceRect='0,0,32,128'/>
</ImageFrame>
</ImageStyle>
<ImageStyle Name='Male05a'>
<ImageFrame SourceRect='0,0,81,130'>
<ImageFragment Source='ui_male_faces_2_00' SourceRect='0,0,256,256'/>
<ImageFragment Offset='0,256' Source='ui_male_faces_2_01' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,0' Source='ui_male_faces_2_02' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,0' Source='ui_male_faces_2_03' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,128' Source='ui_male_faces_2_04' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,128' Source='ui_male_faces_2_05' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,256' Source='ui_male_faces_2_06' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,256' Source='ui_male_faces_2_07' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,384' Source='ui_male_faces_2_08' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,384' Source='ui_male_faces_2_09' SourceRect='0,0,32,128'/>
</ImageFrame>
</ImageStyle>
<ImageStyle Name='Male05b'>
<ImageFrame SourceRect='81,0,162,130'>
<ImageFragment Source='ui_male_faces_2_00' SourceRect='0,0,256,256'/>
<ImageFragment Offset='0,256' Source='ui_male_faces_2_01' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,0' Source='ui_male_faces_2_02' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,0' Source='ui_male_faces_2_03' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,128' Source='ui_male_faces_2_04' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,128' Source='ui_male_faces_2_05' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,256' Source='ui_male_faces_2_06' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,256' Source='ui_male_faces_2_07' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,384' Source='ui_male_faces_2_08' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,384' Source='ui_male_faces_2_09' SourceRect='0,0,32,128'/>
</ImageFrame>
</ImageStyle>
<ImageStyle Name='Male05c'>
<ImageFrame SourceRect='162,0,243,130'>
<ImageFragment Source='ui_male_faces_2_00' SourceRect='0,0,256,256'/>
<ImageFragment Offset='0,256' Source='ui_male_faces_2_01' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,0' Source='ui_male_faces_2_02' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,0' Source='ui_male_faces_2_03' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,128' Source='ui_male_faces_2_04' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,128' Source='ui_male_faces_2_05' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,256' Source='ui_male_faces_2_06' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,256' Source='ui_male_faces_2_07' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,384' Source='ui_male_faces_2_08' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,384' Source='ui_male_faces_2_09' SourceRect='0,0,32,128'/>
</ImageFrame>
</ImageStyle>
<ImageStyle Name='Male05d'>
<ImageFrame SourceRect='243,0,324,130'>
<ImageFragment Source='ui_male_faces_2_00' SourceRect='0,0,256,256'/>
<ImageFragment Offset='0,256' Source='ui_male_faces_2_01' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,0' Source='ui_male_faces_2_02' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,0' Source='ui_male_faces_2_03' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,128' Source='ui_male_faces_2_04' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,128' Source='ui_male_faces_2_05' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,256' Source='ui_male_faces_2_06' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,256' Source='ui_male_faces_2_07' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,384' Source='ui_male_faces_2_08' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,384' Source='ui_male_faces_2_09' SourceRect='0,0,32,128'/>
</ImageFrame>
</ImageStyle>
<ImageStyle Name='Male05e'>
<ImageFrame SourceRect='324,0,405,130'>
<ImageFragment Source='ui_male_faces_2_00' SourceRect='0,0,256,256'/>
<ImageFragment Offset='0,256' Source='ui_male_faces_2_01' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,0' Source='ui_male_faces_2_02' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,0' Source='ui_male_faces_2_03' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,128' Source='ui_male_faces_2_04' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,128' Source='ui_male_faces_2_05' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,256' Source='ui_male_faces_2_06' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,256' Source='ui_male_faces_2_07' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,384' Source='ui_male_faces_2_08' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,384' Source='ui_male_faces_2_09' SourceRect='0,0,32,128'/>
</ImageFrame>
</ImageStyle>
<ImageStyle Name='Male06a'>
<ImageFrame SourceRect='0,130,81,260'>
<ImageFragment Source='ui_male_faces_2_00' SourceRect='0,0,256,256'/>
<ImageFragment Offset='0,256' Source='ui_male_faces_2_01' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,0' Source='ui_male_faces_2_02' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,0' Source='ui_male_faces_2_03' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,128' Source='ui_male_faces_2_04' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,128' Source='ui_male_faces_2_05' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,256' Source='ui_male_faces_2_06' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,256' Source='ui_male_faces_2_07' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,384' Source='ui_male_faces_2_08' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,384' Source='ui_male_faces_2_09' SourceRect='0,0,32,128'/>
</ImageFrame>
</ImageStyle>
<ImageStyle Name='Male06b'>
<ImageFrame SourceRect='81,130,162,260'>
<ImageFragment Source='ui_male_faces_2_00' SourceRect='0,0,256,256'/>
<ImageFragment Offset='0,256' Source='ui_male_faces_2_01' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,0' Source='ui_male_faces_2_02' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,0' Source='ui_male_faces_2_03' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,128' Source='ui_male_faces_2_04' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,128' Source='ui_male_faces_2_05' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,256' Source='ui_male_faces_2_06' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,256' Source='ui_male_faces_2_07' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,384' Source='ui_male_faces_2_08' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,384' Source='ui_male_faces_2_09' SourceRect='0,0,32,128'/>
</ImageFrame>
</ImageStyle>
<ImageStyle Name='Male06c'>
<ImageFrame SourceRect='162,130,243,260'>
<ImageFragment Source='ui_male_faces_2_00' SourceRect='0,0,256,256'/>
<ImageFragment Offset='0,256' Source='ui_male_faces_2_01' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,0' Source='ui_male_faces_2_02' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,0' Source='ui_male_faces_2_03' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,128' Source='ui_male_faces_2_04' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,128' Source='ui_male_faces_2_05' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,256' Source='ui_male_faces_2_06' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,256' Source='ui_male_faces_2_07' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,384' Source='ui_male_faces_2_08' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,384' Source='ui_male_faces_2_09' SourceRect='0,0,32,128'/>
</ImageFrame>
</ImageStyle>
<ImageStyle Name='Male06d'>
<ImageFrame SourceRect='243,130,324,260'>
<ImageFragment Source='ui_male_faces_2_00' SourceRect='0,0,256,256'/>
<ImageFragment Offset='0,256' Source='ui_male_faces_2_01' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,0' Source='ui_male_faces_2_02' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,0' Source='ui_male_faces_2_03' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,128' Source='ui_male_faces_2_04' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,128' Source='ui_male_faces_2_05' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,256' Source='ui_male_faces_2_06' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,256' Source='ui_male_faces_2_07' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,384' Source='ui_male_faces_2_08' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,384' Source='ui_male_faces_2_09' SourceRect='0,0,32,128'/>
</ImageFrame>
</ImageStyle>
<ImageStyle Name='Male06e'>
<ImageFrame SourceRect='324,130,405,260'>
<ImageFragment Source='ui_male_faces_2_00' SourceRect='0,0,256,256'/>
<ImageFragment Offset='0,256' Source='ui_male_faces_2_01' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,0' Source='ui_male_faces_2_02' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,0' Source='ui_male_faces_2_03' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,128' Source='ui_male_faces_2_04' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,128' Source='ui_male_faces_2_05' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,256' Source='ui_male_faces_2_06' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,256' Source='ui_male_faces_2_07' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,384' Source='ui_male_faces_2_08' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,384' Source='ui_male_faces_2_09' SourceRect='0,0,32,128'/>
</ImageFrame>
</ImageStyle>
<ImageStyle Name='Male07a'>
<ImageFrame SourceRect='0,260,81,390'>
<ImageFragment Source='ui_male_faces_2_00' SourceRect='0,0,256,256'/>
<ImageFragment Offset='0,256' Source='ui_male_faces_2_01' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,0' Source='ui_male_faces_2_02' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,0' Source='ui_male_faces_2_03' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,128' Source='ui_male_faces_2_04' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,128' Source='ui_male_faces_2_05' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,256' Source='ui_male_faces_2_06' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,256' Source='ui_male_faces_2_07' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,384' Source='ui_male_faces_2_08' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,384' Source='ui_male_faces_2_09' SourceRect='0,0,32,128'/>
</ImageFrame>
</ImageStyle>
<ImageStyle Name='Male07b'>
<ImageFrame SourceRect='81,260,162,390'>
<ImageFragment Source='ui_male_faces_2_00' SourceRect='0,0,256,256'/>
<ImageFragment Offset='0,256' Source='ui_male_faces_2_01' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,0' Source='ui_male_faces_2_02' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,0' Source='ui_male_faces_2_03' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,128' Source='ui_male_faces_2_04' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,128' Source='ui_male_faces_2_05' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,256' Source='ui_male_faces_2_06' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,256' Source='ui_male_faces_2_07' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,384' Source='ui_male_faces_2_08' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,384' Source='ui_male_faces_2_09' SourceRect='0,0,32,128'/>
</ImageFrame>
</ImageStyle>
<ImageStyle Name='Male07c'>
<ImageFrame SourceRect='162,260,243,390'>
<ImageFragment Source='ui_male_faces_2_00' SourceRect='0,0,256,256'/>
<ImageFragment Offset='0,256' Source='ui_male_faces_2_01' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,0' Source='ui_male_faces_2_02' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,0' Source='ui_male_faces_2_03' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,128' Source='ui_male_faces_2_04' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,128' Source='ui_male_faces_2_05' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,256' Source='ui_male_faces_2_06' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,256' Source='ui_male_faces_2_07' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,384' Source='ui_male_faces_2_08' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,384' Source='ui_male_faces_2_09' SourceRect='0,0,32,128'/>
</ImageFrame>
</ImageStyle>
<ImageStyle Name='Male07d'>
<ImageFrame SourceRect='243,260,324,390'>
<ImageFragment Source='ui_male_faces_2_00' SourceRect='0,0,256,256'/>
<ImageFragment Offset='0,256' Source='ui_male_faces_2_01' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,0' Source='ui_male_faces_2_02' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,0' Source='ui_male_faces_2_03' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,128' Source='ui_male_faces_2_04' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,128' Source='ui_male_faces_2_05' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,256' Source='ui_male_faces_2_06' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,256' Source='ui_male_faces_2_07' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,384' Source='ui_male_faces_2_08' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,384' Source='ui_male_faces_2_09' SourceRect='0,0,32,128'/>
</ImageFrame>
</ImageStyle>
<ImageStyle Name='Male07e'>
<ImageFrame SourceRect='324,260,405,390'>
<ImageFragment Source='ui_male_faces_2_00' SourceRect='0,0,256,256'/>
<ImageFragment Offset='0,256' Source='ui_male_faces_2_01' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,0' Source='ui_male_faces_2_02' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,0' Source='ui_male_faces_2_03' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,128' Source='ui_male_faces_2_04' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,128' Source='ui_male_faces_2_05' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,256' Source='ui_male_faces_2_06' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,256' Source='ui_male_faces_2_07' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,384' Source='ui_male_faces_2_08' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,384' Source='ui_male_faces_2_09' SourceRect='0,0,32,128'/>
</ImageFrame>
</ImageStyle>
<ImageStyle Name='Male08a'>
<ImageFrame SourceRect='0,390,81,520'>
<ImageFragment Source='ui_male_faces_2_00' SourceRect='0,0,256,256'/>
<ImageFragment Offset='0,256' Source='ui_male_faces_2_01' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,0' Source='ui_male_faces_2_02' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,0' Source='ui_male_faces_2_03' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,128' Source='ui_male_faces_2_04' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,128' Source='ui_male_faces_2_05' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,256' Source='ui_male_faces_2_06' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,256' Source='ui_male_faces_2_07' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,384' Source='ui_male_faces_2_08' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,384' Source='ui_male_faces_2_09' SourceRect='0,0,32,128'/>
</ImageFrame>
</ImageStyle>
<ImageStyle Name='Male08b'>
<ImageFrame SourceRect='81,390,162,520'>
<ImageFragment Source='ui_male_faces_2_00' SourceRect='0,0,256,256'/>
<ImageFragment Offset='0,256' Source='ui_male_faces_2_01' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,0' Source='ui_male_faces_2_02' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,0' Source='ui_male_faces_2_03' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,128' Source='ui_male_faces_2_04' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,128' Source='ui_male_faces_2_05' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,256' Source='ui_male_faces_2_06' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,256' Source='ui_male_faces_2_07' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,384' Source='ui_male_faces_2_08' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,384' Source='ui_male_faces_2_09' SourceRect='0,0,32,128'/>
</ImageFrame>
</ImageStyle>
<ImageStyle Name='Male08c'>
<ImageFrame SourceRect='162,390,243,520'>
<ImageFragment Source='ui_male_faces_2_00' SourceRect='0,0,256,256'/>
<ImageFragment Offset='0,256' Source='ui_male_faces_2_01' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,0' Source='ui_male_faces_2_02' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,0' Source='ui_male_faces_2_03' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,128' Source='ui_male_faces_2_04' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,128' Source='ui_male_faces_2_05' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,256' Source='ui_male_faces_2_06' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,256' Source='ui_male_faces_2_07' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,384' Source='ui_male_faces_2_08' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,384' Source='ui_male_faces_2_09' SourceRect='0,0,32,128'/>
</ImageFrame>
</ImageStyle>
<ImageStyle Name='Male08d'>
<ImageFrame SourceRect='243,390,324,520'>
<ImageFragment Source='ui_male_faces_2_00' SourceRect='0,0,256,256'/>
<ImageFragment Offset='0,256' Source='ui_male_faces_2_01' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,0' Source='ui_male_faces_2_02' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,0' Source='ui_male_faces_2_03' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,128' Source='ui_male_faces_2_04' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,128' Source='ui_male_faces_2_05' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,256' Source='ui_male_faces_2_06' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,256' Source='ui_male_faces_2_07' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,384' Source='ui_male_faces_2_08' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,384' Source='ui_male_faces_2_09' SourceRect='0,0,32,128'/>
</ImageFrame>
</ImageStyle>
<ImageStyle Name='Male08e'>
<ImageFrame SourceRect='324,390,405,520'>
<ImageFragment Source='ui_male_faces_2_00' SourceRect='0,0,256,256'/>
<ImageFragment Offset='0,256' Source='ui_male_faces_2_01' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,0' Source='ui_male_faces_2_02' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,0' Source='ui_male_faces_2_03' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,128' Source='ui_male_faces_2_04' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,128' Source='ui_male_faces_2_05' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,256' Source='ui_male_faces_2_06' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,256' Source='ui_male_faces_2_07' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,384' Source='ui_male_faces_2_08' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,384' Source='ui_male_faces_2_09' SourceRect='0,0,32,128'/>
</ImageFrame>
</ImageStyle>
<ImageStyle Name='Male09a'>
<ImageFrame SourceRect='0,0,81,130'>
<ImageFragment Source='ui_male_faces_3_00' SourceRect='0,0,256,256'/>
<ImageFragment Offset='0,256' Source='ui_male_faces_3_01' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,0' Source='ui_male_faces_3_02' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,0' Source='ui_male_faces_3_03' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,128' Source='ui_male_faces_3_04' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,128' Source='ui_male_faces_3_05' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,256' Source='ui_male_faces_3_06' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,256' Source='ui_male_faces_3_07' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,384' Source='ui_male_faces_3_08' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,384' Source='ui_male_faces_3_09' SourceRect='0,0,32,128'/>
</ImageFrame>
</ImageStyle>
<ImageStyle Name='Male09b'>
<ImageFrame SourceRect='81,0,162,130'>
<ImageFragment Source='ui_male_faces_3_00' SourceRect='0,0,256,256'/>
<ImageFragment Offset='0,256' Source='ui_male_faces_3_01' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,0' Source='ui_male_faces_3_02' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,0' Source='ui_male_faces_3_03' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,128' Source='ui_male_faces_3_04' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,128' Source='ui_male_faces_3_05' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,256' Source='ui_male_faces_3_06' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,256' Source='ui_male_faces_3_07' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,384' Source='ui_male_faces_3_08' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,384' Source='ui_male_faces_3_09' SourceRect='0,0,32,128'/>
</ImageFrame>
</ImageStyle>
<ImageStyle Name='Male09c'>
<ImageFrame SourceRect='162,0,243,130'>
<ImageFragment Source='ui_male_faces_3_00' SourceRect='0,0,256,256'/>
<ImageFragment Offset='0,256' Source='ui_male_faces_3_01' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,0' Source='ui_male_faces_3_02' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,0' Source='ui_male_faces_3_03' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,128' Source='ui_male_faces_3_04' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,128' Source='ui_male_faces_3_05' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,256' Source='ui_male_faces_3_06' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,256' Source='ui_male_faces_3_07' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,384' Source='ui_male_faces_3_08' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,384' Source='ui_male_faces_3_09' SourceRect='0,0,32,128'/>
</ImageFrame>
</ImageStyle>
<ImageStyle Name='Male09d'>
<ImageFrame SourceRect='243,0,324,130'>
<ImageFragment Source='ui_male_faces_3_00' SourceRect='0,0,256,256'/>
<ImageFragment Offset='0,256' Source='ui_male_faces_3_01' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,0' Source='ui_male_faces_3_02' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,0' Source='ui_male_faces_3_03' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,128' Source='ui_male_faces_3_04' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,128' Source='ui_male_faces_3_05' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,256' Source='ui_male_faces_3_06' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,256' Source='ui_male_faces_3_07' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,384' Source='ui_male_faces_3_08' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,384' Source='ui_male_faces_3_09' SourceRect='0,0,32,128'/>
</ImageFrame>
</ImageStyle>
<ImageStyle Name='Male09e'>
<ImageFrame SourceRect='324,0,405,130'>
<ImageFragment Source='ui_male_faces_3_00' SourceRect='0,0,256,256'/>
<ImageFragment Offset='0,256' Source='ui_male_faces_3_01' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,0' Source='ui_male_faces_3_02' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,0' Source='ui_male_faces_3_03' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,128' Source='ui_male_faces_3_04' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,128' Source='ui_male_faces_3_05' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,256' Source='ui_male_faces_3_06' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,256' Source='ui_male_faces_3_07' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,384' Source='ui_male_faces_3_08' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,384' Source='ui_male_faces_3_09' SourceRect='0,0,32,128'/>
</ImageFrame>
</ImageStyle>
<ImageStyle Name='Male10a'>
<ImageFrame SourceRect='0,130,81,260'>
<ImageFragment Source='ui_male_faces_3_00' SourceRect='0,0,256,256'/>
<ImageFragment Offset='0,256' Source='ui_male_faces_3_01' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,0' Source='ui_male_faces_3_02' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,0' Source='ui_male_faces_3_03' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,128' Source='ui_male_faces_3_04' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,128' Source='ui_male_faces_3_05' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,256' Source='ui_male_faces_3_06' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,256' Source='ui_male_faces_3_07' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,384' Source='ui_male_faces_3_08' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,384' Source='ui_male_faces_3_09' SourceRect='0,0,32,128'/>
</ImageFrame>
</ImageStyle>
<ImageStyle Name='Male10b'>
<ImageFrame SourceRect='81,130,162,260'>
<ImageFragment Source='ui_male_faces_3_00' SourceRect='0,0,256,256'/>
<ImageFragment Offset='0,256' Source='ui_male_faces_3_01' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,0' Source='ui_male_faces_3_02' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,0' Source='ui_male_faces_3_03' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,128' Source='ui_male_faces_3_04' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,128' Source='ui_male_faces_3_05' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,256' Source='ui_male_faces_3_06' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,256' Source='ui_male_faces_3_07' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,384' Source='ui_male_faces_3_08' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,384' Source='ui_male_faces_3_09' SourceRect='0,0,32,128'/>
</ImageFrame>
</ImageStyle>
<ImageStyle Name='Male10c'>
<ImageFrame SourceRect='162,130,243,260'>
<ImageFragment Source='ui_male_faces_3_00' SourceRect='0,0,256,256'/>
<ImageFragment Offset='0,256' Source='ui_male_faces_3_01' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,0' Source='ui_male_faces_3_02' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,0' Source='ui_male_faces_3_03' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,128' Source='ui_male_faces_3_04' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,128' Source='ui_male_faces_3_05' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,256' Source='ui_male_faces_3_06' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,256' Source='ui_male_faces_3_07' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,384' Source='ui_male_faces_3_08' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,384' Source='ui_male_faces_3_09' SourceRect='0,0,32,128'/>
</ImageFrame>
</ImageStyle>
<ImageStyle Name='Male10d'>
<ImageFrame SourceRect='243,130,324,260'>
<ImageFragment Source='ui_male_faces_3_00' SourceRect='0,0,256,256'/>
<ImageFragment Offset='0,256' Source='ui_male_faces_3_01' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,0' Source='ui_male_faces_3_02' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,0' Source='ui_male_faces_3_03' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,128' Source='ui_male_faces_3_04' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,128' Source='ui_male_faces_3_05' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,256' Source='ui_male_faces_3_06' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,256' Source='ui_male_faces_3_07' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,384' Source='ui_male_faces_3_08' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,384' Source='ui_male_faces_3_09' SourceRect='0,0,32,128'/>
</ImageFrame>
</ImageStyle>
<ImageStyle Name='Male10e'>
<ImageFrame SourceRect='324,130,405,260'>
<ImageFragment Source='ui_male_faces_3_00' SourceRect='0,0,256,256'/>
<ImageFragment Offset='0,256' Source='ui_male_faces_3_01' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,0' Source='ui_male_faces_3_02' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,0' Source='ui_male_faces_3_03' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,128' Source='ui_male_faces_3_04' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,128' Source='ui_male_faces_3_05' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,256' Source='ui_male_faces_3_06' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,256' Source='ui_male_faces_3_07' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,384' Source='ui_male_faces_3_08' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,384' Source='ui_male_faces_3_09' SourceRect='0,0,32,128'/>
</ImageFrame>
</ImageStyle>
<ImageStyle Name='Male11a'>
<ImageFrame SourceRect='0,260,81,390'>
<ImageFragment Source='ui_male_faces_3_00' SourceRect='0,0,256,256'/>
<ImageFragment Offset='0,256' Source='ui_male_faces_3_01' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,0' Source='ui_male_faces_3_02' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,0' Source='ui_male_faces_3_03' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,128' Source='ui_male_faces_3_04' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,128' Source='ui_male_faces_3_05' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,256' Source='ui_male_faces_3_06' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,256' Source='ui_male_faces_3_07' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,384' Source='ui_male_faces_3_08' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,384' Source='ui_male_faces_3_09' SourceRect='0,0,32,128'/>
</ImageFrame>
</ImageStyle>
<ImageStyle Name='Male11b'>
<ImageFrame SourceRect='81,260,162,390'>
<ImageFragment Source='ui_male_faces_3_00' SourceRect='0,0,256,256'/>
<ImageFragment Offset='0,256' Source='ui_male_faces_3_01' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,0' Source='ui_male_faces_3_02' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,0' Source='ui_male_faces_3_03' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,128' Source='ui_male_faces_3_04' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,128' Source='ui_male_faces_3_05' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,256' Source='ui_male_faces_3_06' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,256' Source='ui_male_faces_3_07' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,384' Source='ui_male_faces_3_08' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,384' Source='ui_male_faces_3_09' SourceRect='0,0,32,128'/>
</ImageFrame>
</ImageStyle>
<ImageStyle Name='Male11c'>
<ImageFrame SourceRect='162,260,243,390'>
<ImageFragment Source='ui_male_faces_3_00' SourceRect='0,0,256,256'/>
<ImageFragment Offset='0,256' Source='ui_male_faces_3_01' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,0' Source='ui_male_faces_3_02' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,0' Source='ui_male_faces_3_03' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,128' Source='ui_male_faces_3_04' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,128' Source='ui_male_faces_3_05' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,256' Source='ui_male_faces_3_06' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,256' Source='ui_male_faces_3_07' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,384' Source='ui_male_faces_3_08' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,384' Source='ui_male_faces_3_09' SourceRect='0,0,32,128'/>
</ImageFrame>
</ImageStyle>
<ImageStyle Name='Male11d'>
<ImageFrame SourceRect='243,260,324,390'>
<ImageFragment Source='ui_male_faces_3_00' SourceRect='0,0,256,256'/>
<ImageFragment Offset='0,256' Source='ui_male_faces_3_01' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,0' Source='ui_male_faces_3_02' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,0' Source='ui_male_faces_3_03' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,128' Source='ui_male_faces_3_04' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,128' Source='ui_male_faces_3_05' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,256' Source='ui_male_faces_3_06' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,256' Source='ui_male_faces_3_07' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,384' Source='ui_male_faces_3_08' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,384' Source='ui_male_faces_3_09' SourceRect='0,0,32,128'/>
</ImageFrame>
</ImageStyle>
<ImageStyle Name='Male11e'>
<ImageFrame SourceRect='324,260,405,390'>
<ImageFragment Source='ui_male_faces_3_00' SourceRect='0,0,256,256'/>
<ImageFragment Offset='0,256' Source='ui_male_faces_3_01' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,0' Source='ui_male_faces_3_02' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,0' Source='ui_male_faces_3_03' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,128' Source='ui_male_faces_3_04' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,128' Source='ui_male_faces_3_05' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,256' Source='ui_male_faces_3_06' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,256' Source='ui_male_faces_3_07' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,384' Source='ui_male_faces_3_08' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,384' Source='ui_male_faces_3_09' SourceRect='0,0,32,128'/>
</ImageFrame>
</ImageStyle>
<ImageStyle Name='Female01a'>
<ImageFrame SourceRect='0,0,81,130'>
<ImageFragment Source='ui_female_faces_1_00' SourceRect='0,0,256,256'/>
<ImageFragment Offset='0,256' Source='ui_female_faces_1_01' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,0' Source='ui_female_faces_1_02' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,0' Source='ui_female_faces_1_03' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,128' Source='ui_female_faces_1_04' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,128' Source='ui_female_faces_1_05' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,256' Source='ui_female_faces_1_06' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,256' Source='ui_female_faces_1_07' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,384' Source='ui_female_faces_1_08' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,384' Source='ui_female_faces_1_09' SourceRect='0,0,32,128'/>
</ImageFrame>
</ImageStyle>
<ImageStyle Name='Female01b'>
<ImageFrame SourceRect='81,0,162,128'>
<ImageFragment Source='ui_female_faces_1_00' SourceRect='0,0,256,256'/>
<ImageFragment Offset='0,256' Source='ui_female_faces_1_01' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,0' Source='ui_female_faces_1_02' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,0' Source='ui_female_faces_1_03' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,128' Source='ui_female_faces_1_04' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,128' Source='ui_female_faces_1_05' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,256' Source='ui_female_faces_1_06' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,256' Source='ui_female_faces_1_07' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,384' Source='ui_female_faces_1_08' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,384' Source='ui_female_faces_1_09' SourceRect='0,0,32,128'/>
</ImageFrame>
</ImageStyle>
<ImageStyle Name='Female01c'>
<ImageFrame SourceRect='162,0,243,130'>
<ImageFragment Source='ui_female_faces_1_00' SourceRect='0,0,256,256'/>
<ImageFragment Offset='0,256' Source='ui_female_faces_1_01' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,0' Source='ui_female_faces_1_02' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,0' Source='ui_female_faces_1_03' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,128' Source='ui_female_faces_1_04' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,128' Source='ui_female_faces_1_05' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,256' Source='ui_female_faces_1_06' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,256' Source='ui_female_faces_1_07' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,384' Source='ui_female_faces_1_08' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,384' Source='ui_female_faces_1_09' SourceRect='0,0,32,128'/>
</ImageFrame>
</ImageStyle>
<ImageStyle Name='Female01d'>
<ImageFrame SourceRect='243,0,324,130'>
<ImageFragment Source='ui_female_faces_1_00' SourceRect='0,0,256,256'/>
<ImageFragment Offset='0,256' Source='ui_female_faces_1_01' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,0' Source='ui_female_faces_1_02' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,0' Source='ui_female_faces_1_03' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,128' Source='ui_female_faces_1_04' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,128' Source='ui_female_faces_1_05' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,256' Source='ui_female_faces_1_06' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,256' Source='ui_female_faces_1_07' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,384' Source='ui_female_faces_1_08' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,384' Source='ui_female_faces_1_09' SourceRect='0,0,32,128'/>
</ImageFrame>
</ImageStyle>
<ImageStyle Name='Female01e'>
<ImageFrame SourceRect='324,0,405,130'>
<ImageFragment Source='ui_female_faces_1_00' SourceRect='0,0,256,256'/>
<ImageFragment Offset='0,256' Source='ui_female_faces_1_01' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,0' Source='ui_female_faces_1_02' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,0' Source='ui_female_faces_1_03' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,128' Source='ui_female_faces_1_04' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,128' Source='ui_female_faces_1_05' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,256' Source='ui_female_faces_1_06' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,256' Source='ui_female_faces_1_07' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,384' Source='ui_female_faces_1_08' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,384' Source='ui_female_faces_1_09' SourceRect='0,0,32,128'/>
</ImageFrame>
</ImageStyle>
<ImageStyle Name='Female02a'>
<ImageFrame SourceRect='0,130,81,260'>
<ImageFragment Source='ui_female_faces_1_00' SourceRect='0,0,256,256'/>
<ImageFragment Offset='0,256' Source='ui_female_faces_1_01' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,0' Source='ui_female_faces_1_02' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,0' Source='ui_female_faces_1_03' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,128' Source='ui_female_faces_1_04' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,128' Source='ui_female_faces_1_05' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,256' Source='ui_female_faces_1_06' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,256' Source='ui_female_faces_1_07' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,384' Source='ui_female_faces_1_08' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,384' Source='ui_female_faces_1_09' SourceRect='0,0,32,128'/>
</ImageFrame>
</ImageStyle>
<ImageStyle Name='Female02b'>
<ImageFrame SourceRect='81,128,162,256'>
<ImageFragment Source='ui_female_faces_1_00' SourceRect='0,0,256,256'/>
<ImageFragment Offset='0,256' Source='ui_female_faces_1_01' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,0' Source='ui_female_faces_1_02' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,0' Source='ui_female_faces_1_03' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,128' Source='ui_female_faces_1_04' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,128' Source='ui_female_faces_1_05' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,256' Source='ui_female_faces_1_06' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,256' Source='ui_female_faces_1_07' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,384' Source='ui_female_faces_1_08' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,384' Source='ui_female_faces_1_09' SourceRect='0,0,32,128'/>
</ImageFrame>
</ImageStyle>
<ImageStyle Name='Female02c'>
<ImageFrame SourceRect='162,130,243,260'>
<ImageFragment Source='ui_female_faces_1_00' SourceRect='0,0,256,256'/>
<ImageFragment Offset='0,256' Source='ui_female_faces_1_01' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,0' Source='ui_female_faces_1_02' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,0' Source='ui_female_faces_1_03' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,128' Source='ui_female_faces_1_04' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,128' Source='ui_female_faces_1_05' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,256' Source='ui_female_faces_1_06' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,256' Source='ui_female_faces_1_07' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,384' Source='ui_female_faces_1_08' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,384' Source='ui_female_faces_1_09' SourceRect='0,0,32,128'/>
</ImageFrame>
</ImageStyle>
<ImageStyle Name='Female02d'>
<ImageFrame SourceRect='243,130,324,260'>
<ImageFragment Source='ui_female_faces_1_00' SourceRect='0,0,256,256'/>
<ImageFragment Offset='0,256' Source='ui_female_faces_1_01' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,0' Source='ui_female_faces_1_02' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,0' Source='ui_female_faces_1_03' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,128' Source='ui_female_faces_1_04' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,128' Source='ui_female_faces_1_05' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,256' Source='ui_female_faces_1_06' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,256' Source='ui_female_faces_1_07' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,384' Source='ui_female_faces_1_08' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,384' Source='ui_female_faces_1_09' SourceRect='0,0,32,128'/>
</ImageFrame>
</ImageStyle>
<ImageStyle Name='Female02e'>
<ImageFrame SourceRect='324,130,405,260'>
<ImageFragment Source='ui_female_faces_1_00' SourceRect='0,0,256,256'/>
<ImageFragment Offset='0,256' Source='ui_female_faces_1_01' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,0' Source='ui_female_faces_1_02' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,0' Source='ui_female_faces_1_03' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,128' Source='ui_female_faces_1_04' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,128' Source='ui_female_faces_1_05' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,256' Source='ui_female_faces_1_06' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,256' Source='ui_female_faces_1_07' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,384' Source='ui_female_faces_1_08' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,384' Source='ui_female_faces_1_09' SourceRect='0,0,32,128'/>
</ImageFrame>
</ImageStyle>
<ImageStyle Name='Female03a'>
<ImageFrame SourceRect='0,260,81,390'>
<ImageFragment Source='ui_female_faces_1_00' SourceRect='0,0,256,256'/>
<ImageFragment Offset='0,256' Source='ui_female_faces_1_01' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,0' Source='ui_female_faces_1_02' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,0' Source='ui_female_faces_1_03' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,128' Source='ui_female_faces_1_04' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,128' Source='ui_female_faces_1_05' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,256' Source='ui_female_faces_1_06' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,256' Source='ui_female_faces_1_07' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,384' Source='ui_female_faces_1_08' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,384' Source='ui_female_faces_1_09' SourceRect='0,0,32,128'/>
</ImageFrame>
</ImageStyle>
<ImageStyle Name='Female03b'>
<ImageFrame SourceRect='81,256,162,384'>
<ImageFragment Source='ui_female_faces_1_00' SourceRect='0,0,256,256'/>
<ImageFragment Offset='0,256' Source='ui_female_faces_1_01' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,0' Source='ui_female_faces_1_02' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,0' Source='ui_female_faces_1_03' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,128' Source='ui_female_faces_1_04' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,128' Source='ui_female_faces_1_05' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,256' Source='ui_female_faces_1_06' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,256' Source='ui_female_faces_1_07' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,384' Source='ui_female_faces_1_08' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,384' Source='ui_female_faces_1_09' SourceRect='0,0,32,128'/>
</ImageFrame>
</ImageStyle>
<ImageStyle Name='Female03c'>
<ImageFrame SourceRect='162,260,243,390'>
<ImageFragment Source='ui_female_faces_1_00' SourceRect='0,0,256,256'/>
<ImageFragment Offset='0,256' Source='ui_female_faces_1_01' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,0' Source='ui_female_faces_1_02' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,0' Source='ui_female_faces_1_03' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,128' Source='ui_female_faces_1_04' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,128' Source='ui_female_faces_1_05' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,256' Source='ui_female_faces_1_06' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,256' Source='ui_female_faces_1_07' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,384' Source='ui_female_faces_1_08' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,384' Source='ui_female_faces_1_09' SourceRect='0,0,32,128'/>
</ImageFrame>
</ImageStyle>
<ImageStyle Name='Female03d'>
<ImageFrame SourceRect='243,260,324,390'>
<ImageFragment Source='ui_female_faces_1_00' SourceRect='0,0,256,256'/>
<ImageFragment Offset='0,256' Source='ui_female_faces_1_01' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,0' Source='ui_female_faces_1_02' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,0' Source='ui_female_faces_1_03' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,128' Source='ui_female_faces_1_04' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,128' Source='ui_female_faces_1_05' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,256' Source='ui_female_faces_1_06' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,256' Source='ui_female_faces_1_07' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,384' Source='ui_female_faces_1_08' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,384' Source='ui_female_faces_1_09' SourceRect='0,0,32,128'/>
</ImageFrame>
</ImageStyle>
<ImageStyle Name='Female03e'>
<ImageFrame SourceRect='324,260,405,390'>
<ImageFragment Source='ui_female_faces_1_00' SourceRect='0,0,256,256'/>
<ImageFragment Offset='0,256' Source='ui_female_faces_1_01' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,0' Source='ui_female_faces_1_02' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,0' Source='ui_female_faces_1_03' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,128' Source='ui_female_faces_1_04' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,128' Source='ui_female_faces_1_05' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,256' Source='ui_female_faces_1_06' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,256' Source='ui_female_faces_1_07' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,384' Source='ui_female_faces_1_08' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,384' Source='ui_female_faces_1_09' SourceRect='0,0,32,128'/>
</ImageFrame>
</ImageStyle>
<ImageStyle Name='Female04a'>
<ImageFrame SourceRect='0,390,81,520'>
<ImageFragment Source='ui_female_faces_1_00' SourceRect='0,0,256,256'/>
<ImageFragment Offset='0,256' Source='ui_female_faces_1_01' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,0' Source='ui_female_faces_1_02' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,0' Source='ui_female_faces_1_03' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,128' Source='ui_female_faces_1_04' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,128' Source='ui_female_faces_1_05' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,256' Source='ui_female_faces_1_06' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,256' Source='ui_female_faces_1_07' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,384' Source='ui_female_faces_1_08' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,384' Source='ui_female_faces_1_09' SourceRect='0,0,32,128'/>
</ImageFrame>
</ImageStyle>
<ImageStyle Name='Female04b'>
<ImageFrame SourceRect='81,384,162,512'>
<ImageFragment Source='ui_female_faces_1_00' SourceRect='0,0,256,256'/>
<ImageFragment Offset='0,256' Source='ui_female_faces_1_01' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,0' Source='ui_female_faces_1_02' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,0' Source='ui_female_faces_1_03' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,128' Source='ui_female_faces_1_04' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,128' Source='ui_female_faces_1_05' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,256' Source='ui_female_faces_1_06' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,256' Source='ui_female_faces_1_07' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,384' Source='ui_female_faces_1_08' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,384' Source='ui_female_faces_1_09' SourceRect='0,0,32,128'/>
</ImageFrame>
</ImageStyle>
<ImageStyle Name='Female04c'>
<ImageFrame SourceRect='162,390,243,520'>
<ImageFragment Source='ui_female_faces_1_00' SourceRect='0,0,256,256'/>
<ImageFragment Offset='0,256' Source='ui_female_faces_1_01' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,0' Source='ui_female_faces_1_02' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,0' Source='ui_female_faces_1_03' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,128' Source='ui_female_faces_1_04' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,128' Source='ui_female_faces_1_05' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,256' Source='ui_female_faces_1_06' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,256' Source='ui_female_faces_1_07' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,384' Source='ui_female_faces_1_08' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,384' Source='ui_female_faces_1_09' SourceRect='0,0,32,128'/>
</ImageFrame>
</ImageStyle>
<ImageStyle Name='Female04d'>
<ImageFrame SourceRect='243,390,324,520'>
<ImageFragment Source='ui_female_faces_1_00' SourceRect='0,0,256,256'/>
<ImageFragment Offset='0,256' Source='ui_female_faces_1_01' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,0' Source='ui_female_faces_1_02' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,0' Source='ui_female_faces_1_03' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,128' Source='ui_female_faces_1_04' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,128' Source='ui_female_faces_1_05' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,256' Source='ui_female_faces_1_06' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,256' Source='ui_female_faces_1_07' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,384' Source='ui_female_faces_1_08' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,384' Source='ui_female_faces_1_09' SourceRect='0,0,32,128'/>
</ImageFrame>
</ImageStyle>
<ImageStyle Name='Female04e'>
<ImageFrame SourceRect='324,390,405,520'>
<ImageFragment Source='ui_female_faces_1_00' SourceRect='0,0,256,256'/>
<ImageFragment Offset='0,256' Source='ui_female_faces_1_01' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,0' Source='ui_female_faces_1_02' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,0' Source='ui_female_faces_1_03' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,128' Source='ui_female_faces_1_04' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,128' Source='ui_female_faces_1_05' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,256' Source='ui_female_faces_1_06' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,256' Source='ui_female_faces_1_07' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,384' Source='ui_female_faces_1_08' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,384' Source='ui_female_faces_1_09' SourceRect='0,0,32,128'/>
</ImageFrame>
</ImageStyle>
<ImageStyle Name='Female05a'>
<ImageFrame SourceRect='0,0,81,130'>
<ImageFragment Source='ui_female_faces_2_00' SourceRect='0,0,256,256'/>
<ImageFragment Offset='0,256' Source='ui_female_faces_2_01' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,0' Source='ui_female_faces_2_02' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,0' Source='ui_female_faces_2_03' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,128' Source='ui_female_faces_2_04' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,128' Source='ui_female_faces_2_05' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,256' Source='ui_female_faces_2_06' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,256' Source='ui_female_faces_2_07' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,384' Source='ui_female_faces_2_08' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,384' Source='ui_female_faces_2_09' SourceRect='0,0,32,128'/>
</ImageFrame>
</ImageStyle>
<ImageStyle Name='Female05b'>
<ImageFrame SourceRect='81,0,162,128'>
<ImageFragment Source='ui_female_faces_2_00' SourceRect='0,0,256,256'/>
<ImageFragment Offset='0,256' Source='ui_female_faces_2_01' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,0' Source='ui_female_faces_2_02' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,0' Source='ui_female_faces_2_03' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,128' Source='ui_female_faces_2_04' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,128' Source='ui_female_faces_2_05' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,256' Source='ui_female_faces_2_06' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,256' Source='ui_female_faces_2_07' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,384' Source='ui_female_faces_2_08' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,384' Source='ui_female_faces_2_09' SourceRect='0,0,32,128'/>
</ImageFrame>
</ImageStyle>
<ImageStyle Name='Female05c'>
<ImageFrame SourceRect='162,0,243,130'>
<ImageFragment Source='ui_female_faces_2_00' SourceRect='0,0,256,256'/>
<ImageFragment Offset='0,256' Source='ui_female_faces_2_01' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,0' Source='ui_female_faces_2_02' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,0' Source='ui_female_faces_2_03' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,128' Source='ui_female_faces_2_04' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,128' Source='ui_female_faces_2_05' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,256' Source='ui_female_faces_2_06' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,256' Source='ui_female_faces_2_07' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,384' Source='ui_female_faces_2_08' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,384' Source='ui_female_faces_2_09' SourceRect='0,0,32,128'/>
</ImageFrame>
</ImageStyle>
<ImageStyle Name='Female05d'>
<ImageFrame SourceRect='243,0,324,130'>
<ImageFragment Source='ui_female_faces_2_00' SourceRect='0,0,256,256'/>
<ImageFragment Offset='0,256' Source='ui_female_faces_2_01' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,0' Source='ui_female_faces_2_02' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,0' Source='ui_female_faces_2_03' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,128' Source='ui_female_faces_2_04' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,128' Source='ui_female_faces_2_05' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,256' Source='ui_female_faces_2_06' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,256' Source='ui_female_faces_2_07' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,384' Source='ui_female_faces_2_08' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,384' Source='ui_female_faces_2_09' SourceRect='0,0,32,128'/>
</ImageFrame>
</ImageStyle>
<ImageStyle Name='Female05e'>
<ImageFrame SourceRect='324,0,405,130'>
<ImageFragment Source='ui_female_faces_2_00' SourceRect='0,0,256,256'/>
<ImageFragment Offset='0,256' Source='ui_female_faces_2_01' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,0' Source='ui_female_faces_2_02' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,0' Source='ui_female_faces_2_03' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,128' Source='ui_female_faces_2_04' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,128' Source='ui_female_faces_2_05' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,256' Source='ui_female_faces_2_06' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,256' Source='ui_female_faces_2_07' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,384' Source='ui_female_faces_2_08' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,384' Source='ui_female_faces_2_09' SourceRect='0,0,32,128'/>
</ImageFrame>
</ImageStyle>
<ImageStyle Name='Female06a'>
<ImageFrame SourceRect='0,130,81,260'>
<ImageFragment Source='ui_female_faces_2_00' SourceRect='0,0,256,256'/>
<ImageFragment Offset='0,256' Source='ui_female_faces_2_01' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,0' Source='ui_female_faces_2_02' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,0' Source='ui_female_faces_2_03' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,128' Source='ui_female_faces_2_04' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,128' Source='ui_female_faces_2_05' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,256' Source='ui_female_faces_2_06' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,256' Source='ui_female_faces_2_07' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,384' Source='ui_female_faces_2_08' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,384' Source='ui_female_faces_2_09' SourceRect='0,0,32,128'/>
</ImageFrame>
</ImageStyle>
<ImageStyle Name='Female06b'>
<ImageFrame SourceRect='81,128,162,256'>
<ImageFragment Source='ui_female_faces_2_00' SourceRect='0,0,256,256'/>
<ImageFragment Offset='0,256' Source='ui_female_faces_2_01' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,0' Source='ui_female_faces_2_02' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,0' Source='ui_female_faces_2_03' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,128' Source='ui_female_faces_2_04' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,128' Source='ui_female_faces_2_05' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,256' Source='ui_female_faces_2_06' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,256' Source='ui_female_faces_2_07' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,384' Source='ui_female_faces_2_08' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,384' Source='ui_female_faces_2_09' SourceRect='0,0,32,128'/>
</ImageFrame>
</ImageStyle>
<ImageStyle Name='Female06c'>
<ImageFrame SourceRect='162,130,243,260'>
<ImageFragment Source='ui_female_faces_2_00' SourceRect='0,0,256,256'/>
<ImageFragment Offset='0,256' Source='ui_female_faces_2_01' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,0' Source='ui_female_faces_2_02' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,0' Source='ui_female_faces_2_03' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,128' Source='ui_female_faces_2_04' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,128' Source='ui_female_faces_2_05' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,256' Source='ui_female_faces_2_06' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,256' Source='ui_female_faces_2_07' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,384' Source='ui_female_faces_2_08' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,384' Source='ui_female_faces_2_09' SourceRect='0,0,32,128'/>
</ImageFrame>
</ImageStyle>
<ImageStyle Name='Female06d'>
<ImageFrame SourceRect='243,130,324,260'>
<ImageFragment Source='ui_female_faces_2_00' SourceRect='0,0,256,256'/>
<ImageFragment Offset='0,256' Source='ui_female_faces_2_01' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,0' Source='ui_female_faces_2_02' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,0' Source='ui_female_faces_2_03' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,128' Source='ui_female_faces_2_04' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,128' Source='ui_female_faces_2_05' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,256' Source='ui_female_faces_2_06' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,256' Source='ui_female_faces_2_07' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,384' Source='ui_female_faces_2_08' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,384' Source='ui_female_faces_2_09' SourceRect='0,0,32,128'/>
</ImageFrame>
</ImageStyle>
<ImageStyle Name='Female06e'>
<ImageFrame SourceRect='324,130,405,260'>
<ImageFragment Source='ui_female_faces_2_00' SourceRect='0,0,256,256'/>
<ImageFragment Offset='0,256' Source='ui_female_faces_2_01' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,0' Source='ui_female_faces_2_02' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,0' Source='ui_female_faces_2_03' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,128' Source='ui_female_faces_2_04' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,128' Source='ui_female_faces_2_05' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,256' Source='ui_female_faces_2_06' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,256' Source='ui_female_faces_2_07' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,384' Source='ui_female_faces_2_08' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,384' Source='ui_female_faces_2_09' SourceRect='0,0,32,128'/>
</ImageFrame>
</ImageStyle>
<ImageStyle Name='Female07a'>
<ImageFrame SourceRect='0,260,81,390'>
<ImageFragment Source='ui_female_faces_2_00' SourceRect='0,0,256,256'/>
<ImageFragment Offset='0,256' Source='ui_female_faces_2_01' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,0' Source='ui_female_faces_2_02' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,0' Source='ui_female_faces_2_03' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,128' Source='ui_female_faces_2_04' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,128' Source='ui_female_faces_2_05' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,256' Source='ui_female_faces_2_06' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,256' Source='ui_female_faces_2_07' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,384' Source='ui_female_faces_2_08' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,384' Source='ui_female_faces_2_09' SourceRect='0,0,32,128'/>
</ImageFrame>
</ImageStyle>
<ImageStyle Name='Female07b'>
<ImageFrame SourceRect='81,256,162,384'>
<ImageFragment Source='ui_female_faces_2_00' SourceRect='0,0,256,256'/>
<ImageFragment Offset='0,256' Source='ui_female_faces_2_01' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,0' Source='ui_female_faces_2_02' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,0' Source='ui_female_faces_2_03' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,128' Source='ui_female_faces_2_04' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,128' Source='ui_female_faces_2_05' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,256' Source='ui_female_faces_2_06' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,256' Source='ui_female_faces_2_07' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,384' Source='ui_female_faces_2_08' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,384' Source='ui_female_faces_2_09' SourceRect='0,0,32,128'/>
</ImageFrame>
</ImageStyle>
<ImageStyle Name='Female07c'>
<ImageFrame SourceRect='162,260,243,390'>
<ImageFragment Source='ui_female_faces_2_00' SourceRect='0,0,256,256'/>
<ImageFragment Offset='0,256' Source='ui_female_faces_2_01' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,0' Source='ui_female_faces_2_02' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,0' Source='ui_female_faces_2_03' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,128' Source='ui_female_faces_2_04' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,128' Source='ui_female_faces_2_05' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,256' Source='ui_female_faces_2_06' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,256' Source='ui_female_faces_2_07' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,384' Source='ui_female_faces_2_08' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,384' Source='ui_female_faces_2_09' SourceRect='0,0,32,128'/>
</ImageFrame>
</ImageStyle>
<ImageStyle Name='Female07d'>
<ImageFrame SourceRect='243,260,324,390'>
<ImageFragment Source='ui_female_faces_2_00' SourceRect='0,0,256,256'/>
<ImageFragment Offset='0,256' Source='ui_female_faces_2_01' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,0' Source='ui_female_faces_2_02' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,0' Source='ui_female_faces_2_03' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,128' Source='ui_female_faces_2_04' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,128' Source='ui_female_faces_2_05' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,256' Source='ui_female_faces_2_06' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,256' Source='ui_female_faces_2_07' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,384' Source='ui_female_faces_2_08' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,384' Source='ui_female_faces_2_09' SourceRect='0,0,32,128'/>
</ImageFrame>
</ImageStyle>
<ImageStyle Name='Female07e'>
<ImageFrame SourceRect='324,260,405,390'>
<ImageFragment Source='ui_female_faces_2_00' SourceRect='0,0,256,256'/>
<ImageFragment Offset='0,256' Source='ui_female_faces_2_01' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,0' Source='ui_female_faces_2_02' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,0' Source='ui_female_faces_2_03' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,128' Source='ui_female_faces_2_04' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,128' Source='ui_female_faces_2_05' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,256' Source='ui_female_faces_2_06' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,256' Source='ui_female_faces_2_07' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,384' Source='ui_female_faces_2_08' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,384' Source='ui_female_faces_2_09' SourceRect='0,0,32,128'/>
</ImageFrame>
</ImageStyle>
<ImageStyle Name='Female08a'>
<ImageFrame SourceRect='0,390,81,520'>
<ImageFragment Source='ui_female_faces_2_00' SourceRect='0,0,256,256'/>
<ImageFragment Offset='0,256' Source='ui_female_faces_2_01' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,0' Source='ui_female_faces_2_02' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,0' Source='ui_female_faces_2_03' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,128' Source='ui_female_faces_2_04' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,128' Source='ui_female_faces_2_05' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,256' Source='ui_female_faces_2_06' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,256' Source='ui_female_faces_2_07' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,384' Source='ui_female_faces_2_08' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,384' Source='ui_female_faces_2_09' SourceRect='0,0,32,128'/>
</ImageFrame>
</ImageStyle>
<ImageStyle Name='Female08b'>
<ImageFrame SourceRect='81,384,162,512'>
<ImageFragment Source='ui_female_faces_2_00' SourceRect='0,0,256,256'/>
<ImageFragment Offset='0,256' Source='ui_female_faces_2_01' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,0' Source='ui_female_faces_2_02' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,0' Source='ui_female_faces_2_03' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,128' Source='ui_female_faces_2_04' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,128' Source='ui_female_faces_2_05' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,256' Source='ui_female_faces_2_06' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,256' Source='ui_female_faces_2_07' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,384' Source='ui_female_faces_2_08' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,384' Source='ui_female_faces_2_09' SourceRect='0,0,32,128'/>
</ImageFrame>
</ImageStyle>
<ImageStyle Name='Female08c'>
<ImageFrame SourceRect='162,390,243,520'>
<ImageFragment Source='ui_female_faces_2_00' SourceRect='0,0,256,256'/>
<ImageFragment Offset='0,256' Source='ui_female_faces_2_01' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,0' Source='ui_female_faces_2_02' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,0' Source='ui_female_faces_2_03' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,128' Source='ui_female_faces_2_04' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,128' Source='ui_female_faces_2_05' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,256' Source='ui_female_faces_2_06' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,256' Source='ui_female_faces_2_07' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,384' Source='ui_female_faces_2_08' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,384' Source='ui_female_faces_2_09' SourceRect='0,0,32,128'/>
</ImageFrame>
</ImageStyle>
<ImageStyle Name='Female08d'>
<ImageFrame SourceRect='243,390,324,520'>
<ImageFragment Source='ui_female_faces_2_00' SourceRect='0,0,256,256'/>
<ImageFragment Offset='0,256' Source='ui_female_faces_2_01' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,0' Source='ui_female_faces_2_02' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,0' Source='ui_female_faces_2_03' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,128' Source='ui_female_faces_2_04' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,128' Source='ui_female_faces_2_05' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,256' Source='ui_female_faces_2_06' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,256' Source='ui_female_faces_2_07' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,384' Source='ui_female_faces_2_08' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,384' Source='ui_female_faces_2_09' SourceRect='0,0,32,128'/>
</ImageFrame>
</ImageStyle>
<ImageStyle Name='Female08e'>
<ImageFrame SourceRect='324,390,405,520'>
<ImageFragment Source='ui_female_faces_2_00' SourceRect='0,0,256,256'/>
<ImageFragment Offset='0,256' Source='ui_female_faces_2_01' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,0' Source='ui_female_faces_2_02' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,0' Source='ui_female_faces_2_03' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,128' Source='ui_female_faces_2_04' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,128' Source='ui_female_faces_2_05' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,256' Source='ui_female_faces_2_06' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,256' Source='ui_female_faces_2_07' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,384' Source='ui_female_faces_2_08' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,384' Source='ui_female_faces_2_09' SourceRect='0,0,32,128'/>
</ImageFrame>
</ImageStyle>
<ImageStyle Name='Female09a'>
<ImageFrame SourceRect='0,0,81,130'>
<ImageFragment Source='ui_female_faces_3_00' SourceRect='0,0,256,256'/>
<ImageFragment Offset='0,256' Source='ui_female_faces_3_01' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,0' Source='ui_female_faces_3_02' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,0' Source='ui_female_faces_3_03' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,128' Source='ui_female_faces_3_04' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,128' Source='ui_female_faces_3_05' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,256' Source='ui_female_faces_3_06' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,256' Source='ui_female_faces_3_07' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,384' Source='ui_female_faces_3_08' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,384' Source='ui_female_faces_3_09' SourceRect='0,0,32,128'/>
</ImageFrame>
</ImageStyle>
<ImageStyle Name='Female09b'>
<ImageFrame SourceRect='81,0,162,128'>
<ImageFragment Source='ui_female_faces_3_00' SourceRect='0,0,256,256'/>
<ImageFragment Offset='0,256' Source='ui_female_faces_3_01' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,0' Source='ui_female_faces_3_02' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,0' Source='ui_female_faces_3_03' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,128' Source='ui_female_faces_3_04' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,128' Source='ui_female_faces_3_05' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,256' Source='ui_female_faces_3_06' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,256' Source='ui_female_faces_3_07' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,384' Source='ui_female_faces_3_08' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,384' Source='ui_female_faces_3_09' SourceRect='0,0,32,128'/>
</ImageFrame>
</ImageStyle>
<ImageStyle Name='Female09c'>
<ImageFrame SourceRect='162,0,243,130'>
<ImageFragment Source='ui_female_faces_3_00' SourceRect='0,0,256,256'/>
<ImageFragment Offset='0,256' Source='ui_female_faces_3_01' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,0' Source='ui_female_faces_3_02' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,0' Source='ui_female_faces_3_03' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,128' Source='ui_female_faces_3_04' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,128' Source='ui_female_faces_3_05' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,256' Source='ui_female_faces_3_06' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,256' Source='ui_female_faces_3_07' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,384' Source='ui_female_faces_3_08' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,384' Source='ui_female_faces_3_09' SourceRect='0,0,32,128'/>
</ImageFrame>
</ImageStyle>
<ImageStyle Name='Female09d'>
<ImageFrame SourceRect='243,0,324,130'>
<ImageFragment Source='ui_female_faces_3_00' SourceRect='0,0,256,256'/>
<ImageFragment Offset='0,256' Source='ui_female_faces_3_01' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,0' Source='ui_female_faces_3_02' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,0' Source='ui_female_faces_3_03' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,128' Source='ui_female_faces_3_04' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,128' Source='ui_female_faces_3_05' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,256' Source='ui_female_faces_3_06' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,256' Source='ui_female_faces_3_07' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,384' Source='ui_female_faces_3_08' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,384' Source='ui_female_faces_3_09' SourceRect='0,0,32,128'/>
</ImageFrame>
</ImageStyle>
<ImageStyle Name='Female09e'>
<ImageFrame SourceRect='324,0,405,130'>
<ImageFragment Source='ui_female_faces_3_00' SourceRect='0,0,256,256'/>
<ImageFragment Offset='0,256' Source='ui_female_faces_3_01' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,0' Source='ui_female_faces_3_02' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,0' Source='ui_female_faces_3_03' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,128' Source='ui_female_faces_3_04' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,128' Source='ui_female_faces_3_05' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,256' Source='ui_female_faces_3_06' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,256' Source='ui_female_faces_3_07' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,384' Source='ui_female_faces_3_08' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,384' Source='ui_female_faces_3_09' SourceRect='0,0,32,128'/>
</ImageFrame>
</ImageStyle>
<ImageStyle Name='Female10a'>
<ImageFrame SourceRect='0,130,81,260'>
<ImageFragment Source='ui_female_faces_3_00' SourceRect='0,0,256,256'/>
<ImageFragment Offset='0,256' Source='ui_female_faces_3_01' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,0' Source='ui_female_faces_3_02' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,0' Source='ui_female_faces_3_03' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,128' Source='ui_female_faces_3_04' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,128' Source='ui_female_faces_3_05' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,256' Source='ui_female_faces_3_06' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,256' Source='ui_female_faces_3_07' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,384' Source='ui_female_faces_3_08' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,384' Source='ui_female_faces_3_09' SourceRect='0,0,32,128'/>
</ImageFrame>
</ImageStyle>
<ImageStyle Name='Female10b'>
<ImageFrame SourceRect='81,128,162,256'>
<ImageFragment Source='ui_female_faces_3_00' SourceRect='0,0,256,256'/>
<ImageFragment Offset='0,256' Source='ui_female_faces_3_01' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,0' Source='ui_female_faces_3_02' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,0' Source='ui_female_faces_3_03' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,128' Source='ui_female_faces_3_04' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,128' Source='ui_female_faces_3_05' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,256' Source='ui_female_faces_3_06' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,256' Source='ui_female_faces_3_07' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,384' Source='ui_female_faces_3_08' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,384' Source='ui_female_faces_3_09' SourceRect='0,0,32,128'/>
</ImageFrame>
</ImageStyle>
<ImageStyle Name='Female10c'>
<ImageFrame SourceRect='162,130,243,260'>
<ImageFragment Source='ui_female_faces_3_00' SourceRect='0,0,256,256'/>
<ImageFragment Offset='0,256' Source='ui_female_faces_3_01' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,0' Source='ui_female_faces_3_02' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,0' Source='ui_female_faces_3_03' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,128' Source='ui_female_faces_3_04' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,128' Source='ui_female_faces_3_05' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,256' Source='ui_female_faces_3_06' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,256' Source='ui_female_faces_3_07' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,384' Source='ui_female_faces_3_08' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,384' Source='ui_female_faces_3_09' SourceRect='0,0,32,128'/>
</ImageFrame>
</ImageStyle>
<ImageStyle Name='Female10d'>
<ImageFrame SourceRect='243,130,324,260'>
<ImageFragment Source='ui_female_faces_3_00' SourceRect='0,0,256,256'/>
<ImageFragment Offset='0,256' Source='ui_female_faces_3_01' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,0' Source='ui_female_faces_3_02' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,0' Source='ui_female_faces_3_03' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,128' Source='ui_female_faces_3_04' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,128' Source='ui_female_faces_3_05' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,256' Source='ui_female_faces_3_06' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,256' Source='ui_female_faces_3_07' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,384' Source='ui_female_faces_3_08' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,384' Source='ui_female_faces_3_09' SourceRect='0,0,32,128'/>
</ImageFrame>
</ImageStyle>
<ImageStyle Name='Female10e'>
<ImageFrame SourceRect='324,130,405,260'>
<ImageFragment Source='ui_female_faces_3_00' SourceRect='0,0,256,256'/>
<ImageFragment Offset='0,256' Source='ui_female_faces_3_01' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,0' Source='ui_female_faces_3_02' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,0' Source='ui_female_faces_3_03' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,128' Source='ui_female_faces_3_04' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,128' Source='ui_female_faces_3_05' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,256' Source='ui_female_faces_3_06' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,256' Source='ui_female_faces_3_07' SourceRect='0,0,32,128'/>
<ImageFragment Offset='256,384' Source='ui_female_faces_3_08' SourceRect='0,0,128,128'/>
<ImageFragment Offset='384,384' Source='ui_female_faces_3_09' SourceRect='0,0,32,128'/>
</ImageFrame>
</ImageStyle>
</Namespace>
<Template Name='GridElement' Size='85,130'>\<image e = \'$e$\' location = \'2,0\' name = \'$name$\' size = \'85,130\' stretch = \'false\' style = \'/CreateCharacter.Faces.$name$\'\></Template>
</Page>
