<Namespace Name='ConsoleTextbox'>
<TextboxStyle CaratColor='#00F2C9' CaratWidth='2' Name='ShortStyle' NormalGridStyle='/DefaultGrid.style' NormalTextStyle='/Fonts.HudFont3' SelectionColor='#444444' TextColor='#FFFFFF' TextPadding='4,2,2,2'/>
<TextboxStyle CaratColor='#00F2C9' CaratWidth='2' Name='Style' NormalGridStyle='/DefaultGrid.style' NormalTextStyle='/Fonts.HudFont3' SelectionColor='#444444' TextColor='#FFFFFF' TextPadding='4,6,2,2'/>
</Namespace>
<Namespace Name='SmallTextbox'>
<TextboxStyle CaratColor='#00FF00' CaratWidth='2' Name='Style' NormalGridStyle='/DefaultGrid.style' NormalTextStyle='/Fonts.DefaultFont' SelectionColor='#00FF00' TextColor='#FFFFFF' TextPadding='2,2,2,2'/>
</Namespace>
