<Namespace Name='dropdown20'>
<ImageStyle Name='normal.leftcap'>
<ImageFrame SourceRect='0,0,2,29'>
<ImageFragment Source='ui_options_pulldown_00' SourceRect='0,0,128,96'/>
<ImageFragment Offset='128,0' Source='ui_options_pulldown_01' SourceRect='0,0,128,96'/>
</ImageFrame>
</ImageStyle>
<ImageStyle Name='normal.background'>
<ImageFrame SourceRect='0,0,229,29'>
<ImageFragment Source='ui_options_pulldown_00' SourceRect='0,0,128,96'/>
<ImageFragment Offset='128,0' Source='ui_options_pulldown_01' SourceRect='0,0,128,96'/>
</ImageFrame>
</ImageStyle>
<ImageStyle Name='normal.downarrow'>
<ImageFrame SourceRect='229,0,256,29'>
<ImageFragment Source='ui_options_pulldown_00' SourceRect='0,0,128,96'/>
<ImageFragment Offset='128,0' Source='ui_options_pulldown_01' SourceRect='0,0,128,96'/>
</ImageFrame>
</ImageStyle>
<ImageStyle Name='selected.startcap'>
<ImageFrame SourceRect='0,29,2,58'>
<ImageFragment Source='ui_options_pulldown_00' SourceRect='0,0,128,96'/>
<ImageFragment Offset='128,0' Source='ui_options_pulldown_01' SourceRect='0,0,128,96'/>
</ImageFrame>
</ImageStyle>
<ImageStyle Name='selected.background'>
<ImageFrame SourceRect='0,29,229,59'>
<ImageFragment Source='ui_options_pulldown_00' SourceRect='0,0,128,96'/>
<ImageFragment Offset='128,0' Source='ui_options_pulldown_01' SourceRect='0,0,128,96'/>
</ImageFrame>
</ImageStyle>
<ImageStyle Name='selected.downarrow'>
<ImageFrame SourceRect='229,29,256,58'>
<ImageFragment Source='ui_options_pulldown_00' SourceRect='0,0,128,96'/>
<ImageFragment Offset='128,0' Source='ui_options_pulldown_01' SourceRect='0,0,128,96'/>
</ImageFrame>
</ImageStyle>
<ImageStyle Name='pressed.startcap'>
<ImageFrame SourceRect='0,58,2,87'>
<ImageFragment Source='ui_options_pulldown_00' SourceRect='0,0,128,96'/>
<ImageFragment Offset='128,0' Source='ui_options_pulldown_01' SourceRect='0,0,128,96'/>
</ImageFrame>
</ImageStyle>
<ImageStyle Name='pressed.background'>
<ImageFrame SourceRect='0,58,229,87'>
<ImageFragment Source='ui_options_pulldown_00' SourceRect='0,0,128,96'/>
<ImageFragment Offset='128,0' Source='ui_options_pulldown_01' SourceRect='0,0,128,96'/>
</ImageFrame>
</ImageStyle>
<ImageStyle Name='pressed.downarrow'>
<ImageFrame SourceRect='229,58,256,87'>
<ImageFragment Source='ui_options_pulldown_00' SourceRect='0,0,128,96'/>
<ImageFragment Offset='128,0' Source='ui_options_pulldown_01' SourceRect='0,0,128,96'/>
</ImageFrame>
</ImageStyle>
<DropdownboxStyle CloseSound='beep02_s.wav' Disabled.Background='disabled.background' Disabled.DownArrow='disabled.downarrow' Disabled.StartCap='disabled.startcap' DropBy='160' Listbox.Style='/Listboxes.EmbeddedListbox16.style' Name='style' Normal.Background='normal.background' Normal.DownArrow='normal.downarrow' normal.leftcap='normal.leftcap' Normal.StartCap='selected.startcap' OpenSound='beep01_s.wav' Padding='2,6,10,6' Pressed.Background='pressed.background' Pressed.DownArrow='pressed.downarrow' Pressed.StartCap='pressed.startcap' Scrollbar.Style='/VScrollbar.style' Selected.Background='selected.background' Selected.DownArrow='selected.downarrow' Selected.StartCap='selected.startcap'/>
</Namespace>
