<ImageStyle Loop='true' Name='normal.background' Playtime='1.00'>
<ImageFrame Duration='1' Offset='0,0' opacity='0.200000' sourcefile='ui_elb16' SourceRect='0,48,64,64'/>
</ImageStyle>
<ImageStyle Loop='true' Name='normal.row.startcap' Playtime='1.00'>
<ImageFrame Duration='1' Offset='0,0' opacity='0.494118' sourcefile='ui_elb16' SourceRect='0,16,3,32'/>
</ImageStyle>
<ImageStyle Loop='true' Name='normal.row.background' Playtime='1.00'>
<ImageFrame Duration='1' Offset='0,0' opacity='0.494118' SourceRect='3,16,61,32'/>
</ImageStyle>
<ImageStyle Loop='true' Name='normal.row.endcap' Playtime='1.00'>
<ImageFrame Duration='1' Offset='0,0' opacity='0.494118' SourceRect='61,16,64,32'/>
</ImageStyle>
<ImageStyle Loop='true' Name='disabled.background' Playtime='1.00'>
<ImageFrame Duration='1' Offset='0,0' opacity='0.200000' SourceRect='0,48,64,64'/>
</ImageStyle>
<ImageStyle Loop='true' Name='disabled.row.startcap' Playtime='1.00'>
<ImageFrame Duration='1' Offset='0,0' opacity='0.494118' SourceRect='0,0,3,16'/>
</ImageStyle>
<ImageStyle Loop='true' Name='disabled.row.background' Playtime='1.00'>
<ImageFrame Duration='1' Offset='0,0' opacity='0.494118' SourceRect='3,0,61,16'/>
</ImageStyle>
<ImageStyle Loop='true' Name='disabled.row.endcap' Playtime='1.00'>
<ImageFrame Duration='1' Offset='0,0' opacity='0.494118' SourceRect='61,0,64,16'/>
</ImageStyle>
<ImageStyle Loop='true' Name='selected.background' Playtime='1.00'>
<ImageFrame Duration='1' Offset='0,0' opacity='0.200000' SourceRect='0,48,64,64'/>
</ImageStyle>
<ImageStyle Loop='true' Name='selected.row.startcap' Playtime='1.00'>
<ImageFrame Duration='1' Offset='0,0' opacity='0.494118' SourceRect='0,32,3,48'/>
</ImageStyle>
<ImageStyle Loop='true' Name='selected.row.background' Playtime='1.00'>
<ImageFrame Duration='1' Offset='0,0' opacity='0.494118' SourceRect='3,32,61,48'/>
</ImageStyle>
<ImageStyle Loop='true' Name='selected.row.endcap' Playtime='1.00'>
<ImageFrame Duration='1' Offset='0,0' opacity='0.494118' SourceRect='61,32,64,48'/>
</ImageStyle>
<ListboxStyle GridStyle='/EmbeddedGrid.style' Layout='Vertical' Name='style'/>
<ImageStyle Loop='true' Name='normal.background' Playtime='1.00'>
<ImageFrame Duration='1' Offset='0,0' opacity='0.200000' sourcefile='ui_elb16' SourceRect='0,48,64,64'/>
</ImageStyle>
<ImageStyle Loop='true' Name='normal.row.startcap' Playtime='1.00'>
<ImageFrame Duration='1' Offset='0,0' opacity='0.494118' sourcefile='ui_elb16' SourceRect='0,16,3,32'/>
</ImageStyle>
<ImageStyle Loop='true' Name='normal.row.background' Playtime='1.00'>
<ImageFrame Duration='1' Offset='0,0' opacity='0.494118' SourceRect='3,16,61,32'/>
</ImageStyle>
<ImageStyle Loop='true' Name='normal.row.endcap' Playtime='1.00'>
<ImageFrame Duration='1' Offset='0,0' opacity='0.494118' SourceRect='61,16,64,32'/>
</ImageStyle>
<ImageStyle Loop='true' Name='disabled.background' Playtime='1.00'>
<ImageFrame Duration='1' Offset='0,0' opacity='0.200000' SourceRect='0,48,64,64'/>
</ImageStyle>
<ImageStyle Loop='true' Name='disabled.row.startcap' Playtime='1.00'>
<ImageFrame Duration='1' Offset='0,0' opacity='0.494118' SourceRect='0,0,3,16'/>
</ImageStyle>
<ImageStyle Loop='true' Name='disabled.row.background' Playtime='1.00'>
<ImageFrame Duration='1' Offset='0,0' opacity='0.494118' SourceRect='3,0,61,16'/>
</ImageStyle>
<ImageStyle Loop='true' Name='disabled.row.endcap' Playtime='1.00'>
<ImageFrame Duration='1' Offset='0,0' opacity='0.494118' SourceRect='61,0,64,16'/>
</ImageStyle>
<ImageStyle Loop='true' Name='selected.background' Playtime='1.00'>
<ImageFrame Duration='1' Offset='0,0' opacity='0.200000' SourceRect='0,48,64,64'/>
</ImageStyle>
<ImageStyle Loop='true' Name='selected.row.startcap' Playtime='1.00'>
<ImageFrame Duration='1' Offset='0,0' opacity='0.494118' SourceRect='0,32,3,48'/>
</ImageStyle>
<ImageStyle Loop='true' Name='selected.row.background' Playtime='1.00'>
<ImageFrame Duration='1' Offset='0,0' opacity='0.494118' SourceRect='3,32,61,48'/>
</ImageStyle>
<ImageStyle Loop='true' Name='selected.row.endcap' Playtime='1.00'>
<ImageFrame Duration='1' Offset='0,0' opacity='0.494118' SourceRect='61,32,64,48'/>
</ImageStyle>
<ListboxStyle GridStyle='/EmbeddedGrid.style' Layout='Vertical' Name='style'/>
