<Namespace Name='Fonts'>
<TextStyle Leading='26' Name='MiscIcons'>
<FontCharacter Advance='34' Code='65' Name='A - Vehicle' SourceFile='ui_font_misc_1_00' SourceRect='0,0,34,26'/>
<FontCharacter Advance='34' Code='66' Name='B - Trunk' SourceFile='ui_font_misc_1_00' SourceRect='34,0,68,26'/>
<FontCharacter Advance='34' Code='67' Name='C - Unlock' SourceFile='ui_font_misc_1_00' SourceRect='68,0,102,26'/>
<FontCharacter Advance='34' Code='68' Name='D - Lock' SourceFile='ui_font_misc_1_00' SourceRect='0,26,34,52'/>
<FontCharacter Advance='34' Code='69' Name='E - Squad' SourceFile='ui_font_misc_1_00' SourceRect='34,26,68,52'/>
<FontCharacter Advance='34' Code='70' Name='F - Drive' SourceFile='ui_font_misc_1_00' SourceRect='68,26,102,52'/>
<FontCharacter Advance='34' Code='71' Name='G - Gunner' SourceFile='ui_font_misc_1_00' SourceRect='0,52,34,78'/>
<FontCharacter Advance='34' Code='72' Name='H - Passenger' SourceFile='ui_font_misc_1_00' SourceRect='34,52,68,78'/>
<FontCharacter Advance='34' Code='73' Name='I - Vehicle position' SourceFile='ui_font_misc_1_00' SourceRect='68,52,102,78'/>
<FontCharacter Advance='34' Code='74' Name='J - Hide' SourceFile='ui_font_misc_1_00' SourceRect='0,78,34,104'/>
<FontCharacter Advance='34' Code='75' Name='K - Visible' SourceFile='ui_font_misc_1_00' SourceRect='34,78,68,104'/>
<FontCharacter Advance='34' Code='76' Name='L - Looking' SourceFile='ui_font_misc_1_00' SourceRect='68,78,102,104'/>
<FontCharacter Advance='34' Code='77' Name='M - Not looking' SourceFile='ui_font_misc_2_00' SourceRect='0,0,34,26'/>
</TextStyle>
<TextStyle Leading='21' Name='TabIcons'>
<FontCharacter Advance='42' Code='65' Name='A - Certifications' SourceFile='ui_font_tabs_1_00' SourceRect='0,0,42,21'/>
<FontCharacter Advance='42' Code='66' Name='B - Implants' SourceFile='ui_font_tabs_1_00' SourceRect='42,0,84,21'/>
<FontCharacter Advance='42' Code='67' Name='C - Global' SourceFile='ui_font_tabs_1_00' SourceRect='84,0,126,21'/>
<FontCharacter Advance='42' Code='68' Name='D - Continental' SourceFile='ui_font_tabs_1_00' SourceRect='0,21,42,42'/>
<FontCharacter Advance='42' Code='69' Name='E - Soldier' SourceFile='ui_font_tabs_1_00' SourceRect='42,21,84,42'/>
<FontCharacter Advance='42' Code='70' Name='F - Weapons' SourceFile='ui_font_tabs_1_00' SourceRect='84,21,126,42'/>
<FontCharacter Advance='42' Code='71' Name='G - Armor' SourceFile='ui_font_tabs_1_00' SourceRect='0,42,42,63'/>
<FontCharacter Advance='42' Code='72' Name='H - Equipment' SourceFile='ui_font_tabs_1_00' SourceRect='42,42,84,63'/>
<FontCharacter Advance='42' Code='73' Name='I - Vehicle Ammo' SourceFile='ui_font_tabs_1_00' SourceRect='84,42,126,63'/>
<FontCharacter Advance='42' Code='74' Name='J - Save Configurations' SourceFile='ui_font_tabs_1_00' SourceRect='0,63,42,84'/>
<FontCharacter Advance='42' Code='75' Name='K - Friends' SourceFile='ui_font_tabs_1_00' SourceRect='42,63,84,84'/>
<FontCharacter Advance='42' Code='76' Name='L - Find' SourceFile='ui_font_tabs_1_00' SourceRect='84,63,126,84'/>
<FontCharacter Advance='42' Code='77' Name='M - Squad' SourceFile='ui_font_tabs_1_00' SourceRect='0,84,42,105'/>
<FontCharacter Advance='42' Code='78' Name='N - Kills' SourceFile='ui_font_tabs_1_00' SourceRect='42,84,84,105'/>
<FontCharacter Advance='42' Code='79' Name='O - Facilities' SourceFile='ui_font_tabs_1_00' SourceRect='84,84,126,105'/>
</TextStyle>
<TextStyle Leading='20' Name='ButtonIcons'>
<FontCharacter Advance='32' Code='35' Name='# - Claim Delete' SourceFile='ui_font_buttons_3_00' SourceRect='0,80,32,100'/>
<FontCharacter Advance='32' Code='36' Name='$ - Claim Go' SourceFile='ui_font_buttons_3_00' SourceRect='32,80,64,1000'/>
<FontCharacter Advance='32' Code='37' Name='% - Priority Add' SourceFile='ui_font_buttons_3_00' SourceRect='64,80,96,100'/>
<FontCharacter Advance='32' Code='38' Name='& - Priority Delete' SourceFile='ui_font_buttons_3_00' SourceRect='96,80,128,100'/>
<FontCharacter Advance='32' Code='40' Name='( - Priority Go' SourceFile='ui_font_buttons_3_00' SourceRect='0,100,32,120'/>
<FontCharacter Advance='18' Code='41' Name=') - Radar mini' SourceFile='ui_font_buttons_3_00' SourceRect='39,100,57,120'/>
<FontCharacter Advance='32' Code='42' Name='* - Help mini' SourceFile='ui_font_buttons_3_00' SourceRect='64,100,96,120'/>
<FontCharacter Advance='32' Code='43' Name='+ - Wing' SourceFile='ui_font_buttons_3_00' SourceRect='96,100,128,120'/>
<FontCharacter Advance='32' Code='44' Name=', - Outfit Edit' SourceFile='ui_font_buttons_4_00' SourceRect='0,0,32,20'/>
<FontCharacter Advance='32' Code='45' Name='- - Outfit MOTD' SourceFile='ui_font_buttons_4_00' SourceRect='32,0,64,20'/>
<FontCharacter Advance='32' Code='46' Name='. - Outfit Decal' SourceFile='ui_font_buttons_4_00' SourceRect='64,0,96,20'/>
<FontCharacter Advance='32' Code='47' Name='/ - Weather' SourceFile='ui_font_buttons_4_00' SourceRect='96,0,128,20'/>
<FontCharacter Advance='32' Code='48' Name='0 - Building Resources' SourceFile='ui_font_buttons_4_00' SourceRect='0,20,32,40'/>
<FontCharacter Advance='32' Code='49' Name='1 - Trade' SourceFile='ui_font_buttons_3_00' SourceRect='0,0,32,20'/>
<FontCharacter Advance='32' Code='50' Name='2 - ZoomIn' SourceFile='ui_font_buttons_3_00' SourceRect='32,0,64,20'/>
<FontCharacter Advance='32' Code='51' Name='3 - ZoomOut' SourceFile='ui_font_buttons_3_00' SourceRect='64,0,96,20'/>
<FontCharacter Advance='32' Code='52' Name='4 - Buy Inventory' SourceFile='ui_font_buttons_3_00' SourceRect='96,0,128,20'/>
<FontCharacter Advance='32' Code='53' Name='5 - Recycle' SourceFile='ui_font_buttons_3_00' SourceRect='0,20,32,40'/>
<FontCharacter Advance='32' Code='54' Name='6 - Load Configuration' SourceFile='ui_font_buttons_3_00' SourceRect='32,20,64,40'/>
<FontCharacter Advance='32' Code='55' Name='7 - Delete Configuration' SourceFile='ui_font_buttons_3_00' SourceRect='64,20,96,40'/>
<FontCharacter Advance='32' Code='56' Name='8 - Zoom1' SourceFile='ui_font_buttons_3_00' SourceRect='96,20,128,40'/>
<FontCharacter Advance='32' Code='57' Name='9 - Zoom2' SourceFile='ui_font_buttons_3_00' SourceRect='0,40,32,60'/>
<FontCharacter Advance='32' Code='58' Name=': - Zoom3' SourceFile='ui_font_buttons_3_00' SourceRect='32,40,64,60'/>
<FontCharacter Advance='32' Code='59' Name='; - Zoom4' SourceFile='ui_font_buttons_3_00' SourceRect='64,40,96,60'/>
<FontCharacter Advance='32' Code='60' Name='\< - Zoom5' SourceFile='ui_font_buttons_3_00' SourceRect='96,40,128,60'/>
<FontCharacter Advance='32' Code='61' Name='= - Waypoint Add' SourceFile='ui_font_buttons_3_00' SourceRect='0,60,32,80'/>
<FontCharacter Advance='32' Code='62' Name='\> - Waypoint Delete' SourceFile='ui_font_buttons_3_00' SourceRect='32,60,64,80'/>
<FontCharacter Advance='32' Code='63' Name='? - Waypoint Go' SourceFile='ui_font_buttons_3_00' SourceRect='64,60,96,80'/>
<FontCharacter Advance='32' Code='64' Name='@ - Claim Add' SourceFile='ui_font_buttons_3_00' SourceRect='96,60,128,80'/>
<FontCharacter Advance='32' Code='65' Name='A - Use' SourceFile='ui_font_buttons_1_00' SourceRect='0,0,32,20'/>
<FontCharacter Advance='32' Code='66' Name='B - Drop' SourceFile='ui_font_buttons_1_00' SourceRect='32,0,64,20'/>
<FontCharacter Advance='32' Code='67' Name='C - Destroy' SourceFile='ui_font_buttons_1_00' SourceRect='64,0,96,20'/>
<FontCharacter Advance='32' Code='68' Name='D - Save' SourceFile='ui_font_buttons_1_00' SourceRect='96,0,128,20'/>
<FontCharacter Advance='32' Code='69' Name='E - Promote' SourceFile='ui_font_buttons_1_00' SourceRect='0,20,32,40'/>
<FontCharacter Advance='32' Code='70' Name='F - Kick' SourceFile='ui_font_buttons_1_00' SourceRect='32,20,64,40'/>
<FontCharacter Advance='32' Code='71' Name='G - Invite' SourceFile='ui_font_buttons_1_00' SourceRect='64,20,96,40'/>
<FontCharacter Advance='32' Code='72' Name='H - Outfit listing' SourceFile='ui_font_buttons_1_00' SourceRect='96,20,128,40'/>
<FontCharacter Advance='32' Code='73' Name='I - Personal stats' SourceFile='ui_font_buttons_1_00' SourceRect='0,40,32,60'/>
<FontCharacter Advance='32' Code='74' Name='J - Squad stats' SourceFile='ui_font_buttons_1_00' SourceRect='32,40,64,60'/>
<FontCharacter Advance='32' Code='75' Name='K - Friends' SourceFile='ui_font_buttons_1_00' SourceRect='64,40,96,60'/>
<FontCharacter Advance='32' Code='76' Name='L - Drop circle' SourceFile='ui_font_buttons_1_00' SourceRect='96,40,128,60'/>
<FontCharacter Advance='32' Code='77' Name='M - Show discs' SourceFile='ui_font_buttons_1_00' SourceRect='0,60,32,80'/>
<FontCharacter Advance='32' Code='78' Name='N - Continental threat' SourceFile='ui_font_buttons_1_00' SourceRect='32,60,64,80'/>
<FontCharacter Advance='32' Code='79' Name='O - Place Discs' SourceFile='ui_font_buttons_1_00' SourceRect='64,60,96,80'/>
<FontCharacter Advance='32' Code='80' Name='P - SOI' SourceFile='ui_font_buttons_1_00' SourceRect='96,60,128,80'/>
<FontCharacter Advance='32' Code='81' Name='Q - Center' SourceFile='ui_font_buttons_1_00' SourceRect='0,80,32,100'/>
<FontCharacter Advance='32' Code='82' Name='R - Grab' SourceFile='ui_font_buttons_1_00' SourceRect='32,80,64,100'/>
<FontCharacter Advance='32' Code='83' Name='S - Zoom' SourceFile='ui_font_buttons_1_00' SourceRect='64,80,96,100'/>
<FontCharacter Advance='32' Code='84' Name='T - Label' SourceFile='ui_font_buttons_1_00' SourceRect='96,80,128,100'/>
<FontCharacter Advance='32' Code='85' Name='U - Leave Squad' SourceFile='ui_font_buttons_1_00' SourceRect='0,100,32,120'/>
<FontCharacter Advance='32' Code='86' Name='V - Mini' SourceFile='ui_font_buttons_1_00' SourceRect='32,100,64,120'/>
<FontCharacter Advance='32' Code='87' Name='W - Add Player' SourceFile='ui_font_buttons_1_00' SourceRect='64,100,96,120'/>
<FontCharacter Advance='32' Code='88' Name='X - Delete Player' SourceFile='ui_font_buttons_1_00' SourceRect='96,100,128,120'/>
<FontCharacter Advance='32' Code='89' Name='Y - Equipment' SourceFile='ui_font_buttons_4_00' SourceRect='32,20,64,40'/>
<FontCharacter Advance='32' Code='90' Name='Z - Enemy Resources' SourceFile='ui_font_buttons_4_00' SourceRect='64,20,96,40'/>
<FontCharacter Advance='32' Code='97' Name='a - Monitor' SourceFile='ui_font_buttons_2_00' SourceRect='0,0,32,20'/>
<FontCharacter Advance='32' Code='98' Name='b - Launch droppod' SourceFile='ui_font_buttons_2_00' SourceRect='32,0,64,20'/>
<FontCharacter Advance='32' Code='99' Name='c - Find' SourceFile='ui_font_buttons_2_00' SourceRect='64,0,96,20'/>
<FontCharacter Advance='32' Code='100' Name='d - Exit droppod' SourceFile='ui_font_buttons_2_00' SourceRect='96,0,128,20'/>
<FontCharacter Advance='32' Code='101' Name='e - Message' SourceFile='ui_font_buttons_2_00' SourceRect='0,20,32,40'/>
<FontCharacter Advance='32' Code='102' Name='f - Player info' SourceFile='ui_font_buttons_2_00' SourceRect='32,20,64,40'/>
<FontCharacter Advance='32' Code='103' Name='g - Learn Cert' SourceFile='ui_font_buttons_2_00' SourceRect='64,20,96,40'/>
<FontCharacter Advance='32' Code='104' Name='h - Unlearn Cert' SourceFile='ui_font_buttons_2_00' SourceRect='96,20,128,40'/>
<FontCharacter Advance='32' Code='105' Name='i - Yes' SourceFile='ui_font_buttons_2_00' SourceRect='0,40,32,60'/>
<FontCharacter Advance='32' Code='106' Name='j - No' SourceFile='ui_font_buttons_2_00' SourceRect='32,40,64,60'/>
<FontCharacter Advance='32' Code='107' Name='k - Install Implant' SourceFile='ui_font_buttons_2_00' SourceRect='64,40,96,60'/>
<FontCharacter Advance='32' Code='108' Name='l - Remove Implant' SourceFile='ui_font_buttons_2_00' SourceRect='96,40,128,60'/>
<FontCharacter Advance='32' Code='109' Name='m - Inventory' SourceFile='ui_font_buttons_2_00' SourceRect='0,60,32,80'/>
<FontCharacter Advance='32' Code='110' Name='n - Character' SourceFile='ui_font_buttons_2_00' SourceRect='32,60,64,80'/>
<FontCharacter Advance='32' Code='111' Name='o - Map' SourceFile='ui_font_buttons_2_00' SourceRect='64,60,96,80'/>
<FontCharacter Advance='32' Code='112' Name='p - Vehicle' SourceFile='ui_font_buttons_2_00' SourceRect='96,60,128,80'/>
<FontCharacter Advance='32' Code='113' Name='q - Retrieve Vehicle' SourceFile='ui_font_buttons_2_00' SourceRect='0,80,32,100'/>
<FontCharacter Advance='32' Code='114' Name='r - Outgoing chat' SourceFile='ui_font_buttons_2_00' SourceRect='32,80,64,100'/>
<FontCharacter Advance='32' Code='115' Name='s - Incoming chat' SourceFile='ui_font_buttons_2_00' SourceRect='64,80,96,100'/>
<FontCharacter Advance='32' Code='116' Name='t - Open Chat' SourceFile='ui_font_buttons_2_00' SourceRect='96,80,128,100'/>
<FontCharacter Advance='32' Code='117' Name='u - Outfit Chat' SourceFile='ui_font_buttons_2_00' SourceRect='0,100,32,120'/>
<FontCharacter Advance='32' Code='118' Name='v - Squad Chat' SourceFile='ui_font_buttons_2_00' SourceRect='32,100,64,120'/>
<FontCharacter Advance='32' Code='119' Name='w - Command Chat' SourceFile='ui_font_buttons_2_00' SourceRect='64,100,96,120'/>
<FontCharacter Advance='32' Code='120' Name='x - Alliance Chat' SourceFile='ui_font_buttons_2_00' SourceRect='96,100,128,120'/>
</TextStyle>
<include>ui_font_med.inc</include>
<include>ui_font_med.inc</include>
<include>ui_overheadfont.inc</include>
<include>ui_arial14.inc</include>
<include>ui_sf_chaerilidae_18.inc</include>
<include>ui_font_eurostile8.inc</include>
<include>ui_font_eurostile10.inc</include>
<include>ui_font_eurostile12.inc</include>
</Namespace>
