<TextStyle CachedStyle='6' Leading='20' Name='Medium' UseCachedFont='true'>
<FontCharacter Advance='8' Code='32' SourceFile='ps_interface_font_med' SourceRect='230,80,235,100'/>
<FontCharacter Advance='7' Code='33' SourceFile='ps_interface_font_med' SourceRect='69,60,76,80'/>
<FontCharacter Advance='11' Code='34' SourceFile='ps_interface_font_med' SourceRect='35,80,46,100'/>
<FontCharacter Advance='18' Code='35' SourceFile='ps_interface_font_med' SourceRect='91,60,109,80'/>
<FontCharacter Advance='16' Code='36' SourceFile='ps_interface_font_med' SourceRect='109,60,125,80'/>
<FontCharacter Advance='27' Code='37' SourceFile='ps_interface_font_med' SourceRect='126,60,153,80'/>
<FontCharacter Advance='18' Code='38' SourceFile='ps_interface_font_med' SourceRect='167,60,185,80'/>
<FontCharacter Advance='6' Code='39' SourceFile='ps_interface_font_med' SourceRect='20,60,26,80'/>
<FontCharacter Advance='10' Code='40' SourceFile='ps_interface_font_med' SourceRect='197,60,207,80'/>
<FontCharacter Advance='10' Code='41' SourceFile='ps_interface_font_med' SourceRect='207,60,217,80'/>
<FontCharacter Advance='10' Code='42' SourceFile='ps_interface_font_med' SourceRect='186,60,196,80'/>
<FontCharacter Advance='12' Code='43' SourceFile='ps_interface_font_med' SourceRect='229,60,241,80'/>
<FontCharacter Advance='7' Code='44' SourceFile='ps_interface_font_med' SourceRect='27,60,34,80'/>
<FontCharacter Advance='10' Code='45' SourceFile='ps_interface_font_med' SourceRect='203,40,213,60'/>
<FontCharacter Advance='6' Code='46' SourceFile='ps_interface_font_med' SourceRect='34,60,42,80'/>
<FontCharacter Advance='14' Code='47' SourceFile='ps_interface_font_med' SourceRect='42,60,56,80'/>
<FontCharacter Advance='18' Code='48' SourceFile='ps_interface_font_med' SourceRect='176,40,195,60'/>
<FontCharacter Advance='8' Code='49' SourceFile='ps_interface_font_med' SourceRect='20,40,28,53'/>
<FontCharacter Advance='17' Code='50' SourceFile='ps_interface_font_med' SourceRect='29,40,47,60'/>
<FontCharacter Advance='17' Code='51' SourceFile='ps_interface_font_med' SourceRect='48,40,65,60'/>
<FontCharacter Advance='17' Code='52' SourceFile='ps_interface_font_med' SourceRect='66,40,85,60'/>
<FontCharacter Advance='17' Code='53' SourceFile='ps_interface_font_med' SourceRect='85,40,103,60'/>
<FontCharacter Advance='16' Code='54' SourceFile='ps_interface_font_med' SourceRect='104,40,121,60'/>
<FontCharacter Advance='16' Code='55' SourceFile='ps_interface_font_med' SourceRect='122,40,139,60'/>
<FontCharacter Advance='16' Code='56' SourceFile='ps_interface_font_med' SourceRect='140,40,157,60'/>
<FontCharacter Advance='18' Code='57' SourceFile='ps_interface_font_med' SourceRect='158,40,176,60'/>
<FontCharacter Advance='7' Code='58' SourceFile='ps_interface_font_med' SourceRect='27,80,34,100'/>
<FontCharacter Advance='7' Code='59' SourceFile='ps_interface_font_med' SourceRect='12,60,19,80'/>
<FontCharacter Advance='12' Code='60' SourceFile='ps_interface_font_med' SourceRect='46,80,58,100'/>
<FontCharacter Advance='13' Code='61' SourceFile='ps_interface_font_med' SourceRect='213,40,226,60'/>
<FontCharacter Advance='12' Code='62' SourceFile='ps_interface_font_med' SourceRect='57,80,69,100'/>
<FontCharacter Advance='15' Code='63' SourceFile='ps_interface_font_med' SourceRect='70,80,85,100'/>
<FontCharacter Advance='14' Code='64' SourceFile='ps_interface_font_med' SourceRect='77,60,91,80'/>
<FontCharacter Advance='21' Code='65' SourceFile='ps_interface_font_med' SourceRect='0,0,22,20'/>
<FontCharacter Advance='18' Code='66' SourceFile='ps_interface_font_med' SourceRect='22,0,41,20'/>
<FontCharacter Advance='18' Code='67' SourceFile='ps_interface_font_med' SourceRect='41,0,60,20'/>
<FontCharacter Advance='20' Code='68' SourceFile='ps_interface_font_med' SourceRect='60,0,81,20'/>
<FontCharacter Advance='17' Code='69' SourceFile='ps_interface_font_med' SourceRect='81,0,99,20'/>
<FontCharacter Advance='16' Code='70' SourceFile='ps_interface_font_med' SourceRect='99,0,116,20'/>
<FontCharacter Advance='19' Code='71' SourceFile='ps_interface_font_med' SourceRect='116,0,137,20'/>
<FontCharacter Advance='19' Code='72' SourceFile='ps_interface_font_med' SourceRect='137,0,158,20'/>
<FontCharacter Advance='6' Code='73' SourceFile='ps_interface_font_med' SourceRect='158,0,165,20'/>
<FontCharacter Advance='18' Code='74' SourceFile='ps_interface_font_med' SourceRect='165,0,183,20'/>
<FontCharacter Advance='19' Code='75' SourceFile='ps_interface_font_med' SourceRect='183,0,202,20'/>
<FontCharacter Advance='15' Code='76' SourceFile='ps_interface_font_med' SourceRect='202,0,218,20'/>
<FontCharacter Advance='24' Code='77' SourceFile='ps_interface_font_med' SourceRect='218,0,242,20'/>
<FontCharacter Advance='20' Code='78' SourceFile='ps_interface_font_med' SourceRect='1,20,22,40'/>
<FontCharacter Advance='18' Code='79' SourceFile='ps_interface_font_med' SourceRect='22,20,41,40'/>
<FontCharacter Advance='18' Code='80' SourceFile='ps_interface_font_med' SourceRect='42,20,61,40'/>
<FontCharacter Advance='20' Code='81' SourceFile='ps_interface_font_med' SourceRect='61,20,81,40'/>
<FontCharacter Advance='18' Code='82' SourceFile='ps_interface_font_med' SourceRect='82,20,100,40'/>
<FontCharacter Advance='18' Code='83' SourceFile='ps_interface_font_med' SourceRect='101,20,119,40'/>
<FontCharacter Advance='17' Code='84' SourceFile='ps_interface_font_med' SourceRect='120,20,138,40'/>
<FontCharacter Advance='19' Code='85' SourceFile='ps_interface_font_med' SourceRect='138,20,158,40'/>
<FontCharacter Advance='20' Code='86' SourceFile='ps_interface_font_med' SourceRect='157,20,178,40'/>
<FontCharacter Advance='26' Code='87' SourceFile='ps_interface_font_med' SourceRect='177,20,205,40'/>
<FontCharacter Advance='19' Code='88' SourceFile='ps_interface_font_med' SourceRect='204,20,224,40'/>
<FontCharacter Advance='18' Code='89' SourceFile='ps_interface_font_med' SourceRect='223,20,243,40'/>
<FontCharacter Advance='17' Code='90' SourceFile='ps_interface_font_med' SourceRect='1,40,20,60'/>
<FontCharacter Advance='10' Code='91' SourceFile='ps_interface_font_med' SourceRect='238,40,248,60'/>
<FontCharacter Advance='14' Code='92' SourceFile='ps_interface_font_med' SourceRect='225,40,239,60'/>
<FontCharacter Advance='10' Code='93' SourceFile='ps_interface_font_med' SourceRect='1,60,11,80'/>
<FontCharacter Advance='14' Code='94' SourceFile='ps_interface_font_med' SourceRect='153,60,167,80'/>
<FontCharacter Advance='13' Code='95' SourceFile='ps_interface_font_med' SourceRect='216,60,229,80'/>
<FontCharacter Advance='9' Code='96' SourceFile='ps_interface_font_med' SourceRect='195,40,203,60'/>
<FontCharacter Advance='21' Code='97' SourceFile='ps_interface_font_med' SourceRect='0,0,22,20'/>
<FontCharacter Advance='18' Code='98' SourceFile='ps_interface_font_med' SourceRect='22,0,41,20'/>
<FontCharacter Advance='18' Code='99' SourceFile='ps_interface_font_med' SourceRect='41,0,60,20'/>
<FontCharacter Advance='20' Code='100' SourceFile='ps_interface_font_med' SourceRect='60,0,81,20'/>
<FontCharacter Advance='17' Code='101' SourceFile='ps_interface_font_med' SourceRect='81,0,99,20'/>
<FontCharacter Advance='16' Code='102' SourceFile='ps_interface_font_med' SourceRect='99,0,116,20'/>
<FontCharacter Advance='19' Code='103' SourceFile='ps_interface_font_med' SourceRect='116,0,137,20'/>
<FontCharacter Advance='19' Code='104' SourceFile='ps_interface_font_med' SourceRect='137,0,158,20'/>
<FontCharacter Advance='6' Code='105' SourceFile='ps_interface_font_med' SourceRect='158,0,165,20'/>
<FontCharacter Advance='18' Code='106' SourceFile='ps_interface_font_med' SourceRect='165,0,183,20'/>
<FontCharacter Advance='19' Code='107' SourceFile='ps_interface_font_med' SourceRect='183,0,202,20'/>
<FontCharacter Advance='15' Code='108' SourceFile='ps_interface_font_med' SourceRect='202,0,218,20'/>
<FontCharacter Advance='24' Code='109' SourceFile='ps_interface_font_med' SourceRect='218,0,242,20'/>
<FontCharacter Advance='20' Code='110' SourceFile='ps_interface_font_med' SourceRect='1,20,22,40'/>
<FontCharacter Advance='18' Code='111' SourceFile='ps_interface_font_med' SourceRect='22,20,41,40'/>
<FontCharacter Advance='18' Code='112' SourceFile='ps_interface_font_med' SourceRect='42,20,61,40'/>
<FontCharacter Advance='20' Code='113' SourceFile='ps_interface_font_med' SourceRect='61,20,81,40'/>
<FontCharacter Advance='18' Code='114' SourceFile='ps_interface_font_med' SourceRect='82,20,100,40'/>
<FontCharacter Advance='18' Code='115' SourceFile='ps_interface_font_med' SourceRect='101,20,119,40'/>
<FontCharacter Advance='17' Code='116' SourceFile='ps_interface_font_med' SourceRect='120,20,138,40'/>
<FontCharacter Advance='19' Code='117' SourceFile='ps_interface_font_med' SourceRect='138,20,158,40'/>
<FontCharacter Advance='20' Code='118' SourceFile='ps_interface_font_med' SourceRect='157,20,178,40'/>
<FontCharacter Advance='26' Code='119' SourceFile='ps_interface_font_med' SourceRect='177,20,205,40'/>
<FontCharacter Advance='19' Code='120' SourceFile='ps_interface_font_med' SourceRect='204,20,224,40'/>
<FontCharacter Advance='18' Code='121' SourceFile='ps_interface_font_med' SourceRect='223,20,243,40'/>
<FontCharacter Advance='17' Code='122' SourceFile='ps_interface_font_med' SourceRect='1,40,20,60'/>
<FontCharacter Advance='13' Code='123' SourceFile='ps_interface_font_med' SourceRect='1,80,14,100'/>
<FontCharacter Advance='12' Code='124' SourceFile='ps_interface_font_med' SourceRect='241,60,249,80'/>
<FontCharacter Advance='13' Code='125' SourceFile='ps_interface_font_med' SourceRect='14,80,26,100'/>
<FontCharacter Advance='13' Code='126' SourceFile='ps_interface_font_med' SourceRect='55,60,68,80'/>
</TextStyle>
<TextStyle Leading='37' Name='HUDNumerals'>
<FontCharacter Advance='27' Code='37' SourceRect='56,74,84,111'/>
<FontCharacter Advance='27' Code='48' SourceRect='28,74,56,111'/>
<FontCharacter Advance='27' Code='49' SourceRect='0,0,28,37'/>
<FontCharacter Advance='27' Code='50' SourceRect='28,0,56,37'/>
<FontCharacter Advance='27' Code='51' SourceRect='56,0,84,37'/>
<FontCharacter Advance='27' Code='52' SourceRect='84,0,112,37'/>
<FontCharacter Advance='27' Code='53' SourceRect='0,37,28,74'/>
<FontCharacter Advance='27' Code='54' SourceRect='28,37,56,74'/>
<FontCharacter Advance='27' Code='55' SourceRect='56,37,84,74'/>
<FontCharacter Advance='27' Code='56' SourceRect='84,37,112,74'/>
<FontCharacter Advance='27' Code='57' SourceRect='0,74,28,111'/>
</TextStyle>
