<Namespace Name='DefaultGrid'>
<ImageStyle Name='normal.background'>
<ImageFrame Source='ui_grid' SourceRect='30,0,59,28'/>
</ImageStyle>
<ImageStyle Name='normal.hstartcap'>
<ImageFrame Source='ui_grid' SourceRect='30,28,31,29'/>
</ImageStyle>
<ImageStyle Name='normal.hbackground'>
<ImageFrame Source='ui_grid' SourceRect='31,28,58,29'/>
</ImageStyle>
<ImageStyle Name='normal.hendcap'>
<ImageFrame Source='ui_grid' SourceRect='58,28,59,29'/>
</ImageStyle>
<ImageStyle Name='normal.vstartcap'>
<ImageFrame Source='ui_grid' SourceRect='59,0,60,1'/>
</ImageStyle>
<ImageStyle Name='normal.vbackground'>
<ImageFrame Source='ui_grid' SourceRect='59,1,60,27'/>
</ImageStyle>
<ImageStyle Name='normal.vendcap'>
<ImageFrame Source='ui_grid' SourceRect='59,27,60,28'/>
</ImageStyle>
<ImageStyle Name='normal.junction'>
<ImageFrame Source='ui_grid' SourceRect='59,28,60,29'/>
</ImageStyle>
<ImageStyle Name='selected.background'>
<ImageFrame Source='ui_grid' SourceRect='0,0,29,28'/>
</ImageStyle>
<ImageStyle Name='selected.hstartcap'>
<ImageFrame Source='ui_grid' SourceRect='0,28,1,28'/>
</ImageStyle>
<ImageStyle Name='selected.hbackground'>
<ImageFrame Source='ui_grid' SourceRect='1,28,28,29'/>
</ImageStyle>
<ImageStyle Name='selected.hendcap'>
<ImageFrame Source='ui_grid' SourceRect='28,28,29,29'/>
</ImageStyle>
<ImageStyle Name='selected.vstartcap'>
<ImageFrame Source='ui_grid' SourceRect='29,0,30,1'/>
</ImageStyle>
<ImageStyle Name='selected.vbackground'>
<ImageFrame Source='ui_grid' SourceRect='29,1,30,27'/>
</ImageStyle>
<ImageStyle Name='selected.vendcap'>
<ImageFrame Source='ui_grid' SourceRect='29,27,30,28'/>
</ImageStyle>
<ImageStyle Name='selected.junction'>
<ImageFrame Source='ui_grid' SourceRect='29,28,30,29'/>
</ImageStyle>
<GridStyle Name='style' Normal.Background='normal.background' Normal.HBackground='normal.hbackground' Normal.HEndCap='normal.hendcap' Normal.HStartCap='normal.hstartcap' Normal.Junction='normal.junction' Normal.VBackground='normal.vbackground' Normal.VEndCap='normal.vendcap' Normal.VStartCap='normal.vstartcap' Selected.Background='selected.background' Selected.HBackground='selected.hbackground' Selected.HEndCap='selected.hendcap' Selected.HStartCap='selected.hstartcap' Selected.Junction='selected.junction' Selected.VBackground='selected.vbackground' Selected.VEndCap='selected.vendcap' Selected.VStartCap='selected.vstartcap'/>
</Namespace>
<Namespace Name='EmbeddedGrid'>
<ImageStyle Name='normal.background'>
<ImageFrame Source='ui_gridnoedges_00' SourceRect='30,0,60,29'/>
</ImageStyle>
<ImageStyle Name='selected.background'>
<ImageFrame Source='ui_gridnoedges_00' SourceRect='0,0,30,29'/>
</ImageStyle>
<GridStyle Name='style' Normal.Background='normal.background' Selected.Background='selected.background'/>
</Namespace>
