<Page crosshairtype='ace' defaultcolor='#FFFFFF' enemycolor='#FF0000' friendlycolor='#00FF00' GetsInput='false' Location='262,134' Name='AceCrosshair' PackLocation='Center,Center' PackLocationProp='-250/0001,-250/0001' ScrollExtent='500,500' Size='500,500' Visible='false' visualeditlock='true'>
<Text Font='/SmallFont' LocalText='Valid Deploy Zone' Location='100,112' Name='ID' Opacity='0.500' ScrollExtent='100,12' Size='100,12' Visible='false'>Valid Deploy Zone</Text>
<Ellipse ArcEnd='0.000' Location='234,234' Name='COF' Opacity='0.500' Rotation='0.500' ScrollExtent='32,32' Size='32,32' Thickness='2.000'/>
<Ellipse ArcBegin='0.500' Color='#FF80FF' InnerRadiusColor='#00FF00' Location='229,229' Name='Fade' Opacity='0.010' Rotation='0.500' ScrollExtent='42,42' Size='42,42' Thickness='5.000' Visible='false'/>
<Image Location='234,202' Name='COF_Top' Opacity='0.500' ScrollExtent='32,32' Size='32,32' SourceRect='34,0,66,32' SourceResource='ui_pistol_crosshair' Visible='false'/>
<Image BackgroundColor='#FFFF80' BackgroundTint='#FFFF80' Location='202,234' Name='COF_Left' Opacity='0.500' ScrollExtent='32,32' Size='32,32' SourceRect='0,34,32,66' SourceResource='ui_pistol_crosshair' Visible='false'/>
<Image Location='234,234' Name='Reticle' Opacity='0.500' ScrollExtent='32,32' Size='32,32' SourceRect='0,0,32,32' SourceResource='ui_deploy_crosshair'/>
<Image Location='266,234' Name='COF_Right' Opacity='0.500' ScrollExtent='32,32' Size='32,32' SourceRect='68,34,100,66' SourceResource='ui_pistol_crosshair' Visible='false'/>
<Image Location='234,265' Name='COF_Bottom' Opacity='0.500' ScrollExtent='32,32' Size='32,32' SourceRect='34,66,66,100' SourceResource='ui_pistol_crosshair' Visible='false'/>
</Page>
