<Page Location='18,70' Name='FindSquadPage' PackLocation='left,top' PackLocationProp='0018/0001,0070/0001' PackSize='absolute,absolute' PackSizeProp='0036/0001,0090/0001' ScrollExtent='558,368' Size='558,368' Visible='false'>
<Page Name='SquadListPage' PackLocation='left,top' PackLocationProp='0000/0001,0000/0001' PackSize='absolute,absolute' PackSizeProp='0000/0001,0003/0001' ScrollExtent='558,365' Size='558,365' Visible='false'>
<Page Location='387,333' Name='LFSStatusPage' PackLocation='proportional,bottom' PackLocationProp='0456/0558,-032/0001' ScrollExtent='139,27' Size='139,27'>
<Checkbox BackgroundOpacity='1.000' LocalTooltip='[@FindLookingOffTooltip]' Location='59,3' Name='LookingOff' PackLocation='fixed,fixed' ScrollExtent='80,22' Size='80,22' Style='/Buttons.LargeRadiobox.style' Tooltip='@FindLookingOffTooltip'>@NL</Checkbox>
<Checkbox BackgroundOpacity='1.000' LocalTooltip='[@FindLookingOnTooltip]' Location='1,3' Name='LookingOn' PackLocation='fixed,fixed' ScrollExtent='57,22' Size='57,22' Style='/Buttons.LargeRadiobox.style' Tooltip='@FindLookingOnTooltip'>@L</Checkbox>
</Page>
<Text AbsorbsInput='false' Font='/Fonts.HudFont2' GetsInput='false' LocalText='[@SquadSearchLegendFullNotCertified]' Location='408,299' Name='LegendFullNotCertifiedText' PackLocation='proportional,bottom' PackLocationProp='0478/0558,-066/0001' PackSize='fixed,fixed' PackSizeProp='0002/0003,0002/0003' ScrollExtent='140,28' Size='140,20' TextAlignment='Center' TextAlignmentVertical='Center'>@SquadSearchLegendFullNotCertified</Text>
<Text AbsorbsInput='false' Font='/Fonts.HudFont2' GetsInput='false' LocalText='[@SquadSearchLegendOpenAvailable]' Location='315,299' Name='LegendOpenAvailableText' PackLocation='proportional,bottom' PackLocationProp='0359/0558,-066/0001' PackSize='fixed,fixed' PackSizeProp='0002/0003,0002/0003' ScrollExtent='88,42' Size='88,20' TextAlignment='Center' TextAlignmentVertical='Center'>@SquadSearchLegendOpenAvailable</Text>
<Text AbsorbsInput='false' Font='/Fonts.HudFont2' GetsInput='false' LocalText='[@SquadSearchLegendQualified]' Location='192,299' Name='LegendCertQualifiedText' PackLocation='proportional,bottom' PackLocationProp='0252/0558,-066/0001' PackSize='fixed,fixed' PackSizeProp='0002/0003,0002/0003' ScrollExtent='120,28' Size='120,20' TextAlignment='Center' TextAlignmentVertical='Center'>@SquadSearchLegendQualified</Text>
<Text AbsorbsInput='false' Font='/Fonts.HudFont2' GetsInput='false' LocalText='[@SquadSearchLegendSearchHit]' Location='84,299' Name='LegendSearchHitText' PackLocation='proportional,bottom' PackLocationProp='0134/0558,-066/0001' PackSize='fixed,fixed' PackSizeProp='0002/0003,0002/0003' ScrollExtent='100,28' Size='100,20' TextAlignment='Center' TextAlignmentVertical='Center'>@SquadSearchLegendSearchHit</Text>
<Text AbsorbsInput='false' Font='/Fonts.HudFont3' GetsInput='false' LocalText='[@SquadSearchLegend]' Location='5,299' Name='LegendText' PackLocation='left,bottom' PackLocationProp='0005/0001,-066/0001' PackSize='fixed,fixed' PackSizeProp='0002/0003,0002/0003' ScrollExtent='78,51' Size='78,20' TextAlignment='Center' TextAlignmentVertical='Center'>@SquadSearchLegend</Text>
<Image BackgroundOpacity='1.000' Location='2,294' Name='LegendBorder' PackLocation='left,bottom' PackLocationProp='0002/0001,-071/0001' PackSize='absolute,fixed' PackSizeProp='0005/0001,0002/0003' RStyleDefault='/WindowPanes.ButtonBorder.style' ScrollExtent='553,31' Size='553,31'/>
<Image BackgroundOpacity='1.000' Location='2,331' Name='ButtonBorder' PackLocation='left,bottom' PackLocationProp='0002/0001,-034/0001' PackSize='absolute,fixed' PackSizeProp='0005/0001,0002/0003' RStyleDefault='/WindowPanes.ButtonBorder.style' ScrollExtent='553,31' Size='553,31'/>
<Image AbsorbsInput='false' BackgroundOpacity='1.000' Color='#385E61' Location='2,2' Name='TabBorder' PackLocation='left,top' PackLocationProp='0002/0001,0002/0001' PackSize='absolute,absolute' PackSizeProp='0004/0001,0080/0001' RStyleDefault='/WindowPanes.TabBorder.style' ScrollExtent='554,285' Size='554,285'/>
<Button LocalText='[@SquadSearchListSquadLeaderHeading]' LocalTooltip='[@SquadSearchListSquadLeaderHeadingTooltip]' Location='8,7' Name='SquadLeaderHeadingButton' PackLocation='left,top' PackLocationProp='0008/0001,0007/0001' PackSize='fixed,fixed' PackSizeProp='0002/0003,0002/0003' ScrollExtent='115,20' Size='115,20' Style='/Buttons.ListboxHeading.style' Tooltip='@SquadSearchListSquadLeaderHeadingTooltip' TooltipStyle='/Tooltips.Default'>@SquadSearchListSquadLeaderHeading</Button>
<Button LocalText='[@SquadSearchListPurposeHeading]' LocalTooltip='[@SquadSearchListPurposeHeadingTooltip]' Location='128,7' Name='PurposeHeadingButton' PackLocation='left,top' PackLocationProp='0128/0001,0007/0001' PackSize='absolute,fixed' PackSizeProp='0290/0001,0002/0003' ScrollExtent='268,20' Size='268,20' Style='/Buttons.ListboxHeading.style' Tooltip='@SquadSearchListPurposeHeadingTooltip' TooltipStyle='/Tooltips.Default'>@SquadSearchListPurposeHeading</Button>
<Button LocalText='[@SquadSearchListLocationHeading]' LocalTooltip='[@SquadSearchListLocationHeadingTooltip]' Location='401,7' Name='LocationHeadingButton' PackLocation='right,top' PackLocationProp='-157/0001,0007/0001' PackSize='fixed,fixed' PackSizeProp='0002/0003,0002/0003' ScrollExtent='83,20' Size='83,20' Style='/Buttons.ListboxHeading.style' Tooltip='@SquadSearchListLocationHeadingTooltip' TooltipStyle='/Tooltips.Default'>@SquadSearchListLocationHeading</Button>
<Button LocalText='[@SquadSearchListSizeHeading]' LocalTooltip='[@SquadSearchListSizeHeadingTooltip]' Location='489,7' Name='SizeHeadingButton' PackLocation='right,top' PackLocationProp='-069/0001,0007/0001' PackSize='fixed,fixed' PackSizeProp='0002/0003,0002/0003' ScrollExtent='51,20' Size='51,20' Style='/Buttons.ListboxHeading.style' Tooltip='@SquadSearchListSizeHeadingTooltip' TooltipStyle='/Tooltips.Default'>@SquadSearchListSizeHeading</Button>
<Template Name='ListboxTemplate' Size='535,20'>\<text color = \'$color$\' font = \'/Fonts.HudFont2\' location = \'5,1\' maxlines = \'1\' size = \'95,16\' visible = \'true\'\>
$squadleadername$
\</text\>
\<text color = \'$color$\' font = \'/Fonts.HudFont2\' location = \'128,1\' maxlines = \'1\' size = \'$purpose.w$,16\' visible = \'true\'\>
$purpose$
\</text\>
\<text color = \'$color$\' font = \'/Fonts.HudFont2\' location = \'$zone.x$,1\' maxlines = \'1\' size = \'85,16\' visible = \'true\'\>
$location$
\</text\>
\<text color = \'$color$\' font = \'/Fonts.HudFont2\' location = \'$squadsize.x$,1\' maxlines = \'1\' size = \'80,16\' visible = \'true\'\>
$size$
\</text\></Template>
<Listbox DataSource='SquadsDataSource' Location='4,28' Name='SquadsListbox' PackSize='absolute,absolute' PackSizeProp='0019/0001,0109/0001' RowTemplate='ListboxTemplate' ScrollExtent='539,256' Size='539,256' Style='/Listboxes.Clear.style'/>
<Scrollbar Control='SquadsListbox' Location='544,29' Name='SquadsScrollbar' PackLocation='right,top' PackLocationProp='-014/0001,0029/0001' PackSize='fixed,absolute' PackSizeProp='0002/0003,0111/0001' ScrollExtent='9,254' Size='9,254' Style='/ScrollBars.vertical.style'/>
<DataSource Name='SquadsDataSource'>
<Data isheading='false' isitem='true' location='Drugaskan' Name='DummySquad0' purpose='another purpose' purpose.w='270' size='10/10' squadleadername='Korealis' squadname='abcdef' squadsize.x='489' zone.x='401'/>
<Data isheading='false' isitem='true' location='Desolation' Name='DummySquad0' purpose='another purpose' purpose.w='270' size='6/7' squadleadername='Holeesh' squadname='abcdef' squadsize.x='489' zone.x='401'/>
<Data isheading='false' isitem='true' Name='DummySquad1' purpose='blah blah blah' purpose.w='270' size='10/10' squadleadername='PsychoSanta' squadname='teh best' squadsize.x='489' zone.x='401'/>
<Data color='#00FF00' isheading='false' isitem='true' location='Cyssor' Name='DummySquad0' purpose='another purpose' purpose.w='270' size='8/10' squadleadername='Squishling' squadname='abcdef' squadsize.x='489' zone.x='401'/>
</DataSource>
<Button LocalText='[@SquadSearchListDetails]' LocalTooltip='[@SquadSearchListDetailsTooltip]' Location='51,336' Name='DetailsButton' PackLocation='proportional,bottom' PackLocationProp='0111/0558,-029/0001' ScrollExtent='120,20' Size='120,20' Style='/Buttons.TextButton.style' Tooltip='@SquadSearchListDetailsTooltip' TooltipStyle='/Tooltips.Default'>@SquadSearchListDetails</Button>
<Button LocalText='[@SquadSearchListSearch]' LocalTooltip='[@SquadSearchListSearchTooltip]' Location='220,336' Name='SearchButton' PackLocation='center,bottom' PackLocationProp='-059/0001,-029/0001' ScrollExtent='120,20' Size='120,20' Style='/Buttons.TextButton.style' Tooltip='@SquadSearchListSearchTooltip' TooltipStyle='/Tooltips.Default'>@SquadSearchListSearch</Button>
<Button LocalText='[@SquadSearchListCancelSearch]' LocalTooltip='[@SquadSearchListCancelSearchTooltip]' Location='220,336' Name='CancelSearchButton' PackLocation='center,bottom' PackLocationProp='-059/0001,-029/0001' ScrollExtent='120,20' Size='120,20' Style='/Buttons.TextButton.style' Tooltip='@SquadSearchListCancelSearchTooltip' TooltipStyle='/Tooltips.Default'>@SquadSearchListCancelSearch</Button>
</Page>
<Page Name='SquadSearchPage' PackLocation='left,top' PackLocationProp='0000/0001,0000/0001' PackSize='absolute,absolute' PackSizeProp='0000/0001,0002/0001' ScrollExtent='558,366' Size='558,366' Visible='false'>
<Rectangle Color='#385E61' Location='279,92' Name='ProportionalRect' PackLocation='proportional,top' PackLocationProp='0419/0558,0092/0001' PackSize='proportional,absolute' PackSizeProp='0280/0558,0133/0001' ScrollExtent='280,233' Size='280,233' Visible='false'/>
<Rectangle Color='#385E61' Location='0,92' Name='ProportionalRect' PackLocation='left,top' PackLocationProp='0000/0001,0092/0001' PackSize='proportional,absolute' PackSizeProp='0280/0558,0133/0001' ScrollExtent='280,233' Size='280,233' Visible='false'/>
<Image AbsorbsInput='false' BackgroundOpacity='1.000' Color='#385E61' Location='2,2' Name='TabBorder' PackLocation='left,top' PackLocationProp='0002/0001,0002/0001' PackSize='absolute,absolute' PackSizeProp='0004/0001,0036/0001' RStyleDefault='/WindowPanes.TabBorder.style' ScrollExtent='554,330' Size='554,330'/>
<Text Font='/Fonts.HudFont2' GetsInput='false' LocalText='[@SquadMemberRoleTitle]' Location='20,18' MaxLines='1' Name='RoleTitle' PackLocation='left,top' PackLocationProp='0020/0001,0018/0001' PackSize='fixed,fixed' PackSizeProp='0002/0003,0002/0003' ScrollExtent='100,28' Size='100,16'>@SquadMemberRoleTitle</Text>
<Textbox BackgroundOpacity='0.475' Location='139,13' MaxLength='64' Name='RoleTextbox' PackLocation='left,top' PackLocationProp='0139/0001,0013/0001' PackSize='absolute,fixed' PackSizeProp='0204/0001,0002/0003' ScrollExtent='354,25' Size='354,25' Style='/ConsoleTextbox.ShortStyle'></Textbox>
<Text Font='/Fonts.HudFont2' GetsInput='false' LocalText='[@SquadDefinitionLocationTitle]' Location='20,60' MaxLines='1' Name='LocationTitle' PackLocation='left,top' PackLocationProp='0020/0001,0060/0001' PackSize='fixed,fixed' PackSizeProp='0002/0003,0002/0003' ScrollExtent='99,28' Size='99,14'>@SquadDefinitionLocationTitle</Text>
<DataSource Name='LocationList'>
<Data Name='Cyssor'/>
<Data Name='Searhus'/>
<Data Name='Ishundar'/>
</DataSource>
<Template Name='LocationTemplate' Size='250,20'>\<text font = \'/Fonts.DefaultFont\' location = \'5,-1\' size = \'250,20\'\>
$LocationName$
\</text\></Template>
<Dropdownbox DataSource='LocationList' Location='139,49' Name='LocationDropdown' RowTemplate='LocationTemplate' ScrollExtent='214,32' SelectedItemIndex='1' Size='214,32' Style='/Dropdowns.HudPane.shortstyle'/>
<Image AbsorbsInput='false' BackgroundOpacity='1.000' Color='#385E61' Location='5,91' Name='CertificationCriteriaBorder' PackLocation='left,top' PackLocationProp='0005/0001,0091/0001' PackSize='absolute,absolute' PackSizeProp='0010/0001,0128/0001' RStyleDefault='/WindowPanes.TabBorder.style' ScrollExtent='548,238' Size='548,238'/>
<Image BackgroundOpacity='1.000' Location='6,91' Name='TabBorderTop5' Opacity='0.750' PackLocation='left,top' PackLocationProp='0006/0001,0091/0001' PackSize='fixed,fixed' PackSizeProp='0002/0003,0002/0003' ScrollExtent='13,1' Size='13,1' Style='TabBorderTopStyle'/>
<Text Font='/Fonts.HudFont2' GetsInput='false' LocalText='[@SquadRoleSearchCertificationCriteria]' Location='20,84' MaxLines='1' Name='CertificationCriteriaText' PackLocation='left,top' PackLocationProp='0020/0001,0084/0001' PackSize='fixed,fixed' PackSizeProp='0002/0003,0002/0003' ScrollExtent='120,28' Size='120,16'>@SquadRoleSearchCertificationCriteria</Text>
<Image BackgroundOpacity='1.000' Location='137,91' Name='TabBorderTop5' Opacity='0.750' PackLocation='left,top' PackLocationProp='0137/0001,0091/0001' PackSize='absolute,fixed' PackSizeProp='0143/0001,0002/0003' ScrollExtent='415,1' Size='415,1' Style='TabBorderTopStyle'/>
<Page BackgroundColor='#CC99FF' Name='LeftCertReqPage' PackSize='proportional,absolute' PackSizeProp='0280/0558,0029/0001' ScrollExtent='280,337' Size='280,337'>
<Button LocalText='[@SquadRoleSearchAddCertification]' LocalTooltip='[@SquadRoleSearchAddCertificationTooltip]' Location='70,305' Name='AddCertificationButton' PackLocation='center,bottom' PackLocationProp='-070/0001,-032/0001' ScrollExtent='145,20' Size='145,20' Style='/Buttons.TextButton.style' Tooltip='@SquadRoleSearchAddCertificationTooltip'>@SquadRoleSearchAddCertification</Button>
<Checkbox Activated='true' BackgroundOpacity='1.000' Checked='true' LocalTooltip='[@SquadRoleSearchAnyMatchingPositionTooltip]' Location='9,101' Name='AnyMatchingPositionCheckbox' ScrollExtent='260,20' Size='260,20' Style='/Buttons.Radiobox.style' Tooltip='@SquadRoleSearchAnyMatchingPositionTooltip'>@SquadRoleSearchAnyMatchingPosition</Checkbox>
<Checkbox BackgroundOpacity='1.000' LocalTooltip='[@SquadRoleSearchAnyAvailablePositionTooltip]' Location='9,119' Name='AnyAvailablePositionCheckbox' ScrollExtent='259,20' Size='259,20' Style='/Buttons.Radiobox.style' Tooltip='@SquadRoleSearchAnyAvailablePositionTooltip'>@SquadRoleSearchAnyAvailablePosition</Checkbox>
<Rectangle Color='#385E61' Location='8,138' Name='CertificationsTitleRect' PackLocation='left,top' PackLocationProp='0008/0001,0138/0001' PackSize='absolute,fixed' PackSizeProp='0011/0001,0002/0003' ScrollExtent='269,22' Size='269,22'/>
<Text AbsorbsInput='false' Font='/Fonts.HudFont3' GetsInput='false' LocalText='[@SquadRoleSearchCertificationsListTitle]' Location='10,139' Name='CertificationsTitleText' PackSize='absolute,fixed' PackSizeProp='0015/0001,0002/0003' ScrollExtent='265,34' Size='265,20' TextAlignment='Center'>@SquadRoleSearchCertificationsListTitle</Text>
<Rectangle Color='#385E61' Location='8,159' Name='CertificationsListRect' PackLocation='left,top' PackLocationProp='0008/0001,0159/0001' PackSize='absolute,absolute' PackSizeProp='0011/0001,0195/0001' ScrollExtent='269,142' Size='269,142'/>
<DataSource Name='CertificationsDataSource'>
<Data color='#FFFFFF' internationalize='ARMOR' isheading='true' isitem='false' isnotheading='false' Name='ArmorHeading' w='256'/>
<Data color='#FFFFFF' internationalize='Infiltration Suit' isheading='false' isitem='true' isnotheading='true' Name='armor_infil' w='256'/>
<Data color='#FFFFFF' internationalize='Uni-MAX' isheading='false' isitem='true' isnotheading='true' Name='armor_unimax'/>
<Data color='#FFFFFF' hasitem1='false' hasitem2='false' hasitem3='false' hasitem4='false' hasitem5='false' hasitem6='false' internationalize='SUPPORT' isheading='true' isitem='false' isnotheading='false' issubitem='false' Name='support'/>
<Data internationalize='Hacking' isheading='false' isnotheading='true' Name='support_hacking'/>
</DataSource>
<Template Name='CertificationsListTemplate' Size='270,20'>\<text color = \'$color\' font = \'/Fonts.HudFont2\' location = \'5,0\' maxlines = \'1\' size = \'$w$,20\' visible = \'$IsNotHeading$\'\>
$Internationalize$
\</text\>
\<text color = \'$color$\' font = \'/Fonts.HudFont1\' location = \'-18,2\' maxlines = \'1\' size = \'$w$,18\' textalignment = \'right\' truncateelipsis = \'false\' visible = \'$IsHeading$\'\>
$Internationalize$
\</text\>
\<Image backgroundopacity = \'1.000\' location = \'0,10\' name = \'UnderlineTemplate\' rstyledefault = \'/Listboxes.ListboxContentHeader.style\' scrollextent = \'$w$,8\' size = \'$w$,8\' visible = \'$IsHeading$\'/\></Template>
<Listbox DataSource='CertificationsDataSource' Location='10,160' Name='CertificationsListbox' PackLocation='left,top' PackLocationProp='0010/0001,0160/0001' PackSize='absolute,absolute' PackSizeProp='0024/0001,0197/0001' RowTemplate='CertificationsListTemplate' ScrollExtent='270,140' Size='256,140' Style='/Listboxes.Clear.style'/>
<Scrollbar Control='CertificationsListbox' Location='266,161' Name='CertificationsScrollbar' PackLocation='right,top' PackLocationProp='-014/0001,0161/0001' PackSize='fixed,absolute' PackSizeProp='0002/0003,0199/0001' ScrollExtent='9,138' Size='9,138' Style='/ScrollBars.vertical.style'/>
</Page>
<Page BackgroundColor='#99CCFF' Location='279,0' Name='RightCertReqPage' PackLocation='proportional,top' PackLocationProp='0419/0558,0000/0001' PackSize='proportional,absolute' PackSizeProp='0280/0558,0029/0001' ScrollExtent='280,337' Size='280,337'>
<Button LocalText='[@SquadRoleSearchRemoveCertification]' LocalTooltip='[@SquadRoleSearchRemoveCertificationTooltip]' Location='63,305' Name='RemoveCertificationButton' PackLocation='center,bottom' PackLocationProp='-077/0001,-032/0001' ScrollExtent='145,20' Size='145,20' Style='/Buttons.TextButton.style' Tooltip='@SquadRoleSearchRemoveCertificationTooltip'>@SquadRoleSearchRemoveCertification</Button>
<Checkbox BackgroundOpacity='1.000' LocalTooltip='[@SquadRoleSearchAnySpecifiedCertificationTooltip]' Location='3,101' Name='AnySpecifiedCertificationCheckbox' ScrollExtent='267,20' Size='267,20' Style='/Buttons.Radiobox.style' Tooltip='@SquadRoleSearchAnySpecifiedCertificationTooltip'>@SquadRoleSearchAnySpecifiedCertification</Checkbox>
<Checkbox BackgroundOpacity='1.000' LocalTooltip='[@SquadRoleSearchAllSpecifiedCertificationsTooltip]' Location='3,119' Name='AllSpecifiedCertificationsCheckbox' ScrollExtent='266,20' Size='266,20' Style='/Buttons.Radiobox.style' Tooltip='@SquadRoleSearchAllSpecifiedCertificationsTooltip'>@SquadRoleSearchAllSpecifiedCertifications</Checkbox>
<Rectangle Color='#385E61' Location='1,138' Name='SpecifiedCertificationsTitleRect' PackLocation='left,top' PackLocationProp='0001/0001,0138/0001' PackSize='absolute,fixed' PackSizeProp='0011/0001,0002/0003' ScrollExtent='269,22' Size='269,22'/>
<Text AbsorbsInput='false' Font='/Fonts.HudFont3' GetsInput='false' LocalText='[@SquadRoleSearchSpecifiedCertificationsListTitle]' Location='4,139' Name='SpecifiedCertificationsTitleText' PackSize='absolute,fixed' PackSizeProp='0015/0001,0002/0003' ScrollExtent='265,34' Size='265,20' TextAlignment='Center'>@SquadRoleSearchSpecifiedCertificationsListTitle</Text>
<Rectangle Color='#385E61' Location='1,159' Name='SpecifiedCertificationsListRect' PackLocation='left,top' PackLocationProp='0001/0001,0159/0001' PackSize='absolute,absolute' PackSizeProp='0011/0001,0195/0001' ScrollExtent='269,142' Size='269,142'/>
<DataSource Name='SpecifiedCertificationsDataSource'>
<Data color='#FFFFFF' internationalize='VEHICLES' isheading='true' isitem='false' isnotheading='false' Name='VehiclesHeading' w='257'/>
<Data color='#FFFFFF' internationalize='Air Support' isheading='false' isitem='true' isnotheading='true' Name='vehicles_airsupport' w='257'/>
</DataSource>
<Template Name='SpecifiedCertificationsListTemplate' Size='300,20'>\<text color = \'$color\' font = \'/Fonts.HudFont2\' location = \'5,0\' maxlines = \'1\' size = \'$w$,20\' visible = \'$IsNotHeading$\'\>
$Internationalize$
\</text\>
\<text color = \'$color$\' font = \'/Fonts.HudFont1\' location = \'-18,2\' maxlines = \'1\' size = \'$w$,18\' textalignment = \'right\' truncateelipsis = \'false\' visible = \'$IsHeading$\'\>
$Internationalize$
\</text\>
\<Image backgroundopacity = \'1.000\' location = \'0,10\' name = \'UnderlineTemplate\' rstyledefault = \'/Listboxes.ListboxContentHeader.style\' scrollextent = \'$w$,8\' size = \'$w$,8\' visible = \'$IsHeading$\'/\></Template>
<Listbox DataSource='SpecifiedCertificationsDataSource' Location='3,160' Name='SpecifiedCertificationsListbox' PackLocation='left,top' PackLocationProp='0003/0001,0160/0001' PackSize='absolute,absolute' PackSizeProp='0023/0001,0197/0001' RowTemplate='SpecifiedCertificationsListTemplate' ScrollExtent='300,140' Size='257,140' Style='/Listboxes.Clear.style'/>
<Scrollbar Control='SpecifiedCertificationsListbox' Location='259,161' Name='SpecifiedCertificationsScrollbar' PackLocation='right,top' PackLocationProp='-021/0001,0161/0001' PackSize='fixed,absolute' PackSizeProp='0002/0003,0199/0001' ScrollExtent='9,138' Size='9,138' Style='/ScrollBars.vertical.style'/>
</Page>
<DataSource Name='CertRequirementsDataSource'>
<Data color='#FFFFFF' internationalize='WEAPONS' isheading='true' isnotheading='false' Name='Dummy1' price='10000'/>
<Data color='#FFFFFF' internationalize='Ark of the Covenant' ischecked='false' isheading='false' isnotheading='true' Name='Dummy2' price='5000'/>
<Data color='#FFFFFF' internationalize='Whip' ischecked='true' isheading='false' isnotheading='true' Name='Dummy3' price='5000'/>
</DataSource>
<Image BackgroundOpacity='1.000' Location='1,336' Name='ButtonBorder' PackLocation='left,bottom' PackLocationProp='0001/0001,-030/0001' PackSize='absolute,fixed' PackSizeProp='0004/0001,0002/0003' RStyleDefault='/WindowPanes.ButtonBorder.style' ScrollExtent='554,31' Size='554,31'/>
<Button LocalText='[@SquadRoleCancel]' LocalTooltip='[@SquadRoleCancelTooltip]' Location='414,340' Name='CancelButton' PackLocation='right,bottom' PackLocationProp='-144/0001,-026/0001' ScrollExtent='120,20' Size='120,20' Style='/Buttons.TextButton.style' Tooltip='@SquadRoleCancelTooltip'>@SquadRoleCancel</Button>
<Button LocalText='[@SquadRoleUpdateSearch]' LocalTooltip='[@SquadRoleSearchTooltip]' Location='284,341' Name='SearchButton' PackLocation='right,bottom' PackLocationProp='-274/0001,-025/0001' ScrollExtent='120,20' Size='120,20' Style='/Buttons.TextButton.style' Tooltip='@SquadRoleSearchTooltip'>@SquadRoleUpdateSearch</Button>
<Template Name='ListboxTemplate' Size='347,22'>\<text color = \'$color\' font = \'/Fonts.HudFont2\' location = \'25,0\' maxlines = \'1\' size = \'317,20\' visible = \'$IsNotHeading$\'\>
$Internationalize$
\</text\>
\<text color = \'$color$\' font = \'/Fonts.HudFont1\' location = \'-18,2\' maxlines = \'1\' packlocation = \'left,top\' packlocationprop = \'0043/0001,0063/0001\' packsize = \'absolute,fixed\' packsizeprop = \'0209/0001,0002/0003\' size = \'347,18\' textalignment = \'right\' truncateelipsis = \'false\' visible = \'$IsHeading$\'\>
$Internationalize$
\</text\>
\<Image backgroundopacity = \'1.000\' location = \'5,10\' name = \'UnderlineTemplate\' rstyledefault = \'/Listboxes.ListboxContentHeader.style\' scrollextent = \'342,8\' size = \'342,8\' visible = \'$IsHeading$\'/\>
\<Checkbox backgroundopacity = \'1.000\' checked = \'$ischecked$\' location = \'5,-2\' scrollextent = \'15,17\' size = \'15,17\' style = \'/Buttons.DefaultCheckbox.style\' visible = \'$IsNotHeading$\'\>
\</Checkbox\></Template>
</Page>
</Page>
