<Page Activated='true' Name='TrainingZone' PackSize='1,1' PackSizeProp='0002/0003,0002/0003' ScrollExtent='1024,768' Size='1024,768' Visible='false'>
<Page AbsorbsInput='false' Location='293,259' Name='Select' PackLocation='center,center' PackLocationProp='-219/0001,-125/0001' ScrollExtent='455,233' Size='455,233'>
<Text BackgroundColor='#00F2C9' BackgroundOpacity='0.224' Font='/Fonts.HudFont2' LocalText='[@TrainingMenu]' Location='14,17' Name='MenuTitle' PackLocation='left,top' PackLocationProp='0014/0001,0017/0001' PackSize='absolute,fixed' PackSizeProp='0028/0001,0002/0003' ScrollExtent='427,21' Size='427,21' SizeIncrement='0,0' TextAlignment='Center' TextAlignmentVertical='Center'>@TrainingMenu</Text>
<Button LocalText='[@TrainingShooting]' Location='27,56' Name='Shooting' ScrollExtent='400,17' Size='400,17' Style='/Buttons.RespawnSelection.style'>@TrainingShooting</Button>
<Button LocalText='[@TrainingDriving]' Location='27,86' Name='Driving' ScrollExtent='400,17' Size='400,17' Style='/Buttons.RespawnSelection.style'>@TrainingDriving</Button>
<Button LocalText='[@TrainingGoHome]' Location='27,116' Name='Home' ScrollExtent='400,17' Size='400,17' Style='/Buttons.RespawnSelection.style'>@TrainingGoHome</Button>
<Button LocalText='[@TrainingCancel]' Location='27,176' Name='Cancel' ScrollExtent='400,17' Size='400,17' Style='/Buttons.RespawnSelection.style'>@TrainingCancel</Button>
<Image AbsorbsInput='false' BackgroundOpacity='1.000' Name='Background' PackSize='1,1' PackSizeProp='0002/0003,0002/0003' RStyleDefault='/WindowPanes.DialogBackground.style' ScrollExtent='455,233' Size='455,233' Stretch='false'/>
</Page>
</Page>
