<Page crosshairtype='rifle_vanu' defaultcolor='#FFFFFF' enemycolor='#FF0000' friendlycolor='#00FF00' GetsInput='false' Location='262,134' Name='RifleVanuCrosshair' PackLocation='Center,Center' PackLocationProp='-250/0001,-250/0001' ScrollExtent='500,500' Size='500,500' Visible='false' visualeditlock='true'>
<Image Location='235,247' Name='COF_Left' ScrollExtent='8,8' Size='8,8' SourceResource='ui_crosshair_vanu_rifle_tick'/>
<Image Location='259,247' Name='COF_Right' Rotation='0.500' ScrollExtent='8,8' Size='8,8' SourceResource='ui_crosshair_vanu_rifle_tick'/>
<Image Location='247,236' Name='COF_Top' Rotation='0.250' ScrollExtent='8,8' Size='8,8' SourceResource='ui_crosshair_vanu_rifle_tick'/>
<Image Location='247,258' Name='COF_Bottom' Rotation='0.750' ScrollExtent='8,8' Size='8,8' SourceResource='ui_crosshair_vanu_rifle_tick'/>
<Image Location='218,218' Name='Reticle' Opacity='0.500' ScrollExtent='64,64' Size='64,64' SourceResource='ui_crosshair_vanu_rifle'/>
<Text Font='/SmallFont' LocalText='Rifle Crosshair' Location='100,112' Name='ID' Opacity='0.500' ScrollExtent='100,12' Size='100,12' Visible='false'>Rifle Crosshair</Text>
</Page>
