<Page Location='834,424' movable='true' Name='SoldierManagement' PackLocation='right,bottom' PackLocationProp='-190/0001,-344/0001' ScrollExtent='190,290' Size='190,290' Visible='false'>
<VolumePage CellCount='1,10' CellPadding='0,0' CellSelectable='false' CellSize='160,25' Location='15,22' MinimumScrollExtent='160,250' Name='Volume' ScrollExtent='160,250' Size='160,250'>
<Page MaximumSize='160,25' MinimumSize='160,25' Name='Map' ScrollExtent='160,25' Size='160,25'>
<Button LocalText='o' Name='Button' PackSize='fixed,absolute' PackSizeProp='0002/0003,0000/0001' ScrollExtent='40,25' Size='40,25' Style='/Buttons.TitlebarButton.style'>o</Button>
<Text AbsorbsInput='false' Font='/Fonts.HudFont1' GetsInput='false' LocalText='Map' Location='45,0' Name='Name' PackLocation='fixed,absolute' PackSize='absolute,absolute' PackSizeProp='0090/0001,0000/0001' ScrollExtent='70,25' Size='70,25' TextAlignmentVertical='Center'>Map</Text>
<Text AbsorbsInput='false' Font='/Fonts.HudFont1' GetsInput='false' LocalText='M' Location='115,0' Name='Keymap' PackLocation='right,top' PackLocationProp='-045/0001,0000/0001' PackSize='fixed,absolute' PackSizeProp='0002/0003,0000/0001' ScrollExtent='45,25' Size='45,25' TextAlignment='Center' TextAlignmentVertical='Center' TextColor='#FFFFD5'>M</Text>
</Page>
<Page Location='0,25' MaximumSize='160,25' MinimumSize='160,25' Name='Inventory' ScrollExtent='160,25' Size='160,25'>
<Button LocalText='m' Name='Button' PackSize='fixed,absolute' PackSizeProp='0002/0003,0000/0001' ScrollExtent='40,25' Size='40,25' Style='/Buttons.TitlebarButton.style'>m</Button>
<Text AbsorbsInput='false' Font='/Fonts.HudFont1' GetsInput='false' LocalText='Inventory' Location='45,0' Name='Name' PackLocation='fixed,absolute' PackSize='absolute,absolute' PackSizeProp='0090/0001,0000/0001' ScrollExtent='70,25' Size='70,25' TextAlignmentVertical='Center'>Inventory</Text>
<Text AbsorbsInput='false' Font='/Fonts.HudFont1' GetsInput='false' LocalText='I' Location='115,0' Name='Keymap' PackLocation='right,top' PackLocationProp='-045/0001,0000/0001' PackSize='fixed,absolute' PackSizeProp='0002/0003,0000/0001' ScrollExtent='45,25' Size='45,25' TextAlignment='Center' TextAlignmentVertical='Center' TextColor='#FFFFD5'>I</Text>
</Page>
<Page Location='0,50' MaximumSize='160,25' MinimumSize='160,25' Name='Character' ScrollExtent='160,25' Size='160,25'>
<Button LocalText='n' Name='Button' PackSize='fixed,absolute' PackSizeProp='0002/0003,0000/0001' ScrollExtent='40,25' Size='40,25' Style='/Buttons.TitlebarButton.style'>n</Button>
<Text AbsorbsInput='false' Font='/Fonts.HudFont1' GetsInput='false' LocalText='Character' Location='45,0' Name='Name' PackLocation='fixed,absolute' PackSize='absolute,absolute' PackSizeProp='0090/0001,0000/0001' ScrollExtent='70,25' Size='70,25' TextAlignmentVertical='Center'>Character</Text>
<Text AbsorbsInput='false' Font='/Fonts.HudFont1' GetsInput='false' LocalText='O' Location='115,0' Name='Keymap' PackLocation='right,top' PackLocationProp='-045/0001,0000/0001' PackSize='fixed,absolute' PackSizeProp='0002/0003,0000/0001' ScrollExtent='45,25' Size='45,25' TextAlignment='Center' TextAlignmentVertical='Center' TextColor='#FFFFD5'>O</Text>
</Page>
<Page Location='0,75' MaximumSize='160,25' MinimumSize='160,25' Name='Players' ScrollExtent='160,25' Size='160,25'>
<Button LocalText='v' Name='Button' PackSize='fixed,absolute' PackSizeProp='0002/0003,0000/0001' ScrollExtent='40,25' Size='40,25' Style='/Buttons.TitlebarButton.style'>v</Button>
<Text AbsorbsInput='false' Font='/Fonts.HudFont1' GetsInput='false' LocalText='Players' Location='45,0' Name='Name' PackLocation='fixed,absolute' PackSize='absolute,absolute' PackSizeProp='0090/0001,0000/0001' ScrollExtent='70,25' Size='70,25' TextAlignmentVertical='Center'>Players</Text>
<Text AbsorbsInput='false' Font='/Fonts.HudFont1' GetsInput='false' LocalText='P' Location='115,0' Name='Keymap' PackLocation='right,top' PackLocationProp='-045/0001,0000/0001' PackSize='fixed,absolute' PackSizeProp='0002/0003,0000/0001' ScrollExtent='45,25' Size='45,25' TextAlignment='Center' TextAlignmentVertical='Center' TextColor='#FFFFD5'>P</Text>
</Page>
<Page Location='0,100' MaximumSize='160,25' MinimumSize='160,25' Name='Outfit' ScrollExtent='160,25' Size='160,25'>
<Button LocalText='J' Name='Button' PackSize='fixed,absolute' PackSizeProp='0002/0003,0000/0001' ScrollExtent='40,25' Size='40,25' Style='/Buttons.TitlebarButton.style'>J</Button>
<Text AbsorbsInput='false' Font='/Fonts.HudFont1' GetsInput='false' LocalText='Outfit' Location='45,0' Name='Name' PackLocation='fixed,absolute' PackSize='absolute,absolute' PackSizeProp='0090/0001,0000/0001' ScrollExtent='70,25' Size='70,25' TextAlignmentVertical='Center'>Outfit</Text>
<Text AbsorbsInput='false' Font='/Fonts.HudFont1' GetsInput='false' LocalText='ALT-O' Location='115,0' Name='Keymap' PackLocation='right,top' PackLocationProp='-045/0001,0000/0001' PackSize='fixed,absolute' PackSizeProp='0002/0003,0000/0001' ScrollExtent='45,25' Size='45,25' TextAlignment='Center' TextAlignmentVertical='Center' TextColor='#FFFFD5'>ALT-O</Text>
</Page>
<Page Location='0,125' MaximumSize='160,25' MinimumSize='160,25' Name='Vehicle' ScrollExtent='160,25' Size='160,25'>
<Button LocalText='p' Name='Button' PackSize='fixed,absolute' PackSizeProp='0002/0003,0000/0001' ScrollExtent='40,25' Size='40,25' Style='/Buttons.TitlebarButton.style'>p</Button>
<Text AbsorbsInput='false' Font='/Fonts.HudFont1' GetsInput='false' LocalText='Vehicle' Location='45,0' Name='Name' PackLocation='fixed,absolute' PackSize='absolute,absolute' PackSizeProp='0090/0001,0000/0001' ScrollExtent='70,25' Size='70,25' TextAlignmentVertical='Center'>Vehicle</Text>
<Text AbsorbsInput='false' Font='/Fonts.HudFont1' GetsInput='false' LocalText='ALT-V' Location='115,0' Name='Keymap' PackLocation='right,top' PackLocationProp='-045/0001,0000/0001' PackSize='fixed,absolute' PackSizeProp='0002/0003,0000/0001' ScrollExtent='45,25' Size='45,25' TextAlignment='Center' TextAlignmentVertical='Center' TextColor='#FFFFD5'>ALT-V</Text>
</Page>
<Page Location='0,150' MaximumSize='160,25' MinimumSize='160,25' Name='Mail' ScrollExtent='160,25' Size='160,25'>
<Button LocalText='g' Name='Button' PackSize='fixed,absolute' PackSizeProp='0002/0003,0000/0001' ScrollExtent='40,25' Size='40,25' Style='/Buttons.TitlebarButton.style'>g</Button>
<Text AbsorbsInput='false' Font='/Fonts.HudFont1' GetsInput='false' LocalText='Mail' Location='45,0' Name='Name' PackLocation='fixed,absolute' PackSize='absolute,absolute' PackSizeProp='0090/0001,0000/0001' ScrollExtent='70,25' Size='70,25' TextAlignmentVertical='Center'>Mail</Text>
<Text AbsorbsInput='false' Font='/Fonts.HudFont1' GetsInput='false' LocalText='ALT-M' Location='115,0' Name='Keymap' PackLocation='right,top' PackLocationProp='-045/0001,0000/0001' PackSize='fixed,absolute' PackSizeProp='0002/0003,0000/0001' ScrollExtent='45,25' Size='45,25' TextAlignment='Center' TextAlignmentVertical='Center' TextColor='#FFFFD5'>ALT-M</Text>
</Page>
<Page Location='0,175' MaximumSize='160,25' MinimumSize='160,25' Name='CE' ScrollExtent='160,25' Size='160,25'>
<Button LocalText='Y' Name='Button' PackSize='fixed,absolute' PackSizeProp='0002/0003,0000/0001' ScrollExtent='40,25' Size='40,25' Style='/Buttons.TitlebarButton.style'>Y</Button>
<Text AbsorbsInput='false' Font='/Fonts.HudFont1' GetsInput='false' LocalText='Combat Eng.' Location='45,0' Name='Name' PackLocation='fixed,absolute' PackSize='absolute,absolute' PackSizeProp='0090/0001,0000/0001' ScrollExtent='70,25' Size='70,25' TextAlignmentVertical='Center'>Combat Eng.</Text>
<Text AbsorbsInput='false' BackgroundColor='#00FF00' Font='/Fonts.HudFont1' GetsInput='false' LocalText='ALT-E' Location='115,0' Name='Keymap' PackLocation='right,top' PackLocationProp='-045/0001,0000/0001' PackSize='fixed,absolute' PackSizeProp='0002/0003,0000/0001' ScrollExtent='45,25' Size='45,25' TextAlignment='Center' TextAlignmentVertical='Center' TextColor='#FFFFD5'>ALT-E</Text>
</Page>
<Page Location='0,200' MaximumSize='160,25' MinimumSize='160,25' Name='Performance' ScrollExtent='160,25' Size='160,25'>
<Button LocalText='1' Name='Button' PackSize='fixed,absolute' PackSizeProp='0002/0003,0000/0001' ScrollExtent='40,25' Size='40,25' Style='/Buttons.TitlebarButton.style'>1</Button>
<Text AbsorbsInput='false' BackgroundColor='#0000FF' Font='/Fonts.HudFont1' GetsInput='false' LocalText='Performance' Location='45,0' Name='Name' PackLocation='absolute,absolute' PackSize='absolute,absolute' PackSizeProp='0090/0001,0000/0001' ScrollExtent='70,25' Size='70,25' TextAlignmentVertical='Center'>Performance</Text>
<Text AbsorbsInput='false' BackgroundColor='#00FF00' Font='/Fonts.HudFont1' GetsInput='false' LocalText='ALT-P' Location='115,0' Name='Keymap' PackLocation='right,top' PackLocationProp='-045/0001,0000/0001' PackSize='fixed,absolute' PackSizeProp='0002/0003,0000/0001' ScrollExtent='45,25' Size='45,25' TextAlignment='Center' TextAlignmentVertical='Center' TextColor='#FFFFD5'>ALT-P</Text>
</Page>
<Page Location='0,225' MaximumSize='160,25' MinimumSize='160,25' Name='Session' ScrollExtent='160,25' Size='160,25'>
<Button LocalText='x' Name='Button' PackSize='fixed,absolute' PackSizeProp='0002/0003,0000/0001' ScrollExtent='40,25' Size='40,25' Style='/Buttons.TitlebarButton.style'>x</Button>
<Text AbsorbsInput='false' Font='/Fonts.HudFont1' GetsInput='false' LocalText='Session Stats' Location='45,0' Name='Name' PackLocation='fixed,absolute' PackSize='absolute,absolute' PackSizeProp='0090/0001,0000/0001' ScrollExtent='70,25' Size='70,25' TextAlignmentVertical='Center'>Session Stats</Text>
<Text AbsorbsInput='false' Font='/Fonts.HudFont1' GetsInput='false' LocalText='ALT-S' Location='115,0' Name='Keymap' PackLocation='right,top' PackLocationProp='-045/0001,0000/0001' PackSize='fixed,absolute' PackSizeProp='0002/0003,0000/0001' ScrollExtent='45,25' Size='45,25' TextAlignment='Center' TextAlignmentVertical='Center' TextColor='#FFFFD5'>ALT-S</Text>
</Page>
</VolumePage>
<Image AbsorbsInput='false' BackgroundOpacity='1.000' Dragable='true' Enabled='false' Name='_Background' PackLocation='left,top' PackLocationProp='0000/0001,0000/0001' PackSize='1,1' PackSizeProp='0002/0003,0002/0003' RStyleDefault='/WindowPanes.DialogBackground.style' ScrollExtent='190,290' Size='190,290' Stretch='false'/>
</Page>
