<Page crosshairtype='pistol' defaultcolor='#FFFFFF' enemycolor='#FF0000' friendlycolor='#00FF00' GetsInput='false' Location='262,134' Name='PistolCrosshairOld' PackLocation='Center,Center' PackLocationProp='-250/0001,-250/0001' ScrollExtent='500,500' Size='500,500' Visible='false' visualeditlock='true'>
<Text Font='/SmallFont' LocalText='Pistol Crosshair' Location='100,112' Name='ID' Opacity='0.500' ScrollExtent='72,12' Size='72,12'>Pistol Crosshair</Text>
<Ellipse ArcEnd='1.001' Color='#00FF00' InnerRadiusColor='#00FF00' Location='238,238' Name='COF' Rotation='0.500' ScrollExtent='29,29' Size='29,29' Thickness='5.000'/>
<Ellipse ArcEnd='1.001' Color='#00FF00' InnerRadiusColor='#00FF00' Location='238,238' Name='Fade' Opacity='0.010' Rotation='0.500' ScrollExtent='29,29' Size='29,29' Thickness='5.000'/>
<Image Location='205,204' Name='Reticle' Opacity='0.500' ScrollExtent='95,95' Size='95,95' SourceRect='0,0,64,64' SourceResource='ui_circle_alpha_fade'/>
<Ellipse ArcEnd='1.001' Color='#00FF00' InnerRadiusColor='#00FF00' Location='211,210' Name='Outer' Rotation='0.500' ScrollExtent='85,85' Size='85,85' Thickness='2.000'/>
<Ellipse ArcBegin='0.315' ArcEnd='0.435' Color='#00FF00' InnerRadiusColor='#00FF00' Location='236,235' Name='COFa' Rotation='0.500' ScrollExtent='32,32' Size='32,32' Thickness='7.000'/>
<Ellipse ArcBegin='0.565' ArcEnd='0.685' Color='#00FF00' InnerRadiusColor='#00FF00' Location='236,235' Name='COFb' Rotation='0.500' ScrollExtent='32,32' Size='32,32' Thickness='7.000'/>
<Ellipse ArcBegin='0.815' ArcEnd='0.935' Color='#00FF00' InnerRadiusColor='#00FF00' Location='236,235' Name='COFc' Rotation='0.500' ScrollExtent='32,32' Size='32,32' Thickness='7.000'/>
<Ellipse ArcBegin='0.065' ArcEnd='0.195' Color='#00FF00' InnerRadiusColor='#00FF00' Location='236,235' Name='COFd' Rotation='0.500' ScrollExtent='32,32' Size='32,32' Thickness='7.000'/>
</Page>
