<Page AbsorbsInput='false' Location='284,319' Name='ProgressView' Opacity='0.800' PackLocation='cfc,cfc' PackLocationProp='-001/0001,-019/0001' ScrollExtent='455,93' Size='455,93' Visible='false'>
<Text AbsorbsInput='false' Font='/Fonts.HudFont3' LocalText='[@InformationAboutProgress]' Location='32,27' Name='InfoText' ScrollExtent='400,21' Size='400,21' TextAlignment='Center'>@InformationAboutProgress</Text>
<Progressbar AbsorbsInput='false' Color='#777777' colorhack='#FFFFFF' colorheal='#FF0000' colorrepair='#0099C5' colorrevive='#FF0000' colorupgrade='#00FF00' Location='29,54' Name='Progress' Progress='0.330' ScrollExtent='400,13' Size='400,13' Style='/ProgressBars.Health.style' TooltipStyle='/Fonts.DefaultFont'/>
<Image AbsorbsInput='false' BackgroundOpacity='1.000' Name='Background' PackSize='1,1' PackSizeProp='0002/0003,0002/0003' RStyleDefault='/WindowPanes.DialogBackground.style' ScrollExtent='455,93' Size='455,93' Stretch='false'/>
</Page>
