<Page Location='0,718' movable='true' Name='ActiveItems' PackLocation='Left,Bottom' PackLocationProp='0000/0001,-050/0001' PackSize='1,fixed' PackSizeProp='0002/0003,0002/0003' ScrollExtent='1024,50' Size='1024,50'>
<Page Location='265,5' MaximumSize='113,34' MinimumSize='63,34' Name='VehicleShield' Opacity='0.800' ScrollExtent='113,34' Size='113,34' Visible='false'>
<Text AbsorbsInput='false' Enabled='false' Font='/Fonts.HudFont1' LocalText='[@VehicleShield]' Location='6,18' Name='StatusLabel' PackSize='absolute,fixed' PackSizeProp='0013/0001,0002/0003' ScrollExtent='100,15' Size='100,15' TextAlignment='Center'>@VehicleShield</Text>
<Progressbar AbsorbsInput='false' BackgroundColor='#858585' BarBackgroundColor='#0099C5' Location='6,5' Name='Status' Progress='1.000' ScrollExtent='100,13' Size='100,13' Style='/ProgressBars.Health.style'/>
<Image AbsorbsInput='false' BackgroundOpacity='1.000' Name='Border' PackSize='1,1' PackSizeProp='0002/0003,0002/0003' RStyleDefault='/WindowPanes.ActiveItem.style' ScrollExtent='113,34' Size='113,34'/>
</Page>
<Page Location='265,4' MaximumSize='113,34' MinimumSize='63,34' Name='VehicleStatus' Opacity='0.800' ScrollExtent='113,34' Size='113,34' Visible='false'>
<Text AbsorbsInput='false' Enabled='false' Font='/Fonts.HudFont1' LocalText='[@VehicleStatus]' Location='6,18' Name='StatusLabel' PackSize='absolute,fixed' PackSizeProp='0013/0001,0002/0003' ScrollExtent='100,15' Size='100,15' TextAlignment='Center'>@VehicleStatus</Text>
<Progressbar AbsorbsInput='false' BackgroundColor='#858585' BarBackgroundColor='#FF0000' Location='6,5' Name='Status' Progress='1.000' ScrollExtent='100,13' Size='100,13' Style='/ProgressBars.Health.style'/>
<Image AbsorbsInput='false' BackgroundOpacity='1.000' Name='Border' PackSize='1,1' PackSizeProp='0002/0003,0002/0003' RStyleDefault='/WindowPanes.ActiveItem.style' ScrollExtent='113,34' Size='113,34'/>
</Page>
<Page Location='16,6' MaximumSize='171,40' MinimumSize='71,40' Name='Vehicle' ScrollExtent='171,40' Size='171,40' Visible='false'>
<Page MaximumSize='100,60' MinimumSize='50,40' Name='StatusPage' PackSize='absolute,fixed' PackSizeProp='0071/0001,0002/0003' ScrollExtent='100,40' Size='100,40'>
<Text AbsorbsInput='false' Enabled='false' Font='/Fonts.HudFont1' LocalText='[@VehicleCapacitorStatus]' Location='0,22' Name='VehicleCapacitorLabel' PackSize='absolute,fixed' PackSizeProp='0000/0001,0002/0003' ScrollExtent='100,24' Size='100,12' TextAlignment='Center' Visible='false'>@VehicleCapacitorStatus</Text>
<Progressbar AbsorbsInput='false' BackgroundColor='#858585' BarBackgroundColor='#00F2C9' Location='0,22' Name='VehicleCapacitorBar' PackSize='absolute,fixed' PackSizeProp='0000/0001,0002/0003' Progress='1.000' ScrollExtent='100,12' Size='100,12' Style='/ProgressBars.Health.style'/>
<Text AbsorbsInput='false' Enabled='false' Font='/Fonts.HudFont1' LocalText='[@VehicleStatus]' Location='0,6' Name='StatusLabel' PackSize='absolute,fixed' PackSizeProp='0000/0001,0002/0003' ScrollExtent='100,12' Size='100,12' TextAlignment='Center'>@VehicleStatus</Text>
<Text AbsorbsInput='false' Enabled='false' Font='/Fonts.HudFont1' LocalText='[@ResourceStatus]' Location='0,22' Name='ResourceLabel' PackSize='absolute,fixed' PackSizeProp='0000/0001,0002/0003' ScrollExtent='100,12' Size='100,12' TextAlignment='Center'>@ResourceStatus</Text>
<Text AbsorbsInput='false' Enabled='false' Font='/Fonts.HudFont1' LocalText='[@AfterburnerStatus]' Location='0,22' Name='AfterburnerLabel' PackSize='absolute,fixed' PackSizeProp='0000/0001,0002/0003' ScrollExtent='100,24' Size='100,12' TextAlignment='Center'>@AfterburnerStatus</Text>
<Text AbsorbsInput='false' Enabled='false' Font='/Fonts.HudFont1' LocalText='[@FrameFlightCapacitorStatus]' Location='0,22' Name='FrameFlightCapacitorLabel' PackSize='absolute,fixed' PackSizeProp='0000/0001,0002/0003' ScrollExtent='100,24' Size='100,12' TextAlignment='Center' Visible='false'>@FrameFlightCapacitorStatus</Text>
<Progressbar AbsorbsInput='false' BackgroundColor='#858585' BarBackgroundColor='#FF0000' Location='0,6' Name='Status' PackSize='absolute,fixed' PackSizeProp='0000/0001,0002/0003' Progress='1.000' ScrollExtent='100,12' Size='100,12' Style='/ProgressBars.Health.style'/>
<Progressbar AbsorbsInput='false' BackgroundColor='#858585' Location='0,22' Name='Resource' PackSize='absolute,fixed' PackSizeProp='0000/0001,0002/0003' Progress='0.500' ScrollExtent='100,12' Size='100,12' Style='/ProgressBars.Health.style'/>
<Progressbar AbsorbsInput='false' BackgroundColor='#858585' BarBackgroundColor='#00F2C9' Location='0,22' Name='AfterburnerBar' PackSize='absolute,fixed' PackSizeProp='0000/0001,0002/0003' Progress='1.000' ScrollExtent='100,12' Size='100,12' Style='/ProgressBars.Health.style'/>
<Progressbar AbsorbsInput='false' BackgroundColor='#858585' BarBackgroundColor='#00F2C9' Location='0,22' Name='FrameFlightCapacitorBar' PackSize='absolute,fixed' PackSizeProp='0000/0001,0002/0003' Progress='1.000' ScrollExtent='100,12' Size='100,12' Style='/ProgressBars.Health.style'/>
</Page>
<Page LocalTooltip='Bob' Location='103,0' movable='true' Name='Speedometer' PackLocation='right,top' PackLocationProp='-068/0001,0000/0001' ScrollExtent='67,40' Size='67,40' Tooltip='Bob'>
<Text AbsorbsInput='false' Color='#F2F2F2' Font='/Fonts.HudFont3' LocalText='90%' Location='0,21' Name='Speed' ScrollExtent='65,20' Size='65,20' TextAlignment='Center'>90%</Text>
<Image AbsorbsInput='false' Color='#00F2C9' Name='CruiseMarker' ScrollExtent='65,16' Size='65,16' Stretch='false' Style='CruiseMarkerStyle'/>
<Image AbsorbsInput='false' Color='#00F2C9' Name='ForwardIndicator' ScrollExtent='65,16' Size='65,16' Stretch='false' Style='ForwardStyle'/>
<Image AbsorbsInput='false' Color='#DE4E4E' Name='ReverseIndicator' ScrollExtent='65,16' Size='65,16' Stretch='false' Style='ReverseStyle'/>
<ImageStyle Name='CruiseMarkerStyle'>
<ImageFrame SourceRect='0,16,65,32'>
<ImageFragment Source='ui_hud_activeitem_speedometer_00' SourceRect='0,0,64,64'/>
<ImageFragment Offset='64,0' Source='ui_hud_activeitem_speedometer_01' SourceRect='0,0,32,32'/>
<ImageFragment Offset='64,32' Source='ui_hud_activeitem_speedometer_02' SourceRect='0,0,32,32'/>
</ImageFrame>
</ImageStyle>
<ImageStyle Name='ForwardStyle'>
<ImageFrame SourceRect='0,0,65,16'>
<ImageFragment Source='ui_hud_activeitem_speedometer_00' SourceRect='0,0,64,64'/>
<ImageFragment Offset='64,0' Source='ui_hud_activeitem_speedometer_01' SourceRect='0,0,32,32'/>
<ImageFragment Offset='64,32' Source='ui_hud_activeitem_speedometer_02' SourceRect='0,0,32,32'/>
</ImageFrame>
</ImageStyle>
<ImageStyle Name='ReverseStyle'>
<ImageFrame SourceRect='0,32,65,48'>
<ImageFragment Source='ui_hud_activeitem_speedometer_00' SourceRect='0,0,64,64'/>
<ImageFragment Offset='64,0' Source='ui_hud_activeitem_speedometer_01' SourceRect='0,0,32,32'/>
<ImageFragment Offset='64,32' Source='ui_hud_activeitem_speedometer_02' SourceRect='0,0,32,32'/>
</ImageFrame>
</ImageStyle>
</Page>
</Page>
<Page Location='265,4' Name='HeavyPage' Opacity='0.800' ScrollExtent='113,34' Size='113,34' Visible='false'>
<Text AbsorbsInput='false' Enabled='false' Font='/Fonts.HudFont1' LocalText='[@MaxCapacitor]' Location='6,18' Name='StatusLabel' PackSize='absolute,fixed' PackSizeProp='0013/0001,0002/0003' ScrollExtent='100,15' Size='100,15' TextAlignment='Center'>@MaxCapacitor</Text>
<Progressbar AbsorbsInput='false' BackgroundColor='#858585' BarBackgroundColor='#00F2C9' Location='6,5' Name='Armor' Progress='1.000' ScrollExtent='100,13' Size='100,13' Style='/ProgressBars.Health.style'/>
<Image AbsorbsInput='false' BackgroundOpacity='1.000' Name='Border' PackSize='1,1' PackSizeProp='0002/0003,0002/0003' RStyleDefault='/WindowPanes.ActiveItem.style' ScrollExtent='113,34' Size='113,34'/>
</Page>
<Page Location='43,6' MaximumSize='109,40' MinimumSize='59,40' movable='false' Name='SoldierStatus' PackLocation='right,top' PackLocationProp='-981/0001,0006/0001' ScrollExtent='109,40' Size='109,40'>
<Text AbsorbsInput='false' Enabled='false' Font='/Fonts.HudFont1' LocalText='100/100' Location='14,0' Name='HealthText' PackLocation='center,center' PackLocationProp='-040/0001,-020/0001' ScrollExtent='95,12' Size='95,12' TextAlignment='Center'>100/100</Text>
<Text AbsorbsInput='false' Enabled='false' Font='/Fonts.HudFont1' LocalText='100/100' Location='14,14' Name='StaminaText' PackLocation='center,center' PackLocationProp='-040/0001,-006/0001' ScrollExtent='95,12' Size='95,12' TextAlignment='Center'>100/100</Text>
<Text AbsorbsInput='false' Enabled='false' Font='/Fonts.HudFont1' LocalText='100/100' Location='14,28' Name='ArmorText' PackLocation='center,center' PackLocationProp='-040/0001,0008/0001' ScrollExtent='95,12' Size='95,12' TextAlignment='Center'>100/100</Text>
<Image AbsorbsInput='false' Color='#FF0000' Name='HealthIcon' ScrollExtent='12,12' Size='12,12' Stretch='false' Style='/Icons.HUD.Health'/>
<Image AbsorbsInput='false' Color='#00F2C9' Location='0,14' Name='StaminaIcon' ScrollExtent='12,12' Size='12,12' Stretch='false' Style='/Icons.HUD.Stamina'/>
<Image AbsorbsInput='false' Color='#0099C5' Location='0,28' Name='ArmorIcon' ScrollExtent='12,12' Size='12,12' Stretch='false' Style='/Icons.HUD.Armor'/>
<Progressbar BackgroundColor='#858585' BarBackgroundColor='#FF0000' Location='14,0' Name='Health' PackSize='absolute,fixed' PackSizeProp='0014/0001,0002/0003' Progress='1.000' ScrollExtent='95,12' Size='95,12' Style='/ProgressBars.Health.style'/>
<Progressbar BackgroundColor='#858585' BarBackgroundColor='#00F2C9' Location='14,14' Name='Stamina' PackSize='absolute,fixed' PackSizeProp='0014/0001,0002/0003' Progress='0.400' ScrollExtent='95,12' Size='95,12' Style='/ProgressBars.Health.style'/>
<Progressbar BackgroundColor='#858585' BarBackgroundColor='#0099C5' Location='14,28' Name='Armor' PackSize='absolute,fixed' PackSizeProp='0014/0001,0002/0003' Progress='0.600' ScrollExtent='95,12' Size='95,12' Style='/ProgressBars.Health.style'/>
</Page>
<Page Location='235,5' movable='true' Name='StealthPage' ScrollExtent='20,40' Size='20,40' Visible='false'>
<Image Name='Image' ScrollExtent='20,40' Size='20,40' Style='ImageStyle'/>
<ImageStyle Name='ImageStyle'>
<ImageFrame Source='ui_stealth_indicator_00' SourceRect='15,0,35,40'/>
</ImageStyle>
<Progressbar BarBackgroundColor='#C0C0C0' Location='3,3' Name='Progress' ScrollExtent='14,37' Size='14,37' Style='/ProgressBars.Stealth.style'/>
</Page>
<Page Location='155,4' movable='false' Name='ShortcutPage' PackLocation='right,top' PackLocationProp='-869/0001,0004/0001' ScrollExtent='280,47' Size='280,47'>
<Button BackgroundColor='#FFFFFF' Location='4,0' Name='IncreaseBank' RStyleDefault=' ' ScrollExtent='12,12' Size='12,12' Style='/Buttons.ActiveItems.style_small'></Button>
<Button BackgroundColor='#FFFFFF' Location='4,21' Name='DecreaseBank' Rotation='0.500' RStyleDefault=' ' ScrollExtent='12,12' Size='12,12' Style='/Buttons.ActiveItems.style_small'></Button>
<Text AbsorbsInput='false' Enabled='false' Font='/Fonts.HudFont1' GetsInput='false' LocalText='1' Location='0,7' Name='BankNumber' ScrollExtent='20,18' Size='20,18' TextAlignment='Center' TextAlignmentVertical='Center'>1</Text>
<Text AbsorbsInput='false' Enabled='false' Font='/Fonts.HudFont1' GetsInput='false' LocalText='[@F1]' Location='23,29' Name='F1' ScrollExtent='32,18' Size='32,18' TextAlignment='Center' TextAlignmentVertical='Center'>@F1</Text>
<Text AbsorbsInput='false' Enabled='false' Font='/Fonts.HudFont1' GetsInput='false' LocalText='[@F2]' Location='55,29' Name='F2' ScrollExtent='32,18' Size='32,18' TextAlignment='Center' TextAlignmentVertical='Center'>@F2</Text>
<Text AbsorbsInput='false' Enabled='false' Font='/Fonts.HudFont1' GetsInput='false' LocalText='[@F3]' Location='87,29' Name='F3' ScrollExtent='32,18' Size='32,18' TextAlignment='Center' TextAlignmentVertical='Center'>@F3</Text>
<Text AbsorbsInput='false' Enabled='false' Font='/Fonts.HudFont1' GetsInput='false' LocalText='[@F4]' Location='119,29' Name='F4' ScrollExtent='32,18' Size='32,18' TextAlignment='Center' TextAlignmentVertical='Center'>@F4</Text>
<Text AbsorbsInput='false' Enabled='false' Font='/Fonts.HudFont1' GetsInput='false' LocalText='[@F5]' Location='151,29' Name='F5' ScrollExtent='32,18' Size='32,18' TextAlignment='Center' TextAlignmentVertical='Center'>@F5</Text>
<Text AbsorbsInput='false' Enabled='false' Font='/Fonts.HudFont1' GetsInput='false' LocalText='[@F6]' Location='183,29' Name='F6' ScrollExtent='32,18' Size='32,18' TextAlignment='Center' TextAlignmentVertical='Center'>@F6</Text>
<Text AbsorbsInput='false' Enabled='false' Font='/Fonts.HudFont1' GetsInput='false' LocalText='[@F7]' Location='215,29' Name='F7' ScrollExtent='32,18' Size='32,18' TextAlignment='Center' TextAlignmentVertical='Center'>@F7</Text>
<Text AbsorbsInput='false' Enabled='false' Font='/Fonts.HudFont1' GetsInput='false' LocalText='[@F8]' Location='247,29' Name='F8' ScrollExtent='32,18' Size='32,18' TextAlignment='Center' TextAlignmentVertical='Center'>@F8</Text>
<Page BackgroundColor='#00F2C9' BackgroundOpacity='0.600' Location='20,0' Name='Highlight' ScrollExtent='32,32' Size='32,32' Visible='false'/>
<Grid CellCount='8,1' CellSize='32,32' DataSource='/DataSources.Shortcuts' DragAccepts='Item,Shortcut' Location='20,0' Name='Shortcuts' ScrollExtent='256,32' Size='258,34' Style='/Grids.ClearGrid.style'/>
<Page Location='20,0' Name='ShortcutBackground' Opacity='0.500' ScrollExtent='256,32' Size='256,32'>
<Rectangle Color='#00F2C9' ScrollExtent='256,32' Size='256,32'/>
<Rectangle Color='#00F2C9' Location='32,1' ScrollExtent='1,29' Size='1,29'/>
<Rectangle Color='#00F2C9' Location='64,1' ScrollExtent='1,29' Size='1,29'/>
<Rectangle Color='#00F2C9' Location='96,1' ScrollExtent='1,29' Size='1,29'/>
<Rectangle Color='#00F2C9' Location='128,1' ScrollExtent='1,29' Size='1,29'/>
<Rectangle Color='#00F2C9' Location='160,1' ScrollExtent='1,29' Size='1,29'/>
<Rectangle Color='#00F2C9' Location='192,1' ScrollExtent='1,29' Size='1,29'/>
<Rectangle Color='#00F2C9' Location='224,1' ScrollExtent='1,29' Size='1,29'/>
</Page>
</Page>
<Page Location='460,5' MaximumSize='500,40' MinimumSize='4,40' Name='InventoryPage' ScrollExtent='449,40' Size='449,40'>
<Page Location='194,0' Name='SlotBFR1' ScrollExtent='98,40' Size='98,40'>
<Image AbsorbsInput='false' Color='#FF0000' Location='30,2' Name='Destroyed' ScrollExtent='64,19' Size='64,19' Style='/Buttons.WindowClose.normal'/>
<Image Activated='true' GetsInput='true' LocalTooltip='Bobble was here' Location='45,25' Name='AmmoIcon' ScrollExtent='16,16' Size='16,16' Style='/ItemIcons1GridHigh.9mmbullet_AP' Tooltip='Bobble was here'/>
<Image AbsorbsInput='false' Color='#FFDC00' Location='12,0' Name='Highlight' ScrollExtent='86,24' Size='86,24' Stretch='false' Style='/ProgressBars.Ammo.Background' Visible='false'/>
<Page Location='30,3' Name='WeaponIconPage' ScrollExtent='64,17' Size='64,17'>
<Image AbsorbsInput='false' Name='WeaponIcon' ScrollExtent='67,17' Size='67,17' Style='/ItemIcons1GridHigh.colossus_chaingun'/>
</Page>
<Text AbsorbsInput='false' Font='/Fonts.HudFont1' GetsInput='false' LocalText='1' Location='11,-3' Name='HolsterText' ScrollExtent='17,13' Size='17,13' TextAlignment='Center' TextAlignmentVertical='Center'>1</Text>
<Progressbar BackgroundColor='#C0C0C0' BarBackgroundColor='#C0C0C0' Location='12,0' Name='AmmoProgress' Opacity='0.750' Progress='0.500' ScrollExtent='86,24' Size='86,24' Style='/ProgressBars.Ammo.style'/>
<Text AbsorbsInput='false' Font='/Fonts.HudFont2' GetsInput='false' LocalText='500' Location='62,25' Name='ReserveAmmo' ScrollExtent='33,16' Size='33,16' TextAlignment='Center' TextAlignmentVertical='Center'>500</Text>
<Button BackgroundOpacity='0.000' Color='#000000' Enabled='false' LocalText='Bob' LocalTooltip='[@ActiveWeaponAmmoCountTooltip]' Location='15,25' Name='AmmoCount' ScrollExtent='27,16' Size='27,16' Style='/Buttons.ActiveItems.TextButton' TextColor='#000000' Tooltip='@ActiveWeaponAmmoCountTooltip'>Bob</Button>
<Button Color='#FF0000' Location='3,1' Name='Mode1' ScrollExtent='8,8' Size='8,8' stretch='false' Style='Occupant'></Button>
<Button Color='#F3E138' Location='3,11' Name='Mode2' ScrollExtent='8,8' Size='8,8' stretch='false' Style='Occupant'></Button>
<Button Color='#F3E138' Location='3,21' Name='Mode3' ScrollExtent='8,8' Size='8,8' stretch='false' Style='Occupant'></Button>
<Button Color='#F3E138' Location='3,31' Name='Mode4' ScrollExtent='8,8' Size='8,8' stretch='false' Style='Occupant'></Button>
</Page>
<Page Location='292,0' Name='SlotBFR2' ScrollExtent='98,40' Size='98,40'>
<Image AbsorbsInput='false' Color='#FF0000' Location='30,2' Name='Destroyed' ScrollExtent='64,19' Size='64,19' Style='/Buttons.WindowClose.normal' Visible='false'/>
<Image Activated='true' GetsInput='true' LocalTooltip='Bobble was here' Location='45,25' Name='AmmoIcon' ScrollExtent='16,16' Size='16,16' Style='/ItemIcons1GridHigh.9mmbullet_AP' Tooltip='Bobble was here'/>
<Image AbsorbsInput='false' Color='#FFDC00' Location='12,0' Name='Highlight' ScrollExtent='86,24' Size='86,24' Stretch='false' Style='/ProgressBars.Ammo.Background' Visible='false'/>
<Page Location='30,3' Name='WeaponIconPage' ScrollExtent='64,17' Size='64,17'>
<Image AbsorbsInput='false' Name='WeaponIcon' ScrollExtent='67,17' Size='67,17' Style='/ItemIcons1GridHigh.colossus_chaingun'/>
</Page>
<Text AbsorbsInput='false' Font='/Fonts.HudFont1' GetsInput='false' LocalText='1' Location='11,-3' Name='HolsterText' ScrollExtent='17,13' Size='17,13' TextAlignment='Center' TextAlignmentVertical='Center'>1</Text>
<Progressbar BackgroundColor='#00F2C9' BarBackgroundColor='#00F2C9' Location='12,0' Name='AmmoProgress' Opacity='0.750' Progress='0.500' ScrollExtent='86,24' Size='86,24' Style='/ProgressBars.Ammo.style'/>
<Text AbsorbsInput='false' Font='/Fonts.HudFont2' GetsInput='false' LocalText='500' Location='62,25' Name='ReserveAmmo' ScrollExtent='33,16' Size='33,16' TextAlignment='Center' TextAlignmentVertical='Center'>500</Text>
<Button BackgroundOpacity='0.000' Color='#000000' Enabled='false' LocalText='Bob' LocalTooltip='[@ActiveWeaponAmmoCountTooltip]' Location='15,25' Name='AmmoCount' ScrollExtent='27,16' Size='27,16' Style='/Buttons.ActiveItems.TextButton' TextColor='#000000' Tooltip='@ActiveWeaponAmmoCountTooltip'>Bob</Button>
<Button Color='#FF0000' Location='3,1' Name='Mode1' ScrollExtent='8,8' Size='8,8' stretch='false' Style='Occupant'></Button>
<Button Color='#F3E138' Location='3,11' Name='Mode2' ScrollExtent='8,8' Size='8,8' stretch='false' Style='Occupant'></Button>
<Button Color='#F3E138' Location='3,21' Name='Mode3' ScrollExtent='8,8' Size='8,8' stretch='false' Style='Occupant'></Button>
<Button Color='#F3E138' Location='3,31' Name='Mode4' ScrollExtent='8,8' Size='8,8' stretch='false' Style='Occupant'></Button>
</Page>
<Page Location='292,0' Name='SlotVehicle' ScrollExtent='98,40' Size='98,40' Visible='false'>
<Image AbsorbsInput='false' Color='#FF0000' Location='30,2' Name='Destroyed' ScrollExtent='64,19' Size='64,19' Style='/Buttons.WindowClose.normal' Visible='false'/>
<Image Activated='true' GetsInput='true' LocalTooltip='Bobble was here' Location='45,25' Name='AmmoIcon' ScrollExtent='16,16' Size='16,16' Style='/ItemIcons1GridHigh.9mmbullet_AP' Tooltip='Bobble was here'/>
<Image AbsorbsInput='false' Color='#FFDC00' Location='12,0' Name='Highlight' ScrollExtent='86,24' Size='86,24' Stretch='false' Style='/ProgressBars.Ammo.Background' Visible='false'/>
<Page Location='30,3' Name='WeaponIconPage' ScrollExtent='64,17' Size='64,17'>
<Image AbsorbsInput='false' Name='WeaponIcon' ScrollExtent='67,17' Size='67,17' Style='/ItemIcons1GridHigh.cycler'/>
</Page>
<Text AbsorbsInput='false' Font='/Fonts.HudFont1' GetsInput='false' LocalText='1' Location='11,-3' Name='HolsterText' ScrollExtent='17,13' Size='17,13' TextAlignment='Center' TextAlignmentVertical='Center' Visible='false'>1</Text>
<Progressbar BackgroundColor='#00F2C9' BarBackgroundColor='#00F2C9' Location='12,0' Name='AmmoProgress' Opacity='0.750' Progress='0.900' ScrollExtent='86,24' Size='86,24' Style='/ProgressBars.Ammo.style'/>
<Text AbsorbsInput='false' Font='/Fonts.HudFont2' GetsInput='false' LocalText='500' Location='62,25' Name='ReserveAmmo' ScrollExtent='33,16' Size='33,16' TextAlignment='Center' TextAlignmentVertical='Center'>500</Text>
<Button BackgroundOpacity='0.000' Color='#000000' Enabled='false' LocalText='Bob' LocalTooltip='[@ActiveWeaponAmmoCountTooltip]' Location='15,25' Name='AmmoCount' ScrollExtent='27,16' Size='27,16' Style='/Buttons.ActiveItems.TextButton' TextColor='#000000' Tooltip='@ActiveWeaponAmmoCountTooltip'>Bob</Button>
<Button Color='#FF0000' Location='3,1' Name='Mode1' ScrollExtent='8,8' Size='8,8' stretch='false' Style='Occupant'></Button>
<Button Color='#F3E138' Location='3,11' Name='Mode2' ScrollExtent='8,8' Size='8,8' stretch='false' Style='Occupant'></Button>
<Button Color='#F3E138' Location='3,21' Name='Mode3' ScrollExtent='8,8' Size='8,8' stretch='false' Style='Occupant'></Button>
<Button Color='#F3E138' Location='3,31' Name='Mode4' ScrollExtent='8,8' Size='8,8' stretch='false' Style='Occupant'></Button>
</Page>
<Page Location='-2,0' Name='Slot1' ScrollExtent='98,40' Size='98,40'>
<Image AbsorbsInput='false' Color='#FFDC00' Location='12,0' Name='Highlight' ScrollExtent='86,24' Size='86,24' Stretch='false' Style='/ProgressBars.Ammo.Background' Visible='false'/>
<Page Location='30,3' Name='WeaponIconPage' ScrollExtent='64,17' Size='64,17'>
<Image AbsorbsInput='false' Name='WeaponIcon' ScrollExtent='67,17' Size='67,17' Style='/ItemIcons1GridHigh.cycler'/>
</Page>
<Text AbsorbsInput='false' Font='/Fonts.HudFont1' GetsInput='false' LocalText='W' Location='11,-3' Name='HolsterText' ScrollExtent='17,13' Size='17,13' TextAlignment='Center' TextAlignmentVertical='Center'>W</Text>
<Progressbar BackgroundColor='#00F2C9' BarBackgroundColor='#00F2C9' Location='12,0' Name='AmmoProgress' Opacity='0.750' Progress='0.900' ScrollExtent='86,24' Size='86,24' Style='/ProgressBars.Ammo.style'/>
<Image Activated='true' GetsInput='true' LocalTooltip='Bobble was here' Location='45,25' Name='AmmoIcon' ScrollExtent='16,16' Size='16,16' Style='/ItemIcons1GridHigh.9mmbullet_AP' Tooltip='Bobble was here'/>
<Text AbsorbsInput='false' Font='/Fonts.HudFont2' GetsInput='false' LocalText='500' Location='62,25' Name='ReserveAmmo' ScrollExtent='33,16' Size='33,16' TextAlignment='Center' TextAlignmentVertical='Center'>500</Text>
<Button BackgroundOpacity='0.000' Color='#000000' Enabled='false' LocalText='Bob' LocalTooltip='[@ActiveWeaponAmmoCountTooltip]' Location='15,25' Name='AmmoCount' ScrollExtent='27,16' Size='27,16' Style='/Buttons.ActiveItems.TextButton' TextColor='#000000' Tooltip='@ActiveWeaponAmmoCountTooltip'>Bob</Button>
<Button Color='#FF0000' LocalTooltip='Bob was not here' Location='3,1' Name='Mode1' ScrollExtent='8,8' Size='8,8' stretch='false' Style='Occupant' Tooltip='Bob was not here'></Button>
<Button Color='#F3E138' Location='3,11' Name='Mode2' ScrollExtent='8,8' Size='8,8' stretch='false' Style='Occupant'></Button>
<Button Color='#F3E138' Location='3,21' Name='Mode3' ScrollExtent='8,8' Size='8,8' stretch='false' Style='Occupant'></Button>
<Button Color='#F3E138' Location='3,31' Name='Mode4' ScrollExtent='8,8' Size='8,8' stretch='false' Style='Occupant'></Button>
</Page>
<Page Location='96,0' Name='Slot2' ScrollExtent='98,40' Size='98,40'>
<Image Activated='true' GetsInput='true' LocalTooltip='Bobble was here' Location='45,25' Name='AmmoIcon' ScrollExtent='16,16' Size='16,16' Style='/ItemIcons1GridHigh.9mmbullet_AP' Tooltip='Bobble was here'/>
<Image AbsorbsInput='false' Color='#FFDC00' Location='12,0' Name='Highlight' ScrollExtent='86,24' Size='86,24' Stretch='false' Style='/ProgressBars.Ammo.Background' Visible='false'/>
<Page Location='30,3' Name='WeaponIconPage' ScrollExtent='64,17' Size='64,17'>
<Image AbsorbsInput='false' Name='WeaponIcon' ScrollExtent='67,17' Size='67,17' Style='/ItemIcons1GridHigh.cycler'/>
</Page>
<Text AbsorbsInput='false' Font='/Fonts.HudFont1' GetsInput='false' LocalText='1' Location='11,-3' Name='HolsterText' ScrollExtent='17,13' Size='17,13' TextAlignment='Center' TextAlignmentVertical='Center'>1</Text>
<Progressbar BackgroundColor='#00F2C9' BarBackgroundColor='#00F2C9' Location='12,0' Name='AmmoProgress' Opacity='0.750' Progress='0.900' ScrollExtent='86,24' Size='86,24' Style='/ProgressBars.Ammo.style'/>
<Text AbsorbsInput='false' Font='/Fonts.HudFont2' GetsInput='false' LocalText='500' Location='62,25' Name='ReserveAmmo' ScrollExtent='33,16' Size='33,16' TextAlignment='Center' TextAlignmentVertical='Center'>500</Text>
<Button BackgroundOpacity='0.000' Color='#000000' Enabled='false' LocalText='Bob' LocalTooltip='[@ActiveWeaponAmmoCountTooltip]' Location='15,25' Name='AmmoCount' ScrollExtent='27,16' Size='27,16' Style='/Buttons.ActiveItems.TextButton' TextColor='#000000' Tooltip='@ActiveWeaponAmmoCountTooltip'>Bob</Button>
<Button Color='#FF0000' Location='3,1' Name='Mode1' ScrollExtent='8,8' Size='8,8' stretch='false' Style='Occupant'></Button>
<Button Color='#F3E138' Location='3,11' Name='Mode2' ScrollExtent='8,8' Size='8,8' stretch='false' Style='Occupant'></Button>
<Button Color='#F3E138' Location='3,21' Name='Mode3' ScrollExtent='8,8' Size='8,8' stretch='false' Style='Occupant'></Button>
<Button Color='#F3E138' Location='3,31' Name='Mode4' ScrollExtent='8,8' Size='8,8' stretch='false' Style='Occupant'></Button>
</Page>
<Page Location='194,0' Name='Slot3' ScrollExtent='98,40' Size='98,40' Visible='false'>
<Image Activated='true' GetsInput='true' LocalTooltip='Bobble was here' Location='45,25' Name='AmmoIcon' ScrollExtent='16,16' Size='16,16' Style='/ItemIcons1GridHigh.9mmbullet_AP' Tooltip='Bobble was here'/>
<Image AbsorbsInput='false' Color='#FFDC00' Location='12,0' Name='Highlight' ScrollExtent='86,24' Size='86,24' Stretch='false' Style='/ProgressBars.Ammo.Background' Visible='false'/>
<Page Location='30,3' Name='WeaponIconPage' ScrollExtent='64,17' Size='64,17'>
<Image AbsorbsInput='false' Name='WeaponIcon' ScrollExtent='67,17' Size='67,17' Style='/ItemIcons1GridHigh.cycler'/>
</Page>
<Text AbsorbsInput='false' Font='/Fonts.HudFont1' GetsInput='false' LocalText='1' Location='11,-3' Name='HolsterText' ScrollExtent='17,13' Size='17,13' TextAlignment='Center' TextAlignmentVertical='Center'>1</Text>
<Progressbar BackgroundColor='#00F2C9' BarBackgroundColor='#00F2C9' Location='12,0' Name='AmmoProgress' Opacity='0.750' Progress='0.900' ScrollExtent='86,24' Size='86,24' Style='/ProgressBars.Ammo.style'/>
<Text AbsorbsInput='false' Font='/Fonts.HudFont2' GetsInput='false' LocalText='500' Location='62,25' Name='ReserveAmmo' ScrollExtent='33,16' Size='33,16' TextAlignment='Center' TextAlignmentVertical='Center'>500</Text>
<Button BackgroundOpacity='0.000' Color='#000000' Enabled='false' LocalText='Bob' LocalTooltip='[@ActiveWeaponAmmoCountTooltip]' Location='15,25' Name='AmmoCount' ScrollExtent='27,16' Size='27,16' Style='/Buttons.ActiveItems.TextButton' TextColor='#000000' Tooltip='@ActiveWeaponAmmoCountTooltip'>Bob</Button>
<Button Color='#FF0000' Location='3,1' Name='Mode1' ScrollExtent='8,8' Size='8,8' stretch='false' Style='Occupant'></Button>
<Button Color='#F3E138' Location='3,11' Name='Mode2' ScrollExtent='8,8' Size='8,8' stretch='false' Style='Occupant'></Button>
<Button Color='#F3E138' Location='3,21' Name='Mode3' ScrollExtent='8,8' Size='8,8' stretch='false' Style='Occupant'></Button>
<Button Color='#F3E138' Location='3,31' Name='Mode4' ScrollExtent='8,8' Size='8,8' stretch='false' Style='Occupant'></Button>
</Page>
<Page Location='292,0' Name='Slot4' ScrollExtent='98,40' Size='98,40' Visible='false'>
<Image Activated='true' GetsInput='true' LocalTooltip='Bobble was here' Location='45,25' Name='AmmoIcon' ScrollExtent='16,16' Size='16,16' Style='/ItemIcons1GridHigh.9mmbullet_AP' Tooltip='Bobble was here'/>
<Image AbsorbsInput='false' Color='#FFDC00' Location='12,0' Name='Highlight' ScrollExtent='86,24' Size='86,24' Stretch='false' Style='/ProgressBars.Ammo.Background' Visible='false'/>
<Page Location='30,3' Name='WeaponIconPage' ScrollExtent='64,17' Size='64,17'>
<Image AbsorbsInput='false' Name='WeaponIcon' ScrollExtent='67,17' Size='67,17' Style='/ItemIcons1GridHigh.cycler'/>
</Page>
<Text AbsorbsInput='false' Font='/Fonts.HudFont1' GetsInput='false' LocalText='1' Location='11,-3' Name='HolsterText' ScrollExtent='17,13' Size='17,13' TextAlignment='Center' TextAlignmentVertical='Center'>1</Text>
<Progressbar BackgroundColor='#00F2C9' BarBackgroundColor='#00F2C9' Location='12,0' Name='AmmoProgress' Opacity='0.750' Progress='0.900' ScrollExtent='86,24' Size='86,24' Style='/ProgressBars.Ammo.style'/>
<Text AbsorbsInput='false' Font='/Fonts.HudFont2' GetsInput='false' LocalText='500' Location='62,25' Name='ReserveAmmo' ScrollExtent='33,16' Size='33,16' TextAlignment='Center' TextAlignmentVertical='Center'>500</Text>
<Button BackgroundOpacity='0.000' Color='#000000' Enabled='false' LocalText='Bob' LocalTooltip='[@ActiveWeaponAmmoCountTooltip]' Location='15,25' Name='AmmoCount' ScrollExtent='27,16' Size='27,16' Style='/Buttons.ActiveItems.TextButton' TextColor='#000000' Tooltip='@ActiveWeaponAmmoCountTooltip'>Bob</Button>
<Button Color='#FF0000' Location='3,1' Name='Mode1' ScrollExtent='8,8' Size='8,8' stretch='false' Style='Occupant'></Button>
<Button Color='#F3E138' Location='3,11' Name='Mode2' ScrollExtent='8,8' Size='8,8' stretch='false' Style='Occupant'></Button>
<Button Color='#F3E138' Location='3,21' Name='Mode3' ScrollExtent='8,8' Size='8,8' stretch='false' Style='Occupant'></Button>
<Button Color='#F3E138' Location='3,31' Name='Mode4' ScrollExtent='8,8' Size='8,8' stretch='false' Style='Occupant'></Button>
</Page>
<Page Location='390,0' Name='SlotKnife' ScrollExtent='58,40' Size='58,40'>
<Page AbsorbsInput='false' GetsInput='false' Name='Highlight' ScrollExtent='58,23' Size='58,23' Visible='false'>
<Image AbsorbsInput='false' BackgroundColor='#00F2C9' Color='#FFDC00' Location='12,0' Name='Left' ScrollExtent='23,24' Size='23,24' Stretch='false' Style='FrameLeft'/>
<Image AbsorbsInput='false' BackgroundColor='#00F2C9' Color='#FFDC00' Location='35,0' Name='Right' ScrollExtent='23,24' Size='23,24' Stretch='false' Style='FrameRight'/>
</Page>
<Page Location='33,3' Name='WeaponIconPage' ScrollExtent='17,17' Size='17,17'>
<Image AbsorbsInput='false' Name='WeaponIcon' ScrollExtent='17,17' Size='17,17' Style='/ItemIcons1GridHigh.magcutter'/>
</Page>
<Page AbsorbsInput='false' GetsInput='false' Name='Background' ScrollExtent='58,24' Size='58,24'>
<Image AbsorbsInput='false' BackgroundColor='#00F2C9' Color='#00F2C9' Location='12,0' Name='FrLeft' Opacity='0.750' ScrollExtent='23,24' Size='23,24' Stretch='false' Style='BarLeft'/>
<Image AbsorbsInput='false' BackgroundColor='#00F2C9' Color='#00F2C9' Location='35,0' Name='FrRight' Opacity='0.750' ScrollExtent='23,24' Size='23,24' Stretch='false' Style='FrameRight'/>
<Image AbsorbsInput='false' BackgroundColor='#00F2C9' Color='#00F2C9' Location='12,0' Name='BkLeft' Opacity='0.750' ScrollExtent='23,24' Size='23,24' Stretch='false' Style='FrameLeft'/>
<Image AbsorbsInput='false' BackgroundColor='#00F2C9' Color='#00F2C9' Location='35,0' Name='BkRight' Opacity='0.750' ScrollExtent='23,24' Size='23,24' Stretch='false' Style='BarRight'/>
</Page>
<Text AbsorbsInput='false' Font='/Fonts.HudFont1' GetsInput='false' LocalText='5' Location='11,-3' Name='HolsterText' ScrollExtent='17,13' Size='17,13' TextAlignment='Center' TextAlignmentVertical='Center'>5</Text>
<Button Color='#FF0000' Location='3,1' Name='Mode1' ScrollExtent='8,8' Size='8,8' stretch='false' Style='Occupant'></Button>
<Button Color='#F3E138' Location='3,11' Name='Mode2' ScrollExtent='8,8' Size='8,8' stretch='false' Style='Occupant'></Button>
<ImageStyle Name='FrameLeft'>
<ImageFrame SourceRect='0,0,23,23'>
<ImageFragment Source='ui_HUD_holster2_00' SourceRect='0,0,64,64'/>
<ImageFragment Offset='64,0' Source='ui_HUD_holster2_01' SourceRect='0,0,32,32'/>
<ImageFragment Offset='64,32' Source='ui_HUD_holster2_02' SourceRect='0,0,32,32'/>
</ImageFrame>
</ImageStyle>
<ImageStyle Name='FrameRight'>
<ImageFrame SourceRect='65,0,86,23'>
<ImageFragment Source='ui_HUD_holster2_00' SourceRect='0,0,64,64'/>
<ImageFragment Offset='64,0' Source='ui_HUD_holster2_01' SourceRect='0,0,32,32'/>
<ImageFragment Offset='64,32' Source='ui_HUD_holster2_02' SourceRect='0,0,32,32'/>
</ImageFrame>
</ImageStyle>
<ImageStyle Name='BarLeft'>
<ImageFrame SourceRect='0,24,23,47'>
<ImageFragment Source='ui_HUD_holster2_00' SourceRect='0,0,64,64'/>
<ImageFragment Offset='64,0' Source='ui_HUD_holster2_01' SourceRect='0,0,32,32'/>
<ImageFragment Offset='64,32' Source='ui_HUD_holster2_02' SourceRect='0,0,32,32'/>
</ImageFrame>
</ImageStyle>
<ImageStyle Name='BarRight'>
<ImageFrame SourceRect='65,24,86,47'>
<ImageFragment Source='ui_HUD_holster2_00' SourceRect='0,0,64,64'/>
<ImageFragment Offset='64,0' Source='ui_HUD_holster2_01' SourceRect='0,0,32,32'/>
<ImageFragment Offset='64,32' Source='ui_HUD_holster2_02' SourceRect='0,0,32,32'/>
</ImageFrame>
</ImageStyle>
</Page>
<ImageStyle Name='OccupantStyle'>
<ImageFrame Source='ui_hud_vehicle_occupant_00' SourceRect='0,0,8,8'/>
</ImageStyle>
<ButtonStyle Name='Occupant' RStyleDefault='ROccupant'/>
<RectangleStyle Center='OccupantStyle' Name='ROccupant'/>
<ImageStyle Name='ClipIconStyle'>
<ImageFrame Source='ui_hud_weapon_ammoicons_00' SourceRect='0,0,15,15'/>
</ImageStyle>
<ImageStyle Name='WeaponStyle'>
<ImageFrame Source='ui_hud_weapon_ammoicons_00' SourceRect='0,0,15,15'/>
</ImageStyle>
<ImageStyle Name='PackIconStyle'>
<ImageFrame Source='ui_hud_weapon_ammoicons_00' SourceRect='15,0,30,15'/>
</ImageStyle>
<ImageStyle Name='TrunkIconStyle'>
<ImageFrame Source='ui_hud_weapon_ammoicons_00' SourceRect='0,15,19,27'/>
</ImageStyle>
</Page>
<Page Location='908,0' Name='MailAlert' PackLocation='right,bottom' PackLocationProp='-116/0001,-050/0001' ScrollExtent='58,50' Size='58,50'>
<Image AbsorbsInput='false' BackgroundOpacity='1.000' Location='3,3' Name='Frame' PackSize='absolute,fixed' PackSizeProp='0006/0001,0002/0003' RStyleDefault='/WindowPanes.ActiveItem.style' ScrollExtent='52,44' Size='52,44'/>
<Button BackgroundColor='#FFFFFF' LocalText='g' LocalTooltip='[@MailAlertButtonTooltip^$GA_ToggleMailPane/hud~]' Location='4,4' Name='Button' PackSize='absolute,fixed' PackSizeProp='0008/0001,0002/0003' RStyleDefault=' ' ScrollExtent='50,43' Size='50,43' Style='/Buttons.IconButton.style' Tooltip='@MailAlertButtonTooltip^$GA_ToggleMailPane/hud~'>g</Button>
</Page>
<Page Location='966,0' Name='Control' PackLocation='right,bottom' PackLocationProp='-058/0001,-050/0001' ScrollExtent='58,50' Size='58,50'>
<Image AbsorbsInput='false' BackgroundOpacity='1.000' Location='3,27' Name='Frame' PackSize='absolute,fixed' PackSizeProp='0006/0001,0002/0003' RStyleDefault='/WindowPanes.ActiveItem.style' ScrollExtent='52,20' Size='52,20'/>
<Button BackgroundColor='#FFFFFF' LocalText='n' LocalTooltip='[@MaximizeManagementTooltip^$GA_ToggleManagementPane/hud~]' Location='4,27' Name='Management' PackSize='absolute,fixed' PackSizeProp='0008/0001,0002/0003' RStyleDefault=' ' ScrollExtent='50,20' Size='50,20' Style='/Buttons.IconButton.style' Tooltip='@MaximizeManagementTooltip^$GA_ToggleManagementPane/hud~'>n</Button>
<CheckboxStyle CheckboxSize='50,20' MouseOverSound='interface_feedback_rollover.wav' Name='lfscheckstyle' NormalTextStyle='/Fonts.HudFont2' RStyleActivated='/Buttons.TitlebarTextButton.RPressed' RStyleDefault='/Buttons.TitlebarTextButton.RNormal' RStyleDisabled='/Buttons.TitlebarTextButton.RDisable' RStyleMouseOver='/Buttons.TitlebarTextButton.RNormal' RStyleMouseOverActivated='/Buttons.TitlebarTextButton.RPressed' SetSound='interface_button_pressed.wav' TextAlignment='Center' TextOffset='0,3' UnsetSound='interface_button_pressed.wav'/>
<Image AbsorbsInput='false' BackgroundOpacity='1.000' Location='3,4' Name='Frame' PackSize='absolute,fixed' PackSizeProp='0006/0001,0002/0003' RStyleDefault='/WindowPanes.ActiveItem.style' ScrollExtent='52,20' Size='52,20'/>
<Checkbox Activated='true' BackgroundOpacity='1.000' Checked='true' LocalTooltip='[@ChatLFSTooltip^$GA_ToggleManagementPane/hud~]' Location='4,4' Name='LFSCheckbox' PackSize='absolute,fixed' PackSizeProp='0008/0001,0002/0003' ScrollExtent='50,20' Size='50,20' Style='lfscheckstyle' Tooltip='@ChatLFSTooltip^$GA_ToggleManagementPane/hud~'>LFS</Checkbox>
</Page>
<Page MinimumSize='45,36' Name='Main' PackSize='1,1' PackSizeProp='0002/0003,0002/0003' ScrollExtent='1024,50' Size='1024,50'>
<Checkbox Activated='true' BackgroundOpacity='1.000' Checked='true' Location='3,8' Name='ToggleVehicleIcon' ScrollExtent='9,20' Size='9,20' Style='/Buttons.ActiveItems.checkstyle'>V</Checkbox>
<Image AbsorbsInput='false' BackgroundOpacity='1.000' Location='-20,0' Name='Border' PackSize='absolute,absolute' PackSizeProp='-040/0001,0000/0001' RStyleDefault='/WindowPanes.ActiveItem.style' ScrollExtent='1064,50' Size='1064,50'/>
<Image BackgroundOpacity='1.000' Location='-16,-16' Name='Background' Opacity='0.250' PackSize='absolute,absolute' PackSizeProp='-038/0001,-049/0001' RStyleDefault='/WindowPanes.SmallBackground.style' ScrollExtent='1062,99' Size='1062,99' Stretch='false'/>
</Page>
<Page Location='10,20' Name='Old' ScrollExtent='320,240' Size='320,240' Visible='false'>
<Page Location='206,19' movable='true' Name='SmallStealthPage' ScrollExtent='200,25' Size='200,25'>
<ImageStyle Name='GlowStyle'>
<ImageFrame SourceRect='24,0,48,21'>
<ImageFragment Source='ui_hud_activeitem_stealth_sm_00' SourceRect='0,0,32,32'/>
<ImageFragment Offset='32,0' Source='ui_hud_activeitem_stealth_sm_01' SourceRect='0,0,32,32'/>
</ImageFrame>
</ImageStyle>
<Image AbsorbsInput='false' Location='-1,3' Name='Glow' ScrollExtent='24,21' Size='24,21' Style='ImageStyle'/>
<Image AbsorbsInput='false' BackgroundOpacity='1.000' Location='-1,3' Name='Image' ScrollExtent='24,21' Size='24,21' Style='GlowStyle'/>
<ImageStyle Name='ImageStyle'>
<ImageFrame SourceRect='0,0,24,21'>
<ImageFragment Source='ui_hud_activeitem_stealth_sm_00' SourceRect='0,0,32,32'/>
<ImageFragment Offset='32,0' Source='ui_hud_activeitem_stealth_sm_01' SourceRect='0,0,32,32'/>
</ImageFrame>
</ImageStyle>
<Progressbar AbsorbsInput='false' BarBackgroundColor='#C0C0C0' LocalTooltip='[@ActiveWeaponStealthTooltip]' Location='113,7' Name='Progress' Progress='1.000' ScrollExtent='50,14' Size='50,14' Style='/ProgressBars.Health.style' Tooltip='@ActiveWeaponStealthTooltip'/>
</Page>
<Page Location='186,103' Name='SmallAmmoPage' ScrollExtent='190,24' Size='190,24' Visible='false'>
<Button BackgroundOpacity='0.000' Color='#000000' LocalText='Bob' LocalTooltip='[@ActiveWeaponAmmoCountTooltip]' Location='35,3' Name='AmmoCount' ScrollExtent='40,20' Size='40,20' Style='/Buttons.ActiveItems.TextButton' TextColor='#000000' Tooltip='@ActiveWeaponAmmoCountTooltip'>Bob</Button>
<Button BackgroundOpacity='0.000' Color='#000000' LocalText='Bob' LocalTooltip='[@ActiveWeaponAmmoFiremodeTooltip]' Location='138,5' Name='AmmoFireMode' ScrollExtent='21,15' Size='21,15' Style='/Buttons.ActiveItems.TextButton' TextColor='#000000' Tooltip='@ActiveWeaponAmmoFiremodeTooltip'>Bob</Button>
<Button BackgroundOpacity='0.000' Color='#000000' LocalText='Bob' LocalTooltip='[@ActiveWeaponAmmoTypeTooltip]' Location='163,5' Name='AmmoType' ScrollExtent='20,16' Size='20,16' Style='/Buttons.ActiveItems.TextButton' TextColor='#000000' Tooltip='@ActiveWeaponAmmoTypeTooltip'>Bob</Button>
<Button LocalTooltip='[@ActiveWeaponToggleAmmoTooltip]' Location='4,4' Name='ToggleSize' ScrollExtent='9,20' Size='9,20' Style='/Buttons.ActiveItems.style' Tooltip='@ActiveWeaponToggleAmmoTooltip'></Button>
<Image AbsorbsInput='false' Location='18,4' Name='ClipIcon' ScrollExtent='24,18' Size='24,18' Stretch='false' Style='ClipIconStyle'/>
<Image AbsorbsInput='false' Location='80,4' Name='ReserveIcon' ScrollExtent='24,19' Size='24,19' Stretch='false' Style='PackIconStyle'/>
<Text AbsorbsInput='false' Font='/Fonts.HudFont2' GetsInput='false' LocalText='Bob' Location='93,3' Name='ReserveAmmo' ScrollExtent='41,18' Size='41,18' TextAlignment='Center' TextAlignmentVertical='Center'>Bob</Text>
<ImageStyle Name='ClipIconStyle'>
<ImageFrame Source='ui_hud_weapon_ammoicons_00' SourceRect='0,0,15,15'/>
</ImageStyle>
<ImageStyle Name='PackIconStyle'>
<ImageFrame Source='ui_hud_weapon_ammoicons_00' SourceRect='15,0,30,15'/>
</ImageStyle>
<ImageStyle Name='TrunkIconStyle'>
<ImageFrame Source='ui_hud_weapon_ammoicons_00' SourceRect='0,15,19,27'/>
</ImageStyle>
<Image AbsorbsInput='false' BackgroundOpacity='1.000' Name='Border' PackSize='1,1' PackSizeProp='0002/0003,0002/0003' RStyleDefault='/WindowPanes.ActiveItem.style' ScrollExtent='190,24' Size='190,24'/>
</Page>
<Page Location='195,170' Name='AmmoPage' ScrollExtent='190,63' Size='190,63' Visible='false'>
<Button BackgroundOpacity='0.000' Color='#000000' LocalText='Bob' LocalTooltip='[@ActiveWeaponAmmoCountTooltip]' Location='37,23' Name='AmmoCount' ScrollExtent='60,17' Size='60,17' Style='/Buttons.ActiveItems.TextButton' TextColor='#000000' Tooltip='@ActiveWeaponAmmoCountTooltip'>Bob</Button>
<Button BackgroundOpacity='0.000' Color='#000000' LocalText='Bob' LocalTooltip='[@ActiveWeaponAmmoFiremodeTooltip]' Location='21,44' Name='AmmoFireMode' ScrollExtent='157,16' Size='157,16' Style='/Buttons.ActiveItems.TextButton' TextColor='#000000' Tooltip='@ActiveWeaponAmmoFiremodeTooltip'>Bob</Button>
<Button BackgroundOpacity='0.000' Color='#000000' LocalText='Bob' LocalTooltip='[@ActiveWeaponAmmoTypeTooltip]' Location='21,3' Name='AmmoType' ScrollExtent='156,16' Size='156,16' Style='/Buttons.ActiveItems.TextButton' TextColor='#000000' Tooltip='@ActiveWeaponAmmoTypeTooltip'>Bob</Button>
<Button LocalTooltip='[@ActiveWeaponToggleAmmoTooltip]' Location='5,4' Name='ToggleSize' ScrollExtent='9,20' Size='9,20' Style='/Buttons.ActiveItems.styleChecked' Tooltip='@ActiveWeaponToggleAmmoTooltip'></Button>
<Rectangle AbsorbsInput='false' Color='#00F2C9' Location='19,0' Name='AmmoBox' Opacity='0.750' RStyleDefault='HUDLineStyle.style' ScrollExtent='159,21' Size='159,21'/>
<Rectangle AbsorbsInput='false' Color='#00F2C9' Location='95,20' Name='AmmoBox' Opacity='0.750' RStyleDefault='HUDLineStyle.style' ScrollExtent='83,21' Size='83,21'/>
<Rectangle AbsorbsInput='false' Color='#00F2C9' Location='19,40' Name='AmmoBox' Opacity='0.750' RStyleDefault='HUDLineStyle.style' ScrollExtent='159,23' Size='159,23'/>
<Rectangle AbsorbsInput='false' Color='#00F2C9' Location='19,20' Name='AmmoBox' Opacity='0.750' RStyleDefault='BackgroundLineStyle.style' ScrollExtent='77,21' Size='77,21'/>
<Image AbsorbsInput='false' Location='21,22' Name='ClipIcon' ScrollExtent='24,20' Size='24,20' Stretch='false' Style='ClipIconStyle'/>
<Image AbsorbsInput='false' Location='98,22' Name='ReserveIcon' ScrollExtent='24,18' Size='24,18' Stretch='false' Style='PackIconStyle'/>
<Text AbsorbsInput='false' Font='/Fonts.HudFont2' GetsInput='false' LocalText='Bob' Location='115,22' Name='ReserveAmmo' ScrollExtent='61,18' Size='61,18' TextAlignment='Center' TextAlignmentVertical='Center'>Bob</Text>
<ImageStyle Name='ClipIconStyle'>
<ImageFrame Source='ui_hud_weapon_ammoicons_00' SourceRect='0,0,15,15'/>
</ImageStyle>
<ImageStyle Name='PackIconStyle'>
<ImageFrame Source='ui_hud_weapon_ammoicons_00' SourceRect='15,0,30,15'/>
</ImageStyle>
<ImageStyle Name='TrunkIconStyle'>
<ImageFrame Source='ui_hud_weapon_ammoicons_00' SourceRect='0,15,19,27'/>
</ImageStyle>
<Image AbsorbsInput='false' BackgroundOpacity='1.000' Name='Border' PackSize='1,1' PackSizeProp='0002/0003,0002/0003' RStyleDefault='/WindowPanes.ActiveItem.style' ScrollExtent='190,63' Size='190,63'/>
</Page>
<Page Location='195,143' Name='SmallInventoryPage' ScrollExtent='190,23' Size='190,23' Visible='false'>
<Checkbox Activated='true' BackgroundOpacity='1.000' Checked='true' LocalTooltip='[@ActiveWeaponShowVehicleTooltip]' Location='30,4' Name='Slot1' ScrollExtent='27,15' Size='27,15' Style='/Buttons.SmallMiniInventory.checkstyle' Tooltip='@ActiveWeaponShowVehicleTooltip'>1</Checkbox>
<Checkbox BackgroundOpacity='1.000' LocalTooltip='[@ActiveWeaponShowVehicleTooltip]' Location='64,4' Name='Slot2' ScrollExtent='27,15' Size='27,15' Style='/Buttons.SmallMiniInventory.checkstyle' Tooltip='@ActiveWeaponShowVehicleTooltip'>2</Checkbox>
<Checkbox Activated='true' BackgroundOpacity='1.000' Checked='true' LocalTooltip='[@ActiveWeaponShowVehicleTooltip]' Location='101,4' Name='Slot3' ScrollExtent='27,15' Size='27,15' Style='/Buttons.SmallMiniInventory.checkstyle' Tooltip='@ActiveWeaponShowVehicleTooltip'>3</Checkbox>
<Checkbox BackgroundOpacity='1.000' LocalTooltip='[@ActiveWeaponShowVehicleTooltip]' Location='140,4' Name='Slot4' ScrollExtent='27,15' Size='27,15' Style='/Buttons.SmallMiniInventory.checkstyle' Tooltip='@ActiveWeaponShowVehicleTooltip'>4</Checkbox>
<Button LocalTooltip='[@ActiveWeaponToggleInventoryTooltip]' Location='6,4' Name='ToggleSize' ScrollExtent='9,20' Size='9,20' Style='/Buttons.ActiveItems.style' Tooltip='@ActiveWeaponToggleInventoryTooltip'></Button>
<Image AbsorbsInput='false' BackgroundOpacity='1.000' Name='Border' PackSize='1,1' PackSizeProp='0002/0003,0002/0003' RStyleDefault='/WindowPanes.ActiveItem.style' ScrollExtent='190,23' Size='190,23'/>
</Page>
<Page Location='404,80' Name='InventoryPage' ScrollExtent='190,57' Size='190,57'>
<Text AbsorbsInput='false' Font='/Fonts.ChatFont' GetsInput='false' Location='27,5' Name='SlotText1' ScrollExtent='65,22' Size='65,22' TextAlignment='Center' TextAlignmentVertical='Center'></Text>
<Text AbsorbsInput='false' Font='/Fonts.ChatFont' GetsInput='false' Location='111,5' Name='SlotText2' ScrollExtent='64,22' Size='64,22' TextAlignment='Center' TextAlignmentVertical='Center'></Text>
<Text AbsorbsInput='false' Font='/Fonts.ChatFont' GetsInput='false' Location='27,31' Name='SlotText3' ScrollExtent='65,22' Size='65,22' TextAlignment='Center' TextAlignmentVertical='Center'></Text>
<Text AbsorbsInput='false' Font='/Fonts.ChatFont' GetsInput='false' Location='111,31' Name='SlotText4' ScrollExtent='64,22' Size='64,22' TextAlignment='Center' TextAlignmentVertical='Center'></Text>
<Checkbox BackgroundOpacity='1.000' LocalTooltip='[@ActiveWeaponShowVehicleTooltip]' Location='18,5' Name='Slot1' ScrollExtent='75,22' Size='75,22' Style='/Buttons.MiniInventory.checkstyle' Tooltip='@ActiveWeaponShowVehicleTooltip'>1</Checkbox>
<Checkbox BackgroundOpacity='1.000' LocalTooltip='[@ActiveWeaponShowVehicleTooltip]' Location='99,5' Name='Slot2' ScrollExtent='85,22' Size='85,22' Style='/Buttons.MiniInventory.checkstyle' Tooltip='@ActiveWeaponShowVehicleTooltip'>2</Checkbox>
<Checkbox BackgroundOpacity='1.000' LocalTooltip='[@ActiveWeaponShowVehicleTooltip]' Location='18,31' Name='Slot3' ScrollExtent='75,22' Size='75,22' Style='/Buttons.MiniInventory.checkstyle' Tooltip='@ActiveWeaponShowVehicleTooltip'>3</Checkbox>
<Checkbox BackgroundOpacity='1.000' LocalTooltip='[@ActiveWeaponShowVehicleTooltip]' Location='99,31' Name='Slot4' ScrollExtent='75,22' Size='75,22' Style='/Buttons.MiniInventory.checkstyle' Tooltip='@ActiveWeaponShowVehicleTooltip'>4</Checkbox>
<Button LocalTooltip='[@ActiveWeaponToggleInventoryTooltip]' Location='4,4' Name='ToggleSize' ScrollExtent='9,20' Size='9,20' Style='/Buttons.ActiveItems.styleChecked' Tooltip='@ActiveWeaponToggleInventoryTooltip'></Button>
<Image AbsorbsInput='false' BackgroundOpacity='1.000' Name='Border' PackSize='1,1' PackSizeProp='0002/0003,0002/0003' RStyleDefault='/WindowPanes.ActiveItem.style' ScrollExtent='190,57' Size='190,57'/>
</Page>
</Page>
</Page>
