<Page defaultcolor='#FF0000' enemycolor='#00FF00' friendlycolor='#00FFFF' GetsInput='false' Location='262,134' Name='TestCrosshair' PackLocation='Center,Center' PackLocationProp='-250/0001,-250/0001' ScrollExtent='500,500' Size='500,500' Visible='false'>
<Text Font='/SmallFont' LocalText='Test Crosshair' Location='100,112' Name='ID' Opacity='0.500' ScrollExtent='100,12' Size='100,12' Visible='false'>Test Crosshair</Text>
<Ellipse Color='#FF0000' Location='233,234' Name='COF' Opacity='0.400' ScrollExtent='32,32' Size='32,32'/>
<Image Color='#FF0000' LocalTooltip='0,0,32,32' Location='202,202' Name='COF_TopLeft' Opacity='0.500' ScrollExtent='32,32' Size='32,32' SourceRect='0,0,32,32' SourceResource='ui_pistol_crosshair_test' Stretch='false' Tooltip='0,0,32,32' TooltipStyle='ui_pistolcrosshair'/>
<Image Color='#FF0000' Location='234,202' Name='COF_Top' Opacity='0.500' ScrollExtent='32,32' Size='32,32' SourceRect='34,0,66,32' SourceResource='ui_pistol_crosshair_test'/>
<Image Color='#FF0000' Location='266,202' Name='COF_TopRight' Opacity='0.500' ScrollExtent='32,32' Size='32,32' SourceRect='68,0,100,32' SourceResource='ui_pistol_crosshair_test' Stretch='false'/>
<Image Color='#FF0000' Location='202,234' Name='COF_Left' Opacity='0.500' ScrollExtent='32,32' Size='32,32' SourceRect='0,34,32,66' SourceResource='ui_pistol_crosshair_test'/>
<Image Color='#FF0000' Location='234,234' Name='Reticle' Opacity='0.500' ScrollExtent='32,32' Size='32,32' SourceRect='34,34,66,66' SourceResource='ui_pistol_crosshair_test' Visible='false'/>
<Image Color='#FF0000' Location='266,234' Name='COF_Right' Opacity='0.500' ScrollExtent='32,32' Size='32,32' SourceRect='68,34,100,66' SourceResource='ui_pistol_crosshair_test'/>
<Image Color='#FF0000' Location='202,265' Name='COF_BottomLeft' Opacity='0.500' ScrollExtent='32,32' Size='32,32' SourceRect='0,66,32,100' SourceResource='ui_pistol_crosshair_test'/>
<Image Color='#FF0000' Location='234,265' Name='COF_Bottom' Opacity='0.500' ScrollExtent='32,32' Size='32,32' SourceRect='34,66,66,100' SourceResource='ui_pistol_crosshair_test'/>
<Image Color='#FF0000' Location='266,265' Name='COF_BottomRight' Opacity='0.500' ScrollExtent='32,32' Size='32,32' SourceRect='68,66,100,100' SourceResource='ui_pistol_crosshair_test'/>
<Image Color='#FF0000' Location='232,234' Name='AutolockTracker' ScrollExtent='16,16' Size='16,16' SourceRect='0,0,16,16' SourceResource='ui_autolocktracker' Stretch='false' Visible='false'/>
<Text Color='#FFFF00' Font='/SmallFont' LocalText='0000' Location='217,110' Name='AutolockCountdownText' ScrollExtent='30,12' Size='30,12' TextAlignment='Right' Visible='false'>0000</Text>
<Image Color='#FF0000' Location='245,112' Name='AutolockArrow' ScrollExtent='8,7' Size='8,7' SourceResource='ui_autolock_arrow' Stretch='false' Visible='false'/>
<Image Color='#FF0000' Location='122,122' Name='Autolock' Opacity='0.500' ScrollExtent='256,256' Size='256,256' SourceRect='0,0,256,256' SourceResource='ui_autolock' Visible='false'/>
</Page>
