<Page defaultcolor='#FFFFFF' enemycolor='#FF0000' friendlycolor='#00FF00' GetsInput='false' Location='362,234' Name='MiniGunCrosshair' PackLocation='Center,Center' PackLocationProp='-150/0001,-150/0001' ScrollExtent='300,300' Size='300,300' Visible='false'>
<Text Font='/SmallFont' LocalText='Minigun Crosshair' Location='0,24' Name='ID' Opacity='0.500' ScrollExtent='100,12' Size='100,12' Visible='false'>Minigun Crosshair</Text>
<Ellipse Color='#00FF00' Location='133,134' Name='COF' Opacity='0.400' ScrollExtent='32,32' Size='32,32'/>
<Image LocalTooltip='0,0,32,32' Location='102,102' Name='COF_TopLeft' Opacity='0.500' ScrollExtent='32,32' Size='32,32' SourceRect='0,0,32,32' SourceResource='ui_pistol_crosshair' Stretch='false' Tooltip='0,0,32,32' TooltipStyle='ui_pistolcrosshair'/>
<Image Location='134,102' Name='COF_Top' Opacity='0.500' ScrollExtent='32,32' Size='32,32' SourceRect='34,0,66,32' SourceResource='ui_pistol_crosshair'/>
<Image Location='166,102' Name='COF_TopRight' Opacity='0.500' ScrollExtent='32,32' Size='32,32' SourceRect='68,0,100,32' SourceResource='ui_pistol_crosshair' Stretch='false'/>
<Image Location='102,134' Name='COF_Left' Opacity='0.500' ScrollExtent='32,32' Size='32,32' Style='DefaultCrosshair.COF_LeftGraphic'/>
<Image Location='134,134' Name='Reticle' Opacity='0.500' ScrollExtent='32,32' Size='32,32' Style='DefaultCrosshair.COF_ReticuleGraphic' Visible='false'/>
<Image Location='166,134' Name='COF_Right' Opacity='0.500' ScrollExtent='32,32' Size='32,32' Style='DefaultCrosshair.COF_RightGraphic'/>
<Image Location='102,165' Name='COF_BottomLeft' Opacity='0.500' ScrollExtent='32,32' Size='32,32' Style='DefaultCrosshair.COF_BottomLeftGraphic'/>
<Image Location='134,165' Name='COF_Bottom' Opacity='0.500' ScrollExtent='32,32' Size='32,32' Style='DefaultCrosshair.COF_BottomGraphic'/>
<Image Location='166,165' Name='COF_BottomRight' Opacity='0.500' ScrollExtent='32,32' Size='32,32' Style='DefaultCrosshair.COF_BottomRightGraphic'/>
</Page>
