<Page Location='302,105' MinimumSize='240,60' movable='false' Name='RankPopup' PackLocation='Center,Top' PackLocationProp='-210/0001,0105/0001' PackSize='Fixed,Fixed' PackSizeProp='0002/0003,0002/0003' ScrollExtent='440,60' Size='440,60' Visible='false'>
<Text Activated='true' Font='/Fonts.HudFont3' GetsInput='false' Location='45,13' MaxLines='1' Name='Text' PackSize='absolute,absolute' PackSizeProp='0090/0001,0037/0001' ScrollExtent='350,23' Size='350,23' TextAlignment='Center' TextAlignmentVertical='Center'></Text>
<Image Location='18,10' Name='LeftIcon' PackLocation='Left,Top' PackLocationProp='0018/0001,0010/0001' ScrollExtent='28,31' Size='28,31' Style='/Icons.HUD.Mini_logo_VS'/>
<Image Location='394,10' Name='RightIcon' PackLocation='Right,Top' PackLocationProp='-046/0001,0010/0001' ScrollExtent='28,31' Size='28,31' Style='/Icons.HUD.Mini_logo_VS'/>
<Image AbsorbsInput='false' BackgroundOpacity='1.000' Name='Background' Opacity='0.800' PackSize='1,1' PackSizeProp='0002/0003,0002/0003' RStyleDefault='/WindowPanes.SmallBackground.style' ScrollExtent='440,60' Size='440,60' Stretch='false' Style=' '/>
</Page>
