<Page BackgroundColor='#FFFFFF' crosshairtype='guided_missile' defaultcolor='#FFFFFF' enemycolor='#FF0000' friendlycolor='#00FF00' GetsInput='false' Location='262,134' Name='GuidedMissileCrosshair' PackLocation='Center,Center' PackLocationProp='-250/0001,-250/0001' ScrollExtent='500,500' Size='500,500' Visible='false' visualeditlock='true'>
<Image Location='214,214' Name='Reticle' Opacity='0.500' ScrollExtent='73,73' Size='73,73' SourceResource='ui_crosshair_missile_guided'/>
<Text Font='/SmallFont' LocalText='Rifle Crosshair' Location='100,112' Name='ID' Opacity='0.500' ScrollExtent='100,12' Size='100,12' Visible='false'>Rifle Crosshair</Text>
<Ellipse ArcBegin='0.790' ArcEnd='0.960' GetsInput='false' Location='240,240' Name='COF_TopRight' ScrollExtent='25,25' Size='25,25' Thickness='10.000'/>
<Ellipse ArcBegin='0.040' ArcEnd='0.210' GetsInput='false' Location='240,240' Name='COF_BottomRight' ScrollExtent='25,25' Size='25,25' Thickness='10.000'/>
<Ellipse ArcBegin='0.290' ArcEnd='0.460' GetsInput='false' Location='240,240' Name='COF_BottomLeft' ScrollExtent='25,25' Size='25,25' Thickness='10.000'/>
<Ellipse ArcBegin='0.540' ArcEnd='0.710' GetsInput='false' Location='240,240' Name='COF_TopLeft' ScrollExtent='25,25' Size='25,25' Thickness='10.000'/>
</Page>
