<Page GetsInput='false' Location='754,675' Name='ModuleIndicator' PackLocation='right,bottom' PackLocationProp='-270/0001,-093/0001' ScrollExtent='42,40' Size='42,40' Visible='false'>
<Image AbsorbsInput='false' Color='#F10A1F' Name='ModuleIconInvalid' ScrollExtent='40,40' Size='40,40' SourceRect='0,0,64,64' SourceResource='ui_hud_icon_module_empty' Style=' '/>
<Image AbsorbsInput='false' Name='ModuleIconEmpty' ScrollExtent='40,40' Size='40,40' SourceRect='0,0,64,64' SourceResource='ui_hud_icon_module_empty' Style=' '/>
<Image AbsorbsInput='false' Color='#FF7F00' Name='ModuleIconBind' ScrollExtent='40,40' Size='40,40' SourceRect='0,0,64,64' SourceResource='ui_hud_icon_module_full' Style=' '/>
<Image AbsorbsInput='false' Color='#FFFF00' Name='ModuleIconEnergy' ScrollExtent='40,40' Size='40,40' SourceRect='0,0,64,64' SourceResource='ui_hud_icon_module_full' Style=' '/>
<Image AbsorbsInput='false' Color='#E5C3A1' Name='ModuleIconFortifier' ScrollExtent='40,40' Size='40,40' SourceRect='0,0,64,64' SourceResource='ui_hud_icon_module_full' Style=' '/>
<Image AbsorbsInput='false' Color='#00FFFF' Name='ModuleIconDefender' ScrollExtent='40,40' Size='40,40' SourceRect='0,0,64,64' SourceResource='ui_hud_icon_module_full' Style=' '/>
<Image AbsorbsInput='false' Color='#00FF00' Name='ModuleIconVehicle' ScrollExtent='40,40' Size='40,40' SourceRect='0,0,64,64' SourceResource='ui_hud_icon_module_full' Style=' '/>
<Image AbsorbsInput='false' Color='#007FFF' Name='ModuleIconWeapon' ScrollExtent='40,40' Size='40,40' SourceRect='0,0,64,64' SourceResource='ui_hud_icon_module_full' Style=' '/>
</Page>
