<Page Location='302,105' MinimumSize='240,60' movable='false' Name='AwardPopup' PackLocation='Center,Top' PackLocationProp='-210/0001,0105/0001' PackSize='Fixed,Fixed' PackSizeProp='0002/0003,0002/0003' ScrollExtent='440,104' Size='440,104' Visible='false'>
<Text Activated='true' Font='/Fonts.HudFont3' GetsInput='false' Location='19,13' MaxLines='10' Name='Text' PackSize='absolute,absolute' PackSizeProp='0037/0001,0037/0001' ScrollExtent='403,67' Size='403,67' TextAlignment='Center' TextAlignmentVertical='Center'></Text>
<Image AbsorbsInput='false' BackgroundOpacity='1.000' Name='Background' Opacity='0.800' PackSize='1,1' PackSizeProp='0002/0003,0002/0003' RStyleDefault='/WindowPanes.SmallBackground.style' ScrollExtent='440,104' Size='440,104' Stretch='false' Style=' '/>
</Page>
