<Page AbsorbsInput='false' Location='259,251' Name='OxygenBackground' PackLocation='Center,Center' PackLocationProp='-253/0001,-133/0001' ScrollExtent='506,100' Size='506,100' Visible='false'>
<Progressbar AbsorbsInput='false' BarBackgroundColor='#000000' Color='#777777' Location='29,54' Name='VehicleOxygenBar' ScrollExtent='447,13' Size='447,13' Style='/ProgressBars.Health.style' TooltipStyle='/Fonts.DefaultFont'/>
<Image AbsorbsInput='false' BackgroundOpacity='1.000' Name='Background' PackSize='1,1' PackSizeProp='0002/0003,0002/0003' RStyleDefault='style' ScrollExtent='506,100' Size='506,100' Stretch='false'/>
</Page>
