<Page AbsorbsInput='false' Location='259,251' Name='VehicleOxygen' PackLocation='Center,Center' PackLocationProp='-253/0001,-133/0001' ScrollExtent='506,100' Size='506,100' Visible='false'>
<Text AbsorbsInput='false' Color='#0000FF' Font='/Fonts.HudFont3' LocalText='[@InformationAboutProgress]' Location='29,25' Name='VehicleOxygenText' ScrollExtent='400,21' Size='400,21'>@InformationAboutProgress</Text>
<Progressbar AbsorbsInput='false' BarBackgroundColor='#0000FF' Color='#777777' Location='29,54' Name='VehicleOxygenBar' Progress='0.330' ScrollExtent='447,13' Size='447,13' Style='/ProgressBars.Oxygen.style' TooltipStyle='/Fonts.DefaultFont'/>
</Page>
