<Page crosshairtype='pistol_vanu' defaultcolor='#FFFFFF' enemycolor='#FF0000' friendlycolor='#00FF00' GetsInput='false' Location='262,134' Name='PistolVanuCrosshair' PackLocation='Center,Center' PackLocationProp='-250/0001,-250/0001' ScrollExtent='500,500' Size='500,500' Visible='false' visualeditlock='true'>
<Image Location='249,248' Name='COF_BottomRight' Rotation='0.375' ScrollExtent='32,32' Size='32,32' SourceResource='ui_hud_crosshair_vanu'/>
<Image Location='219,248' Name='COF_BottomLeft' Rotation='0.625' ScrollExtent='32,32' Size='32,32' SourceResource='ui_hud_crosshair_vanu'/>
<Image Location='234,219' Name='COF_Top' ScrollExtent='32,32' Size='32,32' SourceResource='ui_hud_crosshair_vanu'/>
<Text Font='/SmallFont' LocalText='Ancient Crosshair' Location='100,112' Name='ID' Opacity='0.500' ScrollExtent='100,12' Size='100,12' Visible='false'>Ancient Crosshair</Text>
</Page>
