<Page BackgroundColor='#0000FF' Location='957,525' MaximumSize='252,190' MinimumSize='64,18' movable='true' Name='CombatEngineering' PackLocation='right,bottom' PackLocationProp='-067/0001,-243/0001' ScrollExtent='64,190' Size='64,190' UserResizable='true' Visible='false'>
<VolumePage BackgroundColor='#FF0000' CellCount='1,11' CellSelectable='false' CellSize='60,15' MaximumSize='250,190' MinimumScrollExtent='64,189' MinimumSize='64,19' Name='Volume' PackSize='absolute,absolute' PackSizeProp='0000/0001,0000/0001' ScrollExtent='64,190' Size='64,190'>
<Page BackgroundColor='#0000FF' Location='2,2' MaximumSize='60,15' MinimumSize='60,15' Name='Boomers' ScrollExtent='60,15' Size='60,15'>
<Image GetsInput='true' LocalTooltip='[@CEHUDBoomers]' Location='4,0' Name='Icon' ScrollExtent='14,14' Size='14,14' Style='/Icons.Map.Equipment.Boomer_icon' Tooltip='@CEHUDBoomers'/>
<Image Color='#000000' Location='5,1' Name='IconShadow' Opacity='0.750' ScrollExtent='14,14' Size='14,14' Style='/Icons.Map.Equipment.Boomer_icon'/>
<Text Font='/Fonts.HudFont1' GetsInput='false' LocalText='20/20' Location='18,0' Margin='0,0,1,0' Name='Text' PackLocation='top,right' PackLocationProp='0018/0001,-015/0001' PackSize='absolute,absolute' PackSizeProp='0022/0001,0000/0001' ScrollExtent='38,15' ShadowStyle='/Shadows.Default' Size='38,15' TextAlignment='Right' TextAlignmentVertical='Center'>20/20</Text>
</Page>
<Page BackgroundColor='#00FF00' Location='2,19' MaximumSize='60,15' MinimumSize='60,15' Name='Mines' ScrollExtent='60,15' Size='60,15'>
<Image GetsInput='true' LocalTooltip='[@CEHUDHEMines]' Location='4,0' Name='Icon' ScrollExtent='14,14' Size='14,14' Style='/Icons.Map.Equipment.Hemine_icon' Tooltip='@CEHUDHEMines'/>
<Image Color='#000000' Location='5,1' Name='IconShadow' Opacity='0.750' ScrollExtent='14,14' Size='14,14' Style='/Icons.Map.Equipment.Hemine_icon'/>
<Text Font='/Fonts.HudFont1' GetsInput='false' LocalText='20/20' Location='18,0' Margin='0,0,1,0' Name='Text' PackLocation='top,right' PackLocationProp='0018/0001,-015/0001' PackSize='absolute,absolute' PackSizeProp='0022/0001,0000/0001' ScrollExtent='38,15' ShadowStyle='/Shadows.Default' Size='38,15' TextAlignment='Right' TextAlignmentVertical='Center'>20/20</Text>
</Page>
<Page BackgroundColor='#0000FF' Location='2,36' MaximumSize='60,15' MinimumSize='60,15' Name='Spitfires' ScrollExtent='60,15' Size='60,15'>
<Image GetsInput='true' LocalTooltip='[@CEHUDSpitfires]' Location='4,0' Name='Icon' ScrollExtent='14,14' Size='14,14' Style='/Icons.Map.Equipment.Spitfire_icon' Tooltip='@CEHUDSpitfires'/>
<Image Color='#000000' Location='5,1' Name='IconShadow' Opacity='0.750' ScrollExtent='14,14' Size='14,14' Style='/Icons.Map.Equipment.Spitfire_icon'/>
<Text Font='/Fonts.HudFont1' GetsInput='false' LocalText='20/20' Location='18,0' Margin='0,0,1,0' Name='Text' PackLocation='top,right' PackLocationProp='0018/0001,-015/0001' PackSize='absolute,absolute' PackSizeProp='0022/0001,0000/0001' ScrollExtent='38,15' ShadowStyle='/Shadows.Default' Size='38,15' TextAlignment='Right' TextAlignmentVertical='Center'>20/20</Text>
</Page>
<Page BackgroundColor='#0000FF' Location='2,53' MaximumSize='60,15' MinimumSize='60,15' Name='MotionSensors' ScrollExtent='60,15' Size='60,15'>
<Image GetsInput='true' LocalTooltip='[@CEHUDMotionSensors]' Location='4,0' Name='Icon' ScrollExtent='14,14' Size='14,14' Style='/Icons.Map.Equipment.Motion_sensor_icon' Tooltip='@CEHUDMotionSensors'/>
<Image Color='#000000' Location='5,1' Name='IconShadow' Opacity='0.750' ScrollExtent='14,14' Size='14,14' Style='/Icons.Map.Equipment.Motion_sensor_icon'/>
<Text Font='/Fonts.HudFont1' GetsInput='false' LocalText='20/20' Location='18,0' Margin='0,0,1,0' Name='Text' PackLocation='top,right' PackLocationProp='0018/0001,-015/0001' PackSize='absolute,absolute' PackSizeProp='0022/0001,0000/0001' ScrollExtent='38,15' ShadowStyle='/Shadows.Default' Size='38,15' TextAlignment='Right' TextAlignmentVertical='Center'>20/20</Text>
</Page>
<Page Location='2,70' MaximumSize='60,15' MinimumSize='60,15' Name='SensorShields' ScrollExtent='60,15' Size='60,15'>
<Image GetsInput='true' LocalTooltip='[@CEHUDMotionSensors]' Location='4,0' Name='Icon' ScrollExtent='14,14' Size='14,14' Style='/Icons.Map.Equipment.sensor_shield_icon' Tooltip='@CEHUDMotionSensors'/>
<Image Color='#000000' GetsInput='true' LocalTooltip='[@CEHUDMotionSensors]' Location='5,1' Name='IconShadow' ScrollExtent='14,14' Size='14,14' Style='/Icons.Map.Equipment.sensor_shield_icon' Tooltip='@CEHUDMotionSensors'/>
<Text Font='/Fonts.HudFont1' GetsInput='false' LocalText='20/20' Location='18,0' Margin='0,0,1,0' Name='Text' PackLocation='top,right' PackLocationProp='0018/0001,-015/0001' PackSize='absolute,absolute' PackSizeProp='0022/0001,0000/0001' ScrollExtent='38,15' ShadowStyle='/Shadows.Default' Size='38,15' TextAlignment='Right' TextAlignmentVertical='Center'>20/20</Text>
</Page>
<Page BackgroundColor='#0000FF' Location='2,87' MaximumSize='60,15' MinimumSize='60,15' Name='JammerMines' ScrollExtent='60,15' Size='60,15'>
<Image GetsInput='true' LocalTooltip='[@CEHUDJammerMines]' Location='4,0' Name='Icon' ScrollExtent='14,14' Size='14,14' Style='/Icons.Map.Equipment.jammer_mine_icon' Tooltip='@CEHUDJammerMines'/>
<Image Color='#000000' Location='5,1' Name='IconShadow' Opacity='0.750' ScrollExtent='14,14' Size='14,14' Style='/Icons.Map.Equipment.jammer_mine_icon'/>
<Text Font='/Fonts.HudFont1' GetsInput='false' LocalText='20/20' Location='18,0' Margin='0,0,1,0' Name='Text' PackLocation='top,right' PackLocationProp='0018/0001,-015/0001' PackSize='absolute,absolute' PackSizeProp='0022/0001,0000/0001' ScrollExtent='38,15' ShadowStyle='/Shadows.Default' Size='38,15' TextAlignment='Right' TextAlignmentVertical='Center'>20/20</Text>
</Page>
<Page BackgroundColor='#0000FF' Location='2,104' MaximumSize='60,15' MinimumSize='60,15' Name='CloakingSpitfires' ScrollExtent='60,15' Size='60,15'>
<Image GetsInput='true' LocalTooltip='[@CEHUDCloakingSpitfires]' Location='4,0' Name='Icon' ScrollExtent='14,14' Size='14,14' Style='/Icons.Map.Equipment.spitfire_cloaked_icon' Tooltip='@CEHUDCloakingSpitfires'/>
<Image Color='#000000' Location='5,1' Name='IconShadow' Opacity='0.750' ScrollExtent='14,14' Size='14,14' Style='/Icons.Map.Equipment.spitfire_cloaked_icon'/>
<Text Font='/Fonts.HudFont1' GetsInput='false' LocalText='5/5' Location='18,0' Margin='0,0,1,0' Name='Text' PackLocation='top,right' PackLocationProp='0018/0001,-015/0001' PackSize='absolute,absolute' PackSizeProp='0022/0001,0000/0001' ScrollExtent='38,15' ShadowStyle='/Shadows.Default' Size='38,15' TextAlignment='Right' TextAlignmentVertical='Center'>5/5</Text>
</Page>
<Page BackgroundColor='#0000FF' Location='2,121' MaximumSize='60,15' MinimumSize='60,15' Name='FlakSpitfires' ScrollExtent='60,15' Size='60,15'>
<Image GetsInput='true' LocalTooltip='[@CEHUDFlakSpitfires]' Location='4,0' Name='Icon' ScrollExtent='14,14' Size='14,14' Style='/Icons.Map.Equipment.spitfire_aa_icon' Tooltip='@CEHUDFlakSpitfires'/>
<Image Color='#000000' Location='5,1' Name='IconShadow' Opacity='0.750' ScrollExtent='14,14' Size='14,14' Style='/Icons.Map.Equipment.spitfire_aa_icon'/>
<Text Font='/Fonts.HudFont1' GetsInput='false' LocalText='5/5' Location='18,0' Margin='0,0,1,0' Name='Text' PackLocation='top,right' PackLocationProp='0018/0001,-015/0001' PackSize='absolute,absolute' PackSizeProp='0022/0001,0000/0001' ScrollExtent='38,15' ShadowStyle='/Shadows.Default' Size='38,15' TextAlignment='Right' TextAlignmentVertical='Center'>5/5</Text>
</Page>
<Page BackgroundColor='#0000FF' Location='2,138' MaximumSize='60,15' MinimumSize='60,15' Name='TankTraps' ScrollExtent='60,15' Size='60,15'>
<Image GetsInput='true' LocalTooltip='[@CEHUDTankTraps]' Location='4,0' Name='Icon' ScrollExtent='14,14' Size='14,14' Style='/Icons.Map.Equipment.tank_traps_icon' Tooltip='@CEHUDTankTraps'/>
<Image Color='#000000' Location='5,1' Name='IconShadow' Opacity='0.750' ScrollExtent='14,14' Size='14,14' Style='/Icons.Map.Equipment.tank_traps_icon'/>
<Text Font='/Fonts.HudFont1' GetsInput='false' LocalText='5/5' Location='18,0' Margin='0,0,1,0' Name='Text' PackLocation='top,right' PackLocationProp='0018/0001,-015/0001' PackSize='absolute,absolute' PackSizeProp='0022/0001,0000/0001' ScrollExtent='38,15' ShadowStyle='/Shadows.Default' Size='38,15' TextAlignment='Right' TextAlignmentVertical='Center'>5/5</Text>
</Page>
<Page BackgroundColor='#0000FF' Location='2,155' MaximumSize='60,15' MinimumSize='60,15' Name='FieldTurrets' ScrollExtent='60,15' Size='60,15'>
<Image GetsInput='true' LocalTooltip='[@CEHUDFieldTurrets]' Location='4,0' Name='Icon' ScrollExtent='14,14' Size='14,14' Style='/Icons.Map.Equipment.portable_manned_turret_icon' Tooltip='@CEHUDFieldTurrets'/>
<Image Color='#000000' Location='5,1' Name='IconShadow' Opacity='0.750' ScrollExtent='14,14' Size='14,14' Style='/Icons.Map.Equipment.portable_manned_turret_icon'/>
<Text Font='/Fonts.HudFont1' GetsInput='false' LocalText='5/5' Location='18,0' Margin='0,0,1,0' Name='Text' PackLocation='top,right' PackLocationProp='0018/0001,-015/0001' PackSize='absolute,absolute' PackSizeProp='0022/0001,0000/0001' ScrollExtent='38,15' ShadowStyle='/Shadows.Default' Size='38,15' TextAlignment='Right' TextAlignmentVertical='Center'>5/5</Text>
</Page>
<Page BackgroundColor='#0000FF' Location='2,172' MaximumSize='60,15' MinimumSize='60,15' Name='ShieldGenerators' ScrollExtent='60,15' Size='60,15'>
<Image GetsInput='true' LocalTooltip='[@CEHUDShieldGenerators]' Location='4,0' Name='Icon' ScrollExtent='14,14' Size='14,14' Style='/Icons.Map.Equipment.deployable_shield_generator_icon' Tooltip='@CEHUDShieldGenerators'/>
<Image Color='#000000' Location='5,1' Name='IconShadow' Opacity='0.750' ScrollExtent='14,14' Size='14,14' Style='/Icons.Map.Equipment.deployable_shield_generator_icon'/>
<Text Font='/Fonts.HudFont1' GetsInput='false' LocalText='1/1' Location='18,0' Margin='0,0,1,0' Name='Text' PackLocation='top,right' PackLocationProp='0018/0001,-015/0001' PackSize='absolute,absolute' PackSizeProp='0022/0001,0000/0001' ScrollExtent='38,15' ShadowStyle='/Shadows.Default' Size='38,15' TextAlignment='Right' TextAlignmentVertical='Center'>1/1</Text>
</Page>
</VolumePage>
</Page>
