<Page Activated='true' Location='40,543' movable='true' Name='VehicleIcons' Opacity='0.800' PackLocation='left,bottom' PackLocationProp='0040/0001,-225/0001' ScrollExtent='190,140' Size='190,140'>
<Page isvehiclepage='true' Name='galaxy_gunship' ScrollExtent='144,140' Size='144,140' Visible='false'>
<Button Color='#F3E138' Location='68,26' mountpointname='Driver' Name='Driver' ScrollExtent='8,8' Size='8,8' stretch='false' Style='Occupant'></Button>
<Button Color='#F3E138' Location='54,29' mountpointname='GunnerA' Name='GunnerA' ScrollExtent='24,24' Size='24,24' stretch='false' Style='Gunner'></Button>
<Button Color='#F3E138' Location='66,29' mountpointname='GunnerB' Name='GunnerB' ScrollExtent='24,24' Size='24,24' stretch='false' Style='Gunner'></Button>
<Button Color='#F3E138' Location='54,51' mountpointname='GunnerD' Name='GunnerD' ScrollExtent='24,24' Size='24,24' stretch='false' Style='Gunner'></Button>
<Button Color='#F3E138' Location='66,51' mountpointname='GunnerE' Name='GunnerE' ScrollExtent='24,24' Size='24,24' stretch='false' Style='Gunner'></Button>
<Button Color='#F3E138' Location='60,100' mountpointname='gunnerC' Name='GunnerC' ScrollExtent='24,24' Size='24,24' stretch='false' Style='Gunner'></Button>
<Image Color='#F3E138' Location='68,26' mountpointname='Driver' Name='Driver' ScrollExtent='8,8' Size='8,8' Stretch='false' Style='EmptyOccupant'/>
<Image Color='#F3E138' Location='62,37' mountpointname='GunnerA' Name='GunnerA' ScrollExtent='8,8' Size='8,8' Stretch='false' Style='EmptyOccupant'/>
<Image Color='#F3E138' Location='74,37' mountpointname='GunnerB' Name='GunnerB' ScrollExtent='8,8' Size='8,8' Stretch='false' Style='EmptyOccupant'/>
<Image Color='#F3E138' Location='62,59' mountpointname='GunnerD' Name='GunnerD' ScrollExtent='8,8' Size='8,8' Stretch='false' Style='EmptyOccupant'/>
<Image Color='#F3E138' Location='74,59' mountpointname='GunnerE' Name='GunnerE' ScrollExtent='8,8' Size='8,8' Stretch='false' Style='EmptyOccupant'/>
<Image Color='#F3E138' Location='68,108' mountpointname='gunnerC' Name='GunnerC' ScrollExtent='8,8' Size='8,8' Stretch='false' Style='EmptyOccupant'/>
<Progressbar BackgroundColor='#FF0000' BarBackgroundColor='#00F2C9' GetsInput='false' Location='20,20' Name='Progress' Progress='0.600' ScrollExtent='104,100' Size='104,100' Style='/ProgressBars.gunship.style'/>
<Ellipse AbsorbsInput='false' BackgroundOpacity='1.000' Color='#0099C5' Enabled='false' InnerRadiusColor='#0099C5' InnerRadiusOpacity='0.000' maxthickness='50.0' Name='Shield' Opacity='0.750' ScrollExtent='144,140' Size='144,140' Thickness='50.000'/>
</Page>
<Page isvehiclepage='true' Name='phantasm' ScrollExtent='124,140' Size='124,140' Visible='false'>
<Button Color='#F3E138' Location='57,36' mountpointname='Driver' Name='Driver' ScrollExtent='8,8' Size='8,8' stretch='false' Style='Occupant'></Button>
<Button Color='#F3E138' Location='41,55' mountpointname='PassengerA' Name='PassengerA' ScrollExtent='8,8' Size='8,8' stretch='false' Style='Occupant' Visible='false'></Button>
<Button Color='#F3E138' Location='74,55' mountpointname='PassengerB' Name='PassengerB' ScrollExtent='8,8' Size='8,8' stretch='false' Style='Occupant' Visible='false'></Button>
<Button Color='#F3E138' Location='49,76' mountpointname='PassengerC' Name='PassengerC' ScrollExtent='8,8' Size='8,8' stretch='false' Style='Occupant' Visible='false'></Button>
<Button Color='#F3E138' Location='66,76' mountpointname='PassengerD' Name='PassengerD' ScrollExtent='8,8' Size='8,8' stretch='false' Style='Occupant' Visible='false'></Button>
<Image Color='#F3E138' Location='57,36' mountpointname='Driver' Name='Driver' ScrollExtent='8,8' Size='8,8' Stretch='false' Style='EmptyOccupant'/>
<Image Color='#F3E138' Location='41,55' mountpointname='PassengerA' Name='PassengerA' ScrollExtent='8,8' Size='8,8' Stretch='false' Style='EmptyOccupant'/>
<Image Color='#F3E138' Location='74,55' mountpointname='PassengerB' Name='PassengerB' ScrollExtent='8,8' Size='8,8' Stretch='false' Style='EmptyOccupant'/>
<Image Color='#F3E138' Location='49,76' mountpointname='PassengerC' Name='PassengerC' ScrollExtent='8,8' Size='8,8' Stretch='false' Style='EmptyOccupant'/>
<Image Color='#F3E138' Location='66,76' mountpointname='PassengerD' Name='PassengerD' ScrollExtent='8,8' Size='8,8' Stretch='false' Style='EmptyOccupant'/>
<Progressbar BackgroundColor='#FF0000' BarBackgroundColor='#00F2C9' GetsInput='false' Location='20,20' Name='Progress' Progress='0.600' ScrollExtent='83,97' Size='83,97' Style='/ProgressBars.phantasm.style'/>
<Ellipse AbsorbsInput='false' BackgroundOpacity='1.000' Color='#0099C5' Enabled='false' InnerRadiusColor='#0099C5' InnerRadiusOpacity='0.000' maxthickness='50.0' Name='Shield' Opacity='0.750' ScrollExtent='123,140' Size='123,140' Thickness='50.000'/>
</Page>
<Page isvehiclepage='true' Name='apc_vs' ScrollExtent='85,140' Size='85,140' Visible='false'>
<Button Color='#F3E138' LocalTooltip='Bob' Location='38,33' mountpointname='Driver' Name='Driver' ScrollExtent='8,8' Size='8,8' stretch='false' Style='Occupant' Tooltip='Bob'></Button>
<Button Color='#F3E138' Location='19,48' mountpointname='GunnerA' Name='GunnerA' ScrollExtent='24,24' Size='24,24' stretch='false' Style='Gunner'></Button>
<Button Color='#F3E138' Location='41,48' mountpointname='GunnerB' Name='GunnerB' ScrollExtent='24,24' Size='24,24' stretch='false' Style='Gunner'></Button>
<Button Color='#F3E138' Location='29,70' mountpointname='PassengerA' Name='PassengerA' ScrollExtent='8,8' Size='8,8' stretch='false' Style='Occupant'></Button>
<Button Color='#F3E138' Location='47,70' mountpointname='PassengerB' Name='PassengerB' ScrollExtent='8,8' Size='8,8' stretch='false' Style='Occupant'></Button>
<Button Color='#F3E138' Location='21,75' mountpointname='gunnerc' Name='GunnerC' ScrollExtent='24,24' Size='24,24' stretch='false' Style='Gunner'></Button>
<Button Color='#F3E138' Location='39,75' mountpointname='gunnerd' Name='GunnerD' ScrollExtent='24,24' Size='24,24' stretch='false' Style='Gunner'></Button>
<Button Color='#F3E138' Location='21,88' mountpointname='GunnerE' Name='GunnerE' RStyleDefault='OccupantStyle' ScrollExtent='24,24' Size='24,24' stretch='false' Style='Gunner'></Button>
<Button Color='#F3E138' Location='39,88' mountpointname='GunnerF' Name='GunnerF' ScrollExtent='24,24' Size='24,24' stretch='false' Style='Gunner'></Button>
<Button Color='#F3E138' Location='29,109' mountpointname='PassengerG' Name='HeavyA' ScrollExtent='8,8' Size='8,8' stretch='false' Style='Occupant'></Button>
<Button Color='#F3E138' Location='47,109' mountpointname='PassengerH' Name='HeavyB' ScrollExtent='8,8' Size='8,8' stretch='false' Style='Occupant'></Button>
<Image Color='#F3E138' LocalTooltip='Bob' Location='38,33' mountpointname='Driver' Name='Driver' ScrollExtent='8,8' Size='8,8' Stretch='false' Style='EmptyOccupant' Tooltip='Bob'/>
<Image Color='#F3E138' Location='27,56' mountpointname='GunnerA' Name='GunnerA' ScrollExtent='8,8' Size='8,8' Stretch='false' Style='EmptyOccupant'/>
<Image Color='#F3E138' Location='49,56' mountpointname='GunnerB' Name='GunnerB' ScrollExtent='8,8' Size='8,8' Stretch='false' Style='EmptyOccupant'/>
<Image Color='#F3E138' Location='29,70' mountpointname='PassengerA' Name='PassengerA' ScrollExtent='8,8' Size='8,8' Stretch='false' Style='EmptyOccupant'/>
<Image Color='#F3E138' Location='47,70' mountpointname='PassengerB' Name='PassengerB' ScrollExtent='8,8' Size='8,8' Stretch='false' Style='EmptyOccupant'/>
<Image Color='#F3E138' Location='29,83' mountpointname='gunnerc' Name='GunnerC' ScrollExtent='8,8' Size='8,8' Stretch='false' Style='EmptyOccupant'/>
<Image Color='#F3E138' Location='47,83' mountpointname='gunnerd' Name='GunnerD' ScrollExtent='8,8' Size='8,8' Stretch='false' Style='EmptyOccupant'/>
<Image Color='#F3E138' Location='29,96' mountpointname='GunnerE' Name='GunnerE' RStyleDefault='OccupantStyle' ScrollExtent='8,8' Size='8,8' Stretch='false' Style='EmptyOccupant'/>
<Image Color='#F3E138' Location='47,96' mountpointname='GunnerF' Name='GunnerF' ScrollExtent='8,8' Size='8,8' Stretch='false' Style='EmptyOccupant'/>
<Image Color='#F3E138' Location='29,109' mountpointname='PassengerG' Name='HeavyA' ScrollExtent='8,8' Size='8,8' Stretch='false' Style='EmptyOccupant'/>
<Image Color='#F3E138' Location='47,109' mountpointname='PassengerH' Name='HeavyB' ScrollExtent='8,8' Size='8,8' Stretch='false' Style='EmptyOccupant'/>
<Progressbar BackgroundColor='#FF0000' BarBackgroundColor='#00F2C9' GetsInput='false' Location='20,20' Name='Progress' Progress='0.600' ScrollExtent='45,100' Size='45,100' Style='/ProgressBars.apc.style'/>
<Ellipse AbsorbsInput='false' BackgroundOpacity='1.000' Color='#0099C5' Enabled='false' InnerRadiusColor='#0099C5' InnerRadiusOpacity='0.000' maxthickness='50.0' Name='Shield' Opacity='0.750' ScrollExtent='85,140' Size='85,140' Thickness='50.000'/>
</Page>
<Page isvehiclepage='true' Name='apc_tr' ScrollExtent='85,140' Size='85,140' Visible='false'>
<Button Color='#F3E138' LocalTooltip='Bob' Location='38,33' mountpointname='Driver' Name='Driver' ScrollExtent='8,8' Size='8,8' stretch='false' Style='Occupant' Tooltip='Bob'></Button>
<Button Color='#F3E138' Location='19,48' mountpointname='GunnerA' Name='GunnerA' ScrollExtent='24,24' Size='24,24' stretch='false' Style='Gunner'></Button>
<Button Color='#F3E138' Location='41,48' mountpointname='GunnerB' Name='GunnerB' ScrollExtent='24,24' Size='24,24' stretch='false' Style='Gunner'></Button>
<Button Color='#F3E138' Location='29,70' mountpointname='PassengerA' Name='PassengerA' ScrollExtent='8,8' Size='8,8' stretch='false' Style='Occupant'></Button>
<Button Color='#F3E138' Location='47,70' mountpointname='PassengerB' Name='PassengerB' ScrollExtent='8,8' Size='8,8' stretch='false' Style='Occupant'></Button>
<Button Color='#F3E138' Location='21,75' mountpointname='gunnerc' Name='GunnerC' ScrollExtent='24,24' Size='24,24' stretch='false' Style='Gunner'></Button>
<Button Color='#F3E138' Location='39,75' mountpointname='gunnerd' Name='GunnerD' ScrollExtent='24,24' Size='24,24' stretch='false' Style='Gunner'></Button>
<Button Color='#F3E138' Location='21,88' mountpointname='GunnerE' Name='GunnerE' RStyleDefault='OccupantStyle' ScrollExtent='24,24' Size='24,24' stretch='false' Style='Gunner'></Button>
<Button Color='#F3E138' Location='39,88' mountpointname='GunnerF' Name='GunnerF' ScrollExtent='24,24' Size='24,24' stretch='false' Style='Gunner'></Button>
<Button Color='#F3E138' Location='29,109' mountpointname='PassengerG' Name='HeavyA' ScrollExtent='8,8' Size='8,8' stretch='false' Style='Occupant'></Button>
<Button Color='#F3E138' Location='47,109' mountpointname='PassengerH' Name='HeavyB' ScrollExtent='8,8' Size='8,8' stretch='false' Style='Occupant'></Button>
<Image Color='#F3E138' LocalTooltip='Bob' Location='38,33' mountpointname='Driver' Name='Driver' ScrollExtent='8,8' Size='8,8' Stretch='false' Style='EmptyOccupant' Tooltip='Bob'/>
<Image Color='#F3E138' Location='27,56' mountpointname='GunnerA' Name='GunnerA' ScrollExtent='8,8' Size='8,8' Stretch='false' Style='EmptyOccupant'/>
<Image Color='#F3E138' Location='49,56' mountpointname='GunnerB' Name='GunnerB' ScrollExtent='8,8' Size='8,8' Stretch='false' Style='EmptyOccupant'/>
<Image Color='#F3E138' Location='29,70' mountpointname='PassengerA' Name='PassengerA' ScrollExtent='8,8' Size='8,8' Stretch='false' Style='EmptyOccupant'/>
<Image Color='#F3E138' Location='47,70' mountpointname='PassengerB' Name='PassengerB' ScrollExtent='8,8' Size='8,8' Stretch='false' Style='EmptyOccupant'/>
<Image Color='#F3E138' Location='29,83' mountpointname='gunnerc' Name='GunnerC' ScrollExtent='8,8' Size='8,8' Stretch='false' Style='EmptyOccupant'/>
<Image Color='#F3E138' Location='47,83' mountpointname='gunnerd' Name='GunnerD' ScrollExtent='8,8' Size='8,8' Stretch='false' Style='EmptyOccupant'/>
<Image Color='#F3E138' Location='29,96' mountpointname='GunnerE' Name='GunnerE' RStyleDefault='OccupantStyle' ScrollExtent='8,8' Size='8,8' Stretch='false' Style='EmptyOccupant'/>
<Image Color='#F3E138' Location='47,96' mountpointname='GunnerF' Name='GunnerF' ScrollExtent='8,8' Size='8,8' Stretch='false' Style='EmptyOccupant'/>
<Image Color='#F3E138' Location='29,109' mountpointname='PassengerG' Name='HeavyA' ScrollExtent='8,8' Size='8,8' Stretch='false' Style='EmptyOccupant'/>
<Image Color='#F3E138' Location='47,109' mountpointname='PassengerH' Name='HeavyB' ScrollExtent='8,8' Size='8,8' Stretch='false' Style='EmptyOccupant'/>
<Progressbar BackgroundColor='#FF0000' BarBackgroundColor='#00F2C9' GetsInput='false' Location='20,20' Name='Progress' Progress='0.600' ScrollExtent='45,100' Size='45,100' Style='/ProgressBars.apc.style'/>
<Ellipse AbsorbsInput='false' BackgroundOpacity='1.000' Color='#0099C5' Enabled='false' InnerRadiusColor='#0099C5' InnerRadiusOpacity='0.000' maxthickness='50.0' Name='Shield' Opacity='0.750' ScrollExtent='85,140' Size='85,140' Thickness='50.000'/>
</Page>
<Page isvehiclepage='true' Name='apc_nc' ScrollExtent='85,140' Size='85,140' Visible='false'>
<Button Color='#F3E138' LocalTooltip='Bob' Location='38,33' mountpointname='Driver' Name='Driver' ScrollExtent='8,8' Size='8,8' stretch='false' Style='Occupant' Tooltip='Bob'></Button>
<Button Color='#F3E138' Location='19,48' mountpointname='GunnerA' Name='GunnerA' ScrollExtent='24,24' Size='24,24' stretch='false' Style='Gunner'></Button>
<Button Color='#F3E138' Location='41,48' mountpointname='GunnerB' Name='GunnerB' ScrollExtent='24,24' Size='24,24' stretch='false' Style='Gunner'></Button>
<Button Color='#F3E138' Location='29,70' mountpointname='PassengerA' Name='PassengerA' ScrollExtent='8,8' Size='8,8' stretch='false' Style='Occupant'></Button>
<Button Color='#F3E138' Location='47,70' mountpointname='PassengerB' Name='PassengerB' ScrollExtent='8,8' Size='8,8' stretch='false' Style='Occupant'></Button>
<Button Color='#F3E138' Location='21,75' mountpointname='gunnerc' Name='GunnerC' ScrollExtent='24,24' Size='24,24' stretch='false' Style='Gunner'></Button>
<Button Color='#F3E138' Location='39,75' mountpointname='gunnerd' Name='GunnerD' ScrollExtent='24,24' Size='24,24' stretch='false' Style='Gunner'></Button>
<Button Color='#F3E138' Location='21,88' mountpointname='GunnerE' Name='GunnerE' RStyleDefault='OccupantStyle' ScrollExtent='24,24' Size='24,24' stretch='false' Style='Gunner'></Button>
<Button Color='#F3E138' Location='39,88' mountpointname='GunnerF' Name='GunnerF' ScrollExtent='24,24' Size='24,24' stretch='false' Style='Gunner'></Button>
<Button Color='#F3E138' Location='29,109' mountpointname='PassengerG' Name='HeavyA' ScrollExtent='8,8' Size='8,8' stretch='false' Style='Occupant'></Button>
<Button Color='#F3E138' Location='47,109' mountpointname='PassengerH' Name='HeavyB' ScrollExtent='8,8' Size='8,8' stretch='false' Style='Occupant'></Button>
<Image Color='#F3E138' LocalTooltip='Bob' Location='38,33' mountpointname='Driver' Name='Driver' ScrollExtent='8,8' Size='8,8' Stretch='false' Style='EmptyOccupant' Tooltip='Bob'/>
<Image Color='#F3E138' Location='27,56' mountpointname='GunnerA' Name='GunnerA' ScrollExtent='8,8' Size='8,8' Stretch='false' Style='EmptyOccupant'/>
<Image Color='#F3E138' Location='49,56' mountpointname='GunnerB' Name='GunnerB' ScrollExtent='8,8' Size='8,8' Stretch='false' Style='EmptyOccupant'/>
<Image Color='#F3E138' Location='29,70' mountpointname='PassengerA' Name='PassengerA' ScrollExtent='8,8' Size='8,8' Stretch='false' Style='EmptyOccupant'/>
<Image Color='#F3E138' Location='47,70' mountpointname='PassengerB' Name='PassengerB' ScrollExtent='8,8' Size='8,8' Stretch='false' Style='EmptyOccupant'/>
<Image Color='#F3E138' Location='29,83' mountpointname='gunnerc' Name='GunnerC' ScrollExtent='8,8' Size='8,8' Stretch='false' Style='EmptyOccupant'/>
<Image Color='#F3E138' Location='47,83' mountpointname='gunnerd' Name='GunnerD' ScrollExtent='8,8' Size='8,8' Stretch='false' Style='EmptyOccupant'/>
<Image Color='#F3E138' Location='29,96' mountpointname='GunnerE' Name='GunnerE' RStyleDefault='OccupantStyle' ScrollExtent='8,8' Size='8,8' Stretch='false' Style='EmptyOccupant'/>
<Image Color='#F3E138' Location='47,96' mountpointname='GunnerF' Name='GunnerF' ScrollExtent='8,8' Size='8,8' Stretch='false' Style='EmptyOccupant'/>
<Image Color='#F3E138' Location='29,109' mountpointname='PassengerG' Name='HeavyA' ScrollExtent='8,8' Size='8,8' Stretch='false' Style='EmptyOccupant'/>
<Image Color='#F3E138' Location='47,109' mountpointname='PassengerH' Name='HeavyB' ScrollExtent='8,8' Size='8,8' Stretch='false' Style='EmptyOccupant'/>
<Progressbar BackgroundColor='#FF0000' BarBackgroundColor='#00F2C9' GetsInput='false' Location='20,20' Name='Progress' Progress='0.600' ScrollExtent='45,100' Size='45,100' Style='/ProgressBars.apc.style'/>
<Ellipse AbsorbsInput='false' BackgroundOpacity='1.000' Color='#0099C5' Enabled='false' InnerRadiusColor='#0099C5' InnerRadiusOpacity='0.000' maxthickness='50.0' Name='Shield' Opacity='0.750' ScrollExtent='85,140' Size='85,140' Thickness='50.000'/>
</Page>
<Page isvehiclepage='true' Name='portable_manned_turret_vs' ScrollExtent='140,140' Size='140,140' Visible='false'>
<Progressbar BackgroundColor='#FF0000' BarBackgroundColor='#00F2C9' GetsInput='false' Location='24,25' Name='Progress' Progress='0.700' ScrollExtent='100,102' Size='100,102' Style='/ProgressBars.fieldturret.style'/>
<Ellipse AbsorbsInput='false' BackgroundOpacity='1.000' Color='#0099C5' Enabled='false' InnerRadiusColor='#0099C5' InnerRadiusOpacity='0.000' maxthickness='50.0' Name='Shield' Opacity='0.750' ScrollExtent='140,140' Size='140,140' Thickness='50.000'/>
</Page>
<Page isvehiclepage='true' Name='portable_manned_turret_nc' ScrollExtent='140,140' Size='140,140' Visible='false'>
<Progressbar BackgroundColor='#FF0000' BarBackgroundColor='#00F2C9' GetsInput='false' Location='24,25' Name='Progress' Progress='0.700' ScrollExtent='100,102' Size='100,102' Style='/ProgressBars.fieldturret.style'/>
<Ellipse AbsorbsInput='false' BackgroundOpacity='1.000' Color='#0099C5' Enabled='false' InnerRadiusColor='#0099C5' InnerRadiusOpacity='0.000' maxthickness='50.0' Name='Shield' Opacity='0.750' ScrollExtent='140,140' Size='140,140' Thickness='50.000'/>
</Page>
<Page isvehiclepage='true' Name='portable_manned_turret_tr' ScrollExtent='140,140' Size='140,140' Visible='false'>
<Progressbar BackgroundColor='#FF0000' BarBackgroundColor='#00F2C9' GetsInput='false' Location='24,25' Name='Progress' Progress='0.700' ScrollExtent='100,102' Size='100,102' Style='/ProgressBars.fieldturret.style'/>
<Ellipse AbsorbsInput='false' BackgroundOpacity='1.000' Color='#0099C5' Enabled='false' InnerRadiusColor='#0099C5' InnerRadiusOpacity='0.000' maxthickness='50.0' Name='Shield' Opacity='0.750' ScrollExtent='140,140' Size='140,140' Thickness='50.000'/>
</Page>
<Page isvehiclepage='true' Name='portable_manned_turret' ScrollExtent='140,140' Size='140,140' Visible='false'>
<Progressbar BackgroundColor='#FF0000' BarBackgroundColor='#00F2C9' GetsInput='false' Location='20,20' Name='Progress' Progress='0.700' ScrollExtent='100,102' Size='100,102' Style='/ProgressBars.fieldturret.style'/>
<Ellipse AbsorbsInput='false' BackgroundOpacity='1.000' Color='#0099C5' Enabled='false' InnerRadiusColor='#0099C5' InnerRadiusOpacity='0.000' maxthickness='50.0' Name='Shield' Opacity='0.750' ScrollExtent='140,140' Size='140,140' Thickness='50.000'/>
</Page>
<ImageStyle Name='GunOccupant'>
<ImageFrame Source='ui_turretdir' SourceRect='0,0,32,32'/>
</ImageStyle>
<ImageStyle Name='FullOccupant'>
<ImageFrame Source='ui_vehicle_occupant_00' SourceRect='0,0,8,8'/>
</ImageStyle>
<ImageStyle Name='EmptyOccupant'>
<ImageFrame Source='ui_vehicle_occupant_00' SourceRect='8,0,16,8'/>
</ImageStyle>
<RectangleStyle Center='FullOccupant' Name='ROccupant'/>
<RectangleStyle Center='GunOccupant' CenterShrinkH='true' CenterShrinkV='true' Name='RGunner'/>
<ButtonStyle MouseOverSound='interface_feedback_rollover.wav' Name='Occupant' RStyleDefault='ROccupant'/>
<ButtonStyle MouseOverSound='interface_feedback_rollover.wav' Name='Gunner' RStyleDefault='RGunner'/>
<Page isvehiclepage='true' Name='ams' PackLocation='center,center' PackLocationProp='-095/0001,-070/0001' ScrollExtent='78,140' Size='78,140' Visible='false'>
<Progressbar BackgroundColor='#FF0000' BarBackgroundColor='#00F2C9' GetsInput='false' Location='18,20' Name='Progress' Progress='0.800' ScrollExtent='38,100' Size='38,100' Style='/ProgressBars.ams.style'/>
<Ellipse AbsorbsInput='false' BackgroundOpacity='1.000' Color='#0099C5' Enabled='false' InnerRadiusColor='#0099C5' InnerRadiusOpacity='0.000' maxthickness='50.0' Name='Shield' Opacity='0.750' ScrollExtent='78,140' Size='78,140' Thickness='50.000'/>
</Page>
<Page isvehiclepage='true' Name='ant' PackLocation='center,center' PackLocationProp='-095/0001,-070/0001' ScrollExtent='96,140' Size='96,140' Visible='false'>
<Progressbar BackgroundColor='#FF0000' BarBackgroundColor='#00F2C9' GetsInput='false' Location='20,20' Name='Progress' Progress='0.800' ScrollExtent='56,100' Size='56,100' Style='/ProgressBars.ant.style'/>
<Ellipse AbsorbsInput='false' BackgroundOpacity='1.000' Color='#0099C5' Enabled='false' InnerRadiusColor='#0099C5' InnerRadiusOpacity='0.000' maxthickness='50.0' Name='Shield' Opacity='0.750' ScrollExtent='96,140' Size='96,140' Thickness='50.000'/>
</Page>
<Page isvehiclepage='true' Name='apc' ScrollExtent='85,140' Size='85,140' Visible='false'>
<Button Color='#F3E138' LocalTooltip='Bob' Location='38,33' mountpointname='Driver' Name='Driver' ScrollExtent='8,8' Size='8,8' stretch='false' Style='Occupant' Tooltip='Bob'></Button>
<Button Color='#F3E138' Location='19,48' mountpointname='GunnerA' Name='GunnerA' ScrollExtent='24,24' Size='24,24' stretch='false' Style='Gunner'></Button>
<Button Color='#F3E138' Location='41,48' mountpointname='GunnerB' Name='GunnerB' ScrollExtent='24,24' Size='24,24' stretch='false' Style='Gunner'></Button>
<Button Color='#F3E138' Location='29,70' mountpointname='PassengerA' Name='PassengerA' ScrollExtent='8,8' Size='8,8' stretch='false' Style='Occupant'></Button>
<Button Color='#F3E138' Location='47,70' mountpointname='PassengerB' Name='PassengerB' ScrollExtent='8,8' Size='8,8' stretch='false' Style='Occupant'></Button>
<Button Color='#F3E138' Location='21,75' mountpointname='gunnerc' Name='GunnerC' ScrollExtent='24,24' Size='24,24' stretch='false' Style='Gunner'></Button>
<Button Color='#F3E138' Location='39,75' mountpointname='gunnerd' Name='GunnerD' ScrollExtent='24,24' Size='24,24' stretch='false' Style='Gunner'></Button>
<Button Color='#F3E138' Location='21,88' mountpointname='GunnerE' Name='GunnerE' RStyleDefault='OccupantStyle' ScrollExtent='24,24' Size='24,24' stretch='false' Style='Gunner'></Button>
<Button Color='#F3E138' Location='39,88' mountpointname='GunnerF' Name='GunnerF' ScrollExtent='24,24' Size='24,24' stretch='false' Style='Gunner'></Button>
<Button Color='#F3E138' Location='29,109' mountpointname='PassengerG' Name='HeavyA' ScrollExtent='8,8' Size='8,8' stretch='false' Style='Occupant'></Button>
<Button Color='#F3E138' Location='47,109' mountpointname='PassengerH' Name='HeavyB' ScrollExtent='8,8' Size='8,8' stretch='false' Style='Occupant'></Button>
<Image Color='#F3E138' LocalTooltip='Bob' Location='38,33' mountpointname='Driver' Name='Driver' ScrollExtent='8,8' Size='8,8' Stretch='false' Style='EmptyOccupant' Tooltip='Bob'/>
<Image Color='#F3E138' Location='27,56' mountpointname='GunnerA' Name='GunnerA' ScrollExtent='8,8' Size='8,8' Stretch='false' Style='EmptyOccupant'/>
<Image Color='#F3E138' Location='49,56' mountpointname='GunnerB' Name='GunnerB' ScrollExtent='8,8' Size='8,8' Stretch='false' Style='EmptyOccupant'/>
<Image Color='#F3E138' Location='29,70' mountpointname='PassengerA' Name='PassengerA' ScrollExtent='8,8' Size='8,8' Stretch='false' Style='EmptyOccupant'/>
<Image Color='#F3E138' Location='47,70' mountpointname='PassengerB' Name='PassengerB' ScrollExtent='8,8' Size='8,8' Stretch='false' Style='EmptyOccupant'/>
<Image Color='#F3E138' Location='29,83' mountpointname='gunnerc' Name='GunnerC' ScrollExtent='8,8' Size='8,8' Stretch='false' Style='EmptyOccupant'/>
<Image Color='#F3E138' Location='47,83' mountpointname='gunnerd' Name='GunnerD' ScrollExtent='8,8' Size='8,8' Stretch='false' Style='EmptyOccupant'/>
<Image Color='#F3E138' Location='29,96' mountpointname='GunnerE' Name='GunnerE' RStyleDefault='OccupantStyle' ScrollExtent='8,8' Size='8,8' Stretch='false' Style='EmptyOccupant'/>
<Image Color='#F3E138' Location='47,96' mountpointname='GunnerF' Name='GunnerF' ScrollExtent='8,8' Size='8,8' Stretch='false' Style='EmptyOccupant'/>
<Image Color='#F3E138' Location='29,109' mountpointname='PassengerG' Name='HeavyA' ScrollExtent='8,8' Size='8,8' Stretch='false' Style='EmptyOccupant'/>
<Image Color='#F3E138' Location='47,109' mountpointname='PassengerH' Name='HeavyB' ScrollExtent='8,8' Size='8,8' Stretch='false' Style='EmptyOccupant'/>
<Progressbar BackgroundColor='#FF0000' BarBackgroundColor='#00F2C9' GetsInput='false' Location='20,20' Name='Progress' Progress='0.600' ScrollExtent='45,100' Size='45,100' Style='/ProgressBars.apc.style'/>
<Ellipse AbsorbsInput='false' BackgroundOpacity='1.000' Color='#0099C5' Enabled='false' InnerRadiusColor='#0099C5' InnerRadiusOpacity='0.000' maxthickness='50.0' Name='Shield' Opacity='0.750' ScrollExtent='85,140' Size='85,140' Thickness='50.000'/>
</Page>
<Page isvehiclepage='true' Name='aphelion' ScrollExtent='100,140' Size='100,140' Visible='false'>
<Image AbsorbsInput='false' Color='#F3E138' GetsInput='true' LocalTooltip='[@BFRHitLocationFlightPack]' Location='38,98' mountpointname='Driver' Name='FlightPack' ScrollExtent='24,18' Size='24,18' Style='/Icons.HUD.Misc.bfr_flight_pack' Tooltip='@BFRHitLocationFlightPack'/>
<Image AbsorbsInput='false' Color='#F3E138' GetsInput='true' LocalTooltip='[@BFRHitLocationMovement]' Location='65,118' mountpointname='Driver' Name='MovementServos' ScrollExtent='21,21' Size='21,21' Style='/Icons.HUD.Misc.bfr_movement_servos' Tooltip='@BFRHitLocationMovement'/>
<Image AbsorbsInput='false' Color='#F3E138' GetsInput='true' LocalTooltip='[@BFRHitLocationSensors]' Location='43,118' mountpointname='Driver' Name='Sensors' ScrollExtent='15,20' Size='15,20' Style='/Icons.HUD.Misc.bfr_sensors' Tooltip='@BFRHitLocationSensors'/>
<Image AbsorbsInput='false' Color='#00FF00' GetsInput='true' LocalTooltip='[@BFRHitLocationShieldGenerator]' Location='16,122' mountpointname='Driver' Name='ShieldGenerator' ScrollExtent='20,13' Size='20,13' Style='/Icons.HUD.Misc.bfr_shield_generator' Tooltip='@BFRHitLocationShieldGenerator'/>
<Button Color='#F3E138' LocalTooltip='hhh' Location='0,59' mountpointname='Driver' Name='LeftWeapon' ScrollExtent='24,24' Size='24,24' stretch='false' Style='Gunner' Tooltip='hhh'></Button>
<Button Color='#F3E138' Location='76,59' mountpointname='Driver' Name='RightWeapon' ScrollExtent='24,24' Size='24,24' stretch='false' Style='Gunner'></Button>
<Button Color='#F3E138' Location='46,46' mountpointname='Driver' Name='Driver' ScrollExtent='8,8' Size='8,8' stretch='false' Style='Occupant'></Button>
<Image Color='#F3E138' Location='46,46' mountpointname='Driver' Name='Driver' ScrollExtent='8,8' Size='8,8' Stretch='false' Style='EmptyOccupant'/>
<Progressbar BackgroundColor='#FF0000' BarBackgroundColor='#00F2C9' GetsInput='false' Location='3,39' Name='Progress' Progress='0.800' ScrollExtent='95,62' Size='95,62' Style='/ProgressBars.aphelion.style'/>
<Ellipse AbsorbsInput='false' BackgroundOpacity='1.000' Color='#0099C5' Enabled='false' InnerRadiusColor='#0099C5' InnerRadiusOpacity='0.000' maxthickness='50.0' Name='Shield' Opacity='0.750' ScrollExtent='100,140' Size='100,140' Thickness='50.000'/>
</Page>
<Page isvehiclepage='true' Name='aphelion_variant' ScrollExtent='100,140' Size='100,140' Visible='false'>
<Image AbsorbsInput='false' Color='#00FF00' GetsInput='true' LocalTooltip='[@BFRHitLocationShieldGenerator]' Location='16,122' mountpointname='Driver' Name='ShieldGenerator' ScrollExtent='20,13' Size='20,13' Style='/Icons.HUD.Misc.bfr_shield_generator' Tooltip='@BFRHitLocationShieldGenerator'/>
<Image AbsorbsInput='false' Color='#F3E138' GetsInput='true' LocalTooltip='[@BFRHitLocationMovement]' Location='65,118' mountpointname='Driver' Name='MovementServos' ScrollExtent='21,21' Size='21,21' Style='/Icons.HUD.Misc.bfr_movement_servos' Tooltip='@BFRHitLocationMovement'/>
<Image AbsorbsInput='false' Color='#F3E138' GetsInput='true' LocalTooltip='[@BFRHitLocationSensors]' Location='43,118' mountpointname='Driver' Name='Sensors' ScrollExtent='15,20' Size='15,20' Style='/Icons.HUD.Misc.bfr_sensors' Tooltip='@BFRHitLocationSensors'/>
<Button Color='#F3E138' Location='0,59' mountpointname='Driver' Name='LeftWeapon' ScrollExtent='24,24' Size='24,24' stretch='false' Style='Gunner'></Button>
<Button Color='#F3E138' Location='76,59' mountpointname='Driver' Name='RightWeapon' ScrollExtent='24,24' Size='24,24' stretch='false' Style='Gunner'></Button>
<Button Color='#F3E138' Location='46,46' mountpointname='Driver' Name='Driver' ScrollExtent='8,8' Size='8,8' stretch='false' Style='Occupant'></Button>
<Button Color='#F3E138' Location='38,71' mountpointname='GunnerA' Name='GunnerA' ScrollExtent='24,24' Size='24,24' stretch='false' Style='Gunner'></Button>
<Image Color='#F3E138' Location='46,46' mountpointname='Driver' Name='Driver' ScrollExtent='8,8' Size='8,8' Stretch='false' Style='EmptyOccupant'/>
<Image Color='#F3E138' Location='46,79' mountpointname='GunnerA' Name='GunnerA' ScrollExtent='8,8' Size='8,8' Stretch='false' Style='EmptyOccupant'/>
<Progressbar BackgroundColor='#FF0000' BarBackgroundColor='#00F2C9' GetsInput='false' Location='3,39' Name='Progress' Progress='0.800' ScrollExtent='95,62' Size='95,62' Style='/ProgressBars.aphelion.style'/>
<Ellipse AbsorbsInput='false' BackgroundOpacity='1.000' Color='#0099C5' Enabled='false' InnerRadiusColor='#0099C5' InnerRadiusOpacity='0.000' maxthickness='50.0' Name='Shield' Opacity='0.750' ScrollExtent='100,140' Size='100,140' Thickness='50.000'/>
</Page>
<Page isvehiclepage='true' Name='aurora' ScrollExtent='90,140' Size='90,140' Visible='false'>
<Button Color='#F3E138' Location='35,48' mountpointname='Driver' Name='Driver' ScrollExtent='8,8' Size='8,8' stretch='false' Style='Occupant'></Button>
<Button Color='#F3E138' Location='39,40' mountpointname='GunnerA' Name='GunnerA' ScrollExtent='24,24' Size='24,24' stretch='false' Style='Gunner'></Button>
<Button Color='#F3E138' Location='28,82' mountpointname='GunnerB' Name='GunnerB' ScrollExtent='24,24' Size='24,24' stretch='false' Style='Gunner'></Button>
<Button Color='#F3E138' Location='35,69' mountpointname='PassengerA' Name='PassengerA' ScrollExtent='8,8' Size='8,8' stretch='false' Style='Occupant'></Button>
<Button Color='#F3E138' Location='47,69' mountpointname='PassengerB' Name='PassengerB' ScrollExtent='8,8' Size='8,8' stretch='false' Style='Occupant'></Button>
<Image Color='#F3E138' Location='35,48' mountpointname='Driver' Name='Driver' ScrollExtent='8,8' Size='8,8' Stretch='false' Style='EmptyOccupant'/>
<Image Color='#F3E138' Location='47,48' mountpointname='GunnerA' Name='GunnerA' ScrollExtent='8,8' Size='8,8' Stretch='false' Style='EmptyOccupant'/>
<Image Color='#F3E138' Location='36,90' mountpointname='GunnerB' Name='GunnerB' ScrollExtent='8,8' Size='8,8' Stretch='false' Style='EmptyOccupant'/>
<Image Color='#F3E138' Location='35,69' mountpointname='PassengerA' Name='PassengerA' ScrollExtent='8,8' Size='8,8' Stretch='false' Style='EmptyOccupant'/>
<Image Color='#F3E138' Location='47,69' mountpointname='PassengerB' Name='PassengerB' ScrollExtent='8,8' Size='8,8' Stretch='false' Style='EmptyOccupant'/>
<Progressbar BackgroundColor='#FF0000' BarBackgroundColor='#00F2C9' GetsInput='false' Location='20,20' Name='Progress' Progress='0.800' ScrollExtent='50,100' Size='50,100' Style='/ProgressBars.mediumtransport.style'/>
<Ellipse AbsorbsInput='false' BackgroundOpacity='1.000' Color='#0099C5' Enabled='false' InnerRadiusColor='#0099C5' InnerRadiusOpacity='0.000' maxthickness='50.0' Name='Shield' Opacity='0.750' ScrollExtent='90,140' Size='90,140' Thickness='50.000'/>
</Page>
<Page isvehiclepage='true' Name='battlewagon' ScrollExtent='90,140' Size='90,140' Visible='false'>
<Button Color='#F3E138' Location='35,48' mountpointname='Driver' Name='Driver' ScrollExtent='8,8' Size='8,8' stretch='false' Style='Occupant'></Button>
<Button Color='#F3E138' Location='39,40' mountpointname='GunnerA' Name='GunnerA' ScrollExtent='24,24' Size='24,24' stretch='false' Style='Gunner'></Button>
<Button Color='#F3E138' Location='28,82' mountpointname='GunnerB' Name='GunnerB' ScrollExtent='24,24' Size='24,24' stretch='false' Style='Gunner'></Button>
<Button Color='#F3E138' Location='39,61' mountpointname='GunnerC' Name='GunnerC' ScrollExtent='24,24' Size='24,24' stretch='false' Style='Gunner'></Button>
<Button Color='#F3E138' Location='27,61' mountpointname='GunnerD' Name='GunnerD' ScrollExtent='24,24' Size='24,24' stretch='false' Style='Gunner'></Button>
<Image Color='#F3E138' Location='35,48' mountpointname='Driver' Name='Driver' ScrollExtent='8,8' Size='8,8' Stretch='false' Style='EmptyOccupant'/>
<Image Color='#F3E138' Location='47,48' mountpointname='GunnerA' Name='GunnerA' ScrollExtent='8,8' Size='8,8' Stretch='false' Style='EmptyOccupant'/>
<Image Color='#F3E138' Location='36,90' mountpointname='GunnerB' Name='GunnerB' ScrollExtent='8,8' Size='8,8' Stretch='false' Style='EmptyOccupant'/>
<Image Color='#F3E138' Location='47,69' mountpointname='GunnerC' Name='GunnerC' ScrollExtent='8,8' Size='8,8' Stretch='false' Style='EmptyOccupant'/>
<Image Color='#F3E138' Location='35,69' mountpointname='GunnerD' Name='GunnerD' ScrollExtent='8,8' Size='8,8' Stretch='false' Style='EmptyOccupant'/>
<Progressbar BackgroundColor='#FF0000' BarBackgroundColor='#00F2C9' GetsInput='false' Location='20,20' Name='Progress' Progress='0.800' ScrollExtent='50,100' Size='50,100' Style='/ProgressBars.mediumtransport.style'/>
<Ellipse AbsorbsInput='false' BackgroundOpacity='1.000' Color='#0099C5' Enabled='false' InnerRadiusColor='#0099C5' InnerRadiusOpacity='0.000' maxthickness='50.0' Name='Shield' Opacity='0.750' ScrollExtent='90,140' Size='90,140' Thickness='50.000'/>
</Page>
<Page isvehiclepage='true' Name='colossus' ScrollExtent='100,140' Size='100,140' Visible='false'>
<Image AbsorbsInput='false' Color='#00FF00' GetsInput='true' LocalTooltip='[@BFRHitLocationShieldGenerator]' Location='16,122' mountpointname='Driver' Name='ShieldGenerator' ScrollExtent='20,13' Size='20,13' Style='/Icons.HUD.Misc.bfr_shield_generator' Tooltip='@BFRHitLocationShieldGenerator'/>
<Image AbsorbsInput='false' Color='#F3E138' GetsInput='true' LocalTooltip='[@BFRHitLocationSensors]' Location='43,118' mountpointname='Driver' Name='Sensors' ScrollExtent='15,20' Size='15,20' Style='/Icons.HUD.Misc.bfr_sensors' Tooltip='@BFRHitLocationSensors'/>
<Image AbsorbsInput='false' Color='#F3E138' GetsInput='true' LocalTooltip='[@BFRHitLocationMovement]' Location='65,118' mountpointname='Driver' Name='MovementServos' ScrollExtent='21,21' Size='21,21' Style='/Icons.HUD.Misc.bfr_movement_servos' Tooltip='@BFRHitLocationMovement'/>
<Image AbsorbsInput='false' Color='#F3E138' GetsInput='true' LocalTooltip='[@BFRHitLocationFlightPack]' Location='38,97' mountpointname='Driver' Name='FlightPack' ScrollExtent='24,18' Size='24,18' Style='/Icons.HUD.Misc.bfr_flight_pack' Tooltip='@BFRHitLocationFlightPack'/>
<Button Color='#F3E138' Location='3,55' mountpointname='Driver' Name='LeftWeapon' ScrollExtent='24,24' Size='24,24' stretch='false' Style='Gunner'></Button>
<Button Color='#F3E138' Location='73,55' mountpointname='Driver' Name='RightWeapon' ScrollExtent='24,24' Size='24,24' stretch='false' Style='Gunner'></Button>
<Button Color='#F3E138' Location='46,53' mountpointname='Driver' Name='Driver' ScrollExtent='8,8' Size='8,8' stretch='false' Style='Occupant'></Button>
<Image Color='#F3E138' Location='46,53' mountpointname='Driver' Name='Driver' ScrollExtent='8,8' Size='8,8' Stretch='false' Style='EmptyOccupant'/>
<Progressbar BackgroundColor='#FF0000' BarBackgroundColor='#00F2C9' GetsInput='false' Location='6,41' Name='Progress' Progress='0.800' ScrollExtent='88,59' Size='88,59' Style='/ProgressBars.colossus.style'/>
<Ellipse AbsorbsInput='false' BackgroundOpacity='1.000' Color='#0099C5' Enabled='false' InnerRadiusColor='#0099C5' InnerRadiusOpacity='0.000' maxthickness='50.0' Name='Shield' Opacity='0.750' ScrollExtent='100,140' Size='100,140' Thickness='50.000'/>
</Page>
<Page isvehiclepage='true' Name='colossus_variant' ScrollExtent='100,140' Size='100,140' Visible='false'>
<Image AbsorbsInput='false' Color='#F3E138' GetsInput='true' LocalTooltip='[@BFRHitLocationSensors]' Location='43,118' mountpointname='Driver' Name='Sensors' ScrollExtent='15,20' Size='15,20' Style='/Icons.HUD.Misc.bfr_sensors' Tooltip='@BFRHitLocationSensors'/>
<Image AbsorbsInput='false' Color='#F3E138' GetsInput='true' LocalTooltip='[@BFRHitLocationMovement]' Location='65,118' mountpointname='Driver' Name='MovementServos' ScrollExtent='21,21' Size='21,21' Style='/Icons.HUD.Misc.bfr_movement_servos' Tooltip='@BFRHitLocationMovement'/>
<Image AbsorbsInput='false' Color='#00FF00' GetsInput='true' LocalTooltip='[@BFRHitLocationShieldGenerator]' Location='16,122' mountpointname='Driver' Name='ShieldGenerator' ScrollExtent='20,13' Size='20,13' Style='/Icons.HUD.Misc.bfr_shield_generator' Tooltip='@BFRHitLocationShieldGenerator'/>
<Button Color='#F3E138' Location='73,55' mountpointname='Driver' Name='RightWeapon' ScrollExtent='24,24' Size='24,24' stretch='false' Style='Gunner'></Button>
<Button Color='#F3E138' Location='3,55' mountpointname='Driver' Name='LeftWeapon' ScrollExtent='24,24' Size='24,24' stretch='false' Style='Gunner'></Button>
<Button Color='#F3E138' Location='46,53' mountpointname='Driver' Name='Driver' ScrollExtent='8,8' Size='8,8' stretch='false' Style='Occupant'></Button>
<Button Color='#F3E138' Location='38,72' mountpointname='GunnerA' Name='GunnerA' ScrollExtent='24,24' Size='24,24' stretch='false' Style='Gunner'></Button>
<Image Color='#F3E138' Location='46,53' mountpointname='Driver' Name='Driver' ScrollExtent='8,8' Size='8,8' Stretch='false' Style='EmptyOccupant'/>
<Image Color='#F3E138' Location='46,80' mountpointname='GunnerA' Name='GunnerA' ScrollExtent='8,8' Size='8,8' Stretch='false' Style='EmptyOccupant'/>
<Progressbar BackgroundColor='#FF0000' BarBackgroundColor='#00F2C9' GetsInput='false' Location='6,41' Name='Progress' Progress='0.800' ScrollExtent='88,59' Size='88,59' Style='/ProgressBars.colossus.style'/>
<Ellipse AbsorbsInput='false' BackgroundOpacity='1.000' Color='#0099C5' Enabled='false' InnerRadiusColor='#0099C5' InnerRadiusOpacity='0.000' maxthickness='50.0' Name='Shield' Opacity='0.750' ScrollExtent='100,140' Size='100,140' Thickness='50.000'/>
</Page>
<Page isvehiclepage='true' Name='dropship' ScrollExtent='144,140' Size='144,140' Visible='false'>
<Button Color='#F3E138' Location='68,26' mountpointname='Driver' Name='Driver' ScrollExtent='8,8' Size='8,8' stretch='false' Style='Occupant'></Button>
<Button Color='#F3E138' Location='54,29' mountpointname='GunnerA' Name='GunnerA' ScrollExtent='24,24' Size='24,24' stretch='false' Style='Gunner'></Button>
<Button Color='#F3E138' Location='66,29' mountpointname='GunnerB' Name='GunnerB' ScrollExtent='24,24' Size='24,24' stretch='false' Style='Gunner'></Button>
<Button Color='#F3E138' Location='62,49' mountpointname='PassengerA' Name='PassengerA' ScrollExtent='8,8' Size='8,8' stretch='false' Style='Occupant' Visible='false'></Button>
<Button Color='#F3E138' Location='74,49' mountpointname='PassengerB' Name='PassengerB' ScrollExtent='8,8' Size='8,8' stretch='false' Style='Occupant' Visible='false'></Button>
<Button Color='#F3E138' Location='62,59' mountpointname='PassengerC' Name='PassengerC' ScrollExtent='8,8' Size='8,8' stretch='false' Style='Occupant' Visible='false'></Button>
<Button Color='#F3E138' Location='74,59' mountpointname='PassengerD' Name='PassengerD' ScrollExtent='8,8' Size='8,8' stretch='false' Style='Occupant' Visible='false'></Button>
<Button Color='#F3E138' Location='62,69' mountpointname='PassengerE' Name='PassengerE' ScrollExtent='8,8' Size='8,8' stretch='false' Style='Occupant' Visible='false'></Button>
<Button Color='#F3E138' Location='74,69' mountpointname='PassengerF' Name='PassengerF' ScrollExtent='8,8' Size='8,8' stretch='false' Style='Occupant' Visible='false'></Button>
<Button Color='#F3E138' Location='62,80' mountpointname='PassengerG' Name='HeavyA' ScrollExtent='8,8' Size='8,8' stretch='false' Style='Occupant' Visible='false'></Button>
<Button Color='#F3E138' Location='74,80' mountpointname='PassengerH' Name='HeavyB' ScrollExtent='8,8' Size='8,8' stretch='false' Style='Occupant' Visible='false'></Button>
<Button Color='#F3E138' Location='68,93' mountpointname='Vehicle' Name='Vehicle' ScrollExtent='8,8' Size='8,8' stretch='false' Style='Occupant' Visible='false'></Button>
<Button Color='#F3E138' Location='60,100' mountpointname='gunnerC' Name='GunnerC' ScrollExtent='24,24' Size='24,24' stretch='false' Style='Gunner' Visible='false'></Button>
<Image Color='#F3E138' Location='68,26' mountpointname='Driver' Name='Driver' ScrollExtent='8,8' Size='8,8' Stretch='false' Style='EmptyOccupant'/>
<Image Color='#F3E138' Location='62,37' mountpointname='GunnerA' Name='GunnerA' ScrollExtent='8,8' Size='8,8' Stretch='false' Style='EmptyOccupant'/>
<Image Color='#F3E138' Location='74,37' mountpointname='GunnerB' Name='GunnerB' ScrollExtent='8,8' Size='8,8' Stretch='false' Style='EmptyOccupant'/>
<Image Color='#F3E138' Location='62,49' mountpointname='PassengerA' Name='PassengerA' ScrollExtent='8,8' Size='8,8' Stretch='false' Style='EmptyOccupant'/>
<Image Color='#F3E138' Location='74,49' mountpointname='PassengerB' Name='PassengerB' ScrollExtent='8,8' Size='8,8' Stretch='false' Style='EmptyOccupant'/>
<Image Color='#F3E138' Location='62,59' mountpointname='PassengerC' Name='PassengerC' ScrollExtent='8,8' Size='8,8' Stretch='false' Style='EmptyOccupant'/>
<Image Color='#F3E138' Location='74,59' mountpointname='PassengerD' Name='PassengerD' ScrollExtent='8,8' Size='8,8' Stretch='false' Style='EmptyOccupant'/>
<Image Color='#F3E138' Location='62,69' mountpointname='PassengerE' Name='PassengerE' ScrollExtent='8,8' Size='8,8' Stretch='false' Style='EmptyOccupant'/>
<Image Color='#F3E138' Location='74,69' mountpointname='PassengerF' Name='PassengerF' ScrollExtent='8,8' Size='8,8' Stretch='false' Style='EmptyOccupant'/>
<Image Color='#F3E138' Location='62,80' mountpointname='PassengerG' Name='HeavyA' ScrollExtent='8,8' Size='8,8' Stretch='false' Style='EmptyOccupant'/>
<Image Color='#F3E138' Location='74,80' mountpointname='PassengerH' Name='HeavyB' ScrollExtent='8,8' Size='8,8' Stretch='false' Style='EmptyOccupant'/>
<Image Color='#F3E138' Location='68,93' mountpointname='Vehicle' Name='Vehicle' ScrollExtent='8,8' Size='8,8' Stretch='false' Style='EmptyOccupant'/>
<Image Color='#F3E138' Location='68,108' mountpointname='gunnerC' Name='GunnerC' ScrollExtent='8,8' Size='8,8' Stretch='false' Style='EmptyOccupant'/>
<Progressbar BackgroundColor='#FF0000' BarBackgroundColor='#00F2C9' GetsInput='false' Location='20,20' Name='Progress' Progress='0.600' ScrollExtent='104,100' Size='104,100' Style='/ProgressBars.dropship.style'/>
<Ellipse AbsorbsInput='false' BackgroundOpacity='1.000' Color='#0099C5' Enabled='false' InnerRadiusColor='#0099C5' InnerRadiusOpacity='0.000' maxthickness='50.0' Name='Shield' Opacity='0.750' ScrollExtent='144,140' Size='144,140' Thickness='50.000'/>
</Page>
<Page isvehiclepage='true' Name='flail' PackLocation='center,center' PackLocationProp='-095/0001,-070/0001' ScrollExtent='132,140' Size='132,140' Visible='false'>
<Progressbar BackgroundColor='#FF0000' BarBackgroundColor='#00F2C9' GetsInput='false' Location='20,20' Name='Progress' Progress='0.800' ScrollExtent='92,100' Size='92,100' Style='/ProgressBars.flail.style'/>
<Ellipse AbsorbsInput='false' BackgroundOpacity='1.000' Color='#0099C5' Enabled='false' InnerRadiusColor='#0099C5' InnerRadiusOpacity='0.000' maxthickness='50.0' Name='Shield' Opacity='0.750' ScrollExtent='132,140' Size='132,140' Thickness='50.000'/>
</Page>
<Page isvehiclepage='true' Name='fury' ScrollExtent='104,140' Size='104,140' Visible='false'>
<Progressbar BackgroundColor='#FF0000' BarBackgroundColor='#00F2C9' GetsInput='false' Location='20,20' Name='Progress' Progress='0.750' ScrollExtent='64,100' Size='64,100' Style='/ProgressBars.quadassault.style'/>
<Ellipse AbsorbsInput='false' BackgroundOpacity='1.000' Color='#0099C5' Enabled='false' InnerRadiusColor='#0099C5' InnerRadiusOpacity='0.000' maxthickness='50.0' Name='Shield' Opacity='0.750' ScrollExtent='104,140' Size='104,140' Thickness='50.000'/>
</Page>
<Page isvehiclepage='true' Name='liberator' ScrollExtent='114,140' Size='114,140' Visible='false'>
<Button Color='#F3E138' Location='53,35' mountpointname='Driver' Name='Driver' ScrollExtent='8,8' Size='8,8' stretch='false' Style='Occupant'></Button>
<Button Color='#F3E138' Location='53,53' mountpointname='GunnerA' Name='GunnerA' ScrollExtent='8,8' Size='8,8' stretch='false' Style='Occupant'></Button>
<Button Color='#F3E138' Location='45,61' mountpointname='GunnerC' Name='GunnerC' ScrollExtent='24,24' Size='24,24' stretch='false' Style='Gunner'></Button>
<Image Color='#F3E138' Location='53,35' mountpointname='Driver' Name='Driver' ScrollExtent='8,8' Size='8,8' Stretch='false' Style='EmptyOccupant'/>
<Image Color='#F3E138' Location='53,53' mountpointname='GunnerA' Name='GunnerA' ScrollExtent='8,8' Size='8,8' Stretch='false' Style='EmptyOccupant'/>
<Image Color='#F3E138' Location='53,69' mountpointname='GunnerC' Name='GunnerC' ScrollExtent='8,8' Size='8,8' Stretch='false' Style='EmptyOccupant'/>
<Progressbar BackgroundColor='#FF0000' BarBackgroundColor='#00F2C9' GetsInput='false' Location='20,20' Name='Progress' Progress='0.800' ScrollExtent='74,100' Size='74,100' Style='/ProgressBars.liberator.style'/>
<Ellipse AbsorbsInput='false' BackgroundOpacity='1.000' Color='#0099C5' Enabled='false' InnerRadiusColor='#0099C5' InnerRadiusOpacity='0.000' maxthickness='50.0' Name='Shield' Opacity='0.750' ScrollExtent='114,140' Size='114,140' Thickness='50.000'/>
</Page>
<Page isvehiclepage='true' Name='lightgunship' ScrollExtent='110,140' Size='110,140' Visible='false'>
<Progressbar BackgroundColor='#FF0000' BarBackgroundColor='#00F2C9' GetsInput='false' Location='20,20' Name='Progress' Progress='0.800' ScrollExtent='70,100' Size='70,100' Style='/ProgressBars.lightgunship.style'/>
<Ellipse AbsorbsInput='false' BackgroundOpacity='1.000' Color='#0099C5' Enabled='false' InnerRadiusColor='#0099C5' InnerRadiusOpacity='0.000' maxthickness='50.0' Name='Shield' Opacity='0.750' ScrollExtent='110,140' Size='110,140' Thickness='50.000'/>
</Page>
<Page isvehiclepage='true' Name='lightning' ScrollExtent='102,140' Size='102,140' Visible='false'>
<Progressbar BackgroundColor='#FF0000' BarBackgroundColor='#00F2C9' GetsInput='false' Location='20,20' Name='Progress' Progress='0.800' ScrollExtent='62,100' Size='62,100' Style='/ProgressBars.lightning.style'/>
<Ellipse AbsorbsInput='false' BackgroundOpacity='1.000' Color='#0099C5' Enabled='false' InnerRadiusColor='#0099C5' InnerRadiusOpacity='0.000' maxthickness='50.0' Name='Shield' Opacity='0.750' ScrollExtent='102,140' Size='102,140' Thickness='50.000'/>
</Page>
<Page isvehiclepage='true' Name='lodestar' ScrollExtent='144,140' Size='144,140' Visible='false'>
<Button Color='#F3E138' Location='68,26' mountpointname='Driver' Name='Driver' ScrollExtent='8,8' Size='8,8' stretch='false' Style='Occupant'></Button>
<Button Color='#F3E138' Location='68,75' mountpointname='Vehicle' Name='Vehicle' ScrollExtent='8,8' Size='8,8' stretch='false' Style='Occupant' Visible='false'></Button>
<Image Color='#F3E138' Location='68,26' mountpointname='Driver' Name='Driver' ScrollExtent='8,8' Size='8,8' Stretch='false' Style='EmptyOccupant'/>
<Image Color='#F3E138' Location='68,75' mountpointname='Vehicle' Name='Vehicle' ScrollExtent='8,8' Size='8,8' Stretch='false' Style='EmptyOccupant'/>
<Progressbar BackgroundColor='#FF0000' BarBackgroundColor='#00F2C9' GetsInput='false' Location='20,20' Name='Progress' Progress='0.600' ScrollExtent='104,100' Size='104,100' Style='/ProgressBars.lodestar.style'/>
<Ellipse AbsorbsInput='false' BackgroundOpacity='1.000' Color='#0099C5' Enabled='false' InnerRadiusColor='#0099C5' InnerRadiusOpacity='0.000' maxthickness='50.0' Name='Shield' Opacity='0.750' ScrollExtent='144,140' Size='144,140' Thickness='50.000'/>
</Page>
<Page isvehiclepage='true' Name='magrider' ScrollExtent='90,140' Size='90,140' Visible='false'>
<Button Color='#F3E138' Location='41,56' mountpointname='Driver' Name='Driver' ScrollExtent='8,8' Size='8,8' stretch='false' Style='Occupant'></Button>
<Button Color='#F3E138' Location='33,77' mountpointname='GunnerA' Name='GunnerA' ScrollExtent='24,24' Size='24,24' stretch='false' Style='Gunner'></Button>
<Image Color='#F3E138' Location='41,56' mountpointname='Driver' Name='Driver' ScrollExtent='8,8' Size='8,8' Stretch='false' Style='EmptyOccupant'/>
<Image Color='#F3E138' Location='41,85' mountpointname='GunnerA' Name='GunnerA' ScrollExtent='8,8' Size='8,8' Stretch='false' Style='EmptyOccupant'/>
<Progressbar BackgroundColor='#FF0000' BarBackgroundColor='#00F2C9' GetsInput='false' Location='20,20' Name='Progress' Progress='0.800' ScrollExtent='50,100' Size='50,100' Style='/ProgressBars.magrider.style'/>
<Ellipse AbsorbsInput='false' BackgroundOpacity='1.000' Color='#0099C5' Enabled='false' InnerRadiusColor='#0099C5' InnerRadiusOpacity='0.000' maxthickness='50.0' Name='Shield' Opacity='0.750' ScrollExtent='90,140' Size='90,140' Thickness='50.000'/>
</Page>
<Page isvehiclepage='true' Location='0,40' Name='manned_turret' ScrollExtent='96,100' Size='96,100' Visible='false'>
<Progressbar BackgroundColor='#FF0000' BarBackgroundColor='#00F2C9' GetsInput='false' Name='Progress' Progress='0.700' ScrollExtent='96,100' Size='96,100' Style='/ProgressBars.manned_turret.style'/>
</Page>
<Page isvehiclepage='true' Name='mediumtransport' ScrollExtent='90,140' Size='90,140' Visible='false'>
<Button Color='#F3E138' Location='35,48' mountpointname='Driver' Name='Driver' ScrollExtent='8,8' Size='8,8' stretch='false' Style='Occupant'></Button>
<Button Color='#F3E138' Location='39,40' mountpointname='GunnerA' Name='GunnerA' ScrollExtent='24,24' Size='24,24' stretch='false' Style='Gunner'></Button>
<Button Color='#F3E138' Location='28,82' mountpointname='GunnerB' Name='GunnerB' ScrollExtent='24,24' Size='24,24' stretch='false' Style='Gunner'></Button>
<Button Color='#F3E138' Location='35,69' mountpointname='PassengerA' Name='PassengerA' ScrollExtent='8,8' Size='8,8' stretch='false' Style='Occupant'></Button>
<Button Color='#F3E138' Location='47,69' mountpointname='PassengerB' Name='PassengerB' ScrollExtent='8,8' Size='8,8' stretch='false' Style='Occupant'></Button>
<Image Color='#F3E138' Location='35,48' mountpointname='Driver' Name='Driver' ScrollExtent='8,8' Size='8,8' Stretch='false' Style='EmptyOccupant'/>
<Image Color='#F3E138' Location='47,48' mountpointname='GunnerA' Name='GunnerA' ScrollExtent='8,8' Size='8,8' Stretch='false' Style='EmptyOccupant'/>
<Image Color='#F3E138' Location='36,90' mountpointname='GunnerB' Name='GunnerB' ScrollExtent='8,8' Size='8,8' Stretch='false' Style='EmptyOccupant'/>
<Image Color='#F3E138' Location='35,69' mountpointname='PassengerA' Name='PassengerA' ScrollExtent='8,8' Size='8,8' Stretch='false' Style='EmptyOccupant'/>
<Image Color='#F3E138' Location='47,69' mountpointname='PassengerB' Name='PassengerB' ScrollExtent='8,8' Size='8,8' Stretch='false' Style='EmptyOccupant'/>
<Progressbar BackgroundColor='#FF0000' BarBackgroundColor='#00F2C9' GetsInput='false' Location='20,20' Name='Progress' Progress='0.800' ScrollExtent='50,100' Size='50,100' Style='/ProgressBars.mediumtransport.style'/>
<Ellipse AbsorbsInput='false' BackgroundOpacity='1.000' Color='#0099C5' Enabled='false' InnerRadiusColor='#0099C5' InnerRadiusOpacity='0.000' maxthickness='50.0' Name='Shield' Opacity='0.750' ScrollExtent='90,140' Size='90,140' Thickness='50.000'/>
</Page>
<Page isvehiclepage='true' Name='mosquito' ScrollExtent='94,140' Size='94,140' Visible='false'>
<Progressbar BackgroundColor='#FF0000' BarBackgroundColor='#00F2C9' GetsInput='false' Location='20,20' Name='Progress' Progress='0.800' ScrollExtent='54,100' Size='54,100' Style='/ProgressBars.mosquito.style'/>
<Ellipse AbsorbsInput='false' BackgroundOpacity='1.000' Color='#0099C5' Enabled='false' InnerRadiusColor='#0099C5' InnerRadiusOpacity='0.000' maxthickness='50.0' Name='Shield' Opacity='0.750' ScrollExtent='94,140' Size='94,140' Thickness='50.000'/>
</Page>
<Page isvehiclepage='true' Name='peregrine' ScrollExtent='100,140' Size='100,140' Visible='false'>
<Image AbsorbsInput='false' Color='#00FF00' GetsInput='true' LocalTooltip='[@BFRHitLocationShieldGenerator]' Location='16,122' mountpointname='Driver' Name='ShieldGenerator' ScrollExtent='20,13' Size='20,13' Style='/Icons.HUD.Misc.bfr_shield_generator' Tooltip='@BFRHitLocationShieldGenerator'/>
<Image AbsorbsInput='false' Color='#F3E138' GetsInput='true' LocalTooltip='[@BFRHitLocationSensors]' Location='43,118' mountpointname='Driver' Name='Sensors' ScrollExtent='15,20' Size='15,20' Style='/Icons.HUD.Misc.bfr_sensors' Tooltip='@BFRHitLocationSensors'/>
<Image AbsorbsInput='false' Color='#F3E138' GetsInput='true' LocalTooltip='[@BFRHitLocationMovement]' Location='65,118' mountpointname='Driver' Name='MovementServos' ScrollExtent='21,21' Size='21,21' Style='/Icons.HUD.Misc.bfr_movement_servos' Tooltip='@BFRHitLocationMovement'/>
<Image AbsorbsInput='false' Color='#F3E138' GetsInput='true' LocalTooltip='[@BFRHitLocationFlightPack]' Location='38,97' mountpointname='Driver' Name='FlightPack' ScrollExtent='24,18' Size='24,18' Style='/Icons.HUD.Misc.bfr_flight_pack' Tooltip='@BFRHitLocationFlightPack'/>
<Button Color='#F3E138' Location='24,42' mountpointname='Driver' Name='LeftWeapon' ScrollExtent='24,24' Size='24,24' stretch='false' Style='Gunner'></Button>
<Button Color='#F3E138' Location='52,42' mountpointname='Driver' Name='RightWeapon' ScrollExtent='24,24' Size='24,24' stretch='false' Style='Gunner'></Button>
<Button Color='#F3E138' Location='46,50' mountpointname='Driver' Name='Driver' ScrollExtent='8,8' Size='8,8' stretch='false' Style='Occupant'></Button>
<Image Color='#F3E138' Location='46,50' mountpointname='Driver' Name='Driver' ScrollExtent='8,8' Size='8,8' Stretch='false' Style='EmptyOccupant'/>
<Progressbar BackgroundColor='#FF0000' BarBackgroundColor='#00F2C9' GetsInput='false' Location='7,43' Name='Progress' Progress='0.800' ScrollExtent='86,55' Size='86,55' Style='/ProgressBars.peregrine.style'/>
<Ellipse AbsorbsInput='false' BackgroundOpacity='1.000' Color='#0099C5' Enabled='false' InnerRadiusColor='#0099C5' InnerRadiusOpacity='0.000' maxthickness='50.0' Name='Shield' Opacity='0.750' ScrollExtent='100,140' Size='100,140' Thickness='50.000'/>
</Page>
<Page isvehiclepage='true' Name='peregrine_variant' ScrollExtent='100,140' Size='100,140' Visible='false'>
<Image AbsorbsInput='false' Color='#F3E138' GetsInput='true' LocalTooltip='[@BFRHitLocationSensors]' Location='43,118' mountpointname='Driver' Name='Sensors' ScrollExtent='15,20' Size='15,20' Style='/Icons.HUD.Misc.bfr_sensors' Tooltip='@BFRHitLocationSensors'/>
<Image AbsorbsInput='false' Color='#F3E138' GetsInput='true' LocalTooltip='[@BFRHitLocationMovement]' Location='65,118' mountpointname='Driver' Name='MovementServos' ScrollExtent='21,21' Size='21,21' Style='/Icons.HUD.Misc.bfr_movement_servos' Tooltip='@BFRHitLocationMovement'/>
<Image AbsorbsInput='false' Color='#00FF00' GetsInput='true' LocalTooltip='[@BFRHitLocationShieldGenerator]' Location='16,122' mountpointname='Driver' Name='ShieldGenerator' ScrollExtent='20,13' Size='20,13' Style='/Icons.HUD.Misc.bfr_shield_generator' Tooltip='@BFRHitLocationShieldGenerator'/>
<Button Color='#F3E138' Location='24,42' mountpointname='Driver' Name='LeftWeapon' ScrollExtent='24,24' Size='24,24' stretch='false' Style='Gunner'></Button>
<Button Color='#F3E138' Location='52,42' mountpointname='Driver' Name='RightWeapon' ScrollExtent='24,24' Size='24,24' stretch='false' Style='Gunner'></Button>
<Button Color='#F3E138' Location='46,50' mountpointname='Driver' Name='Driver' ScrollExtent='8,8' Size='8,8' stretch='false' Style='Occupant'></Button>
<Button Color='#F3E138' Location='38,68' mountpointname='GunnerA' Name='GunnerA' ScrollExtent='24,24' Size='24,24' stretch='false' Style='Gunner'></Button>
<Image Color='#F3E138' Location='46,50' mountpointname='Driver' Name='Driver' ScrollExtent='8,8' Size='8,8' Stretch='false' Style='EmptyOccupant'/>
<Image Color='#F3E138' Location='46,76' mountpointname='GunnerA' Name='GunnerA' ScrollExtent='8,8' Size='8,8' Stretch='false' Style='EmptyOccupant'/>
<Progressbar BackgroundColor='#FF0000' BarBackgroundColor='#00F2C9' GetsInput='false' Location='7,43' Name='Progress' Progress='0.800' ScrollExtent='86,55' Size='86,55' Style='/ProgressBars.peregrine.style'/>
<Ellipse AbsorbsInput='false' BackgroundOpacity='1.000' Color='#0099C5' Enabled='false' InnerRadiusColor='#0099C5' InnerRadiusOpacity='0.000' maxthickness='50.0' Name='Shield' Opacity='0.750' ScrollExtent='100,140' Size='100,140' Thickness='50.000'/>
</Page>
<Page isvehiclepage='true' Name='prowler' ScrollExtent='116,140' Size='116,140' Visible='false'>
<Button Color='#F3E138' Location='54,39' mountpointname='Driver' Name='Driver' ScrollExtent='8,8' Size='8,8' stretch='false' Style='Occupant'></Button>
<Button Color='#F3E138' Location='74,74' mountpointname='GunnerA' Name='GunnerA' ScrollExtent='24,24' Size='24,24' stretch='false' Style='Gunner'></Button>
<Button Color='#F3E138' Location='18,74' mountpointname='GunnerB' Name='GunnerB' ScrollExtent='24,24' Size='24,24' stretch='false' Style='Gunner'></Button>
<Image Color='#F3E138' Location='54,39' mountpointname='Driver' Name='Driver' ScrollExtent='8,8' Size='8,8' Stretch='false' Style='EmptyOccupant'/>
<Image Color='#F3E138' Location='82,82' mountpointname='GunnerA' Name='GunnerA' ScrollExtent='8,8' Size='8,8' Stretch='false' Style='EmptyOccupant'/>
<Image Color='#F3E138' Location='26,82' mountpointname='GunnerB' Name='GunnerB' ScrollExtent='8,8' Size='8,8' Stretch='false' Style='EmptyOccupant'/>
<Progressbar BackgroundColor='#FF0000' BarBackgroundColor='#00F2C9' GetsInput='false' Location='20,20' Name='Progress' Progress='0.800' ScrollExtent='76,100' Size='76,100' Style='/ProgressBars.prowler.style'/>
<Ellipse AbsorbsInput='false' BackgroundOpacity='1.000' Color='#0099C5' Enabled='false' InnerRadiusColor='#0099C5' InnerRadiusOpacity='0.000' maxthickness='50.0' Name='Shield' Opacity='0.750' ScrollExtent='116,140' Size='116,140' Thickness='50.000'/>
</Page>
<Page isvehiclepage='true' Name='quadassault' ScrollExtent='104,140' Size='104,140' Visible='false'>
<Progressbar BackgroundColor='#FF0000' BarBackgroundColor='#00F2C9' GetsInput='false' Location='20,20' Name='Progress' Progress='0.750' ScrollExtent='64,100' Size='64,100' Style='/ProgressBars.quadassault.style'/>
<Ellipse AbsorbsInput='false' BackgroundOpacity='1.000' Color='#0099C5' Enabled='false' InnerRadiusColor='#0099C5' InnerRadiusOpacity='0.000' maxthickness='50.0' Name='Shield' Opacity='0.750' ScrollExtent='104,140' Size='104,140' Thickness='50.000'/>
</Page>
<Page isvehiclepage='true' Name='quadstealth' ScrollExtent='104,140' Size='104,140' Visible='false'>
<Progressbar BackgroundColor='#FF0000' BarBackgroundColor='#00F2C9' GetsInput='false' Location='20,20' Name='Progress' Progress='0.750' ScrollExtent='64,100' Size='64,100' Style='/ProgressBars.quadassault.style'/>
<Ellipse AbsorbsInput='false' BackgroundOpacity='1.000' Color='#0099C5' Enabled='false' InnerRadiusColor='#0099C5' InnerRadiusOpacity='0.000' maxthickness='50.0' Name='Shield' Opacity='0.750' ScrollExtent='104,140' Size='104,140' Thickness='50.000'/>
</Page>
<Page isvehiclepage='true' Name='router' PackLocation='center,center' PackLocationProp='-095/0001,-070/0001' ScrollExtent='190,140' Size='190,140' Visible='false'>
<Progressbar BackgroundColor='#FF0000' BarBackgroundColor='#00F2C9' GetsInput='false' Location='20,20' Name='Progress' Progress='0.800' ScrollExtent='150,100' Size='150,100' Style='/ProgressBars.router.style'/>
<Ellipse AbsorbsInput='false' BackgroundOpacity='1.000' Color='#0099C5' Enabled='false' InnerRadiusColor='#0099C5' InnerRadiusOpacity='0.000' maxthickness='50.0' Name='Shield' Opacity='0.750' ScrollExtent='190,140' Size='190,140' Thickness='50.000'/>
</Page>
<Page isvehiclepage='true' Name='skyguard' ScrollExtent='95,140' Size='95,140' Visible='false'>
<Button Color='#F3E138' Location='43,63' mountpointname='Driver' Name='Driver' ScrollExtent='8,8' Size='8,8' stretch='false' Style='Occupant'></Button>
<Button Color='#F3E138' Location='35,88' mountpointname='GunnerA' Name='GunnerA' ScrollExtent='24,24' Size='24,24' stretch='false' Style='Gunner'></Button>
<Image Color='#F3E138' Location='43,63' mountpointname='Driver' Name='Driver' ScrollExtent='8,8' Size='8,8' Stretch='false' Style='EmptyOccupant'/>
<Image Color='#F3E138' Location='43,96' mountpointname='GunnerA' Name='GunnerA' ScrollExtent='8,8' Size='8,8' Stretch='false' Style='EmptyOccupant'/>
<Progressbar BackgroundColor='#FF0000' BarBackgroundColor='#00F2C9' GetsInput='false' Location='20,20' Name='Progress' Progress='0.800' ScrollExtent='55,100' Size='55,100' Style='/ProgressBars.skyguard.style'/>
<Ellipse AbsorbsInput='false' BackgroundOpacity='1.000' Color='#0099C5' Enabled='false' InnerRadiusColor='#0099C5' InnerRadiusOpacity='0.000' maxthickness='50.0' Name='Shield' Opacity='0.750' ScrollExtent='95,140' Size='95,140' Thickness='50.000'/>
</Page>
<Page isvehiclepage='true' Name='switchblade' PackLocation='center,center' PackLocationProp='-095/0001,-070/0001' ScrollExtent='84,140' Size='84,140' Visible='false'>
<Progressbar BackgroundColor='#FF0000' BarBackgroundColor='#00F2C9' GetsInput='false' Location='20,20' Name='Progress' Progress='0.800' ScrollExtent='44,100' Size='44,100' Style='/ProgressBars.switchblade.style'/>
<Ellipse AbsorbsInput='false' BackgroundOpacity='1.000' Color='#0099C5' Enabled='false' InnerRadiusColor='#0099C5' InnerRadiusOpacity='0.000' maxthickness='50.0' Name='Shield' Opacity='0.750' ScrollExtent='84,140' Size='84,140' Thickness='50.000'/>
</Page>
<Page isvehiclepage='true' Name='threemanheavybuggy' ScrollExtent='93,140' Size='93,140' Visible='false'>
<Button Color='#F3E138' Location='32,68' mountpointname='Driver' Name='Driver' ScrollExtent='8,8' Size='8,8' stretch='false' Style='Occupant'></Button>
<Button Color='#F3E138' Location='44,60' mountpointname='GunnerA' Name='GunnerA' ScrollExtent='24,24' Size='24,24' stretch='false' Style='Gunner'></Button>
<Button Color='#F3E138' Location='34,84' mountpointname='GunnerB' Name='GunnerB' ScrollExtent='24,24' Size='24,24' stretch='false' Style='Gunner'></Button>
<Image Color='#F3E138' Location='32,68' mountpointname='Driver' Name='Driver' ScrollExtent='8,8' Size='8,8' Stretch='false' Style='EmptyOccupant'/>
<Image Color='#F3E138' Location='52,68' mountpointname='GunnerA' Name='GunnerA' ScrollExtent='8,8' Size='8,8' Stretch='false' Style='EmptyOccupant'/>
<Image Color='#F3E138' Location='42,92' mountpointname='GunnerB' Name='GunnerB' ScrollExtent='8,8' Size='8,8' Stretch='false' Style='EmptyOccupant'/>
<Progressbar BackgroundColor='#FF0000' BarBackgroundColor='#00F2C9' GetsInput='false' Location='20,20' Name='Progress' Progress='1.000' ScrollExtent='53,100' Size='53,100' Style='/ProgressBars.threemanheavybuggy.style'/>
<Ellipse AbsorbsInput='false' BackgroundOpacity='1.000' Color='#0099C5' Enabled='false' InnerRadiusColor='#0099C5' InnerRadiusOpacity='0.000' maxthickness='50.0' Name='Shield' Opacity='0.750' ScrollExtent='93,140' Size='93,140' Thickness='50.000'/>
</Page>
<Page isvehiclepage='true' Name='thunderer' ScrollExtent='90,140' Size='90,140' Visible='false'>
<Button Color='#F3E138' Location='35,48' mountpointname='Driver' Name='Driver' ScrollExtent='8,8' Size='8,8' stretch='false' Style='Occupant'></Button>
<Button Color='#F3E138' Location='39,40' mountpointname='GunnerA' Name='GunnerA' ScrollExtent='24,24' Size='24,24' stretch='false' Style='Gunner'></Button>
<Button Color='#F3E138' Location='28,82' mountpointname='GunnerB' Name='GunnerB' ScrollExtent='24,24' Size='24,24' stretch='false' Style='Gunner'></Button>
<Button Color='#F3E138' Location='35,69' mountpointname='PassengerA' Name='PassengerA' ScrollExtent='8,8' Size='8,8' stretch='false' Style='Occupant'></Button>
<Button Color='#F3E138' Location='47,69' mountpointname='PassengerB' Name='PassengerB' ScrollExtent='8,8' Size='8,8' stretch='false' Style='Occupant'></Button>
<Image Color='#F3E138' Location='35,48' mountpointname='Driver' Name='Driver' ScrollExtent='8,8' Size='8,8' Stretch='false' Style='EmptyOccupant'/>
<Image Color='#F3E138' Location='47,48' mountpointname='GunnerA' Name='GunnerA' ScrollExtent='8,8' Size='8,8' Stretch='false' Style='EmptyOccupant'/>
<Image Color='#F3E138' Location='36,90' mountpointname='GunnerB' Name='GunnerB' ScrollExtent='8,8' Size='8,8' Stretch='false' Style='EmptyOccupant'/>
<Image Color='#F3E138' Location='35,69' mountpointname='PassengerA' Name='PassengerA' ScrollExtent='8,8' Size='8,8' Stretch='false' Style='EmptyOccupant'/>
<Image Color='#F3E138' Location='47,69' mountpointname='PassengerB' Name='PassengerB' ScrollExtent='8,8' Size='8,8' Stretch='false' Style='EmptyOccupant'/>
<Progressbar BackgroundColor='#FF0000' BarBackgroundColor='#00F2C9' GetsInput='false' Location='20,20' Name='Progress' Progress='0.800' ScrollExtent='50,100' Size='50,100' Style='/ProgressBars.mediumtransport.style'/>
<Ellipse AbsorbsInput='false' BackgroundOpacity='1.000' Color='#0099C5' Enabled='false' InnerRadiusColor='#0099C5' InnerRadiusOpacity='0.000' maxthickness='50.0' Name='Shield' Opacity='0.750' ScrollExtent='90,140' Size='90,140' Thickness='50.000'/>
</Page>
<Page isvehiclepage='true' Name='two_man_assault_buggy' ScrollExtent='100,140' Size='100,140' Visible='false'>
<Button Color='#F3E138' Location='39,67' mountpointname='Driver' Name='Driver' ScrollExtent='8,8' Size='8,8' stretch='false' Style='Occupant'></Button>
<Button Color='#F3E138' Location='45,59' mountpointname='GunnerA' Name='GunnerA' ScrollExtent='24,24' Size='24,24' stretch='false' Style='Gunner'></Button>
<Image Color='#F3E138' Location='39,67' mountpointname='Driver' Name='Driver' ScrollExtent='8,8' Size='8,8' Stretch='false' Style='EmptyOccupant'/>
<Image Color='#F3E138' Location='53,67' mountpointname='GunnerA' Name='GunnerA' ScrollExtent='8,8' Size='8,8' Stretch='false' Style='EmptyOccupant'/>
<Progressbar BackgroundColor='#FF0000' BarBackgroundColor='#00F2C9' GetsInput='false' Location='20,20' Name='Progress' Progress='0.800' ScrollExtent='60,100' Size='60,100' Style='/ProgressBars.two_man_assault_buggy.style'/>
<Ellipse AbsorbsInput='false' BackgroundOpacity='1.000' Color='#0099C5' Enabled='false' InnerRadiusColor='#0099C5' InnerRadiusOpacity='0.000' maxthickness='50.0' Name='Shield' Opacity='0.750' ScrollExtent='100,140' Size='100,140' Thickness='50.000'/>
</Page>
<Page isvehiclepage='true' Name='twomanheavybuggy' ScrollExtent='94,140' Size='94,140' Visible='false'>
<Button Color='#F3E138' Location='43,65' mountpointname='Driver' Name='Driver' ScrollExtent='8,8' Size='8,8' stretch='false' Style='Occupant'></Button>
<Button Color='#F3E138' Location='35,88' mountpointname='GunnerA' Name='GunnerA' ScrollExtent='24,24' Size='24,24' stretch='false' Style='Gunner'></Button>
<Image Color='#F3E138' Location='43,65' mountpointname='Driver' Name='Driver' ScrollExtent='8,8' Size='8,8' Stretch='false' Style='EmptyOccupant'/>
<Image Color='#F3E138' Location='43,96' mountpointname='GunnerA' Name='GunnerA' ScrollExtent='8,8' Size='8,8' Stretch='false' Style='EmptyOccupant'/>
<Progressbar BackgroundColor='#FF0000' BarBackgroundColor='#00F2C9' GetsInput='false' Location='20,20' Name='Progress' Progress='0.600' ScrollExtent='54,100' Size='54,100' Style='/ProgressBars.twomanheavybuggy.style'/>
<Ellipse AbsorbsInput='false' BackgroundOpacity='1.000' Color='#0099C5' Enabled='false' InnerRadiusColor='#0099C5' InnerRadiusOpacity='0.000' maxthickness='50.0' Name='Shield' Opacity='0.750' ScrollExtent='94,140' Size='94,140' Thickness='50.000'/>
</Page>
<Page isvehiclepage='true' Name='twomanhoverbuggy' ScrollExtent='94,140' Size='94,140' Visible='false'>
<Button Color='#F3E138' Location='38,76' mountpointname='Driver' Name='Driver' ScrollExtent='8,8' Size='8,8' stretch='false' Style='Occupant'></Button>
<Button Color='#F3E138' Location='41,68' mountpointname='GunnerA' Name='GunnerA' ScrollExtent='24,24' Size='24,24' stretch='false' Style='Gunner'></Button>
<Image Color='#F3E138' Location='38,76' mountpointname='Driver' Name='Driver' ScrollExtent='8,8' Size='8,8' Stretch='false' Style='EmptyOccupant'/>
<Image Color='#F3E138' Location='49,76' mountpointname='GunnerA' Name='GunnerA' ScrollExtent='8,8' Size='8,8' Stretch='false' Style='EmptyOccupant'/>
<Progressbar BackgroundColor='#FF0000' BarBackgroundColor='#00F2C9' GetsInput='false' Location='20,20' Name='Progress' Progress='0.600' ScrollExtent='54,100' Size='54,100' Style='/ProgressBars.twomanhoverbuggy.style'/>
<Ellipse AbsorbsInput='false' BackgroundOpacity='1.000' Color='#0099C5' Enabled='false' InnerRadiusColor='#0099C5' InnerRadiusOpacity='0.000' maxthickness='50.0' Name='Shield' Opacity='0.750' ScrollExtent='94,140' Size='94,140' Thickness='50.000'/>
</Page>
<Page isvehiclepage='true' Name='vanguard' ScrollExtent='104,140' Size='104,140' Visible='false'>
<Button Color='#F3E138' Location='57,54' mountpointname='Driver' Name='Driver' ScrollExtent='8,8' Size='8,8' stretch='false' Style='Occupant'></Button>
<Button Color='#F3E138' Location='52,73' mountpointname='GunnerA' Name='GunnerA' ScrollExtent='24,24' Size='24,24' stretch='false' Style='Gunner'></Button>
<Image Color='#F3E138' Location='57,54' mountpointname='Driver' Name='Driver' ScrollExtent='8,8' Size='8,8' Stretch='false' Style='EmptyOccupant'/>
<Image Color='#F3E138' Location='60,81' mountpointname='GunnerA' Name='GunnerA' ScrollExtent='8,8' Size='8,8' Stretch='false' Style='EmptyOccupant'/>
<Progressbar BackgroundColor='#FF0000' BarBackgroundColor='#00F2C9' GetsInput='false' Location='20,20' Name='Progress' Progress='0.800' ScrollExtent='65,100' Size='65,100' Style='/ProgressBars.vanguard.style'/>
<Ellipse AbsorbsInput='false' BackgroundOpacity='1.000' Color='#0099C5' Enabled='false' InnerRadiusColor='#0099C5' InnerRadiusOpacity='0.000' maxthickness='50.0' Name='Shield' Opacity='0.750' ScrollExtent='104,140' Size='104,140' Thickness='50.000'/>
</Page>
<Page isvehiclepage='true' Name='vanu_sentry_turret' PackLocation='center,center' PackLocationProp='-095/0001,-070/0001' ScrollExtent='122,140' Size='122,140' Visible='false'>
<Progressbar BackgroundColor='#FF0000' BarBackgroundColor='#00F2C9' GetsInput='false' Location='20,20' Name='Progress' Progress='0.800' ScrollExtent='82,100' Size='82,100' Style='/ProgressBars.vanu_sentry_turret.style'/>
<Ellipse AbsorbsInput='false' BackgroundOpacity='1.000' Color='#0099C5' Enabled='false' InnerRadiusColor='#0099C5' InnerRadiusOpacity='0.000' maxthickness='50.0' Name='Shield' Opacity='0.750' ScrollExtent='122,140' Size='122,140' Thickness='50.000'/>
</Page>
<Page isvehiclepage='true' Name='vulture' ScrollExtent='114,140' Size='114,140' Visible='false'>
<Button Color='#F3E138' Location='53,35' mountpointname='Driver' Name='Driver' ScrollExtent='8,8' Size='8,8' stretch='false' Style='Occupant'></Button>
<Button Color='#F3E138' Location='53,53' mountpointname='GunnerA' Name='GunnerA' ScrollExtent='8,8' Size='8,8' stretch='false' Style='Occupant'></Button>
<Button Color='#F3E138' Location='45,61' mountpointname='GunnerC' Name='GunnerC' ScrollExtent='24,24' Size='24,24' stretch='false' Style='Gunner'></Button>
<Image Color='#F3E138' Location='53,35' mountpointname='Driver' Name='Driver' ScrollExtent='8,8' Size='8,8' Stretch='false' Style='EmptyOccupant'/>
<Image Color='#F3E138' Location='53,53' mountpointname='GunnerA' Name='GunnerA' ScrollExtent='8,8' Size='8,8' Stretch='false' Style='EmptyOccupant'/>
<Image Color='#F3E138' Location='53,69' mountpointname='GunnerC' Name='GunnerC' ScrollExtent='8,8' Size='8,8' Stretch='false' Style='EmptyOccupant'/>
<Progressbar BackgroundColor='#FF0000' BarBackgroundColor='#00F2C9' GetsInput='false' Location='20,20' Name='Progress' Progress='0.800' ScrollExtent='74,100' Size='74,100' Style='/ProgressBars.liberator.style'/>
<Ellipse AbsorbsInput='false' BackgroundOpacity='1.000' Color='#0099C5' Enabled='false' InnerRadiusColor='#0099C5' InnerRadiusOpacity='0.000' maxthickness='50.0' Name='Shield' Opacity='0.750' ScrollExtent='114,140' Size='114,140' Thickness='50.000'/>
</Page>
<Page isvehiclepage='true' Name='wasp' ScrollExtent='94,140' Size='94,140' Visible='false'>
<Progressbar BackgroundColor='#FF0000' BarBackgroundColor='#00F2C9' GetsInput='false' Location='20,20' Name='Progress' Progress='0.800' ScrollExtent='54,100' Size='54,100' Style='/ProgressBars.mosquito.style'/>
<Ellipse AbsorbsInput='false' BackgroundOpacity='1.000' Color='#0099C5' Enabled='false' InnerRadiusColor='#0099C5' InnerRadiusOpacity='0.000' maxthickness='50.0' Name='Shield' Opacity='0.750' ScrollExtent='94,140' Size='94,140' Thickness='50.000'/>
</Page>
</Page>
