<Page BackgroundColor='#FFFFFF' crosshairtype='dumbfire_missile' defaultcolor='#FFFFFF' enemycolor='#FF0000' friendlycolor='#00FF00' GetsInput='false' Location='262,134' Name='DumbFireCrosshair' PackLocation='Center,Center' PackLocationProp='-250/0001,-250/0001' ScrollExtent='500,500' Size='500,500' Visible='false' visualeditlock='true'>
<Image Location='214,214' Name='Reticle' Opacity='0.500' ScrollExtent='64,64' Size='64,64' SourceResource='ui_crosshair_missile_dumbfire'/>
<Text Font='/SmallFont' LocalText='Rifle Crosshair' Location='100,112' Name='ID' Opacity='0.500' ScrollExtent='100,12' Size='100,12' Visible='false'>Rifle Crosshair</Text>
<Ellipse ArcBegin='0.813' ArcEnd='0.937' GetsInput='false' InnerRadiusOpacity='0.250' Location='240,240' Name='COF_TopRight' Opacity='0.750' ScrollExtent='25,25' Size='25,25' Thickness='10.000'/>
<Ellipse ArcBegin='0.063' ArcEnd='0.188' GetsInput='false' InnerRadiusOpacity='0.250' Location='240,240' Name='COF_BottomRight' Opacity='0.750' ScrollExtent='25,25' Size='25,25' Thickness='10.000'/>
<Ellipse ArcBegin='0.313' ArcEnd='0.438' GetsInput='false' InnerRadiusOpacity='0.250' Location='240,240' Name='COF_BottomLeft' Opacity='0.750' ScrollExtent='25,25' Size='25,25' Thickness='10.000'/>
<Ellipse ArcBegin='0.563' ArcEnd='0.688' GetsInput='false' InnerRadiusOpacity='0.250' Location='240,240' Name='COF_TopLeft' Opacity='0.750' ScrollExtent='25,25' Size='25,25' Thickness='10.000'/>
</Page>
