<Page defaultcolor='#FFFFFF' enemycolor='#FF0000' friendlycolor='#00FF00' GetsInput='false' Location='262,134' Name='DefaultCrosshair' PackLocation='Center,Center' PackLocationProp='-250/0001,-250/0001' ScrollExtent='500,500' Size='500,500' Visible='false' visualeditlock='true'>
<Text Font='/SmallFont' LocalText='Default Crosshair' Location='100,112' Name='ID' Opacity='0.500' ScrollExtent='100,12' Size='100,12' Visible='false'>Default Crosshair</Text>
<Ellipse Color='#00FF00' Location='233,234' Name='COF' Opacity='0.400' ScrollExtent='32,32' Size='32,32'/>
<Image LocalTooltip='0,0,32,32' Location='202,202' Name='COF_TopLeft' Opacity='0.500' ScrollExtent='32,32' Size='32,32' SourceRect='0,0,32,32' SourceResource='ui_pistol_crosshair' Stretch='false' Tooltip='0,0,32,32' TooltipStyle='ui_pistolcrosshair'/>
<Image Location='234,202' Name='COF_Top' Opacity='0.500' ScrollExtent='32,32' Size='32,32' SourceRect='34,0,66,32' SourceResource='ui_pistol_crosshair'/>
<Image Location='266,202' Name='COF_TopRight' Opacity='0.500' ScrollExtent='32,32' Size='32,32' SourceRect='68,0,100,32' SourceResource='ui_pistol_crosshair' Stretch='false'/>
<Image Location='202,234' Name='COF_Left' Opacity='0.500' ScrollExtent='32,32' Size='32,32' SourceRect='0,34,32,66' SourceResource='ui_pistol_crosshair'/>
<Image Location='234,234' Name='Reticle' Opacity='0.500' ScrollExtent='32,32' Size='32,32' SourceRect='34,34,66,66' SourceResource='ui_pistol_crosshair' Visible='false'/>
<Image Location='266,234' Name='COF_Right' Opacity='0.500' ScrollExtent='32,32' Size='32,32' SourceRect='68,34,100,66' SourceResource='ui_pistol_crosshair'/>
<Image Location='202,265' Name='COF_BottomLeft' Opacity='0.500' ScrollExtent='32,32' Size='32,32' SourceRect='0,66,32,100' SourceResource='ui_pistol_crosshair'/>
<Image Location='234,265' Name='COF_Bottom' Opacity='0.500' ScrollExtent='32,32' Size='32,32' SourceRect='34,66,66,100' SourceResource='ui_pistol_crosshair'/>
<Image Location='266,265' Name='COF_BottomRight' Opacity='0.500' ScrollExtent='32,32' Size='32,32' SourceRect='68,66,100,100' SourceResource='ui_pistol_crosshair'/>
</Page>
