<Page Color='#FF0000' GetsInput='false' Location='470,480' Name='GriefIndicator' PackLocation='cfc,cfc' PackLocationProp='0023/0001,0116/0001' ScrollExtent='130,40' Size='130,40' Visible='false'>
<Text AbsorbsInput='false' Font='/Fonts.OverheadFont' LocalText='+50' Location='46,0' Name='Text' ScrollExtent='84,40' Size='84,40' TextAlignmentVertical='Center'>+50</Text>
<Image AbsorbsInput='false' Name='GriefIcon' ScrollExtent='40,40' Size='40,40' SourceRect='0,0,32,32' SourceResource='grief_weapons_lock_icon' Style=' '/>
</Page>
