<Page BackgroundColor='#FFFFFF' crosshairtype='pistol' defaultcolor='#FFFFFF' enemycolor='#FF0000' friendlycolor='#00FF00' GetsInput='false' Location='262,134' Name='PistolCrosshair' PackLocation='Center,Center' PackLocationProp='-250/0001,-250/0001' ScrollExtent='500,500' Size='500,500' Visible='false' visualeditlock='true'>
<Ellipse InnerRadiusOpacity='0.500' Location='240,240' MinimumSize='25,25' Name='Reticle' Opacity='0.500' ScrollExtent='25,25' Size='25,25' Thickness='3.000'/>
<Ellipse ArcBegin='0.438' ArcEnd='0.563' InnerRadiusOpacity='0.500' Location='240,240' MinimumSize='25,25' Name='ReticleLeft' Opacity='0.500' ScrollExtent='25,25' Size='25,25' Thickness='7.000'/>
<Ellipse ArcBegin='-0.063' ArcEnd='0.063' InnerRadiusOpacity='0.500' Location='240,240' MinimumSize='25,25' Name='ReticleRight' Opacity='0.500' ScrollExtent='25,25' Size='25,25' Thickness='7.000'/>
<Text Font='/SmallFont' LocalText='Rifle Crosshair' Location='100,112' Name='ID' Opacity='0.500' ScrollExtent='100,12' Size='100,12' Visible='false'>Rifle Crosshair</Text>
<Ellipse ArcBegin='0.813' ArcEnd='0.937' GetsInput='false' Location='240,240' Name='COF_TopRight' Opacity='0.900' ScrollExtent='25,25' Size='25,25' Thickness='5.000'/>
<Ellipse ArcBegin='0.063' ArcEnd='0.188' GetsInput='false' Location='240,240' Name='COF_BottomRight' Opacity='0.900' ScrollExtent='25,25' Size='25,25' Thickness='5.000'/>
<Ellipse ArcBegin='0.313' ArcEnd='0.438' GetsInput='false' Location='240,240' Name='COF_BottomLeft' Opacity='0.900' ScrollExtent='25,25' Size='25,25' Thickness='5.000'/>
<Ellipse ArcBegin='0.563' ArcEnd='0.688' GetsInput='false' Location='240,240' Name='COF_TopLeft' Opacity='0.900' ScrollExtent='25,25' Size='25,25' Thickness='5.000'/>
<Ellipse ArcEnd='1.001' InnerRadiusOpacity='0.500' Location='240,240' Name='COF' Opacity='0.750' ScrollExtent='25,25' Size='25,25' Thickness='2.500'/>
</Page>
