<Page GetsInput='false' Location='975,669' Name='CrouchIndicator' PackLocation='right,bottom' PackLocationProp='-049/0001,-099/0001' ScrollExtent='41,40' Size='41,40' Visible='false'>
<Image AbsorbsInput='false' Name='CrouchIcon' ScrollExtent='40,40' Size='40,40' SourceRect='0,0,64,64' SourceResource='ui_hud_icon_crouch' Style=' '/>
<Image AbsorbsInput='false' Location='0,3' Name='ColossusIcon' ScrollExtent='40,35' Size='40,35' Style='/Icons.HUD.CrouchIcons.colossus_crouch' Visible='false'/>
<Image AbsorbsInput='false' Location='5,0' Name='AphelionIcon' ScrollExtent='30,40' Size='30,40' Style='/Icons.HUD.CrouchIcons.aphelion_crouch' Visible='false'/>
<Image AbsorbsInput='false' Location='3,0' Name='PeregrineIcon' ScrollExtent='34,40' Size='34,40' Style='/Icons.HUD.CrouchIcons.peregrine_crouch' Visible='false'/>
</Page>
