<Page movable='true' Name='SquadList' PackLocation='Left,Top' PackLocationProp='0000/0001,0000/0001' PackSize='1,fixed' PackSizeProp='0002/0003,0002/0003' ScrollExtent='1024,36' Size='1024,36' Visible='false'>
<Button BackgroundColor='#FFFFFF' LocalText='v' LocalTooltip='[@ToggleSquadTooltip]' Name='Maximize' RStyleDefault=' ' ScrollExtent='57,32' Size='57,32' Style='/Buttons.MinimizedButton.style' Tooltip='@ToggleSquadTooltip'>v</Button>
<ImageStyle Name='nw'>
<ImageFrame Source='ui_HUD_border_00' SourceRect='0,0,6,6'/>
</ImageStyle>
<ImageStyle Name='north'>
<ImageFrame Source='ui_HUD_border_00' SourceRect='6,0,10,6'/>
</ImageStyle>
<ImageStyle Name='ne'>
<ImageFrame Source='ui_HUD_border_00' SourceRect='10,0,16,6'/>
</ImageStyle>
<ImageStyle Name='west'>
<ImageFrame Source='ui_HUD_border_00' SourceRect='0,6,6,10'/>
</ImageStyle>
<ImageStyle Name='center'>
<ImageFrame Source='ui_HUD_border_00' SourceRect='6,6,10,10'/>
</ImageStyle>
<ImageStyle Name='east'>
<ImageFrame Source='ui_HUD_border_00' SourceRect='10,6,16,10'/>
</ImageStyle>
<ImageStyle Name='sw'>
<ImageFrame Source='ui_HUD_border_00' SourceRect='0,10,6,16'/>
</ImageStyle>
<ImageStyle Name='south'>
<ImageFrame Source='ui_HUD_border_00' SourceRect='6,10,10,16'/>
</ImageStyle>
<ImageStyle Name='se'>
<ImageFrame Source='ui_HUD_border_00' SourceRect='10,10,16,16'/>
</ImageStyle>
<RectangleStyle Center='center' CenterShrinkH='true' CenterShrinkV='true' CenterStretchH='true' CenterStretchV='true' East='east' EastShrink='true' EastStretch='true' Name='SquadBorderRect' North='north' NorthEast='ne' NorthShrink='true' NorthStretch='true' NorthWest='nw' South='south' SouthEast='se' SouthShrink='true' SouthStretch='true' SouthWest='sw' West='west' WestShrink='true' WestStretch='true'/>
</Page>
