<Page BackgroundColor='#FFFFFF' crosshairtype='rek' defaultcolor='#FFFFFF' enemycolor='#FF0000' friendlycolor='#00FF00' GetsInput='false' Location='262,134' Name='REKCrosshair' PackLocation='Center,Center' PackLocationProp='-250/0001,-250/0001' ScrollExtent='500,500' Size='500,500' Visible='false' visualeditlock='true'>
<Ellipse InnerRadiusOpacity='0.500' Location='240,240' MinimumSize='25,25' Name='Reticle' Opacity='0.500' ScrollExtent='25,25' Size='25,25' Thickness='4.000'/>
<Ellipse ArcBegin='0.400' ArcEnd='0.600' InnerRadiusOpacity='0.250' Location='240,240' MinimumSize='25,25' Name='ReticleLeft' Opacity='0.500' ScrollExtent='25,25' Size='25,25' Thickness='10.000'/>
<Ellipse ArcBegin='-0.100' ArcEnd='0.100' InnerRadiusOpacity='0.250' Location='240,240' MinimumSize='25,25' Name='ReticleRight' Opacity='0.500' ScrollExtent='25,25' Size='25,25' Thickness='10.000'/>
<Text Font='/SmallFont' LocalText='Rifle Crosshair' Location='100,112' Name='ID' Opacity='0.500' ScrollExtent='100,12' Size='100,12' Visible='false'>Rifle Crosshair</Text>
</Page>
