<Page BackgroundColor='#FFFFFF' crosshairtype='rifle' defaultcolor='#FFFFFF' enemycolor='#FF0000' friendlycolor='#00FF00' GetsInput='false' Location='262,134' Name='RifleCrosshair' PackLocation='Center,Center' PackLocationProp='-250/0001,-250/0001' ScrollExtent='500,500' Size='500,500' Visible='false' visualeditlock='true'>
<Ellipse InnerRadiusOpacity='0.500' Location='240,240' MinimumSize='25,25' Name='Reticle' Opacity='0.500' ScrollExtent='25,25' Size='25,25' Thickness='1.000' Visible='false'/>
<Text Font='/SmallFont' LocalText='Rifle Crosshair' Location='100,112' Name='ID' Opacity='0.500' ScrollExtent='100,12' Size='100,12' Visible='false'>Rifle Crosshair</Text>
<Ellipse ArcBegin='0.813' ArcEnd='0.937' GetsInput='false' Location='240,240' Name='COF_TopRight' ScrollExtent='25,25' Size='25,25' Thickness='10.000'/>
<Ellipse ArcBegin='0.063' ArcEnd='0.188' GetsInput='false' Location='240,240' Name='COF_BottomRight' ScrollExtent='25,25' Size='25,25' Thickness='10.000'/>
<Ellipse ArcBegin='0.313' ArcEnd='0.438' GetsInput='false' Location='240,240' Name='COF_BottomLeft' ScrollExtent='25,25' Size='25,25' Thickness='10.000'/>
<Ellipse ArcBegin='0.563' ArcEnd='0.688' GetsInput='false' Location='240,240' Name='COF_TopLeft' ScrollExtent='25,25' Size='25,25' Thickness='10.000'/>
<Ellipse ArcEnd='1.001' InnerRadiusOpacity='0.500' Location='240,240' Name='COF' Opacity='0.500' ScrollExtent='25,25' Size='25,25' Thickness='3.500' Visible='false'/>
</Page>
