<Page defaultcolor='#FFFFFF' enemycolor='#FF0000' friendlycolor='#00FF00' GetsInput='false' Location='262,134' Name='ClusterBombCrosshair' PackLocation='Center,Center' PackLocationProp='-250/0001,-250/0001' ScrollExtent='500,500' Size='500,500' Visible='false' visualeditlock='true'>
<Text Font='/SmallFont' LocalText='Default Crosshair' Location='100,112' Name='ID' Opacity='0.500' ScrollExtent='100,12' Size='100,12' Visible='false'>Default Crosshair</Text>
<Page Location='233,234' Name='Reticle' ScrollExtent='32,32' Size='32,32'>
<Ellipse Location='2,2' Name='RingInner' Opacity='0.800' PackLocation='center,center' PackLocationProp='-014/0001,-014/0001' PackSize='fixed,fixed' PackSizeProp='0002/0003,0002/0003' ScrollExtent='28,28' Size='28,28' Thickness='2.000'/>
<Ellipse Color='#000000' Name='BackgroundInner' Opacity='0.800' PackLocation='center,center' PackLocationProp='-016/0001,-016/0001' PackSize='fixed,fixed' PackSizeProp='0002/0003,0002/0003' ScrollExtent='32,32' Size='32,32' Thickness='12.000'/>
<Ellipse Location='2,2' Name='RingOuter' Opacity='0.800' PackSize='absolute,absolute' PackSizeProp='0004/0001,0004/0001' ScrollExtent='28,28' Size='28,28' Thickness='2.000'/>
<Ellipse Color='#000000' Name='BackgroundOuter' Opacity='0.800' PackSize='absolute,absolute' PackSizeProp='0000/0001,0000/0001' ScrollExtent='32,32' Size='32,32' Thickness='12.000'/>
</Page>
</Page>
