<Page Location='298,250' MinimumSize='427,200' movable='true' Name='MainTerminal_Squad' ScrollExtent='427,284' Size='427,284' Visible='false'>
<Text AbsorbsInput='false' Enabled='false' Font='/Fonts.HudFont3' LocalText='I am Text 1!' Location='33,40' Name='Text1' PackLocation='center,top' PackLocationProp='-180/0001,0040/0001' PackSize='fixed,fixed' PackSizeProp='0002/0003,0002/0003' ScrollExtent='365,26' Size='365,26' TextAlignment='Center' TextAlignmentVertical='Center'>I am Text 1!</Text>
<Rectangle Color='#00F2C9' Location='27,35' Name='TimerRect' ScrollExtent='375,30' Size='375,30'/>
<Button LocalText='[@Cancel]' Location='352,8' Name='CancelButton' PackLocation='right,top' PackLocationProp='-075/0001,0008/0001' ScrollExtent='16,16' Size='16,16' Style='/Buttons.WindowClose.style'>@Cancel</Button>
<Button LocalText='[@Cancel]' Location='58,8' Name='HelpButton' PackLocation='left,top' PackLocationProp='0058/0001,0008/0001' ScrollExtent='16,16' Size='16,16' Style='/Buttons.WindowHelp.style'>@Cancel</Button>
<Button LocalText='[@Ability1]' Location='57,81' Name='Button1' ScrollExtent='310,20' Size='310,20' Style='/Buttons.TextButton.style'>@Ability1</Button>
<Button LocalText='[@Ability2]' Location='57,111' Name='Button2' ScrollExtent='310,20' Size='310,20' Style='/Buttons.TextButton.style'>@Ability2</Button>
<Button LocalText='[@Ability3]' Location='57,141' Name='Button3' ScrollExtent='310,20' Size='310,20' Style='/Buttons.TextButton.style'>@Ability3</Button>
<Button LocalText='[@Ability4]' Location='57,171' Name='Button4' ScrollExtent='310,20' Size='310,20' Style='/Buttons.TextButton.style'>@Ability4</Button>
<Rectangle Color='#00F2C9' Location='26,71' Name='ButtonRect' ScrollExtent='375,130' Size='375,130'/>
<Text AbsorbsInput='false' Enabled='false' Font='/Fonts.HudFont3' LocalText='60 Seconds until meltdown!' Location='32,213' Name='TimerText' PackLocation='center,top' PackLocationProp='-181/0001,0213/0001' PackSize='fixed,fixed' PackSizeProp='0002/0003,0002/0003' ScrollExtent='365,26' Size='365,26' TextAlignment='Center' TextAlignmentVertical='Center'>60 Seconds until meltdown!</Text>
<Rectangle Color='#00F2C9' Location='26,209' Name='TimerRect' ScrollExtent='375,33' Size='375,33'/>
<Text AbsorbsInput='false' Enabled='false' Font='/Fonts.HudFont3' LocalText='[@MainTerminalTitle]' Location='92,6' Name='TitleText' PackLocation='center,top' PackLocationProp='-121/0001,0006/0001' PackSize='fixed,fixed' PackSizeProp='0002/0003,0002/0003' ScrollExtent='245,20' Size='245,20' TextAlignment='Center' TextAlignmentVertical='Center'>@MainTerminalTitle</Text>
<Image AbsorbsInput='false' BackgroundOpacity='1.000' Location='30,-1' Name='Title' PackSize='absolute,fixed' PackSizeProp='0054/0001,0002/0003' RStyleActivated='/WindowPanes.TitleBarFocus.style' RStyleDefault='/WindowPanes.TitleBarNoFocus.style' ScrollExtent='373,32' Size='373,32'/>
<Image AbsorbsInput='false' BackgroundOpacity='1.000' Dragable='true' Location='0,12' Name='Background' PackSize='1,Absolute' PackSizeProp='0002/0003,0017/0001' RStyleDefault='/WindowPanes.BigBackground.style' ScrollExtent='427,267' Size='427,267' Stretch='false'/>
</Page>
