<Page Location='834,307' movable='true' Name='PowerOutageProgress' ScrollExtent='190,282' Size='190,282' Visible='false'>
<Text AbsorbsInput='false' BackgroundColor='#00F2C9' BackgroundOpacity='0.224' Enabled='false' Font='/Fonts.HudFont3' LocalText='[@PowerOutageProgressTitle]' Location='13,7' MaxLines='1' Name='Title' PackLocation='left,top' PackLocationProp='0013/0001,0007/0001' PackSize='absolute,fixed' PackSizeProp='0024/0001,0002/0003' ScrollExtent='166,34' Size='166,21' SizeIncrement='0,0' TextAlignment='Center'>@PowerOutageProgressTitle</Text>
<Checkbox Activated='true' BackgroundOpacity='1.000' Checked='true' LocalTooltip='[@ToggleWindowSizeTooltip]' Location='165,7' Name='ToggleSize' PackLocation='right,top' PackLocationProp='-025/0001,0007/0001' ScrollExtent='9,20' Size='9,20' Style='/Buttons.ActiveItems.checkstyle' Tooltip='@ToggleWindowSizeTooltip'>V</Checkbox>
<Page Name='Mini' ScrollExtent='190,106' Size='190,106' Visible='false'>
<Page BackgroundColor='#00FF00' Location='24,30' Name='VS' PackSize='fixed,absolute' PackSizeProp='0002/0003,0052/0001' ScrollExtent='50,54' Size='50,54'>
<Image Location='1,0' Name='Vehicle' PackSize='cfn,ffn' ScrollExtent='48,30' Size='48,30' Style='/ItemIcons1GridHigh.liberator_vs'/>
<Text AbsorbsInput='false' Enabled='false' Font='/Fonts.Agency24' LocalText='DONE' Location='0,30' MaxLines='1' Name='Text' PackLocation='left,top' PackLocationProp='0000/0001,0030/0001' ScrollExtent='50,30' Size='50,30' TextAlignment='Center' TextAlignmentVertical='Center' TextColor='#CC22CC'>DONE</Text>
<Image AbsorbsInput='false' Location='12,2' Name='EmpireDone' PackLocation='Left,Bottom' PackLocationProp='0012/0001,-052/0001' ScrollExtent='28,30' Size='28,30' Stretch='false' Style='/Frontend.MiniVS'/>
</Page>
<Page BackgroundColor='#00FF00' Location='74,30' Name='NC' PackSize='fixed,absolute' PackSizeProp='0002/0003,0052/0001' ScrollExtent='50,54' Size='50,54'>
<Image Location='1,0' Name='Vehicle' PackSize='cfn,ffn' ScrollExtent='48,30' Size='48,30' Style='/ItemIcons1GridHigh.liberator_nc'/>
<Text AbsorbsInput='false' Enabled='false' Font='/Fonts.Agency24' LocalText='DONE' Location='0,30' MaxLines='1' Name='Text' PackLocation='left,top' PackLocationProp='0000/0001,0030/0001' ScrollExtent='50,30' Size='50,30' TextAlignment='Center' TextAlignmentVertical='Center' TextColor='#4444EE'>DONE</Text>
<Image AbsorbsInput='false' Location='12,4' Name='EmpireDone' PackLocation='Left,Bottom' PackLocationProp='0012/0001,-050/0001' ScrollExtent='30,26' Size='30,26' Stretch='false' Style='/Frontend.MiniNC'/>
</Page>
<Page BackgroundColor='#00FF00' Location='124,30' Name='TR' PackSize='fixed,absolute' PackSizeProp='0002/0003,0050/0001' ScrollExtent='50,56' Size='50,56'>
<Image Location='1,0' Name='Vehicle' PackSize='cfn,ffn' ScrollExtent='48,30' Size='48,30' Style='/ItemIcons1GridHigh.liberator_tr'/>
<Text AbsorbsInput='false' Enabled='false' Font='/Fonts.Agency24' LocalText='DONE' Location='0,30' MaxLines='1' Name='Text' PackLocation='left,top' PackLocationProp='0000/0001,0030/0001' ScrollExtent='50,30' Size='50,30' TextAlignment='Center' TextAlignmentVertical='Center' TextColor='#DD2222'>DONE</Text>
<Image AbsorbsInput='false' Location='12,0' Name='EmpireDone' PackLocation='Left,Bottom' PackLocationProp='0012/0001,-056/0001' ScrollExtent='28,32' Size='28,32' Stretch='false' Style='/Frontend.MiniTR'/>
</Page>
<Image AbsorbsInput='false' BackgroundOpacity='1.000' Location='1,0' Name='Background' Opacity='0.700' PackSize='absolute,absolute' PackSizeProp='0000/0001,0000/0001' RStyleDefault='/WindowPanes.SmallBackground.style' ScrollExtent='190,106' Size='190,106' Stretch='false' Style=' '/>
</Page>
<Page Name='Full' ScrollExtent='190,278' Size='190,278'>
<Page BackgroundColor='#00FF00' Location='24,30' Name='VS' PackSize='fixed,fixed' PackSizeProp='0002/0003,0002/0003' ScrollExtent='50,232' Size='50,232'>
<Image AbsorbsInput='false' Location='12,2' Name='EmpireDone' ScrollExtent='28,30' Size='28,30' Style='/Frontend.MiniVS'/>
<Image BackgroundColor='#00FF00' Location='1,0' Name='Vehicle' PackSize='cfn,ffn' ScrollExtent='48,30' Size='48,30' Style='/ItemIcons1GridHigh.liberator_vs'/>
<VolumePage CellCount='1,14' CellPadding='0,2' CellSize='7,10' Location='6,32' MinimumScrollExtent='7,170' Name='Pips' ScrollExtent='7,170' Size='7,170'>
<Page Location='0,2' MaximumSize='7,10' MinimumSize='7,10' Name='Pip13' ScrollExtent='7,10' Size='7,10'>
<Page BackgroundColor='#44AAAA' BackgroundOpacity='1.000' Location='2,2' Name='Pip' PackSize='absolute,absolute' PackSizeProp='0004/0001,0004/0001' ScrollExtent='3,6' Size='3,6'/>
<Rectangle Color='#385E61' GetsInput='false' Name='Frame' PackSize='absolute,absolute' PackSizeProp='0000/0001,0000/0001' ScrollExtent='7,10' Size='7,10' UserScrollable='false'/>
<Page BackgroundOpacity='0.502' Name='Bkg' PackSize='absolute,absolute' PackSizeProp='0000/0001,0000/0001' ScrollExtent='7,10' Size='7,10'/>
</Page>
<Page Location='0,14' MaximumSize='7,10' MinimumSize='7,10' Name='Pip12' ScrollExtent='7,10' Size='7,10'>
<Page BackgroundColor='#44AAAA' BackgroundOpacity='1.000' Location='2,2' Name='Pip' PackSize='absolute,absolute' PackSizeProp='0004/0001,0004/0001' ScrollExtent='3,6' Size='3,6'/>
<Rectangle Color='#385E61' GetsInput='false' Name='Frame' PackSize='absolute,absolute' PackSizeProp='0000/0001,0000/0001' ScrollExtent='7,10' Size='7,10' UserScrollable='false'/>
<Page BackgroundOpacity='0.502' Name='Bkg' PackSize='absolute,absolute' PackSizeProp='0000/0001,0000/0001' ScrollExtent='7,10' Size='7,10'/>
</Page>
<Page Location='0,26' MaximumSize='7,10' MinimumSize='7,10' Name='Pip11' ScrollExtent='7,10' Size='7,10'>
<Page BackgroundColor='#44AAAA' BackgroundOpacity='1.000' Location='2,2' Name='Pip' PackSize='absolute,absolute' PackSizeProp='0004/0001,0004/0001' ScrollExtent='3,6' Size='3,6'/>
<Rectangle Color='#385E61' GetsInput='false' Name='Frame' PackSize='absolute,absolute' PackSizeProp='0000/0001,0000/0001' ScrollExtent='7,10' Size='7,10' UserScrollable='false'/>
<Page BackgroundOpacity='0.502' Name='Bkg' PackSize='absolute,absolute' PackSizeProp='0000/0001,0000/0001' ScrollExtent='7,10' Size='7,10'/>
</Page>
<Page Location='0,38' MaximumSize='7,10' MinimumSize='7,10' Name='Pip10' ScrollExtent='7,10' Size='7,10'>
<Page BackgroundColor='#44AAAA' BackgroundOpacity='1.000' Location='2,2' Name='Pip' PackSize='absolute,absolute' PackSizeProp='0004/0001,0004/0001' ScrollExtent='3,6' Size='3,6'/>
<Rectangle Color='#385E61' GetsInput='false' Name='Frame' PackSize='absolute,absolute' PackSizeProp='0000/0001,0000/0001' ScrollExtent='7,10' Size='7,10' UserScrollable='false'/>
<Page BackgroundOpacity='0.502' Name='Bkg' PackSize='absolute,absolute' PackSizeProp='0000/0001,0000/0001' ScrollExtent='7,10' Size='7,10'/>
</Page>
<Page Location='0,50' MaximumSize='7,10' MinimumSize='7,10' Name='Pip9' ScrollExtent='7,10' Size='7,10'>
<Page BackgroundColor='#44AAAA' BackgroundOpacity='1.000' Location='2,2' Name='Pip' PackSize='absolute,absolute' PackSizeProp='0004/0001,0004/0001' ScrollExtent='3,6' Size='3,6'/>
<Rectangle Color='#385E61' GetsInput='false' Name='Frame' PackSize='absolute,absolute' PackSizeProp='0000/0001,0000/0001' ScrollExtent='7,10' Size='7,10' UserScrollable='false'/>
<Page BackgroundOpacity='0.502' Name='Bkg' PackSize='absolute,absolute' PackSizeProp='0000/0001,0000/0001' ScrollExtent='7,10' Size='7,10'/>
</Page>
<Page Location='0,62' MaximumSize='7,10' MinimumSize='7,10' Name='Pip8' ScrollExtent='7,10' Size='7,10'>
<Page BackgroundColor='#44AAAA' BackgroundOpacity='1.000' Location='2,2' Name='Pip' PackSize='absolute,absolute' PackSizeProp='0004/0001,0004/0001' ScrollExtent='3,6' Size='3,6'/>
<Rectangle Color='#385E61' GetsInput='false' Name='Frame' PackSize='absolute,absolute' PackSizeProp='0000/0001,0000/0001' ScrollExtent='7,10' Size='7,10' UserScrollable='false'/>
<Page BackgroundOpacity='0.502' Name='Bkg' PackSize='absolute,absolute' PackSizeProp='0000/0001,0000/0001' ScrollExtent='7,10' Size='7,10'/>
</Page>
<Page Location='0,74' MaximumSize='7,10' MinimumSize='7,10' Name='Pip7' ScrollExtent='7,10' Size='7,10'>
<Page BackgroundColor='#44AAAA' BackgroundOpacity='1.000' Location='2,2' Name='Pip' PackSize='absolute,absolute' PackSizeProp='0004/0001,0004/0001' ScrollExtent='3,6' Size='3,6'/>
<Rectangle Color='#385E61' GetsInput='false' Name='Frame' PackSize='absolute,absolute' PackSizeProp='0000/0001,0000/0001' ScrollExtent='7,10' Size='7,10' UserScrollable='false'/>
<Page BackgroundOpacity='0.502' Name='Bkg' PackSize='absolute,absolute' PackSizeProp='0000/0001,0000/0001' ScrollExtent='7,10' Size='7,10'/>
</Page>
<Page Location='0,86' MaximumSize='7,10' MinimumSize='7,10' Name='Pip6' ScrollExtent='7,10' Size='7,10'>
<Page BackgroundColor='#44AAAA' BackgroundOpacity='1.000' Location='2,2' Name='Pip' PackSize='absolute,absolute' PackSizeProp='0004/0001,0004/0001' ScrollExtent='3,6' Size='3,6'/>
<Rectangle Color='#385E61' GetsInput='false' Name='Frame' PackSize='absolute,absolute' PackSizeProp='0000/0001,0000/0001' ScrollExtent='7,10' Size='7,10' UserScrollable='false'/>
<Page BackgroundOpacity='0.502' Name='Bkg' PackSize='absolute,absolute' PackSizeProp='0000/0001,0000/0001' ScrollExtent='7,10' Size='7,10'/>
</Page>
<Page Location='0,98' MaximumSize='7,10' MinimumSize='7,10' Name='Pip5' ScrollExtent='7,10' Size='7,10'>
<Page BackgroundColor='#44AAAA' BackgroundOpacity='1.000' Location='2,2' Name='Pip' PackSize='absolute,absolute' PackSizeProp='0004/0001,0004/0001' ScrollExtent='3,6' Size='3,6'/>
<Rectangle Color='#385E61' GetsInput='false' Name='Frame' PackSize='absolute,absolute' PackSizeProp='0000/0001,0000/0001' ScrollExtent='7,10' Size='7,10' UserScrollable='false'/>
<Page BackgroundOpacity='0.502' Name='Bkg' PackSize='absolute,absolute' PackSizeProp='0000/0001,0000/0001' ScrollExtent='7,10' Size='7,10'/>
</Page>
<Page Location='0,110' MaximumSize='7,10' MinimumSize='7,10' Name='Pip4' ScrollExtent='7,10' Size='7,10'>
<Page BackgroundColor='#44AAAA' BackgroundOpacity='1.000' Location='2,2' Name='Pip' PackSize='absolute,absolute' PackSizeProp='0004/0001,0004/0001' ScrollExtent='3,6' Size='3,6'/>
<Rectangle Color='#385E61' GetsInput='false' Name='Frame' PackSize='absolute,absolute' PackSizeProp='0000/0001,0000/0001' ScrollExtent='7,10' Size='7,10' UserScrollable='false'/>
<Page BackgroundOpacity='0.502' Name='Bkg' PackSize='absolute,absolute' PackSizeProp='0000/0001,0000/0001' ScrollExtent='7,10' Size='7,10'/>
</Page>
<Page Location='0,122' MaximumSize='7,10' MinimumSize='7,10' Name='Pip3' ScrollExtent='7,10' Size='7,10'>
<Page BackgroundColor='#44AAAA' BackgroundOpacity='1.000' Location='2,2' Name='Pip' PackSize='absolute,absolute' PackSizeProp='0004/0001,0004/0001' ScrollExtent='3,6' Size='3,6'/>
<Rectangle Color='#385E61' GetsInput='false' Name='Frame' PackSize='absolute,absolute' PackSizeProp='0000/0001,0000/0001' ScrollExtent='7,10' Size='7,10' UserScrollable='false'/>
<Page BackgroundOpacity='0.502' Name='Bkg' PackSize='absolute,absolute' PackSizeProp='0000/0001,0000/0001' ScrollExtent='7,10' Size='7,10'/>
</Page>
<Page Location='0,134' MaximumSize='7,10' MinimumSize='7,10' Name='Pip2' ScrollExtent='7,10' Size='7,10'>
<Page BackgroundColor='#44AAAA' BackgroundOpacity='1.000' Location='2,2' Name='Pip' PackSize='absolute,absolute' PackSizeProp='0004/0001,0004/0001' ScrollExtent='3,6' Size='3,6'/>
<Rectangle Color='#385E61' GetsInput='false' Name='Frame' PackSize='absolute,absolute' PackSizeProp='0000/0001,0000/0001' ScrollExtent='7,10' Size='7,10' UserScrollable='false'/>
<Page BackgroundOpacity='0.502' Name='Bkg' PackSize='absolute,absolute' PackSizeProp='0000/0001,0000/0001' ScrollExtent='7,10' Size='7,10'/>
</Page>
<Page Location='0,146' MaximumSize='7,10' MinimumSize='7,10' Name='Pip1' ScrollExtent='7,10' Size='7,10'>
<Page BackgroundColor='#44AAAA' BackgroundOpacity='1.000' Location='2,2' Name='Pip' PackSize='absolute,absolute' PackSizeProp='0004/0001,0004/0001' ScrollExtent='3,6' Size='3,6'/>
<Rectangle Color='#385E61' GetsInput='false' Name='Frame' PackSize='absolute,absolute' PackSizeProp='0000/0001,0000/0001' ScrollExtent='7,10' Size='7,10' UserScrollable='false'/>
<Page BackgroundOpacity='0.502' Name='Bkg' PackSize='absolute,absolute' PackSizeProp='0000/0001,0000/0001' ScrollExtent='7,10' Size='7,10'/>
</Page>
<Page Location='0,158' MaximumSize='7,10' MinimumSize='7,10' Name='Pip0' ScrollExtent='7,10' Size='7,10'>
<Page BackgroundColor='#44AAAA' BackgroundOpacity='1.000' Location='2,2' Name='Pip' PackSize='absolute,absolute' PackSizeProp='0004/0001,0004/0001' ScrollExtent='3,6' Size='3,6'/>
<Rectangle Color='#385E61' GetsInput='false' Name='Frame' PackSize='absolute,absolute' PackSizeProp='0000/0001,0000/0001' ScrollExtent='7,10' Size='7,10' UserScrollable='false'/>
<Page BackgroundOpacity='0.502' Name='Bkg' PackSize='absolute,absolute' PackSizeProp='0000/0001,0000/0001' ScrollExtent='7,10' Size='7,10'/>
</Page>
</VolumePage>
<Page BackgroundColor='#950095' BackgroundOpacity='1.000' Location='19,35' Name='Progress' ScrollExtent='14,164' Size='14,164'/>
<Page BackgroundOpacity='0.502' Location='17,33' Name='ProgressBkg' ScrollExtent='18,168' Size='18,168'/>
<Rectangle Color='#385E61' GetsInput='false' Location='16,32' Name='Frame' ScrollExtent='20,170' Size='20,170' UserScrollable='false'/>
<Text AbsorbsInput='false' Enabled='false' Font='/Fonts.Agency24' LocalText='DONE' Location='0,202' MaxLines='1' Name='Text' PackLocation='left,top' PackLocationProp='0000/0001,0202/0001' ScrollExtent='50,30' Size='50,30' TextAlignment='Center' TextAlignmentVertical='Center' TextColor='#CC22CC'>DONE</Text>
<Image AbsorbsInput='false' Location='12,206' Name='Empire' PackLocation='Left,Bottom' PackLocationProp='0012/0001,-026/0001' ScrollExtent='28,30' Size='28,30' Style='/Frontend.MiniVS' Visible='false'/>
</Page>
<Page BackgroundColor='#00FF00' Location='74,30' Name='NC' PackSize='fixed,fixed' PackSizeProp='0002/0003,0002/0003' ScrollExtent='50,232' Size='50,232'>
<Image AbsorbsInput='false' Location='12,4' Name='EmpireDone' ScrollExtent='30,26' Size='30,26' Style='/Frontend.MiniNC'/>
<Image BackgroundColor='#00FF00' Location='1,0' Name='Vehicle' PackSize='cfn,ffn' ScrollExtent='48,30' Size='48,30' Style='/ItemIcons1GridHigh.liberator_nc'/>
<VolumePage CellCount='1,14' CellPadding='0,2' CellSize='7,10' Location='6,32' MinimumScrollExtent='7,170' Name='Pips' ScrollExtent='7,170' Size='7,170'>
<Page Location='0,2' MaximumSize='7,10' MinimumSize='7,10' Name='Pip13' ScrollExtent='7,10' Size='7,10'>
<Page BackgroundColor='#AAAA44' BackgroundOpacity='1.000' Location='2,2' Name='Pip' PackSize='absolute,absolute' PackSizeProp='0004/0001,0004/0001' ScrollExtent='3,6' Size='3,6'/>
<Rectangle Color='#385E61' GetsInput='false' Name='Frame' PackSize='absolute,absolute' PackSizeProp='0000/0001,0000/0001' ScrollExtent='7,10' Size='7,10' UserScrollable='false'/>
<Page BackgroundOpacity='0.502' Name='Bkg' PackSize='absolute,absolute' PackSizeProp='0000/0001,0000/0001' ScrollExtent='7,10' Size='7,10'/>
</Page>
<Page Location='0,14' MaximumSize='7,10' MinimumSize='7,10' Name='Pip12' ScrollExtent='7,10' Size='7,10'>
<Page BackgroundColor='#AAAA44' BackgroundOpacity='1.000' Location='2,2' Name='Pip' PackSize='absolute,absolute' PackSizeProp='0004/0001,0004/0001' ScrollExtent='3,6' Size='3,6'/>
<Rectangle Color='#385E61' GetsInput='false' Name='Frame' PackSize='absolute,absolute' PackSizeProp='0000/0001,0000/0001' ScrollExtent='7,10' Size='7,10' UserScrollable='false'/>
<Page BackgroundOpacity='0.502' Name='Bkg' PackSize='absolute,absolute' PackSizeProp='0000/0001,0000/0001' ScrollExtent='7,10' Size='7,10'/>
</Page>
<Page Location='0,26' MaximumSize='7,10' MinimumSize='7,10' Name='Pip11' ScrollExtent='7,10' Size='7,10'>
<Page BackgroundColor='#AAAA44' BackgroundOpacity='1.000' Location='2,2' Name='Pip' PackSize='absolute,absolute' PackSizeProp='0004/0001,0004/0001' ScrollExtent='3,6' Size='3,6'/>
<Rectangle Color='#385E61' GetsInput='false' Name='Frame' PackSize='absolute,absolute' PackSizeProp='0000/0001,0000/0001' ScrollExtent='7,10' Size='7,10' UserScrollable='false'/>
<Page BackgroundOpacity='0.502' Name='Bkg' PackSize='absolute,absolute' PackSizeProp='0000/0001,0000/0001' ScrollExtent='7,10' Size='7,10'/>
</Page>
<Page Location='0,38' MaximumSize='7,10' MinimumSize='7,10' Name='Pip10' ScrollExtent='7,10' Size='7,10'>
<Page BackgroundColor='#AAAA44' BackgroundOpacity='1.000' Location='2,2' Name='Pip' PackSize='absolute,absolute' PackSizeProp='0004/0001,0004/0001' ScrollExtent='3,6' Size='3,6'/>
<Rectangle Color='#385E61' GetsInput='false' Name='Frame' PackSize='absolute,absolute' PackSizeProp='0000/0001,0000/0001' ScrollExtent='7,10' Size='7,10' UserScrollable='false'/>
<Page BackgroundOpacity='0.502' Name='Bkg' PackSize='absolute,absolute' PackSizeProp='0000/0001,0000/0001' ScrollExtent='7,10' Size='7,10'/>
</Page>
<Page Location='0,50' MaximumSize='7,10' MinimumSize='7,10' Name='Pip9' ScrollExtent='7,10' Size='7,10'>
<Page BackgroundColor='#AAAA44' BackgroundOpacity='1.000' Location='2,2' Name='Pip' PackSize='absolute,absolute' PackSizeProp='0004/0001,0004/0001' ScrollExtent='3,6' Size='3,6'/>
<Rectangle Color='#385E61' GetsInput='false' Name='Frame' PackSize='absolute,absolute' PackSizeProp='0000/0001,0000/0001' ScrollExtent='7,10' Size='7,10' UserScrollable='false'/>
<Page BackgroundOpacity='0.502' Name='Bkg' PackSize='absolute,absolute' PackSizeProp='0000/0001,0000/0001' ScrollExtent='7,10' Size='7,10'/>
</Page>
<Page Location='0,62' MaximumSize='7,10' MinimumSize='7,10' Name='Pip8' ScrollExtent='7,10' Size='7,10'>
<Page BackgroundColor='#AAAA44' BackgroundOpacity='1.000' Location='2,2' Name='Pip' PackSize='absolute,absolute' PackSizeProp='0004/0001,0004/0001' ScrollExtent='3,6' Size='3,6'/>
<Rectangle Color='#385E61' GetsInput='false' Name='Frame' PackSize='absolute,absolute' PackSizeProp='0000/0001,0000/0001' ScrollExtent='7,10' Size='7,10' UserScrollable='false'/>
<Page BackgroundOpacity='0.502' Name='Bkg' PackSize='absolute,absolute' PackSizeProp='0000/0001,0000/0001' ScrollExtent='7,10' Size='7,10'/>
</Page>
<Page Location='0,74' MaximumSize='7,10' MinimumSize='7,10' Name='Pip7' ScrollExtent='7,10' Size='7,10'>
<Page BackgroundColor='#AAAA44' BackgroundOpacity='1.000' Location='2,2' Name='Pip' PackSize='absolute,absolute' PackSizeProp='0004/0001,0004/0001' ScrollExtent='3,6' Size='3,6'/>
<Rectangle Color='#385E61' GetsInput='false' Name='Frame' PackSize='absolute,absolute' PackSizeProp='0000/0001,0000/0001' ScrollExtent='7,10' Size='7,10' UserScrollable='false'/>
<Page BackgroundOpacity='0.502' Name='Bkg' PackSize='absolute,absolute' PackSizeProp='0000/0001,0000/0001' ScrollExtent='7,10' Size='7,10'/>
</Page>
<Page Location='0,86' MaximumSize='7,10' MinimumSize='7,10' Name='Pip6' ScrollExtent='7,10' Size='7,10'>
<Page BackgroundColor='#AAAA44' BackgroundOpacity='1.000' Location='2,2' Name='Pip' PackSize='absolute,absolute' PackSizeProp='0004/0001,0004/0001' ScrollExtent='3,6' Size='3,6'/>
<Rectangle Color='#385E61' GetsInput='false' Name='Frame' PackSize='absolute,absolute' PackSizeProp='0000/0001,0000/0001' ScrollExtent='7,10' Size='7,10' UserScrollable='false'/>
<Page BackgroundOpacity='0.502' Name='Bkg' PackSize='absolute,absolute' PackSizeProp='0000/0001,0000/0001' ScrollExtent='7,10' Size='7,10'/>
</Page>
<Page Location='0,98' MaximumSize='7,10' MinimumSize='7,10' Name='Pip5' ScrollExtent='7,10' Size='7,10'>
<Page BackgroundColor='#AAAA44' BackgroundOpacity='1.000' Location='2,2' Name='Pip' PackSize='absolute,absolute' PackSizeProp='0004/0001,0004/0001' ScrollExtent='3,6' Size='3,6'/>
<Rectangle Color='#385E61' GetsInput='false' Name='Frame' PackSize='absolute,absolute' PackSizeProp='0000/0001,0000/0001' ScrollExtent='7,10' Size='7,10' UserScrollable='false'/>
<Page BackgroundOpacity='0.502' Name='Bkg' PackSize='absolute,absolute' PackSizeProp='0000/0001,0000/0001' ScrollExtent='7,10' Size='7,10'/>
</Page>
<Page Location='0,110' MaximumSize='7,10' MinimumSize='7,10' Name='Pip4' ScrollExtent='7,10' Size='7,10'>
<Page BackgroundColor='#AAAA44' BackgroundOpacity='1.000' Location='2,2' Name='Pip' PackSize='absolute,absolute' PackSizeProp='0004/0001,0004/0001' ScrollExtent='3,6' Size='3,6'/>
<Rectangle Color='#385E61' GetsInput='false' Name='Frame' PackSize='absolute,absolute' PackSizeProp='0000/0001,0000/0001' ScrollExtent='7,10' Size='7,10' UserScrollable='false'/>
<Page BackgroundOpacity='0.502' Name='Bkg' PackSize='absolute,absolute' PackSizeProp='0000/0001,0000/0001' ScrollExtent='7,10' Size='7,10'/>
</Page>
<Page Location='0,122' MaximumSize='7,10' MinimumSize='7,10' Name='Pip3' ScrollExtent='7,10' Size='7,10'>
<Page BackgroundColor='#AAAA44' BackgroundOpacity='1.000' Location='2,2' Name='Pip' PackSize='absolute,absolute' PackSizeProp='0004/0001,0004/0001' ScrollExtent='3,6' Size='3,6'/>
<Rectangle Color='#385E61' GetsInput='false' Name='Frame' PackSize='absolute,absolute' PackSizeProp='0000/0001,0000/0001' ScrollExtent='7,10' Size='7,10' UserScrollable='false'/>
<Page BackgroundOpacity='0.502' Name='Bkg' PackSize='absolute,absolute' PackSizeProp='0000/0001,0000/0001' ScrollExtent='7,10' Size='7,10'/>
</Page>
<Page Location='0,134' MaximumSize='7,10' MinimumSize='7,10' Name='Pip2' ScrollExtent='7,10' Size='7,10'>
<Page BackgroundColor='#AAAA44' BackgroundOpacity='1.000' Location='2,2' Name='Pip' PackSize='absolute,absolute' PackSizeProp='0004/0001,0004/0001' ScrollExtent='3,6' Size='3,6'/>
<Rectangle Color='#385E61' GetsInput='false' Name='Frame' PackSize='absolute,absolute' PackSizeProp='0000/0001,0000/0001' ScrollExtent='7,10' Size='7,10' UserScrollable='false'/>
<Page BackgroundOpacity='0.502' Name='Bkg' PackSize='absolute,absolute' PackSizeProp='0000/0001,0000/0001' ScrollExtent='7,10' Size='7,10'/>
</Page>
<Page Location='0,146' MaximumSize='7,10' MinimumSize='7,10' Name='Pip1' ScrollExtent='7,10' Size='7,10'>
<Page BackgroundColor='#AAAA44' BackgroundOpacity='1.000' Location='2,2' Name='Pip' PackSize='absolute,absolute' PackSizeProp='0004/0001,0004/0001' ScrollExtent='3,6' Size='3,6'/>
<Rectangle Color='#385E61' GetsInput='false' Name='Frame' PackSize='absolute,absolute' PackSizeProp='0000/0001,0000/0001' ScrollExtent='7,10' Size='7,10' UserScrollable='false'/>
<Page BackgroundOpacity='0.502' Name='Bkg' PackSize='absolute,absolute' PackSizeProp='0000/0001,0000/0001' ScrollExtent='7,10' Size='7,10'/>
</Page>
<Page Location='0,158' MaximumSize='7,10' MinimumSize='7,10' Name='Pip0' ScrollExtent='7,10' Size='7,10'>
<Page BackgroundColor='#AAAA44' BackgroundOpacity='1.000' Location='2,2' Name='Pip' PackSize='absolute,absolute' PackSizeProp='0004/0001,0004/0001' ScrollExtent='3,6' Size='3,6'/>
<Rectangle Color='#385E61' GetsInput='false' Name='Frame' PackSize='absolute,absolute' PackSizeProp='0000/0001,0000/0001' ScrollExtent='7,10' Size='7,10' UserScrollable='false'/>
<Page BackgroundOpacity='0.502' Name='Bkg' PackSize='absolute,absolute' PackSizeProp='0000/0001,0000/0001' ScrollExtent='7,10' Size='7,10'/>
</Page>
</VolumePage>
<Page BackgroundColor='#4444AA' BackgroundOpacity='1.000' Location='19,35' Name='Progress' ScrollExtent='14,164' Size='14,164'/>
<Page BackgroundOpacity='0.502' Location='17,33' Name='ProgressBkg' ScrollExtent='18,168' Size='18,168'/>
<Rectangle Color='#385E61' GetsInput='false' Location='16,32' Name='Frame' ScrollExtent='20,170' Size='20,170' UserScrollable='false'/>
<Text AbsorbsInput='false' Enabled='false' Font='/Fonts.Agency24' LocalText='DONE' Location='0,202' MaxLines='1' Name='Text' PackLocation='left,top' PackLocationProp='0000/0001,0202/0001' ScrollExtent='50,30' Size='50,30' TextAlignment='Center' TextAlignmentVertical='Center' TextColor='#4444EE'>DONE</Text>
<Image AbsorbsInput='false' Location='12,207' Name='Empire' PackLocation='Left,Bottom' PackLocationProp='0012/0001,-025/0001' ScrollExtent='30,26' Size='30,26' Stretch='false' Style='/Frontend.MiniNC' Visible='false'/>
</Page>
<Page BackgroundColor='#00FF00' Location='124,30' Name='TR' PackSize='fixed,fixed' PackSizeProp='0002/0003,0002/0003' ScrollExtent='50,234' Size='50,234'>
<Image AbsorbsInput='false' Location='12,0' Name='EmpireDone' ScrollExtent='28,32' Size='28,32' Style='/Frontend.MiniTR'/>
<Image BackgroundColor='#00FF00' Location='1,0' Name='Vehicle' PackSize='cfn,ffn' ScrollExtent='48,30' Size='48,30' Style='/ItemIcons1GridHigh.liberator_tr'/>
<VolumePage CellCount='1,14' CellPadding='0,2' CellSize='7,10' Location='6,32' MinimumScrollExtent='7,170' Name='Pips' ScrollExtent='7,170' Size='7,170'>
<Page Location='0,2' MaximumSize='7,10' MinimumSize='7,10' Name='Pip13' ScrollExtent='7,10' Size='7,10'>
<Page BackgroundColor='#AAAAAA' BackgroundOpacity='1.000' Location='2,2' Name='Pip' PackSize='absolute,absolute' PackSizeProp='0004/0001,0004/0001' ScrollExtent='3,6' Size='3,6'/>
<Rectangle Color='#385E61' GetsInput='false' Name='Frame' PackSize='absolute,absolute' PackSizeProp='0000/0001,0000/0001' ScrollExtent='7,10' Size='7,10' UserScrollable='false'/>
<Page BackgroundOpacity='0.502' Name='Bkg' PackSize='absolute,absolute' PackSizeProp='0000/0001,0000/0001' ScrollExtent='7,10' Size='7,10'/>
</Page>
<Page Location='0,14' MaximumSize='7,10' MinimumSize='7,10' Name='Pip12' ScrollExtent='7,10' Size='7,10'>
<Page BackgroundColor='#AAAAAA' BackgroundOpacity='1.000' Location='2,2' Name='Pip' PackSize='absolute,absolute' PackSizeProp='0004/0001,0004/0001' ScrollExtent='3,6' Size='3,6'/>
<Rectangle Color='#385E61' GetsInput='false' Name='Frame' PackSize='absolute,absolute' PackSizeProp='0000/0001,0000/0001' ScrollExtent='7,10' Size='7,10' UserScrollable='false'/>
<Page BackgroundOpacity='0.502' Name='Bkg' PackSize='absolute,absolute' PackSizeProp='0000/0001,0000/0001' ScrollExtent='7,10' Size='7,10'/>
</Page>
<Page Location='0,26' MaximumSize='7,10' MinimumSize='7,10' Name='Pip11' ScrollExtent='7,10' Size='7,10'>
<Page BackgroundColor='#AAAAAA' BackgroundOpacity='1.000' Location='2,2' Name='Pip' PackSize='absolute,absolute' PackSizeProp='0004/0001,0004/0001' ScrollExtent='3,6' Size='3,6'/>
<Rectangle Color='#385E61' GetsInput='false' Name='Frame' PackSize='absolute,absolute' PackSizeProp='0000/0001,0000/0001' ScrollExtent='7,10' Size='7,10' UserScrollable='false'/>
<Page BackgroundOpacity='0.502' Name='Bkg' PackSize='absolute,absolute' PackSizeProp='0000/0001,0000/0001' ScrollExtent='7,10' Size='7,10'/>
</Page>
<Page Location='0,38' MaximumSize='7,10' MinimumSize='7,10' Name='Pip10' ScrollExtent='7,10' Size='7,10'>
<Page BackgroundColor='#AAAAAA' BackgroundOpacity='1.000' Location='2,2' Name='Pip' PackSize='absolute,absolute' PackSizeProp='0004/0001,0004/0001' ScrollExtent='3,6' Size='3,6'/>
<Rectangle Color='#385E61' GetsInput='false' Name='Frame' PackSize='absolute,absolute' PackSizeProp='0000/0001,0000/0001' ScrollExtent='7,10' Size='7,10' UserScrollable='false'/>
<Page BackgroundOpacity='0.502' Name='Bkg' PackSize='absolute,absolute' PackSizeProp='0000/0001,0000/0001' ScrollExtent='7,10' Size='7,10'/>
</Page>
<Page Location='0,50' MaximumSize='7,10' MinimumSize='7,10' Name='Pip9' ScrollExtent='7,10' Size='7,10'>
<Page BackgroundColor='#AAAAAA' BackgroundOpacity='1.000' Location='2,2' Name='Pip' PackSize='absolute,absolute' PackSizeProp='0004/0001,0004/0001' ScrollExtent='3,6' Size='3,6'/>
<Rectangle Color='#385E61' GetsInput='false' Name='Frame' PackSize='absolute,absolute' PackSizeProp='0000/0001,0000/0001' ScrollExtent='7,10' Size='7,10' UserScrollable='false'/>
<Page BackgroundOpacity='0.502' Name='Bkg' PackSize='absolute,absolute' PackSizeProp='0000/0001,0000/0001' ScrollExtent='7,10' Size='7,10'/>
</Page>
<Page Location='0,62' MaximumSize='7,10' MinimumSize='7,10' Name='Pip8' ScrollExtent='7,10' Size='7,10'>
<Page BackgroundColor='#AAAAAA' BackgroundOpacity='1.000' Location='2,2' Name='Pip' PackSize='absolute,absolute' PackSizeProp='0004/0001,0004/0001' ScrollExtent='3,6' Size='3,6'/>
<Rectangle Color='#385E61' GetsInput='false' Name='Frame' PackSize='absolute,absolute' PackSizeProp='0000/0001,0000/0001' ScrollExtent='7,10' Size='7,10' UserScrollable='false'/>
<Page BackgroundOpacity='0.502' Name='Bkg' PackSize='absolute,absolute' PackSizeProp='0000/0001,0000/0001' ScrollExtent='7,10' Size='7,10'/>
</Page>
<Page Location='0,74' MaximumSize='7,10' MinimumSize='7,10' Name='Pip7' ScrollExtent='7,10' Size='7,10'>
<Page BackgroundColor='#AAAAAA' BackgroundOpacity='1.000' Location='2,2' Name='Pip' PackSize='absolute,absolute' PackSizeProp='0004/0001,0004/0001' ScrollExtent='3,6' Size='3,6'/>
<Rectangle Color='#385E61' GetsInput='false' Name='Frame' PackSize='absolute,absolute' PackSizeProp='0000/0001,0000/0001' ScrollExtent='7,10' Size='7,10' UserScrollable='false'/>
<Page BackgroundOpacity='0.502' Name='Bkg' PackSize='absolute,absolute' PackSizeProp='0000/0001,0000/0001' ScrollExtent='7,10' Size='7,10'/>
</Page>
<Page Location='0,86' MaximumSize='7,10' MinimumSize='7,10' Name='Pip6' ScrollExtent='7,10' Size='7,10'>
<Page BackgroundColor='#AAAAAA' BackgroundOpacity='1.000' Location='2,2' Name='Pip' PackSize='absolute,absolute' PackSizeProp='0004/0001,0004/0001' ScrollExtent='3,6' Size='3,6'/>
<Rectangle Color='#385E61' GetsInput='false' Name='Frame' PackSize='absolute,absolute' PackSizeProp='0000/0001,0000/0001' ScrollExtent='7,10' Size='7,10' UserScrollable='false'/>
<Page BackgroundOpacity='0.502' Name='Bkg' PackSize='absolute,absolute' PackSizeProp='0000/0001,0000/0001' ScrollExtent='7,10' Size='7,10'/>
</Page>
<Page Location='0,98' MaximumSize='7,10' MinimumSize='7,10' Name='Pip5' ScrollExtent='7,10' Size='7,10'>
<Page BackgroundColor='#AAAAAA' BackgroundOpacity='1.000' Location='2,2' Name='Pip' PackSize='absolute,absolute' PackSizeProp='0004/0001,0004/0001' ScrollExtent='3,6' Size='3,6'/>
<Rectangle Color='#385E61' GetsInput='false' Name='Frame' PackSize='absolute,absolute' PackSizeProp='0000/0001,0000/0001' ScrollExtent='7,10' Size='7,10' UserScrollable='false'/>
<Page BackgroundOpacity='0.502' Name='Bkg' PackSize='absolute,absolute' PackSizeProp='0000/0001,0000/0001' ScrollExtent='7,10' Size='7,10'/>
</Page>
<Page Location='0,110' MaximumSize='7,10' MinimumSize='7,10' Name='Pip4' ScrollExtent='7,10' Size='7,10'>
<Page BackgroundColor='#AAAAAA' BackgroundOpacity='1.000' Location='2,2' Name='Pip' PackSize='absolute,absolute' PackSizeProp='0004/0001,0004/0001' ScrollExtent='3,6' Size='3,6'/>
<Rectangle Color='#385E61' GetsInput='false' Name='Frame' PackSize='absolute,absolute' PackSizeProp='0000/0001,0000/0001' ScrollExtent='7,10' Size='7,10' UserScrollable='false'/>
<Page BackgroundOpacity='0.502' Name='Bkg' PackSize='absolute,absolute' PackSizeProp='0000/0001,0000/0001' ScrollExtent='7,10' Size='7,10'/>
</Page>
<Page Location='0,122' MaximumSize='7,10' MinimumSize='7,10' Name='Pip3' ScrollExtent='7,10' Size='7,10'>
<Page BackgroundColor='#AAAAAA' BackgroundOpacity='1.000' Location='2,2' Name='Pip' PackSize='absolute,absolute' PackSizeProp='0004/0001,0004/0001' ScrollExtent='3,6' Size='3,6'/>
<Rectangle Color='#385E61' GetsInput='false' Name='Frame' PackSize='absolute,absolute' PackSizeProp='0000/0001,0000/0001' ScrollExtent='7,10' Size='7,10' UserScrollable='false'/>
<Page BackgroundOpacity='0.502' Name='Bkg' PackSize='absolute,absolute' PackSizeProp='0000/0001,0000/0001' ScrollExtent='7,10' Size='7,10'/>
</Page>
<Page Location='0,134' MaximumSize='7,10' MinimumSize='7,10' Name='Pip2' ScrollExtent='7,10' Size='7,10'>
<Page BackgroundColor='#AAAAAA' BackgroundOpacity='1.000' Location='2,2' Name='Pip' PackSize='absolute,absolute' PackSizeProp='0004/0001,0004/0001' ScrollExtent='3,6' Size='3,6'/>
<Rectangle Color='#385E61' GetsInput='false' Name='Frame' PackSize='absolute,absolute' PackSizeProp='0000/0001,0000/0001' ScrollExtent='7,10' Size='7,10' UserScrollable='false'/>
<Page BackgroundOpacity='0.502' Name='Bkg' PackSize='absolute,absolute' PackSizeProp='0000/0001,0000/0001' ScrollExtent='7,10' Size='7,10'/>
</Page>
<Page Location='0,146' MaximumSize='7,10' MinimumSize='7,10' Name='Pip1' ScrollExtent='7,10' Size='7,10'>
<Page BackgroundColor='#AAAAAA' BackgroundOpacity='1.000' Location='2,2' Name='Pip' PackSize='absolute,absolute' PackSizeProp='0004/0001,0004/0001' ScrollExtent='3,6' Size='3,6'/>
<Rectangle Color='#385E61' GetsInput='false' Name='Frame' PackSize='absolute,absolute' PackSizeProp='0000/0001,0000/0001' ScrollExtent='7,10' Size='7,10' UserScrollable='false'/>
<Page BackgroundOpacity='0.502' Name='Bkg' PackSize='absolute,absolute' PackSizeProp='0000/0001,0000/0001' ScrollExtent='7,10' Size='7,10'/>
</Page>
<Page Location='0,158' MaximumSize='7,10' MinimumSize='7,10' Name='Pip0' ScrollExtent='7,10' Size='7,10'>
<Page BackgroundColor='#AAAAAA' BackgroundOpacity='1.000' Location='2,2' Name='Pip' PackSize='absolute,absolute' PackSizeProp='0004/0001,0004/0001' ScrollExtent='3,6' Size='3,6'/>
<Rectangle Color='#385E61' GetsInput='false' Name='Frame' PackSize='absolute,absolute' PackSizeProp='0000/0001,0000/0001' ScrollExtent='7,10' Size='7,10' UserScrollable='false'/>
<Page BackgroundOpacity='0.502' Name='Bkg' PackSize='absolute,absolute' PackSizeProp='0000/0001,0000/0001' ScrollExtent='7,10' Size='7,10'/>
</Page>
</VolumePage>
<Page BackgroundColor='#AA0000' BackgroundOpacity='1.000' Location='19,35' Name='Progress' ScrollExtent='14,164' Size='14,164'/>
<Page BackgroundOpacity='0.502' Location='17,33' Name='ProgressBkg' ScrollExtent='18,168' Size='18,168'/>
<Rectangle Color='#385E61' GetsInput='false' Location='16,32' Name='Frame' ScrollExtent='20,170' Size='20,170' UserScrollable='false'/>
<Text AbsorbsInput='false' Enabled='false' Font='/Fonts.Agency24' LocalText='DONE' Location='0,202' MaxLines='1' Name='Text' PackLocation='left,top' PackLocationProp='0000/0001,0202/0001' ScrollExtent='50,30' Size='50,30' TextAlignment='Center' TextAlignmentVertical='Center' TextColor='#DD2222'>DONE</Text>
<Image AbsorbsInput='false' Location='12,203' Name='Empire' PackLocation='Left,Bottom' PackLocationProp='0012/0001,-031/0001' ScrollExtent='28,32' Size='28,32' Stretch='false' Style='/Frontend.MiniTR' Visible='false'/>
</Page>
<Image AbsorbsInput='false' BackgroundOpacity='1.000' Location='1,0' Name='Background' Opacity='0.700' PackSize='absolute,absolute' PackSizeProp='0000/0001,0000/0001' RStyleDefault='/WindowPanes.SmallBackground.style' ScrollExtent='190,278' Size='190,278' Stretch='false' Style=' '/>
</Page>
</Page>
