<Page AbsorbsInput='false' Location='259,251' Name='AvatarOxygen' PackLocation='Center,Center' PackLocationProp='-253/0001,-133/0001' ScrollExtent='506,100' Size='506,100' Visible='false'>
<Text AbsorbsInput='false' Color='#FF0000' Font='/Fonts.HudFont3' LocalText='[@InformationAboutProgress]' Location='76,25' Name='AvatarOxygenText' ScrollExtent='400,21' Size='400,21' TextAlignment='Right'>@InformationAboutProgress</Text>
<Progressbar AbsorbsInput='false' BarBackgroundColor='#FF0000' Color='#777777' Location='29,54' Name='AvatarOxygenBar' Progress='0.700' ScrollExtent='447,13' Size='447,13' Style='/ProgressBars.Oxygen.style' TooltipStyle='/Fonts.DefaultFont'/>
</Page>
