<Page BackgroundColor='#0000FF' Location='880,675' movable='true' Name='Performance' PackLocation='right,top' PackLocationProp='-130/0001,0682/0001' ScrollExtent='75,63' Size='75,63' Visible='false'>
<Text Font='/Fonts.HudFont1' GetsInput='false' LocalText='[@PerformancePing]' Margin='0,0,1,0' Name='PingLabel' ScrollExtent='30,48' ShadowStyle='/Shadows.Default' Size='30,14' TextAlignment='Right'>@PerformancePing</Text>
<Text Font='/Fonts.HudFont1' GetsInput='false' LocalText='88888 ms' Location='38,0' Name='Ping' ScrollExtent='37,24' ShadowStyle='/Shadows.Default' Size='37,14'>88888 ms</Text>
<Text Font='/Fonts.HudFont1' GetsInput='false' LocalText='[@PerformanceLoss]' Location='0,11' Name='LossLabel' ScrollExtent='30,48' ShadowStyle='/Shadows.Default' Size='30,14' TextAlignment='Right'>@PerformanceLoss</Text>
<Text Font='/Fonts.HudFont1' GetsInput='false' LocalText='100%' Location='38,11' Name='Loss' ScrollExtent='37,14' ShadowStyle='/Shadows.Default' Size='37,14'>100%</Text>
<Text Font='/Fonts.HudFont1' GetsInput='false' LocalText='[@PerformanceFPS]' Location='0,22' Name='FramerateLabel' ScrollExtent='30,48' ShadowStyle='/Shadows.Default' Size='30,14' TextAlignment='Right'>@PerformanceFPS</Text>
<Text Font='/Fonts.HudFont1' GetsInput='false' LocalText='XXX' Location='38,22' Name='Framerate' ScrollExtent='37,14' ShadowStyle='/Shadows.Default' Size='37,14'>XXX</Text>
<Rectangle Color='#000000' GetsInput='false' Location='0,36' Name='AdvancedDivider' PackSize='1' PackSizeProp='0002/0003,xxxx/xxxx' ScrollExtent='75,1' Size='75,1' Visible='false'/>
<Text Font='/Fonts.HudFont1' GetsInput='false' LocalText='[@PerformanceUpstream]' Location='0,39' Name='UpstreamLabel' ScrollExtent='60,36' ShadowStyle='/Shadows.Default' Size='60,14'>@PerformanceUpstream</Text>
<Text Font='/Fonts.HudFont1' GetsInput='false' LocalText='1046 b/s' Location='51,39' Name='Upstream' ScrollExtent='47,24' ShadowStyle='/Shadows.Default' Size='47,14' TextAlignment='Center'>1046 b/s</Text>
<Text Font='/Fonts.HudFont1' GetsInput='false' LocalText='[@PerformanceDownstream]' Location='0,49' Name='DownstreamLabel' ScrollExtent='60,36' ShadowStyle='/Shadows.Default' Size='60,14'>@PerformanceDownstream</Text>
<Text Font='/Fonts.HudFont1' GetsInput='false' LocalText='1446 b/s' Location='51,49' Name='Downstream' ScrollExtent='47,24' ShadowStyle='/Shadows.Default' Size='47,14' TextAlignment='Center'>1446 b/s</Text>
</Page>
