<Page Location='647,187' MinimumSize='367,200' movable='true' Name='Snoop' PackLocation='center,center' PackLocationProp='0135/0001,-197/0001' resizable='true' ScrollExtent='367,200' Size='367,200' Visible='false'>
<Scrollbar Control='Text' Location='342,35' Name='TextScroll' PackLocation='right,top' PackLocationProp='-025/0001,0035/0001' PackSize='fixed,absolute' PackSizeProp='0002/0003,0050/0001' ScrollExtent='9,150' Size='9,150' Style='/ScrollBars.vertical.style'/>
<Text AbsorbsInput='false' Font='/Fonts.ChatFont' LocalText='Bob
Two' Location='18,35' Name='Text' PackSize='absolute,absolute' PackSizeProp='0047/0001,0050/0001' ScrollExtent='320,150' Size='320,150'>Bob
Two</Text>
<Text AbsorbsInput='false' Enabled='false' Font='/Fonts.HudFont3' LocalText='[@SnoopTitle]' Location='39,7' Name='TitleText' PackLocation='center,fixed' PackLocationProp='-144/0001,xxxx/xxxx' PackSize='fixed,fixed' PackSizeProp='0002/0003,0002/0003' ScrollExtent='278,20' Size='278,20' TextAlignment='Center' TextAlignmentVertical='Center'>@SnoopTitle</Text>
<Button LocalText='[@Cancel]' Location='278,8' Name='CancelButton' PackLocation='right,top' PackLocationProp='-089/0001,0008/0001' PackSize='fixed,fixed' PackSizeProp='0002/0003,0002/0003' ScrollExtent='16,16' Size='16,16' Style='/Buttons.WindowClose.style'>@Cancel</Button>
<Image AbsorbsInput='false' BackgroundOpacity='1.000' Location='31,0' Name='Title' PackSize='absolute,fixed' PackSizeProp='0071/0001,0002/0003' RStyleActivated='/WindowPanes.TitleBarFocus.style' RStyleDefault='/WindowPanes.TitleBarNoFocus.style' ScrollExtent='296,32' Size='296,32'/>
<Image AbsorbsInput='false' BackgroundOpacity='1.000' Location='0,16' Name='Background' PackSize='1,absolute' PackSizeProp='0002/0003,0012/0001' RStyleDefault='/WindowPanes.SmallBackground.style' ScrollExtent='367,188' Size='367,188' Stretch='false'/>
</Page>
