<Page BackgroundOpacity='1.000' Name='Loading' PackSize='1,1' PackSizeProp='0002/0003,0002/0003' ScrollExtent='1024,768' Size='1024,768' Visible='false'>
<Text Color='#72C9D1' Font='/Fonts.Agency24' LocalText='ZoneName' Location='20,55' Name='ZoneName' PackLocation='proportional,proportional' PackLocationProp='0127/1024,0080/0768' PackSize='fixed,fixed' PackSizeProp='0002/0003,0002/0003' ScrollExtent='214,50' Size='214,50' TextAlignment='Center' TextAlignmentVertical='Bottom'>ZoneName</Text>
<Page BackgroundOpacity='1.000' Location='40,114' Name='Icons' PackLocation='proportional,proportional' PackLocationProp='0126/1024,0119/0768' PackSize='fixed,fixed' PackSizeProp='0002/0003,0002/0003' ScrollExtent='172,11' Size='172,11'>
<Page BackgroundColor='#72C9D1' BackgroundOpacity='1.000' Location='3,3' Name='Textures' PackSize='fixed,absolute' PackSizeProp='0002/0003,0006/0001' ScrollExtent='40,5' Size='40,5'/>
<Page BackgroundColor='#72C9D1' BackgroundOpacity='1.000' Location='45,3' Name='Objects' PackSize='fixed,absolute' PackSizeProp='0002/0003,0006/0001' ScrollExtent='40,5' Size='40,5'/>
<Page BackgroundColor='#72C9D1' BackgroundOpacity='1.000' Location='87,3' Name='Avatars' PackSize='fixed,absolute' PackSizeProp='0002/0003,0006/0001' ScrollExtent='40,5' Size='40,5'/>
<Page BackgroundColor='#72C9D1' BackgroundOpacity='1.000' Location='129,3' Name='Map' PackSize='fixed,absolute' PackSizeProp='0002/0003,0006/0001' ScrollExtent='40,5' Size='40,5'/>
<Rectangle BackgroundOpacity='1.000' Color='#72C9D1' PackLocation='top,left' PackLocationProp='0000/0001,0000/0001' PackSize='1,1' PackSizeProp='0002/0003,0002/0003' ScrollExtent='172,11' Size='172,11'/>
</Page>
<Page BackgroundOpacity='1.000' Location='67,107' Name='_Icons' PackLocation='proportional,proportional' PackLocationProp='0127/1024,0120/0768' PackSize='fixed,fixed' PackSizeProp='0002/0003,0002/0003' ScrollExtent='121,26' Size='121,26' Visible='false'>
<Text Color='#72C9D1' Enabled='false' Font='/Fonts.ButtonIcons' LocalText='6' Location='1,3' Name='Textures' ScrollExtent='38,27' Size='38,27'>6</Text>
<Text Color='#72C9D1' Enabled='false' Font='/Fonts.TabIcons' LocalText='I' Location='31,2' Name='Objects' ScrollExtent='42,27' Size='38,27'>I</Text>
<Text Color='#72C9D1' Enabled='false' Font='/Fonts.ButtonIcons' LocalText='w' Location='68,2' Name='Avatars' ScrollExtent='38,27' Size='38,27'>w</Text>
<Text Color='#72C9D1' Enabled='false' Font='/Fonts.TabIcons' LocalText='C' Location='89,2' Name='Map' ScrollExtent='42,27' Size='38,27'>C</Text>
<Rectangle BackgroundOpacity='1.000' Color='#72C9D1' PackLocation='top,left' PackLocationProp='0000/0001,0000/0001' PackSize='1,1' PackSizeProp='0002/0003,0002/0003' ScrollExtent='121,26' Size='121,26'/>
</Page>
<Image Location='879,666' Name='Intel' PackLocation='right,bottom' PackLocationProp='-145/0001,-102/0001' ScrollExtent='143,98' Size='143,98' Style='IntelLogo' Visible='false'/>
<Page BackgroundOpacity='1.000' Name='TopLetterBox' PackLocation='left,top' PackLocationProp='0000/0001,0000/0001' PackSize='absolute,proportional' PackSizeProp='0000/0001,0121/0768' ScrollExtent='1024,121' Size='1024,121' text='Searhus'>
<Rectangle BackgroundOpacity='1.000' Color='#72C9D1' Location='0,120' Name='TopLetterBoxEdge' PackLocation='left,bottom' PackLocationProp='0000/0001,-001/0001' PackSize='absolute,fixed' PackSizeProp='0000/0001,0002/0003' ScrollExtent='1024,1' Size='1024,1'/>
</Page>
<Page Location='0,623' Name='BottomLetterBox' PackLocation='left,proportional' PackLocationProp='0000/0001,0695/0768' PackSize='absolute,proportional' PackSizeProp='0000/0001,0145/0768' ScrollExtent='1024,145' Size='1024,145'>
<Page BackgroundOpacity='1.000' Location='627,0' Name='Status' PackLocation='right,top' PackLocationProp='-397/0001,0000/0001' PackSize='fixed,fixed' PackSizeProp='0002/0003,0002/0003' ScrollExtent='337,69' Size='337,69'>
<Text Color='#72C9D1' Font='/Fonts.Agency18' LocalText='Current Loading Status Message' Location='4,21' Margin='0,0,3,0' Name='Text' PackSize='Absolute, Absolute' PackSizeProp='0010/0001,xxxx/xxxx' ScrollExtent='327,27' Size='327,27' TextAlignment='Right'>Current Loading Status Message</Text>
<Progressbar BackgroundColor='#000000' BackgroundOpacity='1.000' Color='#72C9D1' Location='3,4' Name='Progress' Progress='1.000' ScrollExtent='331,14' Size='331,14' Style='/ProgressBars.Health.style' TooltipStyle='/Fonts.DefaultFont'/>
<Rectangle BackgroundOpacity='1.000' Color='#72C9D1' PackSize='absolute,absolute' PackSizeProp='0000/0001,0050/0001' ScrollExtent='337,19' Size='337,19'/>
</Page>
<Rectangle BackgroundOpacity='1.000' Color='#72C9D1' Location='0,10' Name='Edge' PackSize='absolute,fixed' PackSizeProp='0000/0001,0002/0003' ScrollExtent='1024,1' Size='1024,1'/>
<Page BackgroundOpacity='1.000' Location='0,10' Name='Fill' PackLocation='left,top' PackLocationProp='0000/0001,0010/0001' PackSize='absolute,absolute' PackSizeProp='0000/0001,0010/0001' ScrollExtent='1024,135' Size='1024,135'/>
</Page>
<Page AbsorbsInput='false' Enabled='false' Location='0,121' Name='Preview' PackLocation='proportional,proportional' PackLocationProp='0512/1024,0377/0768' PackSize='proportional,proportional' PackSizeProp='1024/1024,0512/0768' ScrollExtent='1024,512' Size='1024,512'>
<Image BackgroundOpacity='1.000' Location='979,37' Name='EastBorder' PackLocation='right,top' PackLocationProp='-045/0001,0037/0001' PackSize='fixed,absolute' PackSizeProp='0002/0003,0065/0001' RStyleDefault='/Frontend.EastBorder.style' ScrollExtent='21,447' Size='21,447' Stretch='false' Style=' '/>
<Image BackgroundOpacity='1.000' Location='24,28' Name='WestBorder' PackLocation='left,top' PackLocationProp='0024/0001,0028/0001' PackSize='fixed,absolute' PackSizeProp='0002/0003,0065/0001' RStyleDefault='/Frontend.WestBorder.style' ScrollExtent='21,447' Size='21,447' Stretch='false' Style=' '/>
<Image BackgroundOpacity='1.000' Location='33,466' Name='SouthBorder' PackLocation='left,bottom' PackLocationProp='0033/0001,-046/0001' PackSize='absolute,fixed' PackSizeProp='0057/0001,0002/0003' RStyleDefault='/Frontend.SouthBorder.style' ScrollExtent='967,22' Size='967,22' Stretch='false' Style=' '/>
<Image BackgroundOpacity='1.000' Location='24,24' Name='NorthBorder' PackLocation='left,top' PackLocationProp='0024/0001,0024/0001' PackSize='absolute,fixed' PackSizeProp='0057/0001,0002/0003' RStyleDefault='/Frontend.NorthBorder.style' ScrollExtent='967,22' Size='967,22' Stretch='false' Style=' '/>
<Image AbsorbsInput='false' Enabled='false' Name='MapImage' PackLocation='proportional,proportional' PackLocationProp='0512/1024,0256/0512' PackSize='proportional,proportional' PackSizeProp='1024/1024,0512/0512' ScrollExtent='1024,512' Size='1024,512' Style='home3'/>
</Page>
<ImageStyle Name='IntelLogo'>
<ImageFrame Source='ui_intel_logo_00' SourceRect='0,0,143,98'/>
</ImageStyle>
<ImageStyle Name='TitleLeft'>
<ImageFrame SourceRect='0,0,248,40'>
<ImageFragment Source='ui_loading_text_bg_00' SourceRect='0,0,128,64'/>
<ImageFragment Offset='128,0' Source='ui_loading_text_bg_01' SourceRect='0,0,128,64'/>
<ImageFragment Offset='256,0' Source='ui_loading_text_bg_02' SourceRect='0,0,128,64'/>
<ImageFragment Offset='384,0' Source='ui_loading_text_bg_03' SourceRect='0,0,128,64'/>
</ImageFrame>
</ImageStyle>
<ImageStyle Name='TitleCenter'>
<ImageFrame SourceRect='248,0,254,40'>
<ImageFragment Source='ui_loading_text_bg_00' SourceRect='0,0,128,64'/>
<ImageFragment Offset='128,0' Source='ui_loading_text_bg_01' SourceRect='0,0,128,64'/>
<ImageFragment Offset='256,0' Source='ui_loading_text_bg_02' SourceRect='0,0,128,64'/>
<ImageFragment Offset='384,0' Source='ui_loading_text_bg_03' SourceRect='0,0,128,64'/>
</ImageFrame>
</ImageStyle>
<ImageStyle Name='TitleRight'>
<ImageFrame SourceRect='256,0,508,40'>
<ImageFragment Source='ui_loading_text_bg_00' SourceRect='0,0,128,64'/>
<ImageFragment Offset='128,0' Source='ui_loading_text_bg_01' SourceRect='0,0,128,64'/>
<ImageFragment Offset='256,0' Source='ui_loading_text_bg_02' SourceRect='0,0,128,64'/>
<ImageFragment Offset='384,0' Source='ui_loading_text_bg_03' SourceRect='0,0,128,64'/>
</ImageFrame>
</ImageStyle>
<RectangleStyle Center='TitleCenter' CenterShrinkH='true' CenterShrinkV='true' CenterStretchH='true' CenterStretchV='true' East='TitleRight' Name='TitleStyle' West='TitleLeft'/>
<ImageStyle Name='z1'>
<ImageFrame>
<ImageFragment Source='ui_loading_map01_00' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,0' Source='ui_loading_map01_01' SourceRect='0,0,256,256'/>
<ImageFragment Offset='512,0' Source='ui_loading_map01_02' SourceRect='0,0,256,256'/>
<ImageFragment Offset='768,0' Source='ui_loading_map01_03' SourceRect='0,0,256,256'/>
<ImageFragment Offset='0,256' Source='ui_loading_map01_04' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,256' Source='ui_loading_map01_05' SourceRect='0,0,256,256'/>
<ImageFragment Offset='512,256' Source='ui_loading_map01_06' SourceRect='0,0,256,256'/>
<ImageFragment Offset='768,256' Source='ui_loading_map01_07' SourceRect='0,0,256,256'/>
</ImageFrame>
</ImageStyle>
<ImageStyle Name='z2'>
<ImageFrame>
<ImageFragment Source='ui_loading_map02_00' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,0' Source='ui_loading_map02_01' SourceRect='0,0,256,256'/>
<ImageFragment Offset='512,0' Source='ui_loading_map02_02' SourceRect='0,0,256,256'/>
<ImageFragment Offset='768,0' Source='ui_loading_map02_03' SourceRect='0,0,256,256'/>
<ImageFragment Offset='0,256' Source='ui_loading_map02_04' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,256' Source='ui_loading_map02_05' SourceRect='0,0,256,256'/>
<ImageFragment Offset='512,256' Source='ui_loading_map02_06' SourceRect='0,0,256,256'/>
<ImageFragment Offset='768,256' Source='ui_loading_map02_07' SourceRect='0,0,256,256'/>
</ImageFrame>
</ImageStyle>
<ImageStyle Name='z3'>
<ImageFrame>
<ImageFragment Source='ui_loading_map03_00' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,0' Source='ui_loading_map03_01' SourceRect='0,0,256,256'/>
<ImageFragment Offset='512,0' Source='ui_loading_map03_02' SourceRect='0,0,256,256'/>
<ImageFragment Offset='768,0' Source='ui_loading_map03_03' SourceRect='0,0,256,256'/>
<ImageFragment Offset='0,256' Source='ui_loading_map03_04' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,256' Source='ui_loading_map03_05' SourceRect='0,0,256,256'/>
<ImageFragment Offset='512,256' Source='ui_loading_map03_06' SourceRect='0,0,256,256'/>
<ImageFragment Offset='768,256' Source='ui_loading_map03_07' SourceRect='0,0,256,256'/>
</ImageFrame>
</ImageStyle>
<ImageStyle Name='z4'>
<ImageFrame>
<ImageFragment Source='ui_loading_map04_00' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,0' Source='ui_loading_map04_01' SourceRect='0,0,256,256'/>
<ImageFragment Offset='512,0' Source='ui_loading_map04_02' SourceRect='0,0,256,256'/>
<ImageFragment Offset='768,0' Source='ui_loading_map04_03' SourceRect='0,0,256,256'/>
<ImageFragment Offset='0,256' Source='ui_loading_map04_04' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,256' Source='ui_loading_map04_05' SourceRect='0,0,256,256'/>
<ImageFragment Offset='512,256' Source='ui_loading_map04_06' SourceRect='0,0,256,256'/>
<ImageFragment Offset='768,256' Source='ui_loading_map04_07' SourceRect='0,0,256,256'/>
</ImageFrame>
</ImageStyle>
<ImageStyle Name='z5'>
<ImageFrame>
<ImageFragment Source='ui_loading_map05_00' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,0' Source='ui_loading_map05_01' SourceRect='0,0,256,256'/>
<ImageFragment Offset='512,0' Source='ui_loading_map05_02' SourceRect='0,0,256,256'/>
<ImageFragment Offset='768,0' Source='ui_loading_map05_03' SourceRect='0,0,256,256'/>
<ImageFragment Offset='0,256' Source='ui_loading_map05_04' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,256' Source='ui_loading_map05_05' SourceRect='0,0,256,256'/>
<ImageFragment Offset='512,256' Source='ui_loading_map05_06' SourceRect='0,0,256,256'/>
<ImageFragment Offset='768,256' Source='ui_loading_map05_07' SourceRect='0,0,256,256'/>
</ImageFrame>
</ImageStyle>
<ImageStyle Name='z6'>
<ImageFrame>
<ImageFragment Source='ui_loading_map06_00' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,0' Source='ui_loading_map06_01' SourceRect='0,0,256,256'/>
<ImageFragment Offset='512,0' Source='ui_loading_map06_02' SourceRect='0,0,256,256'/>
<ImageFragment Offset='768,0' Source='ui_loading_map06_03' SourceRect='0,0,256,256'/>
<ImageFragment Offset='0,256' Source='ui_loading_map06_04' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,256' Source='ui_loading_map06_05' SourceRect='0,0,256,256'/>
<ImageFragment Offset='512,256' Source='ui_loading_map06_06' SourceRect='0,0,256,256'/>
<ImageFragment Offset='768,256' Source='ui_loading_map06_07' SourceRect='0,0,256,256'/>
</ImageFrame>
</ImageStyle>
<ImageStyle Name='z7'>
<ImageFrame>
<ImageFragment Source='ui_loading_map07_00' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,0' Source='ui_loading_map07_01' SourceRect='0,0,256,256'/>
<ImageFragment Offset='512,0' Source='ui_loading_map07_02' SourceRect='0,0,256,256'/>
<ImageFragment Offset='768,0' Source='ui_loading_map07_03' SourceRect='0,0,256,256'/>
<ImageFragment Offset='0,256' Source='ui_loading_map07_04' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,256' Source='ui_loading_map07_05' SourceRect='0,0,256,256'/>
<ImageFragment Offset='512,256' Source='ui_loading_map07_06' SourceRect='0,0,256,256'/>
<ImageFragment Offset='768,256' Source='ui_loading_map07_07' SourceRect='0,0,256,256'/>
</ImageFrame>
</ImageStyle>
<ImageStyle Name='z9'>
<ImageFrame>
<ImageFragment Source='ui_loading_map09_00' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,0' Source='ui_loading_map09_01' SourceRect='0,0,256,256'/>
<ImageFragment Offset='512,0' Source='ui_loading_map09_02' SourceRect='0,0,256,256'/>
<ImageFragment Offset='768,0' Source='ui_loading_map09_03' SourceRect='0,0,256,256'/>
<ImageFragment Offset='0,256' Source='ui_loading_map09_04' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,256' Source='ui_loading_map09_05' SourceRect='0,0,256,256'/>
<ImageFragment Offset='512,256' Source='ui_loading_map09_06' SourceRect='0,0,256,256'/>
<ImageFragment Offset='768,256' Source='ui_loading_map09_07' SourceRect='0,0,256,256'/>
</ImageFrame>
</ImageStyle>
<ImageStyle Name='z10'>
<ImageFrame>
<ImageFragment Source='ui_loading_map10_00' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,0' Source='ui_loading_map10_01' SourceRect='0,0,256,256'/>
<ImageFragment Offset='512,0' Source='ui_loading_map10_02' SourceRect='0,0,256,256'/>
<ImageFragment Offset='768,0' Source='ui_loading_map10_03' SourceRect='0,0,256,256'/>
<ImageFragment Offset='0,256' Source='ui_loading_map10_04' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,256' Source='ui_loading_map10_05' SourceRect='0,0,256,256'/>
<ImageFragment Offset='512,256' Source='ui_loading_map10_06' SourceRect='0,0,256,256'/>
<ImageFragment Offset='768,256' Source='ui_loading_map10_07' SourceRect='0,0,256,256'/>
</ImageFrame>
</ImageStyle>
<ImageStyle Name='home1'>
<ImageFrame>
<ImageFragment Source='ui_loading_map11_00' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,0' Source='ui_loading_map11_01' SourceRect='0,0,256,256'/>
<ImageFragment Offset='512,0' Source='ui_loading_map11_02' SourceRect='0,0,256,256'/>
<ImageFragment Offset='768,0' Source='ui_loading_map11_03' SourceRect='0,0,256,256'/>
<ImageFragment Offset='0,256' Source='ui_loading_map11_04' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,256' Source='ui_loading_map11_05' SourceRect='0,0,256,256'/>
<ImageFragment Offset='512,256' Source='ui_loading_map11_06' SourceRect='0,0,256,256'/>
<ImageFragment Offset='768,256' Source='ui_loading_map11_07' SourceRect='0,0,256,256'/>
</ImageFrame>
</ImageStyle>
<ImageStyle Name='home2'>
<ImageFrame>
<ImageFragment Source='ui_loading_map12_00' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,0' Source='ui_loading_map12_01' SourceRect='0,0,256,256'/>
<ImageFragment Offset='512,0' Source='ui_loading_map12_02' SourceRect='0,0,256,256'/>
<ImageFragment Offset='768,0' Source='ui_loading_map12_03' SourceRect='0,0,256,256'/>
<ImageFragment Offset='0,256' Source='ui_loading_map12_04' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,256' Source='ui_loading_map12_05' SourceRect='0,0,256,256'/>
<ImageFragment Offset='512,256' Source='ui_loading_map12_06' SourceRect='0,0,256,256'/>
<ImageFragment Offset='768,256' Source='ui_loading_map12_07' SourceRect='0,0,256,256'/>
</ImageFrame>
</ImageStyle>
<ImageStyle Name='home3'>
<ImageFrame>
<ImageFragment Source='ui_loading_map13_00' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,0' Source='ui_loading_map13_01' SourceRect='0,0,256,256'/>
<ImageFragment Offset='512,0' Source='ui_loading_map13_02' SourceRect='0,0,256,256'/>
<ImageFragment Offset='768,0' Source='ui_loading_map13_03' SourceRect='0,0,256,256'/>
<ImageFragment Offset='0,256' Source='ui_loading_map13_04' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,256' Source='ui_loading_map13_05' SourceRect='0,0,256,256'/>
<ImageFragment Offset='512,256' Source='ui_loading_map13_06' SourceRect='0,0,256,256'/>
<ImageFragment Offset='768,256' Source='ui_loading_map13_07' SourceRect='0,0,256,256'/>
</ImageFrame>
</ImageStyle>
<ImageStyle Name='tzshtr'>
<ImageFrame>
<ImageFragment Source='ui_loading_map14_00' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,0' Source='ui_loading_map14_01' SourceRect='0,0,256,256'/>
<ImageFragment Offset='512,0' Source='ui_loading_map14_02' SourceRect='0,0,256,256'/>
<ImageFragment Offset='768,0' Source='ui_loading_map14_03' SourceRect='0,0,256,256'/>
<ImageFragment Offset='0,256' Source='ui_loading_map14_04' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,256' Source='ui_loading_map14_05' SourceRect='0,0,256,256'/>
<ImageFragment Offset='512,256' Source='ui_loading_map14_06' SourceRect='0,0,256,256'/>
<ImageFragment Offset='768,256' Source='ui_loading_map14_07' SourceRect='0,0,256,256'/>
<ImageFragment Offset='0,512' Source='ui_loading_map14_08' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,512' Source='ui_loading_map14_09' SourceRect='0,0,256,256'/>
<ImageFragment Offset='512,512' Source='ui_loading_map14_10' SourceRect='0,0,256,256'/>
<ImageFragment Offset='768,512' Source='ui_loading_map14_11' SourceRect='0,0,256,256'/>
</ImageFrame>
</ImageStyle>
<ImageStyle Name='tzdrtr'>
<ImageFrame>
<ImageFragment Source='ui_loading_map15_00' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,0' Source='ui_loading_map15_01' SourceRect='0,0,256,256'/>
<ImageFragment Offset='512,0' Source='ui_loading_map15_02' SourceRect='0,0,256,256'/>
<ImageFragment Offset='768,0' Source='ui_loading_map15_03' SourceRect='0,0,256,256'/>
<ImageFragment Offset='0,256' Source='ui_loading_map15_04' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,256' Source='ui_loading_map15_05' SourceRect='0,0,256,256'/>
<ImageFragment Offset='512,256' Source='ui_loading_map15_06' SourceRect='0,0,256,256'/>
<ImageFragment Offset='768,256' Source='ui_loading_map15_07' SourceRect='0,0,256,256'/>
<ImageFragment Offset='0,512' Source='ui_loading_map15_08' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,512' Source='ui_loading_map15_09' SourceRect='0,0,256,256'/>
<ImageFragment Offset='512,512' Source='ui_loading_map15_10' SourceRect='0,0,256,256'/>
<ImageFragment Offset='768,512' Source='ui_loading_map15_11' SourceRect='0,0,256,256'/>
</ImageFrame>
</ImageStyle>
<ImageStyle Name='tzcotr'>
<ImageFrame>
<ImageFragment Source='ui_loading_map16_00' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,0' Source='ui_loading_map16_01' SourceRect='0,0,256,256'/>
<ImageFragment Offset='512,0' Source='ui_loading_map16_02' SourceRect='0,0,256,256'/>
<ImageFragment Offset='768,0' Source='ui_loading_map16_03' SourceRect='0,0,256,256'/>
<ImageFragment Offset='0,256' Source='ui_loading_map16_04' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,256' Source='ui_loading_map16_05' SourceRect='0,0,256,256'/>
<ImageFragment Offset='512,256' Source='ui_loading_map16_06' SourceRect='0,0,256,256'/>
<ImageFragment Offset='768,256' Source='ui_loading_map16_07' SourceRect='0,0,256,256'/>
<ImageFragment Offset='0,512' Source='ui_loading_map16_08' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,512' Source='ui_loading_map16_09' SourceRect='0,0,256,256'/>
<ImageFragment Offset='512,512' Source='ui_loading_map16_10' SourceRect='0,0,256,256'/>
<ImageFragment Offset='768,512' Source='ui_loading_map16_11' SourceRect='0,0,256,256'/>
</ImageFrame>
</ImageStyle>
<ImageStyle Name='tzshnc'>
<ImageFrame>
<ImageFragment Source='ui_loading_map14_00' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,0' Source='ui_loading_map14_01' SourceRect='0,0,256,256'/>
<ImageFragment Offset='512,0' Source='ui_loading_map14_02' SourceRect='0,0,256,256'/>
<ImageFragment Offset='768,0' Source='ui_loading_map14_03' SourceRect='0,0,256,256'/>
<ImageFragment Offset='0,256' Source='ui_loading_map14_04' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,256' Source='ui_loading_map14_05' SourceRect='0,0,256,256'/>
<ImageFragment Offset='512,256' Source='ui_loading_map14_06' SourceRect='0,0,256,256'/>
<ImageFragment Offset='768,256' Source='ui_loading_map14_07' SourceRect='0,0,256,256'/>
<ImageFragment Offset='0,512' Source='ui_loading_map14_08' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,512' Source='ui_loading_map14_09' SourceRect='0,0,256,256'/>
<ImageFragment Offset='512,512' Source='ui_loading_map14_10' SourceRect='0,0,256,256'/>
<ImageFragment Offset='768,512' Source='ui_loading_map14_11' SourceRect='0,0,256,256'/>
</ImageFrame>
</ImageStyle>
<ImageStyle Name='tzdrnc'>
<ImageFrame>
<ImageFragment Source='ui_loading_map15_00' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,0' Source='ui_loading_map15_01' SourceRect='0,0,256,256'/>
<ImageFragment Offset='512,0' Source='ui_loading_map15_02' SourceRect='0,0,256,256'/>
<ImageFragment Offset='768,0' Source='ui_loading_map15_03' SourceRect='0,0,256,256'/>
<ImageFragment Offset='0,256' Source='ui_loading_map15_04' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,256' Source='ui_loading_map15_05' SourceRect='0,0,256,256'/>
<ImageFragment Offset='512,256' Source='ui_loading_map15_06' SourceRect='0,0,256,256'/>
<ImageFragment Offset='768,256' Source='ui_loading_map15_07' SourceRect='0,0,256,256'/>
<ImageFragment Offset='0,512' Source='ui_loading_map15_08' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,512' Source='ui_loading_map15_09' SourceRect='0,0,256,256'/>
<ImageFragment Offset='512,512' Source='ui_loading_map15_10' SourceRect='0,0,256,256'/>
<ImageFragment Offset='768,512' Source='ui_loading_map15_11' SourceRect='0,0,256,256'/>
</ImageFrame>
</ImageStyle>
<ImageStyle Name='tzconc'>
<ImageFrame>
<ImageFragment Source='ui_loading_map16_00' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,0' Source='ui_loading_map16_01' SourceRect='0,0,256,256'/>
<ImageFragment Offset='512,0' Source='ui_loading_map16_02' SourceRect='0,0,256,256'/>
<ImageFragment Offset='768,0' Source='ui_loading_map16_03' SourceRect='0,0,256,256'/>
<ImageFragment Offset='0,256' Source='ui_loading_map16_04' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,256' Source='ui_loading_map16_05' SourceRect='0,0,256,256'/>
<ImageFragment Offset='512,256' Source='ui_loading_map16_06' SourceRect='0,0,256,256'/>
<ImageFragment Offset='768,256' Source='ui_loading_map16_07' SourceRect='0,0,256,256'/>
<ImageFragment Offset='0,512' Source='ui_loading_map16_08' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,512' Source='ui_loading_map16_09' SourceRect='0,0,256,256'/>
<ImageFragment Offset='512,512' Source='ui_loading_map16_10' SourceRect='0,0,256,256'/>
<ImageFragment Offset='768,512' Source='ui_loading_map16_11' SourceRect='0,0,256,256'/>
</ImageFrame>
</ImageStyle>
<ImageStyle Name='tzshvs'>
<ImageFrame>
<ImageFragment Source='ui_loading_map14_00' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,0' Source='ui_loading_map14_01' SourceRect='0,0,256,256'/>
<ImageFragment Offset='512,0' Source='ui_loading_map14_02' SourceRect='0,0,256,256'/>
<ImageFragment Offset='768,0' Source='ui_loading_map14_03' SourceRect='0,0,256,256'/>
<ImageFragment Offset='0,256' Source='ui_loading_map14_04' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,256' Source='ui_loading_map14_05' SourceRect='0,0,256,256'/>
<ImageFragment Offset='512,256' Source='ui_loading_map14_06' SourceRect='0,0,256,256'/>
<ImageFragment Offset='768,256' Source='ui_loading_map14_07' SourceRect='0,0,256,256'/>
<ImageFragment Offset='0,512' Source='ui_loading_map14_08' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,512' Source='ui_loading_map14_09' SourceRect='0,0,256,256'/>
<ImageFragment Offset='512,512' Source='ui_loading_map14_10' SourceRect='0,0,256,256'/>
<ImageFragment Offset='768,512' Source='ui_loading_map14_11' SourceRect='0,0,256,256'/>
</ImageFrame>
</ImageStyle>
<ImageStyle Name='tzdrvs'>
<ImageFrame>
<ImageFragment Source='ui_loading_map15_00' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,0' Source='ui_loading_map15_01' SourceRect='0,0,256,256'/>
<ImageFragment Offset='512,0' Source='ui_loading_map15_02' SourceRect='0,0,256,256'/>
<ImageFragment Offset='768,0' Source='ui_loading_map15_03' SourceRect='0,0,256,256'/>
<ImageFragment Offset='0,256' Source='ui_loading_map15_04' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,256' Source='ui_loading_map15_05' SourceRect='0,0,256,256'/>
<ImageFragment Offset='512,256' Source='ui_loading_map15_06' SourceRect='0,0,256,256'/>
<ImageFragment Offset='768,256' Source='ui_loading_map15_07' SourceRect='0,0,256,256'/>
<ImageFragment Offset='0,512' Source='ui_loading_map15_08' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,512' Source='ui_loading_map15_09' SourceRect='0,0,256,256'/>
<ImageFragment Offset='512,512' Source='ui_loading_map15_10' SourceRect='0,0,256,256'/>
<ImageFragment Offset='768,512' Source='ui_loading_map15_11' SourceRect='0,0,256,256'/>
</ImageFrame>
</ImageStyle>
<ImageStyle Name='tzcovs'>
<ImageFrame>
<ImageFragment Source='ui_loading_map16_00' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,0' Source='ui_loading_map16_01' SourceRect='0,0,256,256'/>
<ImageFragment Offset='512,0' Source='ui_loading_map16_02' SourceRect='0,0,256,256'/>
<ImageFragment Offset='768,0' Source='ui_loading_map16_03' SourceRect='0,0,256,256'/>
<ImageFragment Offset='0,256' Source='ui_loading_map16_04' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,256' Source='ui_loading_map16_05' SourceRect='0,0,256,256'/>
<ImageFragment Offset='512,256' Source='ui_loading_map16_06' SourceRect='0,0,256,256'/>
<ImageFragment Offset='768,256' Source='ui_loading_map16_07' SourceRect='0,0,256,256'/>
<ImageFragment Offset='0,512' Source='ui_loading_map16_08' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,512' Source='ui_loading_map16_09' SourceRect='0,0,256,256'/>
<ImageFragment Offset='512,512' Source='ui_loading_map16_10' SourceRect='0,0,256,256'/>
<ImageFragment Offset='768,512' Source='ui_loading_map16_11' SourceRect='0,0,256,256'/>
</ImageFrame>
</ImageStyle>
<ImageStyle Name='orbital0'>
<ImageFrame>
<ImageFragment Source='ui_loading_trdrop_00' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,0' Source='ui_loading_trdrop_01' SourceRect='0,0,256,256'/>
<ImageFragment Offset='512,0' Source='ui_loading_trdrop_02' SourceRect='0,0,256,256'/>
<ImageFragment Offset='768,0' Source='ui_loading_trdrop_03' SourceRect='0,0,256,256'/>
<ImageFragment Offset='0,256' Source='ui_loading_trdrop_04' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,256' Source='ui_loading_trdrop_05' SourceRect='0,0,256,256'/>
<ImageFragment Offset='512,256' Source='ui_loading_trdrop_06' SourceRect='0,0,256,256'/>
<ImageFragment Offset='768,256' Source='ui_loading_trdrop_07' SourceRect='0,0,256,256'/>
<ImageFragment Offset='0,512' Source='ui_loading_trdrop_08' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,512' Source='ui_loading_trdrop_09' SourceRect='0,0,256,256'/>
<ImageFragment Offset='512,512' Source='ui_loading_trdrop_10' SourceRect='0,0,256,256'/>
<ImageFragment Offset='768,512' Source='ui_loading_trdrop_11' SourceRect='0,0,256,256'/>
</ImageFrame>
</ImageStyle>
<ImageStyle Name='orbital1'>
<ImageFrame>
<ImageFragment Source='ui_loading_ncdrop_00' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,0' Source='ui_loading_ncdrop_01' SourceRect='0,0,256,256'/>
<ImageFragment Offset='512,0' Source='ui_loading_ncdrop_02' SourceRect='0,0,256,256'/>
<ImageFragment Offset='768,0' Source='ui_loading_ncdrop_03' SourceRect='0,0,256,256'/>
<ImageFragment Offset='0,256' Source='ui_loading_ncdrop_04' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,256' Source='ui_loading_ncdrop_05' SourceRect='0,0,256,256'/>
<ImageFragment Offset='512,256' Source='ui_loading_ncdrop_06' SourceRect='0,0,256,256'/>
<ImageFragment Offset='768,256' Source='ui_loading_ncdrop_07' SourceRect='0,0,256,256'/>
<ImageFragment Offset='0,512' Source='ui_loading_ncdrop_08' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,512' Source='ui_loading_ncdrop_09' SourceRect='0,0,256,256'/>
<ImageFragment Offset='512,512' Source='ui_loading_ncdrop_10' SourceRect='0,0,256,256'/>
<ImageFragment Offset='768,512' Source='ui_loading_ncdrop_11' SourceRect='0,0,256,256'/>
</ImageFrame>
</ImageStyle>
<ImageStyle Name='orbital2'>
<ImageFrame>
<ImageFragment Source='ui_loading_vsdrop_00' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,0' Source='ui_loading_vsdrop_01' SourceRect='0,0,256,256'/>
<ImageFragment Offset='512,0' Source='ui_loading_vsdrop_02' SourceRect='0,0,256,256'/>
<ImageFragment Offset='768,0' Source='ui_loading_vsdrop_03' SourceRect='0,0,256,256'/>
<ImageFragment Offset='0,256' Source='ui_loading_vsdrop_04' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,256' Source='ui_loading_vsdrop_05' SourceRect='0,0,256,256'/>
<ImageFragment Offset='512,256' Source='ui_loading_vsdrop_06' SourceRect='0,0,256,256'/>
<ImageFragment Offset='768,256' Source='ui_loading_vsdrop_07' SourceRect='0,0,256,256'/>
<ImageFragment Offset='0,512' Source='ui_loading_vsdrop_08' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,512' Source='ui_loading_vsdrop_09' SourceRect='0,0,256,256'/>
<ImageFragment Offset='512,512' Source='ui_loading_vsdrop_10' SourceRect='0,0,256,256'/>
<ImageFragment Offset='768,512' Source='ui_loading_vsdrop_11' SourceRect='0,0,256,256'/>
</ImageFrame>
</ImageStyle>
<ImageStyle Name='station1'>
<ImageFrame>
<ImageFragment Source='ui_loading_orbital_tr_00' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,0' Source='ui_loading_orbital_tr_01' SourceRect='0,0,256,256'/>
<ImageFragment Offset='512,0' Source='ui_loading_orbital_tr_02' SourceRect='0,0,256,256'/>
<ImageFragment Offset='768,0' Source='ui_loading_orbital_tr_03' SourceRect='0,0,256,256'/>
<ImageFragment Offset='0,256' Source='ui_loading_orbital_tr_04' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,256' Source='ui_loading_orbital_tr_05' SourceRect='0,0,256,256'/>
<ImageFragment Offset='512,256' Source='ui_loading_orbital_tr_06' SourceRect='0,0,256,256'/>
<ImageFragment Offset='768,256' Source='ui_loading_orbital_tr_07' SourceRect='0,0,256,256'/>
<ImageFragment Offset='0,512' Source='ui_loading_orbital_tr_08' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,512' Source='ui_loading_orbital_tr_09' SourceRect='0,0,256,256'/>
<ImageFragment Offset='512,512' Source='ui_loading_orbital_tr_10' SourceRect='0,0,256,256'/>
<ImageFragment Offset='768,512' Source='ui_loading_orbital_tr_11' SourceRect='0,0,256,256'/>
</ImageFrame>
</ImageStyle>
<ImageStyle Name='station2'>
<ImageFrame>
<ImageFragment Source='ui_loading_orbital_nc_00' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,0' Source='ui_loading_orbital_nc_01' SourceRect='0,0,256,256'/>
<ImageFragment Offset='512,0' Source='ui_loading_orbital_nc_02' SourceRect='0,0,256,256'/>
<ImageFragment Offset='768,0' Source='ui_loading_orbital_nc_03' SourceRect='0,0,256,256'/>
<ImageFragment Offset='0,256' Source='ui_loading_orbital_nc_04' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,256' Source='ui_loading_orbital_nc_05' SourceRect='0,0,256,256'/>
<ImageFragment Offset='512,256' Source='ui_loading_orbital_nc_06' SourceRect='0,0,256,256'/>
<ImageFragment Offset='768,256' Source='ui_loading_orbital_nc_07' SourceRect='0,0,256,256'/>
<ImageFragment Offset='0,512' Source='ui_loading_orbital_nc_08' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,512' Source='ui_loading_orbital_nc_09' SourceRect='0,0,256,256'/>
<ImageFragment Offset='512,512' Source='ui_loading_orbital_nc_10' SourceRect='0,0,256,256'/>
<ImageFragment Offset='768,512' Source='ui_loading_orbital_nc_11' SourceRect='0,0,256,256'/>
</ImageFrame>
</ImageStyle>
<ImageStyle Name='station3'>
<ImageFrame>
<ImageFragment Source='ui_loading_orbital_vs_00' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,0' Source='ui_loading_orbital_vs_01' SourceRect='0,0,256,256'/>
<ImageFragment Offset='512,0' Source='ui_loading_orbital_vs_02' SourceRect='0,0,256,256'/>
<ImageFragment Offset='768,0' Source='ui_loading_orbital_vs_03' SourceRect='0,0,256,256'/>
<ImageFragment Offset='0,256' Source='ui_loading_orbital_vs_04' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,256' Source='ui_loading_orbital_vs_05' SourceRect='0,0,256,256'/>
<ImageFragment Offset='512,256' Source='ui_loading_orbital_vs_06' SourceRect='0,0,256,256'/>
<ImageFragment Offset='768,256' Source='ui_loading_orbital_vs_07' SourceRect='0,0,256,256'/>
<ImageFragment Offset='0,512' Source='ui_loading_orbital_vs_08' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,512' Source='ui_loading_orbital_vs_09' SourceRect='0,0,256,256'/>
<ImageFragment Offset='512,512' Source='ui_loading_orbital_vs_10' SourceRect='0,0,256,256'/>
<ImageFragment Offset='768,512' Source='ui_loading_orbital_vs_11' SourceRect='0,0,256,256'/>
</ImageFrame>
</ImageStyle>
<ImageStyle Name='c1'>
<ImageFrame>
<ImageFragment Source='ui_loading_ugd1_00' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,0' Source='ui_loading_ugd1_01' SourceRect='0,0,256,256'/>
<ImageFragment Offset='512,0' Source='ui_loading_ugd1_02' SourceRect='0,0,256,256'/>
<ImageFragment Offset='768,0' Source='ui_loading_ugd1_03' SourceRect='0,0,256,256'/>
<ImageFragment Offset='0,256' Source='ui_loading_ugd1_04' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,256' Source='ui_loading_ugd1_05' SourceRect='0,0,256,256'/>
<ImageFragment Offset='512,256' Source='ui_loading_ugd1_06' SourceRect='0,0,256,256'/>
<ImageFragment Offset='768,256' Source='ui_loading_ugd1_07' SourceRect='0,0,256,256'/>
<ImageFragment Offset='0,512' Source='ui_loading_ugd1_08' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,512' Source='ui_loading_ugd1_09' SourceRect='0,0,256,256'/>
<ImageFragment Offset='512,512' Source='ui_loading_ugd1_10' SourceRect='0,0,256,256'/>
<ImageFragment Offset='768,512' Source='ui_loading_ugd1_11' SourceRect='0,0,256,256'/>
</ImageFrame>
</ImageStyle>
<ImageStyle Name='c2'>
<ImageFrame>
<ImageFragment Source='ui_loading_ugd2_00' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,0' Source='ui_loading_ugd2_01' SourceRect='0,0,256,256'/>
<ImageFragment Offset='512,0' Source='ui_loading_ugd2_02' SourceRect='0,0,256,256'/>
<ImageFragment Offset='768,0' Source='ui_loading_ugd2_03' SourceRect='0,0,256,256'/>
<ImageFragment Offset='0,256' Source='ui_loading_ugd2_04' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,256' Source='ui_loading_ugd2_05' SourceRect='0,0,256,256'/>
<ImageFragment Offset='512,256' Source='ui_loading_ugd2_06' SourceRect='0,0,256,256'/>
<ImageFragment Offset='768,256' Source='ui_loading_ugd2_07' SourceRect='0,0,256,256'/>
<ImageFragment Offset='0,512' Source='ui_loading_ugd2_08' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,512' Source='ui_loading_ugd2_09' SourceRect='0,0,256,256'/>
<ImageFragment Offset='512,512' Source='ui_loading_ugd2_10' SourceRect='0,0,256,256'/>
<ImageFragment Offset='768,512' Source='ui_loading_ugd2_11' SourceRect='0,0,256,256'/>
</ImageFrame>
</ImageStyle>
<ImageStyle Name='c3'>
<ImageFrame>
<ImageFragment Source='ui_loading_ugd3_00' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,0' Source='ui_loading_ugd3_01' SourceRect='0,0,256,256'/>
<ImageFragment Offset='512,0' Source='ui_loading_ugd3_02' SourceRect='0,0,256,256'/>
<ImageFragment Offset='768,0' Source='ui_loading_ugd3_03' SourceRect='0,0,256,256'/>
<ImageFragment Offset='0,256' Source='ui_loading_ugd3_04' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,256' Source='ui_loading_ugd3_05' SourceRect='0,0,256,256'/>
<ImageFragment Offset='512,256' Source='ui_loading_ugd3_06' SourceRect='0,0,256,256'/>
<ImageFragment Offset='768,256' Source='ui_loading_ugd3_07' SourceRect='0,0,256,256'/>
<ImageFragment Offset='0,512' Source='ui_loading_ugd3_08' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,512' Source='ui_loading_ugd3_09' SourceRect='0,0,256,256'/>
<ImageFragment Offset='512,512' Source='ui_loading_ugd3_10' SourceRect='0,0,256,256'/>
<ImageFragment Offset='768,512' Source='ui_loading_ugd3_11' SourceRect='0,0,256,256'/>
</ImageFrame>
</ImageStyle>
<ImageStyle Name='c4'>
<ImageFrame>
<ImageFragment Source='ui_loading_ugd4_00' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,0' Source='ui_loading_ugd4_01' SourceRect='0,0,256,256'/>
<ImageFragment Offset='512,0' Source='ui_loading_ugd4_02' SourceRect='0,0,256,256'/>
<ImageFragment Offset='768,0' Source='ui_loading_ugd4_03' SourceRect='0,0,256,256'/>
<ImageFragment Offset='0,256' Source='ui_loading_ugd4_04' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,256' Source='ui_loading_ugd4_05' SourceRect='0,0,256,256'/>
<ImageFragment Offset='512,256' Source='ui_loading_ugd4_06' SourceRect='0,0,256,256'/>
<ImageFragment Offset='768,256' Source='ui_loading_ugd4_07' SourceRect='0,0,256,256'/>
<ImageFragment Offset='0,512' Source='ui_loading_ugd4_08' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,512' Source='ui_loading_ugd4_09' SourceRect='0,0,256,256'/>
<ImageFragment Offset='512,512' Source='ui_loading_ugd4_10' SourceRect='0,0,256,256'/>
<ImageFragment Offset='768,512' Source='ui_loading_ugd4_11' SourceRect='0,0,256,256'/>
</ImageFrame>
</ImageStyle>
<ImageStyle Name='c5'>
<ImageFrame>
<ImageFragment Source='ui_loading_ugd5_00' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,0' Source='ui_loading_ugd5_01' SourceRect='0,0,256,256'/>
<ImageFragment Offset='512,0' Source='ui_loading_ugd5_02' SourceRect='0,0,256,256'/>
<ImageFragment Offset='768,0' Source='ui_loading_ugd5_03' SourceRect='0,0,256,256'/>
<ImageFragment Offset='0,256' Source='ui_loading_ugd5_04' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,256' Source='ui_loading_ugd5_05' SourceRect='0,0,256,256'/>
<ImageFragment Offset='512,256' Source='ui_loading_ugd5_06' SourceRect='0,0,256,256'/>
<ImageFragment Offset='768,256' Source='ui_loading_ugd5_07' SourceRect='0,0,256,256'/>
<ImageFragment Offset='0,512' Source='ui_loading_ugd5_08' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,512' Source='ui_loading_ugd5_09' SourceRect='0,0,256,256'/>
<ImageFragment Offset='512,512' Source='ui_loading_ugd5_10' SourceRect='0,0,256,256'/>
<ImageFragment Offset='768,512' Source='ui_loading_ugd5_11' SourceRect='0,0,256,256'/>
</ImageFrame>
</ImageStyle>
<ImageStyle Name='c6'>
<ImageFrame>
<ImageFragment Source='ui_loading_ugd6_00' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,0' Source='ui_loading_ugd6_01' SourceRect='0,0,256,256'/>
<ImageFragment Offset='512,0' Source='ui_loading_ugd6_02' SourceRect='0,0,256,256'/>
<ImageFragment Offset='768,0' Source='ui_loading_ugd6_03' SourceRect='0,0,256,256'/>
<ImageFragment Offset='0,256' Source='ui_loading_ugd6_04' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,256' Source='ui_loading_ugd6_05' SourceRect='0,0,256,256'/>
<ImageFragment Offset='512,256' Source='ui_loading_ugd6_06' SourceRect='0,0,256,256'/>
<ImageFragment Offset='768,256' Source='ui_loading_ugd6_07' SourceRect='0,0,256,256'/>
<ImageFragment Offset='0,512' Source='ui_loading_ugd6_08' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,512' Source='ui_loading_ugd6_09' SourceRect='0,0,256,256'/>
<ImageFragment Offset='512,512' Source='ui_loading_ugd6_10' SourceRect='0,0,256,256'/>
<ImageFragment Offset='768,512' Source='ui_loading_ugd6_11' SourceRect='0,0,256,256'/>
</ImageFrame>
</ImageStyle>
<ImageStyle Name='i1'>
<ImageFrame>
<ImageFragment Source='ui_loading_map99_00' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,0' Source='ui_loading_map99_01' SourceRect='0,0,256,256'/>
<ImageFragment Offset='512,0' Source='ui_loading_map99_02' SourceRect='0,0,256,256'/>
<ImageFragment Offset='768,0' Source='ui_loading_map99_03' SourceRect='0,0,256,256'/>
<ImageFragment Offset='0,256' Source='ui_loading_map99_04' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,256' Source='ui_loading_map99_05' SourceRect='0,0,256,256'/>
<ImageFragment Offset='512,256' Source='ui_loading_map99_06' SourceRect='0,0,256,256'/>
<ImageFragment Offset='768,256' Source='ui_loading_map99_07' SourceRect='0,0,256,256'/>
</ImageFrame>
</ImageStyle>
<ImageStyle Name='i2'>
<ImageFrame>
<ImageFragment Source='ui_loading_map98_00' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,0' Source='ui_loading_map98_01' SourceRect='0,0,256,256'/>
<ImageFragment Offset='512,0' Source='ui_loading_map98_02' SourceRect='0,0,256,256'/>
<ImageFragment Offset='768,0' Source='ui_loading_map98_03' SourceRect='0,0,256,256'/>
<ImageFragment Offset='0,256' Source='ui_loading_map98_04' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,256' Source='ui_loading_map98_05' SourceRect='0,0,256,256'/>
<ImageFragment Offset='512,256' Source='ui_loading_map98_06' SourceRect='0,0,256,256'/>
<ImageFragment Offset='768,256' Source='ui_loading_map98_07' SourceRect='0,0,256,256'/>
</ImageFrame>
</ImageStyle>
<ImageStyle Name='i3'>
<ImageFrame>
<ImageFragment Source='ui_loading_map97_00' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,0' Source='ui_loading_map97_01' SourceRect='0,0,256,256'/>
<ImageFragment Offset='512,0' Source='ui_loading_map97_02' SourceRect='0,0,256,256'/>
<ImageFragment Offset='768,0' Source='ui_loading_map97_03' SourceRect='0,0,256,256'/>
<ImageFragment Offset='0,256' Source='ui_loading_map97_04' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,256' Source='ui_loading_map97_05' SourceRect='0,0,256,256'/>
<ImageFragment Offset='512,256' Source='ui_loading_map97_06' SourceRect='0,0,256,256'/>
<ImageFragment Offset='768,256' Source='ui_loading_map97_07' SourceRect='0,0,256,256'/>
</ImageFrame>
</ImageStyle>
<ImageStyle Name='i4'>
<ImageFrame>
<ImageFragment Source='ui_loading_map96_00' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,0' Source='ui_loading_map96_01' SourceRect='0,0,256,256'/>
<ImageFragment Offset='512,0' Source='ui_loading_map96_02' SourceRect='0,0,256,256'/>
<ImageFragment Offset='768,0' Source='ui_loading_map96_03' SourceRect='0,0,256,256'/>
<ImageFragment Offset='0,256' Source='ui_loading_map96_04' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,256' Source='ui_loading_map96_05' SourceRect='0,0,256,256'/>
<ImageFragment Offset='512,256' Source='ui_loading_map96_06' SourceRect='0,0,256,256'/>
<ImageFragment Offset='768,256' Source='ui_loading_map96_07' SourceRect='0,0,256,256'/>
</ImageFrame>
</ImageStyle>
<ImageStyle Name='t1'>
<ImageFrame>
<ImageFragment Source='ui_loading_map96_00' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,0' Source='ui_loading_map96_01' SourceRect='0,0,256,256'/>
<ImageFragment Offset='512,0' Source='ui_loading_map96_02' SourceRect='0,0,256,256'/>
<ImageFragment Offset='768,0' Source='ui_loading_map96_03' SourceRect='0,0,256,256'/>
<ImageFragment Offset='0,256' Source='ui_loading_map96_04' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,256' Source='ui_loading_map96_05' SourceRect='0,0,256,256'/>
<ImageFragment Offset='512,256' Source='ui_loading_map96_06' SourceRect='0,0,256,256'/>
<ImageFragment Offset='768,256' Source='ui_loading_map96_07' SourceRect='0,0,256,256'/>
</ImageFrame>
</ImageStyle>
</Page>
