<Page Name='Map' PackLocation='center,center' PackLocationProp='-512/0001,-384/0001' PackSize='fixed,fixed' PackSizeProp='0002/0003,0002/0003' runengine='True' ScrollExtent='1022,767' Size='1022,767' Visible='false' wantsinput='Shared'>
<Page Location='674,393' Name='ContextButtonPage' ScrollExtent='51,30' Size='51,30'>
<Button LocalText='Q' LocalTooltip='[@MapFindMeTooltip]' Location='7,4' Name='FindMeButton' ScrollExtent='39,20' Size='39,20' Style='/Buttons.IconButton.style' Tooltip='@MapFindMeTooltip'>Q</Button>
</Page>
<Page Location='732,393' Name='SquadButtonPage' ScrollExtent='174,30' Size='174,30' Visible='false'>
<Button LocalText='W' LocalTooltip='[@MapSquadAddTooltip]' Location='0,4' Name='InviteButton' ScrollExtent='39,20' Size='39,20' Style='/Buttons.IconButton.style' Tooltip='@MapSquadAddTooltip'>W</Button>
<Button LocalText='c' LocalTooltip='[@MapSquadFindTooltip]' Location='0,4' Name='FindButton' ScrollExtent='39,20' Size='39,20' Style='/Buttons.IconButton.style' Tooltip='@MapSquadFindTooltip'>c</Button>
<Button LocalText='+' LocalTooltip='[@MapSquadWingTooltip]' Location='41,4' Name='WingButton' ScrollExtent='39,20' Size='39,20' Style='/Buttons.IconButton.style' Tooltip='@MapSquadWingTooltip'>+</Button>
<Button LocalText='E' LocalTooltip='[@MapSquadPromoteTooltip]' Location='82,4' Name='PromoteButton' ScrollExtent='39,20' Size='39,20' Style='/Buttons.IconButton.style' Tooltip='@MapSquadPromoteTooltip'>E</Button>
<Button LocalText='X' LocalTooltip='[@MapSquadKickTooltip]' Location='124,4' Name='KickButton' ScrollExtent='39,20' Size='39,20' Style='/Buttons.IconButton.style' Tooltip='@MapSquadKickTooltip'>X</Button>
</Page>
<Page Location='732,393' Name='PriorityButtonPage' ScrollExtent='129,30' Size='129,30' Visible='false'>
<Button LocalText='%' LocalTooltip='[@MapPriorityAddTooltip]' Location='41,4' Name='AddButton' ScrollExtent='39,20' Size='39,20' Style='/Buttons.IconButton.style' Tooltip='@MapPriorityAddTooltip'>%</Button>
<Button LocalText='&' LocalTooltip='[@MapPriorityDeleteTooltip]' Location='82,4' Name='DeleteButton' ScrollExtent='39,20' Size='39,20' Style='/Buttons.IconButton.style' Tooltip='@MapPriorityDeleteTooltip'>&</Button>
<Button LocalText='(' LocalTooltip='[@MapPriorityFindTooltip]' Location='0,4' Name='FindButton' ScrollExtent='39,20' Size='39,20' Style='/Buttons.IconButton.style' Tooltip='@MapPriorityFindTooltip'>(</Button>
</Page>
<Page Location='732,393' Name='WaypointButtonPage' ScrollExtent='124,30' Size='124,30'>
<Button LocalText='?' LocalTooltip='[@MapWaypointFindTooltip]' Location='0,4' Name='FindButton' ScrollExtent='39,20' Size='39,20' Style='/Buttons.IconButton.style' Tooltip='@MapWaypointFindTooltip'>?</Button>
<Button LocalText='\>' LocalTooltip='[@MapWaypointDeleteTooltip]' Location='82,4' Name='DeleteButton' ScrollExtent='39,20' Size='39,20' Style='/Buttons.IconButton.style' Tooltip='@MapWaypointDeleteTooltip'>\></Button>
<Button LocalText='=' LocalTooltip='[@MapWaypointAddTooltip]' Location='41,4' Name='AddButton' ScrollExtent='39,20' Size='39,20' Style='/Buttons.IconButton.style' Tooltip='@MapWaypointAddTooltip'>=</Button>
</Page>
<Page Location='907,392' Name='FacilityButtonPage' ScrollExtent='82,30' Size='82,30'>
<Button LocalText='$' LocalTooltip='[@FindClaimedFacilityTooltip]' Location='0,4' Name='FindButton' ScrollExtent='39,20' Size='39,20' Style='/Buttons.IconButton.style' Tooltip='@FindClaimedFacilityTooltip'>$</Button>
<Button LocalText='[@]' LocalTooltip='[@AddClaimedFacilityTooltip]' Location='41,4' Name='AddButton' ScrollExtent='39,20' Size='39,20' Style='/Buttons.IconButton.style' Tooltip='@AddClaimedFacilityTooltip'>@</Button>
<Button LocalText='#' LocalTooltip='[@DeleteClaimedFacilityTooltip]' Location='41,4' Name='DeleteButton' ScrollExtent='39,20' Size='39,20' Style='/Buttons.IconButton.style' Tooltip='@DeleteClaimedFacilityTooltip'>#</Button>
</Page>
<Image BackgroundOpacity='1.000' Location='674,392' Name='ButtonBorder' PackLocation='left,bottom' PackLocationProp='0674/0001,-375/0001' PackSize='absolute,fixed' PackSizeProp='0703/0001,0002/0003' RStyleDefault='/WindowPanes.ButtonBorder.style' ScrollExtent='319,31' Size='319,31'/>
<Page Location='670,536' MinimumScrollExtent='415,178' Name='Chat' ScrollExtent='415,178' Size='328,172'>
<Image BackgroundOpacity='1.000' Location='3,2' Name='ButtonBorder' PackLocation='left,bottom' PackLocationProp='0003/0001,-176/0001' PackSize='absolute,fixed' PackSizeProp='0096/0001,0002/0003' RStyleDefault='/WindowPanes.ButtonBorder.style' ScrollExtent='319,31' Size='319,31'/>
<Rectangle Color='#385E61' Dragable='true' DragGoodCursor=' ' Location='2,146' Name='InputBorder' PackLocation='left,top' PackLocationProp='0002/0001,0146/0001' PackSize='absolute,fixed' PackSizeProp='0094/0001,0002/0003' ScrollExtent='321,25' Size='321,25' Visible='false'/>
<Text AbsorbsInput='false' Enabled='false' Font='/Fonts.ButtonIcons' LocalText='r' Location='13,2' Name='TempThreat' PackLocation='left,top' PackLocationProp='0013/0001,0002/0001' ScrollExtent='41,30' Size='41,30' TextAlignment='Center' TextAlignmentVertical='Center'>r</Text>
<Text AbsorbsInput='false' Enabled='false' Font='/Fonts.ButtonIcons' LocalText='s' Location='54,2' Name='TempThreat' PackLocation='left,top' PackLocationProp='0054/0001,0002/0001' ScrollExtent='41,30' Size='41,30' TextAlignment='Center' TextAlignmentVertical='Center'>s</Text>
<Text AbsorbsInput='false' Enabled='false' Font='/Fonts.ButtonIcons' LocalText='u' Location='187,2' Name='TempThreat' PackLocation='right,top' PackLocationProp='-228/0001,0002/0001' ScrollExtent='41,30' Size='41,30' TextAlignment='Center' TextAlignmentVertical='Center'>u</Text>
<Text AbsorbsInput='false' Enabled='false' Font='/Fonts.ButtonIcons' LocalText='w' Location='228,2' Name='TempThreat' PackLocation='right,top' PackLocationProp='-187/0001,0002/0001' ScrollExtent='41,30' Size='41,30' TextAlignment='Center' TextAlignmentVertical='Center'>w</Text>
<Text AbsorbsInput='false' Enabled='false' Font='/Fonts.ButtonIcons' LocalText='x' Location='269,2' Name='TempThreat' PackLocation='right,top' PackLocationProp='-146/0001,0002/0001' ScrollExtent='41,30' Size='41,30' TextAlignment='Center' TextAlignmentVertical='Center'>x</Text>
<Text AbsorbsInput='false' Enabled='false' Font='/Fonts.ButtonIcons' LocalText='v' Location='146,2' Name='TempThreat' PackLocation='right,top' PackLocationProp='-269/0001,0002/0001' ScrollExtent='41,30' Size='41,30' TextAlignment='Center' TextAlignmentVertical='Center'>v</Text>
<Text AbsorbsInput='false' Enabled='false' Font='/Fonts.ButtonIcons' LocalText='t' Location='105,2' Name='TempThreat' PackLocation='right,top' PackLocationProp='-310/0001,0002/0001' ScrollExtent='41,30' Size='41,30' TextAlignment='Center' TextAlignmentVertical='Center'>t</Text>
<Checkbox Activated='true' BackgroundOpacity='1.000' Checked='true' LocalTooltip='[@SpeakCheckTooltip]' Location='14,7' Name='SpeakRadio' PackLocation='left,top' PackLocationProp='0014/0001,0007/0001' ScrollExtent='39,20' Size='39,20' Style='/Buttons.IconButton.checkstyle' Tooltip='@SpeakCheckTooltip'>r</Checkbox>
<Checkbox BackgroundOpacity='1.000' LocalTooltip='[@ListenCheckTooltip]' Location='55,7' Name='ListenRadio' PackLocation='left,top' PackLocationProp='0055/0001,0007/0001' ScrollExtent='39,20' Size='39,20' Style='/Buttons.IconButton.checkstyle' Tooltip='@ListenCheckTooltip'>s</Checkbox>
<Checkbox BackgroundOpacity='1.000' LocalTooltip='[@OpenCheckTooltip]' Location='106,7' Name='OpenChatCheck' PackLocation='right,top' PackLocationProp='-309/0001,0007/0001' ScrollExtent='39,20' Size='39,20' Style='/Buttons.IconButton.checkstyle' Tooltip='@OpenCheckTooltip'>t</Checkbox>
<Checkbox Activated='true' BackgroundOpacity='1.000' Checked='true' LocalTooltip='[@SquadCheckTooltip]' Location='147,7' Name='SquadCheck' PackLocation='right,top' PackLocationProp='-268/0001,0007/0001' ScrollExtent='39,20' Size='39,20' Style='/Buttons.IconButton.checkstyle' Tooltip='@SquadCheckTooltip'>v</Checkbox>
<Checkbox Activated='true' BackgroundOpacity='1.000' Checked='true' LocalTooltip='[@OutfitCheckTooltip]' Location='188,7' Name='OutfitCheck' PackLocation='right,top' PackLocationProp='-227/0001,0007/0001' ScrollExtent='39,20' Size='39,20' Style='/Buttons.IconButton.checkstyle' Tooltip='@OutfitCheckTooltip'>u</Checkbox>
<Checkbox Activated='true' BackgroundOpacity='1.000' Checked='true' LocalTooltip='[@CommandCheckTooltip]' Location='229,7' Name='CommandCheck' PackLocation='right,top' PackLocationProp='-186/0001,0007/0001' ScrollExtent='39,20' Size='39,20' Style='/Buttons.IconButton.checkstyle' Tooltip='@CommandCheckTooltip'>w</Checkbox>
<Checkbox Activated='true' BackgroundOpacity='1.000' Checked='true' LocalTooltip='[@AllianceCheckTooltip]' Location='270,7' Name='AllianceCheck' PackLocation='right,top' PackLocationProp='-145/0001,0007/0001' ScrollExtent='39,20' Size='39,20' Style='/Buttons.IconButton.checkstyle' Tooltip='@AllianceCheckTooltip'>x</Checkbox>
<Rectangle Color='#385E61' Cursor='/Cursors.DividerGood' Dragable='true' DragBadCursor='/Cursors.DividerBad' DragGoodCursor='/Cursors.DividerGood' DragType='Divider' Location='3,87' Name='OutputDivider' PackLocation='left,top' PackLocationProp='0003/0001,0087/0001' PackSize='absolute,fixed' PackSizeProp='0094/0001,0002/0003' ScrollExtent='321,1' Size='321,1'/>
<Text DragAccepts='Divider' DragBadCursor='/Cursors.DividerBad' DragGoodCursor='/Cursors.DividerGood' Font='/Fonts.ChatFont' GetsInput='false' Location='8,35' minheight='32' Name='OutputStatus' PackSize='Absolute,Fixed' PackSizeProp='0110/0001,0002/0003' ScrollExtent='305,54' Size='305,54'></Text>
<Scrollbar Control='OutputStatus' getsheartbeat='true' Location='314,35' Name='ScrollOutputStatus' PackLocation='Right, Top' PackLocationProp='-101/0001,xxxx/xxxx' ScrollExtent='10,52' Size='10,52' Style='/ScrollBars.vertical.style'/>
<Text DragAccepts='Divider' DragBadCursor='/Cursors.DividerBad' DragGoodCursor='/Cursors.DividerGood' Font='/Fonts.ChatFont' GetsInput='false' Location='7,89' minheight='32' Name='OutputChat' PackLocation='left,top' PackLocationProp='0007/0001,0089/0001' PackSize='Absolute,Absolute' PackSizeProp='0111/0001,0122/0001' ScrollExtent='304,56' Size='304,56'></Text>
<Scrollbar Control='OutputChat' getsheartbeat='true' Location='314,91' Name='ScrollOutputChat' PackLocation='Right, Top' PackLocationProp='-101/0001,xxxx/xxxx' PackSize='Fixed,Absolute' PackSizeProp='0002/0003,0126/0001' ScrollExtent='11,52' Size='11,52' Style='/ScrollBars.vertical.style'/>
<Textbox BackgroundColor='#DDDDDD' BackgroundOpacity='0.475' Location='3,148' MaxLength='127' Name='Input' PackLocation='left,bottom' PackLocationProp='0003/0001,-030/0001' PackSize='absolute,fixed' PackSizeProp='0096/0001,0002/0003' ScrollExtent='319,22' Size='319,22' Style='TextboxStyle'></Textbox>
<TextboxStyle CaratColor='#00F2C9' CaratWidth='2' Name='TextboxStyle' NormalTextStyle='/Fonts.ChatFont' SelectionColor='#444444' TextColor='#FFFFFF' TextPadding='4,6,2,2'/>
<Text BackgroundOpacity='0.800' Location='2,36' Name='Border' ScrollExtent='321,109' Size='321,109'></Text>
<Text BackgroundOpacity='0.800' Location='1,148' Name='Border' ScrollExtent='320,24' Size='320,24'></Text>
</Page>
<Image BackgroundOpacity='1.000' Location='167,60' Name='TabBorderTop1' PackLocation='left,top' PackLocationProp='0167/0001,0060/0001' PackSize='fixed,fixed' PackSizeProp='0002/0003,0002/0003' ScrollExtent='8,2' Size='8,2' Style='TabBorderTopStyle'/>
<Image BackgroundOpacity='1.000' Location='315,60' Name='TabBorderTopRight' PackLocation='left,top' PackLocationProp='0315/0001,0060/0001' PackSize='absolute,fixed' PackSizeProp='0340/0001,0002/0003' ScrollExtent='682,2' Size='682,2' Style='TabBorderTopStyle'/>
<ImageStyle Name='TabBorderTopStyle'>
<ImageFrame Source='ui_window_map_tab_border_00' SourceRect='8,0,24,2'/>
</ImageStyle>
<Image BackgroundOpacity='1.000' Location='25,60' Name='TabBorder' PackLocation='left,top' PackLocationProp='0025/0001,0060/0001' PackSize='absolute,absolute' PackSizeProp='0048/0001,0083/0001' RStyleDefault='/WindowPanes.BigTabBorder.style' ScrollExtent='974,684' Size='974,684' visualeditlock='true'/>
<Text Font='/Fonts.HudFont3' LocalText='[@MapTitle]' Location='286,8' Name='TitleText' PackLocation='center,top' PackLocationProp='-225/0001,0008/0001' PackSize='fixed,fixed' PackSizeProp='0002/0003,0002/0003' ScrollExtent='388,20' Size='388,20' TextAlignment='Center' TextAlignmentVertical='Center'>@MapTitle</Text>
<Button LocalText='[@Cancel]' LocalTooltip='[@HelpTooltip]' Location='69,8' Name='HelpButton' PackLocation='left,top' PackLocationProp='0069/0001,0008/0001' PackSize='fixed,fixed' PackSizeProp='0002/0003,0002/0003' ScrollExtent='16,16' Size='16,16' Style='/Buttons.WindowHelp.style' Tooltip='@HelpTooltip'>@Cancel</Button>
<Button LocalText='[@Cancel]' LocalTooltip='[@CloseTooltip]' Location='935,8' Name='CloseButton' PackLocation='right,top' PackLocationProp='-087/0001,0008/0001' PackSize='fixed,fixed' PackSizeProp='0002/0003,0002/0003' ScrollExtent='16,16' Size='16,16' Style='/Buttons.WindowClose.style' Tooltip='@CloseTooltip'>@Cancel</Button>
<Page BackgroundColor='#00FFFF' BackgroundOpacity='0.475' Location='31,66' Name='GlobalMapBob' ScrollExtent='503,505' Size='503,505' Visible='false'>
<Page AbsorbsInput='false' Name='Text' ScrollExtent='504,501' Size='504,501'>
<Text continentid='1' Font='/Fonts.DefaultFont' GetsInput='false' LocalText='[@Solsar]' Location='-2,314' Name='Solsar' PackLocation='proportional,proportional' PackLocationProp='0048/0504,0325/0501' PackSize='fixed,fixed' PackSizeProp='0002/0003,0002/0003' ScrollExtent='100,22' ShadowStyle='/Shadows.Default' Size='100,22' TextAlignment='Center' TextAlignmentVertical='Center'>@Solsar</Text>
<Text continentid='2' Font='/Fonts.DefaultFont' GetsInput='false' LocalText='[@Hossin]' Location='335,51' Name='Hossin' PackLocation='proportional,proportional' PackLocationProp='0402/0504,0062/0501' PackSize='fixed,fixed' PackSizeProp='0002/0003,0002/0003' ScrollExtent='135,22' ShadowStyle='/Shadows.Default' Size='135,22' TextAlignment='Center' TextAlignmentVertical='Center'>@Hossin</Text>
<Text continentid='3' Font='/Fonts.DefaultFont' GetsInput='false' LocalText='[@Cyssor]' Location='132,272' Name='Cyssor' PackLocation='proportional,proportional' PackLocationProp='0190/0504,0283/0501' PackSize='fixed,fixed' PackSizeProp='0002/0003,0002/0003' ScrollExtent='117,22' ShadowStyle='/Shadows.Default' Size='117,22' TextAlignment='Center' TextAlignmentVertical='Center'>@Cyssor</Text>
<Text continentid='4' Font='/Fonts.DefaultFont' GetsInput='false' LocalText='[@Ishundar]' Location='225,95' Name='Ishundar' PackLocation='proportional,proportional' PackLocationProp='0289/0504,0106/0501' PackSize='fixed,fixed' PackSizeProp='0002/0003,0002/0003' ScrollExtent='128,22' ShadowStyle='/Shadows.Default' Size='128,22' TextAlignment='Center' TextAlignmentVertical='Center'>@Ishundar</Text>
<Text continentid='5' Font='/Fonts.DefaultFont' GetsInput='false' LocalText='[@Forseral]' Location='24,178' Name='Forseral' PackLocation='proportional,proportional' PackLocationProp='0078/0504,0189/0501' PackSize='fixed,fixed' PackSizeProp='0002/0003,0002/0003' ScrollExtent='108,22' ShadowStyle='/Shadows.Default' Size='108,22' TextAlignment='Center' TextAlignmentVertical='Center'>@Forseral</Text>
<Text continentid='6' Font='/Fonts.DefaultFont' GetsInput='false' LocalText='[@Ceryshen]' Location='93,41' Name='Ceryshen' PackLocation='proportional,proportional' PackLocationProp='0152/0504,0052/0501' PackSize='fixed,fixed' PackSizeProp='0002/0003,0002/0003' ScrollExtent='118,22' ShadowStyle='/Shadows.Default' Size='118,22' TextAlignment='Center' TextAlignmentVertical='Center'>@Ceryshen</Text>
<Text continentid='7' Font='/Fonts.DefaultFont' GetsInput='false' LocalText='[@Esamir]' Location='319,410' Name='Esamir' PackLocation='proportional,proportional' PackLocationProp='0390/0504,0421/0501' PackSize='fixed,fixed' PackSizeProp='0002/0003,0002/0003' ScrollExtent='142,22' ShadowStyle='/Shadows.Default' Size='142,22' TextAlignment='Center' TextAlignmentVertical='Center'>@Esamir</Text>
<Text continentid='8' Font='/Fonts.DefaultFont' GetsInput='false' LocalText='[@Oshur]' Location='405,235' Name='Oshur' PackLocation='proportional,proportional' PackLocationProp='0453/0504,0246/0501' PackSize='fixed,fixed' PackSizeProp='0002/0003,0002/0003' ScrollExtent='97,22' ShadowStyle='/Shadows.Default' Size='97,22' TextAlignment='Center' TextAlignmentVertical='Center'>@Oshur</Text>
<Text continentid='9' Font='/Fonts.DefaultFont' GetsInput='false' LocalText='[@Searhus]' Location='276,300' Name='Searhus' PackLocation='proportional,proportional' PackLocationProp='0336/0504,0311/0501' PackSize='fixed,fixed' PackSizeProp='0002/0003,0002/0003' ScrollExtent='121,22' ShadowStyle='/Shadows.Default' Size='121,22' TextAlignment='Center' TextAlignmentVertical='Center'>@Searhus</Text>
<Text continentid='10' Font='/Fonts.DefaultFont' GetsInput='false' LocalText='[@Amerish]' Location='24,445' Name='Amerish' PackLocation='proportional,proportional' PackLocationProp='0090/0504,0456/0501' PackSize='fixed,fixed' PackSizeProp='0002/0003,0002/0003' ScrollExtent='132,22' ShadowStyle='/Shadows.Default' Size='132,22' TextAlignment='Center' TextAlignmentVertical='Center'>@Amerish</Text>
<Text continentid='11' Font='/Fonts.DefaultFont' GetsInput='false' LocalText='[@NCBase]' Location='164,373' Name='SanctuaryNC' PackLocation='proportional,proportional' PackLocationProp='0225/0504,0384/0501' PackSize='fixed,fixed' PackSizeProp='0002/0003,0002/0003' ScrollExtent='122,22' ShadowStyle='/Shadows.Default' Size='122,22' TextAlignment='Center' TextAlignmentVertical='Center'>@NCBase</Text>
<Text continentid='12' Font='/Fonts.DefaultFont' GetsInput='false' LocalText='[@TRBase]' Location='128,150' Name='SanctuaryTR' PackLocation='proportional,proportional' PackLocationProp='0191/0504,0161/0501' PackSize='fixed,fixed' PackSizeProp='0002/0003,0002/0003' ScrollExtent='126,22' ShadowStyle='/Shadows.Default' Size='126,22' TextAlignment='Center' TextAlignmentVertical='Center'>@TRBase</Text>
<Text continentid='13' Font='/Fonts.DefaultFont' GetsInput='false' LocalText='[@VSBase]' Location='318,178' Name='SanctuaryVS' PackLocation='proportional,proportional' PackLocationProp='0381/0504,0189/0501' PackSize='fixed,fixed' PackSizeProp='0002/0003,0002/0003' ScrollExtent='126,22' ShadowStyle='/Shadows.Default' Size='126,22' TextAlignment='Center' TextAlignmentVertical='Center'>@VSBase</Text>
</Page>
<Image AbsorbsInput='false' BackgroundOpacity='1.000' Color='#800080' continentendpoint1='2' continentendpoint2='13' Location='328,121' Name='Connection1' Rotation='0.250' RStyleDefault='ConnectionStyle.style' ScrollExtent='108,16' Size='108,16'/>
<Image AbsorbsInput='false' BackgroundOpacity='1.000' Color='#800080' continentendpoint1='4' continentendpoint2='13' Location='285,125' Name='Connection2' Rotation='0.160' RStyleDefault='ConnectionStyle.style' ScrollExtent='115,16' Size='115,16'/>
<Image AbsorbsInput='false' BackgroundOpacity='1.000' Color='#800080' continentendpoint1='7' continentendpoint2='13' Location='289,289' Name='Connection3' Rotation='0.220' RStyleDefault='ConnectionStyle.style' ScrollExtent='208,16' Size='208,16'/>
<Image AbsorbsInput='false' BackgroundOpacity='1.000' Color='#FF0000' continentendpoint1='4' continentendpoint2='12' Location='178,133' Name='Connection4' Rotation='0.470' RStyleDefault='ConnectionStyle.style' ScrollExtent='105,16' Size='105,16'/>
<Image AbsorbsInput='false' BackgroundOpacity='1.000' Color='#FF0000' continentendpoint1='5' continentendpoint2='12' Location='83,187' Name='Connection5' Rotation='0.430' RStyleDefault='ConnectionStyle.style' ScrollExtent='109,16' Size='109,16'/>
<Image AbsorbsInput='false' BackgroundOpacity='1.000' Color='#FF0000' continentendpoint1='3' continentendpoint2='12' Location='134,206' Name='Connection6' Rotation='0.290' RStyleDefault='ConnectionStyle.style' ScrollExtent='97,16' Size='97,16'/>
<Image AbsorbsInput='false' BackgroundOpacity='1.000' Color='#0000FF' continentendpoint1='7' continentendpoint2='11' Location='217,347' Name='Connection7' Rotation='0.450' RStyleDefault='ConnectionStyle.style' ScrollExtent='113,16' Size='113,16'/>
<Image AbsorbsInput='false' BackgroundOpacity='1.000' Color='#0000FF' continentendpoint1='3' continentendpoint2='11' Location='92,407' Name='Connection8' Rotation='0.450' RStyleDefault='ConnectionStyle.style' ScrollExtent='136,16' Size='136,16'/>
<Image AbsorbsInput='false' BackgroundOpacity='1.000' Color='#0000FF' continentendpoint1='10' continentendpoint2='11' Location='216,417' Name='Connection9' Rotation='0.060' RStyleDefault='ConnectionStyle.style' ScrollExtent='168,16' Size='168,16'/>
<Image AbsorbsInput='false' BackgroundOpacity='1.000' continentendpoint1='4' continentendpoint2='6' Location='156,66' Name='Connection10' Rotation='0.010' RStyleDefault='ConnectionStyle.style' ScrollExtent='121,16' Size='121,16'/>
<Image AbsorbsInput='false' BackgroundOpacity='1.000' continentendpoint1='4' continentendpoint2='9' Location='242,199' Name='Connection11' Rotation='0.200' RStyleDefault='ConnectionStyle.style' ScrollExtent='177,16' Size='177,16'/>
<Image AbsorbsInput='false' BackgroundOpacity='1.000' continentendpoint1='7' continentendpoint2='8' Location='404,443' Name='Connection12' RStyleDefault='ConnectionStyle.style' ScrollExtent='47,16' Size='47,16'/>
<Image AbsorbsInput='false' BackgroundOpacity='1.000' continentendpoint1='7' continentendpoint2='9' Location='325,357' Name='Connection13' Rotation='0.200' RStyleDefault='ConnectionStyle.style' ScrollExtent='75,16' Size='75,16'/>
<Image AbsorbsInput='false' BackgroundOpacity='1.000' continentendpoint1='3' continentendpoint2='9' Location='204,262' Name='Connection14' Rotation='0.040' RStyleDefault='ConnectionStyle.style' ScrollExtent='124,16' Size='124,16'/>
<Image AbsorbsInput='false' BackgroundOpacity='1.000' continentendpoint1='1' continentendpoint2='3' Location='45,321' Name='Connection15' Rotation='0.940' RStyleDefault='ConnectionStyle.style' ScrollExtent='134,16' Size='134,16'/>
<Image AbsorbsInput='false' BackgroundOpacity='1.000' continentendpoint1='2' continentendpoint2='6' Location='157,30' Name='Connection16' Rotation='0.010' RStyleDefault='ConnectionStyle.style' ScrollExtent='236,16' Size='236,16'/>
<Image AbsorbsInput='false' BackgroundOpacity='1.000' continentendpoint1='1' continentendpoint2='2' Location='-118,146' Name='Connection17' Rotation='0.250' RStyleDefault='ConnectionStyle.style' ScrollExtent='298,16' Size='298,16'/>
<Image AbsorbsInput='false' BackgroundOpacity='1.000' continentendpoint1='2' continentendpoint2='8' Location='346,147' Name='Connection18' Rotation='0.220' RStyleDefault='ConnectionStyle.style' ScrollExtent='164,16' Size='164,16'/>
<Image AbsorbsInput='false' BackgroundOpacity='1.000' continentendpoint1='5' continentendpoint2='8' Location='55,4' Name='Connection19' RStyleDefault='ConnectionStyle.style' ScrollExtent='421,16' Size='421,16'/>
<Image AbsorbsInput='false' BackgroundOpacity='1.000' continentendpoint1='8' continentendpoint2='10' Location='95,468' Name='Connection20' RStyleDefault='ConnectionStyle.style' ScrollExtent='385,16' Size='385,16'/>
<Image AbsorbsInput='false' BackgroundOpacity='1.000' continentendpoint1='1' continentendpoint2='10' Location='-2,385' Name='Connection21' Rotation='0.170' RStyleDefault='ConnectionStyle.style' ScrollExtent='108,16' Size='108,16'/>
<Image AbsorbsInput='false' BackgroundOpacity='1.000' continentendpoint1='6' continentendpoint2='10' Location='-220,246' Name='Connection22' Rotation='0.250' RStyleDefault='ConnectionStyle.style' ScrollExtent='462,16' Size='462,16'/>
<Image AbsorbsInput='false' BackgroundOpacity='1.000' continentendpoint1='5' continentendpoint2='6' Location='55,112' Name='Connection23' Rotation='0.310' RStyleDefault='ConnectionStyle.style' ScrollExtent='123,16' Size='123,16'/>
<Image AbsorbsInput='false' BackgroundOpacity='1.000' continentendpoint1='1' continentendpoint2='5' Location='12,246' Name='Connection24' Rotation='0.260' RStyleDefault='ConnectionStyle.style' ScrollExtent='97,16' Size='97,16'/>
<Image AbsorbsInput='false' BackgroundOpacity='1.000' continentendpoint1='7' continentendpoint2='8' Location='343,350' Name='Connection25' Rotation='0.250' RStyleDefault='ConnectionStyle.style' ScrollExtent='201,16' Size='201,16'/>
<Image AbsorbsInput='false' BackgroundOpacity='1.000' continentendpoint1='1' continentendpoint2='2' Location='389,21' Name='Connection26' Rotation='0.250' RStyleDefault='ConnectionStyle.style' ScrollExtent='48,16' Size='48,16'/>
<Image AbsorbsInput='false' BackgroundOpacity='1.000' continentendpoint1='1' continentendpoint2='2' Location='23,5' Name='Connection27' RStyleDefault='ConnectionStyle.style' ScrollExtent='397,16' Size='397,16'/>
<Image AbsorbsInput='false' BackgroundOpacity='1.000' continentendpoint1='5' continentendpoint2='8' Location='354,113' Name='Connection28' Rotation='0.250' RStyleDefault='ConnectionStyle.style' ScrollExtent='229,16' Size='229,16'/>
<Image AbsorbsInput='false' BackgroundOpacity='1.000' continentendpoint1='5' continentendpoint2='8' Location='-25,82' Name='Connection29' Rotation='0.250' RStyleDefault='ConnectionStyle.style' ScrollExtent='175,16' Size='175,16'/>
<Image AbsorbsInput='false' BackgroundOpacity='1.000' continentendpoint1='8' continentendpoint2='10' Location='357,363' Name='Connection30' Rotation='0.250' RStyleDefault='ConnectionStyle.style' ScrollExtent='228,16' Size='228,16'/>
<Image AbsorbsInput='false' BackgroundOpacity='1.000' continentendpoint1='6' continentendpoint2='10' Location='3,24' Name='Connection31' RStyleDefault='ConnectionStyle.style' ScrollExtent='141,16' Size='141,16'/>
<Image AbsorbsInput='false' BackgroundOpacity='1.000' continentendpoint1='6' continentendpoint2='10' Location='2,469' Name='Connection32' RStyleDefault='ConnectionStyle.style' ScrollExtent='80,16' Size='80,16'/>
<Checkbox BackgroundOpacity='1.000' BackgroundTint='#00FF00' continentid='1' Location='4,286' Name='Solsar' PackLocation='proportional,proportional' PackLocationProp='0044/0503,0326/0505' ScrollExtent='80,80' Size='80,80' Style='/Buttons.GlobalMapMap01.style' zonename='z1'></Checkbox>
<Checkbox BackgroundOpacity='1.000' BackgroundTint='#00FF00' continentid='2' Location='360,25' Name='Hossin' PackLocation='proportional,proportional' PackLocationProp='0400/0503,0065/0505' ScrollExtent='80,80' Size='80,80' Style='/Buttons.GlobalMapMap02.style' zonename='z2'></Checkbox>
<Checkbox BackgroundOpacity='1.000' BackgroundTint='#00FF00' continentid='3' Location='143,244' Name='Cyssor' PackLocation='proportional,proportional' PackLocationProp='0191/0503,0284/0505' ScrollExtent='97,80' Size='97,80' Style='/Buttons.GlobalMapMap03.style' zonename='z3'></Checkbox>
<Checkbox BackgroundOpacity='1.000' BackgroundTint='#00FF00' continentid='4' Location='249,65' Name='Ishundar' PackLocation='proportional,proportional' PackLocationProp='0289/0503,0105/0505' ScrollExtent='80,80' Size='80,80' Style='/Buttons.GlobalMapMap04.style' zonename='z4'></Checkbox>
<Checkbox BackgroundOpacity='1.000' BackgroundTint='#00FF00' continentid='5' Location='40,153' Name='Forseral' PackLocation='proportional,proportional' PackLocationProp='0080/0503,0193/0505' ScrollExtent='80,80' Size='80,80' Style='/Buttons.GlobalMapMap05.style' zonename='z5'></Checkbox>
<Checkbox BackgroundOpacity='1.000' BackgroundTint='#00FF00' continentid='6' Location='110,11' Name='Ceryshen' PackLocation='proportional,proportional' PackLocationProp='0150/0503,0051/0505' ScrollExtent='80,80' Size='80,80' Style='/Buttons.GlobalMapMap06.style' zonename='z6'></Checkbox>
<Checkbox BackgroundOpacity='1.000' BackgroundTint='#00FF00' continentid='7' Location='352,384' Name='Esamir' PackLocation='proportional,proportional' PackLocationProp='0392/0503,0424/0505' ScrollExtent='80,80' Size='80,80' Style='/Buttons.GlobalMapMap07.style' zonename='z7'></Checkbox>
<Checkbox BackgroundOpacity='1.000' BackgroundTint='#00FF00' continentid='8' Location='416,208' Name='Oshur' PackLocation='proportional,proportional' PackLocationProp='0456/0503,0248/0505' ScrollExtent='80,80' Size='80,80' Style='/Buttons.GlobalMapMap08.style' zonename='z8'></Checkbox>
<Checkbox BackgroundOpacity='1.000' BackgroundTint='#00FF00' continentid='9' Location='297,273' Name='Searhus' PackLocation='proportional,proportional' PackLocationProp='0337/0503,0313/0505' ScrollExtent='80,80' Size='80,80' Style='/Buttons.GlobalMapMap09.style' zonename='z9'></Checkbox>
<Checkbox BackgroundOpacity='1.000' BackgroundTint='#00FF00' continentid='10' Location='48,418' Name='Amerish' PackLocation='proportional,proportional' PackLocationProp='0088/0503,0458/0505' ScrollExtent='80,80' Size='80,80' Style='/Buttons.GlobalMapMap10.style' zonename='z10'></Checkbox>
<Checkbox BackgroundOpacity='1.000' BackgroundTint='#00FF00' continentid='11' Location='186,348' Name='SanctuaryNC' PackLocation='proportional,proportional' PackLocationProp='0226/0503,0388/0505' ScrollExtent='80,80' Size='80,80' Style='/Buttons.GlobalMapMap11.style' zonename='home1'></Checkbox>
<Checkbox BackgroundOpacity='1.000' BackgroundTint='#00FF00' continentid='12' Location='147,123' Name='SanctuaryTR' PackLocation='proportional,proportional' PackLocationProp='0187/0503,0163/0505' ScrollExtent='80,80' Size='80,80' Style='/Buttons.GlobalMapMap12.style' zonename='home2'></Checkbox>
<Checkbox BackgroundOpacity='1.000' BackgroundTint='#00FF00' continentid='13' Location='338,148' Name='SanctuaryVS' PackLocation='proportional,proportional' PackLocationProp='0378/0503,0188/0505' ScrollExtent='80,80' Size='80,80' Style='/Buttons.GlobalMapMap13.style' zonename='home3'></Checkbox>
<Namespace Name='ConnectionStyle'>
<ImageStyle Name='west'>
<ImageFrame Source='ui_map_warpgate_connection_00' SourceRect='0,0,16,16'/>
</ImageStyle>
<ImageStyle Name='east'>
<ImageFrame Source='ui_map_warpgate_connection_00' SourceRect='16,0,32,16'/>
</ImageStyle>
<ImageStyle Name='center'>
<ImageFrame Source='ui_map_warpgate_connection_00' SourceRect='0,16,16,32'/>
</ImageStyle>
<RectangleStyle Center='center' CenterShrinkH='true' CenterStretchH='true' East='east' Name='style' West='west'/>
</Namespace>
<Namespace Name='HalfConnectionStyle'>
<ImageStyle Name='west'>
<ImageFrame Source='ui_map_warpgate_connection_00' SourceRect='0,0,16,16'/>
</ImageStyle>
<ImageStyle Name='center'>
<ImageFrame Source='ui_map_warpgate_connection_00' SourceRect='0,16,16,32'/>
</ImageStyle>
<RectangleStyle Center='center' CenterShrinkH='true' CenterStretchH='true' East=' ' Name='style' West='west'/>
</Namespace>
</Page>
<Page BackgroundColor='#0000FF' Location='453,713' Name='ZoomToolbar' ScrollExtent='201,24' Size='201,24'>
<Checkbox BackgroundColor='#FFFFFF' BackgroundOpacity='1.000' LocalTooltip='[@MapZoom0Tooltip]' Location='2,3' Name='Zoom0' ScrollExtent='39,20' Size='39,20' Style='/Buttons.IconButton.checkstyle' Tooltip='@MapZoom0Tooltip'>8</Checkbox>
<Checkbox BackgroundColor='#FFFFFF' BackgroundOpacity='1.000' LocalTooltip='[@MapZoom1Tooltip]' Location='42,3' Name='Zoom1' ScrollExtent='39,20' Size='39,20' Style='/Buttons.IconButton.checkstyle' Tooltip='@MapZoom1Tooltip'>9</Checkbox>
<Checkbox BackgroundColor='#FFFFFF' BackgroundOpacity='1.000' LocalTooltip='[@MapZoom2Tooltip]' Location='82,3' Name='Zoom2' ScrollExtent='39,20' Size='39,20' Style='/Buttons.IconButton.checkstyle' Tooltip='@MapZoom2Tooltip'>:</Checkbox>
<Checkbox BackgroundColor='#FFFFFF' BackgroundOpacity='1.000' LocalTooltip='[@MapZoom3Tooltip]' Location='122,3' Name='Zoom3' ScrollExtent='39,20' Size='39,20' Style='/Buttons.IconButton.checkstyle' Tooltip='@MapZoom3Tooltip'>;</Checkbox>
<Checkbox Activated='true' BackgroundColor='#FFFFFF' BackgroundOpacity='1.000' Checked='true' LocalTooltip='[@MapZoom4Tooltip]' Location='162,3' Name='Zoom4' ScrollExtent='39,20' Size='39,20' Style='/Buttons.IconButton.checkstyle' Tooltip='@MapZoom4Tooltip'>\<</Checkbox>
</Page>
<Page Location='878,716' Name='DroppodToolbar' PackLocation='right,bottom' PackLocationProp='-144/0001,-051/0001' PackSize='fixed,fixed' PackSizeProp='0002/0003,0002/0003' ScrollExtent='97,22' Size='97,22'>
<Checkbox AbsorbsInput='false' Activated='true' BackgroundOpacity='1.000' Checked='true' LocalTooltip='[@ToggleDroppodDiscTooltip]' Location='-51,-2' Name='DroppodDiscToggle' ScrollExtent='40,27' Size='40,27' Style='/Buttons.MapDroppodDiscToggle.style' Tooltip='@ToggleDroppodDiscTooltip' Visible='false'></Checkbox>
<Button LocalText='b' LocalTooltip='[@LaunchDroppodTooltip]' Location='0,-1' Name='DroppodLaunchButton' OnPress='psc_launchdroppod
psc_hidemap' ScrollExtent='39,20' Size='39,20' Style='/Buttons.IconButton.style' Tooltip='@LaunchDroppodTooltip'>b</Button>
</Page>
<Page Activated='true' Location='44,708' Name='ToggleToolbar' PackLocation='left,bottom' PackLocationProp='0044/0001,-059/0001' PackSize='fixed,fixed' PackSizeProp='0002/0003,0002/0003' ScrollExtent='214,33' Size='214,33'>
<Text AbsorbsInput='false' Enabled='false' Font='/Fonts.ButtonIcons' LocalText='N' Location='41,3' Name='TempThreat' ScrollExtent='41,30' Size='41,30' TextAlignment='Center' TextAlignmentVertical='Center'>N</Text>
<Text AbsorbsInput='false' Enabled='false' Font='/Fonts.ButtonIcons' LocalText='K' Location='83,3' Name='TempThreat' ScrollExtent='41,30' Size='41,30' TextAlignment='Center' TextAlignmentVertical='Center'>K</Text>
<Text AbsorbsInput='false' Enabled='false' Font='/Fonts.ButtonIcons' LocalText='M' Location='125,4' Name='TempThreat' ScrollExtent='41,30' Size='41,30' TextAlignment='Center' TextAlignmentVertical='Center'>M</Text>
<Text AbsorbsInput='false' Enabled='false' Font='/Fonts.ButtonIcons' LocalText='P' Location='168,3' Name='TempThreat' ScrollExtent='41,30' Size='41,30' TextAlignment='Center' TextAlignmentVertical='Center'>P</Text>
<Text AbsorbsInput='false' Enabled='false' Font='/Fonts.ButtonIcons' LocalText='T' Location='-1,3' Name='TempThreat' ScrollExtent='41,30' Size='41,30' TextAlignment='Center' TextAlignmentVertical='Center'>T</Text>
<Checkbox BackgroundOpacity='1.000' LocalTooltip='[@ToggleThreatTooltip]' Location='42,8' Name='ThreatMapToggle' ScrollExtent='39,20' Size='39,20' Style='/Buttons.IconButton.checkstyle' Tooltip='@ToggleThreatTooltip'>N</Checkbox>
<Checkbox BackgroundOpacity='1.000' LocalTooltip='[@ToggleFriendlyTooltip]' Location='84,8' Name='FriendlySoldierToggle' ScrollExtent='39,20' Size='39,20' Style='/Buttons.IconButton.checkstyle' Tooltip='@ToggleFriendlyTooltip'>K</Checkbox>
<Checkbox BackgroundOpacity='1.000' LocalTooltip='[@ToggleDiskTooltip]' Location='126,8' Name='PriorityDiskToggle' ScrollExtent='39,20' Size='39,20' Style='/Buttons.IconButton.checkstyle' Tooltip='@ToggleDiskTooltip'>M</Checkbox>
<Checkbox BackgroundOpacity='1.000' LocalTooltip='[@PlaceDiskModeTooltip]' Location='222,8' Name='PlacePriorityToggle' ScrollExtent='39,20' Size='39,20' Style='/Buttons.IconButton.checkstyle' Tooltip='@PlaceDiskModeTooltip' Visible='false'>O</Checkbox>
<Checkbox Activated='true' BackgroundOpacity='1.000' Checked='true' LocalTooltip='[@ToggleSOITooltip]' Location='168,8' Name='BuildingSOIToggle' ScrollExtent='39,20' Size='39,20' Style='/Buttons.IconButton.checkstyle' Tooltip='@ToggleSOITooltip'>P</Checkbox>
<Checkbox BackgroundOpacity='1.000' LocalTooltip='[@TextToggleTooltip]' Location='0,8' Name='TextToggle' ScrollExtent='39,27' Size='39,27' Style='/Buttons.IconButton.checkstyle' Tooltip='@TextToggleTooltip'>T</Checkbox>
</Page>
<Page Location='320,710' Name='SoldierToolbar' PackLocation='left,bottom' PackLocationProp='0320/0001,-057/0001' PackSize='fixed,fixed' PackSizeProp='0002/0003,0002/0003' ScrollExtent='84,32' Size='84,32'>
<Text AbsorbsInput='false' Enabled='false' Font='/Fonts.ButtonIcons' LocalText='R' Location='0,2' Name='TempThreat' ScrollExtent='41,30' Size='41,30' TextAlignment='Center' TextAlignmentVertical='Center'>R</Text>
<Text AbsorbsInput='false' Enabled='false' Font='/Fonts.ButtonIcons' LocalText='S' Location='40,1' Name='TempThreat' ScrollExtent='41,30' Size='41,30' TextAlignment='Center' TextAlignmentVertical='Center'>S</Text>
<Checkbox Activated='true' BackgroundColor='#FFFFFF' BackgroundOpacity='1.000' Checked='true' LocalTooltip='[@PanModeTooltip]' Location='0,6' Name='PanModeToggle' ScrollExtent='39,20' Size='39,20' Style='/Buttons.IconButton.checkstyle' Tooltip='@PanModeTooltip'>R</Checkbox>
<Checkbox Activated='true' BackgroundOpacity='1.000' Checked='true' LocalTooltip='[@ZoomModeTooltip]' Location='41,6' Name='ZoomModeToggle' ScrollExtent='39,20' Size='39,20' Style='/Buttons.IconButton.checkstyle' Tooltip='@ZoomModeTooltip'>S</Checkbox>
</Page>
<Checkbox Activated='true' BackgroundOpacity='1.000' Checked='true' LocalTooltip='[@MapGlobalTooltip]' Location='27,31' Name='GlobalMapTab' PackLocation='left,top' PackLocationProp='0027/0001,0031/0001' PackSize='fixed,fixed' PackSizeProp='0002/0003,0002/0003' ScrollExtent='140,31' Size='140,31' Style='/Buttons.MapTab.style' Tooltip='@MapGlobalTooltip'>C</Checkbox>
<Checkbox BackgroundOpacity='1.000' Enabled='false' LocalTooltip='[@MapContinetalTooltip]' Location='175,31' Name='ContinentMapTab' OnDisableEffector='DisableEffector' PackLocation='left,top' PackLocationProp='0175/0001,0031/0001' PackSize='fixed,fixed' PackSizeProp='0002/0003,0002/0003' ScrollExtent='140,31' Size='140,31' Style='/Buttons.MapTab.style' Tooltip='@MapContinetalTooltip'>E</Checkbox>
<Checkbox BackgroundOpacity='1.000' LocalTooltip='[@MapSoldierTooltip]' Location='321,31' Name='SoldierMapTab' PackLocation='left,top' PackLocationProp='0321/0001,0031/0001' PackSize='fixed,fixed' PackSizeProp='0002/0003,0002/0003' ScrollExtent='140,31' Size='140,31' Style='/Buttons.MapTab.style' Tooltip='@MapSoldierTooltip' Visible='false'>E</Checkbox>
<Page Location='674,67' Name='SquadWaypointPage' PackLocation='right,top' PackLocationProp='-348/0001,0067/0001' PackSize='fixed,fixed' PackSizeProp='0002/0003,0002/0003' ScrollExtent='316,322' Size='316,322'>
<Rectangle Color='#00F2C9' colorize='true' Name='SquadWaypointOutline' Opacity='0.750' PackSize='1,1' PackSizeProp='0002/0003,0002/0003' ScrollExtent='316,322' Size='316,322'/>
<Scrollbar colorize='true' Control='ListBox' getsheartbeat='true' Location='305,2' Name='SquadWaypointScroll' PackLocation='Right, Top' PackLocationProp='-011/0001,xxxx/xxxx' ScrollExtent='9,317' Size='9,317' Style='/ScrollBars.vertical.style'/>
<Listbox colorize='true' DataSource='/DataSources.SquadWaypointPriorityList' Location='3,1' Name='ListBox' RowTemplate='ListboxTemplate' ScrollExtent='300,440' Size='300,320' Style='/Listboxes.Clear.style'/>
<Template Name='ListboxTemplate' Size='300,20'>\<text color = \'$color$\' font = \'/Fonts.HudFont1\' location = \'0,2\' maxlines = \'1\' size = \'275,18\' textalignment = \'right\' truncateelipsis = \'false\' visible = \'$isSquadWingHeading$\'\>
$Internationalize$
\</text\>
\<Image backgroundopacity = \'1.000\' location = \'0,10\' name = \'UnderlineTemplate\' rstyledefault = \'/Listboxes.ListboxContentHeader.style\' scrollextent = \'300,8\' size = \'300,8\' visible = \'$isSquadWingHeading$\'/\>
\<text color = \'$color$\' font = \'/Fonts.HudFont1\' location = \'0,2\' maxlines = \'1\' size = \'275,18\' textalignment = \'right\' truncateelipsis = \'false\' visible = \'$isSquadWaypointHeading$\'\>
$Internationalize$
\</text\>
\<Image backgroundopacity = \'1.000\' location = \'0,10\' name = \'UnderlineTemplate\' rstyledefault = \'/Listboxes.ListboxContentHeader.style\' scrollextent = \'300,8\' size = \'300,8\' visible = \'$isSquadWaypointHeading$\'/\>
\<text color = \'$color$\' font = \'/Fonts.HudFont1\' location = \'0,2\' maxlines = \'1\' size = \'275,18\' textalignment = \'right\' truncateelipsis = \'false\' visible = \'$isSquadPriorityHeading$\'\>
$Internationalize$
\</text\>
\<Image backgroundopacity = \'1.000\' location = \'0,10\' name = \'UnderlineTemplate\' rstyledefault = \'/Listboxes.ListboxContentHeader.style\' scrollextent = \'300,8\' size = \'300,8\' visible = \'$isSquadPriorityHeading$\'/\>
\<text color = \'$color$\' font = \'/Fonts.HudFont2\' location = \'5,2\' maxlines = \'1\' size = \'132,18\' visible = \'$isSquadWingSubHeading$\'\>
$Internationalize$
\</text\>
\<text color = \'$color$\' font = \'/Fonts.HudFont2\' location = \'5,2\' maxlines = \'1\' size = \'132,18\' visible = \'$isSquadWaypointSubHeading$\'\>
$Internationalize$
\</text\>
\<text color = \'$color$\' font = \'/Fonts.HudFont1\' location = \'5,2\' maxlines = \'1\' size = \'30,18\' textalignment = \'right\' truncateelipsis = \'false\' visible = \'$isSquadWingMember$\'\>
$MemberID$
\</text\>
\<text color = \'$color$\' font = \'/Fonts.HudFont1\' location = \'45,2\' maxlines = \'1\' size = \'92,18\' visible = \'$isSquadWingMember$\'\>
$Internationalize$
\</text\>
\<Progressbar barbackgroundcolor = \'#00ffff\' localtooltip = \'[@HeatlhTooltip]\' location = \'175,1\' progress = \'$health$\' size = \'110,15\' style = \'/ProgressBars.Squad.style\' tooltip = \'@HeatlhTooltip\' visible = \'$isSquadWingMember\'/\>
\<text color = \'$color$\' font = \'/Fonts.HudFont1\' location = \'25,2\' maxlines = \'1\' size = \'275,18\' visible = \'$isSquadWaypoint$\'\>
$Internationalize$
\</text\>
\<text color = \'$color$\' font = \'/Fonts.HudFont2\' location = \'25,2\' maxlines = \'1\' size = \'275,18\' visible = \'$isSquadPriority$\'\>
$Internationalize$
\</text\></Template>
</Page>
<Page Location='674,426' Name='StatusPage' PackLocation='right,top' PackLocationProp='-348/0001,0426/0001' PackSize='fixed,fixed' PackSizeProp='0002/0003,0002/0003' ScrollExtent='317,106' Size='317,106'>
<Text colorize='true' Font='/Fonts.ChatFont' GetsInput='false' Location='4,20' minheight='32' Name='StatusText' PackLocation='left,top' PackLocationProp='0004/0001,0020/0001' PackSize='Absolute, Absolute' PackSizeProp='0020/0001,xxxx/xxxx' ScrollExtent='297,83' Size='297,83' TextAlignment='Center'></Text>
<Text colorize='true' Font='/Fonts.ChatFont' GetsInput='false' LocalText='[@MapStatusTitle]' Location='2,1' minheight='32' Name='StatusTitle' PackLocation='left,top' PackLocationProp='0002/0001,0001/0001' PackSize='Absolute, Absolute' PackSizeProp='0004/0001,xxxx/xxxx' ScrollExtent='313,22' Size='313,22' TextAlignment='Center'>@MapStatusTitle</Text>
<Scrollbar colorize='true' Control='StatusText' getsheartbeat='true' Location='305,18' Name='StatusScroll' PackLocation='Right,Top' PackLocationProp='-012/0001,0018/0001' PackSize='Fixed,Absolute' PackSizeProp='0002/0003,0025/0001' ScrollExtent='8,81' Size='8,81' Style='/ScrollBars.vertical.style'/>
<Rectangle Color='#00F2C9' Name='StatusOutline' Opacity='0.750' PackSize='1,1' PackSizeProp='0002/0003,0002/0003' ScrollExtent='317,106' Size='317,106'/>
</Page>
<Page BackgroundColor='#00FFFF' Location='30,67' Name='GlobalMap' PackLocation='left,top' PackLocationProp='0030/0001,0067/0001' PackSize='absolute,absolute' PackSizeProp='0384/0001,0128/0001' ScrollExtent='638,639' Size='638,639'>
<Page AbsorbsInput='false' Location='-9,-7' Name='Text' PackSize='proportional,proportional' PackSizeProp='0641/0638,0641/0639' ScrollExtent='641,641' Size='641,641'>
<Text continentid='1' Font='/Fonts.HudFont3' GetsInput='false' LocalText='[@z1]' Location='-46,394' Name='z1' PackLocation='proportional,proportional' PackLocationProp='0079/0641,0405/0641' PackSize='fixed,fixed' PackSizeProp='0002/0003,0002/0003' ScrollExtent='250,22' ShadowStyle='/Shadows.Default' Size='250,22' TextAlignment='Center' TextAlignmentVertical='Center'>@z1</Text>
<Text continentid='2' Font='/Fonts.HudFont3' GetsInput='false' LocalText='[@z2]' Location='389,96' Name='z2' PackLocation='proportional,proportional' PackLocationProp='0514/0641,0107/0641' PackSize='fixed,fixed' PackSizeProp='0002/0003,0002/0003' ScrollExtent='250,22' ShadowStyle='/Shadows.Default' Size='250,22' TextAlignment='Center' TextAlignmentVertical='Center'>@z2</Text>
<Text continentid='3' Font='/Fonts.HudFont3' GetsInput='false' LocalText='[@z3]' Location='310,415' Name='z3' PackLocation='proportional,proportional' PackLocationProp='0435/0641,0426/0641' PackSize='fixed,fixed' PackSizeProp='0002/0003,0002/0003' ScrollExtent='250,22' ShadowStyle='/Shadows.Default' Size='250,22' TextAlignment='Center' TextAlignmentVertical='Center'>@z3</Text>
<Text continentid='4' Font='/Fonts.HudFont3' GetsInput='false' LocalText='[@z4]' Location='315,226' Name='z4' PackLocation='proportional,proportional' PackLocationProp='0440/0641,0237/0641' PackSize='fixed,fixed' PackSizeProp='0002/0003,0002/0003' ScrollExtent='250,22' ShadowStyle='/Shadows.Default' Size='250,22' TextAlignment='Center' TextAlignmentVertical='Center'>@z4</Text>
<Text continentid='5' Font='/Fonts.HudFont3' GetsInput='false' LocalText='[@z5]' Location='-27,142' Name='z5' PackLocation='proportional,proportional' PackLocationProp='0098/0641,0153/0641' PackSize='fixed,fixed' PackSizeProp='0002/0003,0002/0003' ScrollExtent='250,22' ShadowStyle='/Shadows.Default' Size='250,22' TextAlignment='Center' TextAlignmentVertical='Center'>@z5</Text>
<Text continentid='6' Font='/Fonts.HudFont3' GetsInput='false' LocalText='[@z6]' Location='93,62' Name='z6' PackLocation='proportional,proportional' PackLocationProp='0218/0641,0073/0641' PackSize='fixed,fixed' PackSizeProp='0002/0003,0002/0003' ScrollExtent='250,22' ShadowStyle='/Shadows.Default' Size='250,22' TextAlignment='Center' TextAlignmentVertical='Center'>@z6</Text>
<Text continentid='7' Font='/Fonts.HudFont3' GetsInput='false' LocalText='[@z7]' Location='265,545' Name='z7' PackLocation='proportional,proportional' PackLocationProp='0390/0641,0556/0641' PackSize='fixed,fixed' PackSizeProp='0002/0003,0002/0003' ScrollExtent='250,22' ShadowStyle='/Shadows.Default' Size='250,22' TextAlignment='Center' TextAlignmentVertical='Center'>@z7</Text>
<Text continentid='8' Font='/Fonts.HudFont3' GetsInput='false' LocalText='[@z8]' Location='438,277' Name='z8' PackLocation='proportional,proportional' PackLocationProp='0563/0641,0288/0641' PackSize='fixed,fixed' PackSizeProp='0002/0003,0002/0003' ScrollExtent='250,22' ShadowStyle='/Shadows.Default' Size='250,22' TextAlignment='Center' TextAlignmentVertical='Center'>@z8</Text>
<Text continentid='9' Font='/Fonts.HudFont3' GetsInput='false' LocalText='[@z9]' Location='110,295' Name='z9' PackLocation='proportional,proportional' PackLocationProp='0235/0641,0306/0641' PackSize='fixed,fixed' PackSizeProp='0002/0003,0002/0003' ScrollExtent='250,22' ShadowStyle='/Shadows.Default' Size='250,22' TextAlignment='Center' TextAlignmentVertical='Center'>@z9</Text>
<Text continentid='10' Font='/Fonts.HudFont3' GetsInput='false' LocalText='[@z10]' Location='117,533' Name='z10' PackLocation='proportional,proportional' PackLocationProp='0242/0641,0544/0641' PackSize='fixed,fixed' PackSizeProp='0002/0003,0002/0003' ScrollExtent='250,22' ShadowStyle='/Shadows.Default' Size='250,22' TextAlignment='Center' TextAlignmentVertical='Center'>@z10</Text>
<Text continentid='11' empire='1' Font='/Fonts.HudFont3' GetsInput='false' LocalText='[@home1]' Location='209,121' Name='home1' PackLocation='proportional,proportional' PackLocationProp='0334/0641,0132/0641' PackSize='fixed,fixed' PackSizeProp='0002/0003,0002/0003' ScrollExtent='250,22' ShadowStyle='/Shadows.Default' Size='250,22' TextAlignment='Center' TextAlignmentVertical='Center'>@home1</Text>
<Text continentid='12' empire='0' Font='/Fonts.HudFont3' GetsInput='false' LocalText='[@home2]' Location='-32,547' Name='home2' PackLocation='proportional,proportional' PackLocationProp='0093/0641,0558/0641' PackSize='fixed,fixed' PackSizeProp='0002/0003,0002/0003' ScrollExtent='250,22' ShadowStyle='/Shadows.Default' Size='250,22' TextAlignment='Center' TextAlignmentVertical='Center'>@home2</Text>
<Text continentid='13' empire='2' Font='/Fonts.HudFont3' GetsInput='false' LocalText='[@home3]' Location='441,516' Name='home3' PackLocation='proportional,proportional' PackLocationProp='0566/0641,0527/0641' PackSize='fixed,fixed' PackSizeProp='0002/0003,0002/0003' ScrollExtent='250,22' ShadowStyle='/Shadows.Default' Size='250,22' TextAlignment='Center' TextAlignmentVertical='Center'>@home3</Text>
</Page>
<Image AbsorbsInput='false' BackgroundOpacity='1.000' Color='#800080' continentendpoint1='2' continentendpoint2='13' Location='368,302' Name='Connection1' PackLocation='proportional,proportional' PackLocationProp='0560/0638,0310/0639' PackSize='proportional,proportional' PackSizeProp='0384/0638,0016/0639' Rotation='0.232' RStyleDefault='ConnectionStyle.style' ScrollExtent='384,16' Size='384,16'/>
<Image AbsorbsInput='false' BackgroundOpacity='1.000' Color='#800080' continentendpoint1='4' continentendpoint2='13' Location='315,330' Name='Connection2' PackLocation='proportional,proportional' PackLocationProp='0498/0638,0338/0639' PackSize='proportional,proportional' PackSizeProp='0367/0638,0016/0639' Rotation='0.205' RStyleDefault='ConnectionStyle.style' ScrollExtent='367,16' Size='367,16'/>
<Image AbsorbsInput='false' BackgroundOpacity='1.000' Color='#800080' continentendpoint1='7' continentendpoint2='13' Location='412,569' Name='Connection3' PackLocation='proportional,proportional' PackLocationProp='0487/0638,0577/0639' PackSize='proportional,proportional' PackSizeProp='0151/0638,0016/0639' Rotation='0.400' RStyleDefault='ConnectionStyle.style' ScrollExtent='151,16' Size='151,16'/>
<Image AbsorbsInput='false' BackgroundOpacity='1.000' Color='#FF0000' continentendpoint1='4' continentendpoint2='12' Location='14,391' Name='Connection4' PackLocation='proportional,proportional' PackLocationProp='0245/0638,0399/0639' PackSize='proportional,proportional' PackSizeProp='0463/0638,0016/0639' Rotation='0.400' RStyleDefault='ConnectionStyle.style' ScrollExtent='463,16' Size='463,16'/>
<Image AbsorbsInput='false' BackgroundOpacity='1.000' Color='#FF0000' continentendpoint1='5' continentendpoint2='12' Location='-85,363' Name='Connection5' PackLocation='proportional,proportional' PackLocationProp='0089/0638,0371/0639' PackSize='proportional,proportional' PackSizeProp='0348/0638,0016/0639' Rotation='0.233' RStyleDefault='ConnectionStyle.style' ScrollExtent='348,16' Size='348,16'/>
<Image AbsorbsInput='false' BackgroundOpacity='1.000' Color='#FF0000' continentendpoint1='3' continentendpoint2='12' Location='51,504' Name='Connection6' PackLocation='proportional,proportional' PackLocationProp='0269/0638,0512/0639' PackSize='proportional,proportional' PackSizeProp='0437/0638,0016/0639' Rotation='0.455' RStyleDefault='ConnectionStyle.style' ScrollExtent='437,16' Size='437,16'/>
<Image AbsorbsInput='false' BackgroundOpacity='1.000' Color='#0000FF' continentendpoint1='7' continentendpoint2='11' Location='140,319' Name='Connection7' PackLocation='proportional,proportional' PackLocationProp='0335/0638,0327/0639' PackSize='proportional,proportional' PackSizeProp='0390/0638,0016/0639' Rotation='0.255' RStyleDefault='ConnectionStyle.style' ScrollExtent='390,16' Size='390,16'/>
<Image AbsorbsInput='false' BackgroundOpacity='1.000' Color='#0000FF' continentendpoint1='3' continentendpoint2='11' Location='210,231' Name='Connection8' PackLocation='proportional,proportional' PackLocationProp='0355/0638,0239/0639' PackSize='proportional,proportional' PackSizeProp='0291/0638,0016/0639' Rotation='0.190' RStyleDefault='ConnectionStyle.style' ScrollExtent='291,16' Size='291,16'/>
<Image AbsorbsInput='false' BackgroundOpacity='1.000' Color='#0000FF' continentendpoint1='10' continentendpoint2='11' Location='61,307' Name='Connection9' PackLocation='proportional,proportional' PackLocationProp='0278/0638,0315/0639' PackSize='proportional,proportional' PackSizeProp='0434/0638,0016/0639' Rotation='0.295' RStyleDefault='ConnectionStyle.style' ScrollExtent='434,16' Size='434,16'/>
<Image AbsorbsInput='false' BackgroundOpacity='1.000' continentendpoint1='4' continentendpoint2='6' Location='205,141' Name='Connection10' PackLocation='proportional,proportional' PackLocationProp='0336/0638,0149/0639' PackSize='proportional,proportional' PackSizeProp='0263/0638,0016/0639' Rotation='0.080' RStyleDefault='ConnectionStyle.style' ScrollExtent='263,16' Size='263,16'/>
<Image AbsorbsInput='false' BackgroundOpacity='1.000' continentendpoint1='4' continentendpoint2='9' Location='175,233' Name='Connection11' PackLocation='proportional,proportional' PackLocationProp='0286/0638,0241/0639' PackSize='proportional,proportional' PackSizeProp='0223/0638,0016/0639' Rotation='0.490' RStyleDefault='ConnectionStyle.style' ScrollExtent='223,16' Size='223,16'/>
<Image AbsorbsInput='false' BackgroundOpacity='1.000' continentendpoint1='7' continentendpoint2='8' Location='323,428' Name='Connection12' PackLocation='proportional,proportional' PackLocationProp='0488/0638,0436/0639' PackSize='proportional,proportional' PackSizeProp='0330/0638,0016/0639' Rotation='0.340' RStyleDefault='ConnectionStyle.style' ScrollExtent='330,16' Size='330,16'/>
<Image AbsorbsInput='false' BackgroundOpacity='1.000' continentendpoint1='7' continentendpoint2='9' Location='118,465' Name='Connection13' PackLocation='proportional,proportional' PackLocationProp='0271/0638,0473/0639' PackSize='proportional,proportional' PackSizeProp='0306/0638,0016/0639' Rotation='0.147' RStyleDefault='ConnectionStyle.style' ScrollExtent='306,16' Size='306,16'/>
<Image AbsorbsInput='false' BackgroundOpacity='1.000' continentendpoint1='3' continentendpoint2='9' Location='234,382' Name='Connection14' PackLocation='proportional,proportional' PackLocationProp='0329/0638,0390/0639' PackSize='proportional,proportional' PackSizeProp='0191/0638,0016/0639' Rotation='0.150' RStyleDefault='ConnectionStyle.style' ScrollExtent='191,16' Size='191,16'/>
<Image AbsorbsInput='false' BackgroundOpacity='1.000' continentendpoint1='1' continentendpoint2='3' Location='92,397' Name='Connection15' PackLocation='proportional,proportional' PackLocationProp='0292/0638,0405/0639' PackSize='proportional,proportional' PackSizeProp='0401/0638,0016/0639' Rotation='0.993' RStyleDefault='ConnectionStyle.style' ScrollExtent='401,16' Size='401,16'/>
<Image AbsorbsInput='false' BackgroundOpacity='1.000' continentendpoint1='2' continentendpoint2='6' Location='216,48' Name='Connection16' PackLocation='proportional,proportional' PackLocationProp='0344/0638,0056/0639' PackSize='proportional,proportional' PackSizeProp='0257/0638,0016/0639' Rotation='0.015' RStyleDefault='ConnectionStyle.style' ScrollExtent='257,16' Size='257,16'/>
<Image AbsorbsInput='false' BackgroundOpacity='1.000' continentendpoint1='1' continentendpoint2='2' Location='24,199' Name='Connection17' PackLocation='proportional,proportional' PackLocationProp='0289/0638,0207/0639' PackSize='proportional,proportional' PackSizeProp='0531/0638,0016/0639' Rotation='0.415' RStyleDefault='ConnectionStyle.style' ScrollExtent='531,16' Size='531,16'/>
<Image AbsorbsInput='false' BackgroundOpacity='1.000' continentendpoint1='2' continentendpoint2='8' Location='449,180' Name='Connection18' PackLocation='proportional,proportional' PackLocationProp='0536/0638,0188/0639' PackSize='proportional,proportional' PackSizeProp='0175/0638,0016/0639' Rotation='0.150' RStyleDefault='ConnectionStyle.style' ScrollExtent='175,16' Size='175,16'/>
<Image AbsorbsInput='false' BackgroundOpacity='1.000' continentendpoint1='5' continentendpoint2='8' Location='136,191' Name='Connection19' PackLocation='proportional,proportional' PackLocationProp='0348/0638,0199/0639' PackSize='proportional,proportional' PackSizeProp='0424/0638,0016/0639' Rotation='0.035' RStyleDefault='ConnectionStyle.style' ScrollExtent='424,16' Size='424,16'/>
<Image AbsorbsInput='false' BackgroundOpacity='1.000' continentendpoint1='8' continentendpoint2='10' Location='216,407' Name='Connection20' PackLocation='proportional,proportional' PackLocationProp='0391/0638,0415/0639' PackSize='proportional,proportional' PackSizeProp='0350/0638,0016/0639' Rotation='0.405' RStyleDefault='ConnectionStyle.style' ScrollExtent='350,16' Size='350,16'/>
<Image AbsorbsInput='false' BackgroundOpacity='1.000' continentendpoint1='1' continentendpoint2='10' Location='28,502' Name='Connection21' PackLocation='proportional,proportional' PackLocationProp='0121/0638,0510/0639' PackSize='proportional,proportional' PackSizeProp='0187/0638,0016/0639' Rotation='0.105' RStyleDefault='ConnectionStyle.style' ScrollExtent='187,16' Size='187,16'/>
<Image AbsorbsInput='false' BackgroundOpacity='1.000' continentendpoint1='6' continentendpoint2='10' Location='18,257' Name='Connection22' PackLocation='proportional,proportional' PackLocationProp='0229/0638,0265/0639' PackSize='proportional,proportional' PackSizeProp='0423/0638,0016/0639' Rotation='0.215' RStyleDefault='ConnectionStyle.style' ScrollExtent='423,16' Size='423,16'/>
<Image AbsorbsInput='false' BackgroundOpacity='1.000' continentendpoint1='5' continentendpoint2='6' Location='50,53' Name='Connection23' PackLocation='proportional,proportional' PackLocationProp='0123/0638,0061/0639' PackSize='proportional,proportional' PackSizeProp='0147/0638,0016/0639' Rotation='0.400' RStyleDefault='ConnectionStyle.style' ScrollExtent='147,16' Size='147,16'/>
<Image AbsorbsInput='false' BackgroundOpacity='1.000' continentendpoint1='1' continentendpoint2='5' Location='-79,258' Name='Connection24' PackLocation='proportional,proportional' PackLocationProp='0036/0638,0266/0639' PackSize='proportional,proportional' PackSizeProp='0231/0638,0016/0639' Rotation='0.240' RStyleDefault='ConnectionStyle.style' ScrollExtent='231,16' Size='231,16'/>
<Checkbox Activated='true' BackgroundOpacity='1.000' Checked='true' continentid='1' Location='23,325' Name='Solsar' PackLocation='proportional,proportional' PackLocationProp='0076/0638,0399/0639' ScrollExtent='106,149' Size='106,149' Style='/Buttons.GlobalMapMap01.style' zonename='z1'></Checkbox>
<Checkbox BackgroundOpacity='1.000' continentid='2' Location='450,22' Name='Hossin' PackLocation='proportional,proportional' PackLocationProp='0511/0638,0083/0639' ScrollExtent='122,122' Size='122,122' Style='/Buttons.GlobalMapMap02.style' zonename='z2'></Checkbox>
<Checkbox BackgroundOpacity='1.000' continentid='3' Location='363,354' Name='Cyssor' PackLocation='proportional,proportional' PackLocationProp='0430/0638,0417/0639' ScrollExtent='135,127' Size='135,127' Style='/Buttons.GlobalMapMap03.style' zonename='z3'></Checkbox>
<Checkbox BackgroundOpacity='1.000' continentid='4' Location='367,152' Name='Ishundar' PackLocation='proportional,proportional' PackLocationProp='0436/0638,0217/0639' ScrollExtent='138,131' Size='138,131' Style='/Buttons.GlobalMapMap04.style' zonename='z4'></Checkbox>
<Checkbox BackgroundOpacity='1.000' continentid='5' Location='12,89' Name='Forseral' PackLocation='proportional,proportional' PackLocationProp='0086/0638,0153/0639' ScrollExtent='148,128' Size='148,128' Style='/Buttons.GlobalMapMap05.style' zonename='z5'></Checkbox>
<Checkbox BackgroundOpacity='1.000' continentid='6' Location='157,4' Name='Ceryshen' PackLocation='proportional,proportional' PackLocationProp='0211/0638,0057/0639' ScrollExtent='108,106' Size='108,106' Style='/Buttons.GlobalMapMap06.style' zonename='z6'></Checkbox>
<Checkbox BackgroundOpacity='1.000' continentid='7' Location='312,485' Name='Esamir' PackLocation='proportional,proportional' PackLocationProp='0382/0638,0560/0639' ScrollExtent='141,151' Size='141,151' Style='/Buttons.GlobalMapMap07.style' zonename='z7'></Checkbox>
<Checkbox BackgroundOpacity='1.000' continentid='8' Location='501,227' Name='Oshur' PackLocation='proportional,proportional' PackLocationProp='0554/0638,0280/0639' ScrollExtent='106,106' Size='106,106' Style='/Buttons.GlobalMapMap08.style' zonename='z8'></Checkbox>
<Checkbox BackgroundOpacity='1.000' continentid='9' Location='166,240' Name='Searhus' PackLocation='proportional,proportional' PackLocationProp='0230/0638,0307/0639' ScrollExtent='128,134' Size='128,134' Style='/Buttons.GlobalMapMap09.style' zonename='z9'></Checkbox>
<Checkbox BackgroundOpacity='1.000' continentid='10' Location='183,450' Name='Amerish' PackLocation='proportional,proportional' PackLocationProp='0237/0638,0511/0639' ScrollExtent='108,122' Size='108,122' Style='/Buttons.GlobalMapMap10.style' zonename='z10'></Checkbox>
<Checkbox BackgroundOpacity='1.000' continentid='11' empire='1' Location='272,72' Name='SanctuaryNC' PackLocation='proportional,proportional' PackLocationProp='0326/0638,0122/0639' ScrollExtent='108,100' Size='108,100' Style='/Buttons.GlobalMapMap11.style' zonename='home1'></Checkbox>
<Checkbox Activated='true' BackgroundOpacity='1.000' Checked='true' continentid='12' empire='0' Location='54,520' Name='SanctuaryTR' PackLocation='proportional,proportional' PackLocationProp='0084/0638,0550/0639' ScrollExtent='61,60' Size='61,60' Style='/Buttons.GlobalMapMap12.style' zonename='home2'></Checkbox>
<Checkbox BackgroundOpacity='1.000' continentid='13' empire='2' Location='523,479' Name='SanctuaryVS' PackLocation='proportional,proportional' PackLocationProp='0558/0638,0514/0639' ScrollExtent='70,70' Size='70,70' Style='/Buttons.GlobalMapMap13.style' zonename='home3'></Checkbox>
<Namespace Name='ConnectionStyle'>
<ImageStyle Name='west'>
<ImageFrame Source='ui_map_warpgate_connection_00' SourceRect='0,0,16,16'/>
</ImageStyle>
<ImageStyle Name='east'>
<ImageFrame Source='ui_map_warpgate_connection_00' SourceRect='16,0,32,16'/>
</ImageStyle>
<ImageStyle Name='center'>
<ImageFrame Source='ui_map_warpgate_connection_00' SourceRect='0,16,32,32'/>
</ImageStyle>
<RectangleStyle Center='center' CenterShrinkH='true' CenterShrinkV='true' CenterStretchH='true' CenterStretchV='true' East='east' EastShrink='true' EastStretch='true' Name='style' West='west' WestShrink='true' WestStretch='true'/>
</Namespace>
<Namespace Name='HalfConnectionStyle'>
<ImageStyle Name='west'>
<ImageFrame Source='ui_map_warpgate_connection_00' SourceRect='0,0,16,16'/>
</ImageStyle>
<ImageStyle Name='center'>
<ImageFrame Source='ui_map_warpgate_connection_00' SourceRect='0,16,16,32'/>
</ImageStyle>
<RectangleStyle Center='center' CenterShrinkH='true' CenterStretchH='true' East=' ' Name='style' West='west'/>
</Namespace>
<Text BackgroundColor='#00FFFF' BackgroundOpacity='0.475' Name='Border' ScrollExtent='640,642' Size='640,642'></Text>
</Page>
<Page Location='30,66' Name='MapWindow' PackLocation='left,top' PackLocationProp='0030/0001,0066/0001' PackSize='absolute,absolute' PackSizeProp='0383/0001,0126/0001' ScrollExtent='639,641' Size='639,641'>
<Image GetsInput='true' LocalTooltip='[@BuggyVehicle]' Location='11,24' Name='BuggyImage' PackLocation='Top,Left' PackLocationProp='0011/0001,0024/0001' ScrollExtent='21,27' Size='21,27' Stretch='false' Style='Vehicles.BuggyImageStyle' Tooltip='@BuggyVehicle' TooltipStyle='/Tooltips.Default' Visible='false'/>
<Image GetsInput='true' LocalTooltip='[@Ams]' Location='11,49' Name='AmsImage' PackLocation='Top,Left' PackLocationProp='0011/0001,0049/0001' ScrollExtent='17,36' Size='17,36' Stretch='false' Style='Vehicles.AMSImageStyle' Tooltip='@Ams' TooltipStyle='/Tooltips.Default' Visible='false'/>
<Image GetsInput='true' LocalTooltip='[@Dropship]' Location='6,88' Name='DropshipImage' PackLocation='Top,Left' PackLocationProp='0006/0001,0088/0001' ScrollExtent='36,34' Size='36,34' Stretch='false' Style='Vehicles.DropshipImageStyle' Tooltip='@Dropship' TooltipStyle='/Tooltips.Default' Visible='false'/>
<Image GetsInput='true' LocalTooltip='[@QuadVehicle]' Location='33,23' Name='QuadImage' PackLocation='Top,Left' PackLocationProp='0033/0001,0023/0001' ScrollExtent='17,26' Size='17,26' Stretch='false' Style='Vehicles.QuadImageStyle' Tooltip='@QuadVehicle' TooltipStyle='/Tooltips.Default' Visible='false'/>
<Image GetsInput='true' LocalTooltip='[@FlightVehicle]' Location='30,50' Name='FlightVehicleImage' PackLocation='Top,Left' PackLocationProp='0030/0001,0050/0001' ScrollExtent='19,27' Size='19,27' Stretch='false' Style='Vehicles.FlightVehicleImageStyle' Tooltip='@FlightVehicle' TooltipStyle='/Tooltips.Default' Visible='false'/>
<Image GetsInput='true' LocalTooltip='[@Tank]' Location='51,48' Name='TankImage' PackLocation='Top,Left' PackLocationProp='0051/0001,0048/0001' ScrollExtent='20,25' Size='20,25' Stretch='false' Style='Vehicles.TankImageStyle' Tooltip='@Tank' TooltipStyle='/Tooltips.Default' Visible='false'/>
<Image GetsInput='true' LocalTooltip='[@Transport]' Location='49,77' Name='TransportImage' PackLocation='Top,Left' PackLocationProp='0049/0001,0077/0001' ScrollExtent='15,33' Size='15,33' Stretch='false' Style='Vehicles.TransportImageStyle' Tooltip='@Transport' TooltipStyle='/Tooltips.Default' Visible='false'/>
<Image GetsInput='true' LocalTooltip='[@hemine]' Location='0,80' Name='MineImage' ScrollExtent='16,16' Size='16,16' Style='Deployables.MineStyle' Tooltip='@hemine' TooltipStyle='/Tooltips.Default' Visible='false'/>
<Image GetsInput='true' LocalTooltip='[@boomer]' Location='0,63' Name='BoomerImage' ScrollExtent='16,16' Size='16,16' Style='Deployables.BoomerStyle' Tooltip='@boomer' TooltipStyle='/Tooltips.Default' Visible='false'/>
<Image GetsInput='true' LocalTooltip='[@spitfire_turret]' Location='0,42' Name='SpitfireImage' ScrollExtent='13,16' Size='13,16' Style='Deployables.SpitfireStyle' Tooltip='@spitfire_turret' TooltipStyle='/Tooltips.Default' Visible='false'/>
<Image GetsInput='true' LocalTooltip='[@motionalarmsensor]' Location='0,22' Name='MotionSensorImage' ScrollExtent='18,16' Size='18,16' Style='Deployables.MotionSensorStyle' Tooltip='@motionalarmsensor' TooltipStyle='/Tooltips.Default' Visible='false'/>
<Image Activated='true' GetsInput='true' LocalTooltip='[@manned_turret]' Name='MannedTurretImage' ScrollExtent='24,16' Size='24,16' Style='Deployables.MannedTurretStyle' Tooltip='@manned_turret' TooltipStyle='/Tooltips.Default' Visible='false'/>
<Text continentid='1' Font='/Fonts.HudFont3' GetsInput='false' LocalText='[@Solsar]' Location='3,5' Name='MapText' PackLocation='proportional,proportional' PackLocationProp='0128/0639,0016/0641' PackSize='fixed,fixed' PackSizeProp='0002/0003,0002/0003' ScrollExtent='250,22' ShadowStyle='/Shadows.Default' Size='250,22' TextAlignment='Center' TextAlignmentVertical='Center'>@Solsar</Text>
<Image Location='92,3' Name='ZeroImage' ScrollExtent='9,14' Size='9,14' Style='Numbers.ZeroStyle' Visible='false'/>
<Image Location='102,2' Name='OneImage' ScrollExtent='7,13' Size='7,13' Style='Numbers.OneStyle' Visible='false'/>
<Image Location='111,2' Name='TwoImage' ScrollExtent='7,13' Size='7,13' Style='Numbers.TwoStyle' Visible='false'/>
<Image Location='119,2' Name='ThreeImage' ScrollExtent='10,13' Size='10,13' Style='Numbers.ThreeStyle' Visible='false'/>
<Image Location='130,2' Name='FourImage' ScrollExtent='9,13' Size='9,13' Style='Numbers.FourStyle' Visible='false'/>
<Image Location='141,2' Name='FiveImage' ScrollExtent='9,13' Size='9,13' Style='Numbers.FiveStyle' Visible='false'/>
<Image Location='152,2' Name='SixImage' ScrollExtent='8,13' Size='8,13' Style='Numbers.SixStyle' Visible='false'/>
<Image Location='163,2' Name='SevenImage' ScrollExtent='8,13' Size='8,13' Style='Numbers.SevenStyle' Visible='false'/>
<Image Location='174,3' Name='EightImage' ScrollExtent='7,14' Size='7,14' Style='Numbers.EightStyle' Visible='false'/>
<Image Location='184,3' Name='NineImage' ScrollExtent='7,14' Size='7,14' Style='Numbers.NineStyle' Visible='false'/>
<Image Location='49,4' Name='CircleImage' ScrollExtent='20,20' Size='20,20' Style='Waypoint.CircleStyle' Visible='false'/>
<Image Location='75,1' Name='PlayerImage' ScrollExtent='13,40' Size='13,40' Style='Waypoint.PlayerStyle'/>
<Image Location='3,4' Name='SquareImage' ScrollExtent='20,20' Size='20,20' Style='Waypoint.SquareStyle' Visible='false'/>
<Image Location='26,4' Name='TriangleImage' ScrollExtent='19,20' Size='19,20' Style='Waypoint.TriangleStyle' Visible='false'/>
<Image Location='4,3' Name='DropLocationImage' ScrollExtent='20,20' Size='20,20' Style='Droppod.DroppodCursorStyle' Visible='false'/>
<Image Location='31,53' Name='SelectedBuildingImage' ScrollExtent='32,32' Size='32,32' Style='Waypoint.SelectedBuildingStyle'/>
<Image Color='#FF0000' Location='40,16' Name='ClaimedImage' ScrollExtent='32,32' Size='32,32' Style='Waypoint.ClaimedStyle'/>
<Image Color='#00F2C9' Location='22,16' Name='SquadClaimedImage' ScrollExtent='32,32' Size='32,32' Style='Waypoint.SquadClaimedStyle'/>
<OverheadMap AbsorbsInput='false' Name='OverheadMap' PackSize='1,1' PackSizeProp='0002/0003,0002/0003' ScrollExtent='639,641' Size='639,641'/>
</Page>
<Namespace Name='Vehicles'>
<ImageStyle Name='TransportImageStyle'>
<ImageFrame Source='squad_vehicle_map_icons_00' SourceRect='0,24,14,54'/>
</ImageStyle>
<ImageStyle Name='DropshipImageStyle'>
<ImageFrame Source='squad_vehicle_map_icons_00' SourceRect='31,24,66,58'/>
</ImageStyle>
<ImageStyle Name='FlightVehicleImageStyle'>
<ImageFrame Source='squad_vehicle_map_icons_00' SourceRect='55,0,75,25'/>
</ImageStyle>
<ImageStyle Name='AMSImageStyle'>
<ImageFrame Source='squad_vehicle_map_icons_00' SourceRect='15,24,32,58'/>
</ImageStyle>
<ImageStyle Name='QuadImageStyle'>
<ImageFrame Source='squad_vehicle_map_icons_00' SourceRect='0,0,17,24'/>
</ImageStyle>
<ImageStyle Name='TankImageStyle'>
<ImageFrame Source='squad_vehicle_map_icons_00' SourceRect='37,0,55,25'/>
</ImageStyle>
<ImageStyle Name='BuggyImageStyle'>
<ImageFrame Source='squad_vehicle_map_icons_00' SourceRect='17,0,38,25'/>
</ImageStyle>
</Namespace>
<Namespace Name='Droppod'>
<ImageStyle Name='DroppodCursorStyle'>
<ImageFrame Source='drop_circle_cursor_00' SourceRect='0,0,20,20'/>
</ImageStyle>
</Namespace>
<Namespace Name='Numbers'>
<ImageStyle Name='OneStyle'>
<ImageFrame Source='numbers' SourceRect='0,0,7,13'/>
</ImageStyle>
<ImageStyle Name='TwoStyle'>
<ImageFrame Source='numbers' SourceRect='7,0,14,13'/>
</ImageStyle>
<ImageStyle Name='ThreeStyle'>
<ImageFrame Source='numbers' SourceRect='14,0,24,13'/>
</ImageStyle>
<ImageStyle Name='FourStyle'>
<ImageFrame Source='numbers' SourceRect='23,0,32,13'/>
</ImageStyle>
<ImageStyle Name='FiveStyle'>
<ImageFrame Source='numbers' SourceRect='32,0,41,13'/>
</ImageStyle>
<ImageStyle Name='SixStyle'>
<ImageFrame Source='numbers' SourceRect='41,0,49,13'/>
</ImageStyle>
<ImageStyle Name='SevenStyle'>
<ImageFrame Source='numbers' SourceRect='49,0,57,13'/>
</ImageStyle>
<ImageStyle Name='EightStyle'>
<ImageFrame Source='numbers' SourceRect='0,14,7,28'/>
</ImageStyle>
<ImageStyle Name='NineStyle'>
<ImageFrame Source='numbers' SourceRect='8,14,15,28'/>
</ImageStyle>
<ImageStyle Name='ZeroStyle'>
<ImageFrame Source='numbers' SourceRect='16,14,25,28'/>
</ImageStyle>
</Namespace>
<Namespace Name='Waypoint'>
<ImageStyle Name='ClaimedStyle'>
<ImageFrame Source='ui_map_flag_00' SourceRect='0,0,32,32'/>
</ImageStyle>
<ImageStyle Name='SquadClaimedStyle'>
<ImageFrame Source='ui_map_flag_00' SourceRect='0,0,32,32'/>
</ImageStyle>
<ImageStyle Name='SelectedBuildingStyle'>
<ImageFrame Source='ui_map_flag_00' SourceRect='0,0,32,32'/>
</ImageStyle>
<ImageStyle Name='TriangleStyle'>
<ImageFrame Source='waypoints' SourceRect='0,0,19,20'/>
</ImageStyle>
<ImageStyle Name='SquareStyle'>
<ImageFrame Source='waypoints' SourceRect='20,0,40,20'/>
</ImageStyle>
<ImageStyle Name='CircleStyle'>
<ImageFrame Source='waypoints' SourceRect='0,20,20,40'/>
</ImageStyle>
<ImageStyle Name='PlayerStyle'>
<ImageFrame Source='waypoints' SourceRect='41,0,54,40'/>
</ImageStyle>
</Namespace>
<Namespace Name='Deployables'>
<ImageStyle Name='MotionSensorStyle'>
<ImageFrame Source='motion_alarm_sensor_icon_00' SourceRect='0,0,36,32'/>
</ImageStyle>
<ImageStyle Name='MineStyle'>
<ImageFrame Source='he_mine_icon_00' SourceRect='0,0,32,32'/>
</ImageStyle>
<ImageStyle Name='SpitfireStyle'>
<ImageFrame Source='spitfire_icon_00' SourceRect='0,0,26,32'/>
</ImageStyle>
<ImageStyle Name='BoomerStyle'>
<ImageFrame Source='boomer_he_mine_icon_00' SourceRect='0,0,32,32'/>
</ImageStyle>
<ImageStyle Name='MannedTurretStyle'>
<ImageFrame Source='turret_icon_00' SourceRect='0,0,46,32'/>
</ImageStyle>
</Namespace>
<Image BackgroundOpacity='1.000' Location='28,710' Name='ButtonBorder' PackLocation='left,bottom' PackLocationProp='0028/0001,-057/0001' PackSize='absolute,fixed' PackSizeProp='0059/0001,0002/0003' RStyleDefault='/WindowPanes.ButtonBorder.style' ScrollExtent='963,31' Size='963,31'/>
<Image BackgroundOpacity='1.000' Location='40,0' Name='Title' PackLocation='center,top' PackLocationProp='-471/0001,0000/0001' PackSize='absolute,fixed' PackSizeProp='0078/0001,0002/0003' RStyleDefault='/WindowPanes.TitleBarFocus.style' ScrollExtent='944,32' Size='944,32'/>
<Image BackgroundOpacity='1.000' Location='0,12' Name='Background' Opacity='0.700' PackSize='1,1' PackSizeProp='0002/0003,0002/0003' RStyleDefault='/WindowPanes.BigBackground.style' ScrollExtent='1022,767' Size='1022,767' Stretch='false' Style=' '/>
<RectangleStyle Center='BackgroundTileStyle' CenterShrinkH='true' CenterShrinkV='true' Name='RBackgroundTileStyle'/>
<Image BackgroundOpacity='1.000' Name='BackgroundTile' PackSize='1,1' PackSizeProp='0002/0003,0002/0003' RStyleDefault='RBackgroundTileStyle' ScrollExtent='1022,767' Size='1022,767' Stretch='false' Style=' '/>
<ImageStyle Name='BackgroundTileStyle'>
<ImageFrame>
<ImageFragment Source='ui_window_map_bg_00' SourceRect='0,0,64,64'/>
<ImageFragment Offset='64,0' Source='ui_window_map_bg_01' SourceRect='0,0,64,64'/>
<ImageFragment Offset='0,64' Source='ui_window_map_bg_02' SourceRect='0,0,64,64'/>
<ImageFragment Offset='64,64' Source='ui_window_map_bg_03' SourceRect='0,0,64,64'/>
</ImageFrame>
</ImageStyle>
</Page>
