<Page Name='PCT' PackLocation='0.5, 0.5' ScrollExtent='800,600' Size='800,600' Visible='false'>
<Button Location='90,90' Name='Email' OnPress='ui_pushstate
















ui_showpage Email' ScrollExtent='200,32' Size='200,32' Style='/Buttons.Default.style'>E-Mail</Button>
<Button Location='300,90' Name='News' OnPress='ui_pushstate
















ui_showpage News' ScrollExtent='200,32' Size='200,32' Style='/Buttons.Default.style'>News</Button>
<Button Enabled='false' Location='510,90' Name='Calendar' OnPress='ui_pushstate
















ui_showpage Calendar' ScrollExtent='200,32' Size='200,32' Style='/Buttons.Default.style' TextColor='#808080'>Calendar</Button>
<Button Location='90,130' Name='Missions' OnPress='ui_pushstate
















ui_showpage Missions' ScrollExtent='200,32' Size='200,32' Style='/Buttons.Default.style'>Missions</Button>
<Button Location='300,130' Name='Maps' OnPress='ui_pushstate
















ui_showpage PlanetaryMap' ScrollExtent='200,32' Size='200,32' Style='/Buttons.Default.style'>Maps</Button>
<Button Location='510,130' Name='Picture Frames' OnPress='ui_pushstate
















ui_showpage Photos' ScrollExtent='200,32' Size='200,32' Style='/Buttons.Default.style'>Picture Frames</Button>
<Button Location='760,60' Name='Exit' OnPress='ui_popstate' ScrollExtent='16,16' Size='16,16' Style='/Buttons.Exit.style'></Button>
<Image Location='250,160' Name='CorprateLogo' PackLocation='0.5,0.5' ScrollExtent='400,400' Size='300,300'/>
<Image Location='9,47' Name='Plate1' Opacity='0.30' ScrollExtent='782,505' Size='782,505' Stretch='false' Style='/Plates.Large'/>
<Image Name='Backdrop' ScrollExtent='800,600' Size='800,600' Style='/Backdrops.BluePlanet'/>
</Page>
