<Page Name='SelectEmpire' PackSize='1,1' PackSizeProp='0002/0003,0002/0003' ScrollExtent='1024,768' Size='1024,768' Visible='false'>
<Button LocalText='New Button' Location='490,525' Name='RotateRight' PackLocation='center,bottom' PackLocationProp='-022/0001,-243/0001' ScrollExtent='17,12' Size='17,12' Style='/Buttons.CharacterCreateRotateRight.style' TooltipStyle='/Tooltips.Default'>New Button</Button>
<Button LocalText='New Button' Location='210,525' Name='RotateLeft' PackLocation='center,bottom' PackLocationProp='-302/0001,-243/0001' PackSize='fixed,fixed' PackSizeProp='0002/0003,0002/0003' ScrollExtent='17,12' Size='17,12' Style='/Buttons.CharacterCreateRotateLeft.style' TooltipStyle='/Tooltips.Default'>New Button</Button>
<Text Color='#72C9D1' Font='/Fonts.Agency20' LocalText='[@selectempire]' Location='51,518' Name='SelectEmpireText' PackLocation='left,bottom' PackLocationProp='0051/0001,-250/0001' PackSize='absolute,fixed' PackSizeProp='0400/0001,0002/0003' ScrollExtent='624,27' Size='624,27' TextAlignment='Center'>@selectempire</Text>
<Page BackgroundColor='#0000FF' Location='48,55' Name='Logos' PackLocation='left,top' PackLocationProp='0048/0001,0055/0001' PackSize='a,a' PackSizeProp='0394/0001,0308/0001' ScrollExtent='630,460' Size='630,460'>
<Page Location='171,171' Name='NC' ScrollExtent='288,288' Size='288,288'>
<Image Location='12,27' Name='Glow' PackLocation='cfc,cfc' PackLocationProp='0000/0001,0000/0001' PackSize='p,p' PackSizeProp='0264/0288,0234/0288' ScrollExtent='264,234' Size='264,234' Style='/Frontend.NCLogoGlow'/>
<Image Location='12,27' Name='Logo' PackLocation='cfc,cfc' PackLocationProp='0000/0001,0000/0001' PackSize='p,p' PackSizeProp='0264/0288,0234/0288' ScrollExtent='264,234' Size='264,234' Style='/Frontend.NC3DLogo'/>
<Button BackgroundOpacity='0.000' Name='Button' PackSize='1,1' PackSizeProp='0002/0003,0002/0003' ScrollExtent='288,288' Size='288,288' Style='/Buttons.ShellEmpireButton.button' TooltipStyle='/Tooltips.Default'></Button>
</Page>
<Page Location='370,40' Name='VS' ScrollExtent='200,200' Size='200,200'>
<Image Location='23,18' Name='Glow' PackLocation='cfc,cfc' PackLocationProp='0000/0001,-001/0001' PackSize='p,p' PackSizeProp='0154/0200,0162/0200' ScrollExtent='154,162' Size='154,162' Style='/Frontend.VSLogoGlow'/>
<Image Location='23,18' Name='Logo' PackLocation='cfc,cfc' PackLocationProp='0000/0001,-001/0001' PackSize='p,p' PackSizeProp='0154/0200,0162/0200' ScrollExtent='154,162' Size='154,162' Style='/Frontend.VS3DLogo'/>
<Button BackgroundOpacity='0.000' Name='Button' PackSize='1,1' PackSizeProp='0002/0003,0002/0003' ScrollExtent='200,200' Size='200,200' Style='/Buttons.ShellEmpireButton.button' TooltipStyle='/Tooltips.Default'></Button>
</Page>
<Page Location='60,40' Name='TR' ScrollExtent='200,200' Size='200,200'>
<Image Location='36,20' Name='Glow' PackLocation='cfc,cfc' PackLocationProp='0000/0001,0000/0001' PackSize='p,p' PackSizeProp='0128/0200,0161/0200' ScrollExtent='128,161' Size='128,161' Style='/Frontend.TRLogoGlow'/>
<Image Location='36,20' Name='Logo' PackLocation='cfc,cfc' PackLocationProp='0000/0001,0000/0001' PackSize='p,p' PackSizeProp='0128/0200,0161/0200' ScrollExtent='128,161' Size='128,161' Style='/Frontend.TR3DLogo'/>
<Button BackgroundOpacity='0.000' Name='Button' PackSize='1,1' PackSizeProp='0002/0003,0002/0003' ScrollExtent='200,200' Size='200,200' Style='/Buttons.ShellEmpireButton.button' TooltipStyle='/Tooltips.Default'></Button>
</Page>
<GameObjectView BackgroundColor='#0000FF' BackgroundOpacity='1.000' Location='227,240' Name='E3' PackLocation='cpc,cpc' PackLocationProp='0011/0630,0109/0460' PackSize='p,p' PackSizeProp='0199/0630,0198/0460' ScrollExtent='199,198' Size='199,198' Visible='false'/>
<GameObjectView BackgroundColor='#FF00FF' BackgroundOpacity='1.000' Location='408,63' Name='E1' PackLocation='cpc,cpc' PackLocationProp='0168/0630,-093/0460' PackSize='p,p' PackSizeProp='0150/0630,0149/0460' ScrollExtent='150,149' Size='150,149' Visible='false'/>
<GameObjectView BackgroundColor='#FF0000' BackgroundOpacity='1.000' Location='88,58' Name='E2' PackLocation='cpc,cpc' PackLocationProp='-152/0630,-098/0460' PackSize='p,p' PackSizeProp='0150/0630,0149/0460' ScrollExtent='150,149' Size='150,149' Visible='false'/>
</Page>
<Page Location='670,55' Name='EmpireDescription' PackLocation='right,top' PackLocationProp='-354/0001,0055/0001' PackSize='fixed,absolute' PackSizeProp='0002/0003,0115/0001' ScrollExtent='300,653' Size='300,653'>
<Button Enabled='false' LocalText='Planetside' Location='10,10' Name='Heading' PackLocation='left,top' PackLocationProp='0010/0001,0010/0001' PackSize='absolute,fixed' PackSizeProp='0037/0001,0002/0003' ScrollExtent='263,30' Size='263,30' Style='/Buttons.FrontendTitleButton.style' TooltipStyle='/Tooltips.Default'>Planetside</Button>
<Text Color='#72C9D1' Font='/Fonts.Agency18' LocalText='[@EmpireGeneralDescription]' Location='10,45' Name='EmpireText' PackLocation='left,top' PackLocationProp='0010/0001,0045/0001' PackSize='absolute,absolute' PackSizeProp='0036/0001,0051/0001' ScrollExtent='264,602' Size='264,602'>@EmpireGeneralDescription</Text>
<Scrollbar Control='EmpireText' Location='280,45' Name='Scrollbar' PackLocation='right,top' PackLocationProp='-020/0001,0045/0001' PackSize='fixed,absolute' PackSizeProp='0002/0003,0051/0001' ScrollExtent='10,602' Size='10,602' Style='/ScrollBars.frontend_vertical.style'/>
<Image BackgroundOpacity='1.000' Name='Box' PackLocation='left,top' PackLocationProp='0000/0001,0000/0001' PackSize='1,1' PackSizeProp='0002/0003,0002/0003' RStyleDefault='/Frontend.Box.style' ScrollExtent='300,653' Size='300,653' Stretch='false' Style=' '/>
</Page>
<ImageStyle Name='BorderStyle'>
<ImageFrame SourceRect='0,0,561,473'>
<ImageFragment Source='ui_shell_empire_buttons_border_00' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,0' Source='ui_shell_empire_buttons_border_01' SourceRect='0,0,256,256'/>
<ImageFragment Offset='512,0' Source='ui_shell_empire_buttons_border_02' SourceRect='0,0,49,256'/>
<ImageFragment Offset='0,256' Source='ui_shell_empire_buttons_border_03' SourceRect='0,0,256,217'/>
<ImageFragment Offset='256,256' Source='ui_shell_empire_buttons_border_04' SourceRect='0,0,256,217'/>
<ImageFragment Offset='512,256' Source='ui_shell_empire_buttons_border_05' SourceRect='0,0,49,217'/>
</ImageFrame>
</ImageStyle>
<OpacityEffector Name='RolloverEffector' Speed='2.000' TargetOpacity='1.000'/>
<OpacityEffector Name='RolloutEffector' Speed='1.000' TargetOpacity='0.750'/>
<Page Location='157,567' Name='EmpireIncentives' PackLocation='center,bottom' PackLocationProp='-355/0001,-201/0001' PackSize='fixed,fixed' PackSizeProp='0002/0003,0002/0003' ScrollExtent='406,140' Size='406,140'>
<Button BackgroundOpacity='0.000' Name='Tooltip' PackSize='1,1' PackSizeProp='0002/0003,0002/0003' ScrollExtent='406,140' Size='406,140'></Button>
<Text Color='#72C9D1' Font='/Fonts.HudFont3' LocalText='[@EmpireCounts_FrontEndTitle]' Location='45,7' Name='Title' PackLocation='left,top' PackLocationProp='0045/0001,0007/0001' PackSize='absolute,fixed' PackSizeProp='0241/0001,0002/0003' ScrollExtent='165,34' Size='165,24' TextAlignment='Center' TextAlignmentVertical='Center'>@EmpireCounts_FrontEndTitle</Text>
<Text Color='#72C9D1' Font='/Fonts.HudFont3' LocalText='[@EmpireIncentives_FrontEndTitle]' Location='217,7' Name='Title' PackLocation='right,top' PackLocationProp='-189/0001,0007/0001' PackSize='absolute,fixed' PackSizeProp='0220/0001,0002/0003' ScrollExtent='186,34' Size='186,24' TextAlignment='Center' TextAlignmentVertical='Center'>@EmpireIncentives_FrontEndTitle</Text>
<Button Enabled='false' LocalText='Planetside' Location='227,33' Name='TRIncentive' PackLocation='right,top' PackLocationProp='-179/0001,0033/0001' PackSize='absolute,fixed' PackSizeProp='0239/0001,0002/0003' ScrollExtent='167,30' Size='167,30' Style='/Buttons.FrontendTitleButton.style' TooltipStyle='/Tooltips.Default'>Planetside</Button>
<Button Enabled='false' LocalText='Planetside' Location='226,68' Name='NCIncentive' PackLocation='right,top' PackLocationProp='-180/0001,0068/0001' PackSize='absolute,fixed' PackSizeProp='0239/0001,0002/0003' ScrollExtent='167,30' Size='167,30' Style='/Buttons.FrontendTitleButton.style' TooltipStyle='/Tooltips.Default'>Planetside</Button>
<Button Enabled='false' LocalText='Planetside' Location='226,103' Name='VSIncentive' PackLocation='right,top' PackLocationProp='-180/0001,0103/0001' PackSize='absolute,fixed' PackSizeProp='0239/0001,0002/0003' ScrollExtent='167,30' Size='167,30' Style='/Buttons.FrontendTitleButton.style' TooltipStyle='/Tooltips.Default'>Planetside</Button>
<Progressbar BackgroundColor='#858585' BarBackgroundColor='#DE4E4E' Location='95,42' Name='TRProgress' PackLocation='left,top' PackLocationProp='0095/0001,0042/0001' PackSize='fixed,fixed' PackSizeProp='0002/0003,0002/0003' Progress='0.800' ScrollExtent='100,12' Size='100,12' Style='/ProgressBars.Health.style'/>
<Progressbar BackgroundColor='#858585' BarBackgroundColor='#6572D6' Location='95,77' Name='NCProgress' PackLocation='left,top' PackLocationProp='0095/0001,0077/0001' PackSize='fixed,fixed' PackSizeProp='0002/0003,0002/0003' Progress='0.800' ScrollExtent='100,12' Size='100,12' Style='/ProgressBars.Health.style'/>
<Progressbar BackgroundColor='#858585' BarBackgroundColor='#92579E' Location='95,112' Name='VSProgress' PackLocation='left,top' PackLocationProp='0095/0001,0112/0001' PackSize='fixed,fixed' PackSizeProp='0002/0003,0002/0003' Progress='0.800' ScrollExtent='100,12' Size='100,12' Style='/ProgressBars.Health.style'/>
<Image AbsorbsInput='false' Location='10,33' Name='TR' PackLocation='left,top' PackLocationProp='0010/0001,0033/0001' ScrollExtent='32,32' Size='32,32' Style='/Frontend.MiniTR'/>
<Image AbsorbsInput='false' Location='10,67' Name='NC' PackLocation='left,top' PackLocationProp='0010/0001,0067/0001' ScrollExtent='32,32' Size='32,32' Style='/Frontend.MiniNC'/>
<Image AbsorbsInput='false' Location='10,101' Name='VS' PackLocation='left,top' PackLocationProp='0010/0001,0101/0001' ScrollExtent='32,32' Size='32,32' Style='/Frontend.MiniVS'/>
<Text Color='#72C9D1' Font='/Fonts.Agency20' LocalText='-99%' Location='44,36' Name='XP_TR' PackLocation='left,top' PackLocationProp='0044/0001,0036/0001' ScrollExtent='48,24' Size='48,22' TextAlignment='Center'>-99%</Text>
<Text Color='#72C9D1' Font='/Fonts.Agency20' LocalText='-99%' Location='44,72' Name='XP_NC' PackLocation='left,top' PackLocationProp='0044/0001,0072/0001' ScrollExtent='48,24' Size='48,22' TextAlignment='Center'>-99%</Text>
<Text Color='#72C9D1' Font='/Fonts.Agency20' LocalText='-99%' Location='44,106' Name='XP_VS' PackLocation='left,top' PackLocationProp='0044/0001,0106/0001' ScrollExtent='48,24' Size='48,22' TextAlignment='Center'>-99%</Text>
<Image BackgroundOpacity='1.000' Name='Box' PackLocation='left,top' PackLocationProp='0000/0001,0000/0001' PackSize='1,1' PackSizeProp='0002/0003,0002/0003' RStyleDefault='/Frontend.Box.style' ScrollExtent='406,140' Size='406,140' Stretch='false' Style=' '/>
</Page>
<Page Name='FrontendBasic' PackSize='1,1' PackSizeProp='0002/0003,0002/0003' ScrollExtent='1024,768' Size='1024,768'>
<Button LocalText='[@FrontendBackButton]' Location='5,723' Name='BackButton' PackLocation='left,bottom' PackLocationProp='0005/0001,-045/0001' PackSize='fixed,fixed' PackSizeProp='0002/0003,0002/0003' ScrollExtent='120,40' Size='120,40' Style='/Buttons.FrontendButton.style'>@FrontendBackButton</Button>
<Button IsDefaultButton='true' LocalText='[@FrontendNextButton]' Location='899,723' Name='NextButton' PackLocation='right,bottom' PackLocationProp='-125/0001,-045/0001' PackSize='fixed,fixed' PackSizeProp='0002/0003,0002/0003' ScrollExtent='120,40' Size='120,40' Style='/Buttons.FrontendButton.style'>@FrontendNextButton</Button>
<Button LocalText='?' Location='487,728' Name='HelpButton' PackLocation='left,top' PackLocationProp='0487/0001,0728/0001' PackSize='fixed,fixed' PackSizeProp='0002/0003,0002/0003' ScrollExtent='50,35' Size='50,35' Style='/Buttons.FrontendButton.iconstyle' Visible='false'>?</Button>
<Button LocalText='[@FrontendOptionButton]' Location='562,728' Name='OptionsButton' PackLocation='cfc,bottom' PackLocationProp='0100/0001,-040/0001' PackSize='fixed,fixed' PackSizeProp='0002/0003,0002/0003' ScrollExtent='100,35' Size='100,35' Style='/Buttons.FrontendButton.style' Visible='false'>@FrontendOptionButton</Button>
<Button LocalText='EXIT' Location='5,723' Name='CloseButton' PackLocation='left,bottom' PackLocationProp='0005/0001,-045/0001' PackSize='fixed,fixed' PackSizeProp='0002/0003,0002/0003' ScrollExtent='120,40' Size='120,40' Style='/Buttons.FrontendButton.style' Visible='false'>EXIT</Button>
<Image BackgroundOpacity='1.000' Location='15,10' Name='ThickTop' PackLocation='left,top' PackLocationProp='0015/0001,0010/0001' PackSize='absolute,fixed' PackSizeProp='0029/0001,0002/0003' RStyleDefault='/Frontend.Thick.style' ScrollExtent='995,4' Size='995,4' Stretch='false' Style=' '/>
<Image BackgroundOpacity='1.000' Location='125,754' Name='ThickBottom' PackLocation='left,bottom' PackLocationProp='0125/0001,-014/0001' PackSize='absolute,fixed' PackSizeProp='0612/0001,0002/0003' RStyleDefault='/Frontend.Thick.style' ScrollExtent='412,4' Size='412,4' Stretch='false' Style=' '/>
<Image BackgroundOpacity='1.000' Location='537,754' Name='ThickBottom2' PackLocation='left,bottom' PackLocationProp='0537/0001,-014/0001' PackSize='absolute,fixed' PackSizeProp='0662/0001,0002/0003' RStyleDefault='/Frontend.Thick.style' ScrollExtent='362,4' Size='362,4' Stretch='false' Style=' '/>
<Image BackgroundOpacity='1.000' Location='11,10' Name='ThickLeft' PackLocation='left,top' PackLocationProp='0011/0001,0010/0001' PackSize='fixed,absolute' PackSizeProp='0002/0003,0056/0001' RStyleDefault='/Frontend.Thick.style' ScrollExtent='4,712' Size='4,712' Stretch='false' Style=' '/>
<Image BackgroundOpacity='1.000' Location='1010,10' Name='ThickRight' PackLocation='right,top' PackLocationProp='-014/0001,0010/0001' PackSize='fixed,absolute' PackSizeProp='0002/0003,0056/0001' RStyleDefault='/Frontend.Thick.style' ScrollExtent='4,712' Size='4,712' Stretch='false' Style=' '/>
<Image BackgroundOpacity='1.000' Location='979,37' Name='EastBorder' PackLocation='right,top' PackLocationProp='-045/0001,0037/0001' PackSize='fixed,absolute' PackSizeProp='0002/0003,0083/0001' RStyleDefault='/Frontend.EastBorder.style' ScrollExtent='21,685' Size='21,685' Stretch='false' Style=' '/>
<Image BackgroundOpacity='1.000' Location='24,28' Name='WestBorder' PackLocation='left,top' PackLocationProp='0024/0001,0028/0001' PackSize='fixed,absolute' PackSizeProp='0002/0003,0073/0001' RStyleDefault='/Frontend.WestBorder.style' ScrollExtent='21,695' Size='21,695' Stretch='false' Style=' '/>
<Image BackgroundOpacity='1.000' Location='125,722' Name='SouthBorder' PackLocation='left,bottom' PackLocationProp='0125/0001,-046/0001' PackSize='absolute,fixed' PackSizeProp='0250/0001,0002/0003' RStyleDefault='/Frontend.SouthBorder.style' ScrollExtent='774,22' Size='774,22' Stretch='false' Style=' '/>
<Image BackgroundOpacity='1.000' Location='24,24' Name='NorthBorder' PackLocation='left,top' PackLocationProp='0024/0001,0024/0001' PackSize='absolute,fixed' PackSizeProp='0057/0001,0002/0003' RStyleDefault='/Frontend.NorthBorder.style' ScrollExtent='967,22' Size='967,22' Stretch='false' Style=' '/>
<Image Color='#E9DAC0' Name='Planet' ScrollExtent='1024,768' Size='1024,768' Stretch='false' Style='/Plates.PlanetBackground'/>
</Page>
</Page>
