<Namespace Name='Sliderbars'>
<Namespace Name='Options'>
<SliderbarStyle Background='Background' EndCap='EndCap' Name='Style' Slider='Slider' StartCap='StartCap'/>
<ImageStyle Name='EndCap'>
<ImageFrame Source='ui_options_slider_bar_00' SourceRect='30,0,32,13'/>
</ImageStyle>
<ImageStyle Name='StartCap'>
<ImageFrame Source='ui_options_slider_bar_00' SourceRect='0,0,2,13'/>
</ImageStyle>
<ImageStyle Name='Background'>
<ImageFrame Source='ui_options_slider_bar_00' SourceRect='2,0,30,13'/>
</ImageStyle>
<ImageStyle Name='Slider'>
<ImageFrame Source='ui_options_slider_00' SourceRect='0,0,5,26'/>
</ImageStyle>
</Namespace>
<Namespace Name='HDefault'>
<ImageStyle Name='StartCap'>
<ImageFrame Source='ui_sliderbar' SourceRect='0,0,3,9'/>
</ImageStyle>
<ImageStyle Name='EndCap'>
<ImageFrame Source='ui_sliderbar' SourceRect='30,0,32,9'/>
</ImageStyle>
<ImageStyle Name='Background'>
<ImageFrame Source='ui_sliderbar' SourceRect='3,0,28,9'/>
</ImageStyle>
<ImageStyle Name='Slider'>
<ImageFrame Source='ui_sliderbar' SourceRect='0,11,10,32'/>
</ImageStyle>
<SliderbarStyle Background='Background' EndCap='EndCap' Name='Style' Slider='Slider' StartCap='StartCap'/>
</Namespace>
<Namespace Name='HNew'>
<ImageStyle Name='Background'>
<ImageFrame Source='ps_keymap_art_00' SourceRect='0,457,285,472'/>
</ImageStyle>
<ImageStyle Name='Slider'>
<ImageFrame Source='ps_interface_art_00' SourceRect='0,146,5,171'/>
</ImageStyle>
<SliderbarStyle Background='Background' Name='Style' Slider='Slider'/>
</Namespace>
</Namespace>
