<Namespace Name='VScrollbar'>
<ImageStyle Name='startcap.normal'>
<ImageFrame Source='ps_interface_art_00' SourceRect='150,0,170,33'/>
</ImageStyle>
<ImageStyle Name='startcap.disabled'>
<ImageFrame Source='ps_interface_art_00' SourceRect='170,0,190,33'/>
</ImageStyle>
<ImageStyle Name='startcap.pressed'>
<ImageFrame Source='ps_interface_art_00' SourceRect='190,0,210,33'/>
</ImageStyle>
<ImageStyle Name='endcap.normal'>
<ImageFrame Source='ps_interface_art_00' SourceRect='150,222,170,256'/>
</ImageStyle>
<ImageStyle Name='endcap.disabled'>
<ImageFrame Source='ps_interface_art_00' SourceRect='170,222,190,256'/>
</ImageStyle>
<ImageStyle Name='endcap.pressed'>
<ImageFrame Source='ps_interface_art_00' SourceRect='190,222,210,256'/>
</ImageStyle>
<ImageStyle Name='background.normal'>
<ImageFrame Source='ps_interface_art_00' SourceRect='150,33,170,221'/>
</ImageStyle>
<ImageStyle Name='thumb.startcap.normal'>
<ImageFrame Source='ps_interface_art_00' SourceRect='210,0,225,11'/>
</ImageStyle>
<ImageStyle Name='thumb.background.normal'>
<ImageFrame Source='ps_interface_art_00' SourceRect='210,11,225,245'/>
</ImageStyle>
<ImageStyle Name='thumb.endcap.normal'>
<ImageFrame Source='ps_interface_art_00' SourceRect='210,245,225,256'/>
</ImageStyle>
<ScrollbarStyle Background.Disabled='background.disabled' Background.Normal='background.normal' EndCap.Disabled='endcap.disabled' EndCap.Normal='endcap.normal' EndCap.Pressed='endcap.pressed' EndCap.StopOffset='30' Name='style' StartCap.Disabled='startcap.disabled' StartCap.Normal='startcap.normal' StartCap.Pressed='startcap.pressed' Startcap.StopOffset='30' Thumb.Background.Disabled='thumb.background.disabled' Thumb.Background.Normal='thumb.background.normal' Thumb.EndCap.Disabled='thumb.endcap.disabled' Thumb.EndCap.Normal='thumb.endcap.normal' Thumb.MinSize='40' Thumb.StartCap.Disabled='thumb.startcap.disabled' Thumb.StartCap.Normal='thumb.startcap.normal'/>
<ImageStyle Name='background.disabled'>
<ImageFrame Source='ps_interface_art_00' SourceRect='170,33,190,221'/>
</ImageStyle>
</Namespace>
<Namespace Name='HScrollbar'>
<ImageStyle Name='startcap.normal'>
<ImageFrame Source='ui_scrollbar' SourceRect='0,32,16,48'/>
</ImageStyle>
<ImageStyle Name='startcap.disabled'>
<ImageFrame Source='ui_scrollbar' SourceRect='16,32,32,48'/>
</ImageStyle>
<ImageStyle Name='startcap.pressed'>
<ImageFrame Source='ui_scrollbar' SourceRect='32,32,48,48'/>
</ImageStyle>
<ImageStyle Name='background.normal'>
<ImageFrame Source='ui_scrollbar' SourceRect='0,64,48,80'/>
</ImageStyle>
<ImageStyle Name='endcap.normal'>
<ImageFrame Source='ui_scrollbar' SourceRect='0,48,16,64'/>
</ImageStyle>
<ImageStyle Name='endcap.disabled'>
<ImageFrame Source='ui_scrollbar' SourceRect='16,48,32,64'/>
</ImageStyle>
<ImageStyle Name='endcap.pressed'>
<ImageFrame Source='ui_scrollbar' SourceRect='32,48,48,64'/>
</ImageStyle>
<ImageStyle Name='thumb.startcap.normal'>
<ImageFrame Source='ui_scrollbar' SourceRect='0,80,2,96'/>
</ImageStyle>
<ImageStyle Name='thumb.startcap.disabled'>
<ImageFrame Source='ui_scrollbar' SourceRect='0,64,2,80'/>
</ImageStyle>
<ImageStyle Name='thumb.background.normal'>
<ImageFrame Source='ui_scrollbar' SourceRect='2,80,46,96'/>
</ImageStyle>
<ImageStyle Name='thumb.background.disabled'>
<ImageFrame Source='ui_scrollbar' SourceRect='2,64,46,80'/>
</ImageStyle>
<ImageStyle Name='thumb.endcap.normal'>
<ImageFrame Source='ui_scrollbar' SourceRect='46,80,48,96'/>
</ImageStyle>
<ImageStyle Name='thumb.endcap.disabled'>
<ImageFrame Source='ui_scrollbar' SourceRect='46,64,48,80'/>
</ImageStyle>
<ScrollbarStyle Background.Normal='background.normal' EndCap.Disabled='endcap.disabled' EndCap.Normal='endcap.normal' EndCap.Pressed='endcap.pressed' Name='style' StartCap.Disabled='startcap.disabled' StartCap.Normal='startcap.normal' StartCap.Pressed='startcap.pressed' Thumb.Background.Disabled='.thumb.background.disabled' Thumb.Background.Normal='thumb.background.normal' Thumb.EndCap.Disabled='thumb.endcap.disabled' Thumb.EndCap.Normal='thumb.endcap.normal' Thumb.StartCap.Disabled='thumb.startcap.disabled' Thumb.StartCap.Normal='thumb.startcap.normal'/>
</Namespace>
