<Page Name='SelectMissionOffline' PackLocation='Center,Center' PackLocationProp='-512/0001,-384/0001' ScrollExtent='1024,768' Size='1024,768' Visible='false'>
<Image Location='512,64' Name='MissionImage' PackLocation='left,top' PackLocationProp='0512/0001,0064/0001' PackSize='p,p' PackSizeProp='0464/1024,0336/0768' ScrollExtent='464,336' Size='464,336' Stretch='false' Style='Mission3.style'/>
<Page Location='53,55' Name='Mission0' ScrollExtent='449,78' Size='449,78'>
<ImageStyle Name='style'>
<ImageFrame>
<ImageFragment Source='ui_shell_mission1_00' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,0' Source='ui_shell_mission1_01' SourceRect='0,0,208,256'/>
<ImageFragment Offset='0,256' Source='ui_shell_mission1_02' SourceRect='0,0,256,80'/>
<ImageFragment Offset='256,256' Source='ui_shell_mission1_03' SourceRect='0,0,208,80'/>
</ImageFrame>
</ImageStyle>
<Button LocalText='[@OfflineMission0]' LocalTooltip='[@OfflineMissionTip0]' Location='10,10' Name='Button' ScrollExtent='429,30' Size='429,30' Style='/Buttons.FrontendButton.selected' Tooltip='@OfflineMissionTip0' TooltipStyle='/Tooltips.Default'>@OfflineMission0</Button>
<Text Color='#72C9D1' Font='/Fonts.Agency20' LocalText='[@MissionStatusReady]' Location='10,45' Name='Status' PackLocation='left,bottom' PackLocationProp='0010/0001,-033/0001' PackSize='absolute,fixed' PackSizeProp='0020/0001,0002/0003' ScrollExtent='429,30' Size='429,30' TextAlignment='Center'>@MissionStatusReady</Text>
<Image BackgroundOpacity='1.000' Name='Box' PackLocation='left,top' PackLocationProp='0000/0001,0000/0001' PackSize='1,1' PackSizeProp='0002/0003,0002/0003' RStyleDefault='/Frontend.Box.style' ScrollExtent='449,78' Size='449,78' Stretch='false' Style=' '/>
</Page>
<Page Location='53,138' Name='Mission1' ScrollExtent='449,78' Size='449,78'>
<ImageStyle Name='style'>
<ImageFrame>
<ImageFragment Source='ui_shell_mission2_00' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,0' Source='ui_shell_mission2_01' SourceRect='0,0,208,256'/>
<ImageFragment Offset='0,256' Source='ui_shell_mission2_02' SourceRect='0,0,256,80'/>
<ImageFragment Offset='256,256' Source='ui_shell_mission2_03' SourceRect='0,0,208,80'/>
</ImageFrame>
</ImageStyle>
<Button LocalText='[@OfflineMission1]' LocalTooltip='[@OfflineMissionTip1]' Location='10,10' Name='Button' ScrollExtent='429,30' Size='429,30' Style='/Buttons.FrontendButton.style' Tooltip='@OfflineMissionTip1' TooltipStyle='/Tooltips.Default'>@OfflineMission1</Button>
<Text Color='#72C9D1' Font='/Fonts.Agency20' LocalText='[@MissionStatusReady]' Location='10,45' Name='Status' PackLocation='left,bottom' PackLocationProp='0010/0001,-033/0001' PackSize='absolute,fixed' PackSizeProp='0020/0001,0002/0003' ScrollExtent='429,30' Size='429,30' TextAlignment='Center'>@MissionStatusReady</Text>
<Image BackgroundOpacity='1.000' Name='Box' PackLocation='left,top' PackLocationProp='0000/0001,0000/0001' PackSize='1,1' PackSizeProp='0002/0003,0002/0003' RStyleDefault='/Frontend.Box.style' ScrollExtent='449,78' Size='449,78' Stretch='false' Style=' '/>
</Page>
<Page Location='53,221' Name='Mission2' ScrollExtent='449,78' Size='449,78'>
<ImageStyle Name='style'>
<ImageFrame>
<ImageFragment Source='ui_shell_mission3_00' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,0' Source='ui_shell_mission3_01' SourceRect='0,0,208,256'/>
<ImageFragment Offset='0,256' Source='ui_shell_mission3_02' SourceRect='0,0,256,80'/>
<ImageFragment Offset='256,256' Source='ui_shell_mission3_03' SourceRect='0,0,208,80'/>
</ImageFrame>
</ImageStyle>
<Button LocalText='[@OfflineMission2]' LocalTooltip='[@OfflineMissionTip2]' Location='10,10' Name='Button' ScrollExtent='429,30' Size='429,30' Style='/Buttons.FrontendButton.style' Tooltip='@OfflineMissionTip2' TooltipStyle='/Tooltips.Default'>@OfflineMission2</Button>
<Text Color='#72C9D1' Font='/Fonts.Agency20' LocalText='[@MissionStatusReady]' Location='10,45' Name='Status' PackLocation='left,bottom' PackLocationProp='0010/0001,-033/0001' PackSize='absolute,fixed' PackSizeProp='0020/0001,0002/0003' ScrollExtent='429,30' Size='429,30' TextAlignment='Center'>@MissionStatusReady</Text>
<Image BackgroundOpacity='1.000' Name='Box' PackLocation='left,top' PackLocationProp='0000/0001,0000/0001' PackSize='1,1' PackSizeProp='0002/0003,0002/0003' RStyleDefault='/Frontend.Box.style' ScrollExtent='449,78' Size='449,78' Stretch='false' Style=' '/>
</Page>
<Page Location='53,304' Name='Mission3' ScrollExtent='449,78' Size='449,78'>
<ImageStyle Name='style'>
<ImageFrame>
<ImageFragment Source='ui_shell_mission4_00' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,0' Source='ui_shell_mission4_01' SourceRect='0,0,208,256'/>
<ImageFragment Offset='0,256' Source='ui_shell_mission4_02' SourceRect='0,0,256,80'/>
<ImageFragment Offset='256,256' Source='ui_shell_mission4_03' SourceRect='0,0,208,80'/>
</ImageFrame>
</ImageStyle>
<Button LocalText='[@OfflineMission3]' LocalTooltip='[@OfflineMissionTip4]' Location='10,10' Name='Button' ScrollExtent='429,30' Size='429,30' Style='/Buttons.FrontendButton.style' Tooltip='@OfflineMissionTip4' TooltipStyle='/Tooltips.Default'>@OfflineMission3</Button>
<Text Color='#72C9D1' Font='/Fonts.Agency20' LocalText='[@MissionStatusReady]' Location='10,45' Name='Status' PackLocation='left,bottom' PackLocationProp='0010/0001,-033/0001' PackSize='absolute,fixed' PackSizeProp='0020/0001,0002/0003' ScrollExtent='429,30' Size='429,30' TextAlignment='Center'>@MissionStatusReady</Text>
<Image BackgroundOpacity='1.000' Name='Box' PackLocation='left,top' PackLocationProp='0000/0001,0000/0001' PackSize='1,1' PackSizeProp='0002/0003,0002/0003' RStyleDefault='/Frontend.Box.style' ScrollExtent='449,78' Size='449,78' Stretch='false' Style=' '/>
</Page>
<Page Location='53,387' Name='Mission4' ScrollExtent='449,78' Size='449,78'>
<ImageStyle Name='style'>
<ImageFrame>
<ImageFragment Source='ui_shell_mission5_00' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,0' Source='ui_shell_mission5_01' SourceRect='0,0,208,256'/>
<ImageFragment Offset='0,256' Source='ui_shell_mission5_02' SourceRect='0,0,256,80'/>
<ImageFragment Offset='256,256' Source='ui_shell_mission5_03' SourceRect='0,0,208,80'/>
</ImageFrame>
</ImageStyle>
<Button LocalText='[@OfflineMission4]' LocalTooltip='[@OfflineMissionTip4]' Location='10,10' Name='Button' ScrollExtent='429,30' Size='429,30' Style='/Buttons.FrontendButton.style' Tooltip='@OfflineMissionTip4' TooltipStyle='/Tooltips.Default'>@OfflineMission4</Button>
<Text Color='#72C9D1' Font='/Fonts.Agency20' LocalText='[@MissionStatusReady]' Location='10,45' Name='Status' PackLocation='left,bottom' PackLocationProp='0010/0001,-033/0001' PackSize='absolute,fixed' PackSizeProp='0020/0001,0002/0003' ScrollExtent='429,30' Size='429,30' TextAlignment='Center'>@MissionStatusReady</Text>
<Image BackgroundOpacity='1.000' Name='Box' PackLocation='left,top' PackLocationProp='0000/0001,0000/0001' PackSize='1,1' PackSizeProp='0002/0003,0002/0003' RStyleDefault='/Frontend.Box.style' ScrollExtent='449,78' Size='449,78' Stretch='false' Style=' '/>
</Page>
<Page Location='53,470' Name='Mission5' ScrollExtent='449,78' Size='449,78'>
<ImageStyle Name='style'>
<ImageFrame>
<ImageFragment Source='ui_shell_mission6_00' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,0' Source='ui_shell_mission6_01' SourceRect='0,0,208,256'/>
<ImageFragment Offset='0,256' Source='ui_shell_mission6_02' SourceRect='0,0,256,80'/>
<ImageFragment Offset='256,256' Source='ui_shell_mission6_03' SourceRect='0,0,208,80'/>
</ImageFrame>
</ImageStyle>
<Button LocalText='[@OfflineMission5]' LocalTooltip='[@OfflineMissionTip5]' Location='10,10' Name='Button' ScrollExtent='429,30' Size='429,30' Style='/Buttons.FrontendButton.style' Tooltip='@OfflineMissionTip5' TooltipStyle='/Tooltips.Default'>@OfflineMission5</Button>
<Text Color='#72C9D1' Font='/Fonts.Agency20' LocalText='[@MissionStatusReady]' Location='10,45' Name='Status' PackLocation='left,bottom' PackLocationProp='0010/0001,-033/0001' PackSize='absolute,fixed' PackSizeProp='0020/0001,0002/0003' ScrollExtent='429,30' Size='429,30' TextAlignment='Center'>@MissionStatusReady</Text>
<Image BackgroundOpacity='1.000' Name='Box' PackLocation='left,top' PackLocationProp='0000/0001,0000/0001' PackSize='1,1' PackSizeProp='0002/0003,0002/0003' RStyleDefault='/Frontend.Box.style' ScrollExtent='449,78' Size='449,78' Stretch='false' Style=' '/>
</Page>
<Page Location='53,553' Name='Mission6' ScrollExtent='449,78' Size='449,78'>
<ImageStyle Name='style'>
<ImageFrame>
<ImageFragment Source='ui_shell_mission7_00' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,0' Source='ui_shell_mission7_01' SourceRect='0,0,208,256'/>
<ImageFragment Offset='0,256' Source='ui_shell_mission7_02' SourceRect='0,0,256,80'/>
<ImageFragment Offset='256,256' Source='ui_shell_mission7_03' SourceRect='0,0,208,80'/>
</ImageFrame>
</ImageStyle>
<Button LocalText='[@OfflineMission6]' LocalTooltip='[@OfflineMissionTip6]' Location='10,10' Name='Button' ScrollExtent='429,30' Size='429,30' Style='/Buttons.FrontendButton.style' Tooltip='@OfflineMissionTip6' TooltipStyle='/Tooltips.Default'>@OfflineMission6</Button>
<Text Color='#72C9D1' Font='/Fonts.Agency20' LocalText='[@MissionStatusReady]' Location='10,45' Name='Status' PackLocation='left,bottom' PackLocationProp='0010/0001,-033/0001' PackSize='absolute,fixed' PackSizeProp='0020/0001,0002/0003' ScrollExtent='429,30' Size='429,30' TextAlignment='Center'>@MissionStatusReady</Text>
<Image BackgroundOpacity='1.000' Name='Box' PackLocation='left,top' PackLocationProp='0000/0001,0000/0001' PackSize='1,1' PackSizeProp='0002/0003,0002/0003' RStyleDefault='/Frontend.Box.style' ScrollExtent='449,78' Size='449,78' Stretch='false' Style=' '/>
</Page>
<Page Location='53,636' Name='Mission7' ScrollExtent='449,78' Size='449,78'>
<ImageStyle Name='style'>
<ImageFrame>
<ImageFragment Source='ui_shell_mission8_00' SourceRect='0,0,256,256'/>
<ImageFragment Offset='256,0' Source='ui_shell_mission8_01' SourceRect='0,0,208,256'/>
<ImageFragment Offset='0,256' Source='ui_shell_mission8_02' SourceRect='0,0,256,110'/>
<ImageFragment Offset='256,256' Source='ui_shell_mission8_03' SourceRect='0,0,208,110'/>
</ImageFrame>
</ImageStyle>
<Button LocalText='[@OfflineMission7]' LocalTooltip='[@OfflineMissionTip7]' Location='10,10' Name='Button' ScrollExtent='429,30' Size='429,30' Style='/Buttons.FrontendButton.style' Tooltip='@OfflineMissionTip7' TooltipStyle='/Tooltips.Default'>@OfflineMission7</Button>
<Text Color='#72C9D1' Font='/Fonts.Agency20' LocalText='[@MissionStatusReady]' Location='10,45' Name='Status' PackLocation='left,bottom' PackLocationProp='0010/0001,-033/0001' PackSize='absolute,fixed' PackSizeProp='0020/0001,0002/0003' ScrollExtent='429,30' Size='429,30' TextAlignment='Center'>@MissionStatusReady</Text>
<Image BackgroundOpacity='1.000' Name='Box' PackLocation='left,top' PackLocationProp='0000/0001,0000/0001' PackSize='1,1' PackSizeProp='0002/0003,0002/0003' RStyleDefault='/Frontend.Box.style' ScrollExtent='449,78' Size='449,78' Stretch='false' Style=' '/>
</Page>
<Page Location='522,387' Name='MissionDescription' PackLocation='right,bottom' PackLocationProp='-502/0001,-381/0001' PackSize='fixed,absolute' PackSizeProp='0002/0003,0442/0001' ScrollExtent='449,326' Size='449,326'>
<Text Color='#72C9D1' Font='/Fonts.Agency18' LocalText='[@MissionDescription1]' Location='10,8' Name='SelectMissionOfflineInfo' PackLocation='left,top' PackLocationProp='0010/0001,0008/0001' PackSize='absolute,absolute' PackSizeProp='0035/0001,0014/0001' ScrollExtent='414,312' Size='414,312'>@MissionDescription1</Text>
<Scrollbar Control='SelectMissionOfflineInfo' Location='429,8' Name='Scrollbar' PackLocation='right,top' PackLocationProp='-020/0001,0008/0001' PackSize='fixed,absolute' PackSizeProp='0002/0003,0014/0001' ScrollExtent='10,312' Size='10,312' Style='/ScrollBars.frontend_vertical.style'/>
<Image BackgroundOpacity='1.000' Name='Box' PackLocation='left,top' PackLocationProp='0000/0001,0000/0001' PackSize='1,1' PackSizeProp='0002/0003,0002/0003' RStyleDefault='/Frontend.Box.style' ScrollExtent='449,326' Size='449,326' Stretch='false' Style=' '/>
</Page>
<Page Name='FrontendBasic' PackSize='1,1' PackSizeProp='0002/0003,0002/0003' ScrollExtent='1024,768' Size='1024,768'>
<Image BackgroundOpacity='1.000' Location='949,25' Name='ThinTopSide' PackLocation='left,top' PackLocationProp='0949/0001,0025/0001' PackSize='absolute,fixed' PackSizeProp='1004/0001,0002/0003' RStyleDefault='/Frontend.Thin.style' ScrollExtent='20,22' Size='20,22' Stretch='false' Style=' '/>
<Image BackgroundOpacity='1.000' Location='949,10' Name='ThickTopSide' PackLocation='left,top' PackLocationProp='0949/0001,0010/0001' PackSize='absolute,fixed' PackSizeProp='1004/0001,0002/0003' RStyleDefault='/Frontend.Thick.style' ScrollExtent='20,4' Size='20,4' Stretch='false' Style=' '/>
<Button LocalText='[@FrontendCreditsButton]' LocalTooltip='[@FrontendCreditsTooltip]' Location='5,723' Name='CreditsButton' PackLocation='left,bottom' PackLocationProp='0005/0001,-045/0001' PackSize='fixed,fixed' PackSizeProp='0002/0003,0002/0003' ScrollExtent='75,40' Size='75,40' Style='/Buttons.FrontendButton.style' Tooltip='@FrontendCreditsTooltip' Visible='false'>@FrontendCreditsButton</Button>
<Button LocalText='[@FrontendBackButton]' LocalTooltip='[@FrontendBackTooltip]' Location='5,723' Name='BackButton' PackLocation='left,bottom' PackLocationProp='0005/0001,-045/0001' PackSize='fixed,fixed' PackSizeProp='0002/0003,0002/0003' ScrollExtent='75,40' Size='75,40' Style='/Buttons.FrontendButton.style' Tooltip='@FrontendBackTooltip'>@FrontendBackButton</Button>
<Button LocalText='[@FrontendNextButton]' LocalTooltip='[@FrontendNextTooltip]' Location='944,723' Name='NextButton' PackLocation='right,bottom' PackLocationProp='-080/0001,-045/0001' PackSize='fixed,fixed' PackSizeProp='0002/0003,0002/0003' ScrollExtent='75,40' Size='75,40' Style='/Buttons.FrontendButton.style' Tooltip='@FrontendNextTooltip'>@FrontendNextButton</Button>
<Button LocalText='?' LocalTooltip='[@HelpTooltip]' Location='5,5' Name='HelpButton' PackLocation='left,top' PackLocationProp='0005/0001,0005/0001' PackSize='fixed,fixed' PackSizeProp='0002/0003,0002/0003' ScrollExtent='50,40' Size='50,40' Style='/Buttons.FrontendButton.iconstyle' Tooltip='@HelpTooltip'>?</Button>
<Button LocalText='[@FrontendOptionButton]' LocalTooltip='[@FrontendOptionTooltip]' Location='849,5' Name='OptionsButton' PackLocation='right,top' PackLocationProp='-175/0001,0005/0001' PackSize='fixed,fixed' PackSizeProp='0002/0003,0002/0003' ScrollExtent='100,40' Size='100,40' Style='/Buttons.FrontendButton.style' Tooltip='@FrontendOptionTooltip'>@FrontendOptionButton</Button>
<Button LocalText='X' LocalTooltip='[@FrontendCloseTooltip]' Location='969,5' Name='CloseButton' PackLocation='right,top' PackLocationProp='-055/0001,0005/0001' PackSize='fixed,fixed' PackSizeProp='0002/0003,0002/0003' ScrollExtent='50,40' Size='50,40' Style='/Buttons.FrontendButton.iconstyle' Tooltip='@FrontendCloseTooltip'>X</Button>
<Image BackgroundOpacity='1.000' Location='55,10' Name='ThickTop' PackLocation='left,top' PackLocationProp='0055/0001,0010/0001' PackSize='absolute,fixed' PackSizeProp='0230/0001,0002/0003' RStyleDefault='/Frontend.Thick.style' ScrollExtent='794,4' Size='794,4' Stretch='false' Style=' '/>
<Image BackgroundOpacity='1.000' Location='80,754' Name='ThickBottom' PackLocation='left,bottom' PackLocationProp='0080/0001,-014/0001' PackSize='absolute,fixed' PackSizeProp='0160/0001,0002/0003' RStyleDefault='/Frontend.Thick.style' ScrollExtent='864,4' Size='864,4' Stretch='false' Style=' '/>
<Image BackgroundOpacity='1.000' Location='11,44' Name='ThickLeft' PackLocation='left,top' PackLocationProp='0011/0001,0044/0001' PackSize='fixed,absolute' PackSizeProp='0002/0003,0090/0001' RStyleDefault='/Frontend.Thick.style' ScrollExtent='4,678' Size='4,678' Stretch='false' Style=' '/>
<Image BackgroundOpacity='1.000' Location='1010,45' Name='ThickRight' PackLocation='right,top' PackLocationProp='-014/0001,0045/0001' PackSize='fixed,absolute' PackSizeProp='0002/0003,0090/0001' RStyleDefault='/Frontend.Thick.style' ScrollExtent='4,678' Size='4,678' Stretch='false' Style=' '/>
<Image BackgroundOpacity='1.000' Location='979,45' Name='EastBorder' PackLocation='right,top' PackLocationProp='-045/0001,0045/0001' PackSize='fixed,absolute' PackSizeProp='0002/0003,0090/0001' RStyleDefault='/Frontend.EastBorder.style' ScrollExtent='21,678' Size='21,678' Stretch='false' Style=' '/>
<Image BackgroundOpacity='1.000' Location='24,45' Name='WestBorder' PackLocation='left,top' PackLocationProp='0024/0001,0045/0001' PackSize='fixed,absolute' PackSizeProp='0002/0003,0090/0001' RStyleDefault='/Frontend.WestBorder.style' ScrollExtent='21,678' Size='21,678' Stretch='false' Style=' '/>
<Image BackgroundOpacity='1.000' Location='80,722' Name='SouthBorder' PackLocation='left,bottom' PackLocationProp='0080/0001,-046/0001' PackSize='absolute,fixed' PackSizeProp='0160/0001,0002/0003' RStyleDefault='/Frontend.SouthBorder.style' ScrollExtent='864,22' Size='864,22' Stretch='false' Style=' '/>
<Image BackgroundOpacity='1.000' Location='55,24' Name='NorthBorder' PackLocation='left,top' PackLocationProp='0055/0001,0024/0001' PackSize='absolute,fixed' PackSizeProp='0230/0001,0002/0003' RStyleDefault='/Frontend.NorthBorder.style' ScrollExtent='794,22' Size='794,22' Stretch='false' Style=' '/>
<Image Name='Planet' ScrollExtent='1024,768' Size='1024,768' Stretch='false' Style='/Plates.PlanetBackground'/>
</Page>
</Page>
