<Page BackgroundOpacity='0.50' Name='Trade' runengine='True' ScrollExtent='800,600' Size='800,600' Visible='false' visualeditlock='true'>
<Image Location='620,470' ScrollExtent='20,20' Size='20,20' Style='/Icons.Credits'/>
<Text Font='/Fonts.DefaultFont' Location='58,470' Name='CreditsOffered' ScrollExtent='18,20' Size='80,20'>500</Text>
<Image Location='180,470' ScrollExtent='20,20' Size='20,20' Style='/Icons.Credits'/>
<Text Font='/Fonts.DefaultFont' Location='198,470' Name='PlayerCredits' ScrollExtent='36,20' Size='80,20'>15403</Text>
<Image Location='41,470' ScrollExtent='20,20' Size='20,20' Style='/Icons.Credits'/>
<Text Font='/Fonts.DefaultFont' Location='640,470' Name='CreditsReceived' ScrollExtent='12,20' Size='80,20'>0</Text>
<Button Location='180,50' Name='CompleteTrade' ScrollExtent='190,24' Size='257,24' Style='/Buttons.Medium.style'>Complete Trade</Button>
<Grid CellCount='4,6' CellSize='64,64' Location='180,80' Name='PlayerInventory' Opacity='0.60' ScrollExtent='449,194' Size='257,385' Style='/DefaultGrid.style'/>
<Grid CellCount='2,6' CellSize='64,64' Location='41,80' Name='ItemsOffered' Opacity='0.60' ScrollExtent='449,194' Size='129,385' Style='/DefaultGrid.style'/>
<Grid CellCount='2,6' CellSize='64,64' Location='620,80' Name='ItemsReceived' Opacity='0.60' ScrollExtent='449,194' Size='138,385' Style='/DefaultGrid.style'/>
<Button Location='41,50' Name='PlayerReady' ScrollExtent='190,24' Size='129,24' Style='/Buttons.Medium.style'>Ready</Button>
<Button Location='239,540' Name='Cancel' OnPress='ui_popstate' ScrollExtent='190,24' Size='138,24' Style='/Buttons.Medium.style'>Cancel</Button>
</Page>
