<Page movable='true' Name='VideoOptions' navbar.visible='false' PackLocation='Center,Center' PackLocationProp='-512/0001,-384/0001' ScrollExtent='800,600' Size='800,600' Visible='false'>
<Text AbsorbsInput='false' Enabled='false' Font='/Fonts.HudFont3' LocalText='[@OptionsTitle]' Location='91,7' Name='TitleText' ScrollExtent='607,20' Size='607,20' TextAlignment='Center' TextAlignmentVertical='Center'>@OptionsTitle</Text>
<Page Location='22,69' Name='SoundOptionsPage' OnHide='Parent.NavBar.Visible = false' OnShow='Parent.NavBar.Visible = true' PackLocation='Center,Center' PackLocationProp='-378/0001,-231/0001' ScrollExtent='758,468' Size='758,468' Visible='false'>
<Checkbox BackgroundOpacity='1.000' LocalTooltip='[@SoundAllTooltip]' Location='428,145' Name='SoundAll' ScrollExtent='307,25' Size='307,25' Style='/Buttons.OptionsCheckbox.style' Tooltip='@SoundAllTooltip'>@SoundAll</Checkbox>
<Text Font='/Fonts.HudFont3' LocalText='[@SoundTracks]' Location='100,145' Name='Tracks' ScrollExtent='505,25' Size='505,25' TextAlignment='Center' TextAlignmentVertical='Center'>@SoundTracks</Text>
<Checkbox Activated='true' BackgroundOpacity='1.000' Checked='true' LocalTooltip='[@SoundSanctuaryTooltip]' Location='100,180' Name='SoundSanctuary' ScrollExtent='307,25' Size='307,25' Style='/Buttons.OptionsCheckbox.style' Tooltip='@SoundSanctuaryTooltip'>@SoundSanctuary</Checkbox>
<Checkbox Activated='true' BackgroundOpacity='1.000' Checked='true' LocalTooltip='[@SoundShuttleTooltip]' Location='100,215' Name='SoundShuttle' ScrollExtent='307,25' Size='307,25' Style='/Buttons.OptionsCheckbox.style' Tooltip='@SoundShuttleTooltip'>@SoundShuttle</Checkbox>
<Checkbox Activated='true' BackgroundOpacity='1.000' Checked='true' LocalTooltip='[@SoundSOITooltip]' Location='100,250' Name='SoundSOI' ScrollExtent='307,25' Size='307,25' Style='/Buttons.OptionsCheckbox.style' Tooltip='@SoundSOITooltip'>@SoundSOI</Checkbox>
<Checkbox Activated='true' BackgroundOpacity='1.000' Checked='true' LocalTooltip='[@SoundSOIWarningTooltip]' Location='100,285' Name='SoundSOIWarning' ScrollExtent='307,25' Size='307,25' Style='/Buttons.OptionsCheckbox.style' Tooltip='@SoundSOIWarningTooltip'>@SoundSOIWarning</Checkbox>
<Checkbox Activated='true' BackgroundOpacity='1.000' Checked='true' LocalTooltip='[@SoundSOICombatTooltip]' Location='100,319' Name='SoundSOICombat' ScrollExtent='307,25' Size='307,25' Style='/Buttons.OptionsCheckbox.style' Tooltip='@SoundSOICombatTooltip'>@SoundSOICombat</Checkbox>
<Checkbox Activated='true' BackgroundOpacity='1.000' Checked='true' LocalTooltip='[@SoundVictoryTooltip]' Location='99,354' Name='SoundVictory' ScrollExtent='307,25' Size='307,25' Style='/Buttons.OptionsCheckbox.style' Tooltip='@SoundVictoryTooltip'>@SoundVictory</Checkbox>
<Checkbox Activated='true' BackgroundOpacity='1.000' Checked='true' LocalTooltip='[@SoundLossTooltip]' Location='100,389' Name='SoundLoss' ScrollExtent='307,25' Size='307,25' Style='/Buttons.OptionsCheckbox.style' Tooltip='@SoundLossTooltip'>@SoundLoss</Checkbox>
<Checkbox Activated='true' BackgroundOpacity='1.000' Checked='true' LocalTooltip='[@SoundPromotionTooltip]' Location='100,424' Name='SoundPromotion' ScrollExtent='307,25' Size='307,25' Style='/Buttons.OptionsCheckbox.style' Tooltip='@SoundPromotionTooltip'>@SoundPromotion</Checkbox>
<Checkbox Activated='true' BackgroundOpacity='1.000' Checked='true' LocalTooltip='[@SoundTemperateTooltip]' Location='428,180' Name='SoundTemperate' ScrollExtent='307,25' Size='307,25' Style='/Buttons.OptionsCheckbox.style' Tooltip='@SoundTemperateTooltip'>@SoundTemperate</Checkbox>
<Checkbox Activated='true' BackgroundOpacity='1.000' Checked='true' LocalTooltip='[@SoundDesertTooltip]' Location='428,215' Name='SoundDesert' ScrollExtent='307,25' Size='307,25' Style='/Buttons.OptionsCheckbox.style' Tooltip='@SoundDesertTooltip'>@SoundDesert</Checkbox>
<Checkbox Activated='true' BackgroundOpacity='1.000' Checked='true' LocalTooltip='[@SoundArcticTooltip]' Location='428,250' Name='SoundArctic' ScrollExtent='307,25' Size='307,25' Style='/Buttons.OptionsCheckbox.style' Tooltip='@SoundArcticTooltip'>@SoundArctic</Checkbox>
<Checkbox Activated='true' BackgroundOpacity='1.000' Checked='true' LocalTooltip='[@SoundVolcanicTooltip]' Location='428,285' Name='SoundVolcanic' ScrollExtent='307,25' Size='307,25' Style='/Buttons.OptionsCheckbox.style' Tooltip='@SoundVolcanicTooltip'>@SoundVolcanic</Checkbox>
<Checkbox Activated='true' BackgroundOpacity='1.000' Checked='true' LocalTooltip='[@SoundTemperateCombatTooltip]' Location='428,319' Name='SoundTemperateCombat' ScrollExtent='307,25' Size='307,25' Style='/Buttons.OptionsCheckbox.style' Tooltip='@SoundTemperateCombatTooltip'>@SoundTemperateCombat</Checkbox>
<Checkbox Activated='true' BackgroundOpacity='1.000' Checked='true' LocalTooltip='[@SoundDesertCombatTooltip]' Location='428,354' Name='SoundDesertCombat' ScrollExtent='307,25' Size='307,25' Style='/Buttons.OptionsCheckbox.style' Tooltip='@SoundDesertCombatTooltip'>@SoundDesertCombat</Checkbox>
<Checkbox Activated='true' BackgroundOpacity='1.000' Checked='true' LocalTooltip='[@SoundArcticCombatTooltip]' Location='428,389' Name='SoundArcticCombat' ScrollExtent='307,25' Size='307,25' Style='/Buttons.OptionsCheckbox.style' Tooltip='@SoundArcticCombatTooltip'>@SoundArcticCombat</Checkbox>
<Checkbox Activated='true' BackgroundOpacity='1.000' Checked='true' LocalTooltip='[@SoundVolcanicCombatTooltip]' Location='428,424' Name='SoundVolcanicCombat' ScrollExtent='307,25' Size='307,25' Style='/Buttons.OptionsCheckbox.style' Tooltip='@SoundVolcanicCombatTooltip'>@SoundVolcanicCombat</Checkbox>
<Text Font='/Fonts.HudFont3' LocalText='[@SoundVolume]' Location='10,59' Name='SoundVolume2dText' ScrollExtent='211,25' Size='211,25' TextAlignment='Right' TextAlignmentVertical='Center'>@SoundVolume</Text>
<Sliderbar LocalTooltip='[@SoundVolumeTooltip]' Location='232,63' Name='SoundVolume2d' ScrollExtent='126,25' Size='126,25' Style='/Sliderbars.Options.Style' Tooltip='@SoundVolumeTooltip' UpperLimit='100' Value='100' ValueUpdateContinuous='false'/>
<Text Font='/Fonts.HudFont3' LocalText='[@SoundVolume3d]' Location='10,92' Name='SoundVolume3dText' ScrollExtent='211,25' Size='211,25' TextAlignment='Right' TextAlignmentVertical='Center'>@SoundVolume3d</Text>
<Sliderbar LocalTooltip='[@SoundVolume3dTooltip]' Location='232,96' Name='SoundVolume3d' ScrollExtent='126,25' Size='126,25' Style='/Sliderbars.Options.Style' Tooltip='@SoundVolume3dTooltip' UpperLimit='100' ValueUpdateContinuous='false'/>
<Text Font='/Fonts.HudFont3' LocalText='[@MusicVolume]' Location='380,65' Name='SoundMusicText' ScrollExtent='211,25' Size='211,25' TextAlignment='Right' TextAlignmentVertical='Center'>@MusicVolume</Text>
<Sliderbar LocalTooltip='[@SoundMusicTooltip]' Location='604,68' Name='SoundMusic' ScrollExtent='126,25' Size='126,25' Style='/Sliderbars.Options.Style' Tooltip='@SoundMusicTooltip' UpperLimit='100' Value='25' ValueUpdateContinuous='false'/>
<Template Name='Row Template' Size='400,20'>\<text font = \'/Fonts.HUDFont2\' location = \'5,3\' size = \'400,20\'\>
$Name$
\</text\></Template>
<Text Font='/Fonts.HudFont3' LocalText='[@SoundMode]' Location='59,20' Name='SoundModeText' ScrollExtent='162,25' Size='162,25' TextAlignment='Right' TextAlignmentVertical='Center'>@SoundMode</Text>
<Dropdownbox BackgroundColor='#FFFFFF' BackgroundOpacity='0.659' BackgroundTint='#000000' DataSource='/DataSources.SoundOptionsDataSource' LocalTooltip='[@SoundModeTooltip]' Location='233,21' Name='SoundMode' RowTemplate='Row Template' ScrollExtent='400,32' SelectedItemIndex='3' Size='400,32' Style='/Dropdowns.HudPane.style' Tooltip='@SoundModeTooltip'/>
<Checkbox BackgroundOpacity='1.000' LocalTooltip='[@SoundReverseStereoTooltip]' Location='248,133' Name='ReverseStereo' ScrollExtent='291,25' Size='291,25' Style='/Buttons.OptionsCheckbox.style' Tooltip='@SoundReverseStereoTooltip' Visible='false'>@SoundReverseStereo</Checkbox>
</Page>
<Page ContextCapable='true' ContextToParent='true' Location='22,69' Name='KeymapOptionsPage' OnHide='Parent.NavBar.Visible = false' OnShow='Parent.NavBar.Visible = true' PackLocation='Center,Center' PackLocationProp='-378/0001,-231/0001' ScrollExtent='758,468' Size='758,468' Visible='false'>
<Image BackgroundOpacity='1.000' Location='7,41' Name='DescriptionBorder' PackLocation='left,bottom' PackLocationProp='0007/0001,-427/0001' PackSize='absolute,fixed' PackSizeProp='0350/0001,0002/0003' RStyleDefault='/WindowPanes.ButtonBorder.style' ScrollExtent='408,58' Size='408,58'/>
<Textbox BackgroundColor='#DDDDDD' BackgroundOpacity='0.475' LocalTooltip='[@OptionsNameTooltip]' Location='696,479' MaxLength='15' Name='CaptureInput' PackLocation='right,bottom' PackLocationProp='-062/0001,0011/0001' PackSize='fixed,fixed' PackSizeProp='0002/0003,0002/0003' ScrollExtent='52,20' Size='52,20' Style='/ConsoleTextbox.ShortStyle' Tooltip='@OptionsNameTooltip'></Textbox>
<Text Font='/Fonts.HudFont1' LocalText='[@KeymapCommandTitle]' Location='13,94' Name='CommandTitle' ScrollExtent='141,25' Size='141,25' TextAlignment='Center' TextAlignmentVertical='Center'>@KeymapCommandTitle</Text>
<Text Font='/Fonts.HudFont1' LocalText='[@KeymapList1Title]' Location='159,94' Name='List1Title' ScrollExtent='121,25' Size='121,25' TextAlignment='Center' TextAlignmentVertical='Center'>@KeymapList1Title</Text>
<Text Font='/Fonts.HudFont1' LocalText='[@KeymapList2Title]' Location='282,94' Name='List2Title' ScrollExtent='119,25' Size='119,25' TextAlignment='Center' TextAlignmentVertical='Center'>@KeymapList2Title</Text>
<Template Name='CommandListTemplate' Size='145,25'>\<text font = \'/Fonts.HUDFont2\' location = \'5,0\' size = \'145,25\' textalignment = \'left\' textalignmentvertical = \'center\'\>
$actionname$
\</text\></Template>
<Template Name='KeyList2Template' Size='119,25'>\<text font = \'/Fonts.HUDFont2\' location = \'0,2\' size = \'120,23\' textalignment = \'center\' textalignmentvertical = \'center\' textcolor = \'$color2$\'\>
$key2$
\</text\></Template>
<Template Name='KeyList1Template' Size='119,25'>\<text font = \'/Fonts.HUDFont2\' location = \'0,2\' size = \'120,23\' textalignment = \'center\' textalignmentvertical = \'center\' textcolor = \'$color1$\'\>
$key1$
\</text\></Template>
<Text Color='#CCCCCC' Font='/Fonts.HudFont1' LocalText='Status' Location='594,434' Name='StatusMessage' ScrollExtent='147,25' Size='147,25' TextAlignmentVertical='Center'>Status</Text>
<Button LocalText='[@KeymapChangeBinding]' LocalTooltip='[@KeymapChangeBindingTooltip]' Location='431,434' Name='ChangeBinding' ScrollExtent='75,20' Size='75,20' Style='/Buttons.TextButton.style' Tooltip='@KeymapChangeBindingTooltip'>@KeymapChangeBinding</Button>
<Button LocalText='[@KeymapDeleteBinding]' LocalTooltip='[@KeymapDeleteBindingTooltip]' Location='512,434' Name='DeleteBinding' ScrollExtent='75,20' Size='75,20' Style='/Buttons.TextButton.style' Tooltip='@KeymapDeleteBindingTooltip'>@KeymapDeleteBinding</Button>
<Image BackgroundOpacity='1.000' Location='424,429' Name='StatusBorder' PackLocation='left,bottom' PackLocationProp='0424/0001,-039/0001' PackSize='absolute,fixed' PackSizeProp='0440/0001,0002/0003' RStyleDefault='/WindowPanes.ButtonBorder.style' ScrollExtent='318,31' Size='318,31'/>
<Checkbox Activated='true' BackgroundColor='#FFFFFF' BackgroundOpacity='1.000' Checked='true' Cursor='s' LocalTooltip='[@OptionKeyboardTooltip]' Location='422,42' Name='KeyboardCheckbox' ScrollExtent='64,64' Size='64,64' Style='/Buttons.OptionKeyboard.checkstyle' Tooltip='@OptionKeyboardTooltip'></Checkbox>
<Checkbox BackgroundColor='#FFFFFF' BackgroundOpacity='1.000' Cursor='s' LocalTooltip='[@OptionMouseTooltip]' Location='485,42' Name='MouseCheckbox' ScrollExtent='64,64' Size='64,64' Style='/Buttons.OptionMouse.checkstyle' Tooltip='@OptionMouseTooltip'></Checkbox>
<Checkbox BackgroundColor='#FFFFFF' BackgroundOpacity='1.000' Cursor='s' LocalTooltip='[@OptionJoystickTooltip]' Location='548,42' Name='Joy1Checkbox' ScrollExtent='64,64' Size='64,64' Style='/Buttons.OptionJoystick.checkstyle' Tooltip='@OptionJoystickTooltip'></Checkbox>
<Checkbox BackgroundColor='#FFFFFF' BackgroundOpacity='1.000' Cursor='s' Enabled='false' LocalTooltip='[@OptionJoystickTooltip]' Location='615,42' Name='Joy2Checkbox' ScrollExtent='64,64' Size='64,64' Style='/Buttons.OptionJoystick.checkstyle' Tooltip='@OptionJoystickTooltip'></Checkbox>
<Checkbox BackgroundColor='#FFFFFF' BackgroundOpacity='1.000' Cursor='s' Enabled='false' LocalTooltip='[@OptionJoystickTooltip]' Location='682,42' Name='Joy3Checkbox' ScrollExtent='64,64' Size='64,64' Style='/Buttons.OptionJoystick.checkstyle' Tooltip='@OptionJoystickTooltip'></Checkbox>
<Page Location='426,113' Name='MousePage' ScrollExtent='315,314' Size='315,314' Visible='false'>
<Text Font='/SmallFont' LocalText='[@MouseSensitivity]' LocalTooltip='[@MouseSensitivityTooltip]' Location='6,32' Name='MouseSensitivityText' ScrollExtent='125,20' Size='125,20' TextAlignment='Right' Tooltip='@MouseSensitivityTooltip'>@MouseSensitivity</Text>
<Sliderbar LocalTooltip='[@MouseSensitivityTooltip]' Location='138,23' Name='MouseSensitivitySlider' ScrollExtent='174,30' Size='174,30' Style='/Sliderbars.Options.Style' Tooltip='@MouseSensitivityTooltip' UpperLimit='1000' Value='571'/>
<Text Font='/SmallFont' LocalText='[@MouseSteerSensitivity]' LocalTooltip='[@MouseSteerSensitivityTooltip]' Location='6,68' Name='MouseSteerSensitivityText' ScrollExtent='125,20' Size='125,20' TextAlignment='Right' Tooltip='@MouseSteerSensitivityTooltip'>@MouseSteerSensitivity</Text>
<Sliderbar LocalTooltip='[@MouseSteerSensitivityTooltip]' Location='138,57' Name='MouseSteerSensitivitySlider' ScrollExtent='174,30' Size='174,30' Style='/Sliderbars.Options.Style' Tooltip='@MouseSteerSensitivityTooltip' UpperLimit='1000' Value='744'/>
<Text Font='/SmallFont' LocalText='[@MouseAutoCenter]' LocalTooltip='[@MouseAutoCenterTooltip]' Location='6,99' Name='MouseAuoCenterText' ScrollExtent='125,20' Size='125,20' TextAlignment='Right' Tooltip='@MouseAutoCenterTooltip'>@MouseAutoCenter</Text>
<Sliderbar LocalTooltip='[@MouseAutoCenterTooltip]' Location='138,89' Name='MouseAutoCenterSlider' ScrollExtent='174,30' Size='174,30' Style='/Sliderbars.Options.Style' Tooltip='@MouseAutoCenterTooltip' UpperLimit='1000' Value='744'/>
<Checkbox Activated='true' BackgroundOpacity='1.000' Checked='true' LocalTooltip='[@SmoothMouseTooltip]' Location='0,128' Name='SmoothingCheck' ScrollExtent='158,25' Size='158,25' Style='/Buttons.OptionsCheckbox.style' Tooltip='@SmoothMouseTooltip'>@SmoothMouse</Checkbox>
<Checkbox Activated='true' BackgroundOpacity='1.000' Checked='true' LocalTooltip='[@InvertMouseTooltip]' Location='160,128' Name='InvertMouseCheck' ScrollExtent='157,25' Size='157,25' Style='/Buttons.OptionsCheckbox.style' Tooltip='@InvertMouseTooltip'>@InvertMouse</Checkbox>
<Checkbox Activated='true' BackgroundOpacity='1.000' Checked='true' LocalTooltip='[@MouseSteerTooltip]' Location='0,158' Name='SteerCheck' ScrollExtent='159,25' Size='159,25' Style='/Buttons.OptionsCheckbox.style' Tooltip='@MouseSteerTooltip'>@MouseSteer</Checkbox>
<Checkbox Activated='true' BackgroundOpacity='1.000' Checked='true' LocalTooltip='[@MouseFreelookTooltip]' Location='160,158' Name='FreelookCheck' ScrollExtent='154,25' Size='154,25' Style='/Buttons.OptionsCheckbox.style' Tooltip='@MouseFreelookTooltip'>@MouseFreelook</Checkbox>
<Checkbox Activated='true' BackgroundOpacity='1.000' Checked='true' LocalTooltip='[@MouseReversePilotTooltip]' Location='0,188' Name='ReversePilotCheck' ScrollExtent='206,25' Size='206,25' Style='/Buttons.OptionsCheckbox.style' Tooltip='@MouseReversePilotTooltip'>@MouseReversePilot</Checkbox>
<Text Font='/Fonts.HudFont3' LocalText='[@Mouse]' Location='11,5' Name='Name' ScrollExtent='196,20' Size='196,20'>@Mouse</Text>
<Text AbsorbsInput='false' Enabled='false' Font='/Fonts.HudFont1' LocalText='MOUSE 1' Location='0,227' Name='M1Text' ScrollExtent='74,20' Size='74,20' TextAlignment='Center' TextAlignmentVertical='Center'>MOUSE 1</Text>
<Checkbox BackgroundOpacity='1.000' Location='0,227' Name='M1' ScrollExtent='75,22' Size='75,22' Style='/Buttons.KeymapButton.joystyle' value='Left Mouse Button'></Checkbox>
<Text AbsorbsInput='false' Enabled='false' Font='/Fonts.HudFont1' LocalText='MOUSE 2' Location='79,228' Name='M2Text' ScrollExtent='74,20' Size='74,20' TextAlignment='Center' TextAlignmentVertical='Center'>MOUSE 2</Text>
<Checkbox BackgroundOpacity='1.000' Location='77,228' Name='M2' ScrollExtent='75,22' Size='75,22' Style='/Buttons.KeymapButton.joystyle' value='Mouse Button 2'></Checkbox>
<Text AbsorbsInput='false' Enabled='false' Font='/Fonts.HudFont1' LocalText='MOUSE 3' Location='156,229' Name='M3Text' ScrollExtent='74,20' Size='74,20' TextAlignment='Center' TextAlignmentVertical='Center'>MOUSE 3</Text>
<Checkbox BackgroundOpacity='1.000' Location='154,228' Name='M3' ScrollExtent='75,22' Size='75,22' Style='/Buttons.KeymapButton.joystyle' value='Mouse Button 3'></Checkbox>
<Text AbsorbsInput='false' Enabled='false' Font='/Fonts.HudFont1' LocalText='MOUSE 4' Location='233,229' Name='M4Text' ScrollExtent='74,20' Size='74,20' TextAlignment='Center' TextAlignmentVertical='Center'>MOUSE 4</Text>
<Checkbox BackgroundOpacity='1.000' Location='231,228' Name='M4' ScrollExtent='75,22' Size='75,22' Style='/Buttons.KeymapButton.joystyle' value='Mouse Button 4'></Checkbox>
<Text AbsorbsInput='false' Enabled='false' Font='/Fonts.HudFont1' LocalText='MOUSE 5' Location='1,255' Name='M5Text' ScrollExtent='74,20' Size='74,20' TextAlignment='Center' TextAlignmentVertical='Center'>MOUSE 5</Text>
<Checkbox BackgroundOpacity='1.000' Location='1,255' Name='M5' ScrollExtent='75,22' Size='75,22' Style='/Buttons.KeymapButton.joystyle' value='Mouse Button 5'></Checkbox>
<Text AbsorbsInput='false' Enabled='false' Font='/Fonts.HudFont1' LocalText='MOUSE 6' Location='78,255' Name='M6Text' ScrollExtent='74,20' Size='74,20' TextAlignment='Center' TextAlignmentVertical='Center'>MOUSE 6</Text>
<Checkbox BackgroundOpacity='1.000' Location='78,255' Name='M6' ScrollExtent='75,22' Size='75,22' Style='/Buttons.KeymapButton.joystyle' value='Mouse Button 6'></Checkbox>
<Text AbsorbsInput='false' Enabled='false' Font='/Fonts.HudFont1' LocalText='MOUSE 7' Location='157,256' Name='M7Text' ScrollExtent='74,20' Size='74,20' TextAlignment='Center' TextAlignmentVertical='Center'>MOUSE 7</Text>
<Checkbox BackgroundOpacity='1.000' Location='155,256' Name='M7' ScrollExtent='75,22' Size='75,22' Style='/Buttons.KeymapButton.joystyle' value='Mouse Button 7'></Checkbox>
<Text AbsorbsInput='false' Enabled='false' Font='/Fonts.HudFont1' LocalText='MOUSE 8' Location='234,256' Name='M8Text' ScrollExtent='74,20' Size='74,20' TextAlignment='Center' TextAlignmentVertical='Center'>MOUSE 8</Text>
<Checkbox BackgroundOpacity='1.000' Location='232,256' Name='M8' ScrollExtent='75,22' Size='75,22' Style='/Buttons.KeymapButton.joystyle' value='Mouse Button 8'></Checkbox>
<Text AbsorbsInput='false' Enabled='false' Font='/Fonts.HudFont1' LocalText='WHEEL DN' Location='3,283' Name='MDownText' ScrollExtent='74,20' Size='74,20' TextAlignment='Center' TextAlignmentVertical='Center'>WHEEL DN</Text>
<Checkbox BackgroundOpacity='1.000' Location='1,282' Name='MDown' ScrollExtent='75,22' Size='75,22' Style='/Buttons.KeymapButton.joystyle' value='Mouse Wheel Down'></Checkbox>
<Text AbsorbsInput='false' Enabled='false' Font='/Fonts.HudFont1' LocalText='WHEEL UP' Location='79,282' Name='MUpText' ScrollExtent='74,20' Size='74,20' TextAlignment='Center' TextAlignmentVertical='Center'>WHEEL UP</Text>
<Checkbox BackgroundOpacity='1.000' Location='79,282' Name='MUp' ScrollExtent='75,22' Size='75,22' Style='/Buttons.KeymapButton.joystyle' value='Mouse Wheel Up'></Checkbox>
</Page>
<Page Location='422,107' Name='KeyboardPage' ScrollExtent='325,319' Size='325,319'>
<Page Location='134,-2' Name='Mode' ScrollExtent='184,36' Size='184,36' UserMovable='true' UserResizable='true'>
<Text Font='/Fonts.HudFont1' LocalText='[@KeyboardModifier]' Location='-3,1' Name='Modifier' ScrollExtent='196,15' Size='196,15' TextAlignment='Center'>@KeyboardModifier</Text>
<Text AbsorbsInput='false' Enabled='false' Font='/Fonts.HudFont1' LocalText='SHIFT' Location='0,16' Name='J1Text' ScrollExtent='60,15' Size='60,15' TextAlignment='Center' TextAlignmentVertical='Center'>SHIFT</Text>
<Checkbox BackgroundOpacity='1.000' LocalTooltip='[@KeyboardShift]' Location='0,16' Name='Shift' ScrollExtent='60,15' Size='60,15' Style='/Buttons.KeymapButton.joystyle' Tooltip='@KeyboardShift' TooltipStyle='/Tooltips.Default' value='Left Shift'></Checkbox>
<Text AbsorbsInput='false' Enabled='false' Font='/Fonts.HudFont1' LocalText='CTRL' Location='64,16' Name='J8Text' ScrollExtent='60,15' Size='60,15' TextAlignment='Center' TextAlignmentVertical='Center'>CTRL</Text>
<Checkbox BackgroundOpacity='1.000' LocalTooltip='[@KeyboardCtrl]' Location='62,16' Name='Ctrl' ScrollExtent='60,15' Size='60,15' Style='/Buttons.KeymapButton.joystyle' Tooltip='@KeyboardCtrl' TooltipStyle='/Tooltips.Default' value='Left Ctrl'></Checkbox>
<Text AbsorbsInput='false' Enabled='false' Font='/Fonts.HudFont1' LocalText='ALT' Location='127,17' Name='J10Text' ScrollExtent='60,15' Size='60,15' TextAlignment='Center' TextAlignmentVertical='Center'>ALT</Text>
<Checkbox BackgroundOpacity='1.000' LocalTooltip='[@KeyboardAlt]' Location='125,16' Name='Alt' ScrollExtent='60,15' Size='60,15' Style='/Buttons.KeymapButton.joystyle' Tooltip='@KeyboardAlt' TooltipStyle='/Tooltips.Default' value='Left Alt'></Checkbox>
</Page>
<Text Font='/Fonts.HudFont3' LocalText='[@Keyboard]' Location='11,5' Name='Name' ScrollExtent='196,20' Size='196,20'>@Keyboard</Text>
<Page Location='12,38' Name='Row1' ScrollExtent='300,28' Size='300,28'>
<Text AbsorbsInput='false' Enabled='false' Font='/Fonts.HudFont1' LocalText='F1' Location='0,3' Name='K1Text' ScrollExtent='20,20' Size='20,20' TextAlignment='Center' TextAlignmentVertical='Center'>F1</Text>
<Checkbox Activated='true' BackgroundOpacity='1.000' Checked='true' Location='0,3' Name='K1' Opacity='0.800' ScrollExtent='20,20' Size='20,20' Style='/Buttons.KeymapButton.keystyle' TooltipStyle='/Tooltips.Default' value='F1'></Checkbox>
<Text AbsorbsInput='false' Enabled='false' Font='/Fonts.HudFont1' LocalText='F2' Location='25,3' Name='K1Text' ScrollExtent='20,20' Size='20,20' TextAlignment='Center' TextAlignmentVertical='Center'>F2</Text>
<Checkbox BackgroundOpacity='1.000' Location='25,3' Name='K2' ScrollExtent='20,20' Size='20,20' Style='/Buttons.KeymapButton.keystyle' TooltipStyle='/Tooltips.Default' value='F2'></Checkbox>
<Text AbsorbsInput='false' Enabled='false' Font='/Fonts.HudFont1' LocalText='F3' Location='50,3' Name='K1Text' ScrollExtent='20,20' Size='20,20' TextAlignment='Center' TextAlignmentVertical='Center'>F3</Text>
<Checkbox Activated='true' BackgroundOpacity='1.000' Checked='true' Location='50,3' Name='K3' Opacity='0.750' ScrollExtent='20,20' Size='20,20' Style='/Buttons.KeymapButton.keystyle' TooltipStyle='/Tooltips.Default' value='F3'></Checkbox>
<Text AbsorbsInput='false' Enabled='false' Font='/Fonts.HudFont1' LocalText='F4' Location='75,3' Name='K1Text' ScrollExtent='20,20' Size='20,20' TextAlignment='Center' TextAlignmentVertical='Center'>F4</Text>
<Checkbox BackgroundOpacity='1.000' Location='75,3' Name='K4' ScrollExtent='20,20' Size='20,20' Style='/Buttons.KeymapButton.keystyle' TooltipStyle='/Tooltips.Default' value='F4'></Checkbox>
<Text AbsorbsInput='false' Enabled='false' Font='/Fonts.HudFont1' LocalText='F5' Location='100,3' Name='K1Text' ScrollExtent='20,20' Size='20,20' TextAlignment='Center' TextAlignmentVertical='Center'>F5</Text>
<Checkbox BackgroundOpacity='1.000' Location='100,3' Name='K5' ScrollExtent='20,20' Size='20,20' Style='/Buttons.KeymapButton.keystyle' TooltipStyle='/Tooltips.Default' value='F5'></Checkbox>
<Text AbsorbsInput='false' Enabled='false' Font='/Fonts.HudFont1' LocalText='F6' Location='125,3' Name='K1Text' ScrollExtent='20,20' Size='20,20' TextAlignment='Center' TextAlignmentVertical='Center'>F6</Text>
<Checkbox BackgroundOpacity='1.000' Location='125,3' Name='K6' ScrollExtent='20,20' Size='20,20' Style='/Buttons.KeymapButton.keystyle' TooltipStyle='/Tooltips.Default' value='F6'></Checkbox>
<Text AbsorbsInput='false' Enabled='false' Font='/Fonts.HudFont1' LocalText='F7' Location='150,3' Name='K1Text' ScrollExtent='20,20' Size='20,20' TextAlignment='Center' TextAlignmentVertical='Center'>F7</Text>
<Checkbox BackgroundOpacity='1.000' Location='150,3' Name='K7' ScrollExtent='20,20' Size='20,20' Style='/Buttons.KeymapButton.keystyle' TooltipStyle='/Tooltips.Default' value='F7'></Checkbox>
<Text AbsorbsInput='false' Enabled='false' Font='/Fonts.HudFont1' LocalText='F8' Location='175,3' Name='K1Text' ScrollExtent='20,20' Size='20,20' TextAlignment='Center' TextAlignmentVertical='Center'>F8</Text>
<Checkbox BackgroundOpacity='1.000' Location='175,3' Name='K8' ScrollExtent='20,20' Size='20,20' Style='/Buttons.KeymapButton.keystyle' TooltipStyle='/Tooltips.Default' value='F8'></Checkbox>
<Text AbsorbsInput='false' Enabled='false' Font='/Fonts.HudFont1' LocalText='F9' Location='200,3' Name='K1Text' ScrollExtent='20,20' Size='20,20' TextAlignment='Center' TextAlignmentVertical='Center'>F9</Text>
<Checkbox BackgroundOpacity='1.000' Location='200,3' Name='K9' ScrollExtent='20,20' Size='20,20' Style='/Buttons.KeymapButton.keystyle' TooltipStyle='/Tooltips.Default' value='F9'></Checkbox>
<Text AbsorbsInput='false' Enabled='false' Font='/Fonts.HudFont1' LocalText='F10' Location='225,3' Name='K1Text' ScrollExtent='20,20' Size='20,20' TextAlignment='Center' TextAlignmentVertical='Center'>F10</Text>
<Checkbox BackgroundOpacity='1.000' Location='225,3' Name='K10' ScrollExtent='20,20' Size='20,20' Style='/Buttons.KeymapButton.keystyle' TooltipStyle='/Tooltips.Default' value='F10'></Checkbox>
<Text AbsorbsInput='false' Enabled='false' Font='/Fonts.HudFont1' LocalText='F11' Location='250,3' Name='K1Text' ScrollExtent='20,20' Size='20,20' TextAlignment='Center' TextAlignmentVertical='Center'>F11</Text>
<Checkbox BackgroundOpacity='1.000' Location='250,3' Name='K11' ScrollExtent='20,20' Size='20,20' Style='/Buttons.KeymapButton.keystyle' TooltipStyle='/Tooltips.Default' value='F11'></Checkbox>
<Text AbsorbsInput='false' Enabled='false' Font='/Fonts.HudFont1' LocalText='F12' Location='275,3' Name='K1Text' ScrollExtent='20,20' Size='20,20' TextAlignment='Center' TextAlignmentVertical='Center'>F12</Text>
<Checkbox BackgroundOpacity='1.000' Location='275,3' Name='K12' ScrollExtent='20,20' Size='20,20' Style='/Buttons.KeymapButton.keystyle' TooltipStyle='/Tooltips.Default' value='F12'></Checkbox>
</Page>
<Page Location='12,149' Name='Row2' ScrollExtent='300,50' Size='300,50'>
<Text AbsorbsInput='false' Enabled='false' Font='/Fonts.HudFont1' LocalText='DEL' Location='0,3' Name='K1Text' ScrollExtent='43,20' Size='43,20' TextAlignment='Center' TextAlignmentVertical='Center'>DEL</Text>
<Checkbox BackgroundOpacity='1.000' Location='0,3' Name='K1' ScrollExtent='43,20' Size='43,20' Style='/Buttons.KeymapButton.keystyle' TooltipStyle='/Tooltips.Default' value='Delete'></Checkbox>
<Text AbsorbsInput='false' Enabled='false' Font='/Fonts.HudFont1' LocalText='END' Location='50,3' Name='K1Text' ScrollExtent='43,20' Size='43,20' TextAlignment='Center' TextAlignmentVertical='Center'>END</Text>
<Checkbox BackgroundOpacity='1.000' Location='50,3' Name='K2' ScrollExtent='43,20' Size='43,20' Style='/Buttons.KeymapButton.keystyle' TooltipStyle='/Tooltips.Default' value='End'></Checkbox>
<Text AbsorbsInput='false' Enabled='false' Font='/Fonts.HudFont1' LocalText='HOME' Location='100,3' Name='K1Text' ScrollExtent='43,20' Size='43,20' TextAlignment='Center' TextAlignmentVertical='Center'>HOME</Text>
<Checkbox BackgroundOpacity='1.000' Location='100,3' Name='K3' ScrollExtent='43,20' Size='43,20' Style='/Buttons.KeymapButton.keystyle' TooltipStyle='/Tooltips.Default' value='Home'></Checkbox>
<Text AbsorbsInput='false' Enabled='false' Font='/Fonts.HudFont1' LocalText='INS' Location='150,3' Name='K1Text' ScrollExtent='43,20' Size='43,20' TextAlignment='Center' TextAlignmentVertical='Center'>INS</Text>
<Checkbox BackgroundOpacity='1.000' Location='150,3' Name='K4' ScrollExtent='43,20' Size='43,20' Style='/Buttons.KeymapButton.keystyle' TooltipStyle='/Tooltips.Default' value='Insert'></Checkbox>
<Text AbsorbsInput='false' Enabled='false' Font='/Fonts.HudFont1' LocalText='PGDN' Location='200,3' Name='K1Text' ScrollExtent='43,20' Size='43,20' TextAlignment='Center' TextAlignmentVertical='Center'>PGDN</Text>
<Checkbox BackgroundOpacity='1.000' Location='200,3' Name='K5' Opacity='0.600' ScrollExtent='43,20' Size='43,20' Style='/Buttons.KeymapButton.keystyle' TooltipStyle='/Tooltips.Default' value='Page Down'></Checkbox>
<Text AbsorbsInput='false' Enabled='false' Font='/Fonts.HudFont1' LocalText='PGUP' Location='250,3' Name='K1Text' ScrollExtent='43,20' Size='43,20' TextAlignment='Center' TextAlignmentVertical='Center'>PGUP</Text>
<Checkbox BackgroundOpacity='1.000' Location='250,3' Name='K6' ScrollExtent='43,20' Size='43,20' Style='/Buttons.KeymapButton.keystyle' TooltipStyle='/Tooltips.Default' value='Page Up'></Checkbox>
<Text AbsorbsInput='false' Enabled='false' Font='/Fonts.HudFont1' LocalText='UP' Location='0,25' Name='K1Text' ScrollExtent='43,20' Size='43,20' TextAlignment='Center' TextAlignmentVertical='Center'>UP</Text>
<Checkbox BackgroundOpacity='1.000' Location='0,25' Name='K7' ScrollExtent='43,20' Size='43,20' Style='/Buttons.KeymapButton.keystyle' TooltipStyle='/Tooltips.Default' value='Up Arrow'></Checkbox>
<Text AbsorbsInput='false' Enabled='false' Font='/Fonts.HudFont1' LocalText='DOWN' Location='50,25' Name='K1Text' ScrollExtent='43,20' Size='43,20' TextAlignment='Center' TextAlignmentVertical='Center'>DOWN</Text>
<Checkbox BackgroundOpacity='1.000' Location='50,25' Name='K8' ScrollExtent='43,20' Size='43,20' Style='/Buttons.KeymapButton.keystyle' TooltipStyle='/Tooltips.Default' value='Down Arrow'></Checkbox>
<Text AbsorbsInput='false' Enabled='false' Font='/Fonts.HudFont1' LocalText='LEFT' Location='100,25' Name='K1Text' ScrollExtent='43,20' Size='43,20' TextAlignment='Center' TextAlignmentVertical='Center'>LEFT</Text>
<Checkbox BackgroundOpacity='1.000' Location='100,25' Name='K9' ScrollExtent='43,20' Size='43,20' Style='/Buttons.KeymapButton.keystyle' TooltipStyle='/Tooltips.Default' value='Left Arrow'></Checkbox>
<Text AbsorbsInput='false' Enabled='false' Font='/Fonts.HudFont1' LocalText='RIGHT' Location='150,25' Name='K1Text' ScrollExtent='43,20' Size='43,20' TextAlignment='Center' TextAlignmentVertical='Center'>RIGHT</Text>
<Checkbox BackgroundOpacity='1.000' Location='150,25' Name='K10' ScrollExtent='43,20' Size='43,20' Style='/Buttons.KeymapButton.keystyle' TooltipStyle='/Tooltips.Default' value='Right Arrow'></Checkbox>
<Text AbsorbsInput='false' Enabled='false' Font='/Fonts.HudFont1' LocalText='TAB' Location='199,25' Name='K1Text' ScrollExtent='43,20' Size='43,20' TextAlignment='Center' TextAlignmentVertical='Center'>TAB</Text>
<Checkbox BackgroundOpacity='1.000' Location='199,25' Name='K11' ScrollExtent='45,20' Size='45,20' Style='/Buttons.KeymapButton.keystyle' TooltipStyle='/Tooltips.Default' value='Tab'></Checkbox>
<Text AbsorbsInput='false' Enabled='false' Font='/Fonts.HudFont1' LocalText='SPACE' Location='251,25' Name='K12Text' ScrollExtent='43,20' Size='43,20' TextAlignment='Center' TextAlignmentVertical='Center'>SPACE</Text>
<Checkbox BackgroundOpacity='1.000' Location='249,25' Name='K12' ScrollExtent='45,20' Size='45,20' Style='/Buttons.KeymapButton.keystyle' TooltipStyle='/Tooltips.Default' value='Space'></Checkbox>
</Page>
<Page Location='12,60' Name='Row3' ScrollExtent='300,28' Size='300,28'>
<Text AbsorbsInput='false' Enabled='false' Font='/Fonts.HudFont1' LocalText='A' Location='0,3' Name='K1Text' ScrollExtent='20,20' Size='20,20' TextAlignment='Center' TextAlignmentVertical='Center'>A</Text>
<Checkbox BackgroundOpacity='1.000' Location='0,3' Name='K1' ScrollExtent='20,20' Size='20,20' Style='/Buttons.KeymapButton.keystyle' TooltipStyle='/Tooltips.Default' value='A'></Checkbox>
<Text AbsorbsInput='false' Enabled='false' Font='/Fonts.HudFont1' LocalText='B' Location='25,3' Name='K1Text' ScrollExtent='20,20' Size='20,20' TextAlignment='Center' TextAlignmentVertical='Center'>B</Text>
<Checkbox BackgroundOpacity='1.000' Location='25,3' Name='K2' ScrollExtent='20,20' Size='20,20' Style='/Buttons.KeymapButton.keystyle' TooltipStyle='/Tooltips.Default' value='B'></Checkbox>
<Text AbsorbsInput='false' Enabled='false' Font='/Fonts.HudFont1' LocalText='C' Location='50,3' Name='K1Text' ScrollExtent='20,20' Size='20,20' TextAlignment='Center' TextAlignmentVertical='Center'>C</Text>
<Checkbox BackgroundOpacity='1.000' Location='50,3' Name='K3' ScrollExtent='20,20' Size='20,20' Style='/Buttons.KeymapButton.keystyle' TooltipStyle='/Tooltips.Default' value='C'></Checkbox>
<Text AbsorbsInput='false' Enabled='false' Font='/Fonts.HudFont1' LocalText='D' Location='75,3' Name='K1Text' ScrollExtent='20,20' Size='20,20' TextAlignment='Center' TextAlignmentVertical='Center'>D</Text>
<Checkbox BackgroundOpacity='1.000' Location='75,3' Name='K4' ScrollExtent='20,20' Size='20,20' Style='/Buttons.KeymapButton.keystyle' TooltipStyle='/Tooltips.Default' value='D'></Checkbox>
<Text AbsorbsInput='false' Enabled='false' Font='/Fonts.HudFont1' LocalText='E' Location='100,3' Name='K1Text' ScrollExtent='20,20' Size='20,20' TextAlignment='Center' TextAlignmentVertical='Center'>E</Text>
<Checkbox BackgroundOpacity='1.000' Location='100,3' Name='K5' ScrollExtent='20,20' Size='20,20' Style='/Buttons.KeymapButton.keystyle' TooltipStyle='/Tooltips.Default' value='E'></Checkbox>
<Text AbsorbsInput='false' Enabled='false' Font='/Fonts.HudFont1' LocalText='F' Location='125,3' Name='K1Text' ScrollExtent='20,20' Size='20,20' TextAlignment='Center' TextAlignmentVertical='Center'>F</Text>
<Checkbox BackgroundOpacity='1.000' Location='125,3' Name='K6' ScrollExtent='20,20' Size='20,20' Style='/Buttons.KeymapButton.keystyle' TooltipStyle='/Tooltips.Default' value='F'></Checkbox>
<Text AbsorbsInput='false' Enabled='false' Font='/Fonts.HudFont1' LocalText='G' Location='150,3' Name='K1Text' ScrollExtent='20,20' Size='20,20' TextAlignment='Center' TextAlignmentVertical='Center'>G</Text>
<Checkbox BackgroundOpacity='1.000' Location='150,3' Name='K7' ScrollExtent='20,20' Size='20,20' Style='/Buttons.KeymapButton.keystyle' TooltipStyle='/Tooltips.Default' value='G'></Checkbox>
<Text AbsorbsInput='false' Enabled='false' Font='/Fonts.HudFont1' LocalText='H' Location='175,3' Name='K1Text' ScrollExtent='20,20' Size='20,20' TextAlignment='Center' TextAlignmentVertical='Center'>H</Text>
<Checkbox BackgroundOpacity='1.000' Location='175,3' Name='K8' ScrollExtent='20,20' Size='20,20' Style='/Buttons.KeymapButton.keystyle' TooltipStyle='/Tooltips.Default' value='H'></Checkbox>
<Text AbsorbsInput='false' Enabled='false' Font='/Fonts.HudFont1' LocalText='I' Location='200,3' Name='K1Text' ScrollExtent='20,20' Size='20,20' TextAlignment='Center' TextAlignmentVertical='Center'>I</Text>
<Checkbox BackgroundOpacity='1.000' Location='200,3' Name='K9' ScrollExtent='20,20' Size='20,20' Style='/Buttons.KeymapButton.keystyle' TooltipStyle='/Tooltips.Default' value='I'></Checkbox>
<Text AbsorbsInput='false' Enabled='false' Font='/Fonts.HudFont1' LocalText='J' Location='225,3' Name='K1Text' ScrollExtent='20,20' Size='20,20' TextAlignment='Center' TextAlignmentVertical='Center'>J</Text>
<Checkbox BackgroundOpacity='1.000' Location='225,3' Name='K10' ScrollExtent='20,20' Size='20,20' Style='/Buttons.KeymapButton.keystyle' TooltipStyle='/Tooltips.Default' value='J'></Checkbox>
<Text AbsorbsInput='false' Enabled='false' Font='/Fonts.HudFont1' LocalText='K' Location='250,3' Name='K1Text' ScrollExtent='20,20' Size='20,20' TextAlignment='Center' TextAlignmentVertical='Center'>K</Text>
<Checkbox BackgroundOpacity='1.000' Location='250,3' Name='K11' ScrollExtent='20,20' Size='20,20' Style='/Buttons.KeymapButton.keystyle' TooltipStyle='/Tooltips.Default' value='K'></Checkbox>
<Text AbsorbsInput='false' Enabled='false' Font='/Fonts.HudFont1' LocalText='L' Location='275,3' Name='K1Text' ScrollExtent='20,20' Size='20,20' TextAlignment='Center' TextAlignmentVertical='Center'>L</Text>
<Checkbox BackgroundOpacity='1.000' Location='275,3' Name='K12' ScrollExtent='20,20' Size='20,20' Style='/Buttons.KeymapButton.keystyle' TooltipStyle='/Tooltips.Default' value='L'></Checkbox>
</Page>
<Page Location='12,82' Name='Row4' ScrollExtent='300,28' Size='300,28'>
<Text AbsorbsInput='false' Enabled='false' Font='/Fonts.HudFont1' LocalText='M' Location='0,3' Name='K1Text' ScrollExtent='20,20' Size='20,20' TextAlignment='Center' TextAlignmentVertical='Center'>M</Text>
<Checkbox BackgroundOpacity='1.000' Location='0,3' Name='K1' ScrollExtent='20,20' Size='20,20' Style='/Buttons.KeymapButton.keystyle' TooltipStyle='/Tooltips.Default' value='M'></Checkbox>
<Text AbsorbsInput='false' Enabled='false' Font='/Fonts.HudFont1' LocalText='N' Location='25,3' Name='K1Text' ScrollExtent='20,20' Size='20,20' TextAlignment='Center' TextAlignmentVertical='Center'>N</Text>
<Checkbox BackgroundOpacity='1.000' Location='25,3' Name='K2' ScrollExtent='20,20' Size='20,20' Style='/Buttons.KeymapButton.keystyle' TooltipStyle='/Tooltips.Default' value='N'></Checkbox>
<Text AbsorbsInput='false' Enabled='false' Font='/Fonts.HudFont1' LocalText='O' Location='50,3' Name='K1Text' ScrollExtent='20,20' Size='20,20' TextAlignment='Center' TextAlignmentVertical='Center'>O</Text>
<Checkbox BackgroundOpacity='1.000' Location='50,3' Name='K3' ScrollExtent='20,20' Size='20,20' Style='/Buttons.KeymapButton.keystyle' TooltipStyle='/Tooltips.Default' value='O'></Checkbox>
<Text AbsorbsInput='false' Enabled='false' Font='/Fonts.HudFont1' LocalText='P' Location='75,3' Name='K1Text' ScrollExtent='20,20' Size='20,20' TextAlignment='Center' TextAlignmentVertical='Center'>P</Text>
<Checkbox BackgroundOpacity='1.000' Location='75,3' Name='K4' ScrollExtent='20,20' Size='20,20' Style='/Buttons.KeymapButton.keystyle' TooltipStyle='/Tooltips.Default' value='P'></Checkbox>
<Text AbsorbsInput='false' Enabled='false' Font='/Fonts.HudFont1' LocalText='Q' Location='100,3' Name='K1Text' ScrollExtent='20,20' Size='20,20' TextAlignment='Center' TextAlignmentVertical='Center'>Q</Text>
<Checkbox BackgroundOpacity='1.000' Location='100,3' Name='K5' ScrollExtent='20,20' Size='20,20' Style='/Buttons.KeymapButton.keystyle' TooltipStyle='/Tooltips.Default' value='Q'></Checkbox>
<Text AbsorbsInput='false' Enabled='false' Font='/Fonts.HudFont1' LocalText='R' Location='125,3' Name='K1Text' ScrollExtent='20,20' Size='20,20' TextAlignment='Center' TextAlignmentVertical='Center'>R</Text>
<Checkbox BackgroundOpacity='1.000' Location='125,3' Name='K6' ScrollExtent='20,20' Size='20,20' Style='/Buttons.KeymapButton.keystyle' TooltipStyle='/Tooltips.Default' value='R'></Checkbox>
<Text AbsorbsInput='false' Enabled='false' Font='/Fonts.HudFont1' LocalText='S' Location='150,3' Name='K1Text' ScrollExtent='20,20' Size='20,20' TextAlignment='Center' TextAlignmentVertical='Center'>S</Text>
<Checkbox BackgroundOpacity='1.000' Location='150,3' Name='K7' ScrollExtent='20,20' Size='20,20' Style='/Buttons.KeymapButton.keystyle' TooltipStyle='/Tooltips.Default' value='S'></Checkbox>
<Text AbsorbsInput='false' Enabled='false' Font='/Fonts.HudFont1' LocalText='T' Location='175,3' Name='K1Text' ScrollExtent='20,20' Size='20,20' TextAlignment='Center' TextAlignmentVertical='Center'>T</Text>
<Checkbox BackgroundOpacity='1.000' Location='175,3' Name='K8' ScrollExtent='20,20' Size='20,20' Style='/Buttons.KeymapButton.keystyle' TooltipStyle='/Tooltips.Default' value='T'></Checkbox>
<Text AbsorbsInput='false' Enabled='false' Font='/Fonts.HudFont1' LocalText='U' Location='200,3' Name='K1Text' ScrollExtent='20,20' Size='20,20' TextAlignment='Center' TextAlignmentVertical='Center'>U</Text>
<Checkbox BackgroundOpacity='1.000' Location='200,3' Name='K9' ScrollExtent='20,20' Size='20,20' Style='/Buttons.KeymapButton.keystyle' TooltipStyle='/Tooltips.Default' value='U'></Checkbox>
<Text AbsorbsInput='false' Enabled='false' Font='/Fonts.HudFont1' LocalText='V' Location='225,3' Name='K1Text' ScrollExtent='20,20' Size='20,20' TextAlignment='Center' TextAlignmentVertical='Center'>V</Text>
<Checkbox BackgroundOpacity='1.000' Location='225,3' Name='K10' ScrollExtent='20,20' Size='20,20' Style='/Buttons.KeymapButton.keystyle' TooltipStyle='/Tooltips.Default' value='V'></Checkbox>
<Text AbsorbsInput='false' Enabled='false' Font='/Fonts.HudFont1' LocalText='W' Location='250,3' Name='K1Text' ScrollExtent='20,20' Size='20,20' TextAlignment='Center' TextAlignmentVertical='Center'>W</Text>
<Checkbox BackgroundOpacity='1.000' Location='250,3' Name='K11' ScrollExtent='20,20' Size='20,20' Style='/Buttons.KeymapButton.keystyle' TooltipStyle='/Tooltips.Default' value='W'></Checkbox>
<Text AbsorbsInput='false' Enabled='false' Font='/Fonts.HudFont1' LocalText='X' Location='275,3' Name='K1Text' ScrollExtent='20,20' Size='20,20' TextAlignment='Center' TextAlignmentVertical='Center'>X</Text>
<Checkbox BackgroundOpacity='1.000' Location='275,3' Name='K12' ScrollExtent='20,20' Size='20,20' Style='/Buttons.KeymapButton.keystyle' TooltipStyle='/Tooltips.Default' value='X'></Checkbox>
</Page>
<Page Location='12,105' Name='Row5' ScrollExtent='300,28' Size='300,28'>
<Text AbsorbsInput='false' Enabled='false' Font='/Fonts.HudFont1' LocalText='Y' Location='0,3' Name='K1Text' ScrollExtent='20,20' Size='20,20' TextAlignment='Center' TextAlignmentVertical='Center'>Y</Text>
<Checkbox Activated='true' BackgroundOpacity='1.000' Checked='true' Location='0,3' Name='K1' ScrollExtent='20,20' Size='20,20' Style='/Buttons.KeymapButton.keystyle' TooltipStyle='/Tooltips.Default' value='Y'></Checkbox>
<Text AbsorbsInput='false' Enabled='false' Font='/Fonts.HudFont1' LocalText='Z' Location='25,3' Name='K1Text' ScrollExtent='20,20' Size='20,20' TextAlignment='Center' TextAlignmentVertical='Center'>Z</Text>
<Checkbox Activated='true' BackgroundOpacity='1.000' Checked='true' Location='25,3' Name='K2' ScrollExtent='20,20' Size='20,20' Style='/Buttons.KeymapButton.keystyle' TooltipStyle='/Tooltips.Default' value='Z'></Checkbox>
<Text AbsorbsInput='false' Enabled='false' Font='/Fonts.HudFont1' LocalText='1' Location='50,3' Name='K1Text' ScrollExtent='20,20' Size='20,20' TextAlignment='Center' TextAlignmentVertical='Center'>1</Text>
<Checkbox BackgroundOpacity='1.000' Location='50,3' Name='K3' ScrollExtent='20,20' Size='20,20' Style='/Buttons.KeymapButton.keystyle' TooltipStyle='/Tooltips.Default' value='1'></Checkbox>
<Text AbsorbsInput='false' Enabled='false' Font='/Fonts.HudFont1' LocalText='2' Location='75,3' Name='K1Text' ScrollExtent='20,20' Size='20,20' TextAlignment='Center' TextAlignmentVertical='Center'>2</Text>
<Checkbox BackgroundOpacity='1.000' Location='75,3' Name='K4' ScrollExtent='20,20' Size='20,20' Style='/Buttons.KeymapButton.keystyle' TooltipStyle='/Tooltips.Default' value='2'></Checkbox>
<Text AbsorbsInput='false' Enabled='false' Font='/Fonts.HudFont1' LocalText='3' Location='100,3' Name='K1Text' ScrollExtent='20,20' Size='20,20' TextAlignment='Center' TextAlignmentVertical='Center'>3</Text>
<Checkbox BackgroundOpacity='1.000' Location='100,3' Name='K5' ScrollExtent='20,20' Size='20,20' Style='/Buttons.KeymapButton.keystyle' TooltipStyle='/Tooltips.Default' value='3'></Checkbox>
<Text AbsorbsInput='false' Enabled='false' Font='/Fonts.HudFont1' LocalText='4' Location='125,3' Name='K1Text' ScrollExtent='20,20' Size='20,20' TextAlignment='Center' TextAlignmentVertical='Center'>4</Text>
<Checkbox BackgroundOpacity='1.000' Location='125,3' Name='K6' ScrollExtent='20,20' Size='20,20' Style='/Buttons.KeymapButton.keystyle' TooltipStyle='/Tooltips.Default' value='4'></Checkbox>
<Text AbsorbsInput='false' Enabled='false' Font='/Fonts.HudFont1' LocalText='5' Location='150,3' Name='K1Text' ScrollExtent='20,20' Size='20,20' TextAlignment='Center' TextAlignmentVertical='Center'>5</Text>
<Checkbox BackgroundOpacity='1.000' Location='150,3' Name='K7' ScrollExtent='20,20' Size='20,20' Style='/Buttons.KeymapButton.keystyle' TooltipStyle='/Tooltips.Default' value='5'></Checkbox>
<Text AbsorbsInput='false' Enabled='false' Font='/Fonts.HudFont1' LocalText='6' Location='175,3' Name='K1Text' ScrollExtent='20,20' Size='20,20' TextAlignment='Center' TextAlignmentVertical='Center'>6</Text>
<Checkbox BackgroundOpacity='1.000' Location='175,3' Name='K8' ScrollExtent='20,20' Size='20,20' Style='/Buttons.KeymapButton.keystyle' TooltipStyle='/Tooltips.Default' value='6'></Checkbox>
<Text AbsorbsInput='false' Enabled='false' Font='/Fonts.HudFont1' LocalText='7' Location='200,3' Name='K1Text' ScrollExtent='20,20' Size='20,20' TextAlignment='Center' TextAlignmentVertical='Center'>7</Text>
<Checkbox BackgroundOpacity='1.000' Location='200,3' Name='K9' ScrollExtent='20,20' Size='20,20' Style='/Buttons.KeymapButton.keystyle' TooltipStyle='/Tooltips.Default' value='7'></Checkbox>
<Text AbsorbsInput='false' Enabled='false' Font='/Fonts.HudFont1' LocalText='8' Location='225,3' Name='K1Text' ScrollExtent='20,20' Size='20,20' TextAlignment='Center' TextAlignmentVertical='Center'>8</Text>
<Checkbox BackgroundOpacity='1.000' Location='225,3' Name='K10' ScrollExtent='20,20' Size='20,20' Style='/Buttons.KeymapButton.keystyle' TooltipStyle='/Tooltips.Default' value='8'></Checkbox>
<Text AbsorbsInput='false' Enabled='false' Font='/Fonts.HudFont1' LocalText='9' Location='250,3' Name='K1Text' ScrollExtent='20,20' Size='20,20' TextAlignment='Center' TextAlignmentVertical='Center'>9</Text>
<Checkbox BackgroundOpacity='1.000' Location='250,3' Name='K11' ScrollExtent='20,20' Size='20,20' Style='/Buttons.KeymapButton.keystyle' TooltipStyle='/Tooltips.Default' value='9'></Checkbox>
<Text AbsorbsInput='false' Enabled='false' Font='/Fonts.HudFont1' LocalText='0' Location='275,3' Name='K1Text' ScrollExtent='20,20' Size='20,20' TextAlignment='Center' TextAlignmentVertical='Center'>0</Text>
<Checkbox BackgroundOpacity='1.000' Location='275,3' Name='K12' ScrollExtent='20,20' Size='20,20' Style='/Buttons.KeymapButton.keystyle' TooltipStyle='/Tooltips.Default' value='0'></Checkbox>
</Page>
<Page Location='12,127' Name='Row6' ScrollExtent='300,28' Size='300,28'>
<Text AbsorbsInput='false' Enabled='false' Font='/Fonts.HudFont1' LocalText='`' Location='0,3' Name='K1Text' ScrollExtent='20,20' Size='20,20' TextAlignment='Center' TextAlignmentVertical='Center'>`</Text>
<Checkbox Activated='true' BackgroundOpacity='1.000' Checked='true' Location='0,3' Name='K1' ScrollExtent='20,20' Size='20,20' Style='/Buttons.KeymapButton.keystyle' TooltipStyle='/Tooltips.Default' value='`'></Checkbox>
<Text AbsorbsInput='false' Enabled='false' Font='/Fonts.HudFont1' LocalText='-' Location='25,3' Name='K1Text' ScrollExtent='20,20' Size='20,20' TextAlignment='Center' TextAlignmentVertical='Center'>-</Text>
<Checkbox Activated='true' BackgroundOpacity='1.000' Checked='true' Location='25,3' Name='K2' ScrollExtent='20,20' Size='20,20' Style='/Buttons.KeymapButton.keystyle' TooltipStyle='/Tooltips.Default' value='-'></Checkbox>
<Text AbsorbsInput='false' Enabled='false' Font='/Fonts.HudFont1' LocalText='=' Location='50,3' Name='K1Text' ScrollExtent='20,20' Size='20,20' TextAlignment='Center' TextAlignmentVertical='Center'>=</Text>
<Checkbox Activated='true' BackgroundOpacity='1.000' Checked='true' Location='50,3' Name='K3' ScrollExtent='20,20' Size='20,20' Style='/Buttons.KeymapButton.keystyle' TooltipStyle='/Tooltips.Default' value='='></Checkbox>
<Text AbsorbsInput='false' Enabled='false' Font='/Fonts.HudFont1' LocalText='[' Location='75,3' Name='K1Text' ScrollExtent='20,20' Size='20,20' TextAlignment='Center' TextAlignmentVertical='Center'>[</Text>
<Checkbox BackgroundOpacity='1.000' Location='75,3' Name='K4' ScrollExtent='20,20' Size='20,20' Style='/Buttons.KeymapButton.keystyle' TooltipStyle='/Tooltips.Default' value='['></Checkbox>
<Text AbsorbsInput='false' Enabled='false' Font='/Fonts.HudFont1' LocalText=']' Location='100,3' Name='K1Text' ScrollExtent='20,20' Size='20,20' TextAlignment='Center' TextAlignmentVertical='Center'>]</Text>
<Checkbox BackgroundOpacity='1.000' Location='100,3' Name='K5' ScrollExtent='20,20' Size='20,20' Style='/Buttons.KeymapButton.keystyle' TooltipStyle='/Tooltips.Default' value=']'></Checkbox>
<Text AbsorbsInput='false' Enabled='false' Font='/Fonts.HudFont1' LocalText='\\\\' Location='125,3' Name='K1Text' ScrollExtent='20,20' Size='20,20' TextAlignment='Center' TextAlignmentVertical='Center'>\\\\</Text>
<Checkbox BackgroundOpacity='1.000' Location='125,3' Name='K6' ScrollExtent='20,20' Size='20,20' Style='/Buttons.KeymapButton.keystyle' TooltipStyle='/Tooltips.Default' value='Backslash'></Checkbox>
<Text AbsorbsInput='false' Enabled='false' Font='/Fonts.HudFont1' LocalText=';' Location='150,3' Name='K1Text' ScrollExtent='20,20' Size='20,20' TextAlignment='Center' TextAlignmentVertical='Center'>;</Text>
<Checkbox BackgroundOpacity='1.000' Location='150,3' Name='K7' ScrollExtent='20,20' Size='20,20' Style='/Buttons.KeymapButton.keystyle' TooltipStyle='/Tooltips.Default' value=':'></Checkbox>
<Text AbsorbsInput='false' Enabled='false' Font='/Fonts.HudFont1' LocalText=',' Location='175,3' Name='K1Text' ScrollExtent='20,20' Size='20,20' TextAlignment='Center' TextAlignmentVertical='Center'>,</Text>
<Checkbox BackgroundOpacity='1.000' Location='175,3' Name='K8' ScrollExtent='20,20' Size='20,20' Style='/Buttons.KeymapButton.keystyle' TooltipStyle='/Tooltips.Default' value=','></Checkbox>
<Text AbsorbsInput='false' Enabled='false' Font='/Fonts.HudFont1' LocalText='.' Location='200,3' Name='K1Text' ScrollExtent='20,20' Size='20,20' TextAlignment='Center' TextAlignmentVertical='Center'>.</Text>
<Checkbox BackgroundOpacity='1.000' Location='200,3' Name='K9' ScrollExtent='20,20' Size='20,20' Style='/Buttons.KeymapButton.keystyle' TooltipStyle='/Tooltips.Default' value='.'></Checkbox>
<Text AbsorbsInput='false' Enabled='false' Font='/Fonts.HudFont1' LocalText='\'' Location='225,3' Name='K1Text' ScrollExtent='20,20' Size='20,20' TextAlignment='Center' TextAlignmentVertical='Center'>\'</Text>
<Checkbox BackgroundOpacity='1.000' Location='225,3' Name='K10' ScrollExtent='20,20' Size='20,20' Style='/Buttons.KeymapButton.keystyle' TooltipStyle='/Tooltips.Default'></Checkbox>
<Text AbsorbsInput='false' Enabled='false' Font='/Fonts.HudFont1' LocalText='/' Location='250,3' Name='K1Text' ScrollExtent='20,20' Size='20,20' TextAlignment='Center' TextAlignmentVertical='Center'>/</Text>
<Checkbox BackgroundOpacity='1.000' Location='250,3' Name='K11' ScrollExtent='20,20' Size='20,20' Style='/Buttons.KeymapButton.keystyle' TooltipStyle='/Tooltips.Default' value='/'></Checkbox>
</Page>
<Page Location='-1,193' Name='Large' ScrollExtent='325,129' Size='325,129' UserMovable='true' UserResizable='true'>
<Text AbsorbsInput='false' Enabled='false' Font='/Fonts.HudFont1' LocalText='BACKSPACE' Location='4,3' Name='J1Text' ScrollExtent='74,20' Size='74,20' TextAlignment='Center' TextAlignmentVertical='Center'>BACKSPACE</Text>
<Checkbox BackgroundOpacity='1.000' Location='4,3' Name='J1' ScrollExtent='75,22' Size='75,22' Style='/Buttons.KeymapButton.joystyle' TooltipStyle='/Tooltips.Default' value='Backspace'></Checkbox>
<Text AbsorbsInput='false' Enabled='false' Font='/Fonts.HudFont1' LocalText='CAPS LOCK' Location='84,3' Name='J2Text' ScrollExtent='74,20' Size='74,20' TextAlignment='Center' TextAlignmentVertical='Center'>CAPS LOCK</Text>
<Checkbox BackgroundOpacity='1.000' Location='84,3' Name='J2' ScrollExtent='75,22' Size='75,22' Style='/Buttons.KeymapButton.joystyle' TooltipStyle='/Tooltips.Default' value='Caps Lock'></Checkbox>
<Text AbsorbsInput='false' Enabled='false' Font='/Fonts.HudFont1' LocalText='NUM ENTER' Location='164,3' Name='J3Text' ScrollExtent='74,20' Size='74,20' TextAlignment='Center' TextAlignmentVertical='Center'>NUM ENTER</Text>
<Checkbox BackgroundOpacity='1.000' Location='164,3' Name='J3' ScrollExtent='75,22' Size='75,22' Style='/Buttons.KeymapButton.joystyle' TooltipStyle='/Tooltips.Default' value='Num Pad Enter'></Checkbox>
<Text AbsorbsInput='false' Enabled='false' Font='/Fonts.HudFont1' LocalText='APPLICATION' Location='244,3' Name='J4Text' ScrollExtent='74,20' Size='74,20' TextAlignment='Center' TextAlignmentVertical='Center'>APPLICATION</Text>
<Checkbox BackgroundOpacity='1.000' Location='244,3' Name='J4' ScrollExtent='75,22' Size='75,22' Style='/Buttons.KeymapButton.joystyle' TooltipStyle='/Tooltips.Default' value='Application'></Checkbox>
<Text AbsorbsInput='false' Enabled='false' Font='/Fonts.HudFont1' LocalText='PRINT' Location='1,28' Name='J5Text' ScrollExtent='63,20' Size='63,20' TextAlignment='Center' TextAlignmentVertical='Center'>PRINT</Text>
<Checkbox BackgroundOpacity='1.000' Location='1,28' Name='J5' ScrollExtent='63,22' Size='63,22' Style='/Buttons.KeymapButton.joystyle' TooltipStyle='/Tooltips.Default' value='Print Screen'></Checkbox>
<Text AbsorbsInput='false' Enabled='false' Font='/Fonts.HudFont1' LocalText='SCROLL' Location='66,28' Name='J6Text' ScrollExtent='63,20' Size='63,20' TextAlignment='Center' TextAlignmentVertical='Center'>SCROLL</Text>
<Checkbox BackgroundOpacity='1.000' Location='66,28' Name='J6' ScrollExtent='63,22' Size='63,22' Style='/Buttons.KeymapButton.joystyle' TooltipStyle='/Tooltips.Default' value='Scroll Lock'></Checkbox>
<Text AbsorbsInput='false' Enabled='false' Font='/Fonts.HudFont1' LocalText='PAUSE' Location='131,28' Name='J7Text' ScrollExtent='63,20' Size='63,20' TextAlignment='Center' TextAlignmentVertical='Center'>PAUSE</Text>
<Checkbox BackgroundOpacity='1.000' Location='131,28' Name='J7' ScrollExtent='63,22' Size='63,22' Style='/Buttons.KeymapButton.joystyle' TooltipStyle='/Tooltips.Default' value='Pause'></Checkbox>
<Text AbsorbsInput='false' Enabled='false' Font='/Fonts.HudFont1' LocalText='ENTER' Location='196,28' Name='J23Text' ScrollExtent='63,20' Size='63,20' TextAlignment='Center' TextAlignmentVertical='Center'>ENTER</Text>
<Checkbox BackgroundOpacity='1.000' Location='196,28' Name='J23' ScrollExtent='63,22' Size='63,22' Style='/Buttons.KeymapButton.joystyle' TooltipStyle='/Tooltips.Default' value='Enter'></Checkbox>
<Text AbsorbsInput='false' Enabled='false' Font='/Fonts.HudFont1' LocalText='NUM LOCK' Location='261,28' Name='J27Text' ScrollExtent='63,20' Size='63,20' TextAlignment='Center' TextAlignmentVertical='Center'>NUM LOCK</Text>
<Checkbox BackgroundOpacity='1.000' Location='261,28' Name='J27' ScrollExtent='63,22' Size='63,22' Style='/Buttons.KeymapButton.joystyle' TooltipStyle='/Tooltips.Default' value='Num Lock'></Checkbox>
<Text AbsorbsInput='false' Enabled='false' Font='/Fonts.HudFont1' LocalText='SHIFT' Location='15,53' Name='J24Text' ScrollExtent='43,20' Size='43,20' TextAlignment='Center' TextAlignmentVertical='Center'>SHIFT</Text>
<Checkbox BackgroundOpacity='1.000' Location='15,53' Name='J24' ScrollExtent='43,22' Size='43,22' Style='/Buttons.KeymapButton.joystyle' TooltipStyle='/Tooltips.Default' value='SHIFT'></Checkbox>
<Text AbsorbsInput='false' Enabled='false' Font='/Fonts.HudFont1' LocalText='NUM 1' Location='65,53' Name='J8Text' ScrollExtent='43,20' Size='43,20' TextAlignment='Center' TextAlignmentVertical='Center'>NUM 1</Text>
<Checkbox BackgroundOpacity='1.000' Location='65,53' Name='J8' ScrollExtent='43,22' Size='43,22' Style='/Buttons.KeymapButton.joystyle' TooltipStyle='/Tooltips.Default' value='Num Pad 1'></Checkbox>
<Text AbsorbsInput='false' Enabled='false' Font='/Fonts.HudFont1' LocalText='NUM 2' Location='115,53' Name='J9Text' ScrollExtent='43,20' Size='43,20' TextAlignment='Center' TextAlignmentVertical='Center'>NUM 2</Text>
<Checkbox BackgroundOpacity='1.000' Location='115,53' Name='J9' ScrollExtent='43,22' Size='43,22' Style='/Buttons.KeymapButton.joystyle' TooltipStyle='/Tooltips.Default' value='Num Pad 2'></Checkbox>
<Text AbsorbsInput='false' Enabled='false' Font='/Fonts.HudFont1' LocalText='NUM 3' Location='165,53' Name='J10Text' ScrollExtent='43,20' Size='43,20' TextAlignment='Center' TextAlignmentVertical='Center'>NUM 3</Text>
<Checkbox BackgroundOpacity='1.000' Location='165,53' Name='J10' ScrollExtent='43,22' Size='43,22' Style='/Buttons.KeymapButton.joystyle' TooltipStyle='/Tooltips.Default' value='Num Pad 3'></Checkbox>
<Text AbsorbsInput='false' Enabled='false' Font='/Fonts.HudFont1' LocalText='NUM 4' Location='215,53' Name='J11Text' ScrollExtent='43,20' Size='43,20' TextAlignment='Center' TextAlignmentVertical='Center'>NUM 4</Text>
<Checkbox BackgroundOpacity='1.000' Location='215,53' Name='J11' ScrollExtent='43,22' Size='43,22' Style='/Buttons.KeymapButton.joystyle' TooltipStyle='/Tooltips.Default' value='Num Pad 4'></Checkbox>
<Text AbsorbsInput='false' Enabled='false' Font='/Fonts.HudFont1' LocalText='NUM 5' Location='265,53' Name='J12Text' ScrollExtent='43,20' Size='43,20' TextAlignment='Center' TextAlignmentVertical='Center'>NUM 5</Text>
<Checkbox BackgroundOpacity='1.000' Location='265,53' Name='J12' ScrollExtent='43,22' Size='43,22' Style='/Buttons.KeymapButton.joystyle' TooltipStyle='/Tooltips.Default' value='Num Pad 5'></Checkbox>
<Text AbsorbsInput='false' Enabled='false' Font='/Fonts.HudFont1' LocalText='CTRL' Location='15,78' Name='J25Text' ScrollExtent='43,20' Size='43,20' TextAlignment='Center' TextAlignmentVertical='Center'>CTRL</Text>
<Checkbox BackgroundOpacity='1.000' Location='15,78' Name='J25' ScrollExtent='43,22' Size='43,22' Style='/Buttons.KeymapButton.joystyle' TooltipStyle='/Tooltips.Default' value='CTRL'></Checkbox>
<Text AbsorbsInput='false' Enabled='false' Font='/Fonts.HudFont1' LocalText='NUM 6' Location='65,78' Name='J13Text' ScrollExtent='43,20' Size='43,20' TextAlignment='Center' TextAlignmentVertical='Center'>NUM 6</Text>
<Checkbox BackgroundOpacity='1.000' Location='65,78' Name='J13' ScrollExtent='43,22' Size='43,22' Style='/Buttons.KeymapButton.joystyle' TooltipStyle='/Tooltips.Default' value='Num Pad 6'></Checkbox>
<Text AbsorbsInput='false' Enabled='false' Font='/Fonts.HudFont1' LocalText='NUM 7' Location='115,78' Name='J14Text' ScrollExtent='43,20' Size='43,20' TextAlignment='Center' TextAlignmentVertical='Center'>NUM 7</Text>
<Checkbox BackgroundOpacity='1.000' Location='115,78' Name='J14' ScrollExtent='43,22' Size='43,22' Style='/Buttons.KeymapButton.joystyle' TooltipStyle='/Tooltips.Default' value='Num Pad 7'></Checkbox>
<Text AbsorbsInput='false' Enabled='false' Font='/Fonts.HudFont1' LocalText='NUM 8 ' Location='165,78' Name='J15Text' ScrollExtent='43,20' Size='43,20' TextAlignment='Center' TextAlignmentVertical='Center'>NUM 8 </Text>
<Checkbox BackgroundOpacity='1.000' Location='165,78' Name='J15' ScrollExtent='43,22' Size='43,22' Style='/Buttons.KeymapButton.joystyle' TooltipStyle='/Tooltips.Default' value='Num Pad 8'></Checkbox>
<Text AbsorbsInput='false' Enabled='false' Font='/Fonts.HudFont1' LocalText='NUM 9 ' Location='215,78' Name='J16Text' ScrollExtent='43,20' Size='43,20' TextAlignment='Center' TextAlignmentVertical='Center'>NUM 9 </Text>
<Checkbox BackgroundOpacity='1.000' Location='215,78' Name='J16' ScrollExtent='43,22' Size='43,22' Style='/Buttons.KeymapButton.joystyle' TooltipStyle='/Tooltips.Default' value='Num Pad 9'></Checkbox>
<Text AbsorbsInput='false' Enabled='false' Font='/Fonts.HudFont1' LocalText='NUM 0' Location='265,78' Name='J17Text' ScrollExtent='43,20' Size='43,20' TextAlignment='Center' TextAlignmentVertical='Center'>NUM 0</Text>
<Checkbox BackgroundOpacity='1.000' Location='265,78' Name='J17' ScrollExtent='43,22' Size='43,22' Style='/Buttons.KeymapButton.joystyle' TooltipStyle='/Tooltips.Default' value='Num Pad 0'></Checkbox>
<Text AbsorbsInput='false' Enabled='false' Font='/Fonts.HudFont1' LocalText='ALT' Location='15,103' Name='J26Text' ScrollExtent='43,20' Size='43,20' TextAlignment='Center' TextAlignmentVertical='Center'>ALT</Text>
<Checkbox BackgroundOpacity='1.000' Location='15,103' Name='J26' ScrollExtent='43,22' Size='43,22' Style='/Buttons.KeymapButton.joystyle' TooltipStyle='/Tooltips.Default' value='ALT'></Checkbox>
<Text AbsorbsInput='false' Enabled='false' Font='/Fonts.HudFont1' LocalText='NUM /' Location='65,103' Name='J18Text' ScrollExtent='43,20' Size='43,20' TextAlignment='Center' TextAlignmentVertical='Center'>NUM /</Text>
<Checkbox BackgroundOpacity='1.000' Location='65,103' Name='J18' ScrollExtent='43,22' Size='43,22' Style='/Buttons.KeymapButton.joystyle' TooltipStyle='/Tooltips.Default' value='Num Pad /'></Checkbox>
<Text AbsorbsInput='false' Enabled='false' Font='/Fonts.HudFont1' LocalText='NUM *' Location='115,103' Name='J19Text' ScrollExtent='43,20' Size='43,20' TextAlignment='Center' TextAlignmentVertical='Center'>NUM *</Text>
<Checkbox BackgroundOpacity='1.000' Location='115,103' Name='J19' ScrollExtent='43,22' Size='43,22' Style='/Buttons.KeymapButton.joystyle' TooltipStyle='/Tooltips.Default' value='Num Pad *'></Checkbox>
<Text AbsorbsInput='false' Enabled='false' Font='/Fonts.HudFont1' LocalText='NUM -' Location='165,103' Name='J20Text' ScrollExtent='43,20' Size='43,20' TextAlignment='Center' TextAlignmentVertical='Center'>NUM -</Text>
<Checkbox BackgroundOpacity='1.000' Location='165,103' Name='J20' ScrollExtent='43,22' Size='43,22' Style='/Buttons.KeymapButton.joystyle' TooltipStyle='/Tooltips.Default' value='Num Pad -'></Checkbox>
<Text AbsorbsInput='false' Enabled='false' Font='/Fonts.HudFont1' LocalText='NUM +' Location='215,103' Name='J21Text' ScrollExtent='43,20' Size='43,20' TextAlignment='Center' TextAlignmentVertical='Center'>NUM +</Text>
<Checkbox BackgroundOpacity='1.000' Location='215,103' Name='J21' ScrollExtent='43,22' Size='43,22' Style='/Buttons.KeymapButton.joystyle' TooltipStyle='/Tooltips.Default' value='Num Pad +'></Checkbox>
<Text AbsorbsInput='false' Enabled='false' Font='/Fonts.HudFont1' LocalText='NUM .' Location='265,103' Name='J22Text' ScrollExtent='43,20' Size='43,20' TextAlignment='Center' TextAlignmentVertical='Center'>NUM .</Text>
<Checkbox BackgroundOpacity='1.000' Location='265,103' Name='J22' ScrollExtent='43,22' Size='43,22' Style='/Buttons.KeymapButton.joystyle' TooltipStyle='/Tooltips.Default' value='Num Pad .'></Checkbox>
</Page>
</Page>
<Page Location='420,106' Name='JoystickPage' ScrollExtent='328,320' Size='328,320' Visible='false'>
<Page Location='-3,3' Name='JoyLayout' ScrollExtent='331,319' Size='331,319'>
<Text Font='/Fonts.HudFont3' LocalText='Name (local)' Location='11,5' Name='Name' ScrollExtent='196,20' Size='196,20'>Name (local)</Text>
<Page Location='3,88' Name='Normal' ScrollExtent='330,107' Size='330,107'>
<Text AbsorbsInput='false' Enabled='false' Font='/Fonts.HudFont1' LocalText='Bobble' Location='0,-1' Name='J1Text' ScrollExtent='63,20' Size='63,20' TextAlignment='Center' TextAlignmentVertical='Center'>Bobble</Text>
<Checkbox BackgroundOpacity='1.000' Location='0,-1' Name='J1' ScrollExtent='64,22' Size='64,22' Style='/Buttons.KeymapButton.joystyle'></Checkbox>
<Text AbsorbsInput='false' Enabled='false' Font='/Fonts.HudFont1' LocalText='Joy 1' Location='65,-1' Name='J2Text' ScrollExtent='63,20' Size='63,20' TextAlignment='Center' TextAlignmentVertical='Center'>Joy 1</Text>
<Checkbox BackgroundOpacity='1.000' Location='65,-1' Name='J2' ScrollExtent='64,22' Size='64,22' Style='/Buttons.KeymapButton.joystyle'></Checkbox>
<Text AbsorbsInput='false' Enabled='false' Font='/Fonts.HudFont1' LocalText='Joy 1' Location='130,-1' Name='J3Text' ScrollExtent='63,20' Size='63,20' TextAlignment='Center' TextAlignmentVertical='Center'>Joy 1</Text>
<Checkbox BackgroundOpacity='1.000' Location='130,-1' Name='J3' ScrollExtent='64,22' Size='64,22' Style='/Buttons.KeymapButton.joystyle'></Checkbox>
<Text AbsorbsInput='false' Enabled='false' Font='/Fonts.HudFont1' LocalText='Joy 1' Location='195,-1' Name='J4Text' ScrollExtent='63,20' Size='63,20' TextAlignment='Center' TextAlignmentVertical='Center'>Joy 1</Text>
<Checkbox BackgroundOpacity='1.000' Location='195,-1' Name='J4' ScrollExtent='64,22' Size='64,22' Style='/Buttons.KeymapButton.joystyle'></Checkbox>
<Text AbsorbsInput='false' Enabled='false' Font='/Fonts.HudFont1' LocalText='Joy 1' Location='260,-1' Name='J5Text' ScrollExtent='63,20' Size='63,20' TextAlignment='Center' TextAlignmentVertical='Center'>Joy 1</Text>
<Checkbox BackgroundOpacity='1.000' Location='260,-1' Name='J5' ScrollExtent='64,22' Size='64,22' Style='/Buttons.KeymapButton.joystyle'></Checkbox>
<Text AbsorbsInput='false' Enabled='false' Font='/Fonts.HudFont1' LocalText='Joy 1' Location='0,26' Name='J6Text' ScrollExtent='63,20' Size='63,20' TextAlignment='Center' TextAlignmentVertical='Center'>Joy 1</Text>
<Checkbox BackgroundOpacity='1.000' Location='0,26' Name='J6' ScrollExtent='64,22' Size='64,22' Style='/Buttons.KeymapButton.joystyle'></Checkbox>
<Text AbsorbsInput='false' Enabled='false' Font='/Fonts.HudFont1' LocalText='Joy 1' Location='65,26' Name='J7Text' ScrollExtent='63,20' Size='63,20' TextAlignment='Center' TextAlignmentVertical='Center'>Joy 1</Text>
<Checkbox BackgroundOpacity='1.000' Location='65,26' Name='J7' ScrollExtent='64,22' Size='64,22' Style='/Buttons.KeymapButton.joystyle'></Checkbox>
<Text AbsorbsInput='false' Enabled='false' Font='/Fonts.HudFont1' LocalText='Joy 1' Location='130,26' Name='J8Text' ScrollExtent='63,20' Size='63,20' TextAlignment='Center' TextAlignmentVertical='Center'>Joy 1</Text>
<Checkbox BackgroundOpacity='1.000' Location='130,26' Name='J8' ScrollExtent='64,22' Size='64,22' Style='/Buttons.KeymapButton.joystyle'></Checkbox>
<Text AbsorbsInput='false' Enabled='false' Font='/Fonts.HudFont1' LocalText='Joy 1' Location='195,26' Name='J9Text' ScrollExtent='63,20' Size='63,20' TextAlignment='Center' TextAlignmentVertical='Center'>Joy 1</Text>
<Checkbox BackgroundOpacity='1.000' Location='195,26' Name='J9' ScrollExtent='64,22' Size='64,22' Style='/Buttons.KeymapButton.joystyle'></Checkbox>
<Text AbsorbsInput='false' Enabled='false' Font='/Fonts.HudFont1' LocalText='Joy 1' Location='260,26' Name='J10Text' ScrollExtent='63,20' Size='63,20' TextAlignment='Center' TextAlignmentVertical='Center'>Joy 1</Text>
<Checkbox BackgroundOpacity='1.000' Location='260,26' Name='J10' ScrollExtent='64,22' Size='64,22' Style='/Buttons.KeymapButton.joystyle'></Checkbox>
<Text AbsorbsInput='false' Enabled='false' Font='/Fonts.HudFont1' LocalText='Joy 1' Location='0,53' Name='J11Text' ScrollExtent='63,20' Size='63,20' TextAlignment='Center' TextAlignmentVertical='Center'>Joy 1</Text>
<Checkbox BackgroundOpacity='1.000' Location='0,53' Name='J11' ScrollExtent='64,22' Size='64,22' Style='/Buttons.KeymapButton.joystyle'></Checkbox>
<Text AbsorbsInput='false' Enabled='false' Font='/Fonts.HudFont1' LocalText='Joy 1' Location='65,53' Name='J12Text' ScrollExtent='63,20' Size='63,20' TextAlignment='Center' TextAlignmentVertical='Center'>Joy 1</Text>
<Checkbox BackgroundOpacity='1.000' Location='65,53' Name='J12' ScrollExtent='64,22' Size='64,22' Style='/Buttons.KeymapButton.joystyle'></Checkbox>
<Text AbsorbsInput='false' Enabled='false' Font='/Fonts.HudFont1' LocalText='Joy 1' Location='130,53' Name='J13Text' ScrollExtent='63,20' Size='63,20' TextAlignment='Center' TextAlignmentVertical='Center'>Joy 1</Text>
<Checkbox BackgroundOpacity='1.000' Location='130,53' Name='J13' ScrollExtent='64,22' Size='64,22' Style='/Buttons.KeymapButton.joystyle'></Checkbox>
<Text AbsorbsInput='false' Enabled='false' Font='/Fonts.HudFont1' LocalText='Joy 1' Location='195,53' Name='J14Text' ScrollExtent='63,20' Size='63,20' TextAlignment='Center' TextAlignmentVertical='Center'>Joy 1</Text>
<Checkbox BackgroundOpacity='1.000' Location='195,53' Name='J14' ScrollExtent='64,22' Size='64,22' Style='/Buttons.KeymapButton.joystyle'></Checkbox>
<Text AbsorbsInput='false' Enabled='false' Font='/Fonts.HudFont1' LocalText='Joy 1' Location='260,53' Name='J15Text' ScrollExtent='63,20' Size='63,20' TextAlignment='Center' TextAlignmentVertical='Center'>Joy 1</Text>
<Checkbox BackgroundOpacity='1.000' Location='260,53' Name='J15' ScrollExtent='64,22' Size='64,22' Style='/Buttons.KeymapButton.joystyle'></Checkbox>
<Text AbsorbsInput='false' Enabled='false' Font='/Fonts.HudFont1' LocalText='Joy 1' Location='0,80' Name='J16Text' ScrollExtent='63,20' Size='63,20' TextAlignment='Center' TextAlignmentVertical='Center'>Joy 1</Text>
<Checkbox BackgroundOpacity='1.000' Location='0,80' Name='J16' ScrollExtent='64,22' Size='64,22' Style='/Buttons.KeymapButton.joystyle'></Checkbox>
<Text AbsorbsInput='false' Enabled='false' Font='/Fonts.HudFont1' LocalText='Joy 1' Location='65,80' Name='J17Text' ScrollExtent='63,20' Size='63,20' TextAlignment='Center' TextAlignmentVertical='Center'>Joy 1</Text>
<Checkbox BackgroundOpacity='1.000' Location='65,80' Name='J17' ScrollExtent='64,22' Size='64,22' Style='/Buttons.KeymapButton.joystyle'></Checkbox>
<Text AbsorbsInput='false' Enabled='false' Font='/Fonts.HudFont1' LocalText='Joy 1' Location='130,80' Name='J18Text' ScrollExtent='63,20' Size='63,20' TextAlignment='Center' TextAlignmentVertical='Center'>Joy 1</Text>
<Checkbox BackgroundOpacity='1.000' Location='130,80' Name='J18' ScrollExtent='64,22' Size='64,22' Style='/Buttons.KeymapButton.joystyle'></Checkbox>
<Text AbsorbsInput='false' Enabled='false' Font='/Fonts.HudFont1' LocalText='Joy 1' Location='195,80' Name='J19Text' ScrollExtent='63,20' Size='63,20' TextAlignment='Center' TextAlignmentVertical='Center'>Joy 1</Text>
<Checkbox BackgroundOpacity='1.000' Location='195,80' Name='J19' ScrollExtent='64,22' Size='64,22' Style='/Buttons.KeymapButton.joystyle'></Checkbox>
<Text AbsorbsInput='false' Enabled='false' Font='/Fonts.HudFont1' LocalText='Joy 1' Location='260,80' Name='J20Text' ScrollExtent='63,20' Size='63,20' TextAlignment='Center' TextAlignmentVertical='Center'>Joy 1</Text>
<Checkbox BackgroundOpacity='1.000' Location='260,80' Name='J20' ScrollExtent='64,22' Size='64,22' Style='/Buttons.KeymapButton.joystyle'></Checkbox>
</Page>
<Page Location='2,245' Name='Shifted' ScrollExtent='330,68' Size='330,68'>
<Text AbsorbsInput='false' Enabled='false' Font='/Fonts.HudFont1' LocalText='Bobble' Location='0,15' Name='J1Text' ScrollExtent='63,20' Size='63,20' TextAlignment='Center' TextAlignmentVertical='Center'>Bobble</Text>
<Checkbox BackgroundOpacity='1.000' Location='0,15' Name='J1' ScrollExtent='64,22' Size='64,22' Style='/Buttons.KeymapButton.joystyle'></Checkbox>
<Text AbsorbsInput='false' Enabled='false' Font='/Fonts.HudFont1' LocalText='Joy 1' Location='65,15' Name='J2Text' ScrollExtent='63,20' Size='63,20' TextAlignment='Center' TextAlignmentVertical='Center'>Joy 1</Text>
<Checkbox BackgroundOpacity='1.000' Location='65,15' Name='J2' ScrollExtent='64,22' Size='64,22' Style='/Buttons.KeymapButton.joystyle'></Checkbox>
<Text AbsorbsInput='false' Enabled='false' Font='/Fonts.HudFont1' LocalText='Joy 1' Location='130,15' Name='J3Text' ScrollExtent='63,20' Size='63,20' TextAlignment='Center' TextAlignmentVertical='Center'>Joy 1</Text>
<Checkbox BackgroundOpacity='1.000' Location='130,15' Name='J3' ScrollExtent='64,22' Size='64,22' Style='/Buttons.KeymapButton.joystyle'></Checkbox>
<Text AbsorbsInput='false' Enabled='false' Font='/Fonts.HudFont1' LocalText='Joy 1' Location='195,15' Name='J4Text' ScrollExtent='63,20' Size='63,20' TextAlignment='Center' TextAlignmentVertical='Center'>Joy 1</Text>
<Checkbox BackgroundOpacity='1.000' Location='195,15' Name='J4' ScrollExtent='64,22' Size='64,22' Style='/Buttons.KeymapButton.joystyle'></Checkbox>
<Text AbsorbsInput='false' Enabled='false' Font='/Fonts.HudFont1' LocalText='Joy 1' Location='260,15' Name='J5Text' ScrollExtent='63,20' Size='63,20' TextAlignment='Center' TextAlignmentVertical='Center'>Joy 1</Text>
<Checkbox BackgroundOpacity='1.000' Location='260,15' Name='J5' ScrollExtent='64,22' Size='64,22' Style='/Buttons.KeymapButton.joystyle'></Checkbox>
<Text AbsorbsInput='false' Enabled='false' Font='/Fonts.HudFont1' LocalText='Joy 1' Location='0,42' Name='J6Text' ScrollExtent='63,20' Size='63,20' TextAlignment='Center' TextAlignmentVertical='Center'>Joy 1</Text>
<Checkbox BackgroundOpacity='1.000' Location='0,42' Name='J6' ScrollExtent='64,22' Size='64,22' Style='/Buttons.KeymapButton.joystyle'></Checkbox>
<Text AbsorbsInput='false' Enabled='false' Font='/Fonts.HudFont1' LocalText='Joy 1' Location='65,42' Name='J7Text' ScrollExtent='63,20' Size='63,20' TextAlignment='Center' TextAlignmentVertical='Center'>Joy 1</Text>
<Checkbox BackgroundOpacity='1.000' Location='65,42' Name='J7' ScrollExtent='64,22' Size='64,22' Style='/Buttons.KeymapButton.joystyle'></Checkbox>
<Text AbsorbsInput='false' Enabled='false' Font='/Fonts.HudFont1' LocalText='Joy 1' Location='130,42' Name='J8Text' ScrollExtent='63,20' Size='63,20' TextAlignment='Center' TextAlignmentVertical='Center'>Joy 1</Text>
<Checkbox BackgroundOpacity='1.000' Location='130,42' Name='J8' ScrollExtent='64,22' Size='64,22' Style='/Buttons.KeymapButton.joystyle'></Checkbox>
<Text AbsorbsInput='false' Enabled='false' Font='/Fonts.HudFont1' LocalText='Joy 1' Location='195,42' Name='J9Text' ScrollExtent='63,20' Size='63,20' TextAlignment='Center' TextAlignmentVertical='Center'>Joy 1</Text>
<Checkbox BackgroundOpacity='1.000' Location='195,42' Name='J9' ScrollExtent='64,22' Size='64,22' Style='/Buttons.KeymapButton.joystyle'></Checkbox>
<Text AbsorbsInput='false' Enabled='false' Font='/Fonts.HudFont1' LocalText='Joy 1' Location='260,42' Name='J10Text' ScrollExtent='63,20' Size='63,20' TextAlignment='Center' TextAlignmentVertical='Center'>Joy 1</Text>
<Checkbox BackgroundOpacity='1.000' Location='260,42' Name='J10' ScrollExtent='64,22' Size='64,22' Style='/Buttons.KeymapButton.joystyle'></Checkbox>
<Text Font='/Fonts.HudFont1' LocalText='[@JoystickShift]' Location='11,-2' Name='Name' ScrollExtent='196,15' Size='196,15'>@JoystickShift</Text>
</Page>
<Page Location='2,199' Name='POV' ScrollExtent='320,43' Size='320,43'>
<Text Font='/Fonts.HudFont1' LocalText='[@JoystickPOV]' Location='11,0' Name='Name' ScrollExtent='196,15' Size='196,15'>@JoystickPOV</Text>
<Text AbsorbsInput='false' Enabled='false' Font='/Fonts.HudFont1' LocalText='[@JoyPOVUp]' Location='0,17' Name='J1Text' ScrollExtent='63,24' Size='63,20' TextAlignment='Center' TextAlignmentVertical='Center'>@JoyPOVUp</Text>
<Checkbox BackgroundOpacity='1.000' Location='0,17' Name='J1' ScrollExtent='64,22' Size='64,22' Style='/Buttons.KeymapButton.joystyle'></Checkbox>
<Text AbsorbsInput='false' Enabled='false' Font='/Fonts.HudFont1' LocalText='[@JoyPOVDown]' Location='65,17' Name='J2Text' ScrollExtent='63,24' Size='63,20' TextAlignment='Center' TextAlignmentVertical='Center'>@JoyPOVDown</Text>
<Checkbox BackgroundOpacity='1.000' Location='65,17' Name='J2' ScrollExtent='64,22' Size='64,22' Style='/Buttons.KeymapButton.joystyle'></Checkbox>
<Text AbsorbsInput='false' Enabled='false' Font='/Fonts.HudFont1' LocalText='[@JoyPOVRight]' Location='130,17' Name='J3Text' ScrollExtent='63,24' Size='63,20' TextAlignment='Center' TextAlignmentVertical='Center'>@JoyPOVRight</Text>
<Checkbox BackgroundOpacity='1.000' Location='130,17' Name='J3' ScrollExtent='64,22' Size='64,22' Style='/Buttons.KeymapButton.joystyle'></Checkbox>
<Text AbsorbsInput='false' Enabled='false' Font='/Fonts.HudFont1' LocalText='[@JoyPOVLeft]' Location='195,17' Name='J4Text' ScrollExtent='63,24' Size='63,20' TextAlignment='Center' TextAlignmentVertical='Center'>@JoyPOVLeft</Text>
<Checkbox BackgroundOpacity='1.000' Location='195,17' Name='J4' ScrollExtent='64,22' Size='64,22' Style='/Buttons.KeymapButton.joystyle'></Checkbox>
</Page>
<Checkbox BackgroundOpacity='1.000' LocalTooltip='[@JoystickReversePilotTooltip]' Location='137,25' Name='ReversePilotChecked' ScrollExtent='285,25' Size='285,25' Style='/Buttons.OptionsCheckbox.style' Tooltip='@JoystickReversePilotTooltip'>@JoystickReversePilot</Checkbox>
<Text Font='/SmallFont' LocalText='[@JoystickSensitivity]' LocalTooltip='[@JoystickSensitivityTooltip]' Location='6,62' Name='JoystickSensitivityText' ScrollExtent='125,16' Size='125,16' TextAlignment='Right' Tooltip='@JoystickSensitivityTooltip'>@JoystickSensitivity</Text>
<Sliderbar LocalTooltip='[@JoystickSensitivityTooltip]' Location='138,53' Name='JoystickSensitivitySlider' ScrollExtent='180,30' Size='180,30' Style='/Sliderbars.Options.Style' Tooltip='@JoystickSensitivityTooltip' UpperLimit='1000' Value='463'/>
</Page>
</Page>
<ImageStyle Name='TabBorderTopStyle'>
<ImageFrame Source='ui_window_map_tab_border_00' SourceRect='8,0,24,2'/>
</ImageStyle>
<Image BackgroundOpacity='1.000' Location='744,34' Name='TabBorderTop4' PackLocation='left,top' PackLocationProp='0744/0001,0034/0001' PackSize='fixed,fixed' PackSizeProp='0002/0003,0002/0003' ScrollExtent='5,2' Size='5,2' Style='TabBorderTopStyle'/>
<Checkbox Activated='true' BackgroundOpacity='1.000' Checked='true' LocalTooltip='[@KeymapGlobalTooltip]' Location='2,5' Name='GlobalTab' OnDisableEffector='DisableEffector' PackLocation='left,top' PackLocationProp='0002/0001,0005/0001' PackSize='fixed,fixed' PackSizeProp='0002/0003,0002/0003' ScrollExtent='106,31' Size='106,31' Style='/Buttons.OptionTab.style' Tooltip='@KeymapGlobalTooltip'>@KeymapGlobal</Checkbox>
<Checkbox BackgroundOpacity='1.000' LocalTooltip='[@KeymapOverheadTooltip]' Location='108,5' Name='OverheadTab' PackLocation='left,top' PackLocationProp='0108/0001,0005/0001' PackSize='fixed,fixed' PackSizeProp='0002/0003,0002/0003' ScrollExtent='106,31' Size='106,31' Style='/Buttons.OptionTab.style' Tooltip='@KeymapOverheadTooltip'>@KeymapOverhead</Checkbox>
<Checkbox BackgroundOpacity='1.000' LocalTooltip='[@KeymapGeneralTooltip]' Location='214,5' Name='HUDTab' PackLocation='left,top' PackLocationProp='0214/0001,0005/0001' PackSize='fixed,fixed' PackSizeProp='0002/0003,0002/0003' ScrollExtent='106,31' Size='106,31' Style='/Buttons.OptionTab.style' Tooltip='@KeymapGeneralTooltip'>@KeymapGeneral</Checkbox>
<Checkbox BackgroundOpacity='1.000' LocalTooltip='[@KeymapSoldierTooltip]' Location='320,5' Name='SoldierTab' PackLocation='left,top' PackLocationProp='0320/0001,0005/0001' PackSize='fixed,fixed' PackSizeProp='0002/0003,0002/0003' ScrollExtent='106,31' Size='106,31' Style='/Buttons.OptionTab.style' Tooltip='@KeymapSoldierTooltip'>@KeymapSoldier</Checkbox>
<Checkbox BackgroundOpacity='1.000' LocalTooltip='[@KeymapVehicleTooltip]' Location='426,5' Name='VehicleTab' PackLocation='left,top' PackLocationProp='0426/0001,0005/0001' PackSize='fixed,fixed' PackSizeProp='0002/0003,0002/0003' ScrollExtent='106,31' Size='106,31' Style='/Buttons.OptionTab.style' Tooltip='@KeymapVehicleTooltip'>@KeymapVehicle</Checkbox>
<Checkbox BackgroundOpacity='1.000' LocalTooltip='[@KeymapGroundTooltip]' Location='532,5' Name='GroundTab' PackLocation='left,top' PackLocationProp='0532/0001,0005/0001' PackSize='fixed,fixed' PackSizeProp='0002/0003,0002/0003' ScrollExtent='106,31' Size='106,31' Style='/Buttons.OptionTab.style' Tooltip='@KeymapGroundTooltip'>@KeymapGround</Checkbox>
<Checkbox BackgroundOpacity='1.000' LocalTooltip='[@KeymapAirTooltip]' Location='638,5' Name='AirTab' PackLocation='left,top' PackLocationProp='0638/0001,0005/0001' PackSize='fixed,fixed' PackSizeProp='0002/0003,0002/0003' ScrollExtent='106,31' Size='106,31' Style='/Buttons.OptionTab.style' Tooltip='@KeymapAirTooltip'>@KeymapAir</Checkbox>
<Image BackgroundOpacity='1.000' Location='3,35' Name='TabBorder' PackLocation='left,top' PackLocationProp='0003/0001,0035/0001' PackSize='absolute,absolute' PackSizeProp='0012/0001,0038/0001' RStyleDefault='/WindowPanes.BigTabBorder.style' ScrollExtent='746,430' Size='746,430'/>
<Page BackgroundColor='#0000FF' Location='4,37' Name='GlobalModePage' ScrollExtent='418,426' Size='418,426'>
<Text Font='/Fonts.HudFont1' LocalText='[@KeyMapGlobalDescription]' Location='8,7' Name='Description' ScrollExtent='399,50' Size='399,50' TextAlignment='Center' TextAlignmentVertical='Center'>@KeyMapGlobalDescription</Text>
<Scrollbar Control='CommandList' Location='402,78' Name='Scroll' ScrollExtent='9,345' Size='9,345' Style='/ScrollBars.vertical.style'/>
<DataSource Name='PageData'>
<Data actionname='@GA_Help' color='#ffffff' key1='Shift + P' Localactionname='[@GA_Help]' Name='Toggle Help Page'/>
<Data actionname='@GA_Screenshot' color='#ffffff' key1='=' Localactionname='[@GA_Screenshot]' Name='Screenshot'/>
<Data actionname='@GA_EscapeClear' color='#ffffff' key1='ESC' Localactionname='[@GA_EscapeClear]' Name='Clear HUD'/>
<Data actionname='@GA_ToggleOverheadMap' color='#ffffff' key1='M' Localactionname='[@GA_ToggleOverheadMap]' Name='Toggle Overhead Map'/>
<Data actionname='@GA_OpenChat' color='#ffffff' key1='Enter' Localactionname='[@GA_OpenChat]' Name='Open Chat'/>
<Data actionname='@GA_OpenChatSlash' color='#ffffff' key1='/' key2='Num Pad /' Localactionname='[@GA_OpenChatSlash]' Name='Open Chat Slash'/>
<Data actionname='@GA_OpenChatReply' color='#ffffff' key1='Backspace' Localactionname='[@GA_OpenChatReply]' Name='Open Chat Reply'/>
<Data actionname='@GA_ChatWindowPgUp' color='#ffffff' key1='PGUP' Localactionname='[@GA_ChatWindowPgUp]' Name='Chat PGUP'/>
<Data actionname='@GA_ChatWindowPgDn' color='#ffffff' key1='PGDN' Localactionname='[@GA_ChatWindowPgDn]' Name='Chat PGDN'/>
<Data actionname='@GA_StatusWindowPgUp' color='#ffffff' key1='Shift + PGUP' Localactionname='[@GA_StatusWindowPgUp]' Name='Status PGUP'/>
<Data actionname='@GA_StatusWindowPgDn' color='#ffffff' key1='Shift + PGDN' Localactionname='[@GA_StatusWindowPgDn]' Name='Status PGDN'/>
<Data actionname='@GA_ToggleSquadList' color='#ffffff' key1='Alt' Localactionname='[@GA_ToggleSquadList]' Name='Toggle Squad List'/>
<Data actionname='@GA_Squad_1' color='#ffffff' key1='Alt + 1' Localactionname='[@GA_Squad_1]' Name='Squad Msg 1'/>
<Data actionname='@GA_Squad_2' color='#ffffff' key1='Alt + 2' Localactionname='[@GA_Squad_2]' Name='Squad Msg 2'/>
<Data actionname='@GA_Squad_3' color='#ffffff' key1='Alt + 3' Localactionname='[@GA_Squad_3]' Name='Squad Msg 3'/>
<Data actionname='@GA_Squad_4' color='#ffffff' key1='Alt + 4' Localactionname='[@GA_Squad_4]' Name='Squad Msg 4'/>
<Data actionname='@GA_Squad_5' color='#ffffff' key1='Alt + 5' Localactionname='[@GA_Squad_5]' Name='Squad Msg 5'/>
<Data actionname='@GA_Squad_6' color='#ffffff' key1='Alt + 6' Localactionname='[@GA_Squad_6]' Name='Squad Msg 6'/>
<Data actionname='@GA_Squad_7' color='#ffffff' key1='Alt + 7' Localactionname='[@GA_Squad_7]' Name='Squad Msg 7'/>
<Data actionname='@GA_Squad_8' color='#ffffff' key1='Alt + 8' Localactionname='[@GA_Squad_8]' Name='Squad Msg 8'/>
<Data actionname='@GA_Squad_9' color='#ffffff' key1='Alt + 9' Localactionname='[@GA_Squad_9]' Name='Squad Msg 9'/>
<Data actionname='@GA_Squad_0' color='#ffffff' key1='Alt + 0' Localactionname='[@GA_Squad_0]' Name='Squad Msg 10'/>
<Data actionname='@GA_VoiceMacro' color='#ffffff' key1='V' Localactionname='[@GA_VoiceMacro]' Name='Voice Macro'/>
<Data actionname='@GA_VoiceTransmit' color='#ffffff' key1='Y' Localactionname='[@GA_VoiceTransmit]' Name='Voice Transmit'/>
</DataSource>
<Listbox DataSource='PageData' Location='1,79' Name='CommandList' RowTemplate='CommandListTemplate' ScrollExtent='146,600' ScrollLocation='0,255' SelectedItemIndex='6' Size='146,345' Style='/Listboxes.Clear.style'/>
<Listbox DataSource='PageData' Location='155,79' Name='KeyList1' RowTemplate='KeyList1Template' ScrollExtent='120,600' SelectedItemIndex='6' Size='120,345' Style='/Listboxes.Keymap.style'/>
<Listbox DataSource='PageData' Location='280,79' Name='Keylist2' RowTemplate='KeyList2Template' ScrollExtent='120,600' SelectedItemIndex='7' Size='120,345' Style='/Listboxes.Keymap.style'/>
</Page>
<Page BackgroundColor='#0000FF' Location='4,37' Name='OverheadModePage' ScrollExtent='418,426' Size='418,426' Visible='false'>
<Text Font='/Fonts.HudFont1' LocalText='[@KeyMapOverheadDescription]' Location='8,7' Name='Description' ScrollExtent='399,50' Size='399,50' TextAlignment='Center' TextAlignmentVertical='Center'>@KeyMapOverheadDescription</Text>
<Scrollbar Control='CommandList' Location='402,78' Name='Scroll' ScrollExtent='9,345' Size='9,345' Style='/ScrollBars.vertical.style'/>
<DataSource Name='PageData'>
<Data actionname='@GA_ZoomIn' color='#ffffff' key1='Z' key2='Num Pad +' key3='Shift + =' Localactionname='[@GA_ZoomIn]' Name='Zoom In'/>
<Data actionname='@GA_ZoomOut' color='#ffffff' key1='X' key2='Num Pad -' key3='Shift + -' Localactionname='[@GA_ZoomOut]' Name='Zoom Out'/>
<Data actionname='@GA_CenterOnPlayer' color='#ffffff' key1='C' Localactionname='[@GA_CenterOnPlayer]' Name='Center On Player'/>
<Data actionname='@GA_GlobalView' color='#ffffff' key1='G' Localactionname='[@GA_GlobalView]' Name='Global View'/>
<Data actionname='@GA_ToggleBattleplans' color='#ffffff' key1='B' Localactionname='[@GA_ToggleBattleplans]' Name='Toggle Battleplans'/>
<Data actionname='@GA_ToggleBuildingState' color='#ffffff' key1='F' Localactionname='[@GA_ToggleBuildingState]' Name='Toggle Building State'/>
<Data actionname='@GA_ToggleEquipment' color='#ffffff' key1='E' Localactionname='[@GA_ToggleEquipment]' Name='Toggle Equipment'/>
<Data actionname='@GA_ToggleHotSpots' color='#ffffff' key1='H' Localactionname='[@GA_ToggleHotSpots]' Name='Toggle Hot Spots'/>
<Data actionname='@GA_ToggleRsrcFacilityInfo' color='#ffffff' key1='R' Localactionname='[@GA_ToggleRsrcFacilityInfo]' Name='Toggle Rsrc Facility Info'/>
<Data actionname='@GA_ToggleSOI' color='#ffffff' key1='S' Localactionname='[@GA_ToggleSOI]' Name='Toggle SOI'/>
<Data actionname='@GA_ToggleSquad' color='#ffffff' key1='Q' Localactionname='[@GA_ToggleSquad]' Name='Toggle Squad'/>
<Data actionname='@GA_ToggleText' color='#ffffff' key1='T' Localactionname='[@GA_ToggleText]' Name='Toggle Text'/>
<Data actionname='@GA_ToggleWeather' color='#ffffff' key1='T' Localactionname='[@GA_ToggleWeather]' Name='Toggle Weather'/>
</DataSource>
<Listbox DataSource='PageData' Location='1,79' Name='CommandList' RowTemplate='CommandListTemplate' ScrollExtent='146,345' Size='146,345' Style='/Listboxes.Clear.style'/>
<Listbox DataSource='PageData' Location='155,79' Name='KeyList1' RowTemplate='KeyList1Template' ScrollExtent='120,345' Size='120,345' Style='/Listboxes.Keymap.style'/>
<Listbox DataSource='PageData' Location='280,79' Name='Keylist2' RowTemplate='KeyList2Template' ScrollExtent='120,345' Size='120,345' Style='/Listboxes.Keymap.style'/>
</Page>
<Page Location='4,37' Name='HUDModePage' ScrollExtent='418,426' Size='418,426' Visible='false'>
<Text Font='/Fonts.HudFont1' LocalText='[@KeyMapHUDDescription]' Location='8,7' Name='Description' ScrollExtent='399,50' Size='399,50' TextAlignment='Center' TextAlignmentVertical='Center'>@KeyMapHUDDescription</Text>
<DataSource Name='PageData'>
<Data actionname='@GA_Autorun' color='#ffffff' key1='Q' Localactionname='[@GA_Autorun]' Name='Autorun'/>
<Data actionname='@GA_WeaponFire' color='#ffffff' key1='Left Mouse Button' Localactionname='[@WeaponFire]' Name='Weapon Fire' opacity1='1'/>
<Data actionname='@GA_ChangeFireMode' color='#ffffff' key1='Right Mouse Button' Localactionname='[@ChangeFireMode]' Name='Change Fire Mode'/>
<Data actionname='@GA_ChangeAmmo' color='#ffffff' key1='X' Localactionname='[@GA_ChangeAmmo]' Name='Change Ammunition'/>
<Data actionname='@GA_Reload' color='#ffffff' key1='R' Localactionname='[@Reload]' Name='Reload'/>
<Data actionname='@GA_UseObject' color='#ffffff' key1='G' Localactionname='[@GA_UseObject]' Name='Use Item'/>
<Data actionname='@GA_ToggleThirdPersonCamera' color='#ffffff' key1='X' Localactionname='[@GA_ToggleThirdPersonCamera]' Name='Toggle Third Person Camera'/>
<Data actionname='@GA_ToggleInventory' color='#ffffff' key1='I' Localactionname='[@ToggleInventory]' Name='Toggle Inventory'/>
<Data actionname='@GA_Zoom' color='#ffffff' key1='Z' Localactionname='[@Zoom]' Name='Zoom'/>
<Data actionname='@GA_SmoothZoom' color='#ffffff' key1='O' Localactionname='[@SmoothZoom]' Name='Smooth Zoom'/>
<Data actionname='@GA_RadarIncrease' color='#ffffff' key1='M' Localactionname='[@GA_RadarIncrease]' Name='Radar Increase'/>
<Data actionname='@GA_RadarDecrease' color='#ffffff' key1='M' Localactionname='[@GA_RadarDecrease]' Name='Radar Decrease'/>
<Data actionname='@GA_ToggleMouseLook' color='#ffffff' key1='TAB' Localactionname='[@GA_ToggleMouseLook]' Name='Toggle Mouse Look'/>
<Data actionname='@GA_ToggleCharacterPane' color='#ffffff' key1='O' Localactionname='[@ToggleCharacterPane]' Name='Toggle Character Pane'/>
<Data actionname='@GA_ToggleChatPane' color='#ffffff' key1='O' Localactionname='[@GA_ToggleChatPane]' Name='Toggle Chat Pane'/>
<Data actionname='@GA_ToggleManagementPane' color='#ffffff' key1='O' Localactionname='[@GA_ToggleManagementPane]' Name='Toggle Management Pane'/>
<Data actionname='@GA_ToggleOutfitPane' color='#ffffff' key1='O' Localactionname='[@GA_ToggleOutfitPane]' Name='Toggle Outfit Pane'/>
<Data actionname='@GA_TogglePlayerPane' color='#ffffff' key1='P' Localactionname='[@TogglePlayerPane]' Name='Toggle Player Pane'/>
<Data actionname='@GA_ToggleProximityMap' color='#ffffff' key1='O' Localactionname='[@GA_ToggleProximityMap]' Name='Toggle Proximity Map'/>
<Data actionname='@GA_ToggleVehiclePane' color='#ffffff' key1='O' Localactionname='[@GA_ToggleVehiclePane]' Name='Toggle Vehicle Pane'/>
<Data actionname='@GA_ToggleHelp' color='#ffffff' key1='H' Localactionname='[@GA_ToggleHelp]' Name='Toggle Help'/>
<Data actionname='@GA_Cycle_Character_Names' color='#ffffff' key1='N' Localactionname='[@GA_Cycle_Character_Names]' Name='Cycle Character Name'/>
<Data actionname='@GA_StealthSuit' color='#ffffff' key1='K' Localactionname='[@GA_StealthSuit]' Name='Toggle Stealth'/>
<Data actionname='@GA_UseQuickslot1' color='#ffffff' key1='F1' Localactionname='[@GA_UseQuickslot1]' Name='Use Quickslot 1'/>
<Data actionname='@GA_UseQuickslot2' color='#ffffff' key1='F2' Localactionname='[@GA_UseQuickslot2]' Name='Use Quickslot 2'/>
<Data actionname='@GA_UseQuickslot3' color='#ffffff' key1='F3' Localactionname='[@GA_UseQuickslot3]' Name='Use Quickslot 3'/>
<Data actionname='@GA_UseQuickslot4' color='#ffffff' key1='F4' Localactionname='[@GA_UseQuickslot4]' Name='Use Quickslot 4'/>
<Data actionname='@GA_UseQuickslot5' color='#ffffff' key1='F5' Localactionname='[@GA_UseQuickslot5]' Name='Use Quickslot 5'/>
<Data actionname='@GA_UseQuickslot6' color='#ffffff' key1='F6' Localactionname='[@GA_UseQuickslot6]' Name='Use Quickslot 6'/>
<Data actionname='@GA_UseQuickslot7' color='#ffffff' key1='F7' Localactionname='[@GA_UseQuickslot7]' Name='Use Quickslot 7'/>
<Data actionname='@GA_UseQuickslot8' color='#ffffff' key1='F8' Localactionname='[@GA_UseQuickslot8]' Name='Use Quickslot 8'/>
<Data actionname='@GA_RaiseCamera' color='#ffffff' key1='Page Up' key2='Num Pad 9' Localactionname='[@RaiseCamera]' Name='Raise Camera'/>
<Data actionname='@GA_LowerCamera' color='#ffffff' key1='Page Down' key2='Num Pad 3' Localactionname='[@LowerCamera]' Name='Lower Camera'/>
<Data actionname='@GA_MoveCameraIn' color='#ffffff' key1='Num Pad +' Localactionname='[@MoveCameraIn]' Name='Move Camera In'/>
<Data actionname='@GA_MoveCameraOut' color='#ffffff' key1='Num Pad -' Localactionname='[@MoveCameraOut]' Name='Move Camera Out'/>
<Data actionname='@GA_PanCameraLeft' color='#ffffff' key1='Num Pad 4' Localactionname='[@GA_PanCameraLeft]' Name='Pan Camera Left'/>
<Data actionname='@GA_PanCameraRight' color='#ffffff' key1='Num Pad 6' Localactionname='[@GA_PanCameraRight]' Name='Pan Camera Right'/>
</DataSource>
<Listbox DataSource='PageData' Location='1,79' Name='CommandList' RowTemplate='CommandListTemplate' ScrollExtent='146,925' SelectedItemIndex='13' Size='146,345' Style='/Listboxes.Clear.style'/>
<Listbox DataSource='PageData' Location='155,79' Name='KeyList1' RowTemplate='KeyList1Template' ScrollExtent='120,925' SelectedItemIndex='26' Size='120,345' Style='/Listboxes.Keymap.style'/>
<Listbox DataSource='PageData' Location='280,79' Name='Keylist2' RowTemplate='KeyList2Template' ScrollExtent='120,925' SelectedItemIndex='0' Size='120,345' Style='/Listboxes.Keymap.style'/>
<Scrollbar Control='CommandList' Location='402,78' Name='Scroll' ScrollExtent='9,345' Size='9,345' Style='/ScrollBars.vertical.style'/>
</Page>
<Page Location='4,37' Name='SoldierModePage' ScrollExtent='418,426' Size='418,426' Visible='false'>
<Text Font='/Fonts.HudFont1' LocalText='[@KeyMapSoldierDescription]' Location='8,7' Name='Description' ScrollExtent='399,50' Size='399,50' TextAlignment='Center' TextAlignmentVertical='Center'>@KeyMapSoldierDescription</Text>
<DataSource Name='PageData'>
<Data actionname='@GA_Forward' color='#ffffff' key1='W' key2='Up Arrow' key3='Num Pad 8' Localactionname='[@GA_Forward]' Name='Forward'/>
<Data actionname='@GA_Backward' color='#ffffff' key1='S' key2='Down Arrow' key3='Num Pad 2' Localactionname='[@GA_Backward]' Name='Backward'/>
<Data actionname='@GA_StrafeLeft' color='#ffffff' key1='A' Localactionname='[@GA_StrafeLeft]' Name='Strafe Left'/>
<Data actionname='@GA_StrafeRight' color='#ffffff' key1='D' Localactionname='[@GA_StrafeRight]' Name='Strafe Right'/>
<Data actionname='@GA_RunModifier' color='#ffffff' key1='Shift' Localactionname='[@GA_RunModifier]' Name='Run Modifier'/>
<Data actionname='@GA_TurnLeft' color='#ffffff' key1='Left Arrow' Localactionname='[@GA_TurnLeft]' Name='Turn Left'/>
<Data actionname='@GA_TurnRight' color='#ffffff' key1='Right Arrow' Localactionname='[@GA_TurnRight]' Name='Turn Right'/>
<Data actionname='@GA_Crouch' color='#ffffff' key1='C' key2='Ctrl' Localactionname='[@GA_Crouch]' Name='Crouch'/>
<Data actionname='@GA_ToggleCrouch' color='#ffffff' Localactionname='[@GA_ToggleCrouch]' Name='Toggle Crouch'/>
<Data actionname='@GA_Jump' color='#ffffff' key1='Space' Localactionname='[@GA_Jump]' Name='Jump'/>
<Data actionname='@GA_UseRightBackHolster' color='#ffffff' key1='1' Localactionname='[@GA_UseRightBackHolster]' Name='Use Right Back Holster'/>
<Data actionname='@GA_UseRightHipHolster' color='#ffffff' key1='2' Localactionname='[@GA_UseRightHipHolster]' Name='Use Right Hip Holster'/>
<Data actionname='@GA_UseLeftBackHolster' color='#ffffff' key1='3' Localactionname='[@GA_UseLeftBackHolster]' Name='Use Left Back Holster'/>
<Data actionname='@GA_UseLeftHipHolster' color='#ffffff' key1='4' Localactionname='[@GA_UseLeftHipHolster]' Name='Use Left Hip Holster'/>
<Data actionname='@GA_UseKnifeHolster' color='#ffffff' key1='5' Localactionname='[@GA_UseKnifeHolster]' Name='Use Knife Holster'/>
</DataSource>
<Listbox DataSource='PageData' Location='1,79' Name='CommandList' RowTemplate='CommandListTemplate' ScrollExtent='146,375' Size='146,345' Style='/Listboxes.Clear.style'/>
<Listbox DataSource='PageData' Location='155,79' Name='KeyList1' RowTemplate='KeyList1Template' ScrollExtent='120,375' Size='120,345' Style='/Listboxes.Keymap.style'/>
<Listbox DataSource='PageData' Location='280,79' Name='Keylist2' RowTemplate='KeyList2Template' ScrollExtent='120,375' Size='120,345' Style='/Listboxes.Keymap.style'/>
<Scrollbar Control='CommandList' Location='402,78' Name='Scroll' ScrollExtent='9,345' Size='9,345' Style='/ScrollBars.vertical.style'/>
</Page>
<Page Location='4,37' Name='VehicleModePage' ScrollExtent='418,426' Size='418,426' Visible='false'>
<Text Font='/Fonts.HudFont1' LocalText='[@KeyMapVehicleDescription]' Location='8,7' Name='Description' ScrollExtent='399,50' Size='399,50' TextAlignment='Center' TextAlignmentVertical='Center'>@KeyMapVehicleDescription</Text>
<Listbox DataSource='PageData' Location='1,79' Name='CommandList' RowTemplate='CommandListTemplate' ScrollExtent='146,375' Size='146,345' Style='/Listboxes.Clear.style'/>
<Listbox DataSource='PageData' Location='155,79' Name='KeyList1' RowTemplate='KeyList1Template' ScrollExtent='120,375' Size='120,345' Style='/Listboxes.Keymap.style'/>
<Listbox DataSource='PageData' Location='280,79' Name='Keylist2' RowTemplate='KeyList2Template' ScrollExtent='120,375' Size='120,345' Style='/Listboxes.Keymap.style'/>
<Scrollbar Control='CommandList' Location='402,78' Name='Scroll' ScrollExtent='9,345' Size='9,345' Style='/ScrollBars.vertical.style'/>
<DataSource Name='PageData'>
<Data actionname='@GA_0PercentPower' color='#ffffff' key1='1' key2='Num Pad 1' Localactionname='[@GA_0PercentPower]' Name='Cruise 0 Percent Power'/>
<Data actionname='@GA_10PercentPower' color='#ffffff' key1='1' key2='Num Pad 1' Localactionname='[@GA_10PercentPower]' Name='Cruise 10 Percent Power'/>
<Data actionname='@GA_20PercentPower' color='#ffffff' key1='2' key2='Num Pad 2' Localactionname='[@GA_20PercentPower]' Name='Cruise 20 Percent Power'/>
<Data actionname='@GA_30PercentPower' color='#ffffff' key1='3' key2='Num Pad 3' Localactionname='[@GA_30PercentPower]' Name='Cruise 30 Percent Power'/>
<Data actionname='@GA_40PercentPower' color='#ffffff' key1='4' key2='Num Pad 4' Localactionname='[@GA_40PercentPower]' Name='Cruise 40 Percent Power'/>
<Data actionname='@GA_50PercentPower' color='#ffffff' key1='5' key2='Num Pad 5' Localactionname='[@GA_50PercentPower]' Name='Cruise 50 Percent Power'/>
<Data actionname='@GA_60PercentPower' color='#ffffff' key1='6' key2='Num Pad 6' Localactionname='[@GA_60PercentPower]' Name='Cruise 60 Percent Power'/>
<Data actionname='@GA_70PercentPower' color='#ffffff' key1='7' key2='Num Pad 7' Localactionname='[@GA_70PercentPower]' Name='Cruise 70 Percent Power'/>
<Data actionname='@GA_80PercentPower' color='#ffffff' key1='8' key2='Num Pad 8' Localactionname='[@GA_80PercentPower]' Name='Cruise 80 Percent Power'/>
<Data actionname='@GA_90PercentPower' color='#ffffff' key1='9' key2='Num Pad 9' Localactionname='[@GA_90PercentPower]' Name='Cruise 90 Percent Power'/>
<Data actionname='@GA_100PercentPower' color='#ffffff' key1='0' key2='Num Pad 0' Localactionname='[@GA_100PercentPower]' Name='Cruise 100 Percent Power'/>
<Data actionname='@GA_IncrementPower' color='#ffffff' key1='.' Localactionname='[@GA_IncrementPower]' Name='Cruise Increase Power'/>
<Data actionname='@GA_DecrementPower' color='#ffffff' key1=',' Localactionname='[@GA_DecrementPower]' Name='Cruise Decrease Power'/>
<Data actionname='@GA_BailVehicle' color='#ffffff' key1='Alt+G' Localactionname='[@GA_BailVehicle]' Name='Bail Vehicle'/>
<Data actionname='@GA_ResetControls' color='#ffffff' key1='R' Localactionname='[@GA_ResetControls]' Name='Reset Controls'/>
</DataSource>
</Page>
<Page Location='4,37' Name='GroundModePage' ScrollExtent='418,426' Size='418,426' Visible='false'>
<Text Font='/Fonts.HudFont1' LocalText='[@KeyMapGroundDescription]' Location='8,7' Name='Description' ScrollExtent='399,50' Size='399,50' TextAlignment='Center' TextAlignmentVertical='Center'>@KeyMapGroundDescription</Text>
<Listbox DataSource='PageData' Location='1,79' Name='CommandList' RowTemplate='CommandListTemplate' ScrollExtent='146,345' Size='146,345' Style='/Listboxes.Clear.style'/>
<Listbox DataSource='PageData' Location='155,79' Name='KeyList1' RowTemplate='KeyList1Template' ScrollExtent='120,345' Size='120,345' Style='/Listboxes.Keymap.style'/>
<Listbox DataSource='PageData' Location='280,79' Name='Keylist2' RowTemplate='KeyList2Template' ScrollExtent='120,345' Size='120,345' Style='/Listboxes.Keymap.style'/>
<Scrollbar Control='CommandList' Location='402,78' Name='Scroll' ScrollExtent='9,345' Size='9,345' Style='/ScrollBars.vertical.style'/>
<DataSource Name='PageData'>
<Data actionname='@GA_Forward' color='#ffffff' key1='W' Localactionname='[@GA_Forward]' Name='Forward'/>
<Data actionname='@GA_Backward' color='#ffffff' key1='S' Localactionname='[@GA_Backward]' Name='Backward'/>
<Data actionname='@GA_TurnLeft' color='#ffffff' key1='A' key2='Left Arrow' Localactionname='[@GA_TurnLeft]' Name='Turn Left'/>
<Data actionname='@GA_TurnRight' color='#ffffff' key1='D' key2='Right Arrow' Localactionname='[@GA_TurnRight]' Name='Turn Right'/>
<Data actionname='@GA_Brake' color='#ffffff' key1='Space' Localactionname='[@GA_Brake]' Name='Brake'/>
</DataSource>
</Page>
<Page Location='4,37' Name='AirModePage' ScrollExtent='418,426' Size='418,426' Visible='false'>
<Text Font='/Fonts.HudFont1' LocalText='[@KeyMapAirVehicleDescription]' Location='8,7' Name='Description' ScrollExtent='399,50' Size='399,50' TextAlignment='Center' TextAlignmentVertical='Center'>@KeyMapAirVehicleDescription</Text>
<Listbox DataSource='PageData' Location='1,79' Name='CommandList' RowTemplate='CommandListTemplate' ScrollExtent='146,345' Size='146,345' Style='/Listboxes.Clear.style'/>
<Listbox DataSource='PageData' Location='155,79' Name='KeyList1' RowTemplate='KeyList1Template' ScrollExtent='120,345' Size='120,345' Style='/Listboxes.Keymap.style'/>
<Listbox DataSource='PageData' Location='280,79' Name='Keylist2' RowTemplate='KeyList2Template' ScrollExtent='120,345' Size='120,345' Style='/Listboxes.Keymap.style'/>
<Scrollbar Control='CommandList' Location='402,78' Name='Scroll' ScrollExtent='9,345' Size='9,345' Style='/ScrollBars.vertical.style'/>
<DataSource Name='PageData'>
<Data actionname='@GA_Elevate' color='#ffffff' key1='E' Localactionname='[@GA_Elevate]' Name='Flight Elevate'/>
<Data actionname='@GA_Lower' color='#ffffff' key1='C' Localactionname='[@GA_Lower]' Name='Flight Lower'/>
<Data actionname='@GA_Forward' color='#ffffff' key1='W' Localactionname='[@GA_Forward]' Name='Forward'/>
<Data actionname='@GA_Backward' color='#ffffff' key1='S' Localactionname='[@GA_Backward]' Name='Backward'/>
<Data actionname='@GA_StrafeLeft' color='#ffffff' key1='A' key2='Left Arrow' Localactionname='[@GA_StrafeLeft]' Name='Strafe Left'/>
<Data actionname='@GA_StrafeRight' color='#ffffff' key1='D' key2='Right Arrow' Localactionname='[@GA_StrafeRight]' Name='Strafe Right'/>
<Data actionname='@GA_Afterburner' color='#ffffff' key1='Space Bar' Localactionname='[@GA_Afterburner]' Name='Flight Afterburners'/>
</DataSource>
</Page>
</Page>
<Page Location='22,69' Name='VideoOptionsPage' navbar.visible='true' OnHide='Parent.NavBar.Visible = false' OnShow='Parent.NavBar.Visible = true' PackLocation='Center,Center' PackLocationProp='-378/0001,-231/0001' ScrollExtent='758,468' Size='758,468'>
<Text Font='/Fonts.DefaultFont' GetsInput='false' LocalText='(Video settings will take effect next time you start Planetside)' Location='6,435' Name='WarningText' ScrollExtent='737,25' Size='737,25' TextAlignment='Center'>(Video settings will take effect next time you start Planetside)</Text>
<Page Location='6,39' Name='GeneralVideo' OnHide='Parent.NavBar.Visible = false' OnShow='Parent.NavBar.Visible = true' PackLocation='Center,Center' PackLocationProp='-373/0001,-195/0001' ScrollExtent='739,423' Size='739,423'>
<Template Name='Row Template' Size='250,20'>\<text font = \'/Fonts.DefaultFont\' location = \'5,-1\' size = \'250,20\'\>
$Name$
\</text\></Template>
<Text AbsorbsInput='false' Enabled='false' Font='/Fonts.HudFont1' LocalText='[@VideoGammaFullScreen]' Location='549,7' Name='VideoGammaNotice' ScrollExtent='174,73' Size='174,73' TextAlignment='Center' TextAlignmentVertical='Center'>@VideoGammaFullScreen</Text>
<Text Font='/Fonts.HudFont1' LocalText='[@VideoGammaContrast]' LocalTooltip='[@VideoGammaContrastTooltip]' Location='379,50' Name='VideoGammaContrastText' ScrollExtent='162,25' Size='162,25' TextAlignment='Right' TextAlignmentVertical='Center' Tooltip='@VideoGammaContrastTooltip'>@VideoGammaContrast</Text>
<Sliderbar LocalTooltip='[@VideoGammaContrastTooltip]' Location='549,47' Name='VideoGammaContrast' ScrollExtent='173,25' Size='173,25' Style='/Sliderbars.Options.Style' Tooltip='@VideoGammaContrastTooltip' UpperLimit='1000' Value='1000'/>
<Text Font='/Fonts.HudFont1' LocalText='[@VideoGammaBrightness]' LocalTooltip='[@VideoGammaBrightness]' Location='376,13' Name='VideoGammaBrightnessText' ScrollExtent='162,25' Size='162,25' TextAlignment='Right' TextAlignmentVertical='Center' Tooltip='@VideoGammaBrightness'>@VideoGammaBrightness</Text>
<Sliderbar LocalTooltip='[@VideoGammaBrightnessTooltip]' Location='549,10' Name='VideoGammaBrightness' ScrollExtent='173,25' Size='173,25' Style='/Sliderbars.Options.Style' Tooltip='@VideoGammaBrightnessTooltip' UpperLimit='1000' Value='428'/>
<Text Font='/Fonts.HudFont1' LocalText='[@VideoScreenResolutionText]' LocalTooltip='[@VideoScreenResolutionTooltip]' Location='2,51' Name='VideolResolutionText' ScrollExtent='114,25' Size='114,25' TextAlignment='Right' TextAlignmentVertical='Center' Tooltip='@VideoScreenResolutionTooltip'>@VideoScreenResolutionText</Text>
<Dropdownbox DataSource='/DataSources.VideoResolutionDataSource' LocalTooltip='[@VideoScreenResolutionTooltip]' Location='119,48' Name='VideoResolution' RowTemplate='Row Template' ScrollExtent='248,29' SelectedItemIndex='2' Size='248,29' Style='/Dropdowns.HudPane.style' Tooltip='@VideoScreenResolutionTooltip'/>
<Checkbox BackgroundOpacity='1.000' LocalTooltip='[@VideoFullScreenTooltip]' Location='119,15' Name='FullScreen' ScrollExtent='248,25' Size='248,25' Style='/Buttons.OptionsCheckbox.style' Tooltip='@VideoFullScreenTooltip'>@VideoFullScreen</Checkbox>
<Text Font='/Fonts.HudFont1' LocalText='[@VideoQuality]' LocalTooltip='[@VideoQualityTooltip]' Location='144,110' Name='VideoQualityText' ScrollExtent='162,25' Size='162,25' TextAlignment='Right' TextAlignmentVertical='Center' Tooltip='@VideoQualityTooltip'>@VideoQuality</Text>
<Dropdownbox DataSource='/DataSources.VideoQualityDataSource' LocalTooltip='[@VideoQualityTooltip]' Location='313,108' Name='VideoQuality' RowTemplate='Row Template' ScrollExtent='250,29' Size='250,29' Style='/Dropdowns.HudPane.style' Tooltip='@VideoQualityTooltip'/>
<Text Font='/Fonts.HudFont1' LocalText='[@VideoColorText]' LocalTooltip='[@VideoColorTooltip]' Location='-4,191' Name='VideoColorText' ScrollExtent='117,25' Size='117,25' TextAlignment='Right' TextAlignmentVertical='Center' Tooltip='@VideoColorTooltip'>@VideoColorText</Text>
<Dropdownbox DataSource='/DataSources.VideoColorDataSource' LocalTooltip='[@VideoColorTooltip]' Location='121,188' Name='VideoColor' RowTemplate='Row Template' ScrollExtent='250,29' Size='250,29' Style='/Dropdowns.HudPane.style' Tooltip='@VideoColorTooltip'/>
<Text Font='/Fonts.HudFont1' LocalText='[@VideoParticleText]' LocalTooltip='[@VideoParticleTooltip]' Location='323,191' Name='VideoParticleText' ScrollExtent='145,25' Size='145,25' TextAlignment='Right' TextAlignmentVertical='Center' Tooltip='@VideoParticleTooltip'>@VideoParticleText</Text>
<Dropdownbox DataSource='/DataSources.VideoParticleDataSource' LocalTooltip='[@VideoParticleTooltip]' Location='474,191' Name='VideoParticle' RowTemplate='Row Template' ScrollExtent='250,29' Size='250,29' Style='/Dropdowns.HudPane.style' Tooltip='@VideoParticleTooltip'/>
<Text Font='/Fonts.HudFont1' LocalText='[@VideoTextureText]' LocalTooltip='[@VideoTextureTooltip]' Location='-4,233' Name='VideoTextureQualityText' ScrollExtent='117,25' Size='117,25' TextAlignment='Right' TextAlignmentVertical='Center' Tooltip='@VideoTextureTooltip'>@VideoTextureText</Text>
<Dropdownbox DataSource='/DataSources.VideoTextureDataSource' LocalTooltip='[@VideoTextureTooltip]' Location='121,230' Name='VideoTextureQuality' RowTemplate='Row Template' ScrollExtent='250,29' SelectedItemIndex='2' Size='250,29' Style='/Dropdowns.HudPane.style' Tooltip='@VideoTextureTooltip'/>
<Text Font='/Fonts.HudFont1' LocalText='[@VideoFloraText]' LocalTooltip='[@VideoFloraTooltip]' Location='323,233' Name='VideoFloraText' ScrollExtent='145,25' Size='145,25' TextAlignment='Right' TextAlignmentVertical='Center' Tooltip='@VideoFloraTooltip'>@VideoFloraText</Text>
<Dropdownbox DataSource='/DataSources.VideoFloraDataSource' LocalTooltip='[@VideoFloraTooltip]' Location='474,230' Name='VideoFlora' RowTemplate='Row Template' ScrollExtent='250,29' SelectedItemIndex='2' Size='250,29' Style='/Dropdowns.HudPane.style' Tooltip='@VideoFloraTooltip'/>
<Checkbox Activated='true' BackgroundOpacity='1.000' Checked='true' LocalTooltip='[@VideoLODTooltip]' Location='122,275' Name='VideoLODCheck' ScrollExtent='269,25' Size='269,25' Style='/Buttons.OptionsCheckbox.style' Tooltip='@VideoLODTooltip'>@VideoLOD</Checkbox>
<Checkbox Activated='true' BackgroundOpacity='1.000' Checked='true' LocalTooltip='[@VideoDetailWebTooltip]' Location='121,305' Name='VideoDetailWebCheck' ScrollExtent='269,25' Size='269,25' Style='/Buttons.OptionsCheckbox.style' Tooltip='@VideoDetailWebTooltip'>@VideoDetailWeb</Checkbox>
<Checkbox Activated='true' BackgroundOpacity='1.000' Checked='true' LocalTooltip='[@VideoWarpgateTooltip]' Location='121,335' Name='VideoWarpgateCheck' ScrollExtent='269,25' Size='269,25' Style='/Buttons.OptionsCheckbox.style' Tooltip='@VideoWarpgateTooltip'>@VideoWarpgateCheck</Checkbox>
<Checkbox Activated='true' BackgroundOpacity='1.000' Checked='true' LocalTooltip='[@VideoDecalTooltip]' Location='122,365' Name='VideoDecalCheck' ScrollExtent='269,25' Size='269,25' Style='/Buttons.OptionsCheckbox.style' Tooltip='@VideoDecalTooltip'>@VideoDecalCheck</Checkbox>
<Checkbox Activated='true' BackgroundOpacity='1.000' Checked='true' LocalTooltip='[@VideoShadowTooltip]' Location='474,275' Name='VideoShadowCheck' ScrollExtent='249,25' Size='249,25' Style='/Buttons.OptionsCheckbox.style' Tooltip='@VideoShadowTooltip'>@VideoShadow</Checkbox>
<Checkbox Activated='true' BackgroundOpacity='1.000' Checked='true' LocalTooltip='[@VideoWeatherTooltip]' Location='474,305' Name='VideoWeatherCheck' ScrollExtent='249,25' Size='249,25' Style='/Buttons.OptionsCheckbox.style' Tooltip='@VideoWeatherTooltip'>@VideoWeatherCheck</Checkbox>
<Checkbox Activated='true' BackgroundOpacity='1.000' Checked='true' LocalTooltip='[@VideoSKyTooltip]' Location='474,335' Name='VideoSkyCheck' ScrollExtent='249,25' Size='249,25' Style='/Buttons.OptionsCheckbox.style' Tooltip='@VideoSKyTooltip'>@VideoSkyCheck</Checkbox>
<Sliderbar LocalTooltip='[@VideoGammaTooltip]' Location='315,151' Name='VideoYon' ScrollExtent='173,25' Size='173,25' Style='/Sliderbars.Options.Style' Tooltip='@VideoGammaTooltip' UpperLimit='1000' Value='428'/>
<Text Font='/Fonts.HudFont1' LocalText='[@VideoYon]' LocalTooltip='[@VideoYonTooltip]' Location='145,154' Name='VideoYonText' ScrollExtent='162,25' Size='162,25' TextAlignment='Right' TextAlignmentVertical='Center' Tooltip='@VideoYonTooltip'>@VideoYon</Text>
<Rectangle AbsorbsInput='false' Color='#00F2C9' Location='6,144' Name='QualityRect' Opacity='0.750' ScrollExtent='728,249' Size='728,249'/>
</Page>
<Page Location='6,39' Name='AdvancedVideo' OnHide='Parent.NavBar.Visible = false' OnShow='Parent.NavBar.Visible = true' PackLocation='Center,Center' PackLocationProp='-373/0001,-195/0001' ScrollExtent='739,423' Size='739,423' Visible='false'>
<Text AbsorbsInput='false' Enabled='false' Font='/Fonts.HudFont1' LocalText='[@VideoGammaFullScreen]' Location='74,38' Name='VideoGammaNotice' ScrollExtent='174,23' Size='174,23' TextAlignment='Center' TextAlignmentVertical='Center'>@VideoGammaFullScreen</Text>
<Checkbox Activated='true' BackgroundOpacity='1.000' Checked='true' LocalTooltip='[@VideoSyncTooltip]' Location='74,64' Name='VideoSyncCheck' ScrollExtent='269,25' Size='269,25' Style='/Buttons.OptionsCheckbox.style' Tooltip='@VideoSyncTooltip'>@VideoSync</Checkbox>
<Checkbox Activated='true' BackgroundOpacity='1.000' Checked='true' LocalTooltip='[@VideoTripleBufferTooltip]' Location='74,94' Name='VideoTripleCheck' ScrollExtent='269,25' Size='269,25' Style='/Buttons.OptionsCheckbox.style' Tooltip='@VideoTripleBufferTooltip'>@VideoTripleBuffer</Checkbox>
<Checkbox Activated='true' BackgroundOpacity='1.000' Checked='true' LocalTooltip='[@VideoTextureTypeTooltip]' Location='74,13' Name='VideoTextureTypeCheck' ScrollExtent='269,25' Size='269,25' Style='/Buttons.OptionsCheckbox.style' Tooltip='@VideoTextureTypeTooltip'>@VideoTextureType</Checkbox>
<Text Font='/Fonts.HudFont1' LocalText='[@VideoPreload]' Location='306,12' Name='VideoTexturePreloadText' ScrollExtent='162,25' Size='162,25' TextAlignment='Right' TextAlignmentVertical='Center'>@VideoPreload</Text>
<Dropdownbox DataSource='/DataSources.VideoPreloadDataSource' LocalTooltip='[@VideoPreloadTooltip]' Location='475,10' Name='VideoTexturePreload' RowTemplate='Row Template' ScrollExtent='250,29' Size='250,29' Style='/Dropdowns.HudPane.style' Tooltip='@VideoPreloadTooltip'/>
<Rectangle AbsorbsInput='false' Color='#00F2C9' Location='6,134' Name='TextureRect' Opacity='0.750' ScrollExtent='728,258' Size='728,258'/>
<Checkbox Activated='true' BackgroundOpacity='1.000' Checked='true' LocalTooltip='[@VideoTextureAllTooltip]' Location='324,139' Name='TextureAll' ScrollExtent='269,25' Size='269,25' Style='/Buttons.OptionsCheckbox.style' Tooltip='@VideoTextureAllTooltip'>@VideoTextureAll</Checkbox>
<Text Font='/Fonts.HudFont1' LocalText='[@VideoTextureText]' Location='44,141' Name='TextureText' ScrollExtent='262,25' Size='262,25' TextAlignment='Right' TextAlignmentVertical='Center'>@VideoTextureText</Text>
<Checkbox Activated='true' BackgroundOpacity='1.000' Checked='true' LocalTooltip='[@VideoTextureWeaponTooltip]' Location='76,176' Name='TextureWeapon' ScrollExtent='269,25' Size='269,25' Style='/Buttons.OptionsCheckbox.style' Tooltip='@VideoTextureWeaponTooltip'>@VideoTextureWeapon</Checkbox>
<Checkbox Activated='true' BackgroundOpacity='1.000' Checked='true' LocalTooltip='[@VideoTextureVehicleTooltip]' Location='76,206' Name='TextureVehicle' ScrollExtent='269,25' Size='269,25' Style='/Buttons.OptionsCheckbox.style' Tooltip='@VideoTextureVehicleTooltip'>@VideoTextureVehicle</Checkbox>
<Checkbox Activated='true' BackgroundOpacity='1.000' Checked='true' LocalTooltip='[@VideoTextureObjectTooltip]' Location='76,236' Name='TextureObject' ScrollExtent='269,25' Size='269,25' Style='/Buttons.OptionsCheckbox.style' Tooltip='@VideoTextureObjectTooltip'>@VideoTextureObject</Checkbox>
<Checkbox Activated='true' BackgroundOpacity='1.000' Checked='true' LocalTooltip='[@VideoTextureSoldierTooltip]' Location='76,266' Name='TextureSoldier' ScrollExtent='269,25' Size='269,25' Style='/Buttons.OptionsCheckbox.style' Tooltip='@VideoTextureSoldierTooltip'>@VideoTextureSoldier</Checkbox>
<Checkbox Activated='true' BackgroundOpacity='1.000' Checked='true' LocalTooltip='[@VideoTextureBuildingTooltip]' Location='76,296' Name='TextureBuilding' ScrollExtent='269,25' Size='269,25' Style='/Buttons.OptionsCheckbox.style' Tooltip='@VideoTextureBuildingTooltip'>@VideoTextureBuilding</Checkbox>
<Checkbox Activated='true' BackgroundOpacity='1.000' Checked='true' LocalTooltip='[@VideoTextureBuildingLightmapTooltip]' Location='76,326' Name='TextureBuildingLightmap' ScrollExtent='269,25' Size='269,25' Style='/Buttons.OptionsCheckbox.style' Tooltip='@VideoTextureBuildingLightmapTooltip'>@VideoTextureBuildingLightmap</Checkbox>
<Checkbox Activated='true' BackgroundOpacity='1.000' Checked='true' LocalTooltip='[@VideoTextureFloraTooltip]' Location='412,176' Name='TextureFlora' ScrollExtent='269,25' Size='269,25' Style='/Buttons.OptionsCheckbox.style' Tooltip='@VideoTextureFloraTooltip'>@VideoTextureFlora</Checkbox>
<Checkbox Activated='true' BackgroundOpacity='1.000' Checked='true' LocalTooltip='[@VideoTextureRockTooltip]' Location='412,206' Name='TextureRock' ScrollExtent='269,25' Size='269,25' Style='/Buttons.OptionsCheckbox.style' Tooltip='@VideoTextureRockTooltip'>@VideoTextureRock</Checkbox>
<Checkbox Activated='true' BackgroundOpacity='1.000' Checked='true' LocalTooltip='[@VideoTextureEffectTooltip]' Location='412,236' Name='TextureEffect' ScrollExtent='269,25' Size='269,25' Style='/Buttons.OptionsCheckbox.style' Tooltip='@VideoTextureEffectTooltip'>@VideoTextureEffect</Checkbox>
<Checkbox Activated='true' BackgroundOpacity='1.000' Checked='true' LocalTooltip='[@VideoTextureSampleTooltip]' Location='412,266' Name='TextureSample' ScrollExtent='269,25' Size='269,25' Style='/Buttons.OptionsCheckbox.style' Tooltip='@VideoTextureSampleTooltip'>@VideoTextureSample</Checkbox>
<Checkbox Activated='true' BackgroundOpacity='1.000' Checked='true' LocalTooltip='[@VideoTextureLooseTooltip]' Location='412,296' Name='TextureLoose' ScrollExtent='269,25' Size='269,25' Style='/Buttons.OptionsCheckbox.style' Tooltip='@VideoTextureLooseTooltip'>@VideoTextureLoose</Checkbox>
<Checkbox Activated='true' BackgroundOpacity='1.000' Checked='true' LocalTooltip='[@VideoTextureBridgeTooltip]' Location='412,326' Name='TextureBridge' ScrollExtent='269,25' Size='269,25' Style='/Buttons.OptionsCheckbox.style' Tooltip='@VideoTextureBridgeTooltip'>@VideoTextureBridge</Checkbox>
<Checkbox Activated='true' BackgroundOpacity='1.000' Checked='true' LocalTooltip='[@VideoTextureMapTooltip]' Location='412,356' Name='TextureMap' ScrollExtent='269,25' Size='269,25' Style='/Buttons.OptionsCheckbox.style' Tooltip='@VideoTextureMapTooltip'>@VideoTextureMap</Checkbox>
<Template Name='Row Template' Size='250,20'>\<text font = \'/Fonts.DefaultFont\' location = \'5,-1\' size = \'250,20\'\>
$Name$
\</text\></Template>
</Page>
<Image BackgroundOpacity='1.000' Location='292,34' Name='TabBorderTop2' PackLocation='left,top' PackLocationProp='0292/0001,0034/0001' PackSize='fixed,fixed' PackSizeProp='0002/0003,0002/0003' ScrollExtent='455,2' Size='455,2' Style='TabBorderTopStyle'/>
<Image BackgroundOpacity='1.000' Location='141,34' Name='TabBorderTop1' PackLocation='left,top' PackLocationProp='0141/0001,0034/0001' PackSize='fixed,fixed' PackSizeProp='0002/0003,0002/0003' ScrollExtent='14,2' Size='14,2' Style='TabBorderTopStyle'/>
<ImageStyle Name='TabBorderTopStyle'>
<ImageFrame Source='ui_window_map_tab_border_00' SourceRect='8,0,24,2'/>
</ImageStyle>
<Checkbox BackgroundOpacity='1.000' LocalTooltip='[@VideoGeneralTooltip]' Location='2,5' Name='GeneralTab' OnDisableEffector='DisableEffector' PackLocation='left,top' PackLocationProp='0002/0001,0005/0001' PackSize='fixed,fixed' PackSizeProp='0002/0003,0002/0003' ScrollExtent='140,31' Size='140,31' Style='/Buttons.OptionTab.style' Tooltip='@VideoGeneralTooltip'>@VideoGeneral</Checkbox>
<Checkbox Activated='true' BackgroundOpacity='1.000' Checked='true' LocalTooltip='[@VideoAdvancedTooltip]' Location='152,5' Name='AdvancedTab' PackLocation='left,top' PackLocationProp='0152/0001,0005/0001' PackSize='fixed,fixed' PackSizeProp='0002/0003,0002/0003' ScrollExtent='140,31' Size='140,31' Style='/Buttons.OptionTab.style' Tooltip='@VideoAdvancedTooltip'>@VideoAdvanced</Checkbox>
<Image BackgroundOpacity='1.000' Location='3,35' Name='TabBorder' PackLocation='left,top' PackLocationProp='0003/0001,0035/0001' PackSize='absolute,absolute' PackSizeProp='0012/0001,0038/0001' RStyleDefault='/WindowPanes.BigTabBorder.style' ScrollExtent='746,430' Size='746,430'/>
</Page>
<Page Location='22,69' Name='GeneralOptionsPage' ScrollExtent='758,468' Size='758,468' Visible='false'>
<Template Name='Row Template' Size='250,20'>\<text font = \'/Fonts.DefaultFont\' location = \'5,-1\' size = \'250,20\'\>
$Name$
\</text\></Template>
<Dropdownbox DataSource='/DataSources.OptionsNameDataSource' LocalTooltip='[@OptionsRenderNameTooltip]' Location='202,149' Name='RenderNames' RowTemplate='Row Template' ScrollExtent='250,29' SelectedItemIndex='2' Size='250,29' Style='/Dropdowns.HudPane.style' Tooltip='@OptionsRenderNameTooltip'/>
<Text Font='/Fonts.HudFont1' LocalText='[@OptionsRenderNames]' LocalTooltip='[@OptionsRenderNamesTooltip]' Location='30,152' Name='RenderNamesText' ScrollExtent='162,25' Size='162,25' TextAlignment='Right' TextAlignmentVertical='Center' Tooltip='@OptionsRenderNamesTooltip'>@OptionsRenderNames</Text>
<Checkbox BackgroundOpacity='1.000' LocalTooltip='[@AlwaysRunTooltip]' Location='46,21' Name='AlwaysRunCheck' ScrollExtent='320,23' Size='320,23' Style='/Buttons.OptionsCheckbox.style' Tooltip='@AlwaysRunTooltip'>@AlwaysRun</Checkbox>
<Checkbox Activated='true' BackgroundOpacity='1.000' Checked='true' LocalTooltip='[@ExclamationHelpTooltip]' Location='46,58' Name='ExclamationHelp' ScrollExtent='320,23' Size='320,23' Style='/Buttons.OptionsCheckbox.style' Tooltip='@ExclamationHelpTooltip'>@ExclamationHelp</Checkbox>
<Checkbox Activated='true' BackgroundOpacity='1.000' Checked='true' LocalTooltip='[@HeadBobEnabledTooltip]' Location='46,51' Name='HeadBobEnabledCheck' ScrollExtent='320,23' Size='320,23' Style='/Buttons.OptionsCheckbox.style' Tooltip='@HeadBobEnabledTooltip' Visible='false'>@HeadBobEnabled</Checkbox>
<Checkbox Activated='true' BackgroundOpacity='1.000' Checked='true' LocalTooltip='[@ShowEjectedCasingsTooltip]' Location='46,84' Name='ShowEjectedCasingsCheck' ScrollExtent='320,23' Size='320,23' Style='/Buttons.OptionsCheckbox.style' Tooltip='@ShowEjectedCasingsTooltip' Visible='false'>@ShowEjectedCasings</Checkbox>
<Checkbox BackgroundOpacity='1.000' LocalTooltip='[@RadarAutoTooltip]' Location='46,95' Name='RadarAutoCheck' ScrollExtent='320,23' Size='320,23' Style='/Buttons.OptionsCheckbox.style' Tooltip='@RadarAutoTooltip'>@RadarAuto</Checkbox>
</Page>
<Page Location='19,539' Name='LoadSave' ScrollExtent='759,37' Size='759,37'>
<Button LocalText='[@Default]' LocalTooltip='[@KeymapDefaultTooltip]' Location='264,9' Name='DefaultButton' ScrollExtent='75,20' Size='75,20' Style='/Buttons.TextButton.style' Tooltip='@KeymapDefaultTooltip'>@Default</Button>
<Button LocalText='[@Delete]' LocalTooltip='[@KeymapDeleteTooltip]' Location='178,9' Name='DeleteButton' ScrollExtent='75,20' Size='75,20' Style='/Buttons.TextButton.style' Tooltip='@KeymapDeleteTooltip'>@Delete</Button>
<Button LocalText='[@Load]' LocalTooltip='[@KeymapLoadTooltip]' Location='94,9' Name='LoadButton' ScrollExtent='75,20' Size='75,20' Style='/Buttons.TextButton.style' Tooltip='@KeymapLoadTooltip'>@Load</Button>
<Button LocalText='[@Save]' LocalTooltip='[@KeymapSaveTooltip]' Location='12,9' Name='SaveButton' ScrollExtent='75,20' Size='75,20' Style='/Buttons.TextButton.style' Tooltip='@KeymapSaveTooltip'>@Save</Button>
<Textbox BackgroundColor='#DDDDDD' BackgroundOpacity='0.475' LocalTooltip='[@OptionsNameTooltip]' Location='538,6' MaxLength='15' Name='ConfigurationName' PackLocation='right,bottom' PackLocationProp='-221/0001,-031/0001' PackSize='fixed,fixed' PackSizeProp='0002/0003,0002/0003' ScrollExtent='215,25' Size='215,25' Style='/ConsoleTextbox.ShortStyle' Tooltip='@OptionsNameTooltip'></Textbox>
<Text Font='/Fonts.HudFont1' LocalText='[@KeymapConfiguration]' Location='392,7' Name='ConfigurationText' ScrollExtent='143,25' Size='143,25' TextAlignment='Right' TextAlignmentVertical='Center'>@KeymapConfiguration</Text>
<Image BackgroundOpacity='1.000' Name='ButtonBorder' PackSize='1,1' PackSizeProp='0002/0003,0002/0003' RStyleDefault='/WindowPanes.ButtonBorder.style' ScrollExtent='759,37' Size='759,37'/>
</Page>
<Rectangle AbsorbsInput='false' Color='#00F2C9' Location='20,69' Name='AcquiredRect' Opacity='0.750' ScrollExtent='758,468' Size='758,468'/>
<Button LocalText='[@Cancel]' LocalTooltip='[@HelpTooltip]' Location='69,9' Name='HelpButton' PackLocation='right,top' PackLocationProp='-731/0001,0009/0001' ScrollExtent='16,16' Size='16,16' Style='/Buttons.WindowHelp.style' Tooltip='@HelpTooltip'>@Cancel</Button>
<Checkbox Activated='true' BackgroundOpacity='1.000' Checked='true' Cursor='s' LocalTooltip='[@VideoOptionTooltip]' Location='106,41' Name='VideoCheckbox' Radio='true' ScrollExtent='75,20' Size='75,20' Style='/Buttons.TextButton.checkstyle' Tooltip='@VideoOptionTooltip'>@VideoOptionTab</Checkbox>
<Checkbox BackgroundOpacity='1.000' Cursor='s' LocalTooltip='[@KeymapOptionTooltip]' Location='25,41' Name='KeymapCheckbox' Radio='true' ScrollExtent='75,20' Size='75,20' Style='/Buttons.TextButton.checkstyle' Tooltip='@KeymapOptionTooltip'>@KeymapOptionTab</Checkbox>
<Checkbox BackgroundOpacity='1.000' Cursor='s' LocalTooltip='[@SoundOptionTooltip]' Location='185,41' Name='SoundCheckbox' Radio='true' ScrollExtent='75,20' Size='75,20' Style='/Buttons.TextButton.checkstyle' Tooltip='@SoundOptionTooltip'>@SoundOptionTab</Checkbox>
<Checkbox BackgroundOpacity='1.000' Cursor='s' LocalTooltip='[@OtherOptionTooltip]' Location='266,41' Name='OptionsCheckbox' Radio='true' ScrollExtent='75,20' Size='75,20' Style='/Buttons.TextButton.checkstyle' Tooltip='@OtherOptionTooltip'>@GameOptionTab</Checkbox>
<CheckboxStyle CheckboxSize='100,100' Name='checkstyle' NormalTextStyle='/Fonts.HudFont1'/>
<Image Name='Border' ScrollExtent='1035,771' Size='1035,771' Stretch='false' Style='ShellOptionsBackground' Visible='false'/>
<Button IsCancelButton='true' LocalText='[@Cancel]' LocalTooltip='[@CloseTooltip]' Location='708,9' Name='CancelButton' PackLocation='right,top' PackLocationProp='-092/0001,0009/0001' ScrollExtent='16,16' Size='16,16' Style='/Buttons.WindowClose.style' Tooltip='@CloseTooltip'>@Cancel</Button>
<Image AbsorbsInput='false' BackgroundOpacity='1.000' Location='40,0' Name='Title' PackSize='absolute,fixed' PackSizeProp='0083/0001,0002/0003' RStyleActivated='/WindowPanes.TitleBarFocus.style' RStyleDefault='/WindowPanes.TitleBarNoFocus.style' ScrollExtent='717,32' Size='717,32'/>
<Image AbsorbsInput='false' BackgroundOpacity='1.000' Location='0,15' Name='Background' PackSize='1,absolute' PackSizeProp='0002/0003,0011/0001' RStyleDefault='/WindowPanes.BigBackground.style' ScrollExtent='800,589' Size='800,589' Stretch='false' Visible='false'/>
<Image AbsorbsInput='false' BackgroundOpacity='1.000' Location='9,17' Name='FrontendBackground' PackSize='fixed,fixed' PackSizeProp='0002/0003,0002/0003' RStyleDefault='/Frontend.OpaqueBox.style' ScrollExtent='782,566' Size='782,566' Stretch='false'/>
</Page>
